### ISSUE TITLE
Spell organization idea

### ISSUE THREAD

**Issue by Crypton33** [otland/forgottenserver#1004]
Hello,
I've got the idea about organizing spells in TFS.
Right now we have only **spells.xml** file which contains informations about all spells, that's ~750 lines.

What we could do?
We could split that file to smaller files:
- **monster.xml** - monster spells
- **attack.xml** - attack spells / runes
- **healing.xml** - healing spells / runes
- **support.xml** - support spells / runes
- **conjure.xml** - conjure spells
- **other.xml** - other spells, for example: house commands (by the way - shouldn't they be in talkactions or command files?)

One of the advantages of that organization is that we won't have to set group for spells in XML files.
Spells loaded from **attack.xml** wil automatically be in the the **attack** spell group, etc.

What do you think about it?
##

**Comment by marmichalski** [comment]
I can't seem to see any benefits in that. @EPuncker could this be closed?
