### ISSUE TITLE
Total weight of a container

### ISSUE THREAD

**Issue by Sornii** [otland/forgottenserver#1009]
Hello,

I'm a beginner on this project, but I tried to get the total weight of a container via lua script and then I'd need to do all the recursive thing and etc since I didnt found a easy lua script to do that.

So in the source code I saw something that showed me the functions that container has, and it is getSize(), getCapacity(), getEmptySlots(), which I assume this is pretty confusing, since getCapacity() shouldnt be named this way (my personal thoughts).

But the point of all this is that we haven't a function to get the total weight in oz from a container. But the class Container has a function getWeight(), why this is not provided to lua scripts?

**Comment by marksamman** [comment]
Item.getWeight was added in #1062, it should return the total weight for containers.
