### ISSUE TITLE
Destroying Containers (chests, boxes, barrels etc)

### ISSUE THREAD

**Issue by EvulMastah** [otland/forgottenserver#1014]
Items inside containers should be moved on the trash (ground) when parent container is destroyed. If container has a container inside, this container should also be destroyed and items moved on the ground. It should not be possible to destroy containers inside containers, only the ones on the ground (Sorry, not possible.). This is not only lua issue, when monster steps on container the items inside should also be moved on the ground and there should be trash created, now they just disappear.

**Comment by marksamman** [comment]
Implemented in 58fb9c5c106cca0285ec270fa107a52abc71176a.
