### ISSUE TITLE
Buying items with charge(like protection amulet) from the npc shop(eremo) bug

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1079]
Its comes with 1 charges when you buy it from the npc.

http://prntscr.com/5bzq3b

It only fix if you set the protection amulet subtype as 250 in shop_buyable on eremo.xml

I cannot confirm, a player send it to me:

You see a protection amulet (protection physical +6%) that has 0 charges left.
It weighs 5.50 oz. 

Quick fix on modules.lua(ShopModule:parseBuyable(data)):

			if ItemType(itemid):getCharges() > 0 then
				subType = ItemType(itemid):getCharges()
			end

**Comment by TwistedScorpio** [comment]
I can reproduce this, but basically using shop_buyables in xml file, instead of directly specifying the charges in the LUA file.
