### ISSUE TITLE
Drop OTB ?

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#1085]
Why we still use OTB ?!?!
It's a pain in the ass update it, when we could just use .dat and in items.xml set clientId corresponding to the wanted item Id !!!

So that's what I porpouse, also I want know if there is a real reason to keep using it.
The only thing I thought is because the map editor uses it.

**Comment by G4BB3R** [comment]
Why not using a JSON or XML file format ?
The binary format is really bad :-1:

**Comment by ranisalt** [comment]
@G4BB3R because binary formats are significantly smaller. Remember when maps changed from XML to binary and their sizes shrunk by more than 90%.
