### ISSUE TITLE
Bug when kicked for exceeding packet per second limit

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#1101]
If the player have vocation = 0 and than in some script i do this:

```
  Player(cid):setVocation(Vocation(4))
```

When you get kicked for exceeding packet per second limit, your new vocation will not be saved, instead you will be with vocation 0 when you login again.

**Comment by ninjalulz** [comment]
I can't reproduce this.

![](https://i.imgur.com/W6AB4Ic.gif)

**Comment by DaneraOts** [comment]
maxPacketsPerSecond = 25

 

cambiar a 900
