### ISSUE TITLE
Bless Drop

### ISSUE THREAD

**Issue by walissonsantos** [otland/forgottenserver#1103]
Hello, this bug is a strange and very important case, it existed in version 0.4 / 1.0 / 1.1

I'll try to explain ...

The bug is happens on rare occasions, the player is with all 6 blessing however when he dies sometimes loses his backpack and items.

Usually it dies but lose nothing, but in very rare case he loses.

I hope you understand.

**Comment by kanohn** [comment]
@marksamman 

really this bug exists, currently have an online server with 300+ players, I'm using the latest tfs 1.1, and many players are complaining saying that "to bless is bug, sometimes protect and sometimes not," a player who had already donated to much and took it more seriously.

<img src="http://s7.postimg.org/fbjpwy80b/FOTO_1.png"/>
<img src="http://s30.postimg.org/x2n7fmlxt/FOTO_2.png"/>

**Comment by ranisalt** [comment]
Can you be more specific to when it happens? Detail as much as possible the character conditions, how it was killed, what were the previous kills, etc.

**Comment by WibbenZ** [comment]
Ppl have asked me before abt this, also noticed it myself once or twice.
No pattern to follow, thats the reason no one has cares about it - since you really need luck to find it.

Atlest I havent found a commond thread, maybe someone has? :p

**Comment by kanohn** [comment]
the player said it happens when he dies to player, as pictured himself tested killing the character himself a few times, and the fifth time the loot dropped with bless. I have no idea what causes this, I have a suspicion that may be the bless of PvP, which protects other bless then dying again can drop (just a guess, I'll be testing this)

**Comment by kanohn** [comment]
@marksamman 

This will be ignored?

**Comment by marksamman** [comment]
Unless you can provide steps to reproduce, yes, it will be ignored since I have no idea how to go about fixing this if I can't make it happen.
