### ISSUE TITLE
PVP PZ is not leaving

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1109]
Some players are killing PKs but the pz is not going away in the right delay(pzLocked)

**Comment by rowaraujo** [comment]
I can confirm this bug. My solution was to reduce the configuration time in pzLocked: 60000 -> 30 * 1000.

**Comment by marksamman** [comment]
It doesn't make any sense to me that it would work with pzLocked 30000 but not 60000. Can anyone else confirm that PZ lock doesn't disappear with the config value set to 60000, but that it does with 30000?

**Comment by ninjalulz** [comment]
It does disappear after 60 seconds.

**Comment by M4GO** [comment]
sry for open, but i have this bug

**Comment by DSpeichert** [comment]
@M4GO Unless you add more information, nobody will be able to check that.
You should probably open a new bug report with detailed reproduction steps. Make sure they work on the default data pack.
