### ISSUE TITLE
removeAmmoWhenUsingDistanceWeapon don't work

### ISSUE THREAD

**Issue by rodrigoslayertech** [otland/forgottenserver#1125]
The setting "removeAmmoWhenUsingDistanceWeapon" is not working.
Even when I set to "no" also removes the ammunition.

**Comment by kosicki123** [comment]
I'm having a similar error about breakChance and ammoAction. As I read above, I know you made changes into source about that. The error says:
[Warning - Items::parseItemNode] Unknown key value: breakChance
[Warning - Items::parseItemNode] Unknown key value: ammoAction
The error is repeated multiple times. 
Did you move both to weapons.xml?
I'll have to update my weapons.xml to support that, right?

**Comment by marksamman** [comment]
Yes.
