### ISSUE TITLE
Weapons get destroid with use

### ISSUE THREAD

**Issue by Fanges** [otland/forgottenserver#1132]
After updating with the latest TFS version (compile) the weapons get destroyed after use.

**Comment by Codinablack** [comment]
I can't reproduce this, could you give more information? Regular (no script or movements attached) weapons I can use for attack/melee all day without them breaking, also if I try to use the item, it's not possible.

**Comment by ninjalulz** [comment]
![](http://i.imgur.com/zS1M7ud.gif)
I apologize once again for the poor quality. I do not have any script attached to giant sword.
