### ISSUE TITLE
OS X Crash

### ISSUE THREAD

**Issue by Nu77** [otland/forgottenserver#1133]
When startup the server:
```bash
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
Abort trap: 6
```

**Comment by Nu77** [comment]
@marksamman 
The crash will happen only if you don't have the right connection settings to database, i configured my webserver and now it's running like a charm.
I think it could be the non-blocking sql changes, but don't know if i'm right.

**Comment by diath** [comment]
I can confirm that this also happens on Linux, when the specified database settings are incorrect the server segfaults on startup.
