### ISSUE TITLE
Server sometimes crashes when saved

### ISSUE THREAD

**Issue by rowaraujo** [otland/forgottenserver#1134]
Rarely when my server saves using saveServer(), it crashes. I need to use cleanmap() before using the saveServer()?
I'm using serverSave() without cleanmap()... Is there a problem?

I configured to use the saveServer() command every 30 minutes.

I have 10 to 30 players online...

**Comment by rowaraujo** [comment]
@marksamman I did not make any changes in the source.
I have no idea why this is happening.
I am using the 32-bits version Release in Windows 7 Server.
My version of MySQL is 64 bits and I'm thinking that's it...

**Comment by marksamman** [comment]
It could be that your server is running out of memory, 32-bit applications can't allocate more than 2GB RAM. We can't really tell what's wrong without a stack trace, which is why this issue will be marked as invalid until you can provide more information.

**Comment by rowaraujo** [comment]
Ok.
I updated to the latest version now.
Will enable the debugger and occur again I send the stack trace.
Thank you for your attention.

**Comment by rowaraujo** [comment]
I transfer my server to CentOS and now believe it will no longer hang.
