### ISSUE TITLE
Walkthrough Everything Ctrl + Arrow keys

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1136]
Hello,

I have made small code, to easily walkthrough walls, creatures and etc... On a fast phase.

Why is the useful? Well i found it useful, to get to places fast.

http://pastebin.com/Jp6z2AVg

If you would accept it, ill send then pull request or you can do so.

**Comment by EvulMastah** [comment]
When holding keys down, you will get disconnected for exceeding packet-per-second limit.

**Comment by PrinterLUA** [comment]
Well i noticed that, i may should use doMoveCreature? I would like have @marksamman input ^^

**Comment by marksamman** [comment]
I don't think that matters if your client floods the server with packets when holding down Ctrl + any arrow key regardless of what Lua function you call in the server. Even if it didn't, Ctrl + arrow key is meant to turn and nothing else. I could consider something like this if it could be toggled through a talk action or UI control in OTClient, and was off by default.

**Comment by PrinterLUA** [comment]
Toggled? You mean activated by command?

**Comment by marksamman** [comment]
Yes.
