### ISSUE TITLE
Help after Compiling on Ubuntu

### ISSUE THREAD

**Issue by MooMage** [otland/forgottenserver#1137]
Hello,
I am trying to create an Otserver using a virtual machine with Ubuntu Server installed on it.
My intention is to run theforgottenserver on a 32bit Ubuntu Server in an old laptop.
I followed this tutorial: https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu
In another attempts I left the forgottenserver online, but I couldn't connect to it, cause account or password was wrong, that's why I think my problems begin at the momment of cofiguration and installation of mysql.
I need some help cause I facing a lot of difficulty with it and can't find something useful for my situation in the internet. If I get all working fine, I can make a step by step tutorial and post here.
I would be grateful for some help!

THANKS!

Here are the images of what I have done:

![1](https://cloud.githubusercontent.com/assets/10466649/5692661/a8a0a17e-98e5-11e4-9bb0-effa2f3e4e99.JPG)
![2](https://cloud.githubusercontent.com/assets/10466649/5692663/a8b41e8e-98e5-11e4-917e-0740e212427a.JPG)
![3](https://cloud.githubusercontent.com/assets/10466649/5692662/a8ad9d84-98e5-11e4-86d6-39c74691e445.JPG)
![4](https://cloud.githubusercontent.com/assets/10466649/5692665/a8bb8d22-98e5-11e4-9ba0-795f5cd2cc10.JPG)
![5](https://cloud.githubusercontent.com/assets/10466649/5692664/a8b517a8-98e5-11e4-90c0-997670d35af6.JPG)
![6](https://cloud.githubusercontent.com/assets/10466649/5692666/a8bf01fa-98e5-11e4-81ad-a66cbba17b28.JPG)

Had to copie 'tfs' to /forgottenserver - is this right?

![7](https://cloud.githubusercontent.com/assets/10466649/5692667/a8c42ee6-98e5-11e4-83d5-39e07162aaf1.JPG)

**Comment by Nu77** [comment]
You will need a proper database connection, install MySQL typing in terminal: 
```bash
sudo apt-get install mysql
```
after configuring it create a database called forgottenserver and import the schema.sql to your database, configure it in config.lua and run again.

**Comment by MooMage** [comment]
Great!! That worked!
Thanks a lot...
