### ISSUE TITLE
Help after Configuring mysql on Ubuntu and running it

### ISSUE THREAD

**Issue by MooMage** [otland/forgottenserver#1139]
First of all, I would thanks for the support!
I got Forgottenserver working perfectly on my Ubuntu server, but had problemns while creating an account, the account manager didn't work, it appeared a message of account invalid or password invalid.. After hours searching the net, found a tutorial to create a character manually using sql commands, had to study abou hash the password into 'sha1' and more...! That's what I have done. So I've entered the game, but realized that wasn't as I espected. We have only the base and we must create the rest and that was not what I intended.
I got sad :(
But I read about PrinterLUA/FORGOTTENSERVER-ORTS, that there were quests, hunts and a lot more like real Tibia, then tryied it.
Did all step again, but this time I had to compile using 'gcc', spend more some hours and couldn't do it.
Well, I got the files of Forgottenserver and made a copy of  data files from the PrinterLUA/FORGOTTENSERVER-ORTS. That worked! lol? (I am not sure if this is a correct form of doing it, but this is the only way I could compile the server)
I had only one warning, but it started tho.
![1](https://cloud.githubusercontent.com/assets/10466649/5697043/53b30444-99cc-11e4-8efb-677fa740fa17.JPG)

After installation the account manager still didn't work... :(
Is this right? Do I have to create all the characters using sql commands?
Do you have any suggestion?
Here you are what happens to me...

![2](https://cloud.githubusercontent.com/assets/10466649/5697051/cced9914-99cc-11e4-9e40-bfcf173cd214.JPG)

My config.lua

-- Combat settings
-- NOTE: valid values for worldType are: "pvp", "no-pvp" and "pvp-enforced"
worldType = "pvp"
hotkeyAimbotEnabled = "yes"
protectionLevel = 1
killsToRedSkull = 3
killsToBlackSkull = 6
pzLocked = 60000
removeChargesFromRunes = "yes"
timeToDecreaseFrags = 24 * 60 * 60 * 1000
whiteSkullTime = 15 * 60 * 1000
stairJumpExhaustion = 2000
experienceByKillingPlayers = "no"
expFromPlayersLevelRange = 75
noDamageToSameLookfeet = "no"
-- Connection Config
-- NOTE: maxPlayers set to 0 means no limit
ip = "10.1.1.20"
bindOnlyGlobalAddress = "no"
loginProtocolPort = 7171
gameProtocolPort = 7172
statusProtocolPort = 7171
maxPlayers = 0
motd = "Welcome to The Forgotten Server!"
onePlayerOnlinePerAccount = "yes"
allowClones = "no"
serverName = "Forgotten"
statusTimeout = 5000
replaceKickOnLogin = "yes"
maxPacketsPerSecond = 25
-- Deaths
-- NOTE: Leave deathLosePercent as -1 if you want to use the default
-- death penalty formula. For the old formula, set it to 10. For
-- no skill/experience loss, set it to 0.
deathLosePercent = -1
-- Houses
-- NOTE: set housePriceEachSQM to -1 to disable the ingame buy house functionality
housePriceEachSQM = 1000
houseRentPeriod = "never"
-- Item Usage
timeBetweenActions = 200
timeBetweenExActions = 1000
-- Map
-- NOTE: set mapName WITHOUT .otbm at the end
mapName = "forgotten"
mapAuthor = "Komic"
-- Market
marketOfferDuration = 30 * 24 * 60 * 60
premiumToCreateMarketOffer = "yes"
checkExpiredMarketOffersEachMinutes = 60
maxMarketOffersAtATimePerPlayer = 100
-- MySQL
mysqlHost = "127.0.0.1"
mysqlUser = "root"
mysqlPass = "root"
mysqlDatabase = "forgottenserver"
mysqlPort = 3306
mysqlSock = ""
-- Misc.
allowChangeOutfit = "yes"
freePremium = "no"
kickIdlePlayerAfterMinutes = 15
maxMessageBuffer = 4
emoteSpells = "no"
classicEquipmentSlots = "no"
-- Rates
-- NOTE: rateExp is not used if you have enabled stages in data/XML/stages.xml
rateExp = 5
rateSkill = 3
rateLoot = 2
rateMagic = 3
rateSpawn = 1
-- Monsters
deSpawnRange = 2
deSpawnRadius = 50
-- Stamina
staminaSystem = "yes"
-- Scripts
warnUnsafeScripts = "no"
convertUnsafeScripts = "no"
-- Startup
-- NOTE: defaultPriority only works on Windows and sets process priority.
defaultPriority = "high"
startupDatabaseOptimization = "no"
-- Status server information
ownerName = ""
ownerEmail = ""
url = "http://otland.net/"
location = "Sweden"

**Comment by dragaoart** [comment]
There is no account manager in this TFS distro. You have to install a web server and a AAC website to make acc creation available. I suggest you install a LAMP stack and Znote AAC.

**Comment by marksamman** [comment]
Yes. You have to create accounts and characters using SQL commands if you don't have any other interface to do so. The server with the default datapack does not provide any interface for that. The following SQL queries may or may not work:
```sql
INSERT INTO `accounts` (`name`, `password`) VALUES ('moomage', SHA1('my_password'));
INSERT INTO `players` (`name`, `account_id`, `town_id`) VALUES ('Moo Mage', 1, 1);
```

**Comment by MooMage** [comment]
@dragaoart 
Thanks for the suggestions! I am going to install as soon as possible!

@marksamman 
I got that! Created some characters and was possible to have fun for a bit!
Now I am studying on how to put the server online using no-ip.
After online, I gonna install the packages suggested by dragaoart.
