### ISSUE TITLE
Networkmessages addItem client crash

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1142]
When i'm using this item and create a item toPosition and creating another item over that item. It cause client crash. Here is the code:
http://pastebin.com/yVMxDfEt

**Comment by kornholi** [comment]
You are sending raw data to the client, what do you expect? What are you trying to do?

**Comment by marksamman** [comment]
This isn't an issue in the server regardless, if your client crashes that's because you sent a bad packet and the client handles it by crashing. In this case, you're probably sending the wrong stack position.
