### ISSUE TITLE
error in Compiling - debian

### ISSUE THREAD

**Issue by Crock-Linux** [otland/forgottenserver#1144]
root@debian:/home/ot/forgottenserver/build# make
[  1%] Building CXX object CMakeFiles/tfs.dir/src/actions.cpp.o
In file included from /home/ot/forgottenserver/src/actions.cpp:22:0:
/home/ot/forgottenserver/src/actions.h:87:3: error: looser throw specifier for ‘virtual Actions::~Actions()’
In file included from /home/ot/forgottenserver/src/actions.h:23:0,
                 from /home/ot/forgottenserver/src/actions.cpp:22:
/home/ot/forgottenserver/src/baseevents.h:56:11: error:   overriding ‘virtual BaseEvents::~BaseEvents() noexcept (true)’
In file included from /home/ot/forgottenserver/src/creature.h:29:0,
                 from /home/ot/forgottenserver/src/player.h:23,
                 from /home/ot/forgottenserver/src/game.h:31,
                 from /home/ot/forgottenserver/src/actions.cpp:27:
/home/ot/forgottenserver/src/creatureevent.h:49:3: error: looser throw specifier for ‘virtual CreatureEvents::~CreatureEvents()’
In file included from /home/ot/forgottenserver/src/actions.h:23:0,
                 from /home/ot/forgottenserver/src/actions.cpp:22:
/home/ot/forgottenserver/src/baseevents.h:56:11: error:   overriding ‘virtual BaseEvents::~BaseEvents() noexcept (true)’
In file included from /home/ot/forgottenserver/src/spells.h:26:0,
                 from /home/ot/forgottenserver/src/actions.cpp:32:
/home/ot/forgottenserver/src/talkaction.h:39:3: error: looser throw specifier for ‘virtual TalkActions::~TalkActions()’
In file included from /home/ot/forgottenserver/src/actions.h:23:0,
                 from /home/ot/forgottenserver/src/actions.cpp:22:
/home/ot/forgottenserver/src/baseevents.h:56:11: error:   overriding ‘virtual BaseEvents::~BaseEvents() noexcept (true)’
In file included from /home/ot/forgottenserver/src/actions.cpp:32:0:
/home/ot/forgottenserver/src/spells.h:40:3: error: looser throw specifier for ‘virtual Spells::~Spells()’
In file included from /home/ot/forgottenserver/src/actions.h:23:0,
                 from /home/ot/forgottenserver/src/actions.cpp:22:
/home/ot/forgottenserver/src/baseevents.h:56:11: error:   overriding ‘virtual BaseEvents::~BaseEvents() noexcept (true)’
In file included from /home/ot/forgottenserver/src/actions.cpp:32:0:
/home/ot/forgottenserver/src/spells.h:91:3: error: looser throw specifier for ‘virtual CombatSpell::~CombatSpell()’
In file included from /home/ot/forgottenserver/src/actions.h:23:0,
                 from /home/ot/forgottenserver/src/actions.cpp:22:
/home/ot/forgottenserver/src/baseevents.h:30:11: error:   overriding ‘virtual Event::~Event() noexcept (true)’
make[2]: *** [CMakeFiles/tfs.dir/src/actions.cpp.o] Error 1
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2

**Comment by marksamman** [comment]
https://github.com/otland/forgottenserver/pull/1140#issuecomment-69526922
