### ISSUE TITLE
Split login and game server

### ISSUE THREAD

**Issue by Nu77** [otland/forgottenserver#1145]
Splitting the login server from game server is a good thing for achieving scalability and security, user authentication can be done without knowing anything from game logic.
Let the login server handle the user authentication and send for the game server which will handle the game logic, i think this is a good model which tfs should follow.
This also will implement the "Multi World" feature, which is a missing thing in TFS 1.0.
What you guys think about it ?

**Comment by marksamman** [comment]
It will not be split. If you don't want to use it, pick an arbitrary port for the login server and firewall it. It's up to you how you want to set up your infrastructure. I don't see what's stopping you if you wish to run your login server separately, you would only complicate matters for people who don't share your concern about scalability and security by splitting it. You would also have a problem serving the status protocol from the login server port if your login server doesn't share memory with the game server.

With that said, we may eventually write a stand-alone login server, but there are no plans of removing the built-in login server from this project.

**Comment by Nu77** [comment]
@marksamman what the problem with status protocol if login/game server don't share the memory ?
