### ISSUE TITLE
Character � wrong encode

### ISSUE THREAD

**Issue by novasdream** [otland/forgottenserver#1146]
in item 8844,9998

**Comment by marksamman** [comment]
Please elaborate.

**Comment by novasdream** [comment]
Check in item.xml

https://raw.githubusercontent.com/otland/forgottenserver/master/data/items/items.xml

Item id 8844 and item 9998 

check item name.

**Comment by marksamman** [comment]
That is because GitHub serves the file with charset=utf-8 header, which makes your web browser interpret the data as utf-8. items.xml is encoded using iso-8859-1.
