### ISSUE TITLE
Error when compiling TFS

### ISSUE THREAD

**Issue by korch1337** [otland/forgottenserver#1148]
Hey I have a problem when compiling TFS from https://github.com/otland/forgottenserver.git.
It works fine to the last step where I get alot of errors.. I have followed the exact steps from: https://github.com/otland/forgottenserver/wiki/Compiling-on-Debian-GNU-Linux
My server is running on Debian 7 64x.

Here is the log:

"Scanning dependencies of target tfs
[  1%] Building CXX object CMakeFiles/tfs.dir/src/actions.cpp.o
In file included from /root/forgottenserver/src/actions.cpp:22:0:
/root/forgottenserver/src/actions.h:87:3: error: looser throw specifier for ‘virtual Actions::~Actions()’
In file included from /root/forgottenserver/src/actions.h:23:0,
                 from /root/forgottenserver/src/actions.cpp:22:
/root/forgottenserver/src/baseevents.h:56:11: error:   overriding ‘virtual BaseEvents::~BaseEvents() noexcept (true)’
In file included from /root/forgottenserver/src/creature.h:29:0,
                 from /root/forgottenserver/src/player.h:23,
                 from /root/forgottenserver/src/game.h:31,
                 from /root/forgottenserver/src/actions.cpp:27:
/root/forgottenserver/src/creatureevent.h:49:3: error: looser throw specifier for ‘virtual CreatureEvents::~CreatureEvents()’
In file included from /root/forgottenserver/src/actions.h:23:0,
                 from /root/forgottenserver/src/actions.cpp:22:
/root/forgottenserver/src/baseevents.h:56:11: error:   overriding ‘virtual BaseEvents::~BaseEvents() noexcept (true)’
In file included from /root/forgottenserver/src/spells.h:26:0,
                 from /root/forgottenserver/src/actions.cpp:32:
/root/forgottenserver/src/talkaction.h:39:3: error: looser throw specifier for ‘virtual TalkActions::~TalkActions()’
In file included from /root/forgottenserver/src/actions.h:23:0,
                 from /root/forgottenserver/src/actions.cpp:22:
/root/forgottenserver/src/baseevents.h:56:11: error:   overriding ‘virtual BaseEvents::~BaseEvents() noexcept (true)’
In file included from /root/forgottenserver/src/actions.cpp:32:0:
/root/forgottenserver/src/spells.h:40:3: error: looser throw specifier for ‘virtual Spells::~Spells()’
In file included from /root/forgottenserver/src/actions.h:23:0,
                 from /root/forgottenserver/src/actions.cpp:22:
/root/forgottenserver/src/baseevents.h:56:11: error:   overriding ‘virtual BaseEvents::~BaseEvents() noexcept (true)’
In file included from /root/forgottenserver/src/actions.cpp:32:0:
/root/forgottenserver/src/spells.h:91:3: error: looser throw specifier for ‘virtual CombatSpell::~CombatSpell()’
In file included from /root/forgottenserver/src/actions.h:23:0,
                 from /root/forgottenserver/src/actions.cpp:22:
/root/forgottenserver/src/baseevents.h:30:11: error:   overriding ‘virtual Event::~Event() noexcept (true)’
make[2]: *** [CMakeFiles/tfs.dir/src/actions.cpp.o] Error 1
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2"

Any help will be appreciated :)

**Comment by korykora** [comment]
Mark answer this question two times
https://github.com/otland/forgottenserver/issues/1140
