### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by korch1337** [otland/forgottenserver#1149]
I downloaded TFS 1.0 source since im running my system on debian 7 wheezy with gcc version 4.7.2. Im getting an error when trying to create the build files with Cmake. For some reason I didnt get the same error when building the file for TFS 1.1 which I cant use.. here is the log:

CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineSystem.cmake:160 (FILE):
  file attempted to write a file:
  /root/forgottenserver-1.0/CMakeFiles/CMakeOutput.log into a source
  directory.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file:/root/forgottenserver-1.0/CMakeFiles/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file:/root/forgottenserver-1.0/CMakeFiles/CMakeCXXCompiler.cmake
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

Im a noob and I need help, ty :)

**Comment by marksamman** [comment]
Which commands did you use? From which directory did you run cmake?

Please include your entire shell output from git clone up until that error.

**Comment by korch1337** [comment]
to get the nessescary libraries I used:
apt-get install git cmake build-essential liblua5.2-dev libgmp3-dev libmysqlclient-dev libboost-system-dev
I downloaded the TFSv1.0 tar.gz source and extracted it using tar -xvf.
Then I went into the forgotten-v1.0 folder and did:
mkdir build && cd build
cmake ..
Thats when I get the error.
