### ISSUE TITLE
Compiling 10.71 succeeded but login failed.

### ISSUE THREAD

**Issue by kosicki123** [otland/forgottenserver#1151]
Hi, I tried to compile tfs on 10.71 and everything runs fine. Even the server starts fine.
The problem is when I try to run the client, if I login with 10.53, it says that only 10.71 is allowed, which means everything is working fine. When I login with 10.71, it simply throws me an error as it should do when my server is offline.
I've changed definitions.h to change the protocol and also added at itemloader.h the clientversion to run new items otb.
Can somebody help me about why this is problem is happen? 
If I compile to anything until 10.53, everything runs fine.

Thanks!

**Comment by TheSumm** [comment]
I doubt that you made all the changes required for the official 10.71 protocol.
Does logging in with real client work?

**Comment by kosicki123** [comment]
Sorry, I'm not expert like you guys. I don't want to make all the changes that 10.71 has. I just want to make it work, login into the game...
I'm using the real client, it works if I try under <10.53. 
The problem is when I try 10.71~10.72.

I read many things when people change the protocol and I followed the same steps, it works on 10.53, I want to understand why not 10.71, what I'm doing wrong, to learn!

Thanks for your time

**Comment by TheSumm** [comment]
You should probably wait for the official release so you can work on stable server.
Otherwise you could check the Otclient repository to learn more about the protocol and figure out which parts you need.

**Comment by kosicki123** [comment]
Ok, I'll try that by now, but if someone else knows how to solve this problem, please post here!

**Comment by marksamman** [comment]
It isn't a problem with code in this repository, it's a problem with your own modifications, which doesn't belong to this issue tracker. The server supports protocol version 10.41 and nothing else. It will be updated by the time when 1.1 is closer to be released. There is already an issue tracking this matter: https://github.com/otland/forgottenserver/issues/887

**Comment by kosicki123** [comment]
Thanks for directing me! Sorry.
