### ISSUE TITLE
Help - How to put server online?

### ISSUE THREAD

**Issue by MooMage** [otland/forgottenserver#1152]
Hello!
After my last two issues(#1137, #1139), now I am having problems on leaving the otserver online for other people access.
Well, I am trying to create an Otserver in Ubuntu Server using a Virtual Machine in my computer.
All is running perfect, but I can't access the game outside my local network.
If I configure it to access locally, I can play it perfectly, but can't allow my friends to log in the game.
To do so, I installed No-ip and followed their tutorial.
I opened the doors of my router.
But I get 'Error: Connection refused. (10061)'

I need help on how proceed or what to do.
Can someone help me?

Thanks!

![1](https://cloud.githubusercontent.com/assets/10466649/5793668/a61d9a48-9f33-11e4-9451-4c15054b255e.JPG)

![2](https://cloud.githubusercontent.com/assets/10466649/5793669/afab370a-9f33-11e4-858c-6ecea5b85f76.JPG)

![3](https://cloud.githubusercontent.com/assets/10466649/5793670/b4f05f42-9f33-11e4-9b55-13a3f4e8a164.JPG)

![4](https://cloud.githubusercontent.com/assets/10466649/5793671/b79571a6-9f33-11e4-90c1-cd1aec68bea5.JPG)

![5](https://cloud.githubusercontent.com/assets/10466649/5793672/bb9e4e3a-9f33-11e4-866c-a697b25b6a17.JPG)

![6](https://cloud.githubusercontent.com/assets/10466649/5793673/bd26791c-9f33-11e4-853f-a875aa690c4a.JPG)

![7](https://cloud.githubusercontent.com/assets/10466649/5793674/beac0e96-9f33-11e4-92d8-978beef00656.JPG)

**Comment by marksamman** [comment]
This doesn't sound like an issue with our codebase, but a problem with your router/no-ip configuration.
Please use the support forum on OTLand for support matters: http://otland.net/forums/support.16/

**Comment by MooMage** [comment]
Thanks. Used to read lots of threads in otland forum and none of them fit to me. But I gonna create an thread there. Thanks for the support!

**Comment by MooMage** [comment]
If someone is having the same problem, here are the thread I opened and I am tryng to solve.
Thanks!
http://otland.net/threads/help-how-to-put-server-online.227419/
