### ISSUE TITLE
Crash client after the recent changes to the code

### ISSUE THREAD

**Issue by RestlesPL** [otland/forgottenserver#1156]
Please see
http://otland.net/threads/10-41-crash-recent-amendments.227462/
and
https://www.youtube.com/watch?v=PIrMMt1_YWE

**Comment by RestlesPL** [comment]
When this will be fixed?

**Comment by TheSumm** [comment]
If you know the exact commit after which this started happening, it would be good to post it and would probably speed the process up.

**Comment by jollejkpg** [comment]
Otclient does not work either.
Client 10.41

**Comment by jollejkpg** [comment]
OTClient error:


ERROR: got a network message with invalid checksum
at:
    [C++]: ?internalRecvData@Protocol@@AAEXPAEG@Z
