### ISSUE TITLE
Lots of errors on today's commits!

### ISSUE THREAD

**Issue by kosicki123** [otland/forgottenserver#1159]
Hi, I'm using printer's version (https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS) and until yesterday, I got zero bugs on console, with today commits, I got these errors.
![image](https://cloud.githubusercontent.com/assets/1424811/5810540/2f204060-a02f-11e4-815a-90f7aa837beb.png)

**Comment by marksamman** [comment]
Is the only difference in your server since yesterday the executable file of the server? If not, it looks more like this is a problem with your data pack. Have you checked the Lua errors and confirmed that they're not actually real errors?

**Comment by kosicki123** [comment]
I'll try to revert my datapack, I have pulled some data. Thanks a lot.
