### ISSUE TITLE
Strange exhaustion with potions

### ISSUE THREAD

**Issue by att3** [otland/forgottenserver#1163]
Edit.
Removing the player:addCondition(exhaust) from the script gives player "exhaust" of: configKeys.EX_ACTIONS_DELAY_INTERVAL).
The "you are exhausted" message won't pop up.

When I am drinking potions sometimes the exhaustion is that exhaustion what has been set as parameter(atm 350ms~)

But then sometimes the exhaustion will become over 1 second~ (possibly timeBetweenActions+exhaust?)

I haven't yet figured out what triggers it to do so.
However it's not hard to reproduce this issue:

Just edit potions.lua and set the param_ticks to e.g 500.
After that just spam potions as you normally would. - stop every now and then.

You need to get the "you are exhausted" message.
After that the exhaustion will be longer than normal.
````
exhaust:setParameter(CONDITION_PARAM_TICKS, 350)

-- Item Usage
timeBetweenActions = 200
timeBetweenExActions = 1000
````

Having potions exhaust set to e.g 100~
rarely triggers the "you are exhausted" message == there won't be over 1sec exhaust

(with "normal settings" ((1sec potion exhaust + 1~ sec timeBetweenActions the exhaust is sometimes 1 second and sometimes 2~ seconds.))

Also one unrelated question, is it possible to make an item into ITEM_INBOX?
e.g item:setAttribute(ITEM_INBOX)

**Comment by diath** [comment]
The potion script could use some rewrite anyway. It's kind of a clusterfuck atm, a nice config table would be way better. Besides, it doesn't properly add vials where it should.

**Comment by marksamman** [comment]
timeBetweenExActions is applied to every "Use with.." action.
