### ISSUE TITLE
Error in saveServer ()

### ISSUE THREAD

**Issue by rowaraujo** [otland/forgottenserver#1164]
Call Stack:
![error](https://cloud.githubusercontent.com/assets/9668277/5886218/de0912d6-a36e-11e4-86f1-5f29dccfc3e4.png)

**Comment by rowaraujo** [comment]
![autos](https://cloud.githubusercontent.com/assets/9668277/5886225/41b2f8b0-a36f-11e4-8fb0-e9cb254d5fd5.png)

**Comment by marksamman** [comment]
Have you made changes to the source code? The line numbers don't match with the code in this repository.

**Comment by rowaraujo** [comment]
I made no change in iomapserialize.cpp.
I made changes only in definitions.h

**Comment by rowaraujo** [comment]
<item id="1548" name="nothing special" />

**Comment by rowaraujo** [comment]
`<item id="1548" name="nothing special" />`

**Comment by marksamman** [comment]
There are other changes than just in definitions.h, post a complete diff of your source code vs the master branch in this repository.

**Comment by rowaraujo** [comment]
Another error!
It only happens in Windows.

I did not make any changes to the source to be in definitions.h...

(Sorry my bad english, i am brazilian)
![print](https://cloud.githubusercontent.com/assets/9668277/5895461/278f47f4-a4ff-11e4-8b10-3091de93599c.png)

**Comment by marksamman** [comment]
As I've already said, you have made local changes because the line numbers are not matching. If you can't post a complete diff against master, we can't rule out that this crash may be caused by your local changes.
