### ISSUE TITLE
onTargetCombat dosen't recognize boolean values

### ISSUE THREAD

**Issue by WibbenZ** [otland/forgottenserver#1165]
I'm running a code that simply is, if you are in the event and you are in team A you can't attack another player that also is in the event and in team A.
It passes all my if statments etc. And it sends out the "You may not attack.." message, but it dosen't cancel the attack, it simply allows the attack to continue / start.

And i'm using return false to cancel it out after the message is sent out.
```
	print("passed is same team check")
	self:sendCancelMessage("Sorry, you cannot attack your own team.")
	return false
```

Using a version from a few days ago.

**Comment by ninjalulz** [comment]
It uses RETURNVALUEs.

e.g
```Lua
if something then
    return RETURNVALUE_YOUMAYNOTATTACKTHISPLAYER
end
```

**Comment by WibbenZ** [comment]
Thanks @ninjalulz haha, checked the source code and found the RETURNVALUE variables but tought it was just used in the source code. :p
