### ISSUE TITLE
Ice rapier

### ISSUE THREAD

**Issue by Tazer89** [otland/forgottenserver#1167]
Ice rapier doesn't disappear

**Comment by rowaraujo** [comment]
There is no such bug on this server.
I use this server in my project and Ice Rapier disappears.

**Comment by joseluis2g** [comment]
https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/commit/953f67c5912ffd03ce6aca30565d5862b2e81722 the fix until new update
