### ISSUE TITLE
Problems on items with speed bonus

### ISSUE THREAD

**Issue by rowaraujo** [otland/forgottenserver#1171]
![boots of haste](https://cloud.githubusercontent.com/assets/9668277/5991047/5727a42c-a9b2-11e4-896a-38c0c547815e.png)

In game:
![bug speed](https://cloud.githubusercontent.com/assets/9668277/5991059/93a1d3b4-a9b2-11e4-9da0-6fb38f9e812f.png)

**Comment by marksamman** [comment]
This is working as intended. The speed displayed in look description is meant to be half of the value you specify in items.xml.
