### ISSUE TITLE
Command "/a " stop working

### ISSUE THREAD

**Issue by YohanAugusto** [otland/forgottenserver#1176]
Command "/a " stop working after lastest updates.

**Comment by gugahoa** [comment]
It is working.

/a number

**Comment by YohanAugusto** [comment]
i know that i need to use a number.. -.-

but when i put "x" number like "/a 5" my char just change the side to north.

**Comment by marksamman** [comment]
I can't reproduce this.

**Comment by rowaraujo** [comment]
I can't reproduce this.
