### ISSUE TITLE
onAddItem x Player:moveItem

### ISSUE THREAD

**Issue by Kamenuvol** [otland/forgottenserver#1178]
What is the difference between using a movement onAddItem in a tile or using a event Player:moveItem and check the tile?

**Comment by dalkon** [comment]
Player:onMoveItem runs whenever a player moves any item.
onAddItem is triggered when a certain item is added to a tile (a player does not have to place it.)

**Comment by Kamenuvol** [comment]
But I can do the same behavior in both, a player moving a object to a tile. For this specific action, what is the preferred and the faster way?

**Comment by marksamman** [comment]
onAddItem is most likely faster because your tile/position check in onMoveItem will run everytime a player moves an item. If you care about performance in this case, measure it.
