### ISSUE TITLE
Error on Compile in Fedora

### ISSUE THREAD

**Issue by kaitoqueiroz** [otland/forgottenserver#1179]
when I run "cmake .." command I received this:

>CMake Error at cmake/FindMySQL.cmake:116 (MESSAGE):
>Cannot find MySQL.  Include dir: MYSQL_INCLUDE_DIR-NOTFOUND library dir:
>Call Stack (most recent call first):
>CMakeLists.txt:25 (find_package)

>-- Configuring incomplete, errors occurred!
>See also "/home/ec2-user/forgottenserver/build/CMakeFiles/CMakeOutput.log".
>See also "/home/ec2-user/forgottenserver/build/CMakeFiles/CMakeError.log".

And after I run "make" command:

>make: *** No targets specified and no makefile found.  Stop.

**Comment by diath** [comment]
Looks like you're missing the MySQL package. Try:
``yum install community-mysql-devel``

**Comment by kaitoqueiroz** [comment]
I already have installed MySQL on my server
when I trey to run 

> yum install community-mysql-devel
Shows This:
>Package mysql-5.5-1.6.amzn1.noarch already installed and latest version
>Nothing to do

**Comment by kaitoqueiroz** [comment]
Solved.
I've re-install MySQL
