### ISSUE TITLE
[QUESTION] onDeath - How to set action id in corpse

### ISSUE THREAD

**Issue by rowaraujo** [otland/forgottenserver#1187]
function onDeath(creature, corpse, killer, mostDamageKiller, unjustified, mostDamageUnjustified)
    	local targetMonster = creature:getMonster()
    	if not targetMonster or targetMonster:getMaster() then
    		return true
    	end

    	local tile = targetMonster:getPosition():getTile()
    	local thing = tile:getTopVisibleThing()
    	if thing:isItem() then
    		thing:setActionId(3193)
    	end

    	return true
    end

I did not find any example for this on the internet.

**Comment by marksamman** [comment]
http://otland.net/forums/support.16/
