### ISSUE TITLE
[REQUEST] Event function Creature:onMoveItem or Monster:onMoveItem

### ISSUE THREAD

**Issue by rowaraujo** [otland/forgottenserver#1189]
I have this code in Player:onMoveItem

```
	if isInArray({1714, 1715, 1716, 1717, 1738, 1740, 1741, 1747, 1748, 1749}, item.itemid) and item.actionid > 0 or item.actionid == 5640 then
		if self:getAccountType() < ACCOUNT_TYPE_GAMEMASTER then
			self:sendCancelMessage('You cannot move this object.')
			return false
		end
	elseif item.itemid == 7466 then
		self:sendCancelMessage('You cannot move this object.')
		return false
	end
```

This code protects quest chests if any player trying to move it.

If in the reward room can give the spell Utevo Res "demon skeleton, a Demon Skeleton can move any chest quest, as the above code only works for players.

http://prntscr.com/5znb7p

**Comment by ninjalulz** [comment]
Use unique ids.

**Comment by EPuncker** [comment]
indeed jsut use uniqueid and items will not be moveable
