### ISSUE TITLE
BUG - Please move nextUseStaminaTime = {} in global.lua

### ISSUE THREAD

**Issue by rowaraujo** [otland/forgottenserver#1190]
If i type "/reload global" (in GOD) and stage exp is active, i have a serious problem -> BUG STAMINA AND EXP GAIN!!!

This resets all data of players already logged and in function useStamina is not completed.

This line:
<b>local timePassed = currentTime - nextUseStaminaTime[playerId]</b>

```
local function useStamina(player)
	local staminaMinutes = player:getStamina()
	if staminaMinutes == 0 then
		return
	end

	local playerId = player.uid
	local currentTime = os.time()
	local timePassed = currentTime - nextUseStaminaTime[playerId]
	if timePassed <= 0 then
		return
	end

	if timePassed > 60 then
		if staminaMinutes > 2 then
			staminaMinutes = staminaMinutes - 2
		else
			staminaMinutes = 0
		end

		nextUseStaminaTime[playerId] = currentTime + 120
	else
		staminaMinutes = staminaMinutes - 1
		nextUseStaminaTime[playerId] = currentTime + 60
	end

	player:setStamina(staminaMinutes)
end
```

Error prevention code:

```
local function useStamina(player)
	local staminaMinutes = player:getStamina()
	if staminaMinutes == 0 then
		return
	end

	if not nextUseStaminaTime[player.uid] then
		nextUseStaminaTime = {}
		nextUseStaminaTime[player.uid] = 0
	end
...
```
Change this please!

**Comment by diath** [comment]
Just replace:
```nextUseStaminaTime = {}```

With:
```
if not nextUseStaminaTime then
    nextUseStaminaTime = {}
end
```

In global.lua

**Comment by rowaraujo** [comment]
@diath This does not solve the problem!
The problem is that in useStamina function, there is no such key: nextUseStaminaTime[playerId]. If i type "/reload global", because it resets all the keys.

**Comment by TheSumm** [comment]
If so @diath's solution seems to be perfect.

**Comment by klotharek** [comment]
Please fix God commands /a 2

**Comment by rowaraujo** [comment]
Yes, I get it!
Thnx @diath
