### ISSUE TITLE
Config.lua Rates

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1192]
I used TFS 1.0 for a while and didn't have any problems with rates.
When i set them to 0 it ment: you get no experience.
If i give experience with script it uses the multiplier from vocations.xml (like i want)

Today i upgraded to TFS 1.1
now the value 0 in config.lua is being ignored..
Is this bug or there is some new scripts im missing?
(i only have taken over the NPC folder from forgottenserver/master/data)
(and config.lua)

**Comment by whitevo** [comment]
Now i have the latest Data folder also merged with my scripts.
Rates (in config.lua) started working, but they aren't working the way they did before.
All these* and several more scripts what are giving skill experience are also being multiplied by rates found in config.lua

in TFS 1.0 these* scripts what gave experience were multiplied with multipliers found in vocation.xml

I can't find the reason why is that so, because the source code is handling config file and experience same way as before. Maybe im missing something.

But either way, if this was intended change then sadly i have to revert back to TFS 1.0 because this kind of experience system where i only get exp with scripts is crucial for my server.





[these*]
player:addManaSpent ( 160*1)
player:addSkillTries(SKILL_AXE,     20*1)

**Comment by dalkon** [comment]
The multipliers in vocations.xml only has to do with calculating the required amount of times you have to use a skill to level it up, not how much you gain per try. I don't see how 1.0 is different from 1.1 regarding skill tries and mana spent.

**Comment by whitevo** [comment]
already checked.
This doesn't change anything. I might aswell DELETE the functions, i get no errors nor changes..

**Comment by whitevo** [comment]
ups xD

**Comment by whitevo** [comment]
Ah i now understands what does it even do xD
Yeah, this is the issue idd.
Enabled onGainSkillTries takes multiplier from config.lua
Disabled or delted onGailSkillTries takes the default vocation.xml multipliers.

soo.. the issue is in source code?
what should be changed there?

**Comment by dalkon** [comment]
The multipliers in vocations.xml has nothing to do with gaining skills.

**Comment by whitevo** [comment]
they do

**Comment by dalkon** [comment]
Yes but not gaining experience for them, what you're talking about is unrelated to the issue.

**Comment by whitevo** [comment]
ok, perhaps.

so you said look:
Player:onGainSkillTries function
what i have to do here?
This wont help me in that matter. I need 2 different multipliers like before.
Multiplier when hitting monsters = 0 , when using scripts then 1.
How can it be done?

**Comment by marksamman** [comment]
Make Player:onGainSkillTries not apply the multiplier when called through a script. This is not a bug so I'll point you to the support forum on OTLand: http://otland.net/forums/support.16/

**Comment by whitevo** [comment]
sad, then i cant use better tfs version :/
