### ISSUE TITLE
Request: getParameter for combat/condition

### ISSUE THREAD

**Issue by Codinablack** [otland/forgottenserver#1193]
Ok so I seen a post today from someone on otland about doing an action when the ticks of a condition have worn off, and yes there are rudimentary ways of doing this sure, but I would like to request a method for both combat and condition that will return the value of a specified parameter.  I am sure everyone understands what I mean but for clarification here is an example.

condition:getParameter (CONDITION_PARAM_TICKS)

Return value would of course be the amount of ticks left for that condition. Please note, I may have the variable for ticks wrong, nothing to reference right this second because I am posting from my phone.
##

**Comment by Kamenuvol** [comment]
I've seen that post too, and I think doCombat should return true when it is finished and you check:
if doCombat.. then

**Comment by marmichalski** [comment]
This can be closed. @nekiro?

**Comment by nekiro** [comment]
@marmichalski yep, I forgot to mark it properly in #2951
