### ISSUE TITLE
Paladins cant attack while drinking potions?

### ISSUE THREAD

**Issue by slayingworld** [otland/forgottenserver#1195]
Just as the title says, if your drinking potions, paladin wont throw spear/bolt/arrow etc..

Im not sure if this is how it is on RT (Real Tibia), but would like to know a bit more information, if somebody knows. Thanks

P.S. You guys are awesome! Ill start contributing once i get the hang of this github :p

**Comment by EPuncker** [comment]
intended real tibia behavior, there are too many things that make a paladin attack to stop

**Comment by zakius** [comment]
are you guys sure that it works EXACTLY the same? I don't remember having any problems on cipbia, but for pallies you have to get perfect timing in a lot of things or else you will get attack delay
