### ISSUE TITLE
Monsters walking on fields

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#1200]
I want to suggest the addition of a new flag for monsters to make them able to walk through fields even if they are not immune to it, or even if they are not attacked (and if the way is blocked they walk on it anyway), but there are monsters that walks over it even if it damages him, like Wyrms that walk on a fire wall taking damage anyway, I hope I was clear enough and tell me if you need anything else

**Comment by marksamman** [comment]
This is sort of related to #193, you should post your suggestion in that issue so that we can take it into consideration when we make adjustments to monster pathing.
