### ISSUE TITLE
[Question] OutputMessagePool::getInstance()->send(output) or ...getConnection()->send(output)

### ISSUE THREAD

**Issue by rowaraujo** [otland/forgottenserver#1201]
What is the difference between using OutputMessagePool::getInstance()->send(output) or using msg->getConnection()->send(output)?

What is best to avoid m_writeError?

**Comment by marksamman** [comment]
OutputMessagePool::send will call Connection::send after checking the state of the output message (that it isn't configured to auto send).

**Comment by rowaraujo** [comment]
OK.
What is best to avoid m_writeError?
