### ISSUE TITLE
Vocations.xml Skill Multiplier

### ISSUE THREAD

**Issue by Codinablack** [otland/forgottenserver#1202]
Ok so I was trying to make a modalwindow skill point system and during testing I had some funny results. Using this formula..

player:addSkillTries(skillId, player:getVocation():getRequiredSkillTries(skillId, player:getSkillLevel(skillId) + 1) - player:getSkillTries(skillId))

With the different skillid's I found out that I could add one skill correctly on one vocation, but on the other it just wouldn't add anything. I tested this with three different vocations, all had their own skill that the formula would work perfectly. So I changed the values of the skill multipliers in vocations.xml to the same multiplier as the one that works, for the rest of the skills, and that was the problem. If I have the multiplier set to 1.8 it doesn't work, if it is 1.1 it works perfectly. Config for the skill rate multiplier is 1.

**Comment by Codinablack** [comment]
Ok so I have done alot of testing and it turns out the formula was the problem with adding skills, not requiredSkillTries, but also the multiplier is still bugged. If anyone wants to confirm this, here is how to replicate it.

Step 1. Create a new character with 0 skill level and 0 skill tries.
Step 2. Set that character's, vocations's, skill multiplier at 1.8
Step 3. Login with character and use that skill, it will never go up!

Additional Steps to confirm:

* Change the rate of skill in config to whatever you want, faster to speed it up or slower to be sure.
* Check another vocation with another skill multiplier at 1.8 with 0 skill tries to start.
* Check another vocation with 0 skill tries to start, but with skill multiplier at 1.1 or 1.2 and watch skill tries go up!
* Check all these results in database, relog character to make sure everything is updated before checking.

I have tried this multiple times, it works fine to have 0 skill level and 0 skill tries, that is not the problem. But when we start with 0 and 0 and skill multiplier in vocations.xml is 1.8, there will never be any skill tries added....

**Comment by gugahoa** [comment]
Default for skill level is 10. Started at 10 with 0 skill tries and vocation multiplier for club at 1.8 using a Knight. Couldn't reproduce it. :(

**Comment by Codinablack** [comment]
I know the default is 10, but 10 with 0 skill tries, when you do it that way your players will train and train, and as they gain skill level 1, and 2, and 3, none of the skill percent shows up in the client. None of it, it's not until the player actually reaches the amount of skill tries needed to be at level 10 with 100% to go to level 11 before anything ever shows up in the bar. You can test that with any skill multiplier. I figured that out long time ago, before I even knew about being able to make issues here, I figured it out from otland teaching me how to use the database, and you can see, it is right in the schema, you start at level 10 with 0, and as a result no progress is shown to the player until they actually get the tries for that level, it's very discouraging. So I changed it to 0 because it's supposed to be a true rpg game, and starting an Archer with axe level 10 and a Squire with distance level 10 just doesn't sound right to me. That being the case, it still works great from skill level 0 unless the multiplier is too high, why is that not a bug?

**Comment by Codinablack** [comment]
Sweet! Thank you! Hadn't had time to test it yet, I'll check it out and report back if I have any further issues :+1:
