### ISSUE TITLE
ItemAttributes crashing

### ISSUE THREAD

**Issue by dancolaco** [otland/forgottenserver#1203]
When i use **item:setAttribute(x, x)** and **item:getAttribute(x)** it returns and works normally, but when i delete the item by using **/r** or throwing in the water for e.g., the .exe closes.

**Comment by Jo-Tran** [comment]
Actually anytime you use /r it closes the client, haven't tried throwing items in the water yet to see if it closes the client.

**Comment by ColorsCL** [comment]
I just tried to reproduce this and nothing -bad- happened. What attributes are you guys using?

**Comment by dancolaco** [comment]
![](http://i.imgur.com/kr54VNZ.jpg)
Just "1".

**Comment by ColorsCL** [comment]
I tried the code that you gave and tried a lot of different combinations and is not crashing the server at all. Are you using a custom/old version of TFS? Also, you should be using enums instead of "1".

**Comment by TwistedScorpio** [comment]
Maybe (it) is null for him ?

**Comment by Zbizu** [comment]
try tonumber(param)

**Comment by dancolaco** [comment]
The problem isn't the attribute Key or Value, because when i use another talkaction to verify the attribute of the item, it gets the value normally. The crash problem is only removing the item from the game.

**Comment by marksamman** [comment]
This issue will be closed if you cannot supply enough information for us to be able to reproduce it.

A few questions:
* How is the item created?
* Which item id?
* Exactly which attribute keys are set on the item, and what values do they have?
