### ISSUE TITLE
Game.loadMap - load spawns

### ISSUE THREAD

**Issue by dbjorkholm** [otland/forgottenserver#1209]
Would be nice if it loaded spawns from <b>mapName</b>-spawn.xml, same map name as the one that was specified in the path ("path/to/<b>mapName</b>.otbm")
##

**Comment by TheSumm** [comment]
I think it would be good to have seperate functions:
Game.loadSpawns(file)
Game.unloadSpawns(file)
aswell.

**Comment by Nu77** [comment]
Having it in separate functions is good, would being possible load single spawn files at any time.

**Comment by Schiffers** [comment]
bump, any soluctions to this ?
would be very interesting use it muahahaha

**Comment by Mojmistrz** [comment]
this topic deserves a bump

**Comment by Schiffers** [comment]
yes, this deserves bump and one soluction, with this we can load our big maps without suffer, you can load parts of them, then would be nice to work with world changes as real tibia, I'm working with world changes but without handle with some of them, because can't reproduce the spawn :/

**Comment by ranisalt** [comment]
Well, considering the spawn filename is saved with the map, I don't really see the point.

**Comment by Schiffers** [comment]
@ranisalt so why the function Game.loadMap() don't load the spawns too ?

**Comment by ranisalt** [comment]
Because the spawn file is separate and has a different format.
