### ISSUE TITLE
Monster folder lib

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1213]
Hello,

Well since monster have their scripting interface aswell, it would be awesome if they had a lib aswell. Like the others, actions, creaturescripts and etc... Or does it already have?

**Comment by Nu77** [comment]
Why it should have a lib folder? We have global state, only put a lib folder in it and load it by the main interface. Lib folder it's a deprecated utility which i think should be removed from core.

**Comment by PrinterLUA** [comment]
You know what i mean with a lib folder? If you go inside data/spells you will see a lib folder there. I would like to keep someone functions only for that particular system. We don't need to move the areas and etc.. outside the spells lib folder and into global.lua, that is no unnecessary.

**Comment by marksamman** [comment]
@Nu77 is correct. If you want a lib folder for monsters you can create one and use dofile from global.lua, it will have the same effect.
