### ISSUE TITLE
Question about protocol status

### ISSUE THREAD

**Issue by Nu77** [otland/forgottenserver#1214]
Is it only used to serve external information or has any other utility ?

**Comment by djdamc** [comment]
It's used only to serve server info externally and doesn't interact with the game client in any way.

**Comment by Nu77** [comment]
``` c++
std::map<uint32_t, int64_t> ProtocolStatus::ipConnectMap;
const uint64_t ProtocolStatus::start = OTSYS_TIME();
```
```ProtocolStatus::start```: is used to get the uptime of the game
```ProtocolStatus::ipConnectMap```: i think it's used for get the ips connected to protocol status but i don't sure and it's why i'm asking.

**Comment by djdamc** [comment]
Yes, you're right.

**Comment by Nu77** [comment]
Thanks ;)
