### ISSUE TITLE
[BUG] Stairs

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#1216]
![image](https://cloud.githubusercontent.com/assets/2137569/6407666/b6aa3db2-be23-11e4-82ee-2a7cbc59bb9e.png)

When upstair os downstair if there is a multstairs sequence it just down only 1 floor !

**Comment by Skazw** [comment]
Confirmed: http://youtu.be/kkH3X9MBKSw

**Comment by comedinha** [comment]
https://github.com/otland/forgottenserver/issues/19
