### ISSUE TITLE
ITEM_ATTRIBUTE_SHOOTRANGE doesn't work for wands

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#1219]
As in issue title.

**Comment by EPuncker** [comment]
I confirm

**Comment by Zbizu** [comment]
the value is set, but it still uses default range after changing it to 3 or 5

**Comment by ninjalulz** [comment]
Feel free to try this: https://gist.github.com/ninjalulz/2c5785af74e219b97f8b/revisions

**Comment by Codinablack** [comment]
I confirm

**Comment by gugahoa** [comment]
Just tested for bow. Same result as the others.
