### ISSUE TITLE
onTargetCombat bug?

### ISSUE THREAD

**Issue by WibbenZ** [otland/forgottenserver#1222]
I'm trying to add the expert modes and noticed a bug I think.
If (any) if statments are returned in the function it all works good with ex. avalanche, ue etc
But if you use ex. an SD the rune gets removed and the player gets the cooldown for it but the damage is not recived aswell as no effect is added to the target.

Is it supposed to be like this? In that case we need some Creature:onCombat(target) to be able to cancel all combats made if the script is returned.
As I said it works great with ues and area runes.

**Comment by dalkon** [comment]
Creature:onAreaCombat() does the first check for runes / spells, use that.

**Comment by WibbenZ** [comment]
How am I supposed to get the target userdata then? It only has tile and isAggressive.
Should I use getSpectators on each tile or what?

**Comment by WibbenZ** [comment]
@marksamman @dalkon Id really like a fix for this, self:getTarget dosen't work either since the target isen't always indexed. (Ex throwing an sd without starting a target).
There isen't any target variables to push either in the Combat::canDoCombat function.

**Comment by dalkon** [comment]
Then use Tile:getTopVisibleCreature().

**Comment by WibbenZ** [comment]
@dalkon 
```
	local target = tile:getTopVisibleCreature()
	print(tile, target)
	if(not target) then
		print("escaped onAreaCombat")
		return true
	end
```

Prints out userdata, nil, escaped.
SD gets used and the attacker gets a cooldown for it.

So if that is the "fix" then it dosen't work either.

**Comment by dalkon** [comment]
```Lua
local target = tile:getTopVisibleCreature(caster)
if not target then
    return RETURNVALUE_NOTPOSSIBLE
end
return RETURNVALUE_NOERROR
```

**Comment by WibbenZ** [comment]
That fixed it, forgot to check if getTopVisibleCreature needed any parameters.
Thanks.

But in the case of RETURNVALUE_NOERROR, why does it return a boolean value in the event lua files insted of that?
Just a waste to have it since those functions dosen't allow boolean values.

**Comment by dalkon** [comment]
It was never changed in the default files because I probably forgot about it.
