### ISSUE TITLE
itemEx bug

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#1225]
when I use item on a tile with plate armor, it reads border values instead of plate armor
![iexb](https://cloud.githubusercontent.com/assets/5205079/6605214/695a790e-c82e-11e4-8198-ee6d9f779dcc.png)

**Comment by ninjalulz** [comment]
I can't reproduce this.

![](https://i.imgur.com/s9MCmlY.gif)

**Comment by diath** [comment]
Are you using otclient by any chance? I've had a similar issue with otclient, it would sometimes confuse the stack positions and use an item on the wrong item (mostly noticable with borders, but there are some other items that don't work properly).

**Comment by conde2** [comment]
Thats because you are using OTclient check the OTclient repository there is a issue open there.

**Comment by Zbizu** [comment]
closing that as it's otclient issue, not tfs itself
