### ISSUE TITLE
how i add players?

### ISSUE THREAD

**Issue by looksik** [otland/forgottenserver#1233]
i dont know hot to use mysql were can i learn for use in ot ? im new looked all over the sites ot land etc but no sucess :(

**Comment by margohq** [comment]
You can use account maker or you could use option insert on phpMyAdmin.
1. Login to your phpMyAdmin.
2. Select server db.
3. Select accounts table.
4. There you will have option: Insert.
5. Fill all fields & Save.
6. Go to players table.
7. Select again option: Inser.
8. Fill all fields & Save (remember to select account_id).
9. Thats all.

**Comment by marksamman** [comment]
https://otland.net/forums/support.16/
