### ISSUE TITLE
Player:onLook position formatting

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#1237]
Formatting itemid and position like this for onLook events could make scripting much easier - just copy-paste instead of rewriting values manually.
````
17:07 You see pavement.
ItemID: 10399
Position: {x = 1023, y = 997, z = 7}
````

**Comment by Tazer89** [comment]
:+1:

**Comment by esfomeado** [comment]
:+1:

**Comment by Luckey1729** [comment]
I've thought about this before. But isn't `Position(x, y, z)` the preferred method now?

**Comment by Zbizu** [comment]
@Luckey1729 
"1023, 997, 7" is still better than current formatting for scripting purposes

**Comment by marksamman** [comment]
I've changed it to x, y, z.
