### ISSUE TITLE
Rotating magic effects on the server side

### ISSUE THREAD

**Issue by Zaaku12** [otland/forgottenserver#1238]
Hello, My idea is to add rotating magic effect in LUA, in this function:
sendMagicEffect(magicEffect[, player = nullptr])
add somethink like "dir(1=no rotate,2=Right,3=Down,4=Left)"

**Comment by marksamman** [comment]
What?

**Comment by Zaaku12** [comment]
I probably use wrong word :P
I record video with my idea, It shows what I would like to do in server side, instead add 4 magic effects.
https://www.youtube.com/watch?v=3NmJtT7zN7o&feature=youtu.be

**Comment by marksamman** [comment]
The server doesn't deal with graphics. You would have to modify OTClient to rotate effects on specific packets.
