### ISSUE TITLE
Request: Lua function Sleep/Wait/Pause

### ISSUE THREAD

**Issue by Codinablack** [otland/forgottenserver#1239]
Ok I know we already have addevent, but we all know addevent has a few issues that come with it. One being that for the function that you are passing data to, you can't pass userdata or objects, because it's unsafe or w/e. 

I am requesting a simple lua function for use in all scripts to make the script pause x amount of seconds.

wait(10)

Could be milliseconds or whatever you guys prefer, but it would be extremely useful

**Comment by gugahoa** [comment]
That's as unsafe as passing userdata for addEvent, if not more. What makes passing userdata to addEvent directly unsafe is the fact that in the interval before the function is called, the userdata may become invalid, causing a seg fault when used.
