### ISSUE TITLE
Problem with glowing switch tile

### ISSUE THREAD

**Issue by Maldero** [otland/forgottenserver#1240]
I was looking for a method that returns RETURNVALUE_NOTPOSSIBLE or RETURNVALUE_NOTENOUGHROOM, which uses glowing switch or walkstack and have not found this.
So in game all players can enter to walkstack tiles eg. with depo.

**Comment by ninjalulz** [comment]
*Player::canWalkthrough*
```C++
	const Item* playerTileGround = playerTile->ground;
	if (!playerTileGround || !playerTileGround->hasWalkStack()) {
		return false;
	}
```

You can change the walkStack value for glowing switch in items.xml to 1, and players will be able to stack on those.

**Comment by Maldero** [comment]
Ok i saw this, but it dont work. Players can enter on self ob this walkstackable value 0 or 1.

**Comment by ninjalulz** [comment]
Works properly here, I tested with the latest build from [Forgotten Server builds](https://nightlies.otland.net).

Make sure you have the correct attribute key in items.xml
```XML
	<item fromid="11062" toid="11063" article="a" name="glowing switch">
		<attribute key="walkStack" value="0" />
	</item>
```

**Comment by Maldero** [comment]
Yes, its corrected.
	<item fromid="11058" toid="11061" article="a" name="gate" />
	<item fromid="11062" toid="11063" article="a" name="glowing switch">
		<attribute key="walkStack" value="0" />
	</item>
	<item fromid="11064" toid="11075" article="a" name="window" />
Player.cpp:
bool Player::canWalkthrough(const Creature* creature) const
{
	if (group->access || creature->isInGhostMode()) {
		return true;
	}

	const Player* player = creature->getPlayer();
	if (!player) {
		return false;
	}

	const Tile* playerTile = player->getTile();
	if (!playerTile || !playerTile->hasFlag(TILESTATE_PROTECTIONZONE)) {
		return false;
	}

	const Item* playerTileGround = playerTile->ground;
	if (!playerTileGround || !playerTileGround->hasWalkStack()) {
		return false;
	}

	Player* thisPlayer = const_cast<Player*>(this);
	if ((OTSYS_TIME() - lastWalkthroughAttempt) > 2000) {
		thisPlayer->setLastWalkthroughAttempt(OTSYS_TIME());
		return false;
	}

	if (creature->getPosition() != lastWalkthroughPosition) {
		thisPlayer->setLastWalkthroughPosition(creature->getPosition());
		return false;
	}

	thisPlayer->setLastWalkthroughPosition(creature->getPosition());
	return true;
}
Dont' work :(

**Comment by Maldero** [comment]
I downloades newest source, compiled and now works. Dont know what i had wrong in my older sources. Sorry for problem and very thanks for help.

Greetings, Janusz.
