### ISSUE TITLE
game clean

### ISSUE THREAD

**Issue by Schiffers** [otland/forgottenserver#1245]
in the server save, why the server clear the map and not remove corpses? :/

**Comment by ninjalulz** [comment]
It doesn't remove corpses because they're not pickupable.

**Comment by Schiffers** [comment]
well, in others versions the clean map works with corpses, I can edit this to remove corpses?

**Comment by marksamman** [comment]
Yes, but please use this forum for support matters: https://otland.net/forums/support.16/
