### ISSUE TITLE
[Question] Otb Updating method

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1247]
I want to know exactly which is the method that tfs team uses to update the otb to the lastest cip tibia. Why i want to know that:

I want to update my own server to 10.76(latest client) but i want to my otb have the same server ids as the official tfs team otb will have in the future(when 1.1 finish and 10.76 will be available officially). Its not just for maintain my server without debugs, i want the oramond/10.5 items.

I think the community needs to know that because we want to maintain compatibility in the future with official tfs items.otb/items.xml.

Should we just take the official tfs otb(10.35) and use this options(http://prntscr.com/6k86x6)?

**Comment by marksamman** [comment]
Most of the time, using that option in otitemeditor is enough from the latest OTB, but you need to go one version at a time (as in: you don't go directly from 10.35 to 10.76, you need to update to every version along the way); however in the upcoming update I can guarantee you that there will be mismatching ID's if you only click update in the OTB. There will even be a new attribute in the new OTB.

I suggest that you wait if you want to maintain compatibility. I don't have the time to document exactly how the update process works. If you really want me to document it, you may back the issue with a bounty which may or may not make me reconsider, but without a bounty it's definitely not something I'll prioritize over other issues.
