### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by woeterman94** [otland/forgottenserver#1248]
Following commands are not working
/i  (cannot create items)
/summon
/n
/c (cannot find most of the creatures like dragonlord hatching,...)

Commands are not giving an error... Just nothing happens

**Comment by woeterman94** [comment]
I tried more of the /c command.
When I try to create a cat for example (/c cat) 
it says: "A creature with that name cannot be found"

**Comment by diath** [comment]
Are you sure you have the correct group id set for the player and for the account? Also /c teleports a creature from the map to your position, it does not spawn one.

**Comment by marksamman** [comment]
I can't reproduce this.

**Comment by Maldero** [comment]
Have you got account type >= 4 and player access = 3?

**Comment by woeterman94** [comment]
I forgot about the account types, my bad!

thanks
