### ISSUE TITLE
Stackable property in items.xml

### ISSUE THREAD

**Issue by Maldero** [otland/forgottenserver#1250]
Hello overyone.
When I added to an item attribute key "stackable" and value 0 in console:
[Warning - Items::parseItemNode] Unknown key value: stackable
When I added to items.cpp:
else if (tmpStrValue == "stackable") {
it.stackable = valueAttribute.as_bool();
}
Console don't show error, but when I created an item eg. 12426 which is normally stackable and I set to it stackable 0 attribute got debug.

**Comment by marksamman** [comment]
This does not belong to our issue tracker, please use the support forum on OTLand: https://otland.net/forums/support.16/
