### ISSUE TITLE
wrong summon damage message

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#1254]
ss << "Your " << asLowerCaseString(getName()) << " deals " << points << " to " << target->getNameDescription() << '.';

should be:
ss << target->getNameDescription() << " loses " << points << " hitpoints due to an attack by "<< asLowerCaseString(getName()) << '.';

source: http://i.imgur.com/NywAKtU.png

**Comment by marksamman** [comment]
Is it your summon?

**Comment by EPuncker** [comment]
yes it is
