### ISSUE TITLE
Protocol refcount

### ISSUE THREAD

**Issue by djarek** [otland/forgottenserver#1256]
This issue came up when I started refactoring OutputMessagePool to make it more efficient and adapt it for use with the casting system: classes inheriting from the Protocol base class use a crude ref counting scheme which not only is error-prone but also not thread-safe (I believe that it currently can leak ProtocolGame objects in some specific conditions). What do you think about changing it so that its lifetime is managed by shared_ptrs the same way Connection objects are managed (using the std::enable_shared_from_this template). It would add some overhead, however it would ensure proper cleanup (and the overhead would be basically the same if we used an atomic ref counter for Protocol objects).

**Comment by marksamman** [comment]
I don't have any objections. You may go ahead and change it to use shared_ptr and submit a pull request.
