### ISSUE TITLE
Item function "moveTo"

### ISSUE THREAD

**Issue by WibbenZ** [otland/forgottenserver#1257]
Seems like the function is bugged.
The script works like this:
Move the item to position X, if the item is not valid it will be moved back to the player.

If I move it from my backpck to the position the item does not get moved, it stays at the position.
But if I have move the item from the ground to the position the item gets moved back to the players backpack.

**Comment by marksamman** [comment]
What does "the item is not valid" mean? What is an invalid item? How do you move an invalid item to a player? Where is the item located before you're trying to move it? How do you access the item from the Lua script? What kind of item are you trying to move?

Please elaborate on what the issue actually is with Item.moveTo rather than explaining in the terms of your script that we don't have access to.

**Comment by WibbenZ** [comment]
Dident see any point in uploading it.
Ill do it tomorow then.

The validation is to find the item in the array to get the price of it.
If it found a price the item is removed and money is added to the player.
The item can be any item, ex a shovel that is on the ground or in your backpack.
As long as the item id is in the list it will work.

Using the item userdata in the player:moveitem? In the player events.
It is then called to a function that handles the above.

The script works I always get the "you cannot sell this item..." when I put an invalid item on that position.
But I only get the item back if I move it from a ground tile. As I explained, if I move it from my backpack the item gets sent to the position(as it should) I get the message that I cant sell that item but the item isent moved back to the player.

So to test it use the event function and this:
item:moveTo(self)
If you now have the item in a backpack it wont be sent back. It will be added to the ground to where you moved it.
But if the item already is on the ground the item will be moved to your backpack.
Hope that explained it, otherwise ill tell you more and show you the script tomorow when im at my computer.

**Comment by conde2** [comment]
What he is trying to say is that you can't prevent moving an item to a precise container, because moveTo does not accept Cylinder positions i.e ({x=65536, y=64, z=0})

onMoveItem
The parameter fromPosition when some item is inside a Cylinder will return a position like what I said above and if you do item:moveTo(fromPosition) it will do nothing.

**Comment by WibbenZ** [comment]
I used item:moveTo(player).

**Comment by marksamman** [comment]
If someone else understands what the problem is, please post a sample script which can be used to reproduce the issue. I still don't get it. I've tried this, and it's working fine (it creates 5 platinum coins below the player and moves them to the player):
```cpp
Game.createItem("platinum coin", 5, player:getPosition()):moveTo(player)
```

**Comment by WibbenZ** [comment]
As I explained 2 times what atleast I think was pretty clear.
The item is moved from by the player, not created by the server and then moved.

```
function Player:onMoveItem(item, count, fromPosition, toPosition)
	-- Auto VIP seller
	self:sellItem(item, toPosition)
	return true
end

local autoLootItemWorthTable = {
	[2554] = 500
}

function Player.sellItem(player, item, position)
	if(not item) then
		return false
	end
	
	local itemPrice = autoLootItemWorthTable[item.itemid]
	if(itemPrice) then
		player:addItem(itemPrice)
		player:sendTextMessage(MESSAGE_STATUS_CONSOLE_ORANGE, "item got sold")
		return true
	end
	
	player:sendTextMessage(MESSAGE_STATUS_CONSOLE_ORANGE, "item not sold")
	item:moveTo(player)
	return false
end
```

Add them, then create the item shovel.
Now try to move it to the ground, it should be moved back to you, but it dosen't.
Now try to push to another tile (while the shovel is on the ground) and it will be moved to your backpack.

**Comment by marksamman** [comment]
You need to return false in onMoveItem after you call item:moveTo, otherwise it'll be moved to where it was intended to be moved.
