### ISSUE TITLE
:teleportTo() PushMovement Bug

### ISSUE THREAD

**Issue by Codinablack** [otland/forgottenserver#1259]
Ok so I have been up for hours trying to make a new class I have been working on do a simple movement. Anyways, after crashing and crashing my server, I finally started working my way down to testing this function.

creature:teleportTo(pos, true) 

Now when using this action script the movement argument is fully functional

function onUse(player, item, fromPosition, itemEx, toPosition, isHotkey)
	player:teleportTo(toPosition, true)
return true
end

However, when trying this with a monster script, the monster instantly teleports to the target location.

function onCreatureAppear(self, creature)
if creature:isPlayer() then
 local pos = creature:getPosition()
 return self:teleportTo(pos, true)
end
end

I am assuming I did everything correctly in both of these scripts, however with the action script the player who uses the item walks to the position they click on with the item, but when linking a monster to that second script, the monster will teleport on top of the player everytime a player appears in its range.

**Comment by marksamman** [comment]
The push move parameter only works when the distance is 1 SQM. This is intentional.

**Comment by Codinablack** [comment]
The push parameter works fine using the action script and a distance from player to the edge of the screen, it makes me walk the entire way. I used the same exact action script from above in this gif 

![teleportto](https://cloud.githubusercontent.com/assets/8696596/6881868/e75b0298-d53e-11e4-8428-39504a99e969.gif)

Sorry I know you closed this, I really thought it was a bug. However if the intentional behavior of that function is to only work from 1 Sqm away, then there is apparently still a bug, because as you can see with the action script it works from far away.

**Comment by marksamman** [comment]
It's making you walk the entire way because that's how it is for any item you use, you'll walk up to it if you're not in range and then use it. The action isn't being triggered before you reach the range to use it.

**Comment by Codinablack** [comment]
Oh, I didn't even think about that, forgot all about that. Well it works fine for 1 sqm, sorry, not a real bug, sorry.
