### ISSUE TITLE
[Bug] addChoice (ModalWindow)

### ISSUE THREAD

**Issue by mokerhamer** [otland/forgottenserver#1267]
Hi,

I was working on a Daily Task mission. just bounced on a bug.
The id of addChoice is 256 Maximum. 
So in my case if 
100 -> Returns 100
 200 -> Returns 200
300 -> Returns 44   !!!!
 400 -> Returns 144   !!!!
500 -> Returns 244   !!!!

Can anyone conform this?

**Comment by HeavenIsLost** [comment]
Yes the coice is only one byte length. one byte can only holds 255.

**Comment by mokerhamer** [comment]
How can i edit it to make it bigger??

**Comment by HeavenIsLost** [comment]
if you are using cip client you wold need to edit it with a injected dll or something to change how its read the protocol message and of course change the tfs to send a uint32 or a uint16. If you are using otclient you need to change otclient source and tfs like i said early.

**Comment by mokerhamer** [comment]
So if i got it right even if i use this code with uint32 i will NOT accomplish it?

int32_t LuaScriptInterface::luaModalWindowAddChoice(lua_State* L)
{
	// modalWindow:addChoice(id, text)
	const std::string& text = getString(L, 3);
	uint32_t id = getNumber<uint32_t>(L, 2);
	ModalWindow* window = getUserdata<ModalWindow>(L, 1);
	if (window) {
		window->choices.emplace_back(text, id);
		pushBoolean(L, true);
	} else {
		lua_pushnil(L);
	}
	return 1;
}
