### ISSUE TITLE
Maybe a house issue

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1268]
I think the house:setOwner(0) does removes the items but if there is someone sleeping in the bed it doens't remove the player from the bed... 

http://prntscr.com/6omp3p

**Comment by marksamman** [comment]
It's intentional.

**Comment by HeavenIsLost** [comment]
Well, if player "wakeup"(leave the bed) he will be kick from house?

**Comment by marksamman** [comment]
Yes. If the player isn't kicked out that's a bug.
