### ISSUE TITLE
Promotion Bug

### ISSUE THREAD

**Issue by Alscara** [otland/forgottenserver#1270]
Login.lua in creaturescripts has a part for promotion. As it is now, it resets any player to vocation 0 if they get promoted because it returns a non-number value when checking promotion. It should be something along these lines in order to work properly:

local vocation = player:getVocation():getId()
	local promotion = player:getVocation():getPromotion():getId()
	if player:isPremium() then
		local value = player:getStorageValue(STORAGEVALUE_PROMOTION)
		if not promotion and value ~= 1 then
			player:setStorageValue(STORAGEVALUE_PROMOTION, 1)
		elseif value == 1 then
			player:setVocation(promotion)
		end
	elseif not promotion then
		player:setVocation(vocation:getDemotion())
	end

**Comment by dalkon** [comment]
Player.setVocation accepts userdata values and not numbers, any nil value is ignored and would not change your vocation.

**Comment by Alscara** [comment]
Then why did it not work until I made those changes?

**Comment by Alscara** [comment]
Well it still wouldn't work because it's not checking if the player's promoted vocation is a valid vocation, which means it's returning 0 and the player is being promoted to 0.
