### ISSUE TITLE
Attack Value: Distance Weapons

### ISSUE THREAD

**Issue by Codinablack** [otland/forgottenserver#1271]
Ok so I don't know for sure this isn't how it is "intended" to be, however I am certain that it is illogical for it to be this way. When using distance weapons such as bows/crossbows, the attack value is decided strictly by the ammo type. Meaning if I use a regular bow with crystalline arrows, and then use a umbral master bow with crystalline arrows I do the same damage range because I have the same attack value. But the description of the item says: 11:17 You see a umbral master bow (Range:7, Atk+6, Hit%+5). So the attack should go up right? Easiest way to test this is to have a spell execute with a combat object calling back with CALLBACK_PARAM_SKILLVALUE, and using printing the parameter "attackValue". It returns same values when switching out weapons, only changes when switching out ammo.

**Comment by TheSumm** [comment]
It is not ignored in general it might be a issue with the combat callback not considering attack of the weapon.

See https://github.com/otland/forgottenserver/blob/master/src/weapons.cpp#L827-L830

**Comment by Codinablack** [comment]
Thanks guys! Awesome work as always :+1:
