### ISSUE TITLE
Automatic Remount

### ISSUE THREAD

**Issue by WibbenZ** [otland/forgottenserver#1273]
Tried to serach for an issue but could not find one.
Would be nice to add this, if you enter PZ mounted it will automatically mount you when you leave the PZ zone.

**Comment by EPuncker** [comment]
yeah indeed :+1: 
one more thing:
when you logout (doesn't matter if pz or not) and login again, you should get dismounted

**Comment by WibbenZ** [comment]
@marksamman if this is something you plan to add yourself, will this make 1.1 or will it be in a later version?
I could give it a try, but in what way would you store if the player is mounted or not?
The easiest way I can see it is using the player class, here: https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L63
And a boolean value if it should remount or not.

**Comment by marksamman** [comment]
No new features will make it into 1.1. Yes, you would store a boolean in class Player.
