### ISSUE TITLE
Combat:execute() vs. doCombat()

### ISSUE THREAD

**Issue by Codinablack** [otland/forgottenserver#1274]
Ok, first off this is NOT a bug. This is only an "issue". Now I am assuming what I am about to say is "intended behavior" but hear me out for one second.

My issue is that using the method :execute for a combat object requires the "userdata" or object or w/e, whereas using doCombat() uses the creature's ID instead. Now that being said, we don't have the possibility to create the object the new way like:

local combat = Combat()

and still use it with doCombat(). We can't, it will not find the combat object (maybe this is a bug). So okay, that's not a big deal right? It really isn't because we should be using metatables and methods anyways right?

Ok now the problem comes in when a person decides to go ahead and make all "their" spells using the new methods. We are told to NOT pass userdata to addevent correct? This is a big NO NO right? Ok well the problem is when using add event with new metatable and methods, we can't pass the userdata, we pass the id instead. Sure I realize that in the function that is being called from addevent that we can construct the object yet again from the cid, however isn't that bad practice? Is that a wise alternative? I don't know for sure, it just feels like I am doing something that shouldn't be done that way. 

I purpose we either make doCombat() work with combat object created in the new methods, or we make combat:execute() able to work with cid, the same way doCombat() does.

**Comment by marksamman** [comment]
It is not a bad practice to construct the object again from cid in an addEvent callback, it's what you should do. The old combat functions will be moved to compat.lua and be deprecated eventually.

**Comment by Codinablack** [comment]
Ok. That's what I'll do then, just construct the object again. Thank you.
Since I'm commenting one more time anyways, is there any plan for updating spells to use the method I'm talking about with combat:execute(). If I get some free time and no one is planning on doing it I might could find the time to get them done.

**Comment by marksamman** [comment]
Yes, but it's not a priority. You're welcome to submit a pull request if you update them.
