### ISSUE TITLE
Its not an issue, but maybe its possible to add new function.

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1275]
Function what creates CrossHair.

Example:
crosshair(cid, fromPos, posEx)

Currently we only get that crosshair with onUse and on few items.

**Comment by marksamman** [comment]
Please elaborate. What does it on the server side to create a crosshair?

**Comment by whitevo** [comment]
can i still comment?

**Comment by marksamman** [comment]
It is client sided.

**Comment by whitevo** [comment]
yes i know, so can't we do something about it? Cant we force client to make something with SourceCode?

**Comment by djarek** [comment]
Your only option is to add this functionality to the client (which is fairly easy for otclient, very hard for the CipSoft one),
