### ISSUE TITLE
Health bar question

### ISSUE THREAD

**Issue by Luckey1729** [otland/forgottenserver#1276]
I wanted to ask if this is a client-sided issue. This did not occur until I updated my source to newest (used to be ~1700.)

![health bar](http://cyntara.org/img/2015040617492067.png)

I've also noticed that health/mana bar for players now stop at 65535 instead of "overlapping" if anyone is interested.

**Comment by marksamman** [comment]
The health bar is most likely a server issue with large numbers. I'll see if I can reproduce it soon. Health/mana bar stopping at 65535 when you have more HP/mana than that is intentional because 65535 is the highest value we can send in the protocol.

**Comment by Zbizu** [comment]
send it as % then instead of actual value

**Comment by WibbenZ** [comment]
@Zbizu has a good point.
If the value is over 65535, then we return the percentage of the health / mana.
That would also help high exp servers, same goes for player healths etc.

**Comment by Codex-NG** [comment]
This compiled fine, I never tested it tho.
In protocolgame.cpp
`void ProtocolGame::AddPlayerStats(NetworkMessage& msg)
{
	msg.addByte(0xA0);
	// added health percentage
	if (player->getPlayerInfo(PLAYERINFO_MAXHEALTH) > 0) {
		msg.add<uint16_t>(uint16_t(player->getHealth() * 100 / player->getPlayerInfo(PLAYERINFO_MAXHEALTH)));
		msg.add<uint16_t>(100);
	}else {
		msg.add<uint16_t>(0);
		msg.add<uint16_t>(0);
	}
	//msg.add<uint16_t>(std::min<int32_t>(player->getHealth(), std::numeric_limits<uint16_t>::max()));
	//msg.add<uint16_t>(std::min<int32_t>(player->getPlayerInfo(PLAYERINFO_MAXHEALTH), std::numeric_limits<uint16_t>::max()));

	msg.add<uint32_t>(player->getFreeCapacity());
	msg.add<uint32_t>(player->getCapacity());

	msg.add<uint64_t>(player->getExperience());

	msg.add<uint16_t>(player->getLevel());
	msg.addByte(player->getPlayerInfo(PLAYERINFO_LEVELPERCENT));
	msg.addDouble(0, 3); // experience bonus

	// added mana percentage
	if (player->getPlayerInfo(PLAYERINFO_MAXMANA) > 0) {
		msg.add<uint16_t>(player->getPlayerInfo(PLAYERINFO_MANA) * 100 / player->getPlayerInfo(PLAYERINFO_MAXMANA));
		msg.add<uint16_t>(100);
	}else {
		msg.add<uint16_t>(0);
		msg.add<uint16_t>(0);
	}
	//msg.add<uint16_t>(std::min<int32_t>(player->getMana(), std::numeric_limits<uint16_t>::max()));
	//msg.add<uint16_t>(std::min<int32_t>(player->getPlayerInfo(PLAYERINFO_MAXMANA), std::numeric_limits<uint16_t>::max()));

	msg.addByte(std::min<uint32_t>(player->getMagicLevel(), std::numeric_limits<uint8_t>::max()));
	msg.addByte(std::min<uint32_t>(player->getBaseMagicLevel(), std::numeric_limits<uint8_t>::max()));
	msg.addByte(player->getPlayerInfo(PLAYERINFO_MAGICLEVELPERCENT));

	msg.addByte(player->getSoul());

	msg.add<uint16_t>(player->getStaminaMinutes());

	msg.add<uint16_t>(player->getBaseSpeed() / 2);

	Condition* condition = player->getCondition(CONDITION_REGENERATION);
	msg.add<uint16_t>(condition ? condition->getTicks() / 1000 : 0x00);

	msg.add<uint16_t>(player->getOfflineTrainingTime() / 60 / 1000);
}`

**Comment by ranisalt** [comment]
It is not useful at all to scale integers to an integer percentage

**Comment by Codex-NG** [comment]
All i did was take code which was made for an entirely different distro and adapt it to 1.2, so blame the original author :p

**Comment by gugahoa** [comment]
It was feedback, don't take it as an offense.

**Comment by ranisalt** [comment]
So let me explain to prevent further misinterpretation: if you use an integer to behave like a float, you will lose a precious amount of precision. Suppose a player has double the maximum value, ~131k HP, then you can only represent half of the possible values. This is usually not desired.

The code @Codex-NG proposed will work nicely, but it can only represent round percentage values up to 100. That means if that player has 116k HP, roughly 88.5%, it is only possible to represent as 88% (~115.3k) or 89% (~116.6k). Not really significant, but about the HP healed by an ultimate health potion, and that's the loss of precision I was talking about.

The correct solution would be to modify the client to handle larger values, 32 bit are enough to handle up to around level 286 million knights using Tibia hp gain amounts. Unfortunately you can't do that with Tibia client, but you can indeed do with OTClient.

**Comment by Tarliton** [comment]
Sorry to interrupt, but can't you just send to the player the aproximate percentage as an integer and on the server you treat those values as a float or double or anything you want?
I mean the player would just see that he has 88% of life but in reality it would have 88.X or 89.X. If you need to treat his hitpoints as percentage he would have so many that it wouldn't matter if he sees 88% or 87%. What matter is on the server, not on the client.

**Comment by ranisalt** [comment]
Yes, yes, that's what I said. The server is more flexible than the client already :+1: 

As a side effect it's nice not to know exactly how close to death you are, it kind of breaks the statistics :laughing:

**Comment by Codex-NG** [comment]
@ranisalt I see what you are saying now about loss of precision both in your explanation and now my recent understanding of integer division.

The formula should be casted to a decimal value and then rounded up this way you gain rather than lose value.
