### ISSUE TITLE
Weapons Issue

### ISSUE THREAD

**Issue by Luckey1729** [otland/forgottenserver#1280]
If a weapon (sword / axe / club / distance [spear, etc.]) are placed in your **_right_** hand _AND_ you have a shield in your **_left_** hand, the weapon does not work; it will count as fist fighting. BOTH conditions must be met.

![equipment](http://cyntara.org/img/20150408050847367.png)
L = Left Hand
R = Right Hand

Examples:
- Spear [Right Hand]. Shield [Left Hand] = No spear used, **fist fighting**.
- Spear [Right Hand]. Any item (NOT SHIELD) [Left Hand] = Spear used, **distance fighting**.

- Spear [Left Hand]. Any item (INCLUDING SHIELD) [Right Hand] = Spear used, **distance fighting**.

I apologize, this issue is very hard to describe because it is very specific to the parameters mentioned in the first sentence. Feel free to ask for clarification.

**Comment by TheSumm** [comment]
https://github.com/otland/forgottenserver/blob/f775f7d8400adb4bcce49d2c3e1cf981939f1cbf/src/player.cpp#L322

Adding 
```
weaponType == WEAPON_SHIELD
```
to the condition should solve it, I did not see any case where getWeapon is expected to return the shield, getWeaponAndShield is used in those cases.

**Comment by Luckey1729** [comment]
@TheSumm I've tested your change and it seems to be working as expected now.
