### ISSUE TITLE
Browse field client crash 

### ISSUE THREAD

**Issue by rikitrini** [otland/forgottenserver#1283]
Hello guys, well im going to report a bug i checked today with one friend if u have open the browse field and someone use anti push and trash shit under him if you have open the browse field under him you get debug client >.<! its same bug on shadowcores haha if someone can fix! thanks guys

**Comment by WibbenZ** [comment]
I can confirm it.
The bug occurs when all of the slots in the window gets full(pagination system?).

**Comment by rikitrini** [comment]
@WibbenZ right my friend xd

**Comment by Luckey1729** [comment]
Can confirm:

![Debug](http://cyntara.org/img/20150410000549911.png)

The debug occurs when window pagination is expanded. I can place coins under myself until Browse Field shows a window like this:

![Pagination Window](http://cyntara.org/img/20150410000710694.png)

If I add 1 more item, I will debug, regardless of the window I have open (1, 2 or 3.)

**Comment by rikitrini** [comment]
@Luckey1729  yea haha xd when page its full client crash

**Comment by EPuncker** [comment]
I can confirm this as well

**Comment by TechrlzGit** [comment]
Bug confirmed.
