### ISSUE TITLE
Improper weapon actions in weapons.xml

### ISSUE THREAD

**Issue by Luckey1729** [otland/forgottenserver#1285]
~~There is currently no way to remove charges from weapons. For example, a "fiery cranial basher" has 1,000 charges and the charge count does not decrease after each weapon use.~~

~~I have also tried setting ``action="removecount"`` to the weapon (with charges) in weapons.xml. This removes the item after first use instead of decreasing the charge count.~~

Elemental Weapons and Ice Rapier should have ``action="removecharge"`` action in weapons.xml

**Comment by ninjalulz** [comment]
```XML
action="removecharge"
```

**Comment by Luckey1729** [comment]
Thank you, that works!
