### ISSUE TITLE
Players can't "double fall" into holes.

### ISSUE THREAD

**Issue by Luckey1729** [otland/forgottenserver#1288]
For example, this area in the global map is at a demon spawn. You're supposed to step on the hole and fall to the floor below onto another hole that's supposed to take you down to the floor below it.

![Holes](http://cyntara.org/img/20150412010633463.png)

This is the result of stepping on that hole.

![Holes 2](http://cyntara.org/img/20150412025920391.png)

**Comment by comedinha** [comment]
https://github.com/otland/forgottenserver/issues/1216

**Comment by Luckey1729** [comment]
@comedinha This hole bug does not reproduce in the 1.0 series (at least at or before r.1550)
I realize it may be similar but it performs properly on revision 1550. Something has changed since then to make it behave differently.

**Comment by BahamutxD** [comment]
Some stairs are not working properly yet.
Downstairs at ground level. If you go north...
http://i.imgur.com/lt5rOFg.jpg
You end 1 SQM too far. If you go upstairs again...
http://i.imgur.com/RA0Hm1c.jpg
You end 1SQM away again.
http://i.imgur.com/fDS4nV5.jpg

This is happening when going downstairs is north/up direction.
