### ISSUE TITLE
64x Tfs 1.1 - using ORTS datapack  Npc scripts folder Load memory leak 

### ISSUE THREAD

**Issue by Fle-OTL** [otland/forgottenserver#1289]
Hi, 
Recently compiled 64x tfs,
I am using your datapack (amazing btw)
I have hit a few bumps in the road, solved most,
The major problem i am having is with the npcs,
I had to remove the npc scripts folder, because it crashes my server after 2-3 minutes,
I have run the same everything for 48 hours stable without the npc scripts folder.

Mark just asked me too post the problem here, 

maybe you guys can tell me whats going on?

I desperately need this fixed, maybe I can only offer my mapping or graphic design skills in exchange!

Thanks guys, for all your hard work and dedication.

This ORTS datapack is EPIC. 5*'s

Thanks!
-martin

**Comment by TechrlzGit** [comment]
The problem maybe with datapack , here the tfs working like a charm.

**Comment by TheSumm** [comment]
If you find out which group of npcs cause the crash we can fix it or if you can find anything else which might help.

Otherwise this is pretty low priority to me.

**Comment by Fle-OTL** [comment]
Npc Chrak and Npc UzonE are the 2 npcs that are showing errors in console, other then that I dont know.

**Comment by Fle-OTL** [comment]
Maybe you can explain too me how to narrow it down?
 Is it possible this is crashing due to insufficient memory? I have 8gb ram and this is a windows 7 system

**Comment by ninjalulz** [comment]
This is not the correct repository to have this conversation, please close this issue and start a new one over [here](https://github.com/orts/server/issues).

**Comment by JoffreCamacho** [comment]
having the same problem here, will try to erase the npc folder, and make and old school 1 by 1 crash dummie test...
