### ISSUE TITLE
Roshamuul border bug

### ISSUE THREAD

**Issue by WibbenZ** [otland/forgottenserver#1292]
Told him to write it here, since the datapack has no code for this itemid, but he diden't.
https://otland.net/threads/10-76-tfs-1-1-orts-a-real-map-project.204514/page-101#post-2230093
```
19:31 You see an item of type 22158.
Item ID: 22158.
Position: 33630, 32452, 7
```

**Comment by ninjalulz** [comment]
Not a bug, it's supposed to block missiles.
