### ISSUE TITLE
Another wild idea, what actually might exist, but i don't know of.

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1295]
CreatureEvent.
onAttack(cid, target)

Currently we could add the whatever we want to do on attack to all the weapons, but idk, would be nice to just have such creaturescript.

Example Uses.
onAttack(cid, target)
if Player(cid):getStorageValue(???) == 1 then
if Monster(target) then
Monster(target):registerEvent("Something fancy")
end
end

onAttack(cid, target)
if Player(cid):getLevel() > 5 then
some chance to hit player with higer damage and do extra magic effects.

Etc.

**Comment by EvilHero90** [comment]
can be done with
Creature:onAreaCombat(tile, aggressive)
Creature:onTargetCombat(target)
or
onHealthChange(creature, attacker, primaryDamage, primaryType, secondaryDamage, secondaryType, origin)
onManaChange(creature, attacker, manaChange, origin)

**Comment by whitevo** [comment]
where you use onTargetCombat?
Seems like function what seems like a thing i was looking for, but i don't understand how to use as main function. Its more like a method inside the function.

onHealthChance and onManaChange can only be applied trough registering event on creature.
But that's why i would like a onAttack() function.
So i could register events IF the something i ask is true.

**Comment by EvilHero90** [comment]
onTargetCombat is an event (event folder)
check events.xml and creature.lua you'll find everything there.
