### ISSUE TITLE
only one of each Unique ID allowed on map

### ISSUE THREAD

**Issue by Alscara** [otland/forgottenserver#1299]
As of nightly revision 700, only one of each unique id is allowed on the map. This totally breaks some of my scripts that utilized using the same one more than once. Can it at least be a config option or something to decide whether to allow just one or several?

**Comment by marksamman** [comment]
No. A unique id must be unique.

**Comment by Alscara** [comment]
but why now but never before?

**Comment by EPuncker** [comment]
that is called "update" and sometimes "evolution"

**Comment by yrpen** [comment]
Use action id in this case

**Comment by ranisalt** [comment]
Are you even serious?

You have been using UNIQUE ids the wrong way your entire life and now that they work properly you don't like it...

**Comment by djarek** [comment]
It's not a bug, it's a feature :D.

**Comment by yrpen** [comment]
@djarek  :+1: You made my day
