### ISSUE TITLE
Offline Magic Level only trains Shielding

### ISSUE THREAD

**Issue by Blaggo** [otland/forgottenserver#1309]
I am using TFS 1.0. When using the magic level offline trainer statue or training magic level in a bed, it only trains shielding. All other offline trainers work perfect, only the magic level one does not work. 

I found one solution on otland.net to change line 740 in src\game.cpp from:

addOfflineTrainingTries(SKILL_MAGLEVEL, offlineTrainingTime * (vocation->getManaGainAmount() / gainTicks));

to:

addOfflineTrainingTries(SKILL_MAGLEVEL, offlineTrainingTime * ((double)vocation->getManaGainAmount() / gainTicks));

This still did not solve the issue.. :(

Any help would be greatly appreciated. Thanks for your time! :)

**Comment by marksamman** [comment]
If you had to make that change in game.cpp, you weren't using the release version of 1.0. Use the support forum on otland.net.
