### ISSUE TITLE
addEvent suggestion, unless it already exists.

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1313]
I did not find a easy solution so i had to work around it, but i what i would like to see is option to increase already activated addEvent duration.
derp = addEvent(function, 3000)
increaseEvent(derp, 3000)
This should take the current time what has passed and then set new time for it before that function activates.

and while we at it, why not
decreaseEvent(derp, 1000)
If decreaseEvent goes down to 0 or less then instant function activation.

**Comment by marksamman** [comment]
You can reschedule an event by stopping it and adding it again.

**Comment by whitevo** [comment]
but problem is i don't want to stop it. I want to activate it, but not wait until timer is over.

**Comment by marksamman** [comment]
https://otland.net/forums/support.16/

**Comment by whitevo** [comment]
>.>  i have already solved the problem for myself, but just saying.. if you would add these 2 functions for source then that would make it so much nicer..

**Comment by ranisalt** [comment]
It makes much more sense rescheduling it in Lua than hiding it in the sources. The events need to be stopped and rescheduled again anyways.

**Comment by whitevo** [comment]
in lua i can't track event time in millseconds (i can do it with seconds)
in lua what we have to do:
addEvent2(addevent parameters)
function addEvent2(...)
make a global table. make key with what holds the queue number.
to that key add event and how many seconds is maximum lenght of addevent and time when was que made.

Now i can start rescheduling events with other custom functions.

I believe the same result could be added to sourcecode much more effectively.
But whatever, maybe it just m who is using addEvent extensively almost in every script i make xD

**Comment by marksamman** [comment]
You can track it with milliseconds using os.mtime().
