### ISSUE TITLE
Idea to compress outfits.xml

### ISSUE THREAD

**Issue by rowaraujo** [otland/forgottenserver#1315]
```
<?xml version="1.0" encoding="UTF-8"?>
<outfits>
	<outfit id="1" male="128" female="136" name="Citizen" premium="0" unlocked="1" enabled="1" />
	<outfit id="2" male="129" female="137" name="Hunter" premium="0" unlocked="1" enabled="1" />
	<outfit id="3" male="130" female="138" name="Mage" premium="0" unlocked="1" enabled="1" />
	...
</outfits>
```

I'm developing a web system in php that takes the outfits.xml file.
With the above XML is faster reading and the code to read the file is easier to do.

**Comment by ranisalt** [comment]
You might as well store in your database instead, which would be ultimately faster plus this is not a data that needs to be re-read every single time.

**Comment by rowaraujo** [comment]
Yes. But that's not the point. The above code is easier to get to add to the database as well. It is easier to read, edit and update. Improves everything.

**Comment by marksamman** [comment]
Male and female outfits can have different names. You can just add the tags to your own outfits.xml, the server will ignore them. We won't change the format.
