### ISSUE TITLE
Ladder bug when any item is below. 

### ISSUE THREAD

**Issue by lipix** [otland/forgottenserver#1316]
I can't use ladder when any item is below, and fire too. impossible climb the stairs with have fire below.

**Comment by lipix** [comment]
<a href="http://1.ii.gl/H9ZFVpd-.png" target="_blank"><img src="http://1.ii.gl/H9ZFVpd-.png" alt="ImgLand.net image" /></a>

Anything u put below!

**Comment by EvilHero90** [comment]
works fine for me, with fields or items on the same place as the ladder.

**Comment by lipix** [comment]
What could be wrong ?

**Comment by kornholi** [comment]
You are using outdated server or scripts

**Comment by lipix** [comment]
But what should I do to work it? Because my server is upgraded to version 1.1 of TFS

**Comment by EPuncker** [comment]
update your ladder script maybe?

**Comment by lipix** [comment]
teleport.lua ?

http://pastebin.com/5bDWaGa0

**Comment by dalkon** [comment]
Could not reproduce, update your executable, the script cannot be the problem.

**Comment by lipix** [comment]
My executable is updated. I'm using last revision!

**Comment by beastn** [comment]
This error is the same for me.. Compiled the latest TFS 1.1 yesterday and using it with ORTS datapack. Guessing it could be the datapack. Will play around and let you guys know.

**Comment by marksamman** [comment]
Make sure you're also using the official OTB file.

**Comment by gianflogao** [comment]
please someone help? I have the same problem
