### ISSUE TITLE
Remove distinction between static and dynamic tiles.

### ISSUE THREAD

**Issue by djarek** [otland/forgottenserver#1318]
The main difference between static and dynamic tiles is that the former explicitly stores 2 vectors on the heap. Judging by the comments it is done to save memory, however I believe that the added complexity is not worth saving 64 bytes per static tile. What's your opinion?

**Comment by marksamman** [comment]
It's definitely worth it, in fact, I would argue that it could be worth it to add more tile classes and convert them to a more appropriate tile class if necessary, e.g.:
a tile class that only stores ground
a tile class that only stores ground and items (no creatures)
a tile class that only stores items (no ground or creatures)

Assume a 5000x5000 map where half the tiles are static.
((5000*5000)/2) * 64 = 800000000 bytes
800000000 / 1024 / 1024 = 762 MB

We could even save more memory by storing ground as the first index in the item list for dynamic tiles. folly/small_vector may also be of interest.

**Comment by djarek** [comment]
Looking at the way floors are implemented, it would probably make more sense to use some sort of CoW(Copy-on-Write) semantics for static tiles instead (which would reduce memory usage even more than the current system).

**Comment by marksamman** [comment]
That would make the complexity significantly worse than what we have now unless you rewrite a lot of code, because tiles carry tilePos. Tile must return a position because it implements the Cylinder interface.

**Comment by djarek** [comment]
You're totally right, it's probably not worth it. I guess that if we ever got at that point we might as well rewrite most of the game logic anyway :D.
