### ISSUE TITLE
Error in Vocation Attackspeed Property [$10]

### ISSUE THREAD

**Issue by brunominervino** [otland/forgottenserver#1319]
Hello, I have tested the attackspeed property from vocations.xml, and decrease it to 100, for example.
It only work when I attack the creature while I moving my character, if I stand, attack is set to default.

If you don't understand, watch this movie please, have only 20 seconds:
https://youtu.be/8vnhZzNQXVk

##

**Comment by marksamman** [comment]
This is intentional at the moment, but we're considering checking attack with lower intervals in the future. You can try to apply this patch to your source code: https://github.com/otland/forgottenserver/pull/1305

**Comment by brunominervino** [comment]
Hmm ok man.
This change (#1305) don't work at distance weapons :(

**Comment by ranisalt** [comment]
This is now fixed, check the PR.

**Comment by brunominervino** [comment]
@ranisalt @marksamman, I have post a $10 for this issue. Please add bounty label.

**Comment by ranisalt** [comment]
@brunominervino check which of #1305 or #2109 works for you.

**Comment by brunominervino** [comment]
@ranisalt no :( Look a gif on pr, my idea is do anything to implement these possibilities
