### ISSUE TITLE
Compilling tfs 1.1 to 8.60 or older client versions

### ISSUE THREAD

**Issue by kalebealvs** [otland/forgottenserver#1320]
Besides change the min and max target version on definitions header(src/definitions.h) from 1076(the standard version on 1.1) to 860, is there anything else I need to do to work with older client versions like 8.60?

I've changed that and compilled the source, But when I try to connect to the server from yatc client it freezes before load the character list, and show this message on console:

```
ERROR: protected lua call failed: LUA ERROR:
C++ call failed: InputMessage eof reached
stack traceback:
        [C]: ?
        [C]: in function 'getString'
        /gamelib/protocollogin.lua:229: in function 'parseCharacterList'
        /gamelib/protocollogin.lua:166: in function </gamelib/protocollogin.lua:148>
```

Searching though this repository issues I found this other [issue](https://github.com/otland/forgottenserver/issues/208) with a similar error that was claimed to be a client error.
Turns out in my case Isn't just yatc that shows this message. When I try to login with the standard 8.60 client with ipchanger, the client crashes with critical error message.

**Comment by marksamman** [comment]
Yes, a lot. https://otland.net/forums/support.16/
