### ISSUE TITLE
Empty vials going to main backpack on use

### ISSUE THREAD

**Issue by yugokhan10** [otland/forgottenserver#1322]
I'm not expert doing this but I've been trying to fix this using old potions.lua files from other servers but no success... I believe this might be something different on the sources but i have no idea where to look for... If you guys tell me a hint of where i can look for this I believe i can fix this little issue XD ty

**Comment by PrinterLUA** [comment]
https://otland.net/forums/support.16/

**Comment by yugokhan10** [comment]
srry what I'm supposed to find there?
