### ISSUE TITLE
Small Issue in Items.xml

### ISSUE THREAD

**Issue by Alscara** [otland/forgottenserver#1324]
forward slash to close item that has an attribute now at item id 7539

**Comment by onzure** [comment]
lua script ERROR: (EVENT INFERFACE)
DATA/SCRIPTS/EVENTS/SCRIPTS/PLAYER.LUA:PLAYER@ONLOOK
DATA/LIB/CORE/GAME.LUA:12: ATTEMPT TO INDEX GLOBAL 'BOT" (A NILL VALUA)
STACK TRACEBACK
c:?
DATA/LIB/CORE/GAME.LUA:12: IN FUNCTION 'COVERTIPTOSTRING'

HEKP :d

**Comment by Alscara** [comment]
completely unrelated. this is not a support board, it's a resolved issue, post on otland if you need support @onzure
