### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by att3** [otland/forgottenserver#1325]
I am using debian 8 (jessie), and currently gcc 4.8 is installed.
When trying to build this error pops up:
![image](https://cloud.githubusercontent.com/assets/6162681/7445626/f131eb28-f1c3-11e4-8908-0d3b90a83e12.png)
I have tried even re-installing another OS (debian 14.10 and 15.~, yet the same error occurs.)
Does anyone have any idea about this issue?

The machine can build tfs 1.0 (release) though.

**Comment by kornholi** [comment]
Works for me with GCC 4.9.2. Which exact version of GCC are you using?

**Comment by marksamman** [comment]
How much free memory do you have on the machine, and what command are you using to build?

**Comment by ranisalt** [comment]
I can compile with GCC 5.1 on Arch Linux. If you have under 512M memory the compiler may be getting killed by the OS, in which case I would recommend you making a swap file for temporarily increasing memory to at least 1G.

**Comment by HeavenIsLost** [comment]
We are using the same dedicated server. It has 32 gb ram, so at first its not the problem. The mostly strange thing is if i downgrade from gcc 4.9.2 to 4.8.1 i can compile tfs 1.1, but after sometime it stop working again.

**Comment by att3** [comment]
Using, make command - build it as the tutorial says here.
MemTotal:       32913556 kB
MemFree:        18937940 kB

I installed ubuntu 14.10 back, the same error occurs, I am highly suspecting that it's hardware error.

What makes it strange though, earlier the machine had gcc 4.8~, and it built successfully once, installed gcc 4.9 and this error still occurred.
And it builds tfs 1.0 fine, but not 1.1.

**Comment by marksamman** [comment]
Try disabling cotire in CMake.

**Comment by att3** [comment]
Thanks for the tip, it builds successfully now.
https://github.com/otland/forgottenserver/commit/012884b5f388269c2d4a4602a2f898b27b31355b

I am still quite confused why that error occurs. Can't build it with precompiled headers?
I ran some tests, there were no issues with RAM, however there was something off with CPU, the computer froze for 20+seconds during the test. (shouldn't happen according to OVH)
Then I ran the test again and it ran fine. (didn't freeze)

Is it possible that CPU would have something to do with this?
Using Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz

**Comment by marksamman** [comment]
I have no idea, I suggest submitting a bug report to gcc like the error message you get suggests.

**Comment by marksamman** [comment]
I've updated the cotire CMake file to 1.7.2, you could try again with the new version to see if it makes any difference.

**Comment by att3** [comment]
i will do that (report it there).
I have tried compiling after https://github.com/otland/forgottenserver/commit/3ff4fc1e3c247d80e33f8a40c7d6cbef2e59fd31 update without success.

**Comment by marksamman** [comment]
Okay, I'll just revert back to the old cotire version then if it didn't make any difference to you, since Travis doesn't have the required CMake version for it anyway.

**Comment by marksamman** [comment]
If you submitted the bug report to gcc, it would be nice to have a reference to the bug report in this issue (assuming there's a public URL to your bug report).
