### ISSUE TITLE
can't create empty fluid containers with /i

### ISSUE THREAD

**Issue by Alscara** [otland/forgottenserver#1326]
Nothing major, but empty fluid containers cannot be created because /i doesn't handle 0 as a type/count and defaults to 1, which for fluid containers is water. Without a number parameter, it just defaults to 1 as well. Would be nice if /i could process 0 as a type if the item in question supports it.

**Comment by ranisalt** [comment]
I'm looking on this issue, it seems to be a single line in the talkaction script.

**Comment by Alscara** [comment]
yeah, count = math.max(0, count) fixes it, but I imagine I'm not the only person who's going to want this option, so I figured it would make sense to add it in a commit

**Comment by ranisalt** [comment]
Yeah, that was it :) fixed!
