### ISSUE TITLE
starting  tfs 1.0  On  win 7 32x issue

### ISSUE THREAD

**Issue by Ahmedmiramar** [otland/forgottenserver#1329]
when i try to open the theforgottenserver.exe after putting all the files of the server it starts and exits fast that i cant notice what it says plx rep++ help me

**Comment by WibbenZ** [comment]
Got the same thing with 1.1 and 1.2, check your database connection etc.
Or try to take a screenshoot and add it to paint and see what it says xD

**Comment by ranisalt** [comment]
Probably database, it's one of the first errors that can occur. Learn how and fire it from a console so it won't leave upon closing.

**Comment by rowaraujo** [comment]
You can start via CMD for check notice!

**Comment by Ahmedmiramar** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10529996/7469645/b2701980-f31e-11e4-8353-402bc61c356e.png)

that is what it says

**Comment by gugahoa** [comment]
I think this would be better discussed on the forum
https://otland.net/forums/support.16/
