### ISSUE TITLE
Client crash when GM outfit use mount

### ISSUE THREAD

**Issue by Pwntus** [otland/forgottenserver#1334]
If the player has a GM outfit and try to mount (any mount), the Tibia Client will crash.

![Error Report](http://i.imgur.com/pmqpMgk.jpg)

**Comment by WibbenZ** [comment]
Did you use the GM outfit? Mine crashed a while ago when I did that.
Fix would be to send a sorry not posible if the player has that outfit when he executes the mount.

**Comment by Grozzy** [comment]
WibbenZ, you're right. This seems to happen only when you have the GM outfit.

**Comment by Luckey1729** [comment]
Is this limited to the GM outfit (75) or any outfit that doesn't "change" to a mounted position?

**Comment by WibbenZ** [comment]
I have atleast only found this issue with the GM outfit.

**Comment by Luckey1729** [comment]
I just used outfit looktype 680. ![Rolly!](http://vignette3.wikia.nocookie.net/tibia/images/2/23/Glooth_Bomb.gif/revision/latest?cb=20141121103106&path-prefix=en)

Came across the same debug.

**Comment by ranisalt** [comment]
We can add a flag to the outfit type to check if it was loaded from outfits.xml or not. The ones not added from the XML file do not have any mounts, hence they WILL debug if you try to mount with them. Maybe there is another way to check this, but this is the easiest one that comes up to me.

**Comment by WibbenZ** [comment]
You could also just use the Creature:onChangeOutfit event, that way you don't even need any source edits.

**Comment by gunzino** [comment]
I can confirm this. Fixed by editing player.cpp toggleMount() function by checking if the player outfit is in the outfits.xml using the Outfit instance.

**Comment by gunzino** [comment]
const Outfit* newOutfit = Outfits::getInstance()->getOutfitByLookType(getSex(), defaultOutfit.lookType);
if(!newOutfit)
return false;


Add this to Player::toggleMount(bool mount) 
after if (mount) {

**Comment by ranisalt** [comment]
Fork and make a PR :) or I can do it for you

**Comment by gunzino** [comment]
Gonna do it for the first time. ;]
