### ISSUE TITLE
How to calculate header UIDs?

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#1346]
I didn't understand how should I calculate the header UIDs. For instance, the header for [src/combat.h](src/combat.h) is `B02CE79230FC43708699EE91FCC8F7CC`, but I have tried:

- /src/combat.h
- src/combat.h
- /combat.h
- combat.h
- all of the above in uppercase

But neither of those is MD5'd to the hash present in the header file. How should I calculate the hash?

**Comment by marksamman** [comment]
I think many of the existing hashes were just randomly generated by the person who submitted a PR to use UUID's. We prefer using the MD5 hash of the files relative path in the repository, in this case:
src/combat.h
