### ISSUE TITLE
Monster outfit spell

### ISSUE THREAD

**Issue by peonso** [otland/forgottenserver#1354]
I can't get this to work:
Efreet/Marid `<attack name="outfit" interval="1000" chance="17" range="7" monster="rabbit" duration="20000"/>`

But this two do work:
Serpent Spawn `<attack name="outfit" interval="1000" chance="9" range="7" item="3976" duration="4000"/>`
Vampire `<defense name="outfit" interval="1000" chance="1" monster="bat" duration="6000"/>`
##

**Comment by ranisalt** [comment]
Better example to your question: https://github.com/otland/forgottenserver/blob/master/data/monster/Glires/halloweenhare.xml

**Comment by peonso** [comment]
It works differently than Djinn, if it's how `outfit` is working when set as an attack (as area spell that transform both the monster that is casting and the target), it still don't work with `rabbit`, as it just transform itself, and not the target, while it works with `dwarf geomancer`. It still don't allow me to have the correct behavior for Djinn spell, I would need a spell script for it? It's really bugged or working as intended (not working with Marid/Efree)?

**Comment by ranisalt** [comment]
Well, an ATTACK spell that changes outfit should change the target outfit, while a DEFENSE spell should change the caster outfit (like the vampire -> bat). It doesn't matter if you use range or area.

Are you using the default Marid, i.e. [have exactly those lines in this file](https://github.com/otland/forgottenserver/blob/master/data/monster/Djinn/marid.xml#L33-L35)?

Have you considered you may have a wrong chance and the monster just simply isn't changing the target outfit because it never happens to use this spell?

**Comment by EPuncker** [comment]
if you are dealing with range you need to set a target="1" I guess

**Comment by gugahoa** [comment]
Just as @EPuncker said, if you want the target to change outfit, you set target="1", for example with the http://tibia.wikia.com/wiki/Incredibly_Old_Witch the XML is as follow: http://pastebin.com/V8mH0Xfm

**Comment by peonso** [comment]
@ranisalt Yeah dude, same lines,  just increasing chance to `90` to easily see if it works.
@EPuncker @gugahoa just added `target="1"` makes no difference, still does not work.

As I said, Serpent Spawn is working with this lines `<attack name="outfit" interval="1000" chance="9" range="7" item="3976" duration="4000"/>`

I changed Marid/Efreet monsters to `dwarf geomancer` and it's now working. While testing [halloweenhare.xml](https://github.com/otland/forgottenserver/blob/master/data/monster/Glires/halloweenhare.xml) I saw it's transforming to `dwarf geomancer` `crab` `bat` `item="2096"`, and also `rabbit`, but it would transform itself only and not the target while doing so, it did not transformed on anything else. What would justify just strange behavior?

**Comment by Emky** [comment]
anyone found a solution for this yet?

**Comment by raymondtfr** [comment]
A monster casting a spell as described in that line will work just fine using ``monster="rabbit"``. If such spell has a combat area, then the caster monster itself and other affected creatures will be transformed to a "rabbit".

I didn't understand much of what @peonso said, but thinking this further, if a monster has such spell, and it also has a combat area, then the surrounding creatures affected by the combat area spell should not be transformed to any outfit if the tag ``target="0"`` is used, only the caster monster should be.

If its the second case, then it is not a "bug", but rather a not included feature. I don't this is a valid issue.

@ranisalt

**Comment by peonso** [comment]
@raymondtfr 
Not related to that at all. Have you tested the examples people gave?

**Comment by raymondtfr** [comment]
Yes, I did. Everything was working fine, but as I have said earlier, I didn't get much of what you were trying to say. If you could update the issue main comment thoroughly with the issue template, and confirm you can reproduce it as of now (2017), that would help us identifying what this fuss is all about.

**Comment by peonso** [comment]
@raymondtfr I wasn't clear? I couldn't use "rabbit" or "rat" as parameter of a monster outfit spell and got it to work. Tested current code, and **I can't reproduce it**, seems to be working as intended.
