### ISSUE TITLE
Actions::useItem and Actions::useItemEx

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1355]
At the start of those methods, there's a check if a player can do the action, and then set the next action task as nullptr. But those methods, before being called already have those same checks and already set the next action task as nullptr. Is there a reason for that double check?

**Comment by ranisalt** [comment]
If there is already the check in this method, there is no need to guarantee before calling them except when we need to guarantee this condition for another thing. Have you checked that?

(pls link the file)

**Comment by gugahoa** [comment]
in game.cpp, the method is called on the following methods:
Game::playerUseWithCreature
Game::playerUseItem
Game::playerUseItemEx

**Comment by marksamman** [comment]
No reason, I've removed them.
