### ISSUE TITLE
MySQL losing connection

### ISSUE THREAD

**Issue by godely** [otland/forgottenserver#1357]
![screen shot 2015-05-15 at 10 41 49](https://cloud.githubusercontent.com/assets/3101049/7653831/1bb1fa1c-faef-11e4-9ea3-18a802ecda3d.png)

I'm using latest stable release, v1.1. My MySQL server is a remote one, from Amazon RDS, but it didn't use to be a problem on v1.0.

**Comment by lipix** [comment]
I have this problem too !

**Comment by marksamman** [comment]
Which operating system are you running?
Which version of MySQL client?
Which version of MySQL server?

@lipix are you also using Amazon RDS?

**Comment by lipix** [comment]
No @marksamman . I'm using windows, no log erros, but i cant to log in the game !

**Comment by godely** [comment]
1. OS X Yosemite
2. Client: 5.6.21
3. Amazon RDS Engine: MySQL 5.6.22

**Comment by ranisalt** [comment]
I have a working connection between TFS running on EC2 and MySQL running on RDS without problems.

What parameter group are you using on your RDS?

**Comment by ranisalt** [comment]
Well I guess he fixed it...

**Comment by juniorb2ss** [comment]
I have the same problem with amazon cloud.

My structure is:
t2.micro running the site
c3.large running the server
t2.micro database
t2.micro read replicate

Right time the service starts getting caught and losing connection to the database.

**Comment by WibbenZ** [comment]
This has to be related to the companies, ive used 1.0, 1.1, 1.2 on bigger VPS and dedi companies and never had this issue.
Highly doubt it's the code's fault, since alot more people would complain.

**Comment by godely** [comment]
I'm not having this problem anymore since I started using an Ubuntu 14.04 instance :)

**Comment by triath** [comment]
I'm having the same problem connecting to a remote mysql server. It's only the checkExpiredOffers query that is affected.
```
[Error - mysql_real_query] Query: SELECT `id`, `amount`, `price`, `itemtype`, `player_id`, `sale` FROM `market_offers` WHERE `created` <= 1436613086
Message: Lost connection to MySQL server during query
```
* TFS server os: Debian 8.1 x86_64 
* Remote mysql server os: Debian 7.8 x86_64
* Mysql client version:  5.5.44
* Mysql server version: 5.5.44

I don't know if the problem is in TFS or on the server but since this is still unconfirmed I added my info.
If there is any suggestions on what I can do to troubleshoot this I'll try it and report back.
So far I tried to increase *wait_timeout*. *interactive_timeout* and *connect_timeout* on the mysql server without success.

**Comment by marksamman** [comment]
I'm pretty sure that it's because of wait_timeout, and it shouldn't be a problem unless that error is repeated every second. The server will re-establish the connection and run the query again.

**Comment by ranisalt** [comment]
I could reproduce this problem, it happens pretty frequently on Amazon, I guess it's due to their machines rotation.

**Comment by marksamman** [comment]
I don't think there's anything we can do about this, the only thing I can think of if increasing wait_timeout on the server didn't help, is to also try to set it in the client, but the error will persist if the config is untouched on the server. You could also dispatch some lightweight async queries (e.g. "SELECT 1") frequently to maintain activity in the database tasks thread if that error bothers you.
