### ISSUE TITLE
1194826 introduces problem

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#1358]
I have synced my fork with the upstream and recompiled my local test server, and found out it was unbearably slow. To log in, most of the time it took so long the server considered the player has disconnected, and after logging, it took several seconds to move, say something , attack or whatever I tried doing.

I have bisected and checked a few commits and this behavior started at commit 1194826aac44098cffebb71ff70c9bf5e9af0b7a. Before it, the server runs fine. I couldn't figure out what code has caused this problem, but reverting it seems to solve.

**Comment by djarek** [comment]
Found the issue... How the hell did I miss that, seems so obvious now...

**Comment by ranisalt** [comment]
Thanks, @djarek
