### ISSUE TITLE
Create party by command TFS 1.1

### ISSUE THREAD

**Issue by JoseEduardo** [otland/forgottenserver#1365]
I saw that on github TFS has this page:
https://github.com/otland/forgottenserver/wiki/Metatable:Party

but the examples are not clear, as I do to create a party with some player, noting that this party does not exist yet.
For example, we have the desert quest (as in Tibia Global) as I do for by the fourth player in a party without them to do anything.

I created a topic in otland ( https://otland.net/threads/create-party-by-command-tfs-1-1.232438/#post-2241406 ) with the matter, but did not get good results, I tried to create that way and it was not possible:

```
local player1 = Player(getPlayerByName('Admin'))
local party = Party(player1)
party:addInvite(player1)
```

but I get it in return

```
attempt to call global 'Party' <a table value>
```
##

**Comment by djarek** [comment]
As it is now, you cannot create a new party within the script system. You can only get a party object (representing an already existing party) by calling player:getParty().

**Comment by JoseEduardo** [comment]
it would be possible to accomplish this in another way?

**Comment by djarek** [comment]
You would need to write a lua interface function which allows a new party to be created.

**Comment by JoseEduardo** [comment]
There is some chance or interest in doing that? or a kindness to tell me where to start?

**Comment by WibbenZ** [comment]
A tip would be to look here, ttps://github.com/otland/forgottenserver/blob/master/src/game.cpp#L4716-4721

**Comment by JoseEduardo** [comment]
I do not know how does one pull request if you can make and test it, I did two LUA functions that help a lot.

luascript.h
```
static int32_t luaDoCreateParty(lua_State* L);
static int32_t luaDoJoinParty(lua_State* L);
```

luascript.cpp
```
	//doCreateParty(cid, invitedPlayer)
	lua_register(m_luaState, "doCreateParty", LuaScriptInterface::luaDoCreateParty);

	//doJoinParty(lider, invitedPlayer)
	lua_register(m_luaState, "doJoinParty", LuaScriptInterface::luaDoJoinParty);
```

```

int32_t LuaScriptInterface::luaDoCreateParty(lua_State* L)
{
	//doCreateParty(cid, invitedPlayer)
	Player* player = getPlayer(L, 1);

	if (player){
		Party* party = player->getParty();
		if (!party) {
			party = new Party(player);

			Player* invitedPlayer = getPlayer(L, 2);
			party->invitePlayer(*invitedPlayer);
		}
		else if (party->getLeader() != player) {
			std::ostringstream ss;
			ss << player->getName() << " is already in a party.";
			player->sendTextMessage(MESSAGE_INFO_DESCR, ss.str());
			lua_pushboolean(L, false);
		}

	}
	else{
		reportErrorFunc(getErrorDesc(LUA_ERROR_CREATURE_NOT_FOUND));
		lua_pushboolean(L, false);
	}

	return 1;
}

int32_t LuaScriptInterface::luaDoJoinParty(lua_State* L)
{
	//doJoinParty(lider, invitedPlayer)
	Player* player = getPlayer(L, 2);
	if (!player) {
		reportErrorFunc(getErrorDesc(LUA_ERROR_CREATURE_NOT_FOUND));
		lua_pushboolean(L, false);
	}else{
		Player* leader = getPlayer(L, 1);
		if (!leader || !leader->isInviting(player)) {
			reportErrorFunc("Invite not found");
			lua_pushboolean(L, false);
		}else{

			Party* party = leader->getParty();
			if (!party || party->getLeader() != leader) {
				reportErrorFunc("Party not found");
				lua_pushboolean(L, false);
			}
			else{

				if (player->getParty()) {
					player->sendTextMessage(MESSAGE_INFO_DESCR, "You are already in a party.");
					lua_pushboolean(L, false);
				}
				else{
					party->joinParty(*player);
				};
			};
		};
	};
	return 1;
}
```

there may be errors, if someone can do the pull will greatly help these simple functions.
