### ISSUE TITLE
[bug] playerReportBug

### ISSUE THREAD

**Issue by paulosalvatore** [otland/forgottenserver#1369]
When I try to 'Report Coordinate' in game, I am immediately disconnected.

When checking the file 'data/reports/PlayerName.txt' the log has been created, but without the message typed by the player.

------------------------------
Name: PlayerName [Position X: 1000 Y: 1000 Z: 7]
Bug Report:

The 'Bug Report' field is empty even though I've typed in game.

I tried to check the C++ code but I could not solve, just realized that this line is disconnecting me:
```
	if (msg.isOverrun ()) {
		disconnect ();
	}
```
File: protocolgame.cpp Line 549 to 551

Does anyone have any idea how to solve this issue?

**Comment by Decretis** [comment]
Yep. Same here.

**Comment by EPuncker** [comment]
same here

**Comment by Codinablack** [comment]
confirmed
