### ISSUE TITLE
Errors compiling on MAC OSx

### ISSUE THREAD

**Issue by Vysius** [otland/forgottenserver#1373]
Hello everyone,
I've just cloned the project on my mac, but cant compile it properly. I appreciate any help.
Just followed the guide on compiling on mac from the wiki and got this error:

MacBook13:build samuel$ make
[  1%] Generating CXX prefix source cotire/tfs_CXX_prefix.cxx
[  2%] Generating CXX prefix header cotire/tfs_CXX_prefix.hxx
[  3%] Building CXX precompiled header cotire/tfs_CXX_prefix.hxx.pch
In file included from /Users/samuel/projects/forgottenserver/build/cotire/tfs_CXX_prefix.hxx:4:
In file included from /Users/samuel/projects/forgottenserver/build/cotire/tfs_CXX_prefix.cxx:4:
In file included from /Users/samuel/projects/forgottenserver/src/otpch.h:25:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
1 error generated.
CMake Error at cmake/cotire.cmake:1660 (message):
  cotire: error 1 precompiling
  /Users/samuel/projects/forgottenserver/build/cotire/tfs_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake/cotire.cmake:3165 (cotire_precompile_prefix_header)

make[2]: *** [cotire/tfs_CXX_prefix.hxx.pch] Error 1
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2
 

(New to commenting on git, dunno how to force the error on a code tag)

EDIT: Using Yosemite 10.10

**Comment by Nu77** [comment]
This are compiling fine here.
Do you already have upgraded XCode/Command Line Tools ?

**Comment by Vysius** [comment]
Hi Nu77, thx for your answer:
I have not upgraded anything about xCode. 

As i said, i just followed up the instructions of the wiki to compile on OSx.
They say about installing homebrew and cmake, which i already did, but cant execute the make command.


Im really new at developing through apple environments, but i have my windows pc fucked up atm, and maybe for a long time. I dont want to use a VM for this.

**Comment by Nu77** [comment]
Type on terminal and try again:
```bash
xcode-select --install

**Comment by Vysius** [comment]
Already installed: 
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by Vysius** [comment]
I've installed XCode through the appstore, and still no luck on compiling

**Comment by Nu77** [comment]
As i expected, this is a problem with CLT 6.3, upgrade it to 6.3.1 ( which was released by apple some days ago ) should fix this problem.

**Comment by Vysius** [comment]
Thanks Nu77, i updated CLT in the appStore and it compiled. (It was weird it said all the time 1% durin all the compiling proccess, but i have the exec file. Now its compiled, its weird i cant make it work. I copied the tfs compiled server on the root folder, where the data and config.lua are, but it still says cant find config.lua. May the comments on the lua cause this?

**Comment by Vysius** [comment]
Ok, i solved this, executing through terminal. TY for ur help, i close the issue.

:dancer:
