### ISSUE TITLE
[Question] Login with session key

### ISSUE THREAD

**Issue by Pwntus** [otland/forgottenserver#1378]
*I'm a little bit out of my league so please excuse me if the question is kind of dumb, but I try to understand as much as I can;*

I see that in **ProtocolLogin::onRecvFirstMessage()** the account name and password is extracted from the session key separated by a \n. If the session key were to be an alphanumeric string of length 30 (as CipSoft does), how would I proceed to get the account name and password?

**Comment by marksamman** [comment]
https://otland.net/forums/support.16/

**Comment by froomzim** [comment]
Hi guys, fixed on protocollogin.cpp

--- Before ---
	// Generate and add session key
	static std::independent_bits_engine<std::default_random_engine, CHAR_BIT, unsigned short> rbe;
	std::string sessionKey(16, '\x00');
	std::generate(sessionKey.begin(), sessionKey.end(), std::ref(rbe));

	output->addByte(0x28);
	output->addString(tfs::base64::encode({sessionKey.data(), sessionKey.size()}));

	if (!db.executeQuery(fmt::format(
	        "INSERT INTO `sessions` (`token`, `account_id`, `ip`) VALUES ({:s}, {:d}, INET6_ATON({:s}))",
	        db.escapeBlob(sessionKey.data(), sessionKey.size()), account.id, getConnection()->getIP().to_string()))) {
		disconnectClient("Failed to create session.\nPlease try again later.", version);
		return;
	}
	
	
--- Fixed ---

// Generate and add session key
	static std::independent_bits_engine<std::default_random_engine, CHAR_BIT, unsigned short> rbe;
	std::string sessionKey(16, '\x00');
	std::generate(sessionKey.begin(), sessionKey.end(), std::ref(rbe));

	output->addByte(0x28);
	output->addString(tfs::base64::encode({sessionKey.data(), sessionKey.size()}));

	// Convert sessionKey to hexadecimal
	std::string sessionKeyHex;
	for (unsigned char c : sessionKey) {
		sessionKeyHex += fmt::format("{:02x}", c);
	}

	// Insert the session into the database
	if (!db.executeQuery(fmt::format(
	        "INSERT INTO `sessions` (`token`, `account_id`, `ip`) VALUES (UNHEX('{}'), {}, INET6_ATON('{}'))",
	        sessionKeyHex, account.id, getConnection()->getIP().to_string()))) {
		disconnectClient("Failed to create session.\nPlease try again later.", version);
		return;
	}
