### ISSUE TITLE
[Question] When removing a container, the items inside does not call onRemoved()

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1384]
Example:
We have a new type of container, gugahoaContainer.
gugahoaContainer does have the method onRemoved().
If you put a gugahoaContainer inside a normal Container, for example a backpack, and then remove it using Game::internalRemoveItem, gugahoaContainer::onRemoved() will not be called. Only when removing gugahoaContainer directly that onRemoved will be called.

Is this the intended behavior?
##

**Comment by ranisalt** [comment]
If this is true, wouldn`t it leak memory, as the item would not be reachable anymore, but still reside in memory?

**Comment by djarek** [comment]
@gugahoa I believe this is intended behavior - onRemove is supposed to be called when an item has been removed from the [direct] parent cylinder. 
@ranisalt It doesn't leak memory, check the Container destructor. The only way for a leak to occur within this context would be a circular reference (or a leak of the top-level container).
