### ISSUE TITLE
enable/disable loot message in config.lua

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#1386]
as in title
if it can't be moved please add option to disable loot messages

it would be useful in creating custom loot system which I want to use in monster level system
##

**Comment by Codinablack** [comment]
Loot message in lua would be great

**Comment by ranisalt** [comment]
Maybe you can hook onKill? Should not be hard.

**Comment by Codinablack** [comment]
Yeah but then you will still get the default message too. Of course we know we can hook thru onkill -.-

**Comment by Codinablack** [comment]
Should have been different title and more specific. How about a loot option in config.lua?

**Comment by ranisalt** [comment]
Please [consider using otbr/forsaken instead](https://github.com/otbr/forsaken), since its loot drop system is entirely on Lua. You can change the message, the conditions or suppress it entirely.

**Comment by Zbizu** [comment]
@codinablack that is all I need

**Comment by ranisalt** [comment]
Okay then. It's pretty easy to create a new option in config.lua if you know a little C++, [check this PR](https://github.com/otland/forgottenserver/pull/1301/files). Just add an option to the configuration manager class, and surround the loot message output with an if.

**Comment by HeavenIsLost** [comment]
I'm sorry but i don't believe tfs should have every option to every person, or it will become a big monsters(its already big and has a lot of legacy code). This type of stuff should be on your own fork(or  on open projects, like forsaken).

**Comment by WibbenZ** [comment]
As @ranisalt said, all you need is an if statment for it.
We are talking about 3-4 lines of more code?
It's not like he is asking to get some huge code added to the monster files.

**Comment by ranisalt** [comment]
If you are going to disable it permanently on your own server, I suggest you remove/comment out the lines related to loot messages. You can literally remove [those highlighted lines](https://github.com/otland/forgottenserver/blob/7e132eda65be17ee39f4a4ef08c562f165461a01/src/monsters.cpp#L148-L167) from monsters.cpp.

**Comment by Zbizu** [comment]
@WibbenZ I know. I'm able to do it myself. I just saw this feature in 0.4 as config value so I suggested it here. 3-4 lines of code wouldn't harm server efficiency much.

**Comment by marksamman** [comment]
It won't be added to config.lua, but it should definitely be customizable.

**Comment by ranisalt** [comment]
What is your thought on moving loot creation to Lua? Both controlling if the player will drop loot (e.g. with low stamina) and the messages.

**Comment by marksamman** [comment]
Most of the game logic that isn't performance intensive should be moved to Lua at some point.

**Comment by WibbenZ** [comment]
@marksamman 
IMO if we are planing on moving alot to Lua then we should try to make the events abit better, it can be pretty messy in there, having 20-40? functions in one file insted of having ex. onChangeOutfit or w/e it is named in one file etc, that way we can keep the code abit more cleaner and with ease move alot more insted of having to worry about files that have 10k lines in then :p 

Or what is your take on it?

And what is the plan with creaturevents? Is it to remove it and replace with events?

**Comment by marksamman** [comment]
The plan is to come to a conclusion in #1057 first.

**Comment by EPuncker** [comment]
@Zbizu do you mind doing this one? 😛

**Comment by Zbizu** [comment]
I'm not planning to code it anytime soon.

**Comment by EPuncker** [comment]
> It won't be added to config.lua, but it should definitely be customizable.

why tho?

**Comment by Zbizu** [comment]
he probably planned to move it to lua

**Comment by Zbizu** [comment]
Closing because the goal of this suggestion (which was customizable loot message) was achieved.
For anyone wanting to edit loot message, it's located in `forgottenserver/data/scripts/eventcallbacks/monster/default_onDropLoot.lua` now.
