### ISSUE TITLE
Documentation: ProtocolStatus

### ISSUE THREAD

**Issue by gpedro** [otland/forgottenserver#1393]
hi, 

i don't know how this fucking protocol works, it's really really confused. The message sent by the  [TibiaJS/serverstatus](
https://github.com/TibiaJS/serverstatus/blob/master/src/index.js#L13) can reach to [this loc](https://github.com/otland/forgottenserver/blob/master/src/protocolstatus.cpp#L68), `0x06, 0x00, 0xFF, 0xFF, 'info'`, ok, nice. But i tried to change to 
[get playerList or playerInfo](https://github.com/otland/forgottenserver/blob/master/src/protocolstatus.cpp#L75-L83) and i've failed and there is no documentation or something that explains it works. How works? Why i need add 0x06, 0x00, 0xFF in the beginning? 

Thanks!

**Comment by djarek** [comment]
I didn't take a closer look but I presume that the first 2 bytes are the message length and the 3rd one (0xFF) is the protocol identifier.

**Comment by kornholi** [comment]
Correct. The first 0xFF is status protocol identifier and the second 0xFF is the "sub-protocol" identifier.
