### ISSUE TITLE
XML tag for each flag

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#1394]
I have read this proposal on [1.2 roadmap](https://github.com/otland/forgottenserver/wiki/Roadmap-1.2) but I couldn't quite understand why.

A numeric flag number can be arbitrary, and by itself has no meaning, and this is the single reason I thought on changing to more XML tags.

On the other hand, by using a flag tag for each possible flag, we would bloat the groups file a lot. We have currently 38 flags, and using the gamemaster group flag of `137438953471`, which has 37 flags set, would mean we need to add 37 new tags to the group, while the flag value is just an attribute.

This would hardly be pleasing to do by hand, and probably someone would create a tool for that. But what's the point, since [we already](http://comedinha.github.io/flags-calculator/) [got a ton of](http://opentibia.net/page/flagcalculator.html) [flag calculators](https://ranisalt.github.io/flags-calculator/)?

It also adds complexity since it would be necessary to parse the XML instead of just reading the int directly.
##

**Comment by marksamman** [comment]
The point is that you shouldn't need to use a flag calculator to update group flags.

**Comment by ranisalt** [comment]
I doubt anyone would do it by hand. It's 37 flags. Maybe if we keep both options?

**Comment by Codinablack** [comment]
We could make predefined groups with variables to make it smaller and simpler for everyone if we did do it both ways...

**Comment by ranisalt** [comment]
No... that's a very bad option actually IMHO. Groups are already predefined flags, creating predefined flag groups would create predefineception.

**Comment by Kamenuvol** [comment]
Make a list of flags and put the group id which the flag is active
Example:
<flag id = "3" name = "canKillMonsters" groups = "1,2,3"/>

**Comment by joseluis2g** [comment]
also something like this
```xml
<flag id="17" name="ignoredByMonsters">
    <group name="gamemaster"/>
    <group name="player"/>
    <monster name="demon"/>
</flag>
```
idk

**Comment by WibbenZ** [comment]
Why not just make it simple insted of first listing all the groups then list what flag "array" it should have.

````
<group id="2" name="gamemaster" access="1" maxdepotitems="0" maxvipentries="200">
	<flag name="canKillMonsters" value="1" />
	<flag name="ignoredByMonsters" value="1" />
</group>
```

This way we can easily see what flag we have assigned (no flag counter is needed) aswell as with ease disable and enable the flags.

**Comment by kornholi** [comment]
That's what we were planning to do.

**Comment by ranisalt** [comment]
@WibbenZ that's what I said was overkill in the original post. Remember that's 37 flags to set for every group you may want to define.

**Comment by WibbenZ** [comment]
@ranisalt Yeah, but it would be alot cleaner if you ask me.
Sure it might be 37 flags, but still nicer then having to add or remove the group name from the "flag array" as someone propsed aprove.

```
<flag id="17" name="ignoredByMonsters">
    <group name="gamemaster"/>
    <group name="player"/>
    <monster name="demon"/>
</flag>
```

**Comment by ranisalt** [comment]
Yes, and indeed easier to parse, I think.

**Comment by WibbenZ** [comment]
It most likely will, unless 2 groups have the same flags, since you then only have to iterate one flag "array" insted of 2, but if they all have diffrent flags(like the default DP has atm) it should be quicker to load them from each group - even if most of them are the same for the groups.

**Comment by Kamenuvol** [comment]
It is better make like spells.xml to list all flags, even if is not used by any group at the moment.

**Comment by ranisalt** [comment]
@Kamenuvol why?

I think it's easier and better to map group to flags than flag to groups.

**Comment by Kamenuvol** [comment]
What if we make groups in Lua? I've already made and tested it sometime ago, but I have not pushed to my repository because there is no clue of what is the name of the flags that are not used.
My groups.lua is like this: http://pastebin.com/93hS83Fa

**Comment by Kamenuvol** [comment]
I found a way to rebase my local and push. Kamenuvol@b1061c3

**Comment by HeavenIsLost** [comment]
There is a simple solution to this.
Do like @WibbenZ said:
<group id="2" name="gamemaster" access="1" maxdepotitems="0" maxvipentries="200">
    <flag name="canKillMonsters" value="1" />
    <flag name="ignoredByMonsters" value="1" />
</group>

Then we create a default set of values for all groups so we override the flags values in the group configuration. Of course gods and gms will have a big flag list but it does not matter after all.

**Comment by WibbenZ** [comment]
I wrote smth like that way back but idk why I didnt upload it...
Mby some bug or that I got prs that have been open for over a year?

Ill try and see if I can find it tomorow
But id like to see what korn / mark things of a system like that aswell
