### ISSUE TITLE
NetworkMessage::decodeHeader()

### ISSUE THREAD

**Issue by djarek** [otland/forgottenserver#1397]
Is there a particular reason why we're ignoring the highest-order-byte of the packet length here: https://github.com/otland/forgottenserver/blob/master/src/networkmessage.cpp#L33 ? Or have I misunderstood the bitwise operations there? If I'm not mistaken it 's always going to be a bitwise-OR of the first byte of the length and 0 (the latter being the result of a left-shift by 8 of any 8-bit unsigned value).

**Comment by kornholi** [comment]
uint8_t always gets promoted to int during arithmetic, so the calculation is correct.

**Comment by ranisalt** [comment]
We should not rely on the implementation characteristics of processors.

There may be a new generation of processors with specialized 8-bit instructions and all of a sudden TFS will stop working because of that?

Please surround it with a cast to uint16 or larger.

**Comment by djarek** [comment]
@ranisalt 
If you did that, you would need to take care of endianness (using le16toh).

**Comment by ranisalt** [comment]
Shouldn't casting already handle it?

**Comment by djarek** [comment]
How would the compiler know that the endianness of the data in memory is different than the CPU's endianness? On little endian machines a type cast will work (since no swapping is necessary), however, on big endian ones it would not (and swapping would be necessary).
