### ISSUE TITLE
[BUG] Ladder use!

### ISSUE THREAD

**Issue by Cj4k3r** [otland/forgottenserver#1398]
Hi!
I am trying to use the ladder, the first problem is if i have a item under the ladder i cant use it, when i try to use, it uses the GOLD COIN, and i want to use the ladder to go up.

Image:
![ladder1](https://cloud.githubusercontent.com/assets/11999332/7926180/f3033932-08a4-11e5-8d0f-be6c9cff8557.PNG)

**Comment by ninjalulz** [comment]
There shouldn't be anything wrong with the script.

Update your executable, and make sure you're using the official OTB file.
