### ISSUE TITLE
TFS 1.0 maybe an issue?

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1399]
Creating spellcreating system here and funny thing came up, what is not really a big issue, but confusing none the less, why it happens.

addEvent(dealDamagePos, 0, cid, pos, effectOnHit, damType, min, max, spellEffect, effectOnMiss, target)

Should make and addEvent what executes instantly right?
The pos in this case is target:getPosition()

Inside the dealDamagePos function
local creature = Tile(pos):getBottomCreature()
    if creature then
        if not Creature(cid) then cid=0 end
        doTargetCombatHealth(cid, creature, damType, -min, -max, effectOnHit)
    elseif effectOnMiss then doSendMagicEffect(pos, effectOnMiss)
    end

Funny thing is, sometimes its possible to walk out of the position and target takes no damage even though the position was created from target position.
Doesn't happen too often and I can also add direct target damage instead of position damage, but is it a bug or there is no such thing like instant addEvent execute?

**Comment by ninjalulz** [comment]
Call the function directly instead of using a scheduled event. Also they can avoid damage because you're storing the target position in a variable.

Anyway, use [OTLand's Support Forum](https://otland.net/forums/support.16/) for these kind of questions.

**Comment by whitevo** [comment]
its not ad support like question, because i don't need help. I just said It's weird that player doesn't take damage because i though scripts will do their thing automatically and execute before player moves.

and removing addEvent is not an option.
I don't need rework. Script is working exactly like it should. Expect if addEvent timer is 0, but that is ok, Already planning an direct attack.

**Comment by ranisalt** [comment]
Man, sorry, it's had to understand every single phrase you have written. Let me try:

addEvent is not guaranteed to execute on the exactly moment you expect it to since this is virtually impossible to guarantee. If you add an event to the time 0 it might or might not be executed instantly, depends on what the scheduler is doing that moment.

Suggestion: instead of sending a position, send the creature to the function, then inside the function get the position. That way you are guaranteed to get the updated position when the function is called.

**Comment by whitevo** [comment]
Script is working like it suppose to. Most of the time, target doesn't have userdata.

But ok, now I know. I simply assumed before that addEvent is priority execute and others wait after that.

**Comment by Codinablack** [comment]
@whitevo What exactly is wrong with just calling the function? Seems that addevent is quite pointless if there is no delay. Should be able to call the function directly and pass the parameters and all would be fine... Besides Ninja explained where the problems would occur if any...
