### ISSUE TITLE
Error Compile Ubuntu 12.04

### ISSUE THREAD

**Issue by login12** [otland/forgottenserver#1400]
I trying compile this tfs in my dedicated 12.04 ubuntu but get this error;

[  1%] Generating CXX prefix source cotire/tfs_CXX_prefix.cxx
[  2%] Generating CXX prefix header cotire/tfs_CXX_prefix.hxx
[  3%] Building CXX precompiled header cotire/tfs_CXX_prefix.hxx.gch
Scanning dependencies of target tfs
[  5%] Building CXX object CMakeFiles/tfs.dir/src/otpch.cpp.o

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/tfs.dir/src/otpch.cpp.o] Error 4
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2
root@ns502827:/home/ots/forgottenserver-master/build#

**Comment by HeavenIsLost** [comment]
remove everything related to cotire on CMakeLists.txt and it will compile i believe(i had the same problem).

**Comment by login12** [comment]
Wel... when i retire this i have this erro now:
So bad :/

Scanning dependencies of target tfs
[  1%] Building CXX object CMakeFiles/tfs.dir/src/otpch.cpp.o
[  2%] Building CXX object CMakeFiles/tfs.dir/src/actions.cpp.o
In file included from /home/ots/forgottenserver-master/src/actions.h:23:0,
                 from /home/ots/forgottenserver-master/src/actions.cpp:22:
/home/ots/forgottenserver-master/src/baseevents.h:30:22: error: ‘virtual Event::~Event()’ declared virtual cannot be defaulted in the class body
/home/ots/forgottenserver-master/src/baseevents.h:56:27: error: ‘virtual BaseEvents::~BaseEvents()’ declared virtual cannot be defaulted in the class body
In file included from /home/ots/forgottenserver-master/src/actions.cpp:22:0:
/home/ots/forgottenserver-master/src/actions.h:35:49: error: expected ‘;’ at end of member declaration
/home/ots/forgottenserver-master/src/actions.h:35:51: error: ‘override’ does not name a type
/home/ots/forgottenserver-master/src/actions.h:36:52: error: expected ‘;’ at end of member declaration
/home/ots/forgottenserver-master/src/actions.h:36:54: error: ‘override’ does not name a type
/home/ots/forgottenserver-master/src/actions.h:73:36: error: expected ‘;’ at end of member declaration
/home/ots/forgottenserver-master/src/actions.h:73:42: error: ‘override’ does not name a type
/home/ots/forgottenserver-master/src/actions.h:84:21: error: expected initializer before ‘:’ token
In file included from /home/ots/forgottenserver-master/src/item.h:23:0,
                 from /home/ots/forgottenserver-master/src/bed.h:23,
                 from /home/ots/forgottenserver-master/src/actions.cpp:23:
/home/ots/forgottenserver-master/src/cylinder.h:208:29: error: expected initializer before ‘:’ token
In file included from /home/ots/forgottenserver-master/src/items.h:25:0,
                 from /home/ots/forgottenserver-master/src/item.h:25,
                 from /home/ots/forgottenserver-master/src/bed.h:23,
                 from /home/ots/forgottenserver-master/src/actions.cpp:23:
/home/ots/forgottenserver-master/src/itemloader.h:181:16: error: expected declaration before end of line
make[2]: *** [CMakeFiles/tfs.dir/src/actions.cpp.o] Error 1
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2
root@ns502827:/home/ots/forgottenserver-master/build#

**Comment by marksamman** [comment]
Ubuntu 12.04 is too old.

**Comment by ranisalt** [comment]
Which compiler are you using? You need at least GCC 4.8 and I think such an old version of Ubuntu has a prehistorical GCC.

**Comment by login12** [comment]
@marksamman the problem is certain the ubuntu then? u recommend any ubuntu for me?

**Comment by marksamman** [comment]
If you really want to use 12.04, you can use a PPA like we do in Travis: https://github.com/otland/forgottenserver/blob/master/.travis.yml

If you just want to use a LTS release, then use 14.04. Otherwise, use the latest version (15.04). That's if you have to use Ubuntu though, otherwise I'd recommend Debian 8.

**Comment by login12** [comment]
I will try now with 14.04.
In few minutes post de result, here.

**Comment by pedriinz** [comment]
is already, i try in 14.04, and work fine.

**Comment by jaymeproni** [comment]
I sent a mail to Mark and He said to me change my compiler version for someone more new. My compiler version was 4.6 in Ubuntu OS 12.04. So I change it and this error came:

root@otserverx:/home/otserv/global107778/forgottenserver/build# make
Scanning dependencies of target tfs
[  1%] Building CXX object CMakeFiles/tfs.dir/src/otpch.cpp.o
cc1plus: error: /home/otserv/global107778/forgottenserver/build/cotire/tfs_CXX_prefix.hxx.gch: not compatible with this GCC version [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/tfs.dir/src/otpch.cpp.o] Error 1
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2
root@otserverx:/home/otserv/global107778/forgottenserver/build#


My current compiler version:

root@otserverx:/home/otserv/global107778/forgottenserver/build# gcc --version
gcc (Ubuntu 4.9.2-0ubuntu1~12.04) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@otserverx:/home/otserv/global107778/forgottenserver/build#

**Comment by jaymeproni** [comment]
Forget it. It was my mistake. I had forgotten to remove cotire folder. So my steps for sucessfully compiling was:

A) Changer version 4.6 for 4.8 or higher using this steps:
1) sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
2) sudo add-apt-repository ppa:apokluda/boost1.53 -y
3) sudo apt-get update -qq
4) if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
5) if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
6) sudo apt-get install libboost1.53-dev libboost-system1.53-dev liblua5.2-dev libgmp3-dev libmysqlclient-dev gcc-4.9 g++-4.9

7) sudo update-alternatives --remove-all gcc
8) sudo update-alternatives --remove-all g++
9) sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
10) sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
11) sudo update-alternatives --config gcc
12) sudo update-alternatives --config g++
13) ccc --version in shell for testing

B) You already compiled,so:

1) enter in build folder and remove all files and  folders
2) still in build folder ... cmake ..
3) make
4) go to take a beer.

**Comment by ranisalt** [comment]
It's 2015 and you are still using Ubuntu 12.04, didn't it EOL a few months ago?
I suggest you upgrade it ASAP to keep security patches up to date (and have updated version of gcc).

Also, go straight for gcc 5+ if it is available, it compiles faster and better code :+1:

**Comment by djarek** [comment]
https://wiki.ubuntu.com/LTS
12.04 is still supported (a lot of big companies still use it, I use it  at work as well)

**Comment by ranisalt** [comment]
My wrong, I thought their support was 3 years, it's actually more.
