### ISSUE TITLE
Assign null value to variables after being deleted?

### ISSUE THREAD

**Issue by edumntg** [otland/forgottenserver#1402]
Why are some variables being set to nullptr after being deleted? Is this a necessary step? I sought opinions and everywhere I have read that this is unnecessary

Example:
```
delete item;
item = nullptr;
```

**Comment by gugahoa** [comment]
It's a good practice to prevent accessing garbage.
If you look around the code, you'll see that lots of methods that deals with pointers will have a check if it's nullptr.
So, if you only delete 'item', your variable will still point to an address that's garbage and will pass the check if 'item == nullptr', resulting in a seg fault later in the code.

**Comment by ranisalt** [comment]
We should really convert everything to smart pointers.

**Comment by djarek** [comment]
@ranisalt 
Using smart pointers everywhere is an overkill. They should only be used in places where we currently use  *owning* raw pointers (e.g. when stored in a container). Non-owning raw pointers are fine if the lifetime of the pointee can be guaranteed.

**Comment by marksamman** [comment]
It is only necessary to set it to nullptr if we will check whether it's a valid pointer later. It can also a good practice so you don't accidentally double-free, but I'd rather get rid of it where it's clear that this won't happen.
