### ISSUE TITLE
Error compile Debian 8

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1404]
http://2.1m.yt/OzKGa74zF.png

**Comment by marksamman** [comment]
See:
#1325
#1400

Please submit a bug report to GCC like the message suggests and keep us updated.

**Comment by ranisalt** [comment]
Could you try Clang and see if it pops the same error?

**Comment by HeavenIsLost** [comment]
Just remove anything related to cotire on cmakelists.txt and you are good :)
this problem give a lot of headache.

**Comment by PrinterLUA** [comment]
@marksamman i will do that later.
@ranisalt ill try that aswell later.
@HeavenIsLost cheers mate it works.

**Comment by Joeeigel** [comment]
Confirming @HeavenIsLost 's suggestion worked.
