### ISSUE TITLE
CPU consume spike

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1405]
Hello,
From time to time, the TFS will have a spike in CPU and go from using 5% to 30%. I'm still unsure if it's caused by my datapack or something from the TFS. Anyone can relate to this issue?
Btw, I would appreciate if you guys could give some tips on how to track down this issue. I know that gdb is a powerful tool for this, but I don't know how to use it for this purpose.
I'm running the server on Ubuntu 14.04

For reference: I'm going to try this the next time it happens (http://stackoverflow.com/questions/23838498/how-to-diagnose-a-python-process-chewing-cpu-in-linux)

**Comment by djarek** [comment]
If it's more or less periodic then my best guess would be the lua garbage collector. As for tracking it - if the spike occurs, you can just interrupt the application in gdb and see where the application was stopped. Might not help you though, if it happens to be doing something in lua (as it's going to be seen by gdb as external code).

**Comment by marksamman** [comment]
30% use shouldn't been an issue if you actually have players online, but for an idle server, yes it's quite much. You may be able to diagnose this using perf. The Lua garbage collector is definitely a possibility, but it could also be checkDecay, checkCreatures or getSpectatorsInternal by NPC's (assuming it's an idle server).

**Comment by gugahoa** [comment]
It's not an idle server, but the average consume of the CPU is around 3%, hovering to 4% sometimes. That's why the spikes are so noticeable. I installed perf and am reading the manual right now. Seems like the next time it happens I'll know for sure where the issue is. Thanks for the tips :)

**Comment by gugahoa** [comment]
Found what caused this issue. It was a custom modify I made when implementing equipping item via hotkey. Thanks for all the help.
