### ISSUE TITLE
Error Player@onGainExperience TFS 1.2

### ISSUE THREAD

**Issue by Lpcordovil** [otland/forgottenserver#1407]
Good afternoon friends.

I have a problem on my server which is 1.2 TFS ! I'm having problems in Player.lua .

What happens is the following a mistake in my DISTRO and exp of my server is EXP Global Tibia .
Follows the error kill a monster :

Lua Script Error: [Event Interface]
data/events/scripts/player.lua:player@onGainExperience
data/events/scripts/player.lua:162: attempt to perform arithmetic on field '?' (a nil value)
stack traceback:
[C]: in function '__sub'
data/events/scripts/player.lua:162: in function 'useStamina'
data/events/scripts/player.lua:198: in function <data/events/scripts/player.lua:181>

Thanks.

**Comment by WibbenZ** [comment]
https://otland.net/forums/support.16/
Also post the script.
