### ISSUE TITLE
Reduce death penalty

### ISSUE THREAD

**Issue by kaiquefb** [otland/forgottenserver#1412]
Hello friends.
I want to reduce the death penalty for monsters (creatures).
For I noticed that ten of TFs 1.0 to the current 1.2 there is this little problem, where every player level 250+, when creatures die to come to lose 2 level with blessings and level 3 without blessings. This is annoying because many whiny players.
Of level 400+ comes to lose 3 level with bless.

Where can I configure this?

Thanks in advance.

**Comment by WibbenZ** [comment]
https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L4032
https://otland.net/forums/support.16/ (for the next question).

**Comment by kaiquefb** [comment]
Yes friend, the issue is not this the same as the global tibia.
We must set up the most possible next.
A player with level 400 is losing 2-3 with blessing.

In my view it would be a little over 1 level.

**Comment by WibbenZ** [comment]
"In my view" - thats a reason why the project is open source, so you can do w/e you want with it.
Tweak around with this: https://github.com/otland/forgottenserver/blob/master/config.lua#L32-L36

**Comment by kaiquefb** [comment]
It is not my opnion, the global tibia is so.
You may notice that site (http://guildstats.eu/character-level?lang=pt) set the level and see how much it loses and how much it needs for the next level.

**Comment by ranisalt** [comment]
The formula is correct, you can [read this line](https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L4049) and check [the wiki about death](http://tibia.wikia.com/wiki/Death). The formulas are the same.

**Comment by kaiquefb** [comment]
Is something wrong because one player lvl 400 to bless this losing almost 3 level.
Already I noticed this defect des tfs 1.0
The right is lost just over 1 level. you can check the link that informed above.
The formula may be the same wiki tibia, most in practice is wrong.

**Comment by WibbenZ** [comment]
As ive also been told(by Mark) is that we are not trying to mimic Cipsoft.
So if you want to keep it 100% as Cipsoft then you have to do it yourself.
And once you start doing that you will quickly notice that there is alot of things that are missing / done wrong (in the sence of keeping it 100% as Cipsoft).

As ive already said, use the config integer to try and get it to what you want or as ive also said, change the source code.

**Comment by kaiquefb** [comment]
I'm also not trying to imitate CipSoft, so I'm trying to help everyone. Calling for the correction of this small mistake :)
