### ISSUE TITLE
Website system acc TFS 1.2

### ISSUE THREAD

**Issue by cmarfil** [otland/forgottenserver#1414]
Hello, 

There is some web system comptible with TFS 1.2?
I can't find a gesior compatible ( 4 example )

Thanks,

**Comment by WibbenZ** [comment]
https://github.com/gesior/Gesior2012/tree/TFS-1.0
https://github.com/Znote/ZnoteAAC
Next time: https://otland.net/forums/support.16/

This is only for bug reports that are related to TFS, if you are unsure - ask at otland first.

**Comment by cmarfil** [comment]
Ok, thanks a lot.
