### ISSUE TITLE
Compile Error Fedora 22 server

### ISSUE THREAD

**Issue by Alscara** [otland/forgottenserver#1415]
Howdy doodle. Was trying to compile in Fedora 22, got some errors.
#define lua_equal(L, i1, i2) lua_compare(L, (i1), (i2), LUA_OPEQ)
#define lua_strlen lua_rawlen

These two definitions are already defined in /usr/include/luaconf.h as was downloaded during the compiling guide
They are redefined in luascript.h (lua_equal, line 31) and configmanager.cpp (lua_strlen, line 29)

the compiler complains and errors and stops the build. I fixed it by removing them both from luaconf.h, assuming that if they were defined in the TFS source, that version is more important, but following the exact steps in the compiling guide for fedora, this is what happened.

I imagine the guide was for earlier versions and maybe it's just the newer versions that are having issues. On that note, fedora uses dnf instead of yum in the latest version, could be useful to add that to the guide.

**Comment by ranisalt** [comment]
Replace with
```
#undef lua_equal
#define lua_equal(L, i1, i2) lua_compare(L, (i1), (i2), LUA_OPEQ)

#undef lua_strlen
#define lua_strlen lua_rawlen
```
So they keep their correct meaning.
