### ISSUE TITLE
Leaking memory on combat:setCondition

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1416]
Check this script:

http://hastebin.com/rejesicase.coffee

I believe it is leaking memory because every time the player use this spell rune, setCondition will make a copy of the condition. Another "bug" that would happen is as every time it add the condition again, the damage will sum up every time combat is being executed...
##

**Comment by djarek** [comment]
All condition objects assigned to a Combat object are properly deleted once the former is destroyed (check https://github.com/otland/forgottenserver/blob/master/src/combat.cpp#L48-L50).

**Comment by HeavenIsLost** [comment]
Yeah, but if i understand correct, every time the spell is used, the setCondition is called. Every time setCondition is called it will clone the condition, so, the list of conditions in this combat object will be huge, and will be leaking memory.

**Comment by WibbenZ** [comment]
Try to spam the spell (set a low CD) then see if it increases faster or just as fast, might be something else releated or unrelated to the rune or function.

**Comment by djarek** [comment]
Using setCondition like this will cause the Condition objects to be copied every time the spell is cast. However this is not really a leak (the memory in question is still reachable), just misuse of this function.
@marksamman 
This issue can IMO be closed.

**Comment by raymondtfr** [comment]
I can confirm this too (leaks around 500 K [x64]) per use of rune.
