### ISSUE TITLE
Raid Margin and getRaidByName

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1419]
What is margin and how it works?

and

I wonder if it is possible to make the function getRaidByName take directly the xml in a raid instead of the name, for use as raids by GlobalEvents, the xml is coming in all the time conflicts with the interval

**Comment by WibbenZ** [comment]
https://github.com/otland/forgottenserver/issues/940
In the future use otland for support and questions: https://otland.net/forums/support.16/

For the other question;
https://github.com/otland/forgottenserver/blob/master/src/luascript.cpp#L4828-L4841
You can use Game.startRaid(raidName)

**Comment by ranisalt** [comment]
Margin is a time difference the raid can take to start after the last raid. If raid K is to start on an arbitrary time x and the margin is 5, but the last raid has ended on x-1, K will start only after 5 seconds after the last raid has started, in this example at time x+4.
