### ISSUE TITLE
Server unknown crash

### ISSUE THREAD

**Issue by macevedoinf** [otland/forgottenserver#1420]
Just as the title says, I compiled the x64 latest version and it crashes after a while since it starts sometimes 15 minutes, sometimes 30 minutes and the event log only shows APPCRASH without a traceable description. I'm running Windows Server 2008 R2 SP1.

**Comment by WibbenZ** [comment]
Using ORTS?
In that case compile it as x86 (32bit).

In the future ask for support here first: https://otland.net/forums/support.16/
