### ISSUE TITLE
Problem with reading lua scripts

### ISSUE THREAD

**Issue by DarkShinz** [otland/forgottenserver#1423]
Hello!

I don't know if this is the right place to post it, but I'm having an issue with TFS 1.1. I've downloaded TFS 1.1 a month or two ago and made somechanges, but nothing related to Lua stuff. So far, everything  was fine. But yesterday I tried to run a lua script from OTland and it returned maany errors.  So I did a few tests, wich included downloading the latest TFS version and it returned no errors at all.

So, my issue is: Where is the file .cpp/.h related to lua functions of identifying values, cid and stuff? So I can check if mine is outdated. I don't know if the problem is with luascript.cpp. I've replaced half of my file with the latest tfs 1.1 file.

Can someone give me a help?

**Comment by ranisalt** [comment]
Diff your modified files against the unmodified TFS source and you will see where you made changes that may be the cause of your problems.

```
diff -d path/to/your/code/src path/to/tfs/clone/src
```

Also try using OTLand support forums before coming here for help.
https://otland.net/forums/support.16/

**Comment by DarkShinz** [comment]
Hello Rani, sorry for posting here, and Thanks for your help. I've downloaded Code Compare and fixed all differences, but still, the error continue. Do you have any possible idea on where the issue might be ?
