### ISSUE TITLE
classicEquipmentSlots bugged

### ISSUE THREAD

**Issue by peonso** [otland/forgottenserver#1425]
classicEquipmentSlots = "yes"

You can put weapons in any slot, it works in both left and right hand without a shield. But it you have a shield it will only work in left hand.

**Comment by WibbenZ** [comment]
Can't reproduce it, I can add the sword or spellbook first on either hands (tried spellbook on left and right aswell as with the sword).
Updated source?

**Comment by peonso** [comment]
Yeah dude, I just updated it and the problem is already solved. Sorry for the false report. I was using a revision from march. Do you mind to point me when it was adressed?

**Comment by peonso** [comment]
Found it

https://github.com/otland/forgottenserver/commit/5e99f506664b44fa03461a76a28c60a200e187d2#diff-dc52f162280289dd2d4d97d82658362d

Sorry guys.
