### ISSUE TITLE
Has been there fix for diagonal movements for TFS 1.1 or higher?

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1429]
I'm still using TFS 1.0

If I make diagonal step I have to wait ~1second before I move again. Else my character bounces back to position where I was before.

This is specially annoying, because my newest monsters require player to move diagonally.

I would also be satisfied if the diagonal movement penalty could be removed all together (no longer counts it as 2 steps), but I have no clue how to do so. (nor can I compile source, with my computer)

**Comment by whitevo** [comment]
If you trying to reproduce the issue, then simply decrease player movement speed lower than 100, (to give yourself plenty of time to rechange your movement)
Hence the rubberbanding.

**Comment by ranisalt** [comment]
https://github.com/otland/forgottenserver/blob/56575545a60b2a9927de8fbcff62fc4100eaddfc/src/creature.cpp#L1391-L1393

Those are the lines that makes the diagonal steps take longer. Just remove them and recompile.

**Comment by whitevo** [comment]
Ok, thank you, I will let you know, how did it work out for me after someone is available to compile these changes for me.

**Comment by WibbenZ** [comment]
I can help you if this is an issue that needs to be fixed xD
Den 23 jun 2015 17:44 skrev "whitevo" <notifications@github.com>:

**Comment by whitevo** [comment]
ok. i will contact you in otland after i sober up

**Comment by whitevo** [comment]
just wondering, why did you add invalid label?
Players should start rubber-banding and feel 'laglike' experience when moving diagonally?

Or it is idd fixed for higher TFS versions?

**Comment by ranisalt** [comment]
Yes. This is the behavior of Tibia.
