### ISSUE TITLE
[QUESTION] Send skills to client.

### ISSUE THREAD

**Issue by Vysius** [otland/forgottenserver#1433]
Hello, i've started on OTcode, and im trying to send some custom info to my client. Its currently working on the login-logout, but if i try to send the client->skills on every AddStorage., it doesnt seem to work.

I dont know if im doing right, but if i do /addskill blabla, and i get the advance lvl msg, i get my custom info updated on my client. I want the same but with the AddStorage.

Do anyone knows how to make the sendskill launch?

**Comment by marksamman** [comment]
https://otland.net/forums/support.16/
