### ISSUE TITLE
Considerations on C++14

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#1439]
I think it's time to start working on using a more modern standard we have for C++. I spotted several places at the code where new functions could improve code quality, speed and flexibility. Example:
- Using std::experimental::optional instead of dealing with pointers for relying on `nullptr` falsiness. This is safer to handle, does not deal with dynamic alocation (thus has better performance) and ownership issues. [(reference)](http://stackoverflow.com/questions/16860960/how-should-one-use-stdoptional)
- Return `auto` type deduction, and we use way too fewer of `auto` than we should. This makes maintaining the code easier with less code to refactor every time.
- Overloadable `delete` function for objects, e.g. for replacing `decrementReferenceCounter` with a more natural code and scoped deletion.
- Binary literals, e.g. flags can be made clearer with a bit map instead of shifting 1 leftwards.
- String literals for better creating strings out of char literals.
- Improvements on `constexpr`s that can be of good use. Now constexprs can even be templated.
- Deprecation warnings! Moving from one version to another is much more smooth when functions start popping warnings that they are not to be used anymore.

Well, that's a very non-formal description of what the update can offer. Updating to C++14 would require changing some lines in CMakeLists and updating cotire, since 1.6.9 does not support it yet. 1.7.2 does fine.

Let's discuss on the pros and cons of this :)

**Comment by djarek** [comment]
Correct me if I'm wrong, VS 2015 (which brings support full support for C++11 and partial support for C++14) isn't realesed yet which means that our transition point has to occur after the release of VS 2015.
*  I have my reservations about optional. It's a powerful template that can be abused and cause more harm than good (e.g. when used with polymorphic types).
* +1 for auto. In 99% of cases auto makes the code more readable (The other cases are when objects are initialized from badly named functions.
* overloading delete and new operators is dangerous and should be done with care (or preferably avoided). Furthermore, ```decrementReferenceCounter(...)``` can stay, however we would need to adapt it slightly to use with RAII, by either adapting unique_ptr or writing a custom smart ptr that would automatically call increment- and decrementReferenceCounter on construction and destruction.
* +1 for binary and string literals
* to be honest I've found very few cases where constexpr is required over a const, but making something clearly marked as "must be known at compile-time" is a good idea IMO. +1
* +1 for deprecation warnings. This will make it easier to do major refactoring.

**Comment by ranisalt** [comment]
Yes, I believe the major problems are VS taking too long to update it's standard and some distros (mainly Debian-based) that use very outdated versions of GCC under the "stable" motto.

The point on optional is just two or three places we use optional values to save on memory resources, and an own optional class was implemented (see [optional.h](src/optional.h)). This would reduce code not related to the server itself :smile: 

I liked your idea on adapting smart pointers to call reference counter modifiers correctly.

**Comment by marksamman** [comment]
> Using std::experimental::optional instead of dealing with pointers for relying on nullptr falsiness. This is safer to handle, does not deal with dynamic alocation (thus has better performance) and ownership issues. (reference)

std::optional carries the memory overhead of always having the object allocated, and a boolean (?) to check whether the value exists. Where memory usage is not a concern, sure, we could use std::optional, but I wouldn't go so far to start rewriting existing code using std::optional unless there are ownership issues with the existing code.

> Return auto type deduction, and we use way too fewer of auto than we should. This makes maintaining the code easier with less code to refactor every time.

IMO auto makes code harder to maintain because you have to look for the type elsewhere. It shouldn't be used unless the function/variable type is obvious and the type would have been too long to write. This is mostly true for iterators.

It's better that you review the use cases of refactored code where the type has changed than having auto make you miss it because it deduced the new type automatically.

> Overloadable delete function for objects, e.g. for replacing decrementReferenceCounter with a more natural code and scoped deletion.

While I dislike explicit management of a reference counter, I don't think overloading delete is any better. I expect delete to free the memory that is being pointed to and don't want to have to worry about potential overloaded behavior when I use delete. I would rather take the performance hit of using shared_ptr.

> Binary literals, e.g. flags can be made clearer with a bit map instead of shifting 1 leftwards.

Sure, if we use spaces to indent them properly, otherwise I prefer 1 << n.

> String literals for better creating strings out of char literals.

Any example of where we could do this?

> Improvements on constexprs that can be of good use. Now constexprs can even be templated.

Any example of where we could do this?

> Deprecation warnings! Moving from one version to another is much more smooth when functions start popping warnings that they are not to be used anymore.

This is mostly useful for libraries, not so much for us. If a function shouldn't be used anymore, we can just remove it immediately and deal with all the usages of it at the same time. We don't have to worry about anyone else using it. It would be cool if Lua had this though so we could mark everything in compat.lua as deprecated in a nice way.

**Comment by ranisalt** [comment]
Optional [does not have to allocate memory](http://en.cppreference.com/w/cpp/experimental/optional) until the object it is supposed to handle is created. If the optional is empty, it does not necessarily occupies the space of the internal object.

It would be nice, for instance, for returning a pointer in functions like `getPlayer` for the `Creature` type. Instead of returning a pointer, which in my opinion can cause ownership issues (is this pointer from the caller or the callee?), it could return an optional, which evaluates to false when it would return nullptr otherwise, and return the actual value when it is available. No ownership issues, close to zero code change.

That's just an example, more of a modernization than real issues with the current code.

Auto is really nice to work with iterators. Suppose we somewhere have a map and iterate over it, but we want to change that map to an unordered map, that would be just changing the type. For return types too, as `getPlayer()`, repeating the example, clearly returns a Player instance or nothing, and it could be written as `auto* getPlayer()`.

---
The issue with Lua deprecated functions can be solved, partially, by `print`ing a deprecation warning at the start of every function inside compat.

**Comment by marksamman** [comment]
> Optional does not have to allocate memory until the object it is supposed to handle is created. If the optional is empty, it does not necessarily occupies the space of the internal object.

How does optional not occupy the space of the object and not use dynamic allocation? I think you're wrong.

> It would be nice, for instance, for returning a pointer in functions like getPlayer for the Creature type. Instead of returning a pointer, which in my opinion can cause ownership issues (is this pointer from the caller or the callee?), it could return an optional, which evaluates to false when it would return nullptr otherwise, and return the actual value when it is available. No ownership issues, close to zero code change since most of the times we test the truthiness of those return values.
>
> That's just an example, more of a modernization than real issues with the current code.

I'm interested in examples of where we can use string literals and constexpr, not so much about rewriting existing code using optional for no good reason (or maybe it's just that I don't understand your arguments). Please elaborate with code examples how this would solve potential ownership issues, e.g. an example of how it's an issue with the current codebase and how using optional would solve it.

> Auto is really nice to work with iterators. Suppose we somewhere have a map and iterate over it, but we want to change that map to an unordered map, that would be just changing the type. For return types too, as getPlayer(), repeating the example, clearly returns a Player instance or nothing, and it could be written as auto* getPlayer().

As I said, it mostly holds true for iterators, but I disagree about your getPlayer() example. Player* is short enough that it should be explicitly written. The code will be read by someone more often than it will be refactored.

> The issue with Lua deprecated functions can be solved, partially, by printing a deprecation warning at the start of every function inside compat.

Obviously, but it's not a nice way of doing it.

**Comment by djarek** [comment]
@marksamman 
As for use of literals: we could use them to introduce type-safety to otherwise "typeless" numbers that have units, the most commonly used one being time. For example:
```
const auto delay = 250ms;
g_scheduler.addTask(createSchedulerTask(delay, functor));
```

**Comment by ranisalt** [comment]
> Yes, I believe the major problems are VS taking too long to update it's standard

Oh, how the turntables
