### ISSUE TITLE
After death, can't open corpses of things killed before dying

### ISSUE THREAD

**Issue by Alscara** [otland/forgottenserver#1441]
Noticed upon getting wrecked by a serpent spawn, that when I returned, I was unable to loot all the dead serpents I had already killed. Not the owner. Doesn't appear to be happening with any other monsters. Just serpent spawn that I've noticed so far.

**Comment by WibbenZ** [comment]
Known issue, same when you logout, get kicked etc
My guess is that we use the unique id for the owner insted of the GUID.
Or maybe it's supposed to be like this?

**Comment by Alscara** [comment]
Yeah I was thinking we were using a changing value as well. I imagine it shouldn't be this way. I also think it depends on the corpse. Once the body decayed to the half-rotten stage, I was able to open it normally. Perhaps in this case, the issue lies in the initial decay of the serpent spawn. It should only last the 10 seconds or however long it takes to decay from unmovable to movable, but in my case, the movable one was the one that had an owner for like 5 min until it decayed.

**Comment by Alscara** [comment]
Ah yes, that's what caused it.
correct corpse is 6061, the one in serpent spawn.xml is 4323 which takes 900 seconds to decay. that's why it couldn't be opened, cause it had an owner for 900 seconds.

It still had the wrong owner, since my id did change upon relogging, so perhaps that should still be adjusted if Mark feels it's worth it. In the meantime, I'll just fix my script with the proper corpse.

Thanks for the reply, @WibbenZ

**Comment by WibbenZ** [comment]
Corpses are corrwct and only the first id should be personal - as it should be.
After that the corpse can be pushed, equiped aswell as opened.

But give it a try on rl, stand close to a pz tile so you can quickly relog and check.

**Comment by Alscara** [comment]
6061 is the id of the dead serpent spawn that decays after 10 seconds, which is the one that cannot be moved. It decays to 4323 which is what the corpse of serpent spawn is right now, which is movable and does not decay for 900 seconds. Because it is the initial corpse, the owner remains the owner for 900 seconds until it decays to the next stage.

**Comment by WibbenZ** [comment]
Once again test it on rl.
Alot more ppl will want it fixed if you say rl is that way.
Mark has made it clear he does not care, "we are not trying to mimic cipsoft".
But most others do as I said above.

**Comment by Alscara** [comment]
well it doesn't really need fixing if the corpse is correct. the owner is removed once the corpse decays. in this case, the corpse does not decay until 900 seconds because the corpse is wrong. On the correct corpse, it doesn't matter if you log out because it only takes 10 seconds for the owner to be cleared entirely.

**Comment by WibbenZ** [comment]
Certain corpses have extreme durations, some near to nil.
That will be a hack to solve a bigger "bug".

**Comment by Alscara** [comment]
Well as I already said, the correct corpse, as can be found in items.xml is 6061:
<item id="6061" article="a" name="dead serpent spawn">
		<attribute key="containerSize" value="15" />
		<attribute key="decayTo" value="4323" />
		<attribute key="duration" value="10" />
		<attribute key="corpseType" value="blood" />
		<attribute key="fluidSource" value="blood" />
	</item>

The one that is currently set in the monster's script is movable, so automatically I know it's the wrong one. All initial corpses should be unmovable and decay to a movable version after 10 seconds, which is the period designed to allow the actual owner to loot it, as implemented many versions ago when owners became a thing. No corpse with a long duration should ever be used as the initial corpse, so this should not be an issue as long as the corpses are correctly set.

**Comment by WibbenZ** [comment]
Oh must have read it wrong. :p
