### ISSUE TITLE
[TFS 1.0] Disconnected From Server

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1444]
Hello guys, can someone help me?

I Changing version of my server, and i downloaded the last tfs 1.0 of Mark. I Compilled but i can't connect to the server, i change everything (original data and others) and dont works ;s PS: the older sources that i used works fine lol

http://s8.postimg.org/dfw55zr1h/conect.png

**Comment by marksamman** [comment]
https://otland.net/forums/support.16/

**Comment by kanohn** [comment]
Mark, no one was able to help me in the forum, something is buggy at source 1.0, because with the same settings, can connect in version 1.1. I need much use version 1.0, if you compile and try to put online, you will see what is not working to connect.
