### ISSUE TITLE
How to get container location or owner on Player:onMoveItem() ?

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1446]
I wanted to change the way items work with containers in LUA, but I'm missing 1 important parameter and I can't get that. (toPosition owner or uid if its container)

When I move item to container the toPosition.x is always 65535
But all the other parameters are VERY USELESS. (cyclinder and bag window id.)

There seems no way to found out what is the real position of the container or does it have owner.

I can get the owner when the fromPosition is bag, but not with the toPosition.
Also I cant create temporary item with these Position values, to check if the item reaches to owner.

And I don't think its good idea to add an addEvent() before true, to check afterwards where the item ended up. 

Is there some kind of workaround I'm missing or where in sourcecode I have push more parameters to get my desired values?

That would be real epic if i could get the container unique Id or the container userdata if its not a tile where item is moved.

**Comment by marksamman** [comment]
https://otland.net/forums/support.16/

**Comment by whitevo** [comment]
How will support section help if its yet another thing your TFS seems not be able to do?

This 3rd time I can't solve problem with LUA because the source has limitations.

I came here, because you have higher knowledge of what files I would have to edit to get my desired results. I have been checking support forum quite often and people rarely deal with source edits.

Maybe the problem is in client? i don't know and have not gotten any answer from support nor here.

**Comment by Alscara** [comment]
It's not Mark's problem if you can't find support on the forums. You still have to use the forum whether you like it or not. No need to insult his engine when you couldn't even come close to doing a better job.

**Comment by marksamman** [comment]
I misunderstood this issue because you wrote the wrong function name, we should definitely add toCylinder to Player.onMove**Item**.

**Comment by whitevo** [comment]
ah yes, my bad.

@Alscara 
I have nothing against the current TFS, I think it is amazing, but there is always room for improvements (I assume this platform is meant for all 2D RPG games not just for tibia).
Although I think some things come down to client sided restrictions and I'm still using the original client.

@marksamman 
but what does toCylinder contain?
All we need is the "parent" of cylinder: parent:getUniqueId()
With "parent" I mean the container unique id where you are about to move your item. (if its not item then push nil or false)

With LUA we can do the rest. (find the owner or location or whatever else)

**Comment by whitevo** [comment]
I guess this is good onMoveItem solution (no clue how can you do this though.
function Player:onMoveItem(item, count, fromPosition, toPosition, fromContainer, toContainer)

fromContainer and toContainer is userdata for chest or bag or player if the item was moved into or from any of these parent locations

Also in addition new LUA function should be added:
container:getParent()
This should return the userdata of an item or player where this container is inside (if its inside something)

**Comment by diath** [comment]
You can already do the latter since the Item class has getParent() method and Container derives from the Item. If that doesn't work for some reason, you can try container:getItem():getParent() but I don't see why the first option wouldn't work.

**Comment by whitevo** [comment]
wow, thats nice, didn't know it existed xD
didn't even look luascript.cpp because never noticed this function. and assumed it doesn't exist yet xD
getParent() function works perfectly.
