### ISSUE TITLE
Tibia client crashes when motd (in config.lua) is empty

### ISSUE THREAD

**Issue by raymondtfr** [otland/forgottenserver#1450]
In (config.lua) if you let the motd be empty, that is (motd = "") the Tibia client will crash. On the other hand, if it isn't empty, it will not crash.

This is debug assertion:
Last Packet Types: 100 040 020 000 000 000 000 000 000 000
Last Packet: 020 002 000 049 010 040 003 000 049 010 049 100 001 000 009 000
Player Name: (exception)
Player.cpp 344: exception occurred, reason:
Player.cpp 448: exception occurred, reason:
Control.cpp 2155: exception occurred (MessageType: 44 MaW: 305E910 MoW: 0), reason:
Control.cpp 2120: exception occurred (Type = 44), reason:
Dialogs.cpp 57: exception occurred, reason:
DialogsGeneric.cpp 43: exception occurred, reason:
GUI.cpp 2067: assertion failed (Child->getWidth() = 0), reason:
Child->getWidth()>0

**Comment by TheSumm** [comment]
A fix would probably be only adding the motd (byte 0x14) if g_config.getString(ConfigManager::MOTD) is set.
