### ISSUE TITLE
Enchanting Bug.

### ISSUE THREAD

**Issue by MVJohnsen** [otland/forgottenserver#1451]
Enchanting rubies etc will give you half a magic level, even if you are mlvl 180.
you can get mlvl 1-180 in 1 day as long as u have enough rubies.

Cant find anything in enchanting.lua so i think it might be a source problem?

**Comment by ninjalulz** [comment]
That script does not exist in this data pack, and it's definitely not a source issue.

Please close this @marksamman since this belongs in the orts issue tracker.
