### ISSUE TITLE
Npc Error

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1453]
i'd like to know what means this errors below.

Lua Script Error: [Npc interface]
data/npc/scripts/default.lua:eek:nThink
data/npc/lib/npcsystem/npchandler.lua:556: attempt to index a nil value
stack traceback:
[C]: in function '__index'
data/npc/lib/npcsystem/npchandler.lua:556: in function 'onWalkAway'
data/npc/lib/npcsystem/npchandler.lua:522: in function 'onThink'
data/npc/scripts/default.lua:8: in function <data/npc/scripts/default.lua:8>

Lua Script Error: [Npc interface]
data/npc/scripts/Captain Breezelda.lua:eek:nThink
data/npc/lib/npcsystem/npchandler.lua:556: attempt to index a nil value
stack traceback:
[C]: in function '__index'
data/npc/lib/npcsystem/npchandler.lua:556: in function 'onWalkAway'
data/npc/lib/npcsystem/npchandler.lua:522: in function 'onThink'
data/npc/scripts/Captain Breezelda.lua:8: in function <data/npc/scripts/Captain Breezelda.lua:8>

My Captain Breezelda is working fine :x
How can i remove this error ?

**Comment by ranisalt** [comment]
https://otland.net/forums/support.16/
