### ISSUE TITLE
Bug House Doors

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1457]
In map editor have a door in oramond with a item ID (22826):
http://s29.postimg.org/acomh1b7b/house1.png

In-game the ID changes to 22819 automatically:
http://s9.postimg.org/rfbl9frfz/house2.png

Im using the original items.otb and same in Datapack and RME, the items.otb are official. The oramond map i get from Orts.

I testes and saw that if i put the door id 22826 without a house tile, its appear 100%, but why in house dont works?

Please help!

**Comment by marksamman** [comment]
The door ID has probably been serialized in the database. Shut down your server, truncate the tile_store table, and start your server again.

**Comment by kanohn** [comment]
I can't truncate the tile_store, if i do this, the players will lose all itens in house, or not? It has another way to fix this?

**Comment by marksamman** [comment]
Then just delete the entries from tile_store matching the house id of that house.

**Comment by kanohn** [comment]
Thank you Mark, i truncated the tile_store and warned for players to withdraw the items from their houses.

**Comment by ricker75** [comment]
@kanohn  
probably be a problem of its global.lua
http://i.imgur.com/mmhYYL0.png <--- Closed door
http://i.imgur.com/Es21XZN.png   <---  Open Door
