### ISSUE TITLE
Functions getThingPos and getThingFromPos

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1458]
Hello, im using tfs 1.1, and saw in compat.lua that have the functions getThingPos and getThingFromPos. I migrate the tfs 1.0 to tfs 1.1 and I have a lot of scripts now that are not working with these functions..

My questions is: can i get the code for those functions that had in the source tfs 1.0 old, and implement in the sources of tfs 1.1 and withdrawing them from the compat.lua? can i try to do this or can bug something?

thank you for attention.

**Comment by marksamman** [comment]
Can you give an example of something that was working when they were implemented in source and isn't working now that it's in compat.lua?

**Comment by kanohn** [comment]
Yes, look this image, in pits of the inferno gravestone:
http://s22.postimg.org/kmgp0kk4x/bug.png

If the function is in compat.lua, i get this error:
Lua Script Error: [Action Interface] 
data/actions/scripts/pits of inferno quest/pitsOfInfernoQuestBloodGraveStone.lua:onUse

[code]data/lib/compat/compat.lua:830: attempt to compare number with userdata
stack traceback:
	[C]: in function '__le'
	data/lib/compat/compat.lua:830: in function 'getThingPos'
	...s of inferno quest/pitsOfInfernoQuestBloodGraveStone.lua:6: in function <...s of inferno quest/pitsOfInfernoQuestBloodGraveStone.lua:3>[/code]

If the function "getThingPos" is in source, this works 100%. I saw the functions in sources are different code than the compat.lua

It's just one of many scripts that are buggy, I had to change the getThingPos to "getCreaturePosition" to temporarily solve, so I asked if he had trouble picking up the getThingPos that is in the sources of the old tfs 1.0, and implement the tfs 1.1

**Comment by kanohn** [comment]
Solved.

I saw that the error saying that was "compare number with userdata"
Searching on forums i saw that i need to change getThingPos(cid) to getThingPos(cid.uid)

Can you confirm to me if im correct?

**Comment by marksamman** [comment]
It is a bug. doSetItemActionId should work though, what error do you get?

**Comment by kanohn** [comment]
I have this function on this script:

function onKill(cid, target)
	if(isMonster(target) and string.lower(getCreatureName(target)) == "azerus") then
		aze = Game.createItem(1387, 1, { x = 32783, y = 31168, z = 10 })
		doSetItemActionId(aze, 52161)
		doCreatureSay(target, config.message, TALKTYPE_ORANGE_1, 0, 0, { x = 32783, y = 31168, z = 10 })
		addEvent(removal, config.timeToRemove * 1000, { x = 32783, y = 31168, z = 10 })
	end
	return true
end


The teleport creates, but not set action id.


The function "doSetItemActionId" works only in this script here do not understand why:

function onUse(cid, item, fromPosition, itemEx, toPosition)
	if(getPlayerStorageValue(cid, config.storage) < 1) then
		local key = doCreateItemEx(config.key_id, 1)
		doSetItemActionId(key, config.key_aid)

i dont know dont works in all scripts when i migrate to 1.1, in version 1.0 all scripts works with "doSetItemActionId"

**Comment by ninjalulz** [comment]
doSetItemActionId expects a unique id, and not an Item userdata object.

```
doSetItemActionId(aze.uid, 52161)
 ```

**Comment by kanohn** [comment]
Thank you Ninja.

**Comment by marksamman** [comment]
getThingPos should be fixed now, can you confirm? I couldn't see any issues with getThingfromPos though, please elaborate if you're still having issues with that.

**Comment by kanohn** [comment]
Mark, as I said, the getThingPos bug was being caused because in my scripts were getThingPos(cid). Just switched to getThingPos (cid.uid) and everything worked normally, still need to make the change you've done for now?

About getThingfromPos, the function is not working for me, no script to this function works, gives no error on the console, just does not work, I had to change the getThingFromPos by getTopCreature for work, you can check it?

**Comment by marksamman** [comment]
getThingPos(cid) is correct, you should apply the patch and continue to use that, it's also faster. Please post a script that getThingfromPos isn't working in (which was working before it was moved to compat.lua).

**Comment by kanohn** [comment]
Ok, here are two scripts that getThingfromPos not works, without erros in console:

--- [[ Warzone 2 feito por Yuri Lagrotta ]] ---

local kickposs = {x=33000, y=31899, z=9} 

local function deGnomevil()
if(getGlobalStorageValue(91149) < 1) then
    TOP_LEFT_CORNER = {x = 33102, y = 31942, z = 11, stackpos=253}
    BOTTOM_RIGHT_CORNER = {x = 33130, y = 31970, z = 11, stackpos=253}
	for Py = TOP_LEFT_CORNER.y, BOTTOM_RIGHT_CORNER.y do
		for Px = TOP_LEFT_CORNER.x, BOTTOM_RIGHT_CORNER.x do
			creature = getThingfromPos({x=Px, y=Py, z=11, stackpos=253})
			if isMonster(creature.uid) then
				if getCreatureName(creature.uid) == "Gnomevil" then
					doRemoveCreature(creature.uid)
					setGlobalStorageValue(91149, 1)
					addEvent(setGlobalStorageValue, 5 * 60 * 1000, 91149, 0) 
					end
				end
			end
		end
    end
    return FALSE
end    
       
function onStepIn(cid, item, position, topos, frompos)
    if not isPlayer(cid) then
        return false
    end
           
if item.actionid == 5159 then
	doTeleportThing(cid, {x = 33105, y = 31955, z = 11})
	doPlayerSendTextMessage(cid, 19, "You have half an hour to heroically defeat Gnomevil. Otherwise you'll be teleported out by the gnomish emergency device.")
	deGnomevil()
elseif item.actionid == 5160 then
        doTeleportThing(cid, kickposs)
    end
    return true
end


PS: In this script, It is to remove the boss "Gnomevil" every time someone activates this movement, but does not remove, causing the accumulation of bosses in the warzone, in older version with getThingfromPos in source, its works 100%. i have so much scripts that getThingfromPos not works, example Desert Quest, it does not recognize the players who are in tiles, not of errors in the console.

**Comment by WibbenZ** [comment]
Post it to paste.ots.me insted.

**Comment by WibbenZ** [comment]
````
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	local thing = getThingfromPos({x = 32400, y = 32220, z = 7, stackpos = 1})
	print(thing, getPlayerName(thing.uid))
	return true
end
```

Tested with that, including the compat.lua functions (pushThing, getThingfromPos, getPlayerName) and it prints out the array that is returned (thing) aswell as my player name.

What you can do is add print(creature, creature.uid) to see what it returns.
But my guess is that there is nothing at that stackpos = it returns nil.

If that is the case, then just use getSpectators insted, mainly since that function is ment to return an array with all the creature [players, depending on arguments].
