### ISSUE TITLE
Wiki updates

### ISSUE THREAD

**Issue by djarek** [otland/forgottenserver#1459]
The changelog should be updated to inform people about the new dependency for TFS 1.2 (Boost 1.53 or higher). Compilation instructions should also be updated accordingly.

**Comment by marksamman** [comment]
I've updated the changelog, however I don't think compiling instructions needs updating, none of them are version specific except for on Windows, which already links to the latest boost version.

If the compiler in the users package manager is new enough to support the C++11 features we're using I'm going to assume that the package manager also has a new enough version of boost, 1.53.0 was released more than 2 years ago.
