### ISSUE TITLE
Npc Error

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1460]
Hello, i changed my ubuntu 12.04 to ubuntu 15.04 and i get this error constant on console:

Lua Script Error: [Npc interface]
data/npc/scripts/default.lua:onThink
data/npc/lib/npcsystem/npchandler.lua:185: bad argument #1 to 'remove' (position out of bounds)
stack traceback:
[C]: in ?
[C]: in function 'remove'
data/npc/lib/npcsystem/npchandler.lua:185: in function 'releaseFocus'
data/npc/lib/npcsystem/npchandler.lua:346: in function 'unGreet'
data/npc/lib/npcsystem/npchandler.lua:524: in function 'onThink'
data/npc/scripts/default.lua:8: in function

If i back to ubuntu 12.04 the error dont occour. I testes in-game and the error occour if i talk about 'passage' with 'captain haba' in svargrond, if i using ubuntu 12.04, he teleport me 100%, in ubuntu 15.04, he dont teleport me and appear this error.

**Comment by diath** [comment]
See my comment in #1395.

**Comment by kanohn** [comment]
Dont works, please help.
