### ISSUE TITLE
Changing outfits while mounted into a looktype that has no mount sprite crashes the client

### ISSUE THREAD

**Issue by Xileck** [otland/forgottenserver#1462]
How to reproduce:
Mount in any of the outfit except the Gamemaster one then change to gamemaster outfit and it crashes the client for you and people around.
##

**Comment by ranisalt** [comment]
Update your distro. This was fixed with #1368

**Comment by Xileck** [comment]
i'm using the latest distro, and just checked to be sure but yeah it does contain the code of that fix

**Comment by ranisalt** [comment]
Already fixed.
