### ISSUE TITLE
About UnsafeScripts and ConvertUnSafe

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1465]
Hello,

I have a question in relation to these functions in config.lua.

I migrated my tfs tfs server 1.0 to 1.1, and let these functions disabled, but after 9horas uptime, my server crashed, I am without the log now ..

Enable these functions prevents run scripts that are not safe? Actually it may have been the reason that the crash? I used the distro tfs 1.0 with my datapack and never crashed and my server has two weeks.

**Comment by kanohn** [comment]
Why closes my question? how can i add labels on issues?

**Comment by ranisalt** [comment]
Because you should ask on OTLand support. Please stop asking your every single questions here on the issue tracker once and for all, this is only for issues with the server code and not to answer your doubts and scripting problems.

And only Mark, Korn and the other owners can change labels.

**Comment by kanohn** [comment]
Ok, im sorry, thank you.
