### ISSUE TITLE
Removed.

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1473]

**Comment by Cavitt** [comment]
Can confirm this is an issue. Tested the exact scenario described in this report.

**Comment by Cavitt** [comment]
Confirmed this is an issue.
@marksamman this doesn't exist on ShadowCores, it only pushes you back once.

**Comment by kanohn** [comment]
As i said, I tested in TFS 1.0 and not crashes with that, only in TFS 1.1. I saw that functions on "fromPosition" in movements.cpp are different.

**Comment by kanohn** [comment]
@marksamman 

This bug will be ignored? impressive is that in TFS 1.0 did not have this bug, and 1.1 crashes the server.
