### ISSUE TITLE
Changing the length of which text that are displayed on screen is breaked

### ISSUE THREAD

**Issue by bangbus** [otland/forgottenserver#1475]
This is not an issue but more of a question, I dont know where else to ask. The people at sites like otland aren't that knowledgeable.

What I'm wondering is what do I need to edit in the sources for messages that are displayed on the screen.

You know, messages that show up in the middle of the screen e.g on skill advance, broadcasting messages, looking at a door of a house.

example:
You see a door.
It belongs to house 'Blah blah uno, 
Flat 666'. Nobody owns this house.

Why does it linebreak after flat? everything does break after that length.

instead of 

You see a door.
It belongs to house 'Blah blah uno, Flat 666'. Nobody owns this house.

where do I change this?

**Comment by ranisalt** [comment]
Either keep it open or closed.

This is handled by the client.

**Comment by bangbus** [comment]
I don't know what happened, it went crazy.

it is huh? thanks anyways then
