### ISSUE TITLE
XML status bad formed

### ISSUE THREAD

**Issue by cmarfil** [otland/forgottenserver#1476]
Hello,

Otservlist has reported me this bug.
http://s29.postimg.org/b11lu0ajr/screenshot_103.png

The status is not displayed properly, do not do well formed XML, there is a comma at the beginning.

Any idea?
What I can look? and How to test this?

TFS 1.1

Thanks!

**Comment by djarek** [comment]
My guess is that if this occurs consistently, then it might mean that some binary garbage (0x2c or 44d) is pushed at the beginning of the packet. Either the header of the output message is improperly written or the start of the output message is improperly set.

**Comment by ranisalt** [comment]
I have actively developed a library that checks server status [(check here)](https://github.com/renatorib/otinfo) and it has been used on some server lists but none of them ever reported this issue.

I think you are having encoding issues related to your operating system. Could you check that on *nix?

**Comment by cmarfil** [comment]
The server is running on Ubuntu 14.04 :S

**Comment by marksamman** [comment]
When you say that you're using TFS 1.1, are you using the version that was released in May? Have you made any modification to your source code (and if so, please include the full diff)?

**Comment by cmarfil** [comment]
Hello,

I followed exactly the steps (two days ago):
https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu

Thanks.

**Comment by marksamman** [comment]
Then you're not using 1.1, it shouldn't even say 1.1 when you're starting the server.

**Comment by cmarfil** [comment]
so what should I do? :S

**Comment by marksamman** [comment]
You should use 1.1 if you're ready to put your server into production, 1.2 is nowhere near release so it's not considered stable at this point.
