### ISSUE TITLE
Failure to compile latest source in VC13

### ISSUE THREAD

**Issue by Alscara** [otland/forgottenserver#1477]
Y'ello.

Just attempted building the latest source in VC13 on two different computers with latest SDK on both, one with latest boost (1_58_0) and one with 1_57_0.

Gives me error
LNK1104: cannot open file 'libboost_system-vc120-mt-gd-1_58.lib'
(replace 1_58 with 1_57 for the one using 1_57_0)

I checked the file, and it exists and it's not corrupted (redownloaded entire boost and re-linked it. Same issue. Not sure if it's related to some new change. I was able to build just fine about a week or two ago with the then-latest sources.

**Comment by Alscara** [comment]
Also, tried as administrator and not, no change either way.

**Comment by djarek** [comment]
It might have to do with architecture incompatibility. Are you trying to link against a 64 bit library with a 32 bit build?

**Comment by Alscara** [comment]
Building 64-bit release on a 64-bit system with the default library which I'm assuming is 64-bit since it's the same one I used last time which worked fine.

**Comment by marksamman** [comment]
I can't reproduce this, compiling with VS2013 is working fine for me except for a couple of warnings which I've already opened a separate issue for, but it still compiles. Are you sure you installed the 64-bit boost libraries?

**Comment by Alscara** [comment]
I am absolutely partially sure. I downloaded them from the 64-bit link for sure, but is there a way to check compatibility issues or something? I'll try redownloading once again and see if it makes any difference.

**Comment by Alscara** [comment]
I know 100% for sure that the 1_57 is the 64-bit because I made no changes to it and it compiled fine a couple weeks ago. Only thing that changed were the source files on that one. But I'll try again on the new one.

**Comment by EvulMastah** [comment]
Make sure it is in the amd64 subdirectory ;)

**Comment by Alscara** [comment]
I placed them in C:\Development, same as before.

**Comment by EvulMastah** [comment]
What you could try is to take boost libs (x64) to Visual Studio/VC/lib/amd64/

**Comment by Alscara** [comment]
may be helpful to note, this error occurs after wildcardtree builds. so it makes it through most of the build, it finds the initial boost stuff, just not this particular file.

**Comment by Alscara** [comment]
Tried moving the x64 libs to amd64, still nothing

**Comment by djarek** [comment]
Did you try completely removing all compiled objects and starting a fresh build?

**Comment by HeavenIsLost** [comment]
Its may be related to the subject, my friend tried to compile tfs 1.2 and he get thiis error:

http://i.imgur.com/OSruxoA.png

Its related to a older boost?

**Comment by Alscara** [comment]
@djarek yup. didn't help.

I just took my laptop out of sleep mode and tried again. Now it worked. the warnings that Mark mentioned, but other than that, full build no errors.

I can't tell you why it worked because I changed nothing from my last attempt. No idea. 'spose I'll just close this and hope it continues to work.
