### ISSUE TITLE
Union on LuaVariant

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#1481]
Hello,

Couldn't we use an union of the LuaVariant struct to save up a few more bytes?
https://github.com/otland/forgottenserver/blob/master/src/luascript.h#L71-L81

From what I know, the purpose of an union is exactly that, to create a class that can contain only one value at the same time, and LuaVariant does just that. Thus, we could shave off a few bytes - around 9 bytes for the number + Position, plus aligning bytes.

**Comment by diath** [comment]
I don't think you can have an std::string in an union.

**Comment by kornholi** [comment]
C++11 relaxed restrictions on unions and I think it is allowed now

**Comment by djarek** [comment]
Non-trivially constructible types are allowed in unions, however a lot of dragons and undefined behavior await in that foreign land.

**Comment by ranisalt** [comment]
No, it's not that hard. You can have non-trivial types if you know what is the type being used, and we have it.

I did it for the sake of experimentation:
https://github.com/ranisalt/forgottenserver/blob/9cd7271f3481a371e00122e68074c7312605e901/src/luascript.h#L76-L89

Does not seem to leak memory, too. I summoned a big ton of monsters and they all casting spells at the same time crazily didn't seem to rampantly increase memory usage.

**Comment by kornholi** [comment]
seems to work fine: https://gist.github.com/kornholi/1a4c49c51b762b3e4c79

**Comment by marksamman** [comment]
If we're doing this to decrease memory use, the string should probably be a pointer (like in item attributes).

**Comment by ranisalt** [comment]
Yes, that would be the best solution
