### ISSUE TITLE
Bug house invite

### ISSUE THREAD

**Issue by walissonsantos** [otland/forgottenserver#1482]
https://www.youtube.com/watch?v=4Mwi0yf_DBM

It is possible to invite even outside the house so seen in the video.

**Comment by ranisalt** [comment]
Man, that vid is 9 minutes long... Can you just point where the bug happens?

**Comment by walissonsantos** [comment]
This video was a player who created it.

The bug is: the home owner puts the name on the flip sound and then the player can open the aleta sio and keep it open when the homeowner withdraws name, the other player presses ok and invita again (without permission)

**Comment by ranisalt** [comment]
Oh, I figured out what is the bug. Wait a minute and I'll fix it.

**Comment by walissonsantos** [comment]
ranisalt, your solution works only when the player is kicked, if the player walk out of the house before being kicked he can auto invite

**Comment by ranisalt** [comment]
Does the trick now :) I didn't think it was even possible to walk while editing a house list, but OTC also can do it.

**Comment by walissonsantos** [comment]
I also found that it was not possible until a friend showed me. I will create a video and post showing.

**Comment by ranisalt** [comment]
Yes, I tested it and it's possible, I also updated the fix.

**Comment by walissonsantos** [comment]
100% :D
