### ISSUE TITLE
Issue with Shared Exp

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1484]
Hello, im here to report a new issue with shared exp.

I Tested sometimes, when you enabled share experience, sometime give the correct exp and sometimes gives incorrect exp.
I'm already considering the stamina exp bonus, is not that what you're doing incorrectly give exp
Example:

If a monster gives 2000 exp and we have a 20% share bonus and sharing with 2 peoples:

 2000 + 20% / 2 = 1200 (It was to give this exp every time, but sometimes the exp increases about 400 + - with no reason)

**Comment by ranisalt** [comment]
What is your testing ground? Players vocations, stamina bonus, and what monster did you test hunting?

**Comment by kanohn** [comment]
I Tested with different vocations and same vocations, the exp bug even though.
I tested in others servers using tfs 1.1+ and the same thing happens..

I summoned a rotworm and others monsters, tested with different vocations and same vocations, with different bonus, does not matter. sometimes the shared exp returns the correct experience and sometimes an experience somewhat higher than expected.

has nothing to do with stamina bonus, I also tested everything, without the party exp active the experience returns with 100% all working bonus.

**Comment by ranisalt** [comment]
Can you tell me exactly what happens when you hunt with different vocations (and how many) and the same (and how many players)?

It happens to track the bug.

**Comment by kanohn** [comment]
As I said, and I repeat, no matter how many people are in the party, whether it is the same vocation or not, the bug is on exp when shared is active.

There are times that the experiment returns as expected, but sometimes returns a exp a little more or less, we can call it something out of logic, I have no idea of what can be, since the formula seems to be correct, but this bug happens with all servers that use tfs 1.1+

You can even test, open a test server and enable exp shared, you will realize that the exp will not return 100% every time you kill a monster

**Comment by TwistedScorpio** [comment]
Could we relate this issue to this?

https://github.com/otland/forgottenserver/issues/1236

**Comment by ranisalt** [comment]
Follow #1344

**Comment by marksamman** [comment]
This may have been fixed by #1579, please open a new issue if the issue persists.
