### ISSUE TITLE
Client crash 10.80

### ISSUE THREAD

**Issue by olszak94** [otland/forgottenserver#1485]
I've changed definitions.h protocol to be 10.77 - 10.80, and whenever i try to connect via 10.80 client it crashes my client.

**Comment by ranisalt** [comment]
That's because you have to do more than just change definitions to update the client.

Use 10.76 or 77 instead.

**Comment by olszak94** [comment]
Could you point me, what is there to change ?  I would be grateful!

**Comment by ranisalt** [comment]
No, I don't. I guess you have to debug the client line by line to see where the protocol for 10.80 differs from 10.77.
