### ISSUE TITLE
Talkaction commands executed by certain group debugs all connected players

### ISSUE THREAD

**Issue by raymondtfr** [otland/forgottenserver#1488]
Talkaction commands "!z" and "!x" crashes all connected players if, and only if it is executed by a player of groups "2" or "3" (gamemaster or god).

**Comment by ranisalt** [comment]
I can't reproduce it. I tried with god, gamemaster, using valid and invalid values for both talkactions and had no problems using the latest commit.

**Comment by raymondtfr** [comment]
Oh sorry, I've been busy for a few days. I tried using both raw commands ("!x", "!z"), I made no changes to its script in lua "magiceffect.lua" or "animationeffect.lua". I just typed in the default channel > !z and it debugs tibia right away.

**Comment by ranisalt** [comment]
A friend of mine reported this problem using the Tibia client, I was using OTC. The problem is not on the server, is on the Tibia client.

**Comment by WibbenZ** [comment]
What about making a list where the constants name are aswell as the id they resemble to then be able to check if they exist or not.
(Would probbly not be the best to do this in Lua, since we would then have to add the new effects on 2 places).

**Comment by ranisalt** [comment]
@WibbenZ that would be a huge hardcoded list anyway, which is a bad idea

**Comment by WibbenZ** [comment]
Adding a boolean function then, iterating through the enum to see if it contains the value we are trying to get.
That way we would not need any huge lists, no extra work when we update the protocol etc etc
