### ISSUE TITLE
Death to monster in Pvp Zone Tile

### ISSUE THREAD

**Issue by walissonsantos** [otland/forgottenserver#1491]
If a monster kill the player in a pvp zone tile, the player dies and relogin infinitely.

Sorry my bad english.

**Comment by luanlucian93** [comment]
Confirmed.

**Comment by ranisalt** [comment]
Can you provide a video or gif with demonstration?

**Comment by vankk** [comment]
I can confirm this bug!

@ranisalt 
![animation](https://cloud.githubusercontent.com/assets/14372849/13309918/f4e92066-db5f-11e5-8a0e-3b398cfd6abc.gif)

**Comment by ranisalt** [comment]
I believe it's because you are not supposed to be killed on a PvP zone tile, but that is only checked if you are hit by a player. PvP zone tiles are not supposed to host monsters, only players and summons if applicable.

**Comment by vankk** [comment]
> PvP zone tiles are not supposed to host monsters

I agree with that but there is no way to fix this? Avoid this type of error.

**Comment by ninjalulz** [comment]
@ranisalt Please close this issue.
