### ISSUE TITLE
RSA mutex

### ISSUE THREAD

**Issue by djarek** [otland/forgottenserver#1494]
Is the mutex in the RSA class really necessary? It seems that it would only be required if we offered a way to change the RSA key at runtime, because according to gmp docs, all 3rd party calls we use there are thread safe. https://gmplib.org/manual/Reentrancy.html

**Comment by marksamman** [comment]
If that also applies to mpir then we can remove the mutex.

**Comment by djarek** [comment]
http://mpir.org/mpir-1.3.1.pdf#20
The same restrictions apply
