### ISSUE TITLE
Max Tile Items

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1495]
Hello,

Now a player came to me comment that the server could lag / crashing with too many items in the house. (NOT INBOX)

PS: I already put maxInboxItems to fix the problem inbox

LOOK: http://s13.postimg.org/hcw4jh6vr/stack.png

I was testing it, and made many items in each tile, If /save , gave a lag of 4-5 seconds, if you have several houses with this issue, can crash the server..

I saw that each tile has a 255 stack, but I can move items with much more than that limit, if i put inside the backpack or parcels, accumulating many items, i see in mysql table in tile_store have a big item data.

**Comment by marksamman** [comment]
Marking this as an enhancement to look into optimizing that code. As for the crash, please provide a stack trace.

**Comment by kanohn** [comment]
I'm not sure if crashes or not, only the player told me so, I ask you, if the save take too long to save the house tables for excess items may crash? thanks

**Comment by marksamman** [comment]
No.
