### ISSUE TITLE
Skill rates problem

### ISSUE THREAD

**Issue by iskabin** [otland/forgottenserver#1496]
Distance Fighting is advancing faster than club, axe and sword fighting, doesn't matter how I configure vocations.xml, tried to turned off "onGainSkillTries" but the problem persists.

In a Knight for example, I get more "skill_dist_tries" per attack than "skill_sword_tries", even though I set skill id="3" multiplier="1.1"  and skill id="4" multiplier="1.4" . No matter what values I set in there, Distance always advance faster.

What could it be?

**Comment by EvulMastah** [comment]
This is supposed to be like that.

https://github.com/otland/forgottenserver/blob/master/src/weapons.cpp#L857

**Comment by iskabin** [comment]
Ohh, I see ^^ But still, when I edit the rates in vocations.xml, it don't change a thing in the game, if skill id="1" multiplier="1.1" and skill id="2" multiplier="3.1", they skill advance in the same rate :/

**Comment by ranisalt** [comment]
Only for skill level 10.
