### ISSUE TITLE
Fire Field First Use Bug

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1500]
Hello,

The fire field are bugged, i think can be in sources..

If you use a fire field in a char, no damage, only if the char out of the fire field and walk again on her.

Tested with other types of field as energy field, poison, etc., are fine.

if monster hit with fire field too, do not cause the first damage.

**Comment by ranisalt** [comment]
For fuck's sake STOP spamming issues, you are NOT using the code from this repository.

Just tested it, placing a brand new fire field using the rune on the floor and walking on it.
https://youtu.be/3wHnlGZ_va4

And, as expected, it works properly. Use the support forums, your issues are always non-related to the source code and I already told you that.

**Comment by djarek** [comment]
I got the impression that he meant that using the FF on a player doesn't cause fire damage to him (I didn't test it if it happens or not).

**Comment by kanohn** [comment]
no comments @ranisalt 

I have a very bad English, use a translator, but my questions are not difficult to understand, because @djarek  understood what I meant.

Your video you showed has nothing to do with my question ..

I said, IF ANY PLAYER OR CREATURE USE FIRE FIELD IN PLAYER, HE WILL NOT GET DAMAGE! ONLY IF OUT OF FIELD AND RETURN.

if you do not understand again I repeat many times as you want, and yes it is a bug in the sources of this repository. If not, a thousand excuses, but I'm pretty sure it's

Test and then let me know.

**Comment by kanohn** [comment]
@ranisalt what this?

**Comment by ranisalt** [comment]
I understood your problem now, I could reproduce it and I'm trying to fix.

**Comment by kanohn** [comment]
ok, sorry for all the confusion

**Comment by kanohn** [comment]
@ranisalt 

I'm thinking that this bug fire field may have something to do with items.otb

I'm already using the original otb the tfs 1.1
