### ISSUE TITLE
Enhanced NPC System

### ISSUE THREAD

**Issue by totolol123** [otland/forgottenserver#1504]
Why not implement that NPC System and improve it? This looks really good and can be easily customizable and for the new NPC System in roadmap i think this is a good start.

here the link:
https://otland.net/threads/enhanced-npc-system-0-01alpha-released.143943/#post1384937

what you guys think about it?

**Comment by marksamman** [comment]
Because it's completely different and we're not going to break backwards compatibility when we rewrite the NPC system.

**Comment by totolol123** [comment]
Alright :p
Thanks.
