### ISSUE TITLE
Segmentation fault on Item::getTile()

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#1506]
I was playing with the field creation trying to help with #1500 and coded the snippet:

```
		Item* item = Item::CreateItem(itemId);
		if (caster) {
			item->setOwner(caster->getID());

			if (MagicField* field = item->getMagicField()) {
				if (Tile* tile = field->getTile()) {
					CreatureVector* creatures = tile->getCreatures();
```
But it gives me a segmentation fault on `field->getTile()`, more precisely on that if:
```
	Cylinder* cylinder = getTopParent();
	//get root cylinder
	if (cylinder->getParent()) {
```
The `getTopParent` function returns nil and it is not checked.

**Comment by kanohn** [comment]
@ranisalt 
This fix the fire field bug?

**Comment by ranisalt** [comment]
@kanohn no, this is another bug
