### ISSUE TITLE
Ability to overwrite otb

### ISSUE THREAD

**Issue by WibbenZ** [otland/forgottenserver#1508]
Just found this thread; https://otland.net/threads/make-border-walkable.235198/
And tought it would be great with a posibility to overwrite the otb attributes via Lua / items.xml.

something like:
```
Item:setAttribute(ATTRIBUTE_IS_WALKABLE, bool)
```

It is ofc posible to just change the otb file manually, but this way we can change just those items we want changed.

**Comment by djarek** [comment]
Are these changes meant to be persistent? Also, aren't attributes associated with ItemType rather than each individual Item instance?

**Comment by WibbenZ** [comment]
Atleast till the server restarts.
They are, so it would have to require attributes to the Item class (like 0.x).

**Comment by Kamenuvol** [comment]
I suppose it won't work because items.otb copies the attributes from tibia.dat
If you change only otb, the client will not "see" the difference
That's why I am against otb. I think it is not useful.

**Comment by WibbenZ** [comment]
Well this would keep backwards compatability aswell as give us new things to work with.
Lets say you wanna create a game where the player has to think, ex. putting him a box and once he finishes the mission he can walk through the wall / boarder etc etc

And I think it would work, aslong as we add the posibility to overwrite the otb loadings.
Nothing would have to be changed on the client side or otb file, since it would do the changes after that.

As you can see here (the loading function) https://github.com/otland/forgottenserver/blob/master/src/items.cpp#L144-L382
We should be pretty easily I guess rewrite it, atleast if we some how copy the attributes we load from the OTB file to each item.

**Comment by djarek** [comment]
On further consideration I have to agree with @Kamenuvol. While an interesting idea, it might not be worth the added complexity, especially considering the limitations of both the client and the protocol.

**Comment by WibbenZ** [comment]
I don't think it would be that hard tbh, sure it will require some more code etc but I still think it's worth looking into.
It seems like cipsoft is doing something like this aswell (so we are not limited by the client or dat file) seeing as ex mwalls in wars can be walked through if you have not attacked the caster etc etc

This would also make it posible to add light to certain items etc

**Comment by ranisalt** [comment]
It would also make possible creating items with random stats and abilities, which is fairly useful for RPG servers.

**Comment by djarek** [comment]
Then perhaps we should store the overriden attributes with the item in the database instead of overwriting the otb files. We could use Boost Flyweight to store the attributes to save memory (this would require a slight rework of the ItemType class). Here's the documentation of Boost Flyweight:
http://www.boost.org/doc/libs/1_58_0/libs/flyweight/doc/index.html

**Comment by WibbenZ** [comment]
It would be fine with the ability to just overwrite ItemType, but I think it would get alot more use if it could overwrite just one item.
Isen't there any good way to IF we change the attributes fetch it from the ItemType otherwise from the Item class.
This would mean we have to load ItemType things as an Item or add an extention to the ItemType class to allow it to serach for a specific Item.

**Comment by djarek** [comment]
IMO the best solution in our case would be a sort of CoW system: items inherit their attributes from their base ItemType, however, if you want to modify the ItemType, a copy is created behind the scenes and the Item has a different ItemType. To limit memory usage we could employ some sort of a simple deduplication mechanism.

**Comment by WibbenZ** [comment]
Sounds good Djarek :D

**Comment by Kamenuvol** [comment]
Some informations about Cipsoft's Tibia:
-items can have more than a name. Ex: wooden tile and loose board (Rook)
-items can have capacity changed. Ex: plum tree on Femor Hills, dead tree? near Blood Herb Quest

Maybe we could have default properties as it occurs now in items.xml and change these properties for specific items in mapeditor and scriptings.

**Comment by WibbenZ** [comment]
Taking Cipsoft as an example was a bad ide, since Mark does not wanna mimic Cipsoft.
But IMO it could be used for alot of things, as you also explained(even if it's from Cipsoft).

Everything that we have in the game should be modifiable via Lua IMO.
We have things like Creature:addMana(-500), why not the ability to set stats to items(will be added) aswell as the ability to change real attributes of the object, ex. can be walked through, path finding as explained above etc etc.

**Comment by Kamenuvol** [comment]
I agree, and I think some properties could be changed in map editor as well.
About the comparison, I don't see the example I made as an attempt of mimic Cipsoft. It's only another way to make properties modifiable.

**Comment by marksamman** [comment]
Custom items will not touch the OTB, they will specify a client ID of which they derive client attributes. You will not be able to overwrite any OTB attributes that puts the client out of sync with the client, if you modify the client you should also modify your OTB file directly. You can't make an item walkable in the server if it's not walkable in the client, because the client will not even try to walk on it, and the client has no idea what the ground speed is either; the other way around is possible though but the client will snap back as if you're trying to walk into a house you're not invited to, and in that case you can just register an onStepIn event for that item id and teleport back to the previous position (and in the future you'll just be able to return false).

**Comment by WibbenZ** [comment]
Well it's sad to hear, since Cipsoft has to be able to do this in some way and ive looked at the parser of the flash client and can't find anything that we are missing that could be linked to this.
But the movement "return" will it really block the creature, like you are walking into a wall or will it teleport the creature back?
