### ISSUE TITLE
getCapacity and getFreeCapacity seems to return wrong

### ISSUE THREAD

**Issue by cornex** [otland/forgottenserver#1512]
So, I have 407 cap on my character. It is a normal account, not a GOD or something like that. When I use the getFreeCapacity i get 40650 as output.. 

The code snippet is running from global.lua, 

```LUA
function test()
	player = Player('Charname')

	print(player:getFreeCapacity()) -- returns 40650 on 407 cap

	addEvent(test, 5000)
end

test()
```

**Comment by cornex** [comment]
Kinda seems correct when I look at it again, please lighten me up :)

**Comment by ranisalt** [comment]
Just for future reference, this function returns tue current capacity in hundredths, not integer. That is, if you have 406.50 of remaining capacity (e.g. gold coins have less than 1 oz), then it returns 40650, not 406.5
