### ISSUE TITLE
closeShopWindow(cid) and npc:closeShopWindow(player) is not working.

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1518]
as stated in title.
Using these functions in creaturescript or talkaction will not close the opened shop window.

Although sometimes it does. But I have no clue why it happens..

While im already bringing issues up I have an another question.
Is this suppose to be like that now?
print(item:getUniqueId())
will print the item UID and then the item UID changes... .. .
So in other words we cant record items by their uid anymore.

**Comment by marksamman** [comment]
They can only be called from the NPC interface.

**Comment by whitevo** [comment]
Will it ever change?
 I figured out how to call it anywhere else. (gotta execute function at the same time when any of the npc's onThink() activates)
But that is pretty annoying.

**Comment by WibbenZ** [comment]
You can try this;
```
local networkMessage = NetworkMessage()
networkMessage:addByte(0x7C)
networkMessage:sendToPlayer(player)
```

That will close it on the client side.
So if it works just rewrite the NpcScriptInterface::luaCloseShopWindow function to fit your needs.
Can be risky, but give it a try :p

**Comment by whitevo** [comment]
(NpcScriptInterface::luaCloseShopWindow function) ??
You know I don't do source edits xD

But that whatever you just suggested works :o 
How did you know the byte code for that function Oo?
and why it is risky?

Anyway thank you, it will replace the huge ugly looking 'for loop' addevent mechanism

**Comment by WibbenZ** [comment]
https://github.com/otland/forgottenserver/blob/master/src/npc.cpp#L811
Leads to https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L1306
And that leads to https://github.com/otland/forgottenserver/blob/master/src/player.h#L990
And that leads to the end where the package code is; https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L1475-L1480

Then you convert it to Lua and use it :p 

The risky code is the things that are executed by the server before that package is sent, could cause memory leaks etc if you don't release everything.

I would rewrite the system to even if the server returns false, send the close shop.
Worst thing that could happen is that the client could crash if the shop isen't open.
