### ISSUE TITLE
Gitter for forgottenserver

### ISSUE THREAD

**Issue by comedinha** [otland/forgottenserver#1523]
It would be cool create a chat in gitter for forgottenserver
https://gitter.im/

**Comment by WibbenZ** [comment]
Waste if you ask me, just look at ORTS: https://gitter.im/orts/server?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

Better you use OTLand where there actually are people active and can respons.

**Comment by comedinha** [comment]
The gitter is not very active, but I see great potential for it :3

**Comment by marksamman** [comment]
Use OTLand.
