### ISSUE TITLE
Always changing UniqueID is annoying!

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1525]
I will post it as a separate issue.

Item unique ID is changed over time if its used or called trough script.
Why is that? Can't we just keep it the way it is so we could easily find that item and do something with it in future if we have the item unique ID.

item:getUniqueId()
addEvent(function() print(item:getUniqueId()) end, 1000)
will give 2 different Values.
And that is pretty annoying if you ask me.
With TFS 1.0 it was all nice and good.

**Comment by djarek** [comment]
I think this is unintended behavior - if an item has no UID the script system will assign a new UID, however, the next time you check the UID of that item this function does not check if this particular item has already been registered.

**Comment by marksamman** [comment]
This is working as intended.

**Comment by whitevo** [comment]
as for "unsafe" just wrote fast demonstration.

But we cant set Unique ID s with Lua :| 
Why would you make this mechanic worse than it was previously?

It was much easier, faster and better to handle items when the item got his uniqueId when it was created to game.

**Comment by marksamman** [comment]
It's working as intended, and essentially the same as before when used properly. If you're having issues with it, you're either using it wrong or you've failed to demonstrate how you relied on the changed behavior properly. Besides, you should not use the temporary uid's that you get from Item.getUniqueId() in new code, they only exist for backwards compatibility. You should use item userdata.

**Comment by whitevo** [comment]
as djarek mentioned and as I have learned passing userdata trough addEvent is unsafe.
It crashed my my server nonstop before I knew its not safe.
And after that I started passing item:getUniqueId() trough addEvents.

When event time came, I constructed the item userdata.
If it didn't exist then return false. easy. no crashes here.

But when passing item and trying to see if it exist and it doesn't. Don't wana go on that rode where server starts crashing because of that.

It is not working as same way as before.
Before the Item uid did not change.

Currently I'm passing the item last position trough addEvent() and if it exists there then something happens.

What do you suggest to do lets say: teleport item after 24 minutes to town altar after item has been taken from altar. (and item can be anywhere by that time or even removed, we have no clue

**Comment by WibbenZ** [comment]
Wait are we supposed to push userdata values in scheduled events?
In that case why do we have the "warnUnsafeScripts"~?

**Comment by marksamman** [comment]
> as djarek mentioned and as I have learned passing userdata trough addEvent is unsafe.

Correct.

> It crashed my my server nonstop before I knew its not safe.
> And after that I started passing item:getUniqueId() trough addEvents.

That is only OK for items that have a unique ID on the map. For items without a persistent unique ID, the unique ID you get from that call is temporary, and will only be the same during the same Lua call.

> When event time came, I constructed the item userdata.
> If it didn't exist then return false. easy. no crashes here.

This should always have failed for items without a persistent unique ID, if it succeeded in 1.1, that was a memory leak and a bug.

> It is not working as same way as before.
> Before the Item uid did not change.

Please post an example script that worked in 1.1 and stopped working in 1.2.

> Currently I'm passing the item last position trough addEvent() and if it exists there then something happens.

This is what you should do, assuming the items position will not change. If it can change, then a player can just pick up the item and logout, or throw it in the water, or stack it with other items etc.

**Comment by whitevo** [comment]
[QUOTE]This is what you should do, assuming the items position will not change. If it can change, then a player can just pick up the item and logout, or throw it in the water, or stack it with other items etc[/QUOTE]
How did you quote me xD.
Anywho that is annoying because then I would have to make item tracker script to finally find out where the heck is that item now.

[QUOTE]This should always have failed for items without a persistent unique ID, if it succeeded in 1.1, that was a memory leak and a bug.[/QUOTE]
it was TFS 1.0
and as on post one I showed you how i used it.
I did something like that:
local item = Game.createItem(itemID, 1, pos)
local itemUID = item:getUniqueId()
addEvent(removeItem(), 50000, itemUID)

**Comment by ranisalt** [comment]
Use &gt; to quote instead
> Like this

**Comment by whitevo** [comment]
and how you cancel it?

**Comment by whitevo** [comment]
well back to this problem.. This is so annoying.

Is there any solutions to track the items?
This seems impossible right now..

Can I at least set UniqueID's with itemattribute if I remove this in luascript.cpp?:
if (attribute == ITEM_ATTRIBUTE_UNIQUEID) {
			reportErrorFunc("Attempt to set protected key \"uid\"");
			pushBoolean(L, false);
			return 1;
		}

And how would it affect the temporary UID creator?
Hopefully it has no problems and wont create duplicate UID's

What i was thinking is do something like this:
tempUID = item:getUniqueId()
    item:setAttribute(ITEM_ATTRIBUTE_UNIQUEID, tempUID)

This maybe allows me in future to do this:
Item(uid):getPosition()

And if the container parent is added too one day. Could even see to who this item belongs to.

**Comment by whitevo** [comment]
Ok this unique ID problem is keep popping up again and again on TFS 1.1 and above
Apparently I can't even move items with Unique ID now..

Mark, if you cant bring any good reason why unique ID works like it is right now
I will either have to figure out how to make at the unique ID's at least moveable 
(which I have no clue about)
or
go back to TFS 1.0 and spent weeks to convert my scripts back to TFS 1.0

**Comment by WibbenZ** [comment]
My best tip is to look at the logs, try to find what the changes was and add "mirror files" so you can easily revert the changes in the future in your own source.

**Comment by whitevo** [comment]
How to look the logs?
This github is confusing

**Comment by WibbenZ** [comment]
https://github.com/otland/forgottenserver/commits/master
Download some software to check diffrences, go as far back as you can - the last commit that you used it in.
You can also try to locate the function itself, could be quicker if you are lucky :p 

About "where" the functions are, id say you most likely got something in item.cpp, that either returns false or return to a function in the game class.
Try to look for Game::***
Then replace *** with things like internal, item, etc etc

**Comment by ranisalt** [comment]
Complementing @WibbenZ if you remember a single commit where it worked properly (a version tag is also a commit) you can use git bisect to binary search for the commit where the fault was introduced. It will take log(n) steps instead of n, where n is the amount of commits you have to test.
