### ISSUE TITLE
TFS closes when an error occurs

### ISSUE THREAD

**Issue by WibbenZ** [otland/forgottenserver#1527]
Ive noticed this myself, aswell in alots of other threads; https://otland.net/threads/can-not-start-my-server-tfs-1-0.235713/
Tought it was only with me and a few others but tought it could be posted and hopefully others might come forward.

The problem seems to be that TFS closes right away when we thrown an error, ex. as the thread states the MySQL settings or it isen't started (as in my case).

Ill look into it to try and find it.

**Comment by djarek** [comment]
This is expected behavior of a console application - once it exits the command prompt closes as well, unless it was separately started.

**Comment by WibbenZ** [comment]
´``
		g_dispatcher.addTask(createTask([]() {
			g_dispatcher.addTask(createTask(
				std::bind(&Game::shutdown, &g_game)
			));
			g_scheduler.stop();
			g_databaseTasks.stop();
			g_dispatcher.stop();
		}));
		ExitThread(0);
```

That would make it posible to atleast read it. Trying to find a solution to why it says "the program has stopped responding"~ when I exit the program after reading the error.

Found this, but it dosen't seem to wanna work, I still the get error.
```

		SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX);
		_set_abort_behavior(0,_WRITE_ABORT_MSG);
```

**Comment by djarek** [comment]
This is not a proper way to solve it. On Windows the proper way is to log to a file. On UNIX-likes it is customary to print to stdout and stderr and let these be capture by the system logging daemon (like systemd-journald or syslog-ng).

**Comment by WibbenZ** [comment]
@marksamman how is this invalid? It's more or less a bug.
This was never a problem with the 0.x series.

**Comment by marksamman** [comment]
It's working as intended. The process should exit on failure, not hang.

**Comment by WibbenZ** [comment]
In that case why even throw the error?

**Comment by marksamman** [comment]
Because you can read it from stdout as long as you run the process in a way that you can see it. We should write errors to stderr though and maybe also forward it to a file.

**Comment by WibbenZ** [comment]
Ok good to hear, tought when you added the invalid and closed you pointed out that it wasen't actually a bug.
To seeing to all the threads on otland because people haven't started uniform / xampp etc it kinda is :p

**Comment by marksamman** [comment]
It isn't a bug, but it might not be ideal for Windows users who just run the executable right away so that the console closes with the process.

**Comment by djarek** [comment]
We should consider adding a unified logging system not only to make logging consistent, but also to perhaps add persistence (which would help newbies).

**Comment by WibbenZ** [comment]
Its already on the roadmap.
https://github.com/otland/forgottenserver/wiki/Roadmap-1.2
```
Update all log messages to be consistent
```

I guess no one has started since its a job that will be pretty boring :p

**Comment by djarek** [comment]
While I agree that updating log messages is a boring, designing an efficient logging system (which means either using explicit threading or using boost::asio) is not a trivial task.

**Comment by ranisalt** [comment]
This is only because Windows is full retard. You never go full retard.

You can fire up the command prompt, navigate to your TFS folder and run the server there, so the console won't close on error. That's the proper way to do, just like *nix.
