### ISSUE TITLE
player:onMove(self)

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1529]
Would this event be possible to do?

Does this event/funtion exist somewhere? i didn't find it

Uses for that event are:
Area changes will trigger scripts. (content areas are no longer seperated by tiles or their unique properties, but by invisible grid made in this event)

return false would not allow player to step 
(this would be the place to add the option where player cant move)
Right now "cant move" means that player will be teleported back to the tile where he walked from.

Walking can be made more effective when certain storage values or conditions met :)

**Comment by marksamman** [comment]
#775 #1049 #1188
