### ISSUE TITLE
Just a question about dispatcher

### ISSUE THREAD

**Issue by totolol123** [otland/forgottenserver#1532]
I trying to understand how dispatcher works and when we should use it, something like:
```c++```
g_dispatcher.addTask(createTask(std::bind(&ProtocolLogin::getCharacterList, thisPtr, accountName, password, version)));
```
someone can explain it a little?
Thanks.

**Comment by djarek** [comment]
This question belongs to the otland support board. https://otland.net/forums/support.16/
