### ISSUE TITLE
Quest chest bug

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#1539]
Why TFS 1.x is not compatible with old (great) quest system where you put items inside box in map editor and use check UID as storage ID?

BUG:
https://github.com/otland/forgottenserver/blob/master/data/actions/scripts/quests/quests.lua

I cannot test it on server, but this code for me means that, it tries to give 'chest' to player (without item inside):

    local itemType = ItemType(item.itemid)

I think it should be **item.uid** if you want to keep this script super simple (why don't you use my advanced quest script that was popular in all old TFSes:
http://opentibia.net/topic/121575-advanced-quest-chest/

**Comment by PrinterLUA** [comment]
https://github.com/orts/server/blob/master/data/actions/scripts/quests/system.lua
