### ISSUE TITLE
Exp Shared Bug

### ISSUE THREAD

**Issue by walissonsantos** [otland/forgottenserver#1540]
When the player is in the party and is with EXP shared activated, those that are within some SQM they get EXP, but if the player stands healing (Exura, exura gran), and are not attacking the monster he receives the EXP, besides the stamina is intact. decreases only 2 minutes and then to decrease.

**Comment by vankk** [comment]
I can confirm this.

**Comment by vankk** [comment]
@DSpeichert You forget to mark this issue and #2315  as closed and marked as fixed - The issue was fixed with #2472

**Comment by DSpeichert** [comment]
Fixed in #2472
