### ISSUE TITLE
Quest Description

### ISSUE THREAD

**Issue by MaxyTibia** [otland/forgottenserver#1544]
Any ppl can help me?
https://otland.net/threads/c-quest-description.235994/

**Comment by MaxyTibia** [comment]
@marksamman, why you have closed without comments? This implementation is for enhancement.
I did not give details here because the details are already on the topic.

**Comment by WibbenZ** [comment]
Because this is not our support forum.
This is the bug tracker.
Read the first page.

**Comment by MaxyTibia** [comment]
@WibbenZ, I do not need support, I only give an idea that can even be created a pull request as it is to improve the quest description.

**Comment by WibbenZ** [comment]
#1064 comment about it there; in details.
Please search in the future in that case.
