### ISSUE TITLE
Player String Storage and Creature Storage

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#1545]
1. I understand that for some efficiency and 'script safety' reasons, you prefere 'number' storage, but 'string' storage would be really useful for many scripts.

I think that should be added as new type of storage with functions like 'getStringStorageValue' and 'setStringStorageValue'.
1. Maybe add storage to creatures as it was in TFS 0.4? It was really useful for 'action'/'creaturescripts' to save some information in creature.

**Comment by ranisalt** [comment]
:+1: to storage on creatures, it's really good.

**Comment by brunominervino** [comment]
@gesior look:
https://gist.github.com/ninjalulz/481ff43ab084cdff69ae

About storage on creatures, I think it's good.

**Comment by PrinterLUA** [comment]
"Npcs and monsters are temporary, use global storages.
If you want to use strings then make some sort of tables for each numeric value."

I quote something @dalkon told me.

**Comment by gesior** [comment]
@brunominervino 
Send SQL query everytime you want to set/get storage? If you use it on 'players online' loop, it will freez server!

@PrinterLUA 
What? Make table of string that map to numbers? I want to keep in database string values!
Like player say '!mydescription I am cool guy' and I want to store it somewhere.

Use globalstorages? What? How? I got monster with some weird IDs and I want to keep for it few values. Is it so hard to add 1 array/map to Creature?

**Comment by WibbenZ** [comment]
I can actually agree on this, might be quicker to use numbers, but it's not that bad having the ability to use strings.
Insted of huge arrays to let the server know that Storages.WrathOfTheEmpror.Mission1.HasTalkedWIth* means 1001 etc

About adding a query with each get / set function is just crazy?
Thats the kind of stuff you find on OTLand IMO :p 

Best would be to store it in the memory till we restart / save etc and then save it to the database (like we do with integer storages).

But these things gets closed right away pretty much with the "wontfix" label.

**Comment by djarek** [comment]
@gesior
Asynchronous queries could be used to get and set storage values (though that requires the lua programmer to restructure their code to be "sort of" functional in style), too bad they're basically broken ATM (#1533).

Also, what's wrong with using a global lua table for creature storage? Making it persistent doesn't make sense for monsters anyway.

**Comment by gesior** [comment]
@djarek 
Memory leak? Monsters die, storages stay. J/K
Global storage would be nice, because you could keep tables and objects in it.

I spent too much time on 0.3.6/0.4 where each folder had own LUA environment.
Is it one environment for all scripts in TFS 1.2?

**Comment by djarek** [comment]
@gesior 
Last time I checked, almost all scripts run in the same lua_state (database migration scripts are the only exception AFAIK), so yeah, global variables seem to be global.
