### ISSUE TITLE
Just dont know what is it.

### ISSUE THREAD

**Issue by Krzysioka** [otland/forgottenserver#1554]
Ok, this is my problem:
My script has a little disadvantage, and when i am disselecting target my champ is still attacking for 1 sec. I dont care with that. But if i walk in the pz zone my combat mode dissapears, and i can log out (while next attack is coming for the target). If i log out, my server crashes, i understand why, but how to make combat mode (this 2 crossed swords idk how i should call that) in pz for those 3 additional seconds.

**Comment by marksamman** [comment]
Post your script.

**Comment by Krzysioka** [comment]
this is problem what i mean, script is ok for me, and i think u understand that i dont want to share my scripts....

**Comment by marksamman** [comment]
Then this is not an issue.
