### ISSUE TITLE
getPathTo is not working as expected

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1556]
I'm trying to move a monster from his position to his master position(spawn position). It works if spawn position is closer(20~25 sqms), but if if its not inside this range getPathTo will just fail(return false).

test code:
http://hastebin.com/ebazadabox.avrasm

**Comment by djarek** [comment]
I haven't delved too deep into the map code, so I only have a high-level understanting of it. Pathing is computed by using the A* algorithm (https://en.wikipedia.org/wiki/A*_search_algorithm). MAX_NODES is the maximal number of nodes that are taken into consideration, so doubling them increases the number of vertices in the graph that represents all possible paths. So, in the worst case the performance of the path search is going to drop by a factor of 4.

**Comment by marksamman** [comment]
This is working as intended, the current algorithm is optimized for max 512 nodes. If you increase max nodes, the algorithm may not be optimal and you should consider rewriting it using a priority queue.
