### ISSUE TITLE
PK on PZ

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1559]
Hello, 

I saw on my server lately some players have caught PK within the PZ, then I realized:

If the player throwing a fire field on the ground and enter the pz, and came another player and die in that fire field, the player who threw get PK.

someone can reproduce this? thanks.

**Comment by ranisalt** [comment]
I think this used to happen even on Tibia. The quickest solution would be to check if the owner of the field is logged out or on PZ when someone steps in, and only apply damage if not.

**Comment by ninjalulz** [comment]
It's working as intended. Player <b>A</b> can always relog to lose the skull.
