### ISSUE TITLE
Container::queryMaxCount() failing in special cases.

### ISSUE THREAD

**Issue by jo3bingham** [otland/forgottenserver#1561]
How to reproduce
Take any character with capacity (so no GM/God characters), open it's main backpack, and fill it's main backpack with whatever you want as long as one slot has a single gold coin in it and the rest of the slots are occupied. Do whatever else you have to to make sure the character has very little capacity left, but enough to carry at least 1 more gold coin.

Simply, you can:
Create a paladin of level 1008, clear its inventory, and give it's main backpack these contents: http://i.imgur.com/cz6jX2o.png

When you try to add another gold coin to that container from another source (e.g, ground) you will get a "not enough room" error even though there is room to stack and you have enough capacity. The return happens here: https://github.com/otland/forgottenserver/blob/master/src/container.cpp#L385

I haven't had time to pinpoint the exact issue, but I'm assuming it happens in the Cylinder->queryAdd() call in Container::queryAdd().

**Comment by HeavenIsLost** [comment]
My fix( Container::queryMaxCount): http://hastebin.com/ubebokagot.coffee

The issue(i have get it from my mental debugger, may be wrong):

When  Container::queryMaxCount is calling queryAdd(line 377) is is using the reminder as the count which means that if you have 1 gold in that slot you the reminder value is 99.

The query add will reach this piece of code:
https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L2391

So, if i understand correctly, that piece of code in player class will ask if player have the capacity for that 99 items(reminder) istead of the count(1,2,3,4,..) you are trying to add.

**Comment by jo3bingham** [comment]
@HeavenIsLost Thanks. That makes sense.

**Comment by Emilianenko** [comment]
Hey @HeavenIsLost how did you fixed this?
