### ISSUE TITLE
Why max amount of buttons in modal window is 4 ??

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1562]
Why max amount of buttons in modal window is 4 ??
Once again I have to write annoying work around because something was limited wtih no reason.

**Comment by marksamman** [comment]
Why even open an issue if you claim that we've limited something for no reason? Can you even point out where this limit is? Because I'm not seeing it, and until I see it this is not an issue with the server.

**Comment by whitevo** [comment]
What do you mean point out?
I said in post1 that Modal window button count is limited to 4.
You don't see it? Means you can have 5 or more buttons on your modal window?

**Comment by marksamman** [comment]
I mean that you should point out where in our code base that limit is, because as far as I know it doesn't exist. Yes, a modal window can have up to 255 buttons on the server. Whether or not the client will render them is a different question which doesn't belong in our issue tracker.

**Comment by whitevo** [comment]
Ok this, means problem is in client.
Cant wait until I'm ready to take on OTC.. Too much stuff piling up there!
