### ISSUE TITLE
Damage is reduced even if hand-slot items have no defense stats.

### ISSUE THREAD

**Issue by raymondtfr** [otland/forgottenserver#1567]
If your character isn't equipped with any equipment at all, and let's just say some monster deal a static damage over time. Now, if you equip any free hand slot with any of the following items: Assassin Star, Snowball, Crossbows (and more I guess), the damage you will now receive will be slightly reduced, even though your character is all bare and the item of your hand-slot has no defense (and of course no Arm) at all.

##### How to reproduce:
1. Throw all your equips away (that means Arm = Defense = 0).
2. Create a monster and edit its .xml file (so that you can make its melee damage static,e.g. as min = max.)
3. Let the monster hit you, and memorize its damage.
4. Now do the same thing, but before that equip any of your free hand slot with an item, such as Assassin Star (or Snowball), and notice the reduced melee damage the monster will deal on you.

I guess in this part of code it didn't check wether armorValue could be 0 (zero):
I guess it is in ```if (damage <= 0)``` where it really should be ```if (amorValue <= 0)```.

```c++
if (checkArmor) {
	int32_t armorValue = getArmor();
	if (armorValue > 1) {
		double armorFormula = armorValue * 0.475;
		int32_t armorReduction = static_cast<int32_t>(std::ceil(armorFormula));
		damage -= uniform_random(armorReduction, armorReduction + static_cast<int32_t>(std::floor(armorFormula)));
	} else if (armorValue == 1) {
		--damage;
	}

	if (damage <= 0) {
		damage = 0;
		blockType = BLOCK_ARMOR;
	}
}
```

**Comment by gesior** [comment]
This code calculates only armor damage reduction:
armor = 1 -> remove '1 dmg'
armor > 1 -> remove 'from 0.475  to 2 * 0.475 - rounded up' * armor
armor = 0 -> do nothing (no reduction)


Your 'defense' problem is here:
https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L440

    
    int32_t Player::getDefense() const
    {
    	int32_t baseDefense = 5;
    	int32_t defenseValue = 0;
    	int32_t defenseSkill = 0;
    	int32_t extraDefense = 0;
    	float defenseFactor = getDefenseFactor();
    	const Item* weapon;
    	const Item* shield;
    	getShieldAndWeapon(shield, weapon);
    
    	if (weapon) {
    		defenseValue = baseDefense + weapon->getDefense();
    		extraDefense = weapon->getExtraDefense();
    		defenseSkill = getWeaponSkill(weapon);
    	}
    
    	if (shield && shield->getDefense() >= defenseValue) {
    		defenseValue = baseDefense + shield->getDefense() + extraDefense;
    		defenseSkill = getSkillLevel(SKILL_SHIELD);
    	}
    
    	if (defenseSkill == 0) {
    		return 0;
    	}
    
    	defenseValue = static_cast<int32_t>(defenseValue * vocation->defenseMultiplier);
    	return static_cast<int32_t>(std::ceil((static_cast<float>(defenseSkill * (defenseValue * 0.015)) + (defenseValue * 0.1)) * defenseFactor));
    }
    
defenseValue is 0, but:
**if (weapon) {** // player got weapon
**defenseValue = baseDefense + weapon->getDefense();**

defenseValue = **baseDefense** + weapon->getDefense();

**baseDefense** is 5, so when you wear ANY weapon or ANY shield, it increase your defense by 5.
Plus.. it uses 'distance' (for assassin stars) as your 'defense' skill, not 'shielding', so paladin with weak shield uses 'assassin star' to block hits + uses his 'distance skill' (high), not 'shielding' (low).

**Comment by raymondtfr** [comment]
Oh, thanks, I don't understand much about these ideas (defense, etc) and how they work together modifying defense values. I guess when I have more time of research I can also improve our formulas based on Tibia-stats, if they're already similar to theirs. I much appreciate you for making it crystal clear to me!
