### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1568]
Hello, i want to know if 90% usage of CPU is normal for TFS process?

I have a server with 600+ players online and i saw with htop the TFS process using constant 90% of cpu.

i don't have lag in-game at moment, i'm using the last tfs 1.1 from github.

look this image: http://s9.postimg.org/kz6auqv3j/highcpu.png

this is normal? thanks.

**Comment by gesior** [comment]
You got 2 TFSes running or 1 running and you show threads?
It does not look normal, if it's 1 TFS. 90% of 1 core for 'game thread' is possible on medium class dedic, but 50% for second core (is it 'network thread'?) is not normal - looks like some hacker attack.

Check how many mb/s uses your server.

I think that better place for this kind of question is:
https://otland.net/forums/support.16/
and report, when you confirm, that it's some kind of BUG.

**Comment by gesior** [comment]
Your 'defense' problem is here:
https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L440

    
    int32_t Player::getDefense() const
    {
    	int32_t baseDefense = 5;
    	int32_t defenseValue = 0;
    	int32_t defenseSkill = 0;
    	int32_t extraDefense = 0;
    	float defenseFactor = getDefenseFactor();
    	const Item* weapon;
    	const Item* shield;
    	getShieldAndWeapon(shield, weapon);
    
    	if (weapon) {
    		defenseValue = baseDefense + weapon->getDefense();
    		extraDefense = weapon->getExtraDefense();
    		defenseSkill = getWeaponSkill(weapon);
    	}
    
    	if (shield && shield->getDefense() >= defenseValue) {
    		defenseValue = baseDefense + shield->getDefense() + extraDefense;
    		defenseSkill = getSkillLevel(SKILL_SHIELD);
    	}
    
    	if (defenseSkill == 0) {
    		return 0;
    	}
    
    	defenseValue = static_cast<int32_t>(defenseValue * vocation->defenseMultiplier);
    	return static_cast<int32_t>(std::ceil((static_cast<float>(defenseSkill * (defenseValue * 0.015)) + (defenseValue * 0.1)) * defenseFactor));
    }
    
defenseValue is 0, but:
**if (weapon) {** // player got weapon
**defenseValue = baseDefense + weapon->getDefense();**

defenseValue = **baseDefense** + weapon->getDefense();

**baseDefense** is 5, so when you wear ANY weapon or ANY shield, it increase your defense by 5.
Plus.. it uses 'distance' (for assassin stars) as your 'defense' skill, not 'shielding', so paladin with weak shield uses 'assassin star' to block hits + uses his 'distance skill' (high), not 'shielding' (low).

**Comment by marksamman** [comment]
Please provide a perf report, until then we can't know if anything is actually wrong, it could be normal.
