### ISSUE TITLE
internal compiler error: Segmentation fault (program cc1plus)

### ISSUE THREAD

**Issue by olszak94** [otland/forgottenserver#1569]
Followed every step as listed in [here](https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu).

I have plenty of ram (32GB), below you can see every step and error that occured.

[![asciicast](https://asciinema.org/a/604eoc1lvgtis97oq3hylg0t5.png)](https://asciinema.org/a/604eoc1lvgtis97oq3hylg0t5)

**Comment by marksamman** [comment]
#1325
#1400
#1404

Still waiting for someone to submit a bug report to GCC, however if you don't want to submit a bug report to GCC, you can just disable cotire and it should compile fine.
