### ISSUE TITLE
GetPlayerInfo by socket

### ISSUE THREAD

**Issue by elpmoraes** [otland/forgottenserver#1573]
Hello!

I know that we get server info by socket:
$info = chr(6).chr(0).chr(255).chr(255).'info';

But how to get player info ?
As describe protocolstatus.cpp:

case 0x01: {
            uint16_t requestedInfo = msg.get<uint16_t>(); // only a Byte is necessary, though we could add new info here
            std::string characterName;
            if (requestedInfo & REQUEST_PLAYER_STATUS_INFO) {
                characterName = msg.getString();
            }
            g_dispatcher.addTask(createTask(std::bind(&ProtocolStatus::sendInfo, std::static_pointer_cast<ProtocolStatus>(shared_from_this()),
                                  requestedInfo, characterName)));
            return;
        }

**Comment by diath** [comment]
You need to send 1 instead of 255, then 64 encoded as two bytes instead of 'info', then the player's name (prefixed by the length of the player name encoded as two bytes as well).

**Comment by elpmoraes** [comment]
Is that right ?
chr(6).chr(0).chr(1).chr(64).chr(64).chr(10).chr(10).'playername';
