### ISSUE TITLE
Server CRASH

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1574]
Hello, its a bug from TFS?

Crash log:
http://hastebin.com/yafeyoyeha.xml

**Comment by ranisalt** [comment]
No, it seems to be a GDB bug. It's not finding a required package, try reinstalling it.

**Comment by kanohn** [comment]
Well, my server get crash today 2-3 times..

I did it from my restart:
ulimit -c unlimited
while true; do ./tfs; done

And got a core file, i just did:
gdb tfs core

and got this log above.

What i need to do? i just did apt-get install gdb before this steps.

**Comment by ranisalt** [comment]
Which GDB are you using? It seems to be an issue with the packaged version for Ubuntu 14.04, as is stated [here](http://askubuntu.com/questions/345873/gdb-crashes-with-importerror-no-module-named-libstdcxx-v6-printers), but if you have the ubuntu-toolchain-r PPA, update your GDB and try again.

**Comment by marksamman** [comment]
Include the full backtrace from each crash.
