### ISSUE TITLE
Tfs 1.1 compiling error

### ISSUE THREAD

**Issue by dicemangs** [otland/forgottenserver#1575]
![screenshot_1](https://cloud.githubusercontent.com/assets/14906912/10193355/8dfb8cdc-6750-11e5-93ad-f4fb9e01761d.png)

I dont know what need to be done if you can help me please and thank you

**Comment by EvulMastah** [comment]
https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows#2-install-the-required-software
