### ISSUE TITLE
Move with ghostmode.

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1577]
I walk into a fire/energy/etc and appers this:
http://1.1m.yt/oDgPjzcR-.png

I didn't know where to remove that, and I guess it's in C++ or flags.

Thanks.

**Comment by brunominervino** [comment]
I'm using latest version of TFS 1.2 and it does not.

**Comment by vankk** [comment]
hmm, I already tryed everything, but are getting all effects with ghostmode and the players can see it, do you have any idea how I fix that? using 1.0. @brunominervino

**Comment by raymondtfr** [comment]
Try this and see if it works.

In game.cpp (line 4060) find this:
```c++
		if (!target->isAttackable() || Combat::canDoCombat(attacker, target) != RETURNVALUE_NOERROR) {
			addMagicEffect(list, targetPos, CONST_ME_POFF);
			return true;
		}
```
Change it to:
```c++
		if (!target->isAttackable() || Combat::canDoCombat(attacker, target) != RETURNVALUE_NOERROR) {
			if (!target->isInGhostMode()) {
				addMagicEffect(targetPos, CONST_ME_POFF);
			}
			return true;
		}
```

**Comment by vankk** [comment]
Already have this code in my game.cpp at line 3868 o.o

**Comment by raymondtfr** [comment]
Oh my bad xD, I mean in line **Game::combatChangeHealth** at line 3968.

**Comment by vankk** [comment]
Keep getting effects in the administrador with flags: 272730398714

**Comment by imranhhk** [comment]
Is it possible that you have movement script that is causing this puff?

For example, you can check the script for Fire Walker Boots and see if the problem is there.

**Comment by vankk** [comment]
I forgot to comment on this issue, sorry for that.

The problem that I reported in Setember was been fixed with @raymondtfr code, but I found another bug on move with ghostmode (godmode), the gif below is self-explanatory, but I'll explain.. When you're in ghostmode keep returning the effects and also returns _talktype_monster_say_.

![](https://cloud.githubusercontent.com/assets/14372849/13618432/da47a7d4-e562-11e5-827c-a254f4dbd3b0.gif)

**Comment by BenDol** [comment]
Shouldn't this be handled by the script you wrote? Since its adding the magic effect and text without any context to the player.

**Comment by vankk** [comment]
Oh, I did not know about that, I thought it was the same of TFS 0.4, that forces the function to not send magicEffect if you're in ghostmode.

**Comment by wgrrifel** [comment]
@vankk I think you should re-open, this could be a enchant, imo.

**Comment by vankk** [comment]
Lets @marksamman  judge it.

**Comment by BenDol** [comment]
Its can't be improved unless the script is written with the player in context, simply doing `position:sendMagicEffect(magicEffect)` doesn't know if the player is in ghost mode since it has nothing to do with the player. Perhaps player:sendMagicEffect(magicEffect) could be a good solution for it.

**Comment by vankk** [comment]
Mark, what do you think about this issue?

**Comment by vankk** [comment]
I'll re-open this issue @marksamman what do you think?
I'll give a shoot to try make this enchant..
