### ISSUE TITLE
possible Condition bug

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1580]
I'm not too sure how conditions should work, but I think its a bit buggy, I have solved this problem for myself few days ago making a function what registrates all conditions with sub id my game has on start up, but maybe you want make it easier for new users and let them make functions like that below.

attributes = Condition(ATTRIBUTES)
function Player:addMaxMana(amount, duration, ID)
    attributes:setParameter(SUBID, ID)
    attributes:setParameter(MAXMANAPOINTS, amount)
    attributes:setTicks(duration)
    self:addCondition(attributes)
end

This parameter to set sub id is pretty useless in this case. If player dies or logs off the condition will stay. 
On top of it the condition will disappear, but the effect remains. I think its bug, but who knows.

**Comment by brunominervino** [comment]
I have problem with Conditions too.
The players are complaining about exhausted in the potions.
Look:
```lua
local exhaust = Condition(CONDITION_EXHAUST_HEAL)
exhaust:setTicks(1000)
```
Sometimes it works, but it does not go through this validation:
```lua
	if player:getCondition(CONDITION_EXHAUST_HEAL) then
		player:sendTextMessage(MESSAGE_STATUS_SMALL, 'You cannot use objects that that fast.')
		return true
	end
```

When this validation works, the exhausted is 4000ms and not 1000ms like I set.

**Comment by whitevo** [comment]
give sub id to to the condition when making conditions right now. Maybe this weird issue will be solved in future

How the heck did you make a code line :/

local exhaust = Condition(CONDITION_EXHAUST_HEAL, 1)
exhaust:setTicks(1000)

if player:getCondition(CONDITION_EXHAUST_HEAL, 1) then
        player:sendTextMessage(MESSAGE_STATUS_SMALL, 'You cannot use objects that fast.')
        return true
    end

**Comment by brunominervino** [comment]
@whitevo I will try, thank you.

**Comment by brunominervino** [comment]
@whitevo same problem with subid...

To use code syntax here, look: https://guides.github.com/features/mastering-markdown/#examples

**Comment by whitevo** [comment]
how do you add that condition to player?
(btw I suggest just to use storage values to mess with cooldowns)

**Comment by brunominervino** [comment]
Yes, I'm using storages momentarily.
So many players died by potion exhausted.

**Comment by whitevo** [comment]
Just coming back to this, because I just went trough another item refactoring and bindCondition function popped up again.

I have now realized why "sub id" doesn't work.
It wasn't the sub id problem at all.
I just missunderstood what does second parameter means. Condition(ATTRIBUTES, number)
The number is not SUB ID what I though so far for like 10 months now until today xD
it is ID of condition.
Explains alot :D

Well that is that. No buggerinos just missunderstanding, you can move this to solved.
