### ISSUE TITLE
Attack spell/rune causes negative (and positive) damage in creatures

### ISSUE THREAD

**Issue by raymondtfr** [otland/forgottenserver#1587]
If there are two creatures (or player) around you, if you reduce these creature's HP twice (to ease the observation) and use any attack spell/rune, you'll see that in one of the creatures the spell will deal "negative" damage, and will also deal damage on the other creature (as expected), but it'll deal a "positive" damage (the same damage value as the other creature that got a negative damage), that is, one of the creatures gets healed.
You can only reproduce this if there a minimum of 2 creatures around you.
![screen shot 10-10-15 at 02 05 am](https://cloud.githubusercontent.com/assets/6445979/10409363/462797c8-6ed2-11e5-8654-41e128489098.PNG)
My guess is that this came with #1548 .

**Comment by brunominervino** [comment]
After this last commit, sometimes the attacks did not affect creatures and it does not work in area.

![bug](https://cloud.githubusercontent.com/assets/10432401/10411607/9a0daed0-6f41-11e5-8d21-dbf9e2969f1b.png)

**Comment by marksamman** [comment]
Can you confirm that #1589 fixes this?

**Comment by raymondtfr** [comment]
I have just tested it, and yes, it does!
