### ISSUE TITLE
Migration And Vocation Error

### ISSUE THREAD

**Issue by krypton9208** [otland/forgottenserver#1590]
Ubuntu 15.04 cmake and make without errors....

![zrzut ekranu 2015-10-12 22 37 09](https://cloud.githubusercontent.com/assets/6137589/10438134/04cb8a8e-7132-11e5-900c-2f2f19b94a0e.png)

**Comment by marksamman** [comment]
You should run tfs from build's parent directory (move tfs up and run it from there).
