### ISSUE TITLE
Game.createContainer(itemID, size, pos) is not working.

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1592]
Like the title says, it doesn't work for TFS 1.1.x (i don't use latest though.)

**Comment by ninjalulz** [comment]
What are you trying to do?

**Comment by whitevo** [comment]
Wanted to create container. with the size I chose it to be and then take that item and put it where I need:
in player bag, slot or depot, etc.

**Comment by ninjalulz** [comment]
I see. Unfortunately, you cannot create an item as a container unless it passes these conditions. See [item.cpp#L94](https://github.com/otland/forgottenserver/blob/master/src/item.cpp#L94)

**Comment by HeavenIsLost** [comment]
Use this code from orts system.lua:

http://hastebin.com/uwarexitup.coffee

You create the container, insert the items inside, then you can add it to the player, to the tile, depot, inbox, etc...

**Comment by whitevo** [comment]
sadly this wont help me, I need custom sizes
