### ISSUE TITLE
Compilling error

### ISSUE THREAD

**Issue by HyphenMaster** [otland/forgottenserver#1595]
Hi,

when i trying compiling latest source code I getting some error

Error	108	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\weapons.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	106	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\waitlist.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	104	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\vocation.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	100	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\trashholder.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	102	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\tile.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	98	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\thing.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	96	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\teleport.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	94	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\tasks.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	90	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\talkaction.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	88	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\spells.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	84	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\spawn.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	86	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\scriptmanager.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	82	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\raids.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	74	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\quests.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	92	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\protocolstatus.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	78	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\protocolold.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	76	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\protocollogin.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	80	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\protocolgame.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	69	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\player.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	67	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\party.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	65	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\otserv.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	63	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\npc.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	61	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\networkmessage.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	59	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\movement.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	57	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\monsters.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	55	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\monster.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	47	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\map.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	45	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\mailbox.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	51	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\luascript.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	41	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\items.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	43	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\item.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	53	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\iomarket.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	49	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\iomapserialize.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	39	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\iomap.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	37	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\iologindata.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	29	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\inbox.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	25	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\housetile.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	35	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\house.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	27	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\guild.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	31	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\game.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	33	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\events.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	23	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\depotlocker.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	21	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\depotchest.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	19	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\creatureevent.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	17	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\creature.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	15	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\container.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	13	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\configmanager.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	5	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\condition.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	7	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\commands.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	3	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\combat.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	11	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\chat.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	1	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\bed.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	9	error C2610: 'ItemType::ItemType(ItemType &&)' : is not a special member function which can be defaulted (..\src\actions.cpp)	d:\otserver\src\items.h	122	1	theforgottenserver
Error	109	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\weapons.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	107	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\waitlist.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	105	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\vocation.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	101	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\trashholder.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	103	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\tile.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	99	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\thing.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	97	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\teleport.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	95	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\tasks.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	91	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\talkaction.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	89	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\spells.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	85	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\spawn.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	87	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\scriptmanager.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	83	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\raids.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	75	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\quests.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	93	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\protocolstatus.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	79	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\protocolold.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	77	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\protocollogin.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	81	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\protocolgame.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	70	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\player.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	68	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\party.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	66	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\otserv.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	64	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\npc.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	62	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\networkmessage.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	60	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\movement.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	58	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\monsters.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	56	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\monster.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	48	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\map.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	46	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\mailbox.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	52	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\luascript.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	42	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\items.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	44	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\item.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	54	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\iomarket.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	50	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\iomapserialize.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	40	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\iomap.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	38	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\iologindata.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	30	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\inbox.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	26	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\housetile.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	36	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\house.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	28	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\guild.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	32	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\game.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	34	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\events.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	24	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\depotlocker.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	22	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\depotchest.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	20	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\creatureevent.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	18	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\creature.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	16	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\container.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	14	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\configmanager.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	6	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\condition.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	8	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\commands.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	4	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\combat.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	12	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\chat.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	2	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\bed.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver
Error	10	error C2610: 'ItemType &ItemType::operator =(ItemType &&)' : is not a special member function which can be defaulted (..\src\actions.cpp)	d:\otserver\src\items.h	123	1	theforgottenserver

**Comment by marksamman** [comment]
#1557
