### ISSUE TITLE
Async queries for some cases

### ISSUE THREAD

**Issue by gunzino** [otland/forgottenserver#1597]
Hello,

I would like to ask, if it's safe to change all the INSERT,UPDATE queries to use the new db thread in TFS1.2 to make it async, specially iologindata.cpp. The saves would be without the lag then.

Can it affect something in the game ? Or there should be added some feature for locking some tables during async queries ? (would became half-async)

Thank you for answer.

**Comment by marksamman** [comment]
No, it's not safe, but it can be made safe with a lot of work. See my comments in #835 to get an idea of it.
