### ISSUE TITLE
Difference between Scheduler and Dispatcher ?

### ISSUE THREAD

**Issue by gunzino** [otland/forgottenserver#1598]
Hello,

Sorry for bothering, I am just developing some new features for TFS and I wonder if it's there some difference between using g_dispatcher and g_scheduler. Are they two separate threads ? The difference is only that scheduler does tasks after some delay ?

I am connecting to Redis NoSQL databse from TFS. I want to parse the callbacks from Redis in TFS and wondering if they should be handled with scheduler or dispatcher or it does not matter.

**Comment by marksamman** [comment]
Scheduler tasks are processed by the Dispatcher so it doesn't matter.
