### ISSUE TITLE
Spell CALLABACK_PARAM Bug or is it intend?

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1599]
Hello, i wonder if this is a bug or intend? Since i feel it is annoying to copy same code. Due to you cannot use the same one without getting a error:
https://otland.net/threads/help-with-the-spell-tfs-1-2.237626/#post-2296476

[Warning - CallBack::loadCallBack] Event onGetFormulaValues not found.
[Warning - CallBack::loadCallBack] Event onTargetCreature not found.
[Warning - CallBack::loadCallBack] Event onGetFormulaValues not found.
[Warning - CallBack::loadCallBack] Event onTargetCreature not found.
[Warning - CallBack::loadCallBack] Event onGetFormulaValues not found.
[Warning - CallBack::loadCallBack] Event onTargetCreature not found.
[Warning - CallBack::loadCallBack] Event onGetFormulaValues not found.
[Warning - CallBack::loadCallBack] Event onTargetCreature not found.
[Warning - CallBack::loadCallBack] Event onGetFormulaValues not found.
[Warning - CallBack::loadCallBack] Event onTargetCreature not found.

**Comment by whitevo** [comment]
That is weird.
It shouldn't be problem to have same function.
You might want to make the function into local function though.
and put print("test") inside the onGetFormulaValues(). To see how many times it executes the function.

**Comment by PrinterLUA** [comment]
You cannot make it local aswell, it does not find the function then.
