### ISSUE TITLE
Duration of spells fields on game

### ISSUE THREAD

**Issue by fironfox** [otland/forgottenserver#1604]
My spells field ex:(fire field, poison field, magic wall...) are leaving in a wrong time. In my spells.xml, items.xml and .lua files, the time are correclty, 20 sec for mwall and other times for the other spells, but when the server get 250 more players online or uptime > 5 hours, the fields timer start to increase seconds to leave and some times getting 5 seconds of delay. i run the original theforgottenserver 1.0 code of this repository, but, have minor modifies and fixes what i have taked from here. Its possible is an overload of tfs or something like this? I have read one topic in otland of tfs 1.2 + tunning:
 
https://otland.net/threads/tfs-1-2-performance-tuning.235648/ 

But i don't know if this works and if the tfs 1.0 support this. My machine have a good config, with 32 gb of ram and xeon E5 running with HD. (sorry for bad english)

edit: My CPU usage of tfs don't get more than 10%

**Comment by ninjalulz** [comment]
Ran a couple of tests on a server that uses TFS 1.2 , has more players & uptime, and I were unable to detect any delays by using a timer.
