### ISSUE TITLE
DistanceWeapons bug

### ISSUE THREAD

**Issue by marcelobcortes** [otland/forgottenserver#1605]
hello!

all distance weapons stops shooting when using a potion
if it isnt a bug, please help me to disable this feature

**Comment by Tarliton** [comment]
It's not a bug, ask the forum for help

**Comment by mattyx14** [comment]
@up no are solution ... swing work on old versions from tfs 0.3 series ... this option no are added on tfs 1.x

**Comment by vankk** [comment]
I can confirm this issue Mark, seems swing has not added on tfs 1.x

**Comment by wgrriffel** [comment]
@marksamman I confirm as well, what i say here related to internal items exhaustion, it happens with any item on any condiction, you can just use too fast any item then bolt/arrow/spear will be not used, the same not affect knights and mages attacks.

**Comment by EPuncker** [comment]
swing has not been added, but classic attack speed fixes this:
https://github.com/otland/forgottenserver/commit/24a27e10de5bb476b979ad7e6bf95c53bdaad6d6
