### ISSUE TITLE
Arch Linux Package

### ISSUE THREAD

**Issue by LaloHao** [otland/forgottenserver#1607]
Not really an issue. I added a pkg to AUR to compile tfs

https://aur.archlinux.org/packages/forgottenserver-git/

or `yaourt -S forgottenserver-git`

https://otland.net/threads/compiling-latest-tfs-on-arch-linux.237762/

I was trying to add it to wiki but i couldn't find edit button
Cheers

**Comment by ranisalt** [comment]
May I ask why? PKGBUILDs are meant to install software, but yours does not install anything. Not that I find it useless, it could be used as a guide on how to build TFS, but it does not fit the purposes of a package.

Also, if one wants to edit the source, it would not be possible, and you throw data in /tmp which is volatile and will be destroyed upon reboot.

At last, your build phase is completely wrong. You should not ever hardcode paths or force to build on another directory than the one yaourt/pacaur/whatever is configured to.

**Comment by LaloHao** [comment]
I realize it doesn't install anything, i wouldn't want it overwriting the server files, thats why i tried to do it on /tmp/ so it can be moved elsewhere after compiling

The fun part which is why i mostly did it is so it can be cross-compiled to a Raspberry Pi using distcc
https://otland.net/threads/cross-compiling-latest-tfs-for-raspberry-pi.237783/

It is my first PKG so it's not really that great, how would you suggest it be done?

**Comment by ranisalt** [comment]
I suggest you do not have a package at all. Packages are meant to install.

It would be nice if TFS had support to have configuration and data files on different folders (say /etc/tfs/config.lua and /srv/tfs/data), then a package would be nice to install start/stop scripts and base files.

**Comment by LaloHao** [comment]
Makepkg already has everything needed for distributed compiling. It was the easiest method for compiling on the Raspberry since it failed at about 40% because of the lack of RAM. 

I'm thinking that splitting tfs on several folders seems easy, or am i missing something?
