### ISSUE TITLE
onUse() bug

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1609]
If item is in same position with ladder, none of the items will work.

**Comment by beastn** [comment]
This isn't a bug. You have edited your OTB with the wrong version of item editor. If you haven't edited your OTB then you need to use the official release =)

**Comment by PrinterLUA** [comment]
You have made changes, that cause this problem. If items are blocking a ladder, then the ladder should work. Atleast what it is doing on my server.

**Comment by whitevo** [comment]
hmm ok, I have idd edited my levers. So that they can't be stepped on.
I will consider making a script to push player back from lever instead of editing OTB then.
