### ISSUE TITLE
Setting interval (in monsters *.xml files) to 0 (zero) crashes the server

### ISSUE THREAD

**Issue by raymondtfr** [otland/forgottenserver#1611]
In **monster files**, this piece of code:
```xml
	<summons maxSummons="2">
		<summon name="War Wolf" interval="0" chance="50" />
	</summons>
```
will *crash* the server **(when it tries to summon up a creature)** if, and **only if** the ``interval`` is set to **0** *(zero)*. I don't know if that's what it is intended to happen, because 0 is an undefined value to set an interval *(I guess those variables should be initialized to a set of default values)*, but shouldn't we handle it properly *by not letting the server crash* *(additionaly a notifying message in console)*?

**Comment by conde2** [comment]
Tested and I can confirm this

**Comment by socket2810** [comment]
You could simply not let the interval be zero, like this:
````C++
if ((attr = summonNode.attribute("speed")) || (attr = summonNode.attribute("interval"))) {
	speed = pugi::cast<int32_t>(attr.value());
	// If attribute value is zero then use default. Maybe send a console warning?
	if (!speed) {
		speed = 1000;
	} 
}
````

**Comment by ranisalt** [comment]
I think the solution by @socket2810 creates additional unwanted behavior. If someone sets an invalid value anywhere, the server should not start at all warning that an invalid value was set and where, not forcing another value causing the server to act differently from what it was configured to.

Indeed this is exactly where this warning should be printed.

**Comment by djarek** [comment]
I agree with @ranisalt - invalid configuration loading should cause a starting server to fail to load and print an appropriate error message. We should also try to somehow gracefully handle the situation when the user tries to reload the config with the invalid value while the server is already running.

**Comment by socket2810** [comment]
That might be a better way to handle invalid configuration but it diverges from the way it's currently done with the hundreds of warnings (and default values) we have in place at the moment.

**Comment by ranisalt** [comment]
Configuration reload could be transaction-like, where failing to reload something cancels the entire reloading without applying.

**Comment by ranisalt** [comment]
While I'm at it, what are the other possible invalid values to be set?

Negative speed values, max health under now health (or the other hand), non-positive target distance, negative run on health, negative target change chance, outfit colors outsite the color "spectrum", negative defense and armor, non-positive voice/summon interval... what else?

**Comment by raymondtfr** [comment]
I  guess that it was just the tip of the iceberg.
The server will crash all these occasions (using Tibia client):
* ``experience="x"`` (x < 0) -- obviously, the client will crash if you kill the creature (you'll still be able to log in your character without crashing again).
* ``look type="x"`` (x <= 0) -- you won't be able to log in again (client will crash).
* ``health now="x" max="x"`` -- **x** can be less than or equal to 0 (creature will die right after created).

**Comment by ranisalt** [comment]
> health now="x" max="x" -- x can be less than or equal to 0 (creature will die right after created).

I think this is not an error but rather a user's fault, but it could indeed be warned on the console.

**Comment by Kamenuvol** [comment]
The crash is already solved, but we really need to parse the things better.
