### ISSUE TITLE
math.random on startup

### ISSUE THREAD

**Issue by kevinyst** [otland/forgottenserver#1614]
local x = math.random(5)
print(x)
when i put this in onStartup() (globalevents/startup.lua), always results 3.
when i put "math.random(10)", always results 6.
this is a bug?

**Comment by djarek** [comment]
Have you tried setting the seed before using math.random()?
```
math.randomseed(os.time())
```

**Comment by kevinyst** [comment]
it worked, thanks!

**Comment by diegorodriguesvieira** [comment]
Only one doubt, what is the purpose of this random?
Thank you =)

**Comment by Tarliton** [comment]
Every time you start the server the random seed would be different so the random numbers aren't always the same. That's what happens when you choose time as the random seed. It's for increasing unpredictability.

**Comment by diegorodriguesvieira** [comment]
Thank you @Tarliton =)
