### ISSUE TITLE
Variant only for Players?

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1615]
Hello,

well i have noticed, that when a monster shoot a custom spell which include variant. It does not retrive the variant.

It does not teleport to target position. If i do local position = creature:getTarget():getPosition() - That will work.

http://pastebin.com/BVHBStqF

**Comment by conde2** [comment]
Please try debugging the variant

function onCastSpell(creature, variant)
    for k,v in pairs(variant) do
        print(k,v)
    end
end

show the results
You should probably use variant.pos

**Comment by TheSumm** [comment]
Both castSpell function calls in monsters.cpp call this [one](https://github.com/otland/forgottenserver/blob/26f3e3731915fe5e2984d4b997f82d10769f205c/src/spells.cpp#L315-L347), not the one at [line 289](https://github.com/otland/forgottenserver/blob/26f3e3731915fe5e2984d4b997f82d10769f205c/src/spells.cpp#L289).

Looking at your spell it does not seem to have an area attached to it, that is why the type of variant will be number (see [here](https://github.com/otland/forgottenserver/blob/26f3e3731915fe5e2984d4b997f82d10769f205c/src/spells.cpp#L331-L332)). Use ```variant:getNumber()``` instead to retrieve the target creature.
