### ISSUE TITLE
player:addItem always return true when count is higher than 1

### ISSUE THREAD

**Issue by ColorsCL** [otland/forgottenserver#1616]
Well the title says it all, I don't know if this is a bug or is intended. 
Example below is with a character with no cap or no free slots.

```lua
if player:addItem(2160, 1, false) then --returns false
end

if player:addItem(2160, 5, false) then --returns true
end
```

**Comment by ninjalulz** [comment]
I think it's the intended behavior. When the count is higher than 1, it creates a table, and is either empty or contains userdata objects if the items are created.

**Comment by TheSumm** [comment]
```
local ret = player:addItem(2160, 5, false)
if type(ret) == "table" and #ret > 0 or type(ret) == "metadata" then
  -- do stuff
end
```

**Comment by ColorsCL** [comment]
I couldn't do what I had in mind, but I guess that this can be closed now.
Thanks for all the help :)
