### ISSUE TITLE
Being able to eat more food than intended

### ISSUE THREAD

**Issue by peonso** [otland/forgottenserver#1618]
https://github.com/otland/forgottenserver/blob/26f3e3731915fe5e2984d4b997f82d10769f205c/data/actions/scripts/other/food.lua#L108

should be

    if condition and math.floor(condition:getTicks() / 1000 + food[1] * 12) >= 1200 then

**Comment by marksamman** [comment]
Fixed in 215ddf4dc9be0b9c29c7276a5aecbba110e93d0f.
