### ISSUE TITLE
ItemEx suggestion

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1619]
An error what is easy to bypass but still makes me wonder why its there is first place?
If you use item what doesn't have option to use it on another item the itemEx turn into table with values:
type = 0
stack = 0
id = 0
or something like that.

Maybe it could return nil instead? saves us the problem writing: 
if itemEx and not type(itemEx) ~= "userdata" then end

**Comment by ranisalt** [comment]
Am I seeing a double negation?

**Comment by whitevo** [comment]
what do you mean by that xD?

**Comment by marksamman** [comment]
Because of backwards compatibility.
