### ISSUE TITLE
[FIXED] Bug with pvp zone

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1622]
Seems PvP Zone is bugged at last TFS. When you attack a player at pvp zone you get pz locked (http://2.1m.yt/rO0BHKBl.png). Normally pvp zone doesn't get pz locked, only battle.

Any fix for this? Thanks.

**Comment by vankk** [comment]
Fixed by Slavi Doido!

on **player.cpp** seach for:
```
void Player::onAttackedCreature(Creature* target)
{
    Creature::onAttackedCreature(target);
```
and **add above** it:
```
// Fix avoid pz in pvp zones.
    if (target && target->getZone() == ZONE_PVP) {
        return;
    }
```

**Comment by ranisalt** [comment]
I think you mean below, not above

**Comment by vankk** [comment]
Oh, sorry. Done, fixed.

**Comment by slavidodo** [comment]
Corret my name please, Slavi Dodo.

**Comment by vankk** [comment]
@marksamman 
Check the momments, this issue was already been fixed.

**Comment by marksamman** [comment]
The issue tracker is for this source code hosted in this repository and not for a local copy that you have on your computer. As long as the issue affects the source code in this repository, the issue remains open. I'm aware that there is a proposed solution among the comments, but it has not been submitted as a pull request, and I have not reviewed it.
