### ISSUE TITLE
Ladder dont work with fresh corpse

### ISSUE THREAD

**Issue by thexamx** [otland/forgottenserver#1624]
Hello, when i use ladder immadetiately after killing monsters, when its fresh with tile of blood.  I cant use ladder by right clicking it..
Corpse (not movable)
But when i use it after the corpse delay to movable then its working even with blood.

Summary:
Non movable corpse its not working with ladder when monster die on ladder.

Its making corpse lay above the ladder.

Tested on clean source.

**Comment by thexamx** [comment]
Same with hole. If any type of splash/blood is on hole you cant open it.
![](https://i.gyazo.com/cf6fcba3e1104e53063ff11c7cac75e5.png)

**Comment by marksamman** [comment]
Please open a new issue for that.
