### ISSUE TITLE
Cannot create a GOD har

### ISSUE THREAD

**Issue by toxicbyte** [otland/forgottenserver#1626]
Have tried setting MySQL DB account to type 5, player group_id to 3 (god according to my groups.xml), changed the flags of the groups.xml, etc. And still nothing

**Comment by mattyx14** [comment]
I check on enums.h
```
enum AccountType_t : uint8_t {
	ACCOUNT_TYPE_NORMAL = 1,
	ACCOUNT_TYPE_TUTOR = 2,
	ACCOUNT_TYPE_SENIORTUTOR = 3,
	ACCOUNT_TYPE_GAMEMASTER = 4,
	ACCOUNT_TYPE_GOD = 5
};
```

**Comment by conde2** [comment]
Using latest sources here, have no problem with creating GOD !
