### ISSUE TITLE
CRASH REPORT HELP

### ISSUE THREAD

**Issue by Healek** [otland/forgottenserver#1629]
Hello friends, my server get crash all day and i need to fix it :(
TFS 1.1
GDB GIVE ME THIS ERROR:
BT FULL
#0 0x000000000086c07e in Creature::getDirection() const ()
No symbol table info available.
#1 0x00000000009d8de5 in ProtocolGame::sendCancelWalk() ()
No symbol table info available.
#2 0x0000000000a22fd5 in _ZNKSt7_Mem_fnIM12ProtocolGameFvvEE7_M_callIRP17ProtocolSpectatorJEEEvOT_PVKvDpOT0_ ()
No symbol table info available.
#3 0x0000000000a22e92 in _ZNKSt7_Mem_fnIM12ProtocolGameFvvEEclIRP17ProtocolSpectatorJEvEEvOT_DpOT0_ ()
No symbol table info available.
#4 0x0000000000a22ac2 in _ZNSt5_BindIFSt7_Mem_fnIM12ProtocolGameFvvEEP17ProtocolSpectatorEE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
()
No symbol table info available.
#5 0x0000000000a223fc in _ZNSt5_BindIFSt7_Mem_fnIM12ProtocolGameFvvEEP17ProtocolSpectatorEEclIJEvEET0_DpOT_ ()
No symbol table info available.
#6 0x0000000000a214d7 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (ProtocolGame::*)()> (ProtocolSpectator*)> >::_M_invoke(std::_Any_data const&) ()
No symbol table info available.
#7 0x0000000000a4a9f6 in std::function<void ()>::eek:perator()() const ()
No symbol table info available.

**Comment by Healek** [comment]
why you close this thread? i need help to fix it..

**Comment by marksamman** [comment]
This is not a support forum.

**Comment by Healek** [comment]
ok, thank you =)
