### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Bielzinero** [otland/forgottenserver#1630]
Using TFS 0.3.6pl1

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x73b235e2a700 (LWP 28914)]
Game::combatChangeHealth (this=0x8829c0 <g_game>,
    combatType=combatType@entry=COMBAT_FIREDAMAGE, attacker=attacker@entry=
    0x0, target=target@entry=0x0, healthChange=healthChange@entry=-1,
    hitEffect=hitEffect@entry=MAGIC_EFFECT_UNKNOWN,
    hitColor=TEXTCOLOR_UNKNOWN, force=false) at game.cpp:4177
4177    game.cpp: No such file or directory.

**Comment by Bielzinero** [comment]
Why did you close my issue?

**Comment by marksamman** [comment]
This repository is not for TFS 0.3. There isn't any repository for TFS 0.3, you're on your own for using obsolete software.
