### ISSUE TITLE
Splash/Blood on Hole

### ISSUE THREAD

**Issue by thexamx** [otland/forgottenserver#1631]
If any type of splash/blood is on hole you cant open it.
On picture we clearly see that blood is above hole.

![](https://i.gyazo.com/9054923909632063c5d461fd70ea4e97.png)

**Comment by thexamx** [comment]
any news?

**Comment by kanohn** [comment]
this also happens with picks

**Comment by ranisalt** [comment]
This was already fixed.

**Comment by kanohn** [comment]
@ranisalt, you are talking that it has been fixed in this commit, or what commit?
