### ISSUE TITLE
Server Crash with gdb log

### ISSUE THREAD

**Issue by Healek** [otland/forgottenserver#1637]
I'm still using the last rev from forgottenserver (1.2) FULL.
Sometimes my server is getting crashed, i try to find this error.
BT FULL:

#1  0x00000000008128a5 in Container::hasParent() const ()
No symbol table info available.
#2  0x0000000000845b2d in Game::playerMoveUpContainer(unsigned int, unsigned char) ()
No symbol table info available.
#3  0x00000000009f30ea in _ZNKSt7_Mem_fnIM4GameFvjhEEclIJRjRhEvEEvPS0_DpOT_ ()
No symbol table info available.
#4  0x00000000009efc58 in _ZNSt5_BindIFSt7_Mem_fnIM4GameFvjhEEPS1_jhEE6__callIvJEJLm0ELm1ELm2EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE ()
No symbol table info available.
#5  0x00000000009eb902 in _ZNSt5_BindIFSt7_Mem_fnIM4GameFvjhEEPS1_jhEEclIJEvEET0_DpOT_ ()
No symbol table info available.
#6  0x00000000009e2460 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, unsigned char)> (Game*, unsigned int, unsigned char)> >::_M_invoke(std::_Any_data const&) ()
No symbol table info available.
#7  0x0000000000a254e6 in std::function<void ()>::operator()() const ()
No symbol table info available.
#8  0x0000000000a253d0 in Task::operator()() ()

FRAME 1:
#1  0x00000000008128a5 in Container::hasParent() const ()

**Comment by marksamman** [comment]
Compile with -O0 and -g and provide a new stacktrace.

**Comment by Healek** [comment]
ok, i will try.
