### ISSUE TITLE
tile:getTopCreature() sometimes does return nil for tiles with creature

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#1638]
A strange behavior is happening with tile:getTopCreature()
I'm using it with addEvent and sometimes it does not return the creature in the tile, and yes the creature is there and the tile / position is correct.

This is just part of the script

http://pastebin.com/xv0PVKkF

**Comment by TheSumm** [comment]
Not sure if that is related to / causing the issue, but ```getNextPosition``` does not return any value, it just modifies position passed as the parameter.

**Comment by conde2** [comment]
That was just an example, can you use this code example (with this little fix ) and see if you can reproduce this behaviour ?

It happens sometimes, but try 10 to 20 times and it should happen!

**Comment by PrinterLUA** [comment]
By passing pos on the addEvent, it changes the position 1 step ahead. Pass fromPos instead.

**Comment by conde2** [comment]
It may be because the creature is moving and when calling the function the creature is no longer in the position checked.
