### ISSUE TITLE
bug with internal remove item

### ISSUE THREAD

**Issue by Schiffers** [otland/forgottenserver#1639]
when I try use it
if (size() == 0) {
	g_game.internalRemoveItem(this);
}
got a crash, I'll explain better...
when I create the item that is to be removed when empty, and send it inside the depot, if I do not logout and remove items from inside has no crash, but if I logout, and then login and try to remove the items from the container the first item out does not crash, but the second crash already gives ...
I try debug it, so: have this lines in tasks.cpp
for (auto item : ToReleaseItems) {

and 

g_game.map.clearSpectatorCache();

**Comment by Schiffers** [comment]
@marksamman why you closed it? if have the bug, so go test it.

**Comment by marksamman** [comment]
Because that code was added by you. This is not a support forum.
