### ISSUE TITLE
weapons.cpp, shorter maxHitChance formula

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#1643]
I believe there is a way to make the code shorter in WeaponDistance::useWeapon(Player* player, Item* item, Creature* target).

Instead of splitting it to cases, it could be something like:
```std::min<uint32_t>((range/distance) * ((maxHitChance/100) * skill), maxHitChance)```

formula compared with current one for 75% hit chance, distance 3, 4 and 7, range 7
http://www.wolframalpha.com/input/?i=plot+75%2C+x+*+1.55+%2B+6%2C+x+*+1.25+%2B+3%2C+x+*+0.7+%2B+2%2C+%287%2F3%29+*+%28%2875%2F100%29+*+x%29%2C+%287%2F4%29+*+%28%2875%2F100%29+*+x%29%2C+%287%2F7%29+*+%28%2875%2F100%29+*+x%29%2C+x+%3D+10..104

**Comment by marksamman** [comment]
I'm not sure I follow, and whether it's possible to do this without using advanced math operations which will slow down the code, because distance 1 and 5 use the same chance formula. If you already have a working solution, please open a pull request so that it can be reviewed.
