### ISSUE TITLE
Windows SDK outdated.

### ISSUE THREAD

**Issue by l04d** [otland/forgottenserver#1644]
i've been having problems with compilation, actually with mpir  ("Error	LNK2001	unresolved external symbol __imp___iob_func	theforgottenserver	C:\Users\l04d\Downloads\forgottenserver-master\vc14\mpir.lib(memory.obj)	1").
Solved with mpir update.
https://github.com/wbhart/mpir

**Comment by ranisalt** [comment]
Well fuck Windows.

Just kidding. Doesn't something like chocolatey or [nuget](https://www.nuget.org/) help with this? The latter I remember having some libraries for automatic download and install to not-so-bad locations. It would be nicer to have scripted installs instead of compiled libraries.

**Comment by l04d** [comment]
I'm about this too, but unfortunately i need to run windows because of fucking autocad.
i think SDK files should be moved into github repository so we can make a pull request.

**Comment by socket2810** [comment]
There is a workaround for that, add this in any source file.
````C++
extern "C" {FILE __iob_func[3] = {*stdin, *stdout, *stderr}; }
````

**Comment by fir3element** [comment]
update mpir

**Comment by marksamman** [comment]
The SDK has been updated to version 3.0, it should be compatible with Visual Studio 2015.

**Comment by esfomeado** [comment]
@marksamman could you please put on the sdk the library versions?

Thanks

**Comment by marksamman** [comment]
@esfomeado version 3.1 of the SDK (now on the Windows compiling page) should have VERSION files which show the version of the library
