### ISSUE TITLE
Bug with VIP in account/character

### ISSUE THREAD

**Issue by totolol123** [otland/forgottenserver#1656]
Just a little bug i noticed. You can add yourself on vip list in any other character on the same account and after log in in that character you will see yourself on the vip and also you can talk with yourself.
Shouldn't be possible add or talk with yourself right? I think that should be impossible add any character off the same account on vip list.

**Comment by ranisalt** [comment]
IIRC it's also possible on Tibia but it just does nothing since messages are 1) not stored 2) not delivered if you are offline.

And what if more than 1 player per account is allowed and both want to talk? You would be limiting the feature.
