### ISSUE TITLE
# Crash server

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1658]
(gdb) thread 1
[Switching to thread 1 (Thread 0x7530cfb09780 (LWP 3614))]
#0  0x00007530ce007b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
81      ../sysdeps/unix/syscall-template.S: Ficheiro ou directoria inexistente.
(gdb) bt
#0  0x00007530ce007b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000000a08610 in boost::asio::detail::epoll_reactor::run (this=0x23b3850, block=true, ops=...) at /usr/local/include/boost/asio/detail/impl/epoll_reactor.ipp:392
#2  0x0000000000a092ae in boost::asio::detail::task_io_service::do_run_one (this=0x23b36f0, lock=..., this_thread=..., ec=...) at /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:356
#3  0x0000000000a090bd in boost::asio::detail::task_io_service::run (this=0x23b36f0, ec=...) at /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:149
#4  0x0000000000a09547 in boost::asio::io_service::run (this=0x7c9d9163d350) at /usr/local/include/boost/asio/impl/io_service.ipp:59
#5  0x0000000000a06b5d in ServiceManager::run (this=0x7c9d9163d320) at /home/Viking/src/server.cpp:52
#6  0x00000000009806d7 in main (argc=1, argv=0x7c9d9163d578) at /home/Viking/src/otserv.cpp:110
(gdb)

thread 2

er=0x75309c9caf80, type=TALKTYPE_SAY, words="!exp") at /home/Viking/src/talkaction.cpp:101
#9  0x000000000084bfd2 in Game::playerSaySpell (this=0xd9ebe0 <g_game>, player=0x75309c9caf80, type=TALKTYPE_SAY, text="!exp") at /home/Viking/src/game.cpp:3321
#10 0x000000000084bcb0 in Game::playerSay (this=0xd9ebe0 <g_game>, playerId=268435472, channelId=0, type=TALKTYPE_SAY, receiver="", text="!exp") at /home/Viking/src/game.cpp:3251
#11 0x00000000009efd07 in std::_Mem_fn<void (Game::*)(unsigned int, unsigned short, SpeakClasses, std::string const&, std::string const&)>::operator()<unsigned int&, unsigned short&, SpeakClasses&, std::string&, std::string&, void> (this=0x2890c90, __object=0xd9ebe0 <g_game>) at /usr/include/c++/4.8/functional:601
#12 0x00000000009ecc55 in std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, unsigned short, SpeakClasses, std::string const&, std::string const&)> (Game*, unsigned int, unsigned short, SpeakClasses, std::string, std::string)>::__call<void, , 0ul, 1ul, 2ul, 3ul, 4ul, 5ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul, 5ul>) (this=0x2890c90,
    __args=<unknown type in /home/Viking/tfs, CU 0x161fc57, DIE 0x17303ba>) at /usr/include/c++/4.8/functional:1296
#13 0x00000000009e88f2 in std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, unsigned short, SpeakClasses, std::string const&, std::string const&)> (Game*, unsigned int, unsigned short, SpeakClasses, std::string, std::string)>::operator()<, void>() (this=0x2890c90) at /usr/include/c++/4.8/functional:1355
#14 0x00000000009e0366 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, unsigned short, SpeakClasses, std::string const&, std::string const&)> (Game*, unsigned int, unsigned short, SpeakClasses, std::string, std::string)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/4.8/functional:2071
#15 0x0000000000a20a80 in std::function<void ()>::operator()() const (this=0x29f5120) at /usr/include/c++/4.8/functional:2471
#16 0x0000000000a2096a in Task::operator() (this=0x29f5110) at /home/Viking/src/tasks.h:42
#17 0x0000000000a20212 in Dispatcher::threadMain (this=0xd9ea40 <g_dispatcher>) at /home/Viking/src/tasks.cpp:50
#18 0x000000000098cd3d in std::_Mem_fn<void (Dispatcher::*)()>::operator()<, void>(Dispatcher*) const (this=0x23b3948, __object=0xd9ea40 <g_dispatcher>) at /usr/include/c++/4.8/functional:601
#19 0x000000000098c7ab in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x23b3940) at /usr/include/c++/4.8/functional:1732
#20 0x000000000098c107 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::operator()() (this=0x23b3940) at /usr/include/c++/4.8/functional:1720
#21 0x000000000098bb32 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)> >::_M_run() (this=0x23b3928) at /usr/include/c++/4.8/thread:115
#22 0x00007530ce87c390 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#23 0x00007530ceb04182 in start_thread (arg=0x7530cd3f8700) at pthread_create.c:312
#24 0x00007530ce00747d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)

thread 3

(gdb) thread 3
[Switching to thread 3 (Thread 0x7530ccb46700 (LWP 3620))]
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
238     ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S: Ficheiro ou directoria inexistente.
(gdb) bt
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x0000000000a04a0b in __gthread_cond_timedwait (__cond=0xd9eb20 <g_scheduler+64>, __mutex=0xd9eaf8 <g_scheduler+24>, __abs_timeout=0x7530ccb45d60)
    at /usr/include/x86_64-linux-gnu/c++/4.8/bits/gthr-default.h:871
#2  0x0000000000a05553 in std::condition_variable::__wait_until_impl<std::chrono::duration<long, std::ratio<1l, 1000000000l> > > (this=0xd9eb20 <g_scheduler+64>, __lock=..., __atime=...)
    at /usr/include/c++/4.8/condition_variable:160
#3  0x0000000000a0520f in std::condition_variable::wait_until<std::chrono::duration<long, std::ratio<1l, 1000000000l> > > (this=0xd9eb20 <g_scheduler+64>, __lock=..., __atime=...)
    at /usr/include/c++/4.8/condition_variable:100
#4  0x0000000000a04ab4 in Scheduler::threadMain (this=0xd9eae0 <g_scheduler>) at /home/Viking/src/scheduler.cpp:34
#5  0x000000000098ccd5 in std::_Mem_fn<void (Scheduler::*)()>::operator()<, void>(Scheduler*) const (this=0x23b3ad8, __object=0xd9eae0 <g_scheduler>) at /usr/include/c++/4.8/functional:601
#6  0x000000000098c6f9 in std::_Bind_simple<std::_Mem_fn<void (Scheduler::*)()> (Scheduler*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x23b3ad0) at /usr/include/c++/4.8/functional:1732
#7  0x000000000098c0e9 in std::_Bind_simple<std::_Mem_fn<void (Scheduler::*)()> (Scheduler*)>::operator()() (this=0x23b3ad0) at /usr/include/c++/4.8/functional:1720
#8  0x000000000098bb14 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Scheduler::*)()> (Scheduler*)> >::_M_run() (this=0x23b3ab8) at /usr/include/c++/4.8/thread:115
#9  0x00007530ce87c390 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007530ceb04182 in start_thread (arg=0x7530ccb46700) at pthread_create.c:312
#11 0x00007530ce00747d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by degolaot** [comment]
PS. I removed the !exp command now.

**Comment by marksamman** [comment]
1-8 is missing from thread 2

**Comment by degolaot** [comment]
I was desperate when ot down. I dont see it missing.

**Comment by PrinterLUA** [comment]
I feel like you have custom source edits.

**Comment by degolaot** [comment]
nop, It was one command called !exp

When I removed  this command the otserver dont down anymore.

thanks
