### ISSUE TITLE
Pk on depot after shoot runes

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1662]
This is not a big problem, but we got an impression of "bug". How it works? The player throws a fire field on the ground and enters depot after it, later another player comes and goes over the fire. The player who is in the depot will be Pk .

I was tryed to put: combat:setParameter(COMBAT_PARAM_AGGRESSIVE, 1) on script but dont work

Print: http://prntscr.com/9loqz0

**Comment by marksamman** [comment]
Working as intended, see #1559.
