### ISSUE TITLE
Clean map isn't working?

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1663]
The function cleanmap() isn't working?

![clean](https://cloud.githubusercontent.com/assets/14372849/12081881/afeccde2-b26e-11e5-9784-1107813ba085.png)

**Comment by Tarliton** [comment]
https://github.com/otland/forgottenserver/blob/master/src/map.cpp#L1000

I believe that is pz, right?

**Comment by vankk** [comment]
Yes, it's in pz and didn't clean monsters corpose.

**Comment by Tarliton** [comment]
So, you got the answer yourself. Corpses are decaying, they will eventually desapear. Pz is not cleaned on purpose. You can check the code for yourself.
Next time you should ask this on the forum.

**Comment by vankk** [comment]
Dude, just fuck off, wtf. Just trying check if it's TFS bug.

And by the way for "fix it":

Change it:
https://github.com/otland/forgottenserver/blob/master/src/map.cpp#L1000

for it:
```if (!tile || tile->hasFlag(TILESTATE_HOUSE)) {```
