### ISSUE TITLE
Crash #2

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1664]
*** Error in `/home/Viking/tfs': malloc(): memory corruption (fast): 0x000072e000000010 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x72e048a96700 (LWP 9039)]
0x000072e0495eacc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: Ficheiro ou directoria inexistente.
(gdb)

----------

bt full

#0  0x000072e0495eacc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        resultvar = 0
        pid = 9035
        selftid = 9039
#1  0x000072e0495ee0d8 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x72e048a95390,
            sa_sigaction = 0x72e048a95390}, sa_mask = {__val = {
              126307638697576, 126307419622752, 126307617297335,
              126307617297296, 8358488, 11, 126307617297335, 126307617297360,
              8518502, 11, 126307419622760, 4607199022163613071,
              126307427106704, 4575657222627480831, 126307419622752,
              126307617297440}}, sa_flags = 8515170,
          sa_restorer = 0x72e048a954fe}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000072e049627394 in __libc_message (do_abort=do_abort@entry=1,
    fmt=fmt@entry=0x72e049735b28 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
        ap = {{gp_offset = 40, fp_offset = 29408,
            overflow_arg_area = 0x72e048a95670,
            reg_save_area = 0x72e048a95600}}
        fd = 40
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x000072e0496320f7 in malloc_printerr (action=<optimized out>,
    str=0x72e049735ec8 "malloc(): memory corruption (fast)",
    ptr=<optimized out>) at malloc.c:4996
        buf = "000072e000000010"
        cp = <optimized out>
#4  0x000072e049634e04 in _int_malloc (av=0x72e040000020, bytes=88)
    at malloc.c:3359
        p = 0x0
        fb = < optimized out >
        pp = < optimized out >
        nb = 96
        idx = < optimized out >
        bin = < optimized out >
        victim = < optimized out >
        size = < optimized out >
        victim_index = < optimized out >
        remainder = < optimized out >
        remainder_size = < optimized out >
        block = < optimized out >
        bit = < optimized out >
        map = < optimized out >

**Comment by degolaot** [comment]
http://pastebin.com/iHmtX0yw thread 1

**Comment by ranisalt** [comment]
Lines 9 to 11 on thread 2 seem to be a problem, there was memory corruption on allocation via the operator new inside the STL. What compiler version and operation system are you using?

**Comment by marksamman** [comment]
You have made changes to your source code, so I'm going to ask you to stop posting crash reports as not only does it make us more difficult for us to analyze them, but they may just as well be caused by your modifications.
