### ISSUE TITLE
addDamage don't work

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1667]
addDamage don't work.

![addDamage](http://1.1m.yt/uHlNHgT.png)

**Comment by ranisalt** [comment]
Code, please

**Comment by vankk** [comment]
@ranisalt 
Trying use it https://github.com/otland/forgottenserver/blob/master/data/spells/scripts/attack/soul%20fire.lua

and tryed use this too:
https://github.com/otland/forgottenserver/pull/1635/files

both doesn't work.

**Comment by ninjalulz** [comment]
You have probably applied your own changes to Game::combatChangeHealth, and in the process, you managed to "destroy" Combat.addDamage. However, it's working perfectly fine for me when I tested a couple of minutes ago.

**Comment by vankk** [comment]
Thanks, Ninja.
```
if (healthChange == 0) {
	return false;
}
```
to
```
if (healthChange == 0) {
	return true;
}
```
It was my bad, I'm sorry.
