### ISSUE TITLE
Server does not open after update

### ISSUE THREAD

**Issue by MaxyTibia** [otland/forgottenserver#1671]
After I made all changes from latest commits, I have this problem:

```
>> Loading script systems
Segmentation fault
```

GDB log:
http://pastebin.com/ECxSaUW2

Please help me,
Thanks a lot.

**Comment by marksamman** [comment]
I can't reproduce this.

**Comment by MaxyTibia** [comment]
Another version of GDB log:
http://pastebin.com/dnyhNSjD

**Comment by ranisalt** [comment]
Please use git bisect to check exactly at which commit this started to happen.
