### ISSUE TITLE
Compilation Error Ubuntu 14.04

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1672]
[  1%] Generating CXX prefix source cotire/tfs_CXX_prefix.cxx
[  2%] Generating CXX prefix header cotire/tfs_CXX_prefix.hxx
[  3%] Building CXX precompiled header cotire/tfs_CXX_prefix.hxx.gch
Scanning dependencies of target tfs
[  5%] Building CXX object CMakeFiles/tfs.dir/src/otpch.cpp.o

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/tfs.dir/src/otpch.cpp.o] Error 4
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2

----------

I'm using the latest CMakeLists.txt

This has happened before ?

My old and current working is:
http://pastebin.com/Ya36N01r

**Comment by marksamman** [comment]
#1325
#1400
#1404
#1569
