### ISSUE TITLE
Monsters Walking on bombs

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1674]
Hello, in tibia global some monsters dont walk in fire bomb, energy bomb, etc...
Like: Choking Fear

In global he dont walk in energy bomb if the player dont attack, but here he is walking.
Have others too like Retching Horror

**Comment by slavidodo** [comment]
Check another monster ( rat is example of monsters that aren't moving ) if it can move then give another comment.

If not then check the immune flag, as far as I think it's depending on immune!

**Comment by ranisalt** [comment]
They don't only if there is another way around the field, if the only possible way is walking over a field then they do walk.

**Comment by degolaot** [comment]
But in real tibia they have a random chance to walk and its like 5% of chance to walk without player attacked they.

**Comment by slavidodo** [comment]
The only way to fix is editing sources tile.cpp or monster.cpp -. creature.cpp.

**Comment by WibbenZ** [comment]
The issue already exists, #193
