### ISSUE TITLE
NPC trade window and selling items small big problem

### ISSUE THREAD

**Issue by Cokil** [otland/forgottenserver#1676]
I have small big problem
When i move item from eq to backpack it isn't turn white in trade window look:
How to fix it?
![bug](https://cloud.githubusercontent.com/assets/16600412/12183644/fcd793be-b587-11e5-8515-fc89292187de.jpg)

**Comment by slavidodo** [comment]
I think there are two solutions :
1- Adding player items to shop item list.
2- Edit ``` internalMoveItem ``` to update the item list if player moved an item.

**Comment by ranisalt** [comment]
> 1- Adding player items to shop item list.

This is already an option and you can toggle it in the client, but does not solve the problem. 2) is good.

**Comment by vankk** [comment]
It's working how suppost to be.

![WPDNu5](http://2.1m.yt/WPDNu5.png)

**Comment by WibbenZ** [comment]
No one noticed the old UI layout? :)
This is most likely unrelated to this repo (not sure when the UI was changed, but vankk said it works).
So if you are using 1.0 or 1.1 then update to 1.2.

**Comment by Cokil** [comment]
I'm using 0.4 r3884 and I don't know what to do with "internalMoveItem" I'm noob ;s

**Comment by marksamman** [comment]
That does not belong to this issue tracker. Use the Support forum on OTLand.
