### ISSUE TITLE
Cmake Version

### ISSUE THREAD

**Issue by Ravene** [otland/forgottenserver#1679]
hi i try today compile theforgottenserver but i got this

CMake Error at cmake/cotire.cmake:40 (cmake_minimum_required):
  CMake 2.8.12 or higher is required.  You are running version 2.8.9
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)

**Comment by ranisalt** [comment]
Err... it's exactly that. You need a newer version of CMake. That means you should ASAP stop using whatever prehistorical version of Ubuntu you are using.
