### ISSUE TITLE
onMoveItem needs toContainer

### ISSUE THREAD

**Issue by drakylucas** [otland/forgottenserver#1684]
You can get "fromContainer" using item:getParent():getId()
but you can't do it toContainer.
I'm trying to limit by LUA a backpack only for a specific kind of items and can't do it right now :s 

function Player:onMoveItem(item, count, fromPosition, toPosition)

**Comment by ranisalt** [comment]
`onMoveItem` could be easily modified to hold `fromContainer` and `toContainer` but that would be backwards-incompatible, as other scripts relying on that would break.

**Comment by drakylucas** [comment]
It doesn't work, works when you move from container to other container, but server crashes if you don't move from X container to Y container (like moving from container to ground)

**Comment by marksamman** [comment]
Duplicate of #1446
