### ISSUE TITLE
onLook vocation

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1687]
![Image](http://3.1m.yt/biENPqp.png)

The image is high explanatory.

**Comment by raymondtfr** [comment]
I just downloaded the source with latest commits, compiled (using boost 1.6.0, and SDK 3.0) and tested, and this does not happens.

If you are compiled it with Boost 1.5.9 and SDK 2.0 then try compiling it again with the new Boost 1.6.0 and the newer SDK 3.0.

**Comment by vankk** [comment]
@raymondtfr 
I'm trying compiling by using it.. https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu is that?I don't quite understand what did you mean.

**Comment by raymondtfr** [comment]
Oh, I thought you were on Windows.

In that case, use the latest sources (don't do any modifications) and compile it and see if this problem persists, if that is not the case *then this problem might be related to any changes you might have made in the sources*.

**Comment by vankk** [comment]
![Image](http://1.1m.yt/L0A5_r9.png)
![Image](http://3.1m.yt/CrwRcmr.png)

**Comment by raymondtfr** [comment]
Weirdest thing. I double-checked it, with all four vocations (just in case) and it does show the required vocations.
Did you run the server with default TFS datapack - if not, it could be your **items.otb**.

**Comment by vankk** [comment]
I just removed **showInDescription="0"** on **movements.xml** and it worked as suppost to be. Do you know why that?

**Comment by raymondtfr** [comment]
Oh. Well it seems that you had ``showInDescription=0`` specified for vocations *sorcerer* and *druid*, like this (?):
```xml
		<vocation name="Sorcerer" showInDescription="0" />
		<vocation name="Druid" showInDescription="0" />
```
when ``showInDescription`` equals ``0`` then the vocation string in ``name`` will not appear in description when you right-click the item.
By removing showInDescription="0" in both ``<vocation name="Sorcerer" showInDescription="0" />" and ``<vocation name="Druid" showInDescription="0" />`` the default value for which ``showInDescription`` initializes is ``1`` I guess (I haven't checked sources), and by that those vocation strings will be shown.
