### ISSUE TITLE
[Solved] Spells Utito tempo~

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1689]
Utito tempo
Utito tempo san

is decreasing shield by 0

**Comment by raymondtfr** [comment]
**Description:** "During this time, the knight is in a Blood Rage that gives him incredible attack power but lets him *completely neglect his defence*, and so he is **unable to block any attacks in this condition**."

By saying that the player is "**unable to block any attacks in this condition**" means that when you use this spell your shielding skill is not taken into account, and therefore you will not reduce any physical based attacks with your shielding.

The thing is, in vanilla even though your defense is completely neglected, the skill bar does not show Shielding 0 -- but it is. In TFS, it is shown Shielding 0 -- so it stays pretty evident for the player.

So this is not a bug.

**Comment by degolaot** [comment]
Humm, thank you man, you are right, i think.
