### ISSUE TITLE
Incorrect wizard addon

### ISSUE THREAD

**Issue by pvpfleczu** [otland/forgottenserver#1692]
Hello, in the latest version TFS I find this bug with Wizard Outfit(addon)

This isn't First addon for Wizard
![](http://i.imgur.com/RgzMKSE.png)
This is First addon for Wizard.... not seccond
![](http://i.imgur.com/xIcHB6l.png)

**Comment by marksamman** [comment]
That's client-sided, so it has nothing to do with TFS.
