### ISSUE TITLE
npcs more like rl tibia

### ISSUE THREAD

**Issue by rudger** [otland/forgottenserver#1697]
This will make npcs not walk over items with height > 0 by default.

remove:
	if ((attr = npcNode.attribute("ignoreheight"))) {
		ignoreHeight = attr.as_bool();
	}

add:
      ignoreHeight = npcNode.attribute("ignoreheight").as_bool();

**Comment by rudger** [comment]
and in void Npc::reset():
 ignoreHeight = false;

**Comment by degolaot** [comment]
But if player through one item in ground (any item) the npc will dont move?

**Comment by rudger** [comment]
Only item with height > 0 (barrels, boxes...)
