### ISSUE TITLE
[QUESTION] Update 10.90

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1701]
When will update this branch to 10.90?

**Comment by WibbenZ** [comment]
When 1.3 is released I suppose(was like that with 10.76 and 1.2).

**Comment by vankk** [comment]
Any preview when 1.3 will be released?

**Comment by Weeboo** [comment]
help in completing **1.2** only need need need?

**Comment by WibbenZ** [comment]
Well this is not 100% but I bet Mark wants most of these things done before 1.2 is released;
https://github.com/otland/forgottenserver/wiki/Roadmap-1.2

And then you can also serach here, these are posible bugs etc that should be fixed before 1.2 is released (but once again, they might be moved to 1.3).
https://github.com/otland/forgottenserver/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.2
