### ISSUE TITLE
items.otb issue

### ISSUE THREAD

**Issue by rudger** [otland/forgottenserver#1702]
I'm walking on real Tibia and I see statues as itemid: 8834-8837 with text ingame but if I open RME I can't put text on them. (hint: Island of Destiny, Dawnport).
I know it's easily editable but wanted to point it out.

**Comment by WibbenZ** [comment]
This was up before (if it's the same issue) by me, it's not an OTB or even a TFS issue.
It's an issue with RME, the signs in thais (outside the dp etc) could also not be edited, you can read about it here; https://github.com/hjnilsson/rme/issues/29
