### ISSUE TITLE
Game::removeMoney is not removing money properly

### ISSUE THREAD

**Issue by Marahin** [otland/forgottenserver#1706]
Hello,

I have stepped upon an issue where Game::removeMoney (@ game.cpp) does not work properly. 
To reproduce the error, take any working (banker for example) NPC script which uses removeMoney, so either with player:removeMoney(x) or with doPlayerRemoveMoney(cid, count).

Then get yourself a container inside a container, for example bag inside a bag. In the inner bag put 1 crystal coin, and in the upper bag - 1 crystal coin as well.
If you try to "deposit 20000", the NPC will indeed deposit it, however your money will not be taken away from you.

It might not be the removeMoney() itself, but maybe internalRemoveItem function? Not sure. 

I'm looking forward to a fix, since I haven't found anything on the forums that actually mention the cause of the bug - usually people blame an NPC; this however is a serious vulnerability in the core of the server.

**Comment by marksamman** [comment]
Try changing the last line in Game::removeMoney from "return false" to "return true".
