### ISSUE TITLE
Large Memory Leak

### ISSUE THREAD

**Issue by brunominervino** [otland/forgottenserver#1711]
For some time I am doing a monitoring in my server, where there is a large memory leak. In a very short time he gets to use half of the total cloud memory. Here is a result of monitoring:

http://pastebin.com/ShtDrm6K

Anyone have any idea?

**Comment by vankk** [comment]
You are using the latest commit or using Vanahein's sources?

**Comment by brunominervino** [comment]
@marksamman How we can make a profiling to analyze this? Do you have any references?

**Comment by marksamman** [comment]
You can use valgrind.

**Comment by brunominervino** [comment]
Ok, thank you! I will search it to use.

**Comment by ranisalt** [comment]
I'm not sure valgrind has support for FS I/O. I remember not being able to use it some time ago.

**Comment by brunominervino** [comment]
@marksamman you know gprof? My problem is to use with cmake, look about: http://linoxide.com/tools/gprof-performance-analysis-programs/

**Comment by ranisalt** [comment]
@brunominervino just pass the `-pg` flag to the compiler (`CMAKE_CXX_FLAGS`) and it will generate profiling information.

**Comment by brunominervino** [comment]
@ranisalt I already try this and don't work for me...
What commands you use to compile?

**Comment by asamy45** [comment]
Why are you using gprof?  It's not the tool you want, valgrind is the tool you want...  Also, how does that pastebin link show any kind of memory leakage?

**Comment by wgrriffel** [comment]
@brunominervino I've made a lot of valgrind tests and all of them returns not a single leak, could you give some example when you get the leaks?
