### ISSUE TITLE
desintegrate rune like tibia rl

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1712]
Actually the [desintegrate rune ](https://github.com/otland/forgottenserver/blob/master/data/spells/scripts/support/desintegrate%20rune.lua)is not working as suppost to be [like tibia rl](http://tibia.wikia.com/wiki/Disintegrate_Rune)

**Comment by marksamman** [comment]
You'll have to explain how it's not working as you expect it to, linking to a wiki page telling us that it's not working as "tibia rl" is not good enough.

**Comment by TheSumm** [comment]
It should:
- work even if there is a creature on the target tile
- remove the first 500 items it can remove
- when finding an item it cannot remove (actionid > 0, uid <= 65535, not movable, human corpse) it skips that one and continues

Magic effects are probably wrong too, I am not totally certain, but I think it always sends CONST_ME_POFF whether it removes something or not.

**Comment by vankk** [comment]
Oh, my bad @marksamman but @TheSumm was already explained, also **you can use the desintegrate rune on player feet**.
