### ISSUE TITLE
Is it possible to support ipv6?

### ISSUE THREAD

**Issue by hugito00** [otland/forgottenserver#1723]
I can only allow access external connections through ipv6 ;(

*My ISP is a beatch*

**Comment by kornholi** [comment]
There's no support right now, but it could be easily added. The main issue
would be client support, since I assume IPv4 is hardcoded in most clients.

**Comment by hugito00** [comment]
Yeah, tought so.

I kinda made a few changes to bind my ipv6 in the forgottenserver. (could confirm using a port scan)
But I don't think it will be easy to make the client accept my ipv6 ( even using a dns )
