### ISSUE TITLE
[QUESTION] sendCreatureSkull(const Creature* creature)

### ISSUE THREAD

**Issue by drakus607** [otland/forgottenserver#1725]
void sendCreatureSkull(const Creature* creature) const {
	if (client) {
		client->sendCreatureSkull(creature);
	}
}

Could someone explain to me, what this function does? I'm playing a bit with PVP system (I'm also learning object oriented c++ here, so please don't get mad at me, if I'll ask stupid questions).

I know what setSkull() does, but I have no idea what above function is for. There is no documentation, so I figured I will just ask about. Please let me know if this is no place for questions like this one.

Thanks and have a good day.

**Comment by Kamenuvol** [comment]
It sends the skull to the client. If you don't send the skull will count in deaths but not appear to the player.
