### ISSUE TITLE
Die

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1736]
A few problems:

- The name **dice** was been changed in patch 10.22 to **die**.
- You cannot use a die on the Depot box.

**Comment by wgrrifel** [comment]
on my point of view that's have nothing to do with tfs, be unable to use on depot was the way cipsoft found to avoid botters, about the name nvm.

**Comment by marksamman** [comment]
It's up to you to customize your data pack as you wish, these things are not issues, but a pull request is welcome if you'd like to change them.
