### ISSUE TITLE
Wrong increase/decrease id

### ISSUE THREAD

**Issue by wgrriffel** [otland/forgottenserver#1739]
At lines 23 and 24 in actions.xml are turning into wrong item.

**Comment by vankk** [comment]
I can confirm this issue.

![Uploading issue 1739.gif…]()

**Comment by wgrrifel** [comment]
Probably the best fix for that is reallocate the id of bamboo lamp, but for that we need to change id on items.otb or i'm wrong?

**Comment by marksamman** [comment]
That's not an acceptable solution. If the item ids aren't adjacent, the solution is to write a Lua script.

**Comment by vankk** [comment]
@marksamman 
We can use something like this? http://pastebin.com/MQkNuBi8
