### ISSUE TITLE
onCreatureAppear execute to early?

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1740]
Hello,

Well i would like to point out two issues:
First one, if i example. Create a monster and set redskull on it. Then print it out onCreatureAppear and i get skull: 0

"Rat has spawned with skullId: 0"

Only workaround i found, was to use addEvent to delay and then i can print the value. But i think it would be very heavy if it spawns alot of monsters and addEvents getting executed.
http://pastebin.com/XzEQgbVy

Second problem, if i use onCreatureAppear and the setSkull to red again, when a monster spawn on startup. It does not have the skull. Until i kill it and it respawns.
I suspects it has todo something with this:
https://github.com/otland/forgottenserver/blob/master/src/spawn.cpp#L208

**Comment by PrinterLUA** [comment]
Well i found maybe a solution, if we delay it in the source Game::placeCreature:
http://pastebin.com/B3stEnPZ

I would love some input on this @marksamman

**Comment by djarek** [comment]
The onCreatureAppear function is called when you call ```Game.createMonster("Rat", player:getPosition())``` which I believe is working as designed (the creature is present in the game world once that function returns, thus I think it's logical that onCreatureAppear event is triggered then).

**Comment by PrinterLUA** [comment]
So delaying it. Is the only way?

**Comment by djarek** [comment]
Not sure about the second case, but in the first one, yes, that's the only way.

**Comment by PrinterLUA** [comment]
Would the change i made in The source good way. Or will is it a dangling pointer?

**Comment by djarek** [comment]
I think you might encounter client debugs from time to time due to the spawned creature not being known by the spectators' clients.
