### ISSUE TITLE
Tibia Specifications Initiative

### ISSUE THREAD

**Issue by mazen-mardini** [otland/forgottenserver#1742]
There is a very huge need for the Tibia protocols and file-formats to be documented to allow newer developers to understand OT better and thereby increase the amount contributions to the community. 

For more information: https://otland.net/threads/tibia-specifications-initiative.241415/

Please share your opinions, either here at GitHub or at OTLand.

Thank you.

**Comment by marksamman** [comment]
The Forgotten Server is not dependent on proprietary file formats, nor is this an issue that belongs in this tracker. If you'd like to document the formats that The Forgotten Server uses, you may open a pull request with your documentation and I'll copy it over to the wiki.

**Comment by mazen-mardini** [comment]
Thank you for you feedback.

It's quite obvious that OTServ is not dependent on proprietary file formats, but it is important for OTServ developers to know about the protocols of the communication between the server and the client.

The link that I posted is about an initiative that covers all OT projects, not just otserv. This is why I mentioned the file formats, because it is relevant to the initiative, the initiative that also benefits otserv by help providing documentation of the game/login protocols to the developers.

But I agree, although this is a central project in the OT community and hosting the documentation here might bring some benefits, it's probably much better to do it elsewhere.
