### ISSUE TITLE
Game.createMonster bug?

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1744]
The monsters are not summoned if in configured position have fire on ground

Game.createMonster(name, position)

**Comment by vankk** [comment]
`Game.createMonster(monsterName, position[, extended = false[, force = false]])`

To read more [click here](Game.createMonster(monsterName, position[, extended = false[, force = false]])).

:stuck_out_tongue:

**Comment by degolaot** [comment]
Thanks, but page not found for read more

**Comment by vankk** [comment]
@degolaot 
Sorry, check it again.
