### ISSUE TITLE
compiling on windows

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#1748]
could you write a tutorial for codeblocks instead of visual studio to compile on windows?
vs2015 is like cancer for windows. Installing it takes ages to download and unpack, slows system startup and makes huge mess in registry.

**Comment by Zbizu** [comment]
thank you for quick reaction. You da real mvp!

**Comment by ranisalt** [comment]
You know you can use CMake to generate a CB project, right?

**Comment by wgrriffel** [comment]
@Zbizu you can use compiler whatever you want, it's board to found issues not support, ask on otland forums for it.

**Comment by Shawak** [comment]
You mixed up some things there, marksamman actually is the real mvp and you're the cancer

**Comment by Zbizu** [comment]
@Shawak I asked for a solution, not your opinion. After ages of wasted time I compiled it on virtual machine so I don't care anymore anyway.

**Comment by asamy45** [comment]
@ranisalt gave you *the* solution.
