### ISSUE TITLE
Issue while compiling latest sources.

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1749]
I have faced this error while compiling.
```LINK : fatal error LNK1104: cannot open file 'libboost_system-vc140-mt-gd-1_60.lib'```
Well, I have checked if the file is in linker search and found it.
(Windows/ Boost 1-60 / MSVC 2015)

**Comment by marksamman** [comment]
Does this happen for anyone else? I'm not sure if this is a support matter or an actual issue. Last time I tried compiling with Visual Studio it worked fine. Are you perhaps trying to compile a 64-bit build with 32-bit libraries or the other way around?

**Comment by ninjalulz** [comment]
Nope, it works just fine here.

**Comment by slavidodo** [comment]
@marksamman After a long search I found this issue happening in window 10 ( old builds ), updating my windows fixed the issue since the error not just happened with forgottenserver.

**Comment by Shawak** [comment]
Compiling with visual studio works for me.
