### ISSUE TITLE
AddSkillTries not working as expected

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1751]
Shouldn't this function

``` lua
target:addSkillTries(skillId, target:getVocation():getRequiredSkillTries(skillId, target:getSkillLevel(skillId) + 1) - target:getSkillTries(skillId))
``

Give the target skill to 100%
```

**Comment by ranisalt** [comment]
But what happens?

**Comment by slavidodo** [comment]
I am on distance level 80, it don't add 1 lvl, it adds some percentages only.

**Comment by slavidodo** [comment]
@ranisalt Well, I just figured out that if you tried to add sword to a mage for example, you will face this error. but if you tried to give me a knight, it will work as expected.

**Comment by kornholi** [comment]
Why'd you close this? Seems like a bug to me.

**Comment by thatmichaelguy** [comment]
Needs to be inside a loop as seen in [add_skill.lua](https://github.com/otland/forgottenserver/blob/master/data/talkactions/scripts/add_skill.lua#L54)

**Comment by EPuncker** [comment]
as mentioned above, it needs to be inside a loop, so not a but at all
