### ISSUE TITLE
Decay Bug when put decaying item inside Depot Chest and logout.

### ISSUE THREAD

**Issue by kanohn** [otland/forgottenserver#1753]
Hi,

1 - First Decay Bug:
Edit an item with duration less than 5 minutes, decayto attribute and try to reproduce:
Put this item inside the house, then !leavehouse.

Duration will stop when the item reach the inbox, and never count again, and item become infinite.

2 - Second Decay Bug:

Edit an item with duration less than 5 minutes, decayto attribute and try to reproduce:
Put this item inside depot chest, then logout your character.
Login in again, and look at the item, stop the duration forever and become infinite.

Why need to fix this? For the item "claw of the nexus spawn" when lose item power, transform to new claw of the nexus spawn that have 86400 seconds duration and decay attribute, and is not the same thing like rings or anything that count the time only when equipped, always this item stop decaying forever when the player put in depot chest and leave the game, same with houses.

**Comment by kanohn** [comment]
Edit: This happen only if the item have < minutes left.

If the item have more than 1 hour, it will show hour and minutes, and minutes are decaying.

If the item have less than 1 hour, it will show minutes and seconds, and seconds don't decay.

**Comment by wgrriffel** [comment]
I confirm this, tested with a candlestick and after the candle gone for mailbox from a house never decayed, becomes infinity.

**Comment by PrinterLUA** [comment]
Can you do me a favor add under this line: https://github.com/otland/forgottenserver/blob/master/src/house.cpp#L258

This:
g_game.startDecay(item);

**Comment by wgrriffel** [comment]
@PrinterLUA maybe this should be checked at depot chest and mailbox, it doesn't happen only when moved from a house, also in items on depot chest, and thats crucial for some items like secret agents tools, if you deposit a jammed one to depot it never decay to normal one.

**Comment by slavidodo** [comment]
As well, it should be added where the items are loaded from database to depot!

**Comment by gugahoa** [comment]
How exactly is the intended behavior?
Item continues to decay inside of depot? Item continues to decay after removing from depot?

**Comment by Tarliton** [comment]
@gugahoa The item stops to decay inside of the depot. It only decays when a player is carrying or on the floor.
I tested this with a Mysterious Voodoo Skull.

**Comment by gugahoa** [comment]
@Tarliton When you say depot you mean depot locker (with depot chest and inbox) or only depot chest? If only depot chest, if you send a parcel with a item that decays inside, will it decay inside the inbox?

**Comment by Tarliton** [comment]
@gugahoa I only tested inside of the depot chest, not the inbox. I believe that it's the same behavior between those two. I will test later.

**Comment by wgrriffel** [comment]
@gugahoa items just don't decay inside of mailbox or depot, i tested moving with !leavehouse  when it goes to mailbox don't decay also.

**Comment by Tarliton** [comment]
@wgrriffel I mean on the ~real~ server.

**Comment by gugahoa** [comment]
If possible, test the case of lighting a torch inside the depot/inbox and see if it decays.

**Comment by wgrriffel** [comment]
@gugahoa what is happening, tested about now, if item is moved from or parcel house or by player to depotbox ONLY stop decays either player logouts out, if not everything is fine as far as i tested.

**Comment by gugahoa** [comment]
I already know what's happening, as reported by @kanohn 
Items don't stop decaying when put inside depot/inbox. Seems like the intended behavior is for it to stop decaying.
If there's a item decaying inside depot/inbox, and you logout, when you login the item does not start decaying again after taking it out of the depot/inbox.

I already have a fix ready for the above mentioned scenario. Just need someone to test if you light a torch inside the depot, should it start decaying inside depot?

**Comment by wgrriffel** [comment]
@gugahoa sorry i didnt noticed, tried on real tibia right now with a candlestick, it doesnt decayed while i were offline (about 20 mins), and i am logged in for 20 min and candlestick seens it are not decaying at depot, just to be sure i'll make the same with touch, touch i know it decay after 20 mins.

**Comment by wgrriffel** [comment]
@gugahoa torch while offline did not decayed, but while online did, on depotlocker and mailbox had this behavior.

**Comment by gugahoa** [comment]
I did a thoroughly test on global. To sum it up: The item will decay inside the depot locker (regardless of being depot chest or inbox) as long as you stand besides it.
I'm already working on a fix, shouldn't be too long before I send a PR.

**Comment by wgrriffel** [comment]
@gugahoa you sure i didnt realized it, it will decay only when stand still in front of depot spot, that's why when i logged out doesnt decayed =)

**Comment by vankk** [comment]
I can't confirm the first issue.

It is working here.
![First issue item decay house](http://2.1m.yt/RdkvsCn.gif)
