### ISSUE TITLE
Cryptographically secure pseudo-random number generator for otserv

### ISSUE THREAD

**Issue by mazen-mardini** [otland/forgottenserver#1758]
This is a request to implement secure randomization based on std::random_device that relies on platform-specific random number generators (such as /dev/urandom).

The reason to make support for such an RNG is to make otserv generally less predictable. Take this scenario for example:
- There is a Quest-script that was released to the public that was written in LUA.
- Several known servers integrate it into their map.
- The quest generates random rewards for the players at the end.
- The seed (for randomization) is out in the public and is not based on a random number entered by the user anything else server-specific that is impossible to figure out.
- Players (if smart/willing) might theoretically abuse this flaw to get the desired reward.

The same applies to everything that is randomly generated in LUA, and is publicly released, and might yield significant profit for the user if abused. A potential solution would be to ask every server admin to create his/her own random number for the seed, but the problem with that is that it is 1. inconvenient and 2. going to generate the same set of numbers on server-reset.

To solve this problem random_device might be used to get unpredictably random numbers. To spare the devs some time I've written the foundation in c++.

``` cpp
#include <boost/thread.hpp>
#include <random>

double random_double() {
	static boost::thread_specific_ptr<std::random_device> gen_ptr;
	
	if (!gen_ptr.get())
		gen_ptr.reset(new std::random_device);
	
	std::random_device& gen = *gen_ptr.get();
	
	unsigned int&& random_int = gen() - gen.min();
	unsigned int&& distance = gen.max() - gen.min();
	
	double&& random_double = (double)random_int / (double)distance;
	
	return random_double;
}

int32_t random_range(int32_t from, int32_t to) {
	int64_t&& distance = (int64_t)to - (int64_t)from;
	return (int32_t)((int64_t)from + (int64_t)round(random_double() * distance));
}
```
The code is thread-safe (works with std::thread too) and is cross-platform.

Integration of this would be done by creating a LUA function such as "randomDeviceRange(from, to)" that utilized random_range. 

If you are interested, but need the code to be modified in some way, then please send a message.

@ranisalt, I've written a possible scenario.
@asamy45, Hmm, I've actually worked very little with platform-specific threading so I'm not sure what sched_yield exactly does. But in any case we can't include anything platform-specific as we would have to support every thinkable platform and that would make the function random_double far too complex. It is probably better to just use boost as much as possible.

_EDIT: Code no longer relies on boost.random, but rather on the std variant of random_device._

**Comment by asamy45** [comment]
Hi,

First, my comment was sarcastic; you don't really need "thread-safety" here.  You're pretty much reading from /dev/urandom, etc, if something really needs to be done about the thread-safety, it's in the kernel, and is done via per-cpu code not per-thread.
Second, if you want per-thread, you can just use the keyword **__thread**
Third, `sched_yield()` yields the current processor, causing it to switch to the next task, this is useful when the current task is about to sleep or so...

**Comment by ranisalt** [comment]
You really don't need Boost. C++11 random is very enough with `std::random_device` providing the available CSPRNG and falling back to a non-CSPRNG if none are available.

**Comment by mazen-mardini** [comment]
@ranisalt, that sounds good. I'll try out the std variant and tell you the results.

**Comment by kornholi** [comment]
> The seed (for randomization) is out in the public and is not based on a random number entered by the user anything else server-specific that is impossible to figure out.

Uh, where exactly is the seed out in public? The RNG is seeded by current time (in milliseconds) at server startup. Even if you knew the seed, figuring out the RNG stream position with more than a few players would be difficult and even harder to abuse.

I don't see how this is an issue at all.

**Comment by mazen-mardini** [comment]
@kornholi, Is math.random automatically seeded?

**Comment by marksamman** [comment]
https://github.com/otland/forgottenserver/blob/master/data/globalevents/scripts/startup.lua#L2

**Comment by mazen-mardini** [comment]
@marksamman, I see. Didn't realize LUA had an alternative to os.time().

**Comment by marksamman** [comment]
It doesn't. It's a custom function which calls OTSYS_TIME in our code:
```cpp
inline int64_t OTSYS_TIME()
{
	return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
}
```

**Comment by mazen-mardini** [comment]
@marksamman, Okay I see. It certainly limits the use-cases for this type of RNG then. For already having time in millisecond precision available in LUA changes a lot.
@ranisalt, The std variant seem to work fine with me. I'll update the original post in any case.

**Comment by ranisalt** [comment]
Here's what you probably want @mazen-mardini 
https://github.com/ranisalt/forgottenserver/tree/csprng

**Comment by marksamman** [comment]
I would be careful to call that a CSPRNG since it uses Mersenne Twister with a 32-bit seed on most systems. It's definitely stronger than what we currently have in Lua because the seed is gathered from random_device which is an actual CSPRNG.

**Comment by ranisalt** [comment]
Yes, you are right. I replaced with the shuffle order engine, which is somewhat more unpredictable, but that's as strong as we can get with C++11 and should be enough for the usage aforementioned.
