### ISSUE TITLE
Is there any reason deathlist isn't added to TFS 1.0+?

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1760]
As title said, deathlist, is somehow important.

**Comment by ninjalulz** [comment]
Are you talking about a "deathList" parameter for onDeath? You can easily retrieve "deathList" information by iterating through Creature.getDamageMap.

**Comment by slavidodo** [comment]
I meant why by default it's not added?

**Comment by Shawak** [comment]
Because you dont need it by default, so why create a mess
