### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by aderal000** [otland/forgottenserver#1763]
After update to newest commit, when I try to build I get:

> -- Performing Test COMPILER_KNOWS_CXX11
> -- Performing Test COMPILER_KNOWS_CXX11 - Success
> -- Performing Test COMPILER_KNOWS_STDLIB
> -- Performing Test COMPILER_KNOWS_STDLIB - Failed
> -- Found GMP: /usr/include
> CMake Error at /usr/local/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
>   Could NOT find PugiXML (missing: PUGIXML_INCLUDE_DIR PUGIXML_LIBRARIES)
> Call Stack (most recent call first):
>   /usr/local/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
>   cmake/FindPugiXML.cmake:5 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:27 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/ots/tfs-source/build/CMakeFiles/CMakeOutput.log".
> See also "/home/ots/tfs-source/build/CMakeFiles/CMakeError.log".
> [root@tardis build]#

I have istaled PugiXML by:  yum install pugixml

**Comment by ranisalt** [comment]
You need `pugixml-devel` [as the manual states](https://github.com/otland/forgottenserver/wiki/Compiling-on-Fedora).

**Comment by aderal000** [comment]
Now I get:

> [  6%] Building CXX object CMakeFiles/tfs.dir/src/actions.cpp.o
> /home/ots/tfs-source/src/actions.cpp: In member function 'virtual bool Actions::registerEvent(Event*, const pugi::xml_node&)':
> /home/ots/tfs-source/src/actions.cpp:103:87: error: 'class pugi::xml_attribute' has no member named 'as_string'
>     std::cout << "[Warning - Actions::registerEvent] Missing toid in fromid: " << attr.as_string() << std::endl;
>                                                                                        ^
> /home/ots/tfs-source/src/actions.cpp:137:89: error: 'class pugi::xml_attribute' has no member named 'as_string'
>     std::cout << "[Warning - Actions::registerEvent] Missing touid in fromuid: " << attr.as_string() << std::endl;
>                                                                                          ^
> /home/ots/tfs-source/src/actions.cpp:171:89: error: 'class pugi::xml_attribute' has no member named 'as_string'
>     std::cout << "[Warning - Actions::registerEvent] Missing toaid in fromaid: " << attr.as_string() << std::endl;
>                                                                                          ^
> /home/ots/tfs-source/src/actions.cpp: In member function 'virtual bool Action::loadFunction(const pugi::xml_attribute&)':
> /home/ots/tfs-source/src/actions.cpp:441:34: error: 'const class pugi::xml_attribute' has no member named 'as_string'
>   const char* functionName = attr.as_string();
>                                   ^
> make[2]: *** [CMakeFiles/tfs.dir/src/actions.cpp.o] Error 1
> make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
> make: *** [all] Error 2
> [root@tardis build]#

**Comment by ranisalt** [comment]
You should follow the issue template.

**Comment by aderal000** [comment]
I will in next issue if happen :0 Can saomebody help me with that?

**Comment by jakon89** [comment]
Try: `cmake -DPUGIXML_INCLUDE_DIR=/usr/local/opt/pugixml/include/pugixml-1.8 -DPUGIXML_LIBRARIES=/usr/local/opt/pugixml/lib/pugixml-1.8 ..`
