### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by aderal000** [otland/forgottenserver#1765]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Update to newest commit
2. Build

### Expected behaviour
Build TFS

### Actual behaviour
 [  6%] Building CXX object CMakeFiles/tfs.dir/src/actions.cpp.o
> /home/ots/tfs-source/src/actions.cpp: In member function 'virtual bool Actions::registerEvent(Event*, const pugi::xml_node&)':
> /home/ots/tfs-source/src/actions.cpp:103:87: error: 'class pugi::xml_attribute' has no member named 'as_string'
>     std::cout << "[Warning - Actions::registerEvent] Missing toid in fromid: " << attr.as_string() << std::endl;
>                                                                                        ^
> /home/ots/tfs-source/src/actions.cpp:137:89: error: 'class pugi::xml_attribute' has no member named 'as_string'
>     std::cout << "[Warning - Actions::registerEvent] Missing touid in fromuid: " << attr.as_string() << std::endl;
>                                                                                          ^
> /home/ots/tfs-source/src/actions.cpp:171:89: error: 'class pugi::xml_attribute' has no member named 'as_string'
>     std::cout << "[Warning - Actions::registerEvent] Missing toaid in fromaid: " << attr.as_string() << std::endl;
>                                                                                          ^
> /home/ots/tfs-source/src/actions.cpp: In member function 'virtual bool Action::loadFunction(const pugi::xml_attribute&)':
> /home/ots/tfs-source/src/actions.cpp:441:34: error: 'const class pugi::xml_attribute' has no member named 'as_string'
>   const char* functionName = attr.as_string();
>                                   ^
> make[2]: *** [CMakeFiles/tfs.dir/src/actions.cpp.o] Error 1
> make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
> make: *** [all] Error 2
> [root@tardis build]#

### Environment
Centos 6 x64, cmake 4.3, gcc

**Comment by marksamman** [comment]
CentOS 6 is too old. Upgrade to 7.

**Comment by aderal000** [comment]
What libs are to old?

**Comment by Marahin** [comment]
The ones you have in CentOS 6.

**Comment by marksamman** [comment]
Your entire OS is too old. The GCC version is too old. At least pugixml is too old. If you need help, please use the support board on OTLand: https://otland.net/forums/support.16/
