### ISSUE TITLE
Teleport use

### ISSUE THREAD

**Issue by mattyx14** [otland/forgottenserver#1766]
Use ladder with pz tile is possible to use for skull players

**Comment by wgrriffel** [comment]
Would be appreciated you use new issue template, that help everybody looking into an issue, I tried many ways to reproduce this and all of them failed, be more specific how to reproduce.

**Comment by mattyx14** [comment]
Step 1
<a href="http://1.1m.yt/yAJt1aH.png" target="_blank"><img src="http://1.1m.yt/yAJt1aH.png" alt="ImgLand.net image" /></a>

Step 2
<a href="http://1.1m.yt/MMKVjo4.png" target="_blank"><img src="http://1.1m.yt/MMKVjo4.png" alt="ImgLand.net image" /></a>

**Comment by mattyx14** [comment]
Here the example for: https://github.com/otland/forgottenserver/issues/1767
<a href="http://3.1m.yt/pcgrhAN.png" target="_blank"><img src="http://3.1m.yt/pcgrhAN.png" alt="ImgLand.net image" /></a>

**Comment by ranisalt** [comment]
I don't think it's still an issue but if it is, ask for a pull request of the commit above

**Comment by mattyx14** [comment]
the ladder no is possible to use :S with this change check this

**Comment by wgrriffel** [comment]
@mattyx14 that's because he forgot to add getSkull() != 0.

**Comment by BenDol** [comment]
@wgrriffel that wouldn't be correct you should use pzlocked value.

**Comment by wgrriffel** [comment]
@BenDol for sure, just give him an idea, anyway imo it's not an issue, it's just a problem with his project, if some player aren't be suppose to climb a ladder with pz the ladder should be rounded with PZ tile, just like cipsoft does.

**Comment by mattyx14** [comment]
yep this work fine now jejeje
