### ISSUE TITLE
Stack Players

### ISSUE THREAD

**Issue by mattyx14** [otland/forgottenserver#1768]
Here the example for: https://github.com/otland/forgottenserver/issues/1767
<a href="http://3.1m.yt/pcgrhAN.png" target="_blank"><img src="http://3.1m.yt/pcgrhAN.png" alt="ImgLand.net image" /></a>

**Comment by PrinterLUA** [comment]
What does protection level has to do with stacking other players? I sense you made source modifications.

**Comment by wgrriffel** [comment]
I tried to reproduce this with normal switches (default TFS map on Deposit) and it's don't happen to me.

**Comment by vankk** [comment]
> I tried to reproduce this with normal switches (default TFS map on Deposit) and it doesn't happening to me.

Same as here.

**Comment by marksamman** [comment]
If you're going to keep opening new issues, at least use the issue template, but please don't open new issues just because the old ones were closed. Instead, you can still comment on a closed issue and explain why we should open the issue when nobody can reproduce it.
