### ISSUE TITLE
Crash on Tfs 1.2

### ISSUE THREAD

**Issue by fironfox** [otland/forgottenserver#1770]
My server crashs and in GDB crash report have this report:
`Type "apropos word" to search for commands related to "word"...
Reading symbols from tfs...(no debugging symbols found)...done.
[New LWP 7583]
[New LWP 7584]
[New LWP 7585]
[New LWP 7586]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./tfs --log-file output.txt error.txt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000008e470a in NetworkMessage::getLength() const ()
[Current thread is 1 (Thread 0x6b52de2c2740 (LWP 7583))]
`
I use the Source with cast system of djarek, is the only modification.

**Comment by marksamman** [comment]
Please open a new issue if this happens without modifications to the source code, and use the issue template.
