### ISSUE TITLE
Crash on Tfs 1.2

### ISSUE THREAD

**Issue by fironfox** [otland/forgottenserver#1771]
Now, after i post one log with tfs custom modifications, i'm running tfs 1.2 without source modifications and the crashs continue to appears... I have use the gdb for catch de crash logs and caught this:

#0  0x00006a852a053fa9 in ?? ()
No symbol table info available.
#1  0x0000000000a73e5b in std::_Rb_tree<Position, std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > >, std::_Select1st<std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > > >, std::less<Position>, std::allocator<std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > > > >::_M_insert_node(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node<std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > > >*) ()
No symbol table info available.
#2  0x0000000000a72b7e in std::_Rb_tree_iterator<std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > > > std::_Rb_tree<Position, std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > >, std::_Select1st<std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > > >, std::less<Position>, std::allocator<std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > > > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<Position const&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > > >, std::piecewise_construct_t const&, std::tuple<Position const&>&&, std::tuple<>&&) ()
No symbol table info available.
#3  0x0000000000a71d7d in std::map<Position, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> >, std::less<Position>, std::allocator<std::pair<Position const, std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> > > > >::operator[](Position const&) ()
No symbol table info available.
#4  0x0000000000a6e817 in Map::getSpectators(std::unordered_set<Creature*, std::hash<Creature*>, std::equal_to<Creature*>, std::allocator<Creature*> >&, Position const&, bool, bool, int, int, int, int) ()
No symbol table info available.
#5  0x0000000000934d95 in Game::internalCreatureChangeVisible(Creature*, bool) ()
No symbol table info available.
#6  0x00000000008d815d in ConditionInvisible::startCondition(Creature*) ()
No symbol table info available.
#7  0x0000000000904b75 in Creature::addCondition(Condition*, bool) ()
No symbol table info available.
#8  0x0000000000a97d14 in MoveEvent::EquipItem(MoveEvent*, Player*, Item*, slots_t, bool) ()
No symbol table info available.
#9  0x0000000000a987f3 in MoveEvent::fireEquip(Player*, Item*, slots_t, bool)    ()
No symbol table info available.
#10 0x0000000000a96413 in MoveEvents::onPlayerEquip(Player*, Item*, slots_t, bool) ()
No symbol table info available.
#11 0x0000000000ad51b1 in Player::postAddNotification(Thing*, Cylinder const*, int, cylinderlink_t) ()
No symbol table info available.
#12 0x000000000092b787 in Game::transformItem(Item*, unsigned short, int) ()
No symbol table info available.
#13 0x0000000000a97c55 in MoveEvent::EquipItem(MoveEvent*, Player*, Item*, slots_t, bool) ()
No symbol table info available.
#14 0x0000000000a987f3 in MoveEvent::fireEquip(Player*, Item*, slots_t, bool)    ()
No symbol table info available.
#15 0x0000000000a96413 in MoveEvents::onPlayerEquip(Player*, Item*, slots_t, bool) ()
No symbol table info available.
#16 0x0000000000ad51b1 in Player::postAddNotification(Thing*, Cylinder const*, int, cylinderlink_t) ()
No symbol table info available.
#17 0x0000000000929532 in Game::internalMoveItem(Cylinder*, Cylinder*, int, Item*, unsigned int, Item**, unsigned int, Creature*, Item*) ()
No symbol table info available.
#18 0x0000000000afecc3 in ProtocolGame::parseEquipObject(NetworkMessage&) ()
No symbol table info available.
#19 0x0000000000afd399 in ProtocolGame::parsePacket(NetworkMessage&) ()
No symbol table info available.
#20 0x0000000000aec040 in Protocol::onRecvMessage(NetworkMessage&) ()
No symbol table info available.
#21 0x00000000008debd5 in Connection::parsePacket(boost::system::error_code const&) ()
No symbol table info available.
#22 0x00000000008f3b05 in void std::_Mem_fn_base<void (Connection::*)(boost::system::error_code const&), true>::_M_call<std::shared_ptr<Connection>&, boost::system::error_code const&>(std::shared_ptr<Connection>&, void const volatile*, boost::system::error_code const&) const ()
No symbol table info available.
#23 0x00000000008f29e4 in void std::_Mem_fn_base<void (Connection::*)(boost::system::error_code const&), true>::operator()<std::shared_ptr<Connection>&, boost::system::error_code const&, void>(std::shared_ptr<Connection>&, boost::system::error_code const&) const ()
No symbol table info available.
#24 0x00000000008f11ae in void std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)>::__call<void, boost::system::error_code const&, unsigned long const&, 0ul, 1ul>(std::tuple<boost::system::error_code const&, unsigned long const&>&&, std::_Index_tuple<0ul, 1ul>) ()
No symbol table info available.
#25 0x00000000008ef155 in void std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)>::operator()<boost::system::error_code const&, unsigned long const&, void>(boost::system::error_code const&, unsigned long const&) ()
No symbol table info available.
#26 0x00000000008ebeeb in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >::operator()(boost::system::error_code const&, unsigned long, int) ()
No symbol table info available.
#27 0x00000000008f5bde in boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >, boost::system::error_code, unsigned long>::operator()() ()
No symbol table info available.
#28 0x00000000008f5b40 in void boost::asio::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >, boost::system::error_code, unsigned long> >(boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer
No symbol table info available.
#29 0x00000000008f59d4 in void boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >, boost::system::error_code, unsigned long>, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >(boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >, boost::system::error_code, unsigned long>&, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)>&) ()
No symbol table info available.
#30 0x00000000008f5569 in void boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >, boost::system::error_code, unsigned long>, boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >(boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >, boost::system::error_code, unsigned long>&, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >*) ()
No symbol table info available.
#31 0x00000000008f4ffa in void boost_asio_handler_invoke_helpers::invoke<boost::
asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >, boost::system::error_code, unsigned long>, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> > >(boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >, boost::system::error_code, unsigned long>&, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> >&) ()
No symbol table info available.
#32 0x00000000008f45e2 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<std::_Mem_fn<void (Connection::*)(boost::system::error_code const&)> (std::shared_ptr<Connection>, std::_Placeholder<1>)> > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
No symbol table info available.
#33 0x0000000000b56d2e in boost::asio::detail::task_io_service_operation::complete(boost::asio::detail::task_io_service&, boost::system::error_code const&, unsigned long) ()
No symbol table info available.
#34 0x0000000000b57e57 in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) ()
No symbol table info available.
#35 0x0000000000b57b67 in boost::asio::detail::task_io_service::run(boost::system::error_code&) ()
No symbol table info available.
#36 0x0000000000b58086 in boost::asio::io_service::run() ()
#37 0x0000000000b55269 in ServiceManager::run() ()
No symbol table info available.
#38 0x0000000000aab506 in main ()
No symbol table info available.

**Comment by wgrriffel** [comment]
would you mind follows issue template?

**Comment by wgrriffel** [comment]
@fironfox you don't need open a new issue for that, you can edit this one and reopen.
