### ISSUE TITLE
Mailbox removes items that you send to offline players (always)

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#1776]
Above this line:

    IOLoginData::savePlayer(&tmpPlayer);

https://github.com/otland/forgottenserver/blob/master/src/mailbox.cpp#L120

You must add:

    tmpPlayer.setLastDepotId(1); // here any number, but not -1

or this line:

    if (player->lastDepotId != -1) {

https://github.com/otland/forgottenserver/blob/master/src/iologindata.cpp#L795

**will make it NOT SAVE player depot.**

Funny.. in case when we are ONLY interested in updating player depot, it saves everything, but NOT player depot xD

Sorry, but I got no idea how to make Pull request on GitHub and no time to learn it now.

**Comment by marksamman** [comment]
Depot and inbox are stored separately.
