### ISSUE TITLE
TFS Crash Mutex

### ISSUE THREAD

**Issue by dadasko** [otland/forgottenserver#1777]
[Switching to thread 1 (Thread 0x697e9fc77700 (LWP 41685))]
#0  __GI___pthread_mutex_lock (mutex=0x3f7e3f0)
    at ../nptl/pthread_mutex_lock.c:66
66      ../nptl/pthread_mutex_lock.c: No such file or directory.

[Switching to thread 2 (Thread 0x697ea2533740 (LWP 41681))]
#0  0x0000697ea07f5e53 in epoll_wait ()
    at ../sysdeps/unix/syscall-template.S:81
81      ../sysdeps/unix/syscall-template.S: No such file or directory.

[Switching to thread 3 (Thread 0x697e9eb8e700 (LWP 41688))]
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.

[Switching to thread 4 (Thread 0x697e9f3ec700 (LWP 41686))]
#0  pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
238     ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S: No such file or directory.

BT FULL

#0  __GI___pthread_mutex_lock (mutex=0x3f7e3f0) at ../nptl/pthread_mutex_lock.c:66
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        type = 24744
#1  0x00000000007cc1c3 in __gthread_mutex_lock(pthread_mutex_t*) ()
No symbol table info available.
#2  0x00000000007cc213 in __gthread_recursive_mutex_lock(pthread_mutex_t*) ()
No symbol table info available.
#3  0x00000000007cd44a in std::recursive_mutex::lock() ()
No symbol table info available.
#4  0x00000000007cd620 in std::lock_guard<std::recursive_mutex>::lock_guard(std::recursive_mutex&)
    ()
No symbol table info available.
#5  0x00000000007fa930 in Connection::getIP() ()
No symbol table info available.
#6  0x00000000009f2368 in ProtocolLogin::getCharacterList(std::string const&, std::string const&)
    ()
No symbol table info available.
#7  0x00000000009f4217 in void std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)>::_M_call<std::shared_ptr<ProtocolLogin>&, std::string&, std::string&>(std::shared_ptr<ProtocolLogin>&, void const volatile*, std::string&, std::string&) const ()
No symbol table info available.
#8  0x00000000009f4172 in void std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)>::operator()<std::shared_ptr<ProtocolLogin>&, std::string&, std::string&, void>(std::shared_ptr<ProtocolLogin>&, std::string&, std::string&) const ()
No symbol table info available.
#9  0x00000000009f40e8 in void std::_Bind<std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)> (std::shared_ptr<ProtocolLogin>, std::string, std::string)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) ()
No symbol table info available.
#10 0x00000000009f3db4 in void std::_Bind<std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)> (std::shared_ptr<ProtocolLogin>, std::string, std::string)>::operator()<, void>() ()
No symbol table info available.
#11 0x00000000009f3be4 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)> (std::shared_ptr<ProtocolLogin>, std::string, std::string)> >::_M_invoke(std::_Any_data const&) ()
No symbol table info available.
#12 0x0000000000a1d26c in std::function<void ()>::operator()() const ()
No symbol table info available.
#13 0x0000000000a1d156 in Task::operator()() ()
No symbol table info available.
#14 0x0000000000a1ca12 in Dispatcher::threadMain() ()
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#15 0x000000000099f5c1 in void std::_Mem_fn<void (Dispatcher::*)()>::operator()<, void>(Dispatcher*) const ()
No symbol table info available.
#16 0x000000000099f01f in void std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
No symbol table info available.
#17 0x000000000099e915 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::operator()() ()
No symbol table info available.
#18 0x000000000099e23e in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)> >::_M_run() ()
No symbol table info available.
#19 0x0000697ea1085970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#20 0x0000697ea12e20a4 in start_thread (arg=0x697e9fc77700) at pthread_create.c:309
        __res = <optimized out>
        pd = 0x697e9fc77700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {115992567445248, 5826683491557467487, 0,
                115992610242656, 124120768204928, 115992567445248, -9069767730929179297,
                -9069744286690417313}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0},
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#21 0x0000697ea07f587d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

**Comment by marksamman** [comment]
Use the issue template.
