### ISSUE TITLE
Creating new branch for BETA tfs 1.3

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1780]
As I mentioned here https://otland.net/threads/tfs-update-to-10-8x-10-9x-series-adding-missing-features.242616/ 
> I think it's time to update

@marksamman Could you create new branch `[BETA] Tfs 1.3` to allow us pushing pull requests and discuss it.

I shall get support from many ppl, i will update the missing features list on otland as soon as possible.

**Comment by marksamman** [comment]
You may work on any feature and submit a pull request. There's no need for us to branch into 1.3.

**Comment by slavidodo** [comment]
That's the point, we want to work on a features not related to 10.76.

**Comment by marksamman** [comment]
You're welcome to do that. I'm still not seeing what difference a new branch would make. TFS 1.2 isn't going to be released with protocol version 10.76.

**Comment by slavidodo** [comment]
That's the point, tfs 1.3 is going to be released within protocol 11.00
