### ISSUE TITLE
[Feature Request] parsePacket to Lua!

### ISSUE THREAD

**Issue by mokerhamer** [otland/forgottenserver#1786]
As the title says.

We just load a .xml. Now instead of programming in c++ we can do it in Lua. i'm currently using a system displayed in the screenshots below and it works amazingly! I don't have to compile and rebuild and reboot server with every small change. I just reload lua (/reload gameprotocols)!
Currently i have the following working with this system.
*Premiumstore
*Equiphotkey

Example XML (Feel free to check out  Premiumshop entry codes, the are annoying to track :) ):

![image](https://cloud.githubusercontent.com/assets/11699949/15158043/68ad2e06-16ee-11e6-96d3-45215b470e3c.png)

Example coding, of opening premiumshop, feel free to take a good look at opening Premiumstore code :)

![image](https://cloud.githubusercontent.com/assets/11699949/15158031/5ff67b96-16ee-11e6-85e2-cd22331a3c60.png)

Short but powerfull!

My system was made by Milice, so full credits to him.

**Comment by ranisalt** [comment]
Lots of stuff could be offloaded to Lua. Problem is it would be too easy to mess and break a server - nothing that I care personally.

**Comment by HeavenIsLost** [comment]
@ranisalt and what about performance? Luajit is good but does not operate miracles.

**Comment by ranisalt** [comment]
As stated by @djarek once, the major bottleneck is spectators, so we probably can afford some performance hit. Maybe not for all networking, but surely some of it can be scriptable.

**Comment by marksamman** [comment]
The major bottlenecks are: getSpectators, XTEA (IO thread probably spends 99% of its time doing XTEA encrypt, it either needs heavy optimizations using vectorization or we should support multiple IO threads), Map::getTile, heap allocations/deallocations, pathfinding and item attribute lookups. As long as these things aren't done in Lua, you can probably implement everything else without a noticeable difference if you're running LuaJIT. The most significant performance hit is going to be from increased heap allocation/deallocations by using Lua.

I agree that this is a powerful concept, and this is similar to how TFS 2.0 would probably be designed, where every packet would be handled in Lua.

**Comment by EPuncker** [comment]
https://github.com/otland/forgottenserver/pull/2978
