### ISSUE TITLE
Question about a networking code

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1788]
@djarek @marksamman 

Look at this line of code: https://github.com/otland/forgottenserver/blob/master/src/protocollogin.cpp#L208

Why we are using std::dynamic_pointer_cast instead of std::static_pointer_cast? We are sure that its a ProtocolLogin instance, why we should check the type using the dynamic cast?

The same thing here: https://github.com/otland/forgottenserver/blob/master/src/protocolgame.h#L84

**Comment by marksamman** [comment]
I don't see any reason why dynamic_pointer_cast is being used there.
