### ISSUE TITLE
Crash server - log

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1789]
#1  0x000000000044606a in ContainerIterator::advance (this=this@entry=0x7f1fac207d40) at container.cpp:727
        c = <optimised out>
        i = <optimised out>
#2  0x000000000047b451 in Game::playerEquipItem (this=0x832100 <g_game>, playerId=<optimised out>, spriteId=3447) at game.cpp:5820
        it = {over = std::list = {[0] = 0x8179290, [1] = 0x8179320, [2] = 0x81793b0, [3] = 0x8179440}, cur = }
        container = <optimised out>
        totalCount = <optimised out>
        remainderCount = 2
        containerItem = <optimised out>
        maxStack = 100
        player = 0x83df800
        type = @0x1db6280: {group = ITEM_GROUP_NONE, type = ITEM_TYPE_NONE, id = 2544, clientId = 3447, stackable = true, isAnimation = false, name = "arrow",
          article = "an", pluralName = "", description = "", runeSpellName = "", vocationString = "", abilities = std::unique_ptr<Abilities> containing 0x0,
          conditionDamage = std::unique_ptr<ConditionDamage> containing 0x0, weight = 70, levelDoor = 0, decayTime = 0, wieldInfo = 0, minReqLevel = 0,
          minReqMagicLevel = 0, charges = 0, maxHitChance = 90, decayTo = -1, attack = 25, defense = 0, extraDefense = 0, armor = 0, rotateTo = 0,
          runeMagLevel = 0, runeLevel = 0, combatType = COMBAT_NONE, transformToOnUse = {0, 0}, transformToFree = 0, destroyTo = 0, maxTextLen = 0,
          writeOnceItemId = 0, transformEquipTo = 0, transformDeEquipTo = 0, maxItems = 8, slotPosition = 560, speed = 0, wareId = 3447,
          magicEffect = CONST_ME_NONE, bedPartnerDir = DIRECTION_NONE, weaponType = WEAPON_AMMO, ammoType = AMMO_ARROW, shootType = CONST_ANI_ARROW,
          corpseType = RACE_NONE, fluidSource = FLUID_NONE, floorChange = 0 '\000', alwaysOnTopOrder = 0 '\000', lightLevel = 0 '\000', lightColor = 0 '\000',
          shootRange = 1 '\001', hitChance = 0 '\000', forceUse = false, hasHeight = false, walkStack = true, blockSolid = false, blockPickupable = false,
          blockProjectile = false, blockPathFind = false, allowPickupable = false, showDuration = false, showCharges = false, showAttributes = false,
          replaceable = true, pickupable = true, rotatable = false, useable = false, moveable = true, alwaysOnTop = false, canReadText = false,
          canWriteText = false, isVertical = false, isHorizontal = false, isHangable = false, allowDistRead = false, lookThrough = false, stopTime = false,
          showCount = true}
        slot = <optimised out>
#3  0x000000000059d508 in operator() (this=0x84162c0) at /usr/include/c++/4.8/functional:2471
No locals.
#4  operator() (this=0x84162b0) at tasks.h:42
No locals.
#5  Dispatcher::threadMain (this=0x832820 <g_dispatcher>) at tasks.cpp:50
        task = 0x84162b0
        taskLockUnique = {_M_device = 0x832838 <g_dispatcher+24>, _M_owns = false}
#6  0x00007f1fad1d6a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x00007f1fac211182 in start_thread (arg=0x7f1fac208700) at pthread_create.c:312
        __res = <optimised out>
        pd = 0x7f1fac208700
        now = <optimised out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139774008526592, -717684273526520614, 0, 0, 139774008527296, 139774008526592, 591411586524071130,
                591411595822449882}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimised out>
        pagesize_m1 = <optimised out>
        sp = <optimised out>
        freesize = <optimised out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007f1fac93e47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
---Type <return> to continue, or q <return> to quit---

**Comment by ranisalt** [comment]
The issue template! Don't ignore it.
