### ISSUE TITLE
Question about perfomance of condition

### ISSUE THREAD

**Issue by totolol123** [otland/forgottenserver#1791]
Just a question about creating a condition inside onCast function, something like:
```lua
function onCastSpell(creature, variant)
    local condition = Condition(SOME_CONDITION)
    ...
end
```
It will affect the perfomance in any way? If yes then deleting it after the use will resolve that perfomance problem? like:
```lua
function onCastSpell(creature, variant)
    local condition = Condition(SOME_CONDITION)
    ...
    condition:delete()
end
```
Thanks.

**Comment by ranisalt** [comment]
No, not significantly. Actually it's even necessary for some spell effects.
