### ISSUE TITLE
Client Debug

### ISSUE THREAD

**Issue by StevenTrembly** [otland/forgottenserver#1793]
Based to https://github.com/otland/forgottenserver/issues/885

I provided more information about the bug, so i hope it get a fix

https://otland.net/threads/movecreature-client-debug-with-all-information-proved.242954/

**Comment by PrinterLUA** [comment]
This has nothing with TFS 1.x serie? What is even OTX.

**Comment by StevenTrembly** [comment]
Thanks for the replay,

OTX based to 0.4, but why dose it matter if there is a common bug which exist in TFS 1.x serie?

**Comment by marksamman** [comment]
Unless anyone can confirm that it happens in 1.x, this does not belong to our issue tracker. #885 was long before TFS 1.0 was released, so it may very well have been fixed since.
