### ISSUE TITLE
[Suggestion] Move monster drop loot to Lua

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1797]
Would it be interesting and useful to move monster drop to Lua?
I made this feature a while ago for the servers I work on, it was quite useful to make random global drops.

The approach I did was use a feature sent as PR for TFS a while ago, Monster:onSpawn, to register the onDeath event on every monster. The rest was merely passing the C++ functions that generate loot to Lua.

**Comment by wgrriffel** [comment]
Signed, drops could be really fun customisable

**Comment by vankk** [comment]
Signed.

**Comment by marksamman** [comment]
Duplicate of #1249

**Comment by gugahoa** [comment]
Didn't even remember I made this same suggestion before. wow
Should have search for it before creating this issue, I'm sorry
