### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by walissonsantos** [otland/forgottenserver#1798]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./tfs --log-file output.txt error.txt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ProtocolGame::canSee (this=this@entry=0x7f6611b70960, x=32224, y=32371,
    z=10) at protocolgame.cpp:894
894             if (myPos.z <= 7) {
(gdb) bt
#0  ProtocolGame::canSee (this=this@entry=0x7f6611b70960, x=32224, y=32371,
    z=10) at protocolgame.cpp:894
#1  0x0000000000535d4d in canSee (pos=..., this=0x7f6611b70960)
    at protocolgame.cpp:884
#2  ProtocolGame::sendMagicEffect (this=0x7f6611b70960, pos=...,
    type=type@entry=13 '\r') at protocolgame.cpp:2653
#3  0x000000000042f0cf in sendMagicEffect (type=13 '\r', pos=..., this=
    0x7f662ebad800) at player.h:1094
#4  Game::addMagicEffect (list=std::unordered_set with 46 elements = {...},
    pos=..., effect=effect@entry=13 '\r') at game.cpp:4431
#5  0x000000000043450d in Game::addMagicEffect (this=0x8b5dc0 <g_game>,
    pos=..., effect=<optimized out>) at game.cpp:4424
#6  0x000000000047cfa8 in Combat::doCombatMana (caster=caster@entry=0x0,
    target=target@entry=0x7f65c3e9e000, damage=..., params=...)
    at combat.cpp:856
#7  0x000000000057ce2d in LuaScriptInterface::luaDoTargetCombatMana (
    L=0x40eec378) at luascript.cpp:3825
#8  0x00007f6692f59a88 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#9  0x00007f6692f9cf60 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#10 0x00000000005eb34f in protectedCall (nresults=1, nargs=6, L=0x40eec378)
    at luascript.cpp:375
---Type <return> to continue, or q <return> to quit---
#11 LuaScriptInterface::callFunction (this=0x152a1a0, params=params@entry=6)
    at luascript.cpp:602
#12 0x000000000041426a in Action::executeUse (this=0x1679dd0,
    player=0x7f65c3e9e000, item=<optimized out>, fromPos=..., toPos=...,
    extendedUse=<optimized out>, isHotkey=true) at actions.cpp:584
#13 0x0000000000417fa8 in Actions::useItemEx (this=0x7f6611b70960,
    player=0x7f65c3e9e000, fromPos=..., toPos=..., toStackPos=1 '\001', item=
    0x7f662a260560, isHotkey=true, creatureId=32371,
    creatureId@entry=307035930) at actions.cpp:422
#14 0x00000000004439c0 in Game::playerUseWithCreature (this=0x8b5dc0 <g_game>,
    playerId=<optimized out>, fromPos=..., fromStackPos=<optimized out>,
    creatureId=268481234, spriteId=<optimized out>, isHotkey=true)
    at game.cpp:2334
#15 0x000000000044b3b2 in operator()<unsigned int&, Position&, unsigned char&, unsigned int&, short unsigned int&, bool&, void> (__object=<optimized out>,
    this=<optimized out>) at /usr/include/c++/4.9/functional:569
#16 __call<void, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul> (__args=<optimized out>,
    this=<optimized out>) at /usr/include/c++/4.9/functional:1264
#17 operator()<, void> (this=<optimized out>)
    at /usr/include/c++/4.9/functional:1323
#18 std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, Position const&, unsigned char, unsigned int, unsigned short, bool)> (Game*, unsigned int, Position, unsigned char, unsigned int, unsigned short, bool)---Type <return> to continue, or q <return> to quit---
::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/4.9/functional:2039
#19 0x00000000004c270e in operator() (this=0x666a908)
    at /usr/include/c++/4.9/functional:2439
#20 operator() (this=0x666a900) at tasks.h:39
#21 Dispatcher::dispatcherThread (this=0x8b6400 <g_dispatcher>) at tasks.cpp:64
#22 0x00007f66920d0970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#23 0x00007f66918ee0a4 in start_thread (arg=0x7f6690f13700)
    at pthread_create.c:309
#24 0x00007f66916239cd in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by ranisalt** [comment]
Use. The. Damn. Issue. Template.

**Comment by HeavenIsLost** [comment]
Does not matter, just a lecher asking us to fix his issues.

**Comment by walissonsantos** [comment]
@HeavenIsLost I'm lecher? who are you?
