### ISSUE TITLE
Question about a old bug

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1801]
@marksamman I know that issue does not belongs to this repository, but I need ask something, if on TFS 1.2 has been fixed the bug that had in ShadowCores with the Market, something with boh, don't remember too much.

Thanks.

**Comment by vankk** [comment]
Thank you for being so self-proud, and have not answered the question if the bug as been fixed on the 1.2 repository.

**Comment by marksamman** [comment]
Thank you for using the issue template and using the issue tracker for it's purpose.
