### ISSUE TITLE
onMoveItem Event bug

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1804]
### Expected behaviour

Should not be moved from the slotPosition, either by just draging the item or switching the item with another item.
### Actual behaviour

I've made an item, in the event onMoveItem not being moveable, but still it's possible if you switch the item with another item e.g if the item is in the feet slot and you move another pair of boots to that slot. The "unmoveable" boots gets switched. But trying moving them out, would not work, you have to switch.
### Environment

Latest tfs.

**Comment by PrinterLUA** [comment]
Maybe onEquip and onDeEquip should allow return values.

**Comment by gugahoa** [comment]
onEquip and onDeEquip does allow return values. If you return false onEquip, it will not equip.

**Comment by PrinterLUA** [comment]
It seems onEquip only accept return values. onDeEquip does not. Is this intended? Or should we add onDeEquip check on Player::queryRemove.

**Comment by Zbizu** [comment]
steps to reproduce:
1. Equip item
2. Save server
3. Set onMoveItem to return false when this item id
4. Replace item with another in your eq

Expected: action denied
Observed: item can be replaced

Possible workaround:
Check toPosition, if eq slot and item that shouldn't be moved is equipped, return false
