### ISSUE TITLE
Level Door

### ISSUE THREAD

**Issue by genrider** [otland/forgottenserver#1805]
Here the example

![bez nazwy](https://cloud.githubusercontent.com/assets/5441478/15627071/b8bdd4d4-24d8-11e6-8d2e-8f592118cded.gif)

**Comment by wgrriffel** [comment]
`<movevent event="StepIn" itemid="5113" script="quest door.lua" />`
change to level door.lua, added by mistaken.

**Comment by marksamman** [comment]
Fixed in 5b04c5d3c86ed26a7eda43a7a0a61453c8199464.
