### ISSUE TITLE
Duplicating browsefield window.

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1808]
![Image_1](http://image.prntscr.com/image/b76d62bc8f8e4826a72cd1865f68d952.png)
And the error is in cipsoft's servers as well.

To produce, just keep opening a backpack and pressing back button.

**Comment by marksamman** [comment]
This has nothing to do with the server.

**Comment by ranisalt** [comment]
This has been default since ever, and if you manipulate one window the changes reflect on the others too.

**Comment by slavidodo** [comment]
I later got that when i examined tibia's flash client.

**Comment by TheSumm** [comment]
This is intended behaviour and essential when playing the game.
