### ISSUE TITLE
[Question] How does client recognizes skull of creature when he appears.

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1818]
When a new creature enters the screen, how does the client recognizes his skull?

**Comment by ranisalt** [comment]
https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L2759

It is sent on L2798

**Comment by slavidodo** [comment]
Well, thanks this will help my expert pvp alot.

@ranisalt 
Another question, how could I do some operations on an item when it appears in players screen, like when player is moving to west a new items appears in his screen.

**Comment by ranisalt** [comment]
I don't think that's easy, as there's not a `onItemAppear` event. You probably will have to hook `onWalk` to that.

**Comment by slavidodo** [comment]
Well the first solution seems nice, we gotta check for deltax, y (depending on direction), this seems easier, however I think that second could do better performance.

out of topic,
Can i ask for your skype/whatever commucation app you use? I'd be so glad to have a chat with you!

**Comment by ranisalt** [comment]
I don't usually use skype but you can hit me there, ranisalt

(actually it's ranisalt on virtually everything I have)

**Comment by slavidodo** [comment]
Done, awaiting for you agreement!

**Comment by slavidodo** [comment]
@ranisalt Didn't you receive my contact request?
