### ISSUE TITLE
Remove useless virtualCylinder class.

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1820]

**Comment by HeavenIsLost** [comment]
Why?

**Comment by kornholi** [comment]
Can someone test this doesn't break anything? e.g. adding items to containers if they have no parent

**Comment by slavidodo** [comment]
I didn't test but it should work fine, because virtual cylinder was actually a null pointer all the time!

**Comment by marksamman** [comment]
What do you mean with "virtual cylinder was actually a null pointer"? It wasn't, and this shouldn't have been changed so close to the 1.2 release...
```
VirtualCylinder* VirtualCylinder::virtualCylinder = new VirtualCylinder;
```

I suggest reverting it for now and leaving it in an open PR for people to test, and we can merge it after the 1.2 release if it seems fine, unless I'm wrong and it actually was a null pointer. An example of a side effect that may introduce bugs is that isRemoved() will now return true for items that used to have a virtual cylinder.

**Comment by slavidodo** [comment]
We can just add a static cylinder instead of virtualCylinder.

~I agree on the suggestion!

**Comment by gugahoa** [comment]
This breaks in luascripts.cpp:
doCreateItemEx (returns 0, causes memory leak)

The following functions will not work if item was created via Game.createItem:
Item.moveTo
Item.split
Item.getUniqueId
Item.transform

In game.cpp:
Game::internalRemoveItem(Item*, int32_t, bool, uint32_t) will not remove if item was created via Game.createItem
Game::transformItem(Item*, uint16_t, int32_t) if the item was created via Game.createItem

Those are the ones I tested

**Comment by slavidodo** [comment]
Solution is just creating a Cylinder instead of VirtualCylinder.
