### ISSUE TITLE
Suggestion of enhancement to addDamage()

### ISSUE THREAD

**Issue by raymondtfr** [otland/forgottenserver#1825]
### Brief description

 A player casts a **DOT** _(damage-over-time)_ spell and its projectile effect gets to the **position P**. In that position P there is a **tile**, and this tile has a **stack of creatures**.
### Steps to reproduce
1. Choose a spell that adds a combat condition, such as **Holy Flash** (script below).
2. Set the tag `targetCasterOrDirection` in **spells.xml** to **1**.
3. Cast the spell on a tile that has a stack of creatures **(atleast 1 player, and 1 monster)**.

``` lua
--[[
local combat = Combat()
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_HOLYDAMAGE)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_HOLYDAMAGE)
combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_SMALLHOLY)

function onCastSpell(creature, variant)
    local condition = Condition(CONDITION_DAZZLED)
    condition:setParameter(CONDITION_PARAM_DELAYED, true)

    local min = (creature:getLevel() * 0.01) + (creature:getMagicLevel() * 0.3) + 2
    local max = (creature:getLevel() * 0.01) + (creature:getMagicLevel() * 0.5) + 3
    local rounds = math.random(math.floor(min), math.floor(max))
    local time = math.random(10, 12) * 1000
]]
    local damage = creature:getTarget() and creature:getTarget():isPlayer() and 10 or 20
    local tile = Tile(variant:getPosition())
    if not creature:getTarget() and tile and tile:getCreatures() then
        local tileCreatures = tile:getCreatures()
        -- If the creature count on that tile is one (1), then its fine,
        -- but the problem surfaces when it is greater than one (1),
        -- because it'll add the combat condition to all stack creatures.
        for i = 1, tile:getCreatureCount() do
            if tileCreatures[i]:isPlayer() then
                damage = 10
            elseif tileCreatures[i]:isMonster() then
                damage = 20
            end
            condition:addDamage(rounds, time, -damage)
        end
    else
        condition:addDamage(rounds, time, -damage)
    end
--[[
    combat:setCondition(condition)
    return combat:execute(creature, variant)
end
]]
```
### Expected behaviour

We should be able to control to which creatures we want the condition to be added to. For example, there are 20 creatures stacked on the same tile (7 players and 13 monsters) if we use, let's say, the spell Holy Flash on that tile, then it should hit all of the stacked creatures but with a extended version of  addDamage() we should be able to add damage 10 to those 7 players, and damage 20 to those 13 monsters.

Couldn't `addDamage(rounds, time, damage)` be **extended** to something like `addDamage(target, rounds, time, damage)` that works with area combat spells. So the combat condition would be added only to a creature that is at a determined stack index of that tile that the target is positioned at.
### Actual behaviour

The combat condition is added to all the creatures on that tile, and therefore, there is no way to control to which creatures the condition should be added to.

This current behavior is fine for spells that doesn't add conditions to a target (because it should hit all creatures stacked on a tile, and _game.cpp_ handles the damage, i.e. half damage dealt to players), but this default behavior used in most spells **is not ideal for damage-over-time spells** since the damage may differ between monsters/players.
### Environment

TFS 1.2

**Comment by gugahoa** [comment]
I'm way for in for it. I think the whole way we handle spells should be enhanced.
I gave a suggestion #1762 that would help in this case, and open up new possibilities for spells.

So far I didn't have any success making an at least good "enough" improvement.

**Comment by raymondtfr** [comment]
That's great @gugahoa . I had some ideas on how to tackle this issue, but it happens I yet do not have such knowledge to carry on with it.
As for you suggestion (#1762) I think Callbacks are fine, but in this case I don't think they are best suited for dot spells, since Callbacks IIRC are executed only aftewards onCastSpell() and it may hit the perfomance a little?

The idea I had to try to solve this issue was to extend parameters in function ``addDamage()`` to something like this ``addDamage(player, target, damage, time, rounds)``, or even ``addDamage(player, target, tile, targetTileStackpos, damage, time rounds)``, anyway somehow bind the condition to the target id if it is hit by a area combat spell (w/ or w/o target lock, as ``creature:getTarget()`` currently works in ``onTileCombat``), or maybe the players class could inherit this and the other required function, and work from there. :dancers:

**Comment by diath** [comment]
Can't you already already achieve that by using CALLBACK_PARAM_TARGETTILE then Tile(position):getCreatures() to iterate over the creatures and use doCombatTargetHealth accordingly?

**Comment by diath** [comment]
Oh I haven't read your second comment although I'm not sure what's wrong with callbacks this will more or less do what you want and you can modify the combat params in the similar way that you did in your original snippet:

```lua
local c1 = Condition(CONDITION_DAZZLED)
c1:setParameter(CONDITION_PARAM_DELAYED, true)
c1:addDamage(5, 1000, -10)

local c2 = Condition(CONDITION_DAZZLED)
c2:setParameter(CONDITION_PARAM_DELAYED, true)
c2:addDamage(5, 1000, -20)

function onTargetTile(creature, position)
	local creatures = Tile(position):getCreatures()
	for _, creature in pairs(creatures) do
		if creature:isPlayer() then
			creature:addCondition(c1)
		elseif creature:isMonster() then
			creature:addCondition(c2)
		end
	end
end

local combat = Combat()
combat:setArea(createCombatArea(AREA_CROSS5X5))
combat:setCallback(CALLBACK_PARAM_TARGETTILE, "onTargetTile")

function onCastSpell(creature, variant, isHotkey)
	return combat:execute(creature, variant)
end
```

**Comment by totolol123** [comment]
Combat can't just be completely moved to lua?

**Comment by EvulMastah** [comment]
https://github.com/otland/forgottenserver/pull/1645

You could also add 4th optional boolean parameter to addDamage, if set would clear previous damage list and generate new one.

**Comment by raymondtfr** [comment]
@diath Hi, thanks for the snippet code, I actually did try using ``onTargetTile()`` but I was trying to achieve this behavior with only one (1) condition object, but it would fail everytime since it added the same ``addDamage()`` setup for all each stack creatures on a tile.

Your snippet code does exactly what I wanted, and I even adapted it to the way I'm doing in #1635

So, after many tests with this, I came across two situations.

I can either create two condition objects (as you did), one for players and the other for monsters. And there is no need to delete them. But creating two condition objects seems too much (counting with ``onCastSpell()``).

The other option is to create **and re-create** only one condition object (which is used both for monsters and players) on each loop iteration and delete this condition object ``condition:delete()`` each time it is added within the loop. This way it will not use the same ``addDamage()`` setup for all creatures stacked on that tile.

On the other hand, I'll need to create one more condition object, on ``onCastSpell()`` inthis case, but only if the player has locked on a target (selected a target through a mouse-click), so obviously the check will only be executed if ``onTileTarget()`` does not.

Actual testing script looks now like this:
```lua
local combat = Combat()
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_HOLYDAMAGE)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_HOLYDAMAGE)
combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_SMALLHOLY)

function onTargetTile(creature, position)
	local tile = Tile(position)
	local tileCreatures = tile:getCreatures()

	-- if I just check for tileCreatures then tile:getCreatures() may return true for a ground item,
	-- but there are actually no creatures on that tile (bug), that's why I added the tile:getCreatureCount() check (perfomance-wise).
	if tileCreatures and tile:getCreatureCount() ~= 0 then
		for _, creature in pairs(tileCreatures) do
			local condition = Condition(CONDITION_DAZZLED)
			condition:setParameter(CONDITION_PARAM_DELAYED, true)

			if creature:isPlayer() then
				condition:addDamage(7, 1000, -10)
				creature:addCondition(condition)

			elseif creature:isMonster() then
				condition:addDamage(7, 1000, -20)
				creature:addCondition(condition)
			end
			condition:delete()
		end
		creature:getPlayer():sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, "onTargetTile. Condition has been added.\n")
	end
	return true
end

combat:setCallback(CALLBACK_PARAM_TARGETTILE, "onTargetTile")

function onCastSpell(creature, variant)
	local target = creature:getTarget()
	if target then
		local condition = Condition(CONDITION_DAZZLED)
		condition:setParameter(CONDITION_PARAM_DELAYED, true)

		condition:addDamage(7, 1000, -(target and target:getPlayer() and 10 or 20))
		combat:setCondition(condition)
		creature:getPlayer():sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, "onCastSpell. Condition has been added.")
	end

	return combat:execute(creature, variant)
end

```
So, as I've commented in the code above. I think ``creature:getTiles()`` returning **true** when there are actually no creatures on the tile might be a minor bug... am I correct? so I can add a new issue.

@totolol123 I don't know if it is possible and if it did it would require a huge code refactor, but anyway this issue has nothing to do with this.

@EvulMastah Yep, the idea is to use the script with @djarek 's condition clearing facility (which I've also been testing with this issue).
So far, djarek's condition clearing facility has been great to use alongside with addDamage(), so I don't think it is actually needed to be moved to addDamage() and accomplish the same effect. So far I only needed to use it and the end of the script.

**Comment by diath** [comment]
@raymondtfr 
It's not a bug. Tile:getCreatures() returns an empty table when there are no creatures on a tile and empty table evaluates to true in Lua. So you can either keep your check or replace it with:

```lua
if tileCreatures and #tileCreatures ~= 0 then
```

**Comment by djarek** [comment]
@raymondtfr 
I'm having trouble understanding the point of explicitly using condition:delete() because there is no reason, unless you want to optimize memory usage (or don't trust the gc to actually run the condition finalizer).

**Comment by raymondtfr** [comment]
@diath Oh, I didn't know about that lua table thing, thanks.
I'm gonna replace my check with yours, it is better perfomance-wise.

@djarek I had to use condition:delete() because as of now, using the same condition over and over **not deleting it** at the end this is what happens:
http://pastebin.com/Lh5MSp63

If I explictly **delete** the condition at the end, it gives me the proper behavior:
http://pastebin.com/njYaezQV

As you've mentioned, does this means that the gc **is not running the condition finalizer**?

**Comment by djarek** [comment]
@raymondtfr 
This is strange, I thought that the local reference to the condition userdata was assigned a new condition on every iteration of the for loop, I'm not sure this is intended behavior.

**Comment by raymondtfr** [comment]
Well, it seems I found a better solution to this, which is to use ``onTargetCreature()``, as it returns the target whether it is on a tile or not.

```lua
function onTargetCreature(creature, target)
	local condition = Condition(CONDITION_DAZZLED)
	condition:setParameter(CONDITION_PARAM_DELAYED, true)

	local min = (creature:getLevel() * 0.01) + (creature:getMagicLevel() * 0.3) + 2
	local max = (creature:getLevel() * 0.01) + (creature:getMagicLevel() * 0.5) + 3
	local rounds = math.random(math.floor(min), math.floor(max))
	local time = math.random(10, 12) * 1000
	local damage = target:isPlayer() and 10 or 20

	condition:addDamage(rounds, time, -damage)
	target:addCondition(condition)
	return true
end

combat:setCallback(CALLBACK_PARAM_TARGETCREATURE, "onTargetCreature")

function onCastSpell(creature, variant)
	return combat:execute(creature, variant)
end
```

But now a new problem surfaced. Instead of damage messages displayed in the form (for the caster and spectators):
``A dragon loses 20 hitpoints due your attack.`` and ``A dragon loses 20 hitpoints due to an attack by CREATURE_NAME.``

It'll now display in the form:
``A dragon loses 20 hitpoints.``

If I remove ``creature:addCondition()`` it works normally. But using it is the only way (I guess) we have to bind a condition to a determined creature.

So, based on my attempts, I guess a expanded version of ``addDamage()`` could still be favorable, cause everything would be handled direcly in ``onCastSpell()``.

Anyway, if this is the best I can get now then I'll update required spells in #1635 this way and hope it is good enough to be merged.

**Comment by diath** [comment]
Try:
```lua
condition:setParam(CONDITIONATTR_OWNER, creature:getId())
```

**Comment by raymondtfr** [comment]
@diath Thanks, this param fixed that issue.

**Comment by raymondtfr** [comment]
@diath 

> This is strange, I thought that the local reference to the condition userdata was assigned a new condition on every iteration of the for loop, I'm not sure this is intended behavior.

You were right _(that code does that, but my answer was erroneous)_, I was creating a new condition object on each loop iteration. And if I didn't delete the condition at the end, that would happen.

**Comment by raymondtfr** [comment]
@marksamman @djarek I have noticed a memory leak that grows from a small to a large memory leak. This happens **only** happens if I **do not delete** the created condition at the end of the script.

The way to reproduce this is to continuously spam (rapidly or not) -- i.e. utori pox -- and just a few seconds later the leak will start (here it increases by 64 K, then it grows), and after it starts it requires a few more spams to grow and so on. And I didn't even tried monsters spells which creates many more conditions (and not getting deleted at the end) that may grow even more rapidly -- this could mean larger memory leaks in servers, imagine servers with 100+, 900+, 2k+ players and monsters.

Do I need to explicitly delete the condition? Because I have nowhere find in the sources a piece of code that deletes it, only the function **condition:delete()** in **luascript.cpp**, which implies that (we should always) the only way to delete a condition is through this condition metatable function?

**Comment by djarek** [comment]
@raymondtfr 
https://github.com/otland/forgottenserver/blob/master/src/luascript.cpp#L2438
As I've mentioned earlier, the condition:delete() function is being set as the finalizer for the lua **garbage collector**. What you're seeing here is that the garbage collector has not started running its collection cycle. IIRC the lua garbage collector doesn't do anything unless you allocate a certain % threshold of allocated memory. The problem here is that lua only sees a pointer to a *Condition* object, so from its point of view it's allocating very little memory(8 bytes per condition). Also please bear in mind that unless you clear *Condition* objects from a *Combat*, they will stay allocated as long as the *Combat* object.

**Comment by raymondtfr** [comment]
@djarek Oh, now I get it. Thanks for clarifying that to me, you were pretty clear.
