### ISSUE TITLE
Monsters's IDLE bug.

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#1834]
Monsters don't move(dance) when the player is in screen on PZ.

**Comment by mattyx14** [comment]
On PZ

**Comment by whitevo** [comment]
if monster doesn't have targetList of friendList, the onThink event wont work. Maybe that is the case

**Comment by HeavenIsLost** [comment]
On this line:
https://github.com/otland/forgottenserver/blob/master/src/monster.cpp#L1129
I have added:
`	} else if (getTimeSinceLastMove() > 1000) {
		//choose a random direction
		result = getRandomStep(getPosition(), direction);
	}`

it will make the monster do a random walk to any direction while its not idle.

**Comment by slavidodo** [comment]
@HeavenIsLost I will check it as soon as i get to a pc.

Well can someone confirm this for multi-floor as well?

**Comment by Schiffers** [comment]
@HeavenIsLost this change solve the problem with the protection zone, but if the player is trapped by monsters or walls, the monster will stay idle just attack from far

**Comment by PrinterLUA** [comment]
This issue has something releated to my PR: https://github.com/otland/forgottenserver/commit/064630baad244f986de7c53f8d751f8c4f3c655e

**Comment by slavidodo** [comment]
@PrinterLUA If you agree that, please open an issue to revert it back until you make a solution.
