### ISSUE TITLE
Ubuntu compiling

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1843]
Hi, I'm trying to compile the The Forgotten Server on Ubuntu machine for my friend, and it is giving a error on compile libpugixml-dev.

root@BBHost:/home/Enfo/sources/build# sudo apt-get install libpugixml-dev
sudo: unable to resolve host BBHost
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libpugixml-dev

**Comment by wgrriffel** [comment]
http://packages.ubuntu.com/source/trusty/pugixml
it seems all ok with packages, must be problem with your machine, since i get all fine about a mounth ago on ubuntu.

**Comment by ranisalt** [comment]
Are you are sure you are on Trusty (14.04) or higher?

**Comment by vankk** [comment]
Sorry, I did not checked the Ubuntu Version it is 12.04
