### ISSUE TITLE
Can't create market offers

### ISSUE THREAD

**Issue by Lundrial** [otland/forgottenserver#1849]
Well, you can't create offers in the market apparently.
it has a reproduction rate of 100%
basically, when you click the create offer button nothing happens, the item is not removed, the offer isn't created and the database isn't modified either.
this is happening on the main branch without modifications, I also tried using a nightlies build to check if I did something wrong with the same results.

**Comment by wgrriffel** [comment]
for me is working as expected, my build is with this commit 61b1b1f979b5299c477a93840e1ef26a3fa3365a, tho do you have deposited gold on bank account to cover fee?

**Comment by Lundrial** [comment]
nvm, I'm stupid.
tried without gold to pay the fee.

**Comment by wgrriffel** [comment]
@marksamman though there is no error message like you do not have enough gold for fee, it just doesnt create the offer, suppose to act like that?
