### ISSUE TITLE
item:transform bug while transforming something in your backpack

### ISSUE THREAD

**Issue by EvilHero90** [otland/forgottenserver#1850]
### Title already pretty much explains the issue
If you put an item in your backpack and do an "onUse" event to transform the item into a leverl (id 1945) as an example, then the lever will be in your backpack instead on the ground.

### Steps to reproduce
1. put an item in your backpack and then transform this item into a lever (id 1945) with an onUse script as an example.

### Expected behaviour

item should be dropped to the ground as it's an item which cannot be picked up

### Actual behaviour

item resides in the backpack it can be used and cannot be erased out of the backpack

## Screenshots

![bug1](https://cloud.githubusercontent.com/assets/3682541/16569784/d652482a-423a-11e6-8307-de7cd60231a8.png)
![bug2](https://cloud.githubusercontent.com/assets/3682541/16569783/d65198d0-423a-11e6-9b8e-65e1774e7904.png)

**Comment by ranisalt** [comment]
I think it can be tackled by preventing immovable items to be spawned not on ground.

**Comment by Schiffers** [comment]
wtf, why is a bug? if you do wrong scripts it will be problematic, then, if you use correct code types to not get this problems, this is my little opinion

**Comment by TheSumm** [comment]
I would rather keep this as a feature than prevent it.
If you want the item to appear on the ground, you can achieve that using Item.moveTo.

**Comment by ranisalt** [comment]
+1 to the statements above. Don't blame the server for your bad code.

**Comment by marksamman** [comment]
Closing this as the consensus is that this is bad user code and not a flaw in the engine.
