### ISSUE TITLE
About Game.createItem

### ISSUE THREAD

**Issue by Schiffers** [otland/forgottenserver#1859]
Question...
Is possible we made Game.createItem(id, count) for values higher than 100 ?

**Comment by marksamman** [comment]
#1856

**Comment by andersonfaaria** [comment]
@marksamman there's any way to put values higher than 100 for doCreateItemEx? I'm tired of having to make it through Lua

**Comment by ranisalt** [comment]
The way I see it, the server should not care if the user wants to create multiple stacks of items. We should limit to 100 and, if you want multiple stacks, create them one by one. This is much more foolproof and standard.

**Comment by marksamman** [comment]
I feel the same way. We're just making the API more complex by making a single function able to return 3 different types (nil, table, or userdata), but I'm leaning towards merging #1856 because we've already implemented this behavior for Player.addItem. doCreateItemEx is unlikely to be changed though, it will be deprecated eventually (and implemented in compat.lua).

**Comment by ranisalt** [comment]
Both changes (#1856 or changing Player.addItem) would result in an API modification and I think this should be on a major version update (to 2.0).

**Comment by gugahoa** [comment]
As it's backward compatible, I don't feel that it is necessary to implement only on a major version update.
But +1 to not add this on the TFS and let the server scriptwriter handle that

**Comment by Schiffers** [comment]
Hum, some guys give me some feedback about the question, thanks guys, but how I can implement it on my forked tfs ?

**Comment by ranisalt** [comment]
@Schiffers you can merge this PR: https://github.com/otland/forgottenserver/pull/1856

**Comment by Schiffers** [comment]
@ranisalt I already merge it, and won't work this for exemple:
Game.createItem(2160, 300, toPosition)
numbers highter than 100,  the function will create 100.

**Comment by joseluis2g** [comment]
@Schiffers Working here

**Comment by Schiffers** [comment]
@joseluis2g I'll compile it again,  :) thanks for the feed
