### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1865]
Helloo today my server was crashed and I got this log:

(gdb) bt full
#0  0x00000000004249cc in Item::isRemoved (this=<optimized out>) at item.h:753
No locals.
#1  0x00000000004aa72a in Item::canDecay (this=this@entry=0x7fb18b41dac0) at item.cpp:1545
        it = <optimized out>
#2  0x000000000046b706 in Game::checkDecay (this=0x835220 <g_game>) at game.cpp:4581
        item = 0x7fb18b41dac0
        duration = <optimized out>
        bucket = 3
        it =
        end =
#3  0x000000000059ffa8 in operator() (this=0x7fb1530dee90) at /usr/include/c++/4.8/functional:2471
No locals.
#4  operator() (this=0x7fb1530dee80) at tasks.h:42
No locals.
#5  Dispatcher::threadMain (this=0x835940 <g_dispatcher>) at tasks.cpp:50
        task = 0x7fb1530dee80
        taskLockUnique = {_M_device = 0x835958 <g_dispatcher+24>, _M_owns = false}
#6  0x00007fb1a1beca60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x00007fb1a0c27184 in start_thread (arg=0x7fb1a0c1e700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7fb1a0c1e700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140400883001088, 7725863218579347614, 0, 0, 140400883001792, 140400883001088, -7758428741831911266, -7758428729881683810},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
---Type <return> to continue, or q <return> to quit---
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007fb1a135437d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

game.cpp http://pastebin.com/CstPTHks
item.h http://pastebin.com/rjjWmEtD
item.cpp http://pastebin.com/UrgtuBBX

I do not know if it was any change over time , but it seems not , someone to confirm that it is a bug?

**Comment by marksamman** [comment]
Please don't report crashes if you've made changes to your source code unless you can tell us how to reproduce the crash and it's reproducible with the source code from this repository.
