### ISSUE TITLE
Amulets limited to 100 charges on reward system

### ISSUE THREAD

**Issue by guiismiti** [otland/forgottenserver#1866]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
    support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository
### Steps to reproduce (include any configuration/script required to reproduce)
1. I checked "reproducible without changes" since I think it may happen to depots aswell;
2. In the lua loot script, need to set the count of each item with charges (amulet, ring, enchanted weapon) as the charges it should have;
3. Kill monsters to send an item with more than 100 charges to the player's reward chest/depot.
### Expected behaviour

The items sent to the reward chest/depot should have the correct charges.
### Actual behaviour

Items are limited to 100 charges (item count can not be higher than 100).
Note: items are only limited when sending it to a reward chest / depot - when moving them to a corpse (which is the case of the regular loot system), the charges are set correctly.

This is happening because of `luaContainerAddItem(lua_State* L)`
This function is in luascript.cpp
The current line 6459 sets the max count to 100 (so we don't get higher stacks of stackable items):

`Item* item = Item::CreateItem(itemId, std::min<uint32_t>(subType, 100));`

I have fixed it in my code so it checks the itemId and will set the max count as 750 for the itemIds of amulets (and might ring). I set it as 750 since it is the highest charge number for original amulets.

I guess that the ideal (or correct) way of fixing this is to check attribute "charges" in items.xml; if attribute is not set, set max count as 100; if yes, set max count to "charges". I did not do it this way because I didn't have enough time, given that I don't know C++

**Comment by wgrriffel** [comment]
@guiismiti i think you should post this issue in the pull request since it is not a part of sources of repository.

**Comment by ranisalt** [comment]
> A reward chest system is required;

Keep in mind:

> This issue is reproducible without changes to the code in this repository

**Comment by guiismiti** [comment]
@ranisalt I edited the text more than 10 times, and I let that pass. The reward chest system is not required.

**Comment by Mkalo** [comment]
This may be considered a bug, but you can fix it by doing this:
`		container:addItemEx(Game.createItem(2200, 150))`
To fix this in container:addItem you can just look at Game.createItem code:
`if (it.stackable) {
		count = std::min<uint16_t>(count, 100);
}`

So we do the same with container:addItem:
`const ItemType& it = Item::items[itemId];
Item* item = Item::CreateItem(itemId, it.stackable ? std::min<uint32_t>(subType, 100) : subType);`

**Comment by guiismiti** [comment]
@Mkalo Thank you, it worked fine.

**Comment by Schiffers** [comment]
@Mkalo this fix create 250 UHP for exemple, buyed in the store...
inbox:addItem(itemType:getId(), count, INDEX_WHEREEVER, FLAG_NOLIMIT)
count = 250, coded before, then it create 250 UHP in one stack of items
[img]http://i.imgur.com/uY4VulZ.png[/img]
