### ISSUE TITLE
Missing a tilestate?

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1868]
Why there is no [TILESTATE_HOUSE](https://github.com/otland/forgottenserver/blob/29f2a2239bcdce6c99d9d6a138c1f14b5b00a46a/src/tile.h#L41) on title flags? How we can suppost to check a house?

Regards,
vankk.

**Comment by ranisalt** [comment]
dynamic_cast to HouseTile?

**Comment by vankk** [comment]
I don't think that dynamic_cast to HouseTile can handle [with this](https://github.com/otland/forgottenserver/blob/master/src/map.cpp#L1000).

**Comment by ranisalt** [comment]
Why not?

```cpp
if (!tile || tile->hasFlag(TILESTATE_PROTECTIONZONE) || dynamic_cast<HouseTile*>(tile)) {
    continue;
}
```

Will certainly do the trick, if what you want is not to clean houses and you can not set protection zone on them.

**Comment by darkjav** [comment]
@ranisalt I try do it and not working, still without clean pz zone...

**Comment by ranisalt** [comment]
Yes, it ignores PZ. Use `if (!tile || dynamic_cast<HouseTile*>(tile)) {` if you want to clean PZ too.
