### ISSUE TITLE
About banishment

### ISSUE THREAD

**Issue by Codex-NG** [otland/forgottenserver#1872]
Can you people stop banning me on otland, i am running out of names to create accounts with ;) and I wouldn't have to create new accounts if you didn't ban my main account for a year.. 

A year for christs sakes.. i could understand if I was acting up on these alt accounts but I'm not, I am posting code.. or providing support for your useless brain dead members, I wouldn't have to do this if the staff/support team had half a brain cell and only got their position because they were runner up in the circle jerk contest.. (yeah Summ this is directed at you)

**Comment by LordVissie** [comment]
HAHA

**Comment by Codex-NG** [comment]
I don't know March or May or 2017

**Comment by Zbizu** [comment]
possible fix: ban codex from repo  :thumbsup:

**Comment by cbrm** [comment]
Find other forum.

**Comment by LordVissie** [comment]
> Find other forum.

@Codex-NG The forum from [camel-ots](http://camel-ots.no-ip.org/) is always open for you m9.

**Comment by Codex-NG** [comment]
@cbrm if I find another forum then you will loose your position on otland.. because like Summ you don't do anything but ban people... I almost never see your lazy ass in support/request... I thought you died...

**Comment by Codex-NG** [comment]
@Zbizu your just gay... actually from your real life pic i can't tell if you're a guy or a girl... either way you are fucking ugly!
I wouldn't fuck you with @cbrm's tiny dick and @LordVisse pushing!

**Comment by gugahoa** [comment]
Everyone, please just report this clown.
