### ISSUE TITLE
Error MySQL at phpMyAdmin!

### ISSUE THREAD

**Issue by Yvespav** [otland/forgottenserver#1873]
Hello.
When I import the Schema.sql in phpMyAdmin happens this error:

(translate: "MySQL returned no registration.")

![image](https://cloud.githubusercontent.com/assets/20978257/17604749/8c0db17a-5fed-11e6-8752-07d7f954d62d.png)

I'm following this tutorial, but for the other guy did not.
https://www.youtube.com/watch?v=DDbUajE33yg

What can I do?

**Comment by EvulMastah** [comment]
Be happy, it's a success (info) message.

**Comment by Yvespav** [comment]
It is normal then have nothing? I'll put next? Sorry, I do not understand anything.

**Comment by Yvespav** [comment]
Haha well. Thx bro!
