### ISSUE TITLE
StoreTrash feature for fast cleaning

### ISSUE THREAD

**Issue by mattyx14** [otland/forgottenserver#1885]
Is possible add this feature for fast map cleaning the current demore much time on clean:
https://github.com/DSpeichert/tfs/blob/07c2869337a1c544db78f081dc1e64153bc6b51f/config.lua.dist#L188
https://github.com/DSpeichert/tfs/blob/07c2869337a1c544db78f081dc1e64153bc6b51f/game.cpp#L341

and this feature on 0.3.7 make the clean more fast

**Comment by marksamman** [comment]
We've already made major optimizations to the map clean code compared to how it worked in 0.3 without the "store trash" config on, with zero memory overhead. So I don't think this is needed.

**Comment by mattyx14** [comment]
ok :+1:

**Comment by marksamman** [comment]
You didn't have to close the issue. I was just sharing my personal opinion, others may disagree and if a discussion shows that it still makes a huge difference we should still consider optimizing it.
