### ISSUE TITLE
About pull requests

### ISSUE THREAD

**Issue by Codex-NG** [otland/forgottenserver#1886]
I can't seem to put a pull request in, it keeps going to some comparison window... 

So I was wondering if pull requests were just for bug fixes or changing the overall structure of the game, if bug fixes aren't the only reason for a pull request then I might be interested in sharing some new "enhancements" I've built which will eventually start to make TFS less tibia like.

**Comment by gugahoa** [comment]
This is a good question, I was going to answer saying that PR should be about improving the engine itself, but I can't seem to think of good boundaries.

@marksamman what do you say about writing a "Contribution Guideline" and putting it on the README.md?

@Codex-NG while we don't know what can be viewed as a PR within the scope of the TFS for sure, you could read the roadmap and issues to see if something you have fits them.

**Comment by ranisalt** [comment]
I think if you ever want to change the engine behavior, make it optional. I feel TFS is an ever evolving project and will never get "done", just better.
