### ISSUE TITLE
Using cmake to generate Visual Studio files

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#1904]
I'm not a Windows user, but I know CMake can generate build files for Visual Studio too, yet we still maintain and version build files for vc14 on the repository. Couldn't they be replaced with what CMake generates?

I can not test it since I don't have neither Windows nor VS license.

**Comment by marksamman** [comment]
AFAIK Windows doesn't have standard paths for libraries/includes, so I'm not sure how CMake would find the dependencies (perhaps it could use the environment variable we set for the SDK?), you would also need to install CMake which adds more steps to the compiling on Windows tutorial. You don't need a VS license btw, the community edition is free.

Bottomline is that Windows is a pain to compile software on, we shouldn't do anything to make the experience any worse than it already is.

**Comment by ranisalt** [comment]
I just read that CMake on Windows is bad that you have to manually specify where it should look for files, pretty much killing the purpose of `find_package`. So this is probably a no go for now.
