### ISSUE TITLE
Monster walk through bug

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1918]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
    support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository
### Steps to reproduce (include any configuration/script required to reproduce)
1. Log into a player, or summon a monster
2. Create (with /m) 10 rats. 2 Will start random step.
3. Create a monster that can push (Cyclops/Dragon)
### Expected behaviour

I'm not sure as I don't play official Tibia. Something along the line of pushing the weaker monster out of the way or side stepping until there's room is what I think is acceptable in this case.
### Actual behaviour

Stronger monster will try to walk through weaker monster, deleting him (weaker monster) in the process

**Comment by andersonfaaria** [comment]
I can confirm that, but in my version of this repository the weaker monster don't get deleted, they just stick both in the same sqm.
![sem titulo](https://cloud.githubusercontent.com/assets/8560144/18419883/ba5c24e2-783b-11e6-9f9b-e5b8a776e09d.png)

**Comment by vankk** [comment]
I can confirm that too.

**Comment by ranisalt** [comment]
In Tibia stronger monsters crush weaker monsters if there is no room to reach the target. Not all monsters do that, though. It's actually used as strategy to kill bosses that summon a lot (such as Ghazbaran's deathslicers), limiting space around the blocker so that the Ghazbaran crushes the deathslicers to get through.

**Comment by gugahoa** [comment]
In Monster::pushCreatures, any monster that can push, will have that behavior. Can someone confirm if any monster has that behavior or only really strong monsters?

**Comment by TechrlzGit** [comment]
Confirmed that too.

**Comment by wgrriffel** [comment]
@ranisalt you're mistaken, monsters such as minotaur guard crush minotaurs, not beeing a boss, this behaviour occurs even if there is enough room, as minotaur has a lower speed it kills minotaurs that are in his path, i think this behaviour is more linked with game rpg instead of a boss strategy.

**Comment by peonso** [comment]
Fix for that here https://github.com/otland/forgottenserver/issues/922#issuecomment-246080775

**Comment by ranisalt** [comment]
@wgrriffel I meant players use this stuff to kill bosses, not that it's monster behavior.

**Comment by andersonfaaria** [comment]
@ranisalt @wgrriffel it would be really awesome if the monster really turned in the minion to get space instead of just "poffing" it without even leave a body. but then again we would have to check if the monster is a ranged or close combat one.

**Comment by ranisalt** [comment]
As I said, we can just use logic from moving crates. It already does the job of moving if possible, else crushing.
