### ISSUE TITLE
Missing Glooth Engineer Outfits

### ISSUE THREAD

**Issue by kuzyn1** [otland/forgottenserver#1919]
Hey.
Why Glooth Engineer Outfit is missing? Outfit is in Tibia 10.5, even if I add this:

`<outfit type="0" looktype="610" name="Glooth Engineer" premium="yes" unlocked="no" enabled="yes" />`

the outfit is missing.

**Comment by Kamenuvol** [comment]
I've tested adding this line and it works. Also, the type is wrong.
