### ISSUE TITLE
[delete]

### ISSUE THREAD

**Issue by urban119** [otland/forgottenserver#1924]

**Comment by andersonfaaria** [comment]
you must put something sparkling below so the use will be on the item with the actionid.

**Comment by urban119** [comment]
In tfs 8.X and 9.X the sparkling block item, but if the item have set actionId, You can be used... now no.
I have second ask.. becouse when I got some items below spark and using "browse field" i can put out items below sparking... (its wrong, becouse before sparking blocking all items on the floor).
