### ISSUE TITLE
Question about serialization/unserialization

### ISSUE THREAD

**Issue by w19787** [otland/forgottenserver#1942]
just wonder any reason that forgotten server is not using protobuf or boost serialization solution. it seems to me a lot of extra work to create serialize/unserialze for each object.

can someone show me some thoughts? thanks in advance.

**Comment by gugahoa** [comment]
One of the items on the roadmap is moving away from boost and other dependencies, it maybe because of that. 
Is those solution a lot better than the one being used?

**Comment by kornholi** [comment]
What objects are you talking about? TFS is also older than protobuf.

**Comment by w19787** [comment]
from my personal view, the current serialization/unserialization of item/items object is not easy to maintain. [i am new to this project, likely i am wrong]

it seems that more and more game design houses intend to use protobuf. Some analysis show it is very effective.

**Comment by DerzeGuilherme** [comment]
It is difficult to change to a more efficient model. But it's a valid idea.

**Comment by w19787** [comment]
@gugahoa why are we planning to move away from boost? what is plan for networking framework?
