### ISSUE TITLE
Crash with gdb tfs 1.2 in ubuntu 14

### ISSUE THREAD

**Issue by eltom** [otland/forgottenserver#1947]
### Steps to reproduce (include any configuration/script required to reproduce)
1. `Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x732b2ec4a700 (LWP 11894)]
0x000000000080e746 in Game::playerMoveUpContainer(unsigned int, unsigned char)
    ()
(gdb) bt full
#0  0x000000000080e746 in Game::playerMoveUpContainer(unsigned int, unsigned cha                                                                                                 r) ()
No symbol table info available.
#1  0x00000000009a094c in void std::_Mem_fn<void (Game::*)(unsigned int, unsigne                                                                                                 d char)>::operator()<unsigned int&, unsigned char&, void>(Game*, unsigned int&,                                                                                                  unsigned char&) const ()
No symbol table info available.
#2  0x000000000099e4fc in void std::_Bind<std::_Mem_fn<void (Game::*)(unsigned i                                                                                                 nt, unsigned char)> (Game*, unsigned int, unsigned char)>::__call<void, , 0ul, 1                                                                                                 ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) ()
No symbol table info available.
#3  0x000000000099b4b0 in void std::_Bind<std::_Mem_fn<void (Game::*)(unsigned i                                                                                                 nt, unsigned char)> (Game*, unsigned int, unsigned char)>::operator()<, void>()
    ()
No symbol table info available.
#4  0x0000000000994b20 in std::_Function_handler<void (), std::_Bind<std::_Mem_f                                                                                                 n<void (Game::*)(unsigned int, unsigned char)> (Game*, unsigned int, unsigned ch                                                                                                 ar)> >::_M_invoke(std::_Any_data const&) ()
No symbol table info available. 
#5  0x00000000009cd746 in std::function<void ()>::operator()() const ()
No symbol table info available.
#6  0x00000000009cd630 in Task::operator()() ()`
2. `
#7  0x00000000009cced8 in Dispatcher::threadMain() ()
No symbol table info available.
#8  0x000000000094bb1d in void std::_Mem_fn<void (Dispatcher::*)()>::operator()<, void>(Dispatcher*) const ()
No symbol table info available.
#9  0x000000000094b58b in void std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
No symbol table info available.
#10 0x000000000094aee7 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::operator()() ()
No symbol table info available.
#11 0x000000000094a8ce in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)> >::_M_run() ()
No symbol table info available.
#12 0x0000732b2fe96a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#13 0x0000732b300f1184 in start_thread (arg=0x732b2ec4a700)
    at pthread_create.c:312
        __res = <optimised out>
        pd = 0x732b2ec4a700
        now = <optimised out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {126629305427712,
                7890120105551976031, 1, 0, 126629305428416, 126629305427712,`

The server is crash when this bug appear.

I use tfs 1.2 and when i compile, compile server without error, but sometimes crash the server for this bug.

**Comment by marksamman** [comment]
Use the full issue template, and compile your server with debug symbols, and then open a new issue when you have a stack trace from a debug build.

**Comment by eltom** [comment]
@marksamman  i have the same bug..
