### ISSUE TITLE
---------

### ISSUE THREAD

**Issue by A-Syntax** [otland/forgottenserver#1949]
---------------------

**Comment by A-Syntax** [comment]
I will most likely do the same for vocations, & stages, also any other files which load data through xml

**Comment by marksamman** [comment]
Can you provide an example of where Lua would be better than XML in the context of items.xml or vocations.xml? Introducing scripting logic into the files for no good reason just makes it harder for beginners to understand how to edit the file. Why confuse them with two different ways to achieve the same thing when one is sufficient?

**Comment by A-Syntax** [comment]
Well that is why it is optional, I didn't replace the option to load xml, this is mainly for those who are scripters and want direct access to these files.

**Comment by gugahoa** [comment]
Lua would be really useful for stages, quests, mounts and outfits. But for items I fail to see a benefit of using Lua.

For vocations, the benefit would be for custom OTs, which is a minority and I don't know if TFS has them in mind

**Comment by ranisalt** [comment]
There is #1642 moving stages to Lua.

**Comment by A-Syntax** [comment]
What i made is similar 

	-- if set to true the server will use stage values instead of config.lua values
	enabled = true
	stages = {
		{ minlevel = 1, maxlevel = 8, multiplier= 7 },
		{ minlevel = 9, maxlevel = 20, multiplier = 6 },
		{ minlevel = 21, maxlevel = 50, multiplier = 5 },
		{ minlevel = 51, maxlevel = 100, multiplier = 4 },
		{ minlevel = 101, multiplier = 5 }
	}

**Comment by A-Syntax** [comment]
static struct a {
		const char* name;
		int type;
	}stageL[] = {
		{ "minlevel", LUA_TNUMBER },
		{ "maxlevel", LUA_TNUMBER },
		{ "multiplier", LUA_TNUMBER },
		{ NULL, 0}
	};


	bool Game::loadExperienceStages()
	{
		// this will give the option to load experience stages as xml or lua
		bool useXML = g_config.getBoolean(ConfigManager::USE_XML);
		if (!useXML) {
			lua_State *L = luaL_newstate();
			std::string str;
			if (!L) {
				throw std::runtime_error("Failed to allocate memory in stages");
			}

			luaL_openlibs(L);

			if (luaL_dofile(L, "data/LUA/stages.lua")) {
				std::cout << "[Error - Stages] " << lua_tostring(L, -1) << std::endl;
				lua_close(L);
				return false;
			}

			lua_getglobal(L, "enabled"); // -2
			lua_getglobal(L, "stages"); // -1

			if (lua_isboolean(L, -2)) { // should be enabled in the stack
				stagesEnabled = g_lua.getBoolean(L, -2); // the value of enabled
				if (stagesEnabled) { 
					if (lua_istable(L, -1)) {
						uint32_t minLevel, maxLevel, multiplier;
						for (int i = 1; ; i++) { // start outter for loop
							lua_rawgeti(L, -1, i);
							if (lua_isnil(L, -1)) {
								lua_pop(L, 1);
								break;
							}
							for (int fields = 0; stageL[fields].name != NULL; fields++) { // start inner for loop
								lua_getfield(L, -1, stageL[fields].name);
								if (lua_isnumber(L, -1)) { // start of isnumber
									str = stageL[fields].name;
									if (str == "minlevel") {
										minLevel = g_lua.getNumber<uint32_t>(L, 1);
									}else {
										minLevel = 1;
									}
									if (str == "maxlevel") {
										maxLevel = g_lua.getNumber <uint32_t>(L, 1);
									}else {
										maxLevel = 0;
										lastStageLevel = minLevel;
										useLastStageLevel = true;
									}
									if (str == "multiplier") {
										multiplier = g_lua.getNumber <uint32_t>(L, 1);
									}else {
										multiplier = 1;
									}
									if (useLastStageLevel) {
										stages[lastStageLevel] = multiplier;
									}
									else {
										for (uint32_t i = minLevel; i <= maxLevel; ++i) {
											stages[i] = multiplier;
										}
									}
									//std::cout << str << "\n";
								} // end of isnumber
								lua_pop(L, 1);
							} // end inner loop
							lua_pop(L, 1);
						}// end outter loop
					}
				}
			}
			lua_close(L);
			return true;
		}
		else {
			pugi::xml_document doc;
			pugi::xml_parse_result result = doc.load_file("data/XML/stages.xml");
			if (!result) {
				printXMLError("Error - Game::loadExperienceStages", "data/XML/stages.xml", result);
				return false;
			}

			for (auto stageNode : doc.child("stages").children()) {
				if (strcasecmp(stageNode.name(), "config") == 0) {
					stagesEnabled = stageNode.attribute("enabled").as_bool();
				}
				else {
					uint32_t minLevel, maxLevel, multiplier;

					pugi::xml_attribute minLevelAttribute = stageNode.attribute("minlevel");
					if (minLevelAttribute) {
						minLevel = pugi::cast<uint32_t>(minLevelAttribute.value());
					}
					else {
						minLevel = 1;
					}

					pugi::xml_attribute maxLevelAttribute = stageNode.attribute("maxlevel");
					if (maxLevelAttribute) {
						maxLevel = pugi::cast<uint32_t>(maxLevelAttribute.value());
					}
					else {
						maxLevel = 0;
						lastStageLevel = minLevel;
						useLastStageLevel = true;
					}

					pugi::xml_attribute multiplierAttribute = stageNode.attribute("multiplier");
					if (multiplierAttribute) {
						multiplier = pugi::cast<uint32_t>(multiplierAttribute.value());
					}
					else {
						multiplier = 1;
					}

					if (useLastStageLevel) {
						stages[lastStageLevel] = multiplier;
					}
					else {
						for (uint32_t i = minLevel; i <= maxLevel; ++i) {
							stages[i] = multiplier;
						}
					}
				}
			}
			return true;
		}
	}

**Comment by A-Syntax** [comment]
Still learning the lua c api :)

**Comment by A-Syntax** [comment]
@gugahoa 
I am happy that you fail to see the benefit of it being really useful, I on the other hand found it very useful =) 
@marksamman 
I think people are confused with or without this change, this change allows people the freedom to build absolutely anything they want, right now xml is too restrictive, you might as well store vocations, stages, items and anything else that uses xml as a text document because that is how useful xml is to a game server.

I know most of you are much more advanced in c++ than me, but the changes I have made to the sources have made things way easier, there is a ton of things missing from TFS that should be there which aren't. I was fortunate enough to have add new features which either did exist at one point or never existed in the 1st place.

Don't get me wrong, I love this project, its just that it could be so much better than what it is now.

**Comment by ranisalt** [comment]
Why destroying the issue?
