### ISSUE TITLE
Should this be using some free compilers instead of the Visual Studio ones?

### ISSUE THREAD

**Issue by Obsdark** [otland/forgottenserver#1951]
When i saw the tutorials about how to compile this, i always think than, with every year than happends, the IDE's and stuff the newbies can use to compile this are making themselfs older and older, and harder and harder to get.

Also, visual studio compilers and proyect-types tend to change a lot over the years, because of that maybie we must try to make some kind of tutorial user-friendly with easy-to-get software doesn't?

I'm actualy trying to compile this source in NetBeans 8.1, not sure if i'm gonna made it, but it would be cool if somebody do it in this or eclipse or something like that, so to avoid the microsoft-dependance for compilation, and open this to more and more people who want to use it.

Asuming bring on more people is an issue, of course, for the develop and continuation of the proyect and OTservers. 

Sorry if this wasn't the right place to put this, but i guess i must try.

**Comment by kornholi** [comment]
Why would you want to use NetBeans when Visual Studio is free and better? On Linux you can use whatever you want that supports CMake.

**Comment by Obsdark** [comment]
Because there is a tut for compile this source with Visual Studio 2013 on OTLand, and there is another one who vagely mention the use of Visual Studio 2015 here, what i'm trying to say is than is better to avoid multiple programs with several differences to make tutorials to compile something for learning and facility purposes.

Ok granted, maybie not with netbeans, maybie a tutorial with Eclipse?, i don't know, not an expert in c++ specificaly but i know a good tut with an IDE's aplication with a very long lifetime without any significant changes but with apropiate mantainance can open doors to new people to compile it easier, and because of that, give them the feel so to not worry to break it, giving them more freedom in order to experiment with it.

I'm also open to alternative  solutions.

**Comment by A-Syntax** [comment]
When I initially tried to compile with Visual Studios 2015 I had issues as well, even some of the files such as the version of boost suggested did not work with the compiling instructions. Eventually through trial and error I got everything up and running. 

I think it might be a good idea to update the tutorials every time you update the distribution with an explicit step by step.

**Comment by ranisalt** [comment]
> Why would you want to use NetBeans when Visual Studio is free and better?

I don't use any, but because NB is open source, maybe?

**Comment by kornholi** [comment]
If you have strong opinions about IDEs you should know how to set them up.

**Comment by Obsdark** [comment]
Not really "strong opinions" about IDE's, if that was the case, i will be speaking bad about VS and good about NB, but the thing is, VS is good, i use it in my work in a daily basis, (i program in C# there btw) but the thing with this is, the versions are harder and harder to get without virus, that's the hole point of this suggestion, if the compilation process is teached with easier-to-obtain software, probably it gonna be also easier to bring new people to modify it and we are gonna have a time-probe tutorial to teach the people how to compile it without the need of ever do a tut again, or fixing just little tiny bits each certain amount of years.

**Comment by marksamman** [comment]
Why is it harder to get VS? It's free, and our tutorial links to the official webpage (https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows), so I don't see why it would be easier to get a virus by trying to download VS than by trying to download a different IDE.

**Comment by wgrriffel** [comment]
@Obsdark VS is free for individual.

**Comment by A-Syntax** [comment]
Yea, initially it tells you, you have 30 days trial but that is only because they want you to sign up for an account which cost absolutely nothing. After the 30 days they lock the software until you sign in but after you sign in you don't even need to be online to use the compiler.

All you are doing is registering the program with Microsoft and thats it, no hidden fees or anything.

**Comment by w19787** [comment]
Xcode is working very well on Mac :)

**Comment by ReyAleman** [comment]
[VS Community](https://www.visualstudio.com/vs/community/), it's free.

**Comment by ranisalt** [comment]
I thought the discussion was around free as in freedom, not free of charge.

I'm pretty sure you can generate project files for Codeblocks and Eclipse on CMake so you can use those on Windows.

**Comment by wgrriffel** [comment]
@ranisalt it will not make it with this repo cmake.txt just because it will not find dependencies on windows, it is writen for unix-like systems, can generate VS project also if fixed for it.
