### ISSUE TITLE
[Question] Player::canSee logic

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1955]
Is there any reason for the logic behind if a player can see another creature to be inside ProtocolGame?
Correct me if I'm wrong, but I think it would be more intuitive for it to be inside Player instead

**Comment by A-Syntax** [comment]
cansee is a virtual method, so its shared amongst many different classes, creature, npc, player, monster protocolgame just happens to have 2 overloads one of which accepts const pointer to creature which means creature can be anyone of creature's children.

So why would it make more sense to define it in player?

**Comment by djarek** [comment]
@gugahoa
Yeah, you're absolutely right, ProtocolGame should only contain code related to game protocol (de)serialization.
