### ISSUE TITLE
case 0xF2: /* rule violation report */ break;

### ISSUE THREAD

**Issue by kito2** [otland/forgottenserver#1958]
Rule Violation (Report Bot/Macro) isn't referencing the report function.

**Comment by vankk** [comment]
I can't think of Rule Violation being a useful thing for us (OT).

**Comment by kito2** [comment]
Depends on your config and setup.

**Comment by Milice** [comment]
Now, i know this comment is not very constructive but i think if you could actually make good use of this function then you should have the knowledge to actually code it yourself aswell. I might look in to this soon and if i get somewhere with it i might post a pull request.

**Comment by kito2** [comment]
I would like to try, but c++ is rocket science for me. Hahah

**Comment by marksamman** [comment]
There isn't any rule violation report function to reference, so this is not a bug, just simply something that hasn't been implemented yet and the comment is there to indicate what kind of packet it is. If you'd like to give it a shot, please open a pull request.
