### ISSUE TITLE
Question: couple questions about server code

### ISSUE THREAD

**Issue by w19787** [otland/forgottenserver#1959]
Dear,

```
  i have couple questions about the server solution. if you can provide me some thoughts will be deeply appreciated!!
```
1. how can we make sure the quality of the server code? do we plan to develop unit test cases in future? what is the framework will be used?
2. in one of dicussion thread, i was told that this project will plan to remove the boost and other dependencies. Is this true? boost seems to be a solid soluiton, why do we plan to replace it?
3. The code of message exchange between server and client is using raw number instead of enum value. it is not helpful to read and maintain. is it any reason for this?

**Comment by wgrriffel** [comment]
The only reason to drop boost from dependencies is that because is an additional step when using VS, also it is not been used that much since mutex, thread and shared_ptr have been added to STL, i think it will be replaced by STL after [c++17](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/n4612.pdf).

**Comment by w19787** [comment]
how about boost asio? any plan to replace with other networking? i am not using VS, so i am fine with boost :)

**Comment by wgrriffel** [comment]
take a look at #1759

**Comment by ranisalt** [comment]
@w19787 ASIO can be used standalone, without depending on the entire boost library, but we still have a dependency on a lockfree stack and boost provides a good one, and there's not really much options out there.

As for 1, it would be very nice to have at least some regression tests to assure new features do not introduce bugs to old ones. I suggest gtest as it's easily integrable with cmake (example: https://github.com/ranisalt/hoist)

**Comment by w19787** [comment]
thanks for all replies.  i don't have big picture of this project, but would like to add couple suggestions:

1. it will be very nice to add unit test framework
2. it might be good to use google protobuf for serializaiton/unserialization
3. ORM which could make our code base more clean
4. log system. boost seems to be a solid log system.

if you have different opinon, will apprieciated if you share it. it will help me to learn!!

**Comment by ranisalt** [comment]
> ORM which could make our code base more clean

There's odb which seems great but would require a huge refactoring. I could do it, if wanted.

**Comment by w19787** [comment]
Personal point of view, i like ORM. need inputs from project owners to plan whether this could be one of project road map.
