### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1968]
Hello, when two or more monsters die on same sqm, we can't open the first corpse, only with browser field or if wait the corpse decay to another..

**Comment by wgrriffel** [comment]
already reported at #1851

**Comment by andersonfaaria** [comment]
@ranisalt the problem is in tile.cpp, exactly in this function
 Item* Tile::getUseItem() const

**Comment by andersonfaaria** [comment]
I don't know/understand the origin of the bug but it's something related to forceUse. If two creatures dies in the same sqm you can only open the first corpse (the higher one) when the second one decays the first time.. if you try to open the first (higher) it will open the second (lowest). I noticed it a long time ago but not using two corpses, instead I've tested it with a torch and a recent corpse. If a creature dies and you throw a torch over the body and clicks to light the torch the corpse will be opened. If a creature dies above a torch and you try to open the loot it will lit the torch.

**Comment by degolaot** [comment]
@ranisalt  as andersonfaaria said

**Comment by ranisalt** [comment]
You can add a breakpoint to that function and debug line by line to see which line has unproper behavior.
