### ISSUE TITLE
Question about PLAYERINFO_MAXHEALTH

### ISSUE THREAD

**Issue by A-Syntax** [otland/forgottenserver#1979]
Just a quick question, why do we use `player->getPlayerInfo(PLAYERINFO_MAXHEALTH)` in 
`void ProtocolGame::AddPlayerStats(NetworkMessage& msg)` instead of `player->getMaxHealth()`?

Is there any difference between the 2 and how so?

**Comment by A-Syntax** [comment]
I was messing with `ProtocolGame::AddPlayerStats`, but decided to put it back the way it was because its late and I can't think straight at the moment :p

**Comment by ninjalulz** [comment]
I don't think there is any reason behind it (in fact, it has been used for several years already), but I think it should be changed to getMaxHealth as it's frequently used around the codebase, and not _getPlayerInfo(PLAYERINFO_MAXHEALTH)_. This applies to _getPlayerInfo(PLAYERINFO_MAXMANA)_ as well.

**Comment by ranisalt** [comment]
My bet: legacy
