### ISSUE TITLE
Critical Damage Monsters

### ISSUE THREAD

**Issue by yoiker** [otland/forgottenserver#1981]
Just a quick question, why the critical damage recently used on servers that go rolling down there using official Tibia, the only critical hits it creatures that suit you and should be critical for all creatures, is there any way to fix that?. As I said the only damage critical strikes the monster that wants to do the test with 8 creatures and not all receive the impact of critical servers at least I downloaded that happens and let me know how to fix it >.<, please.

**Comment by marksamman** [comment]
I can't make any sense of this.
