### ISSUE TITLE
Get Item Description Attribute

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1983]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
`print(item:getAttribute(ITEM_ATTRIBUTE_DESCRIPTION))`

### Expected behaviour
Should print item description. E.g Magic Sword id 2400, description = "It's the Sword of Valor."

### Actual behaviour
Print nothing, but when you set description to the item, it replace the old one and then it prints the text.

### Environment
TFS 1.2

**Comment by Mkalo** [comment]
This is not a bug, that's how attributes work. They are only used when you assign the attribute to the item.
You can do something like:
`local description = item:hasAttribute(ITEM_ATTRIBUTE_DESCRIPTION) and item:getAttribute(ITEM_ATTRIBUTE_DESCRIPTION) or item:getType():getDescription()`

**Comment by conde2** [comment]
Use ItemType and then getDescription

Not a bug.

**Comment by Kamenuvol** [comment]
I suppose there is custom description and ItemType does not have this part. I am not sure.

**Comment by A-Syntax** [comment]
Item
https://github.com/otland/forgottenserver/blob/33d074fe1cb28d7f094e0e6896ada65d9cd472a2/src/luascript.cpp#L1994
ItemType
https://github.com/otland/forgottenserver/blob/33d074fe1cb28d7f094e0e6896ada65d9cd472a2/src/luascript.cpp#L2403

**Comment by PrinterLUA** [comment]
Well i know that the function getDescription exsist, but question is it intended behavior

**Comment by marksamman** [comment]
Since we've had multiple releases with this behavior, yes. Returning the ItemType description when the attribute doesn't exist may be more desirable for your use case, but it's too late to change that. You can override the function in Lua to make it do what you want though.

**Comment by PrinterLUA** [comment]
@marksamman 

Maybe reopen the issue, since getDescription works. But the thing is, it says 

> This potion restores 20 of a monster's life.

 instead of 

> This potion restores 20% of a monster's life.

Seems like it skips the `%` sign.
