### ISSUE TITLE
Error on signal handling in #1435

### ISSUE THREAD

**Issue by Mkalo** [otland/forgottenserver#1994]
#

### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Compile it in windows

### Expected behaviour
Compiled with no errors

### Actual behaviour
Doesn't compile
![sig](https://cloud.githubusercontent.com/assets/7635617/20371816/820b8f96-ac4e-11e6-9288-fb52b1c8725a.png)

### Environment

TFS 1.3

OBS: Adding the signals with define made it crash. Removing 
`set.add(SIGUSR1);`
`set.add(SIGHUP);`
And other occurrences of those two signals (switch case)  solved the issue.

**Comment by TechrlzGit** [comment]
Same here.

**Comment by marksamman** [comment]
Fixed in #1995
