### ISSUE TITLE
ProtocolLogin::getCharacterList  - gdb log with bt full.

### ISSUE THREAD

**Issue by eltom** [otland/forgottenserver#1996]
### Steps to reproduce (include any configuration/script required to reproduce)
TFS 1.3 compiling with debug symbols.
1.  I don't know how to produce it, its crash my server 1 or 2 times per day.
2. I have talked with the players that this error happened to them and they say that they exit by exit, and when they want to try to enter again they do not load the list of characters and the tibia client crashes. (Just when this happens the server also crashes)

3. I have only this gdb logs bt and bt full:

gdb bt:

`#0  0x00000000007f697e in boost::asio::basic_io_object<boost::asio::stream_socket_service<boost::asio::ip::tcp>, true>::get_service (this=0x6100)
    at /usr/include/boost/asio/basic_io_object.hpp:214
#1  0x00000000007f4188 in boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >::remote_endpoint (this=0x6100, ec=...)
    at /usr/include/boost/asio/basic_socket.hpp:1453
#2  0x00000000007ec49d in Connection::getIP (this=0x0) at /home/test/src/connection.cpp:271
#3  0x00000000009c5b83 in ProtocolLogin::getCharacterList (this=0x1d56ef8, accountName="11111dale17", password="jesus1996") at /home/test/src/protocollogin.cpp:53
#4  0x00000000009c79bb in std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)>::_M_call<std::shared_ptr<ProtocolLogin>&, std::string&, std::string&> (
    this=0x2002f90, __ptr=std::shared_ptr (count 2, weak 1) 0x1d56ef8) at /usr/include/c++/4.8/functional:558
#5  0x00000000009c7918 in std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)>::operator()<std::shared_ptr<ProtocolLogin>&, std::string&, std::string&, void> (this=0x2002f90, __object=std::shared_ptr (count 2, weak 1) 0x1d56ef8) at /usr/include/c++/4.8/functional:610
#6  0x00000000009c788e in std::_Bind<std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)> (std::shared_ptr<ProtocolLogin>, std::string, std::string)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x2002f90, __args=<unknown type in /home/server/dovux, CU 0x15e9612, DIE 0x1670f60>)
    at /usr/include/c++/4.8/functional:1296
#7  0x00000000009c755c in std::_Bind<std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)> (std::shared_ptr<ProtocolLogin>, std::string, std::string)>::operator()<, void>() (this=0x2002f90) at /usr/include/c++/4.8/functional:1355
#8  0x00000000009c7398 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)> (std::shared_ptr<ProtocolLogin>, std::string, std::string)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/4.8/functional:2071
#9  0x00000000009f1488 in std::function<void ()>::operator()() const (this=0x16d84f0) at /usr/include/c++/4.8/functional:2471
#10 0x00000000009f1372 in Task::operator() (this=0x16d84e0) at /home/test/src/tasks.h:40
#11 0x00000000009f0c1a in Dispatcher::threadMain (this=0xd5fe20 <g_dispatcher>) at /home/test/src/tasks.cpp:50
#12 0x000000000096ff11 in std::_Mem_fn<void (Dispatcher::*)()>::operator()<, void>(Dispatcher*) const (this=0x121cb48, __object=0xd5fe20 <g_dispatcher>)
    at /usr/include/c++/4.8/functional:601
#13 0x000000000096f989 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x121cb40)
    at /usr/include/c++/4.8/functional:1732
#14 0x000000000096f363 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::operator()() (this=0x121cb40) at /usr/include/c++/4.8/functional:1720
#15 0x000000000096edf6 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)> >::_M_run() (this=0x121cb28)
    at /usr/include/c++/4.8/thread:115
#16 0x000066c34f673a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x000066c34f8ce184 in start_thread (arg=0x66c34e45f700) at pthread_create.c:312
#18 0x000066c34eddb37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
 `
gdb bt full:

`#0  0x00000000007f697e in boost::asio::basic_io_object<boost::asio::stream_socket_service<boost::asio::ip::tcp>, true>::get_service (this=0x6100)
    at /usr/include/boost/asio/basic_io_object.hpp:214
No locals.
#1  0x00000000007f4188 in boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >::remote_endpoint (this=0x6100, ec=...)
    at /usr/include/boost/asio/basic_socket.hpp:1453
No locals.
#2  0x00000000007ec49d in Connection::getIP (this=0x0) at /home/test/src/connection.cpp:271
        error = {m_val = 0, m_cat = 0x66c35018e0d0}
        endpoint = {impl_ = {data_ = {base = {sa_family = 59920, sa_data = "EN\303f\000\000\320\352EN\303f\000"}, v4 = {sin_family = 59920, sin_port = 20037, sin_addr = {
                  s_addr = 26307}, sin_zero = "\320\352EN\303f\000"}, v6 = {sin6_family = 59920, sin6_port = 20037, sin6_flowinfo = 26307, sin6_addr = {__in6_u = {
                    __u6_addr8 = "\320\352EN\303f\000\000 \352EN\303f\000", __u6_addr16 = {60112, 20037, 26307, 0, 59936, 20037, 26307, 0}, __u6_addr32 = {1313204944, 26307,
                      1313204768, 26307}}}, sin6_scope_id = 8336628}}}}
#3  0x00000000009c5b83 in ProtocolLogin::getCharacterList (this=0x1d56ef8, accountName="11111dale17", password="jesus1996") at /home/test/src/protocollogin.cpp:53
        i = 0
        serverIp = 16777343
        account = {characters = std::vector of length -14123625479918, capacity -390 = {"",
            "\001", '\000' <repeats 15 times>, "\370\366EN\303f\000\000\001\000\000\000\000\000\000\000\330\366EN\303f\000\000\001\000\000\000\000\000\000\000 \366EN\303f\000\000\001", '\000' <repeats 143 times>..., "", <error reading variable: Cannot access memory at address 0xffffffffffffffe9>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0x62ac829c89d818e8>,
            <error reading variable: Cannot access memory at address 0x187c2595f7da441f>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, "", "",
            <error reading variable: Cannot access memory at address 0xa3d00000a26>,
            "\340\371EN\303f\000\000\340\377\377\377\377\377\377\377", '\000' <repeats 16 times>, "\360\356EN\303f\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\260\207\000H\303f", '\000' <repeats 138 times>...,
            "\340\371EN\303f\000\000\340\377\377\377\377\377\377\377", '\000' <repeats 16 times>, "\360\356EN\303f\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\260\207\000H\303f", '\000' <repeats 138 times>..., <error reading variable: Cannot access memory at address 0xffffffffffffffc8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            "\000\367EN\303f\000\000\370\060n\210\264\357+K", '\000' <repeats 16 times>, "\300\371EN\303f\000\000\000\367EN\303f\000\000\370\060\256U?s\255\206\370\060\364J\255p\255\206", '\000' <repeats 65 times>, "\367EN\303f\000\000}\263\335N\303f", '\000' <repeats 58 times>...,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe9>,
            '\000' <repeats 80 times>, "\003", '\000' <repeats 48 times>, "\367EN\303f\000\000\001", '\000' <repeats 15 times>, "\001", '\000' <repeats 31 times>, "\b\350DN\303f\000\000\000\000\000\000\000\000\000\000"..., <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, "", <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
---Type <return> to continue, or q <return> to quit---
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe9>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xb4d900bfc8094>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>,
            <error reading variable: Cannot access memory at address 0xffffffffffffffe8>, <error reading variable: Cannot access memory at address 0xffffffffffffffe8>...},
          name = <error reading variable: Cannot access memory at address 0xe83>, lastDay = 685926890, id = 1313205156, premiumDays = 26307, accountType = 0}
        motd = <error reading variable: Cannot access memory at address 0x20ec8348e589483d>
        output = warning: can't find linker symbol for virtual table for `std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>' value
warning: can't find linker symbol for virtual table for `std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>' value
std::shared_ptr (count 1303976384, weak 26306) 0x0
        size = 0 '\000'
#4  0x00000000009c79bb in std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)>::_M_call<std::shared_ptr<ProtocolLogin>&, std::string&, std::string&> (
    this=0x2002f90, __ptr=std::shared_ptr (count 2, weak 1) 0x1d56ef8) at /usr/include/c++/4.8/functional:558
No locals.
#5  0x00000000009c7918 in std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)>::operator()<std::shared_ptr<ProtocolLogin>&, std::string&, std::string&, void> (this=0x2002f90, __object=std::shared_ptr (count 2, weak 1) 0x1d56ef8) at /usr/include/c++/4.8/functional:610
No locals.
#6  0x00000000009c788e in std::_Bind<std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)> (std::shared_ptr<ProtocolLogin>, std::string, std::string)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x2002f90, __args=<unknown type in /home/server/dovux, CU 0x15e9612, DIE 0x1670f60>)
    at /usr/include/c++/4.8/functional:1296
No locals.
#7  0x00000000009c755c in std::_Bind<std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)> (std::shared_ptr<ProtocolLogin>, std::string, std::string)>::operator()<, void>() (this=0x2002f90) at /usr/include/c++/4.8/functional:1355
No locals.
#8  0x00000000009c7398 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (ProtocolLogin::*)(std::string const&, std::string const&)> (std::shared_ptr<ProtocolLogin>, std::string, std::string)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/4.8/functional:2071
No locals.
#9  0x00000000009f1488 in std::function<void ()>::operator()() const (this=0x16d84f0) at /usr/include/c++/4.8/functional:2471
No locals.
#10 0x00000000009f1372 in Task::operator() (this=0x16d84e0) at /home/test/src/tasks.h:40
No locals.
#11 0x00000000009f0c1a in Dispatcher::threadMain (this=0xd5fe20 <g_dispatcher>) at /home/test/src/tasks.cpp:50
        task = 0x16d84e0
        taskLockUnique = {_M_device = 0xd5fe38 <g_dispatcher+24>, _M_owns = false}
#12 0x000000000096ff11 in std::_Mem_fn<void (Dispatcher::*)()>::operator()<, void>(Dispatcher*) const (this=0x121cb48, __object=0xd5fe20 <g_dispatcher>)
    at /usr/include/c++/4.8/functional:601
No locals.
#13 0x000000000096f989 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x121cb40)
    at /usr/include/c++/4.8/functional:1732
No locals.
---Type <return> to continue, or q <return> to quit---
---Type <return> to continue, or q <return> to quit---
#14 0x000000000096f363 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::operator()() (this=0x121cb40) at /usr/include/c++/4.8/functional:1720
No locals.
#15 0x000000000096edf6 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)> >::_M_run() (this=0x121cb28)
    at /usr/include/c++/4.8/thread:115
No locals.
#16 0x000066c34f673a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#17 0x000066c34f8ce184 in start_thread (arg=0x66c34e45f700) at pthread_create.c:312
        __res = <optimised out>
        pd = 0x66c34e45f700
        now = <optimised out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {112989017863936, 5416686535505228024, 0, 0, 112989017864640, 112989017863936, -8742204585798651656, -8742207412067094280},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimised out>
        pagesize_m1 = <optimised out>
        sp = <optimised out>
        freesize = <optimised out>
        __PRETTY_FUNCTION__ = "start_thread"
#18 0x000066c34eddb37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
(gdb)
`

### Expected behaviour
Assign ip 0.0.0.0 without problems and don't crash the server.

### Actual behaviour
Assign ip 0.0.0.0 Infinitely until the server crashes

### Environment
TFS 1.3 in Ubuntu 14.04 LTS

**Comment by marksamman** [comment]
You've made changes to your source code, so it's possible that the crash doesn't affect the source code in this repository. If you want us to look into it, reproduce the crash with the source code from this repository without changes and post a new stacktrace.
