### ISSUE TITLE
How do you do a pull request?

### ISSUE THREAD

**Issue by Ledan-Chen** [otland/forgottenserver#1998]
Do I edit the files in this repository and submit a pull request or do I fork this repository and make the changes there? Sorry this is all new to me.

**Comment by diath** [comment]
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by ranisalt** [comment]
Prefer forking, the Github editor is a piece of shit and you can only update a single file at a time.

**Comment by Ledan-Chen** [comment]
Thanks @ranisalt I went with that method.
