### ISSUE TITLE
[Question] Passing userdata to event

### ISSUE THREAD

**Issue by totolol123** [otland/forgottenserver#2008]
As title says, is safe to do this:
```lua
    addEvent(function(player) if player then player:something... end end, time, player)
```
Or we should do only this:
```lua
    addEvent(function(cid) local player = Player(cid) if player then player:something... end end, time, player:getId())
```

**Comment by ninjalulz** [comment]
No, it's not safe at all. Userdata objects aren't set to nil whenever the memory is free'd (e.g. player logs out) so passing an object to addEvent isn't in your best interest.
