### ISSUE TITLE
maxPacketsPerSecond 

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#2012]
Hello, when player take pk and use some bot like Mage Bot for DASH he will be kicked and disconected (with PK/pz locked).

maxPacketsPerSecond = 25

I think is a bug, players can't logout with pz locked.

**Comment by wgrriffel** [comment]
he will not be kicked from server, just disconnected, his character will stand there until he can log out.

**Comment by darkjav** [comment]
You need use maxPacketsPerSecond = 35 or more,
but probably you can get problems with bots that flood packets, like WPE PRO,
more info here: https://github.com/otland/forgottenserver/issues/1845
and here: https://github.com/malucooo/Otxserver-Global/issues/46
