### ISSUE TITLE
Construction kits not useable with browse field

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2013]
https://otland.net/threads/bug-browser-field-items.247509/

**Comment by ranisalt** [comment]
You erased the entire issue template to post a link...

**Comment by TheSumm** [comment]
The line https://github.com/otland/forgottenserver/blob/master/data/actions/scripts/other/constructionkits.lua#L22 should additionally check whether the item is used from "browse field".

**Comment by ranisalt** [comment]
The link is broken now, but from @TheSumm comment it's probably related to #1915

**Comment by TheSumm** [comment]
No the issue here was that you cannot open furniture kits from the browse field container.
The script thinks that the furniture kit is in the player's inventory and not on a tile.

**Comment by Zbizu** [comment]
IMO "use in browse field window" is interesting case to explore, but deserves more clarity in the future (maybe an event like "onUseBrowseField").

solution for now:
global or pushing it to lua through enums: `ITEM_BROWSEFIELD = 460`

fixed function:
```
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	local kit = constructionKits[item.itemid]
	
	if not kit then
		return false
	end

	local tile = Tile(item:getPosition())
	
	if tile and tile:getHouse() then
		if fromPosition.x ~= CONTAINER_POSITION or item:getParent():getId() == ITEM_BROWSEFIELD then
			item:transform(kit)
			fromPosition:sendMagicEffect(CONST_ME_POFF)	
		else
			player:sendTextMessage(MESSAGE_STATUS_SMALL, "Put the construction kit on the floor first.")
		end
	else
		player:sendTextMessage(MESSAGE_STATUS_SMALL, "You may construct this only inside a house.")
	end
	
	return true
end
```

tested cases (use place/kit location):
- in backpack/outside a house (open in house message)
- in backpack/inside a house (put on the floor message)
- on the floor/outside a house (open in house message)
- on the floor/inside a house (opens)
- browse field/outside a house (open in house message)
- browse field/inside a house (opens)

If someone wants to open a pull request, I grant my permission to copy and use this code freely.

**Comment by ramon-bernardo** [comment]
The [current code](https://github.com/otland/forgottenserver/blob/48167ef5fee895f8195eebd82d15e6d01cece159/data/actions/scripts/other/construction_kits.lua#L16-L31) solved the problem.
- Construction kits can only be opened if they are on the floor of a house and from 'Use'. Browse field does not work.
