### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2014]
I dont know why and dont see the crash, just looking on files and got archive "core" and got:

(gdb) bt full
#0  0x000000000058af07 in Scheduler::threadMain (this=0x836840 <g_scheduler>)
    at scheduler.cpp:47
        task = 0x26b16bc0
        it = {<std::__detail::_Node_iterator_base<unsigned int, false>> = {
            _M_cur = 0x0}, <No data fields>}
        ret = <optimized out>
        eventLockUnique = {_M_device = 0x836858 <g_scheduler+24>,
          _M_owns = false}
#1  0x00007896aebc7a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x00007896adc02184 in start_thread (arg=0x7896ad360700)
    at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7896ad360700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {132588546426624,
                5656523560197079182, 0, 0, 132588546427328, 132588546426624,
                -4634951278052720498, -4634949807038349170},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0},
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
---Type <return> to continue, or q <return> to quit---
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007896ae32f37d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
(gdb)

**Comment by Schiffers** [comment]
how reproduce it?

**Comment by GoularPink** [comment]
http://prntscr.com/demev8

:S

**Comment by marksamman** [comment]
Use the issue template, and also post the stack trace of the dispatcher thread.

**Comment by GoularPink** [comment]
How I use issue template and how I take the stack trace? @marksamman

**Comment by marksamman** [comment]
You use the issue template by filling it when opening an issue instead of removing all the text. You get the stack trace of the dispatcher thread by checking the other threads in gdb with "thread X" where you replace X with a number, usually between 0 and 4. After you switch thread, write bt, and you'll see if the dispatcher main function is in the stack trace. Even better if you post the stack trace of all threads.

**Comment by GoularPink** [comment]
hum, ok thanks
