### ISSUE TITLE
Incorrect monster behaviour

### ISSUE THREAD

**Issue by elderapo** [otland/forgottenserver#2015]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Find or spawn monster that is away from normal players so only GM/GOD can see it.
2. Use dot spell (ex. utori pox) or soulfire on that monster (it doesn't work with field/bomb runes).

### Expected behaviour

Monster should stand still and receive damage from dot.
### Actual behaviour

Monster is "running around" like if it was observed by normal player from other floor.

**Comment by wgrriffel** [comment]
I've noticed this some time ago, can confirm this.

**Comment by vankk** [comment]
I can confirm this

![-](http://3.1m.yt/SELBxnx.gif)

**Comment by Tarliton** [comment]
I might be wrong, but when a condition is added it does not check if the player is ignored by monsters.
Then it proceeds to update idle status and as the conditions is not empty, it will start to move.
https://github.com/otland/forgottenserver/blob/0f5cf5c9fdc6f359d992d1ae196c73550ebc7fbe/src/monster.cpp#L645-L665

**Comment by ranisalt** [comment]
Though it can be considered a bug, I'm not sure this needs to be fixed, since it's only reproducible in very specific conditions and away from players. It doesn't hit neither gameplay experience nor performance.

**Comment by joseluis2g** [comment]
Conditions on new tfs rev are really bugged, its like condition attacks do not check if the target blocks the hit or not.
