### ISSUE TITLE
constructionkits not work

### ISSUE THREAD

**Issue by glombers** [otland/forgottenserver#2017]
I own a house:
![enter image description here](http://i.imgur.com/HzF6sIh.gif)

**Comment by Tarliton** [comment]
As this was implemented in [vanilla 10.92](http://tibia.wikia.com/wiki/Furniture_package), it is currenly not implemented here.

**Comment by glombers** [comment]
I understand and look for a solution to this problem, I do not know if it's something in the `LUA` or in `c ++`

**Comment by Tarliton** [comment]
You will have to find out which packet is sent by the client and then decide what to do with that. It could be in C++ or Lua.

**Comment by wgrriffel** [comment]
@Tarliton 
```javascript
static const CTOGGLEWRAPSTATE:int = 139;
```

**Comment by glombers** [comment]
@Tarliton I can not much of Lua and C ++ support means let the bug might be able to go the dissolution

**Comment by Zbizu** [comment]
Which way should it be implemented? action onWrap or xml-sided like rotate?

**Comment by Kamenuvol** [comment]
@Zbizu, should be on the same way of rotate.
2 options:
-change rotate to onRotate and make onWrap and onUnwrap;
-or all in xml
