### ISSUE TITLE
Rift carpets / void carpets not being saved as house items

### ISSUE THREAD

**Issue by guiismiti** [otland/forgottenserver#2021]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Place a rift/void carpet (not folded) inside a house
2. Save and restart server

### Expected behaviour
The carpet should be saved and loaded, just like the other items inside the house.

### Actual behaviour
The carpet is not saved or loaded (it is not a moveable item). I'm only talking about those two carpets here, but it probably happens with those new carpets from the Tibia Store.

I fixed this for the rift carpet but I'm not making a pull request, since I'm a noob (sorry for the mess from now on).
**The ID used for the void carpet, in my server, is 25392**:
In _IOMapSerialize::loadItem_
I complemented the conditional:
`if (iType.moveable || !tile) {`
became
`if (iType.moveable || !tile || id == 25392)`
In _IOMapSerialize::saveTile_
I complemented the conditional:
`if (!(it.moveable || item->getDoor() || (item->getContainer() && !item->getContainer()->empty()) || it.canWriteText || item->getBed())) {`
became
`if (!(it.moveable || item->getID() == 25392 || item->getDoor() || (item->getContainer() && !item->getContainer()->empty()) || it.canWriteText || item->getBed())) {`

**Comment by Kamenuvol** [comment]
There should be a new attribute to carpets and identify it where you put the id (item->getCarpet())

**Comment by Schiffers** [comment]
I've fixed it by editing the items.otb. the new tapestrys should use the flag moveable then it will be saved in the houses,, so you need create an event script to not able players move it, I hope that I had helped

**Comment by guiismiti** [comment]
@Kamenuvol 's solution should be used.
Mine can be considered a workaround, and @Schiffers ' aswell - but yes, editing items.otb and lua is always much more practical.

**Comment by marksamman** [comment]
Editing the OTB or hard-coding item ID's in the source code aren't acceptable solutions. If it can't be fixed by checking some suitable attribute, then a new attribute should be added to items.xml which allows items to be saved even though they're not moveable.

**Comment by gugahoa** [comment]
Can confirm this happens, as well

**Comment by darkjav** [comment]
Confirmed.

**Comment by vankk** [comment]
I managed the issue doing what Mark said, I doesn't have enough time theses days, soon will open a PR.
