### ISSUE TITLE
Xlog with pz locked 

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#2023]
Reproduce:
step1: Character take a pz locked 
step2: Xlog 
step3: log in 
step4: Xlog again
finish: the character will lost pz locked.

**Comment by wgrriffel** [comment]
wtf is Xlog?

**Comment by login12** [comment]
wtf is Xlog?²

**Comment by TechrlzGit** [comment]
xlog = exit

**Comment by login12** [comment]
I tried it, five times.
I don't lose pz locked.

I dont see any problem so?

**Comment by marksamman** [comment]
The real problem here is that the issue template is missing.
