### ISSUE TITLE
GM change outfit + mount = Tibia crash

### ISSUE THREAD

**Issue by Olrios** [otland/forgottenserver#2028]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Login on your GM character
2. Take for random outfit, example Citizen
3. Choose mount, example Widow Queen
4. Mount up, using CTRL + R
5. Change outfit again to Gamemaster Outfit.
6, Enjoy crash

### Expected behaviour
When changing to GM outfit, you should be dismounted.

**Comment by Pwntus** [comment]
#1334

**Comment by darkjav** [comment]
https://github.com/otland/forgottenserver/commit/ea9ad8e443c855473a1bb7c7d7a5bbbe4251fe89

**Comment by ranisalt** [comment]
As #1334 was previously fixed by ea9ad8e somewhere in between now and then there was a regression.

**Comment by ranisalt** [comment]
I just tried to reproduce it with OTClient and the server just plain ignores the mount, using the code added on ea9ad8e

**Comment by ranisalt** [comment]
Could you please try #2035?
