### ISSUE TITLE
rewrapping furniture (feature added in 10.92)

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#2031]
Hello.
I want to get right click -> wrap working (see #2017).
(wrapping furniture using game client feature)

The byte for "wrap" is 0x8B
according to what I heard its structure is similiar to useItem

Which way should it be written to make it a suitable pull for TFS? @marksamman 
```
items.xml -> wrapTo="id" -> functions similiar to "rotate" in sources
```
or
```
player event/action -> onWrap -> Lua
```

**Comment by marksamman** [comment]
Both. Store wrapTo in ItemType, add a getter function for it in the ItemType Lua API, and do the wrap logic in the event function.

**Comment by Zbizu** [comment]
https://github.com/otland/forgottenserver/blob/master/src/itemloader.h#L151
what is an equivalent for flag WRAPPABLE?

I need it to find if item is wrappable, like this:
https://github.com/otland/forgottenserver/blob/master/src/item.h#L640
(I could also compare wrapTo with 0 if there is no such flag)

**Comment by HeavenIsLost** [comment]
As far i have look in the new store items cipsoft uses only one item to wrap all their new furniture. Like that one item has a special property to hold the furniture id.
