### ISSUE TITLE
Reseting the mute's condition at death

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#2044]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Mute a player
2. Kill the player

### Expected behaviour
The player should keep muted.

### Actual behaviour
When the player dies it reset the condition and the player can talk in the Channel which he was muted.

### Environment
The test was maded in Windows 7 - 64 bits.

**Comment by Dyablots** [comment]
Totally reproducible, it requires a fix. It also reproduces when you **advance level**.

**Comment by vankk** [comment]
@marksamman Could you give us your opinion? How you want it be fixed?

**Comment by joseluis2g** [comment]
you can fix it doing it persistent and not like setting ticks to -1 just check it by sources

**Comment by GoularPink** [comment]
@marksamman

**Comment by ranisalt** [comment]
Stop marking Mark on the issue, he already receives notifications when someone opens the issue and comments on it and if he didn't commented or fixed the issue he is busy. Just wait or lean how to fix it yourselves.

You should probably keep a list of muted players (and timeouts, when appropriate) on the channel.
