### ISSUE TITLE
Version 10.100 (10.00) issue with trade window from npcs

### ISSUE THREAD

**Issue by Olimpotibia** [otland/forgottenserver#2045]
`void ProtocolGame::sendMarketBrowseOwnHistory(const HistoryMarketOfferList& buyOffers, const HistoryMarketOfferList& sellOffers)
{
	uint32_t i = 0;
	std::map<uint32_t, uint16_t> counterMap;
	uint32_t buyOffersToSend = std::min<uint32_t>(buyOffers.size(), 810 + std::max<int32_t>(0, 810 - sellOffers.size()));
	uint32_t sellOffersToSend = std::min<uint32_t>(sellOffers.size(), 810 + std::max<int32_t>(0, 810 - buyOffers.size()));

	NetworkMessage msg;
	msg.addByte(0xF9);
	msg.add<uint16_t>(MARKETREQUEST_OWN_HISTORY);

	msg.add<uint32_t>(buyOffersToSend);
	for (auto it = buyOffers.begin(); i < buyOffersToSend; ++it, ++i) {
		msg.add<uint32_t>(it->timestamp);
		msg.add<uint16_t>(counterMap[it->timestamp]++);
		msg.addItemId(it->itemId);
		msg.add<uint16_t>(it->amount);
		msg.add<uint32_t>(it->price);
		msg.addByte(it->state);
	}

	counterMap.clear();
	i = 0;

	msg.add<uint32_t>(sellOffersToSend);
	msg.addByte(1); // has reached Main (allow player to open Prey window)
	msg.add<uint16_t>(0x00); // imbuement detail
	for (auto it = sellOffers.begin(); i < sellOffersToSend; ++it, ++i) {
		msg.add<uint32_t>(it->timestamp);
		msg.add<uint16_t>(counterMap[it->timestamp]++);
		msg.addItemId(it->itemId);
		msg.add<uint16_t>(it->amount);
		msg.add<uint32_t>(it->price);
		msg.addByte(it->state);
	}

	writeToOutputBuffer(msg);
}`

I added bytes from version 10.100 prey system and works fine but when you try to trade with npcs and this npcs have +3 items crash client, for example: 3 items window dont need extend to see more items because only have 3 but when  you add or talk for example with rashid and he have + 3 objects client crash because need msg.addbyte or something like this..

Thnx anyway

**Comment by marksamman** [comment]
Use the issue template. This doesn't seem to affect the source code in this repository.

**Comment by Olimpotibia** [comment]
okay
