### ISSUE TITLE
Issue with shop_sellable "window" +3 Items = crash maybe need new bytes?

### ISSUE THREAD

**Issue by Olimpotibia** [otland/forgottenserver#2046]
### I have issue with new client version 10.100 (10.00) using actual npc system or maybe missing bytes.
1. Problem one is when player say trade to sell items crash client.
2. Im looking why appear it and i think the problem appear when npc create shop_sellable with +3 items on the list.
3. posible causes: Npc system works fine but new tibia client using new byte on this part to manage good prey system or something new.

### With version 10.99
1. With version 10.97 to 10.99 and with new tibia 11 works fine without new bytes.

### Actual copilation 10.100 (10.00)
1. Works perfect, can play normaly but only the problem is the trade window.

**Comment by Olimpotibia** [comment]
now mark?

**Comment by login12** [comment]
Weird. Here it not reproduced.

**Comment by TechrlzGit** [comment]
- [ ] This issue is reproducible without changes to the code in this repository

**Comment by joseluis2g** [comment]
lmao

**Comment by ranisalt** [comment]
TFS works up to 10.98, if you are trying to force another version you are on your own.
