### ISSUE TITLE
Requesting Lua function for millisecond time

### ISSUE THREAD

**Issue by Colandus** [otland/forgottenserver#2051]
I believe we should have an os.time alternative with millisecond precision.

**Comment by marksamman** [comment]
There is os.mtime()

**Comment by Colandus** [comment]
Oh, since when?

**Comment by ninjalulz** [comment]
Since [21st Oct, 2014](https://github.com/otland/forgottenserver/commit/9f39e18fe4dfdb1e6163de583324b6b965676a5f) 😄

**Comment by Colandus** [comment]
That's cool. Well guys I haven't been around since 2012.
