### ISSUE TITLE
Reload chatchannels, bug?

### ISSUE THREAD

**Issue by Colandus** [otland/forgottenserver#2056]
When reloading chatchannels, you are unable to write to any channel such as Help/World Chat/Gamemaster etc until you close and reopen them again (or relog).

Is this a bug or are all channels purposefully wiped from memory when reloading?

**Comment by ranisalt** [comment]
I think it's due to the speak event being nulled (https://github.com/otland/forgottenserver/blob/master/src/chat.cpp#L296)

**Comment by asamy** [comment]
@ranisalt But they are rewritten, so I doubt that's the issue.  Probably need to reopen the chat channels?

**Comment by Colandus** [comment]
@asamy Yes, that's what I said. Why are they nulled anyway?

**Comment by asamy** [comment]
Oh didn't see.  Anyway, since the chat channel is re-created, you'd need to re-add the users to add it, a deep copy basically, so someone should maybe provide a patch to do that.
