### ISSUE TITLE
allowfaruse (eg. fishing rod) not working

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#2059]
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. using fishing rod results in "there is no way" error (allowfaruse="1" in actions.xml)

### Expected behaviour
1. fishing without pathfinding request

### Actual behaviour
1. "there is no way" message

### Environment
Ubuntu 14.04.5 LTS

it worked properly before #2020 (though I'm not sure which commit caused that)

**Comment by ranisalt** [comment]
Please use [git bisect](https://stackoverflow.com/questions/4713088/how-to-use-git-bisect) to find exactly in which commit this regression happened. Good think you know around where it broke :P

**Comment by ranisalt** [comment]
Didn't catch my eye, should be solved now. Thanks @gugahoa 👍
