### ISSUE TITLE
A question - redundant code?

### ISSUE THREAD

**Issue by Colandus** [otland/forgottenserver#2064]
Isn't this last for loop unnecessary?

```
			std::vector<Container*> containers;

			for (const auto& it : openContainers) {
				Container* container = it.second.container;
				if (!Position::areInRange<1, 1, 0>(container->getPosition(), getPosition())) {
					containers.push_back(container);
				}
			}

			for (const Container* container : containers) {
				autoCloseContainers(container);
			}
```

Can't autoCloseContainers(container); be inside the previous loop? I don't see why a second loop is necessary, nor the definition of containers vector. There is no other code after that, so the fact that containers might be used again is excluded.

**Comment by marksamman** [comment]
It may invalidate the iterator.

**Comment by Colandus** [comment]
@marksamman How?

**Comment by marksamman** [comment]
By erasing entries from openContainers while iterating over openContainers.
