### ISSUE TITLE
onStepOut / closingdoor.lua bug

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#2065]
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. create gate of expertise
2. set action id e.g 1001
3. use and step out of it

### Expected behaviour
level door should close

### Actual behaviour
it stays open because
```tile:getCreatureCount()```
returns 1 instead of 0 in closingdoor.lua (movement)

### Environment
same as in #2059, probably caused by recent changes in sources

**Comment by PrinterLUA** [comment]
Since the latest commit using return values onStepIn and onStepOut #2049

So instead of using teleportTo to "block" someone from enter. We should return false instead.

**Comment by Zbizu** [comment]
@PrinterLUA blocking someone from enter works fine
stepping out is the problem because door doesn't close

**Comment by Zbizu** [comment]
workaround
```
local function tpOthers(oldPos, newPos)
	local c = Tile(oldPos):getCreatures()
	for i = 1, #c do
		c[i]:teleportTo(newPos)
	end
end

function onStepOut(creature, item, position, fromPosition)
	local tile = Tile(position)
	local newPosition = {x = position.x + 1, y = position.y, z = position.z}
	local query = Tile(newPosition):queryAdd(creature)
	if query ~= RETURNVALUE_NOERROR or query == RETURNVALUE_NOTENOUGHROOM then
		newPosition.x = newPosition.x - 1
		newPosition.y = newPosition.y + 1
		query = Tile(newPosition):queryAdd(creature)
	end

	if query == RETURNVALUE_NOERROR or query ~= RETURNVALUE_NOTENOUGHROOM then
		addEvent(tpOthers, 100, item:getPosition(), newPosition)
		local it = tile:getItems()
		for i = 1, #it do
			if it[i]:getWeight() > 0 then
				it[i]:moveTo(newPosition)
			end
		end
		local f = tile:getFieldItem()
		if f then
			f:remove()
		end
	end

	item:transform(item.itemid - 1)
	return true
end
```

**Comment by Zbizu** [comment]
tested it now on a fresh tfs, no longer bugged
