### ISSUE TITLE
Use shovel on blood

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#2073]
Can't use shovel on ground if have blood there:

http://prntscr.com/dtxbmb

**Comment by ninjalulz** [comment]
It's because the current configuration does not account for the sand ID 9059. Feel free to submit a pull request if you get it to work.

**Comment by DSpeichert** [comment]
Fixed in 5ccfce5e2807cc8cc0c4d5e4bd891105fcfcffa2 / #2393
