### ISSUE TITLE
Multiple database entries for the same house door list

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#2074]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Own a guild hall
2. Add a player to a door list with aleta grav
3. Save the server

### Expected behaviour
A single entry in the `house_lists` table should be used to store that door name list.

### Actual behaviour
Multiple entries with the same content are stored

![Imgur](http://i.imgur.com/jotp9UM.png)

**Comment by ranisalt** [comment]
It seems it happens because house lists for doors are never deleted, they are only inserted (`IOMapSerialize::saveHouseInfo()`)

**Comment by Xagul** [comment]
Played around with it a bit and figured out that if you give door rights to a player and then open/close the door it will create a new entry each time.

https://i.imgur.com/0QeOH93.png

**Comment by ranisalt** [comment]
@Xagul can you check that #2075 fixes?
