### ISSUE TITLE
Update Container Items

### ISSUE THREAD

**Issue by K3V1N-BR** [otland/forgottenserver#2078]
Hello,

I would like some help in this issue, I'm using TFS 1.1 to running a 7.72 server and when container (Depot) has more items than the capacity, removing an item does not update the container items correctly. It happen when the player lost some house and the items go to his depot.

Regards,
Kevin.

**Comment by ranisalt** [comment]
Please follow the template issues. As per your question, you are running a modified version of the source code we can not provide assistance to.
