### ISSUE TITLE
doAreaCombatCondition(cid, pos, area, condition, effect) crashes TFS

### ISSUE THREAD

**Issue by raymondtfr** [otland/forgottenserver#2094]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Use the function from the title above in any spell.
2. TFS should crash when the spell is cast for the second time.

### Expected behaviour
The function should not crash TFS.

### Actual behaviour
The function crashes TFS.

### Environment

TFS 1.3

**Comment by ninjalulz** [comment]
I was able to reproduce this as well. Since OP hasn't provided any [stacktrace](http://pastebin.com/sXZ5jJ8a), I'll go ahead and do that.

**Comment by totolol123** [comment]
Confirmed. Also, while we are in it theres no way of having a "Area" function? Like that:
```lua
    area = CombatArea(CIRCLE_5X5)
    area:setCombat(combat)
    area:setCondition(condition)
    area:setCenter(playerPos)
    area:setEffect(effect)
```

**Comment by raymondtfr** [comment]
I haven't tested other similar functions (doAddAreaCondition, etc)
@ranisalt
