### ISSUE TITLE
"Bug" when changing floors and standing on 3 stackable objects

### ISSUE THREAD

**Issue by t0kenz** [otland/forgottenserver#2114]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Place any 3 stackable objects
2. Attempt to change floors

https://gyazo.com/4ef6df19b1a5779d3f975e0eb867a5e5

Seems like this "bug" if you may call it that resides even back to tfs 0.3.6pl1.

### Expected behaviour
The creature (player) should change direction depending on if the player is trying to go up -> direction set to north and if the player is trying to go down -> direction set to south.

### Actual behaviour
Nothing is affecting the direction, which leads to it remaining the same when changing floors.

Fix: #2113

**Comment by conde2** [comment]
@ranisalt please close this issue
