### ISSUE TITLE
Compiling  on Windows 10 "Cannot open include file: 'chrono'"

### ISSUE THREAD

**Issue by cmarfil** [otland/forgottenserver#2117]
Hello,

Compiling on windows 10, with Visual studio 2015 Update 3.

`Error	C1083	Cannot open include file: 'chrono': No such file or directory	theforgottenserver	c:\users\juan\desktop\tibia serv\tibia serv\src\otpch.h	26	`

Any suggestion?

Thanks!

**Comment by conde2** [comment]
Here works fine windows 10 visual studio 2015

**Comment by kornholi** [comment]
You have not set up Boost correctly

**Comment by djarek** [comment]
@cmarfil 
Looks like an issue with bad/missing environment variables.
