### ISSUE TITLE
[Suggestion] Summons

### ISSUE THREAD

**Issue by Riverlance** [otland/forgottenserver#2118]
Hello, guys.

I was testing the summons and I got a little bored with the current system of summons.
So, I have 3 suggestions for the summons of TFS.

> 1. Summons could be **walkable**. It will make so much easier to walk through narrow paths.
> 2. Summons could **teleport for your position** when you are **farway** (25 SQMs is perfect, in my opinion) or **when you change a floor level**.
> 3. For the floor change, I suggest also a creature script as **onFloorchange(cid, fromPos, toPos)** for make this summons teleport and other stuffs by lua script.

@WibbenZ @Mkalo

**Comment by WibbenZ** [comment]
This is a thing for your personal project imo, we should focus on staying as close the "target game" as posible imo.
If that game has those features then sure.

Another thing we might be able to do is move summon codes to Lua to allow easier changes.
To my understanding from Mark we should move as much as posible to Lua.

**Comment by Riverlance** [comment]
Sure. So, can you pass it for lua?

**Comment by TheSumm** [comment]
Summons are walkable on optional pvp and on open pvp (depending on whether you are in an aggression and who's summon it is).

**Comment by Riverlance** [comment]
Here is my config (has only "pvp", "no-pvp" and "pvp-enforced"):

> worldType = "pvp"

And my summons are not walkable, even if I am it's master.
So this is an issue?

**Comment by WibbenZ** [comment]
Well I don't have time right now, been doing some work on my OTC project, but when I need a change ill look into it :> 

It works as it "should" on PvP you should not be able to walk through (any?) summons.
What Summ is talking about requires us to update to the new war system (if we want it as close as posible to the "real" game.

**Comment by Riverlance** [comment]
Ooh, ok. Got. Thanks! ;)
