### ISSUE TITLE
[Question] - CONDITION_PARAM_SUBID

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#2122]
We have two different SUBID for haste and strong haste, shouldn't they be the same ? So if you cast strong haste it will overwrite haste spell ?

**Comment by raymondtfr** [comment]
No. It has to be different subid's for each different spell, so that you can identify which spell you cast.

**Comment by conde2** [comment]
SUBID is for finding specific conditions when using getCondition and to not overwrite conditions, if you cast haste and strong haste you will have 2 conditions running at the same time, what is not meant to

**Comment by raymondtfr** [comment]
I am pretty sure if a condition of the same type is added to a creature then it will overwrite the former, otherwise it would not make sense to have subids at all.

Yes, I meant *spell* as a spell that adds a condition to a creature.

**Comment by raymondtfr** [comment]
@conde2 You're actually right here. I mislead the real purpose of subids... conditions with different subids can coexist, which would change the default behavior of spells, I'll make a PR to remove subids and let users decide if they want that or not.
