### ISSUE TITLE
[QUESTION] Raid with hours and days

### ISSUE THREAD

**Issue by tiagotwos** [otland/forgottenserver#2127]
My raids doesn't work fine, I put this in raids.xml

`<raid name="RatsThais" file="normal/ratsthais.xml" interval2="5" margin="0" />`

but when start the first raid, no have a continuation, execute once, so, I tried with date and hours, but nothing script worked ... anyone can help me ? tfs 1.2

**Comment by conde2** [comment]
Please use OTLand support board for this
