### ISSUE TITLE
Question - push const player as userdata

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#2130]
What are the implications of doing this:

	LuaScriptInterface::pushUserdata<const Player>(L, player);

Pushing a const value to lua.

**Comment by ranisalt** [comment]
Probably because `player` is `const Player*` and it would discard the const qualifier.

**Comment by conde2** [comment]
So there is no problem at all doing this ? Pushing const values to lua ends up of pushing it like it is not const ?

**Comment by ranisalt** [comment]
No and it probably doesn't make any difference.

**Comment by conde2** [comment]
Thanks.
