### ISSUE TITLE
onLook problem

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#2135]
### Before creating an issue, please ensure:
- [X ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Look yourself 

### Expected behaviour
call Player:onLook event 

### Actual behaviour
calling Player:onLookInBattleList event 

### Environment
Latest TFS

Not sure if it is because I'm using OTClient

**Comment by ninjalulz** [comment]
You should have opened an issue in the OTClient repository instead of here, since it works just fine with the vanilla client.

**Comment by conde2** [comment]
I didn't know if the problem was with otclient or TFS, that's why I opened it here anyway thanks for telling me where the problem really on.
