### ISSUE TITLE
accounts table empty?

### ISSUE THREAD

**Issue by adahox** [otland/forgottenserver#2141]
accounts mysql table comes empty? why?how can create an account ?once i've created on phpmyadmin and it does not work.

**Comment by wgrriffel** [comment]
> Before creating an issue, please ensure:
> 
>  This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)

damn, at least read firsts lines before errasing issue template, and yes it comes empty and that's why it's called schema.
