### ISSUE TITLE
saveServer() and cleanMap(), it says: not found.

### ISSUE THREAD

**Issue by javierglch** [otland/forgottenserver#2146]
Hello

These functions are not working: saveServer() and cleanMap(), it says: not found.
https://gyazo.com/94ef3088b87ce16615fa0116ad0fdcde

i searched it in sources, and appears to be correct...

**Comment by vankk** [comment]
https://github.com/otland/forgottenserver/blob/1ae8483ac3319cc5a7a2db5af77bf0885459811b/src/luascript.cpp#L3510-L3514

https://github.com/otland/forgottenserver/blob/1ae8483ac3319cc5a7a2db5af77bf0885459811b/src/luascript.cpp#L3503-L3508

?

**Comment by ranisalt** [comment]
Follow the issue template. You have modifications to your source code.
