### ISSUE TITLE
onLogout should have second parameter isForced!

### ISSUE THREAD

**Issue by Colandus** [otland/forgottenserver#2147]
onLogout event should have additional parameter isForced. This is necessary in case you have logic that expects player not to be logged out after preventing logout by returning false.

I would create a pull request if I wasn't noob with git :(

**Comment by EPuncker** [comment]
@DSpeichert so if we are not implementing it at all after two attempts we might as well close this issue? I don't see any use for forced as well

**Comment by DSpeichert** [comment]
I think the other PRs had a different meaning of forced, no? I read the 3 PRs and each really expected different meaning of "not forced" and "forced". I'll close this until there is a solid design proposal on what each should do.
