### ISSUE TITLE
God commands won't work

### ISSUE THREAD

**Issue by securmk** [otland/forgottenserver#2154]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Run server and log in
2. Try to execute god commands such as /i /s or /m

### Expected behavior
They do what they're supposed to do (like creating an item, summoning an NPC or summoning a wild monster.

### Actual behavior
It does nothing. Doesn't throw any error on server, it just doesn't do anything. Word won't appear in chat. Account type is 3 and player type is 3.

### Environment
The Forgotten Server - Version 1.3
Compiled with Clang version 6.0 (clang-600.0.57)
Compiled on Feb  5 2017 14:42:43 for platform x64

**Comment by Vulcanx** [comment]
Account type should be 5.

**Comment by securmk** [comment]
@Vulcanx Yeah I already tried that. It doesn't work neither.

**Comment by ranisalt** [comment]
Then you have modified your source.

**Comment by securmk** [comment]
Managed to solve it by re-compiling. Don't know what was causing it. Thanks 👍

**Comment by ranisalt** [comment]
I'm pretty sure you have issued `git pull` on the repository, updating the data files (that work without recompiling) but without recompiling the server. Always recompile after `git pull` :P
