### ISSUE TITLE
Question about Store Inbox

### ISSUE THREAD

**Issue by brunominervino** [otland/forgottenserver#2156]
@ranisalt what you think about create new class called 'StoreInbox' for implement Store System? Suggested by @ninjalulz [here](https://github.com/otland/forgottenserver/pull/2143#discussion_r99316904) and supported by @Mkalo.

If they agree, is it best to do a new pull request?

**Comment by ranisalt** [comment]
Very similar to #1641 on this issue. I don't know how the store system works, does it really have a separate inbox for bought items?

**Comment by WibbenZ** [comment]
Yes its prety much the code from the purse except that you can only get items in it, you can't put the old premium scrolls in it.
So tbh #531 should be closed.

But... If you buy supplies let's say GMPs the server counts them as if you had them in your backpack, so it's a way to not lose supplies if you are hunting.
Not 100% on this but im pretty sure about it xD

**Comment by brunominervino** [comment]
Basically how @WibbenZ told.

**Comment by WibbenZ** [comment]
Agreed, some might use Znote / Gesior on the side of this and might want ppl to be able to store those items in there.
Would be alot easier to accept certain itemids insted of recompiling the source code.

**Comment by brunominervino** [comment]
@WibbenZ exactly.

**Comment by ninjalulz** [comment]
I'm slightly confused as to what you two are talking about. Not losing supplies? Accepting certain item ids?

**Comment by WibbenZ** [comment]
Well in Tibia you get all the things you buy in the store inbox.
If you die you don't lose those items, so if you keep the GMPs you bought via the store in there you won't lose them if you die.

You can move bought items back, that should be OK with this system, but if you bought items via a website you can't put them in the store inbox, that is why it would be better to handle the store inbox in Lua so we can add an exception for those donation items not bought via the ingame store.

**Comment by brunominervino** [comment]
@WibbenZ you can use, example GMPs, inside store inbox?

**Comment by WibbenZ** [comment]
Aa I said not 100 on that but I think so.
Bubba did smth the store inbox when a new server started, but im not sure if he moved a couple to his bp or not.

Im sure you can't have pz when buying atleast since he had to stop hunting to buy more.

**Comment by ninjalulz** [comment]
@WibbenZ Yes, I do understand that, however I believe you are forgetting one thing. The ingame store and AACs (e.g. Znote & Gesior) relies on Lua to add things to players, so it shouldn't be an issue. It's not like we must have this feature, do we? Having a locked store inbox, and only allowing items to be added with the no limit flag would be sufficient.

I still don't believe using the Player event _onMoveItem_ is the correct approach in this scenario.

**Comment by joseluis2g** [comment]
internal query add aka creating a new class would be the best solution

**Comment by WibbenZ** [comment]
Well both ways work, but it would be easier for others to have it in Lua.
Correct and correct, well it all depends on how we wanna write it, but since most ppl seem to not wanna have it in Lua then put it in C++ :p

**Comment by TheSumm** [comment]
- The store inbox is basically a second backpack slot, which always has the container "store inbox" in it
- It should not be "locked" (red border) since you can move store items from/to the store inbox
- You cannot drop the store inbox on death and the store inbox itself has no weight
- The weight of items inside the store inbox will be subtracted from your cap (as it is a normal container in your inventory).
- Hotkeys consider items in your store inbox.
- It can only contain items bought from the store (items need to be assigned a special store attribute to verify this)
- Store items cannot be stacked with non-store items
- Store items can be moved to your depot (or to your **own** house if it is a furniture item / furniture package)
- Store items might be placed in your inbox if you have store-bought furniture in your house and then lose the house

**Comment by EPuncker** [comment]
just leaving this here for reference:
https://github.com/otland/forgottenserver/commit/1f1c490fe8b7ef9d80d14ad72710b7b46b4141fd

**Comment by nekiro** [comment]
Implemented in https://github.com/otland/forgottenserver/pull/3186
