### ISSUE TITLE
onManaChange(...) - cannot block part of damage with mana shield

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#2159]
I tried to make script that block 50% of spell damage. For health it works fine, but then I tried to make it work for players with mana shield:

```
function onManaChange(creature, attacker, manaChange, origin)
	if origin == ORIGIN_SPELL then
		manaChange = manaChange / 2
	end
	return manaChange
end
```

as you can read in this line:
https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L3984

It will execute 'onHealthChange' with health reduced by number of mana I blocked and deal that damage (with origin NONE) to.. mana as player still got manashield.

On my server I changed that line to:

`damage.primary.value = healthChange - manaDamage;`

but it will probably give bug with weapons that deal 'element damage'.

I hope you guys can re-think whole onHealthChange and onManaChange code and make it work in every possible scenario.

**Comment by Mkalo** [comment]
I don't think I understand what is going wrong, could you try to explain again? For me that code seems perfectly fine.

**Comment by ninjalulz** [comment]
@Mkalo Take a look at this snippet: https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L3997-L4006. The remainder goes through here, and deals additional damage (in other words, the player still takes full damage).

**Comment by gesior** [comment]
If I set health and mana change functions to return '50%' for spells (origin = spell) player will take (from exori vis 40 dmg hit):
1. First it will call onManaChange event with 40 dmg and reduce dmg to 20 (40 / 2).
2. Deal 20 dmg to mana shield.
3. Then it will call onHealthChange with dmg 20 (40-20!) and reduce dmg to 10.
4. Then it will call 'combatChangeHealth' with 10 dmg and origin 'none'. Mana events will not execute.
5. Then it will deal 10 dmg to mana shield.

So player get 30 dmg (should get 20 with 50% reduction) and **it shows 2 hits in player console!**


**Hm... If I make event that works with any origin, will it go into loop?**
I got no server to test it, but if script 'onManaChange' return '0' and you got 'some' health event that return full dmg it look like it will crash server (stackoverflow).

**Comment by Mkalo** [comment]
@gesior Can you test this patch:
https://gist.github.com/Mkalo/237ee95d24dbab1f39890931c4af80f1
I'm pretty sure it fixes your issue.

Just becareful cause with this I changed the event to:
```lua
onManaChange(creature, attacker, primaryDamage, primaryType, secondaryDamage, secondaryType, origin)
```
And you will probably need to check if the type is COMBAT_MANADRAIN because with this combat the function works kinda differently:

If the combat is COMBAT_MANADRAIN:
Positive values for primaryDamage and secondaryDamage are going to heal your mana, while negative values are going to decrease your mana.
Else:
The damage values are always positive and its going to decrease your mana.
