### ISSUE TITLE
why are you simplifying the code so much...

### ISSUE THREAD

**Issue by woeterman94** [otland/forgottenserver#2163]
I mean.. Look at this:

The code for a piggybank...

function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if math.random(6) == 1 then
		item:getPosition():sendMagicEffect(CONST_ME_POFF)
		player:addItem(ITEM_GOLD_COIN, 1)
		item:transform(2115)
	else
		item:getPosition():sendMagicEffect(CONST_ME_SOUND_YELLOW)
		player:addItem(ITEM_PLATINUM_COIN, 1)
	end
	return true
end

**Comment by ranisalt** [comment]
Why not? Get a random roll, if it's equal to 1 (or really any value, but 1/6 change) add a gold coin and break, else add a platinum. What's there to add?

**Comment by DSpeichert** [comment]
@woeterman94 Not sure if there's any action item here (anything you want done with that). So I'm closing this, but feel free to respond if you want to propose anything.
