### ISSUE TITLE
Segmentation fault on FreeBSD

### ISSUE THREAD

**Issue by securmk** [otland/forgottenserver#2170]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Download source from GitHub repository.
2. Compile on FreeBSD system.
3. Run on FreeBSD system.

### Expected behavior
The server runs as it should.

### Actual behavior
Segmentation fault (core dumped).

### Environment
Latest version of FreeBSD and official vanilla version of TFS.

Here is the log:

Starting program: /root/gameserver/tfs
(no debugging symbols found)...(no debugging symbols found)...[New LWP 100119]
[New Thread 804416000 (LWP 100119/tfs)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 804416000 (LWP 100119/tfs)]
0x000000000045d8c8 in std::__1::function<void ()(Player&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::function ()
Current language:  auto; currently minimal
#0  0x000000000045d8c8 in std::__1::function<void ()(Player&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::function ()
#1  0x000000000045a7ee in Commands::Commands ()
#2  0x00000000004ea698 in Game::Game ()
#3  0x00000000007df6e7 in __cxx_global_var_init.13 ()
#4  0x00000000007e2865 in _GLOBAL__sub_I_otserv.cpp ()
#5  0x000000000098c602 in __do_global_ctors_aux ()
#6  0x000000000040a3f6 in _init ()
#7  0x00007fffffffe580 in ?? ()
#8  0x0000000800c75e9d in objlist_call_init (list=<value optimized out>,
    lockstate=<value optimized out>) at /usr/src/libexec/rtld-elf/rtld.c:2535
#9  0x0000000800c754e4 in _rtld (sp=<value optimized out>,
    exit_proc=<value optimized out>, objp=<value optimized out>)
    at /usr/src/libexec/rtld-elf/rtld.c:690
#10 0x0000000800c735c9 in .text ()
    at /usr/src/libexec/rtld-elf/amd64/rtld_start.S:39
#11 0x0000000000000000 in ?? ()

**Comment by ranisalt** [comment]
On the environment, please mention all related software versions (gcc, lua/luajit, mysql, etc)

**Comment by marksamman** [comment]
There was a crash that only happened on FreeBSD in the past which was because global variables on FreeBSD were initialized in a different order than on other operating systems. It could be something similar here.

**Comment by securmk** [comment]
Error with libs. Solved.
