### ISSUE TITLE
Summons crash

### ISSUE THREAD

**Issue by Tazer89** [otland/forgottenserver#2173]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.
2.
3.

### Expected behaviour
When monster has summons up and been killed the server crash.

### Actual behaviour
https://www.youtube.com/watch?v=lvSGsLdbmrw

### Environment
No compile errors and also latest commit.

**Comment by ninjalulz** [comment]
Can you provide the necessary steps to reproduce the crash?

P.S. The facebook video is not accessible to the public.

**Comment by wgrriffel** [comment]
either you can upload attachs from github, you don't need go to disservices such as facebook.

**Comment by Tazer89** [comment]
https://www.youtube.com/watch?v=lvSGsLdbmrw

**Comment by vankk** [comment]
This video is not avaiable.

**Comment by Tazer89** [comment]
Now video is fixed. sorry.

**Comment by ninjalulz** [comment]
I were unable to crash the server by recreating the steps provided (I even tried with different monsters, but no luck there either). Can you post a stacktrace from gdb?

**Comment by Tazer89** [comment]
Did the monster have summons up when you kill it?

**Comment by ninjalulz** [comment]
> Did the monster have summons up when you kill it? Becouse the crash only happens when you kill (Master) that summons when he has summons up

Yes, of course. I repeated the process multiple times, and still no crash. Is the source code you're using untouched, and what operative system is the server running on?

**Comment by ranisalt** [comment]
You have new mail

**Comment by Tazer89** [comment]
Wierd i uses last commit when i try it... Im running it on debian.

**Comment by Tazer89** [comment]
I did a fresh install of debian and fresh commit and it stills crashing when summons is up.

**Comment by Kamenuvol** [comment]
No crash here. But I found other issue: when God summons something the wild monsters do not attack it as before.

**Comment by Tazer89** [comment]
@Kamenuvol are you using debian?

**Comment by Kamenuvol** [comment]
No, Windows 10 compiling with VS2015

**Comment by Tazer89** [comment]
@Kamenuvol then it has something with debians to do then.

**Comment by Kamenuvol** [comment]
Have you tested it before #2131 ?

**Comment by Tazer89** [comment]
@Kamenuvol i changed back for #2131 and now it not crashing at all. so it has with #2131 to do.

**Comment by Kamenuvol** [comment]
Have you tested killing a player that has summons?

**Comment by Kamenuvol** [comment]
https://github.com/otland/forgottenserver/blob/5ba1ef3926695237a8da3d969bd99e779a0ae7f1/src/creature.cpp#L1136 try swap line 1136 with 1137

**Comment by Tazer89** [comment]
@Kamenuvol nope did not work. still crashing.

**Comment by dead** [comment]
Not the same issue, but when I summon a creature and logout the server crash.
The problem can be fixed adding this code to logout.lua
```
    summons = player:getSummons()
    for i, summon in ipairs(summons) do
        summon:remove()
    end
```

**Comment by DSpeichert** [comment]
@dead can you reverify the problem after 155ea351565b8091393ff27d69c587a7baedf5a9?
