### ISSUE TITLE
Database charset must be UTF-8

### ISSUE THREAD

**Issue by ranisalt** [otland/forgottenserver#2175]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Create database with character set different than `utf8` (e.g. MariaDB defaults to `latin1`)
2. Import schema.sql

### Expected behaviour
Schema tables should be created on the database.

### Actual behaviour
It fails with error message `ERROR 1071 (42000) at line 15: Specified key was too long; max key length is 767 bytes`.

It happens because characters on `latin1` use 4 bytes on MySQL, and there is an unique key on `players.name` (and others, maybe) which is 255 characters, thus 1020 bytes, hitting the 767 bytes limit on keys. It's not an issue on UTF-8 as it uses 3 bytes per character, thus 765 bytes just short of the limit.

We should either manually set the column character set to `utf8` on every indexed column or set it to the entire database, which is a better option IMHO since utf8 is ubiquitous and should prevent other problems with the database.

**Comment by marksamman** [comment]
Replacing all instances of:
) Engine=InnoDB;
with:
) Engine=InnoDB DEFAULT CHARACTER SET=utf8;

... in schema.sql should fix this. The only thing that's unfortunate is that I think game clients use a UTF-8 incompatible charset, we had to do something like this in the past: https://github.com/otland/forgottenserver/commit/51c2b30f399406326e53b01d2968be5021a027b1#diff-02a5c822dac3211b227f53f928b2ef67L151

**Comment by ranisalt** [comment]
Well, C++ itself isn't very UTF-8 friendly by default...

**Comment by wgrriffel** [comment]
@ranisalt just reporting that ive upgraded my debian to 9, and all packages that refers to mysql (that is on wiki btw) now is directed to mariadb packages, there is any workaround that i may use for now?

**Comment by ranisalt** [comment]
No, I've been using MariaDB (the default on Arch Linux) since ever and there's no difference with InnoDB storage. Actually there's more to change on the software than the database.
