### ISSUE TITLE
Summons crashing

### ISSUE THREAD

**Issue by Mkalo** [otland/forgottenserver#2190]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Summon any monster
2. Logout

### Expected behaviour
Player logout and summon disappear.

### Actual behaviour
Crash

### Environment
Latest build of TFS 1.3

Related to #2173 but it is crashing for another reason.

Backtrace:
http://pastebin.com/z6nM8Jsp

**Comment by Kamenuvol** [comment]
I can't reproduce

**Comment by Mkalo** [comment]
@Kamenuvol That is weird, it happens all the times and I tested 10 times.

Downloaded the executable from https://ci.appveyor.com/project/kornholi/forgottenserver/build/1.0.389/job/m46qdj81k943f1f9/artifacts

And using the latest data pack (with the summon spell modifications.)

**Comment by Vulcanx** [comment]
Was unable to reproduce, tested with fire elemental and monk using utevo res

**Comment by Kamenuvol** [comment]
@Mkalo Which Windows are you using?

**Comment by dead** [comment]
I can reproduce. Compiling in a docker VM.

**Comment by Mkalo** [comment]
Backtrace:
http://pastebin.com/z6nM8Jsp

**Comment by Mkalo** [comment]
@Kamenuvol Tested in windows 7 and ubuntu 16.04, it crashes in both.

**Comment by vankk** [comment]
I can confirm this issue.

![](http://3.1m.yt/6IdFaGo.png)

Using Windows Seven 64 bits.

**Comment by Kamenuvol** [comment]
I really don't understand why it's happening for you and not for me using same .exe file from appveyor, same windows. What is causing that? Now I want to solve the mystery 🤔

**Comment by ranisalt** [comment]
Can't reproduce too.

**Comment by DSpeichert** [comment]
Reproduced on latest Ubuntu with the exact same backtrace as given.

**Comment by Mkalo** [comment]
@Kamenuvol @ranisalt Did you guys download exactly from https://ci.appveyor.com/project/kornholi/forgottenserver/build/1.0.389/job/m46qdj81k943f1f9/artifacts ?

You know that the latest build in the list https://ci.appveyor.com/project/kornholi/forgottenserver also shows pull requests and you might just have downloaded my fixed version of the pull request. At least that's what happened with @Vulcanx.

**Comment by ranisalt** [comment]
I don't have Windows, but @dspeichert says he has reproduced on Ubuntu too.

**Comment by jo3bingham** [comment]
Unless I'm reading @Mkalo's GDB dump incorrectly, the segmentation fault is happening at the line `summon->setAttackedCreature(nullptr);` in:
```
for (Creature* summon : summons) {
    summon->setAttackedCreature(nullptr);
    summon->setMaster(nullptr);
}
```
which implies `summon` is a nullptr. Which means the summon isn't being removed. Upon making sure the summon is actually removed when necessary (#2191), it wouldn't hurt to do a nullptr check:
```
for (Creature* summon : summons) {
    if (!summon) {
        continue;
    }
    summon->setAttackedCreature(nullptr);
    summon->setMaster(nullptr);
}
```

**Comment by Kamenuvol** [comment]
Please, try to print the summon list size on the destructor before this loop.

**Comment by Mkalo** [comment]
@jo3bingham summon is never nullptr, delete doesn't make every pointer to that object a nullptr.

**Comment by jo3bingham** [comment]
@Mkalo A segmentation fault happens when trying to access an invalid memory address, which implies that `summon` is invalid in some way (usually a nullptr).

**Comment by Mkalo** [comment]
A wild crash has appeared:
http://pastebin.com/M89EkwYu

This happens for another reason poitned out by an user in otland in [here](https://otland.net/threads/segmentation-fault.250084/)
![crash](https://cloud.githubusercontent.com/assets/7635617/23717872/45de107a-0414-11e7-85fb-2de0cb3152f8.png)

![revert](https://cloud.githubusercontent.com/assets/7635617/23717884/4dc64a6e-0414-11e7-92f7-2c0371129a24.png)

Both crashes were gone when I reverted https://github.com/otland/forgottenserver/commit/5ba1ef3926695237a8da3d969bd99e779a0ae7f1
