### ISSUE TITLE
Server Froze

### ISSUE THREAD

**Issue by K3V1N-BR** [otland/forgottenserver#2201]
Yesterday a guy started doing something to froze the game, a lot of players got disconnected but the server stay online I use gdb and save the output of the executable so I'm sure of it, just the players are disconnecting. I was monitoring the traffic to detect some kind of DOS/DDOS but I can't see nothing and the company also doesn't detected nothing. I decide move the server to the (OVH), I was using (nfoservers.com), but after some minutes the guy started talk with me and started the attack again. Please! someone have an ideia how I can detect it or doing something ?

System: Debian 8.7
Iptables running.
Website: running in another machine to avoid attacks.
TFS: 1.2

Thank you in advanced.

**Comment by djarek** [comment]
@K3V1N-BR 
Could you provide me with the gdb dump ? Are you using the official TFS 1.2 release or something from master?

**Comment by vankk** [comment]
I don't think that is a problem with the engine, maybe the problem is in your datapack. I updated Aura's engine this week and I didn't had any problem with freeze.

**Comment by TwistedScorpio** [comment]
The issue is happening because on his server, an **NPC sells parcels + labels** at the same time (talking, no trade window), so when a player goes and buys _100+ parcels_ at a time and he has at least 1 empty slot on which to add the first parcel, the server freezes until all parcels + labels are added to the player, resulting in a massive freeze to all the players.

**Comment by K3V1N-BR** [comment]
@djarek It was a bug in my MUTE system. I don't have any output of gdb to show because it doesn't crash, it just froze because the cpu usage was high. How I can set a limit to stack items in SQM (Houses and outside) ? maybe if someone start make a big amount of itens inside the house and use the command (!leavehouse) it can be bad ?
