### ISSUE TITLE
Why RSA decrypt is altering Login NetworkMessage (not the first 0)?

### ISSUE THREAD

**Issue by UltraMC** [otland/forgottenserver#2208]
I ask as during analysis of loginpacket structure I don't understand the following part.

Why in ```RSA::decrypt```  in line ```mpz_export(msg + (128 - count), nullptr, 1, 1, 0, 0, m);``` You do ```msg + (128 - count)``` ?(https://github.com/otland/forgottenserver/blob/0815f772aae41ab90ba6eab557e028e845603a3f/src/rsa.cpp#L88 )

If decryption failed (```128 - count != 0```) it will alter message by adding a number to it but in what purpose? Is it going to change XTEA decryption result?

It should ultimatly fail at https://github.com/otland/forgottenserver/blob/cc8e15e9166359faa52d38823e679355a615ab23/src/protocollogin.cpp#L209
but here next question pops up why it's ```RSA::decrypt```'ed once again here if it's should stop execution here https://github.com/otland/forgottenserver/blob/cc8e15e9166359faa52d38823e679355a615ab23/src/protocollogin.cpp#L150

**Comment by djarek** [comment]
If the decrypted message is shorter than 1024 bits (128 bytes) it will be padded at the front:
https://github.com/gilgad13/rsa-gmp/blob/master/rsa.c#L205-L208. mpz_export does not write these zeros, so we need to manually calculate the offset and prepend an appropriate number of zeros.

**Comment by UltraMC** [comment]
@djarek great, what about second use of https://github.com/otland/forgottenserver/blob/cc8e15e9166359faa52d38823e679355a615ab23/src/protocollogin.cpp#L209

**Comment by djarek** [comment]
@UltraMC 
The token is stored in the second block of 128 bytes, that's why we perform a decrypt twice (decrypt only decrypts one block).
I don't believe this is specific to our implementation of 2FA.
