### ISSUE TITLE
Party Leader problem

### ISSUE THREAD

**Issue by TheSumm** [otland/forgottenserver#221]
If my understanding isn't wrong I think there is a bug when leader leaves the party.

Player::getPartyShield will still return SHIELD_YELLOW for that player if the method of any member is called as the check is:
if (party->getLeader() == player) {

I do not know if that is the right way to fix it or if it has any side effects.
if (party->getLeader() == player && player->getParty()) {
##

**Comment by ramon-bernardo** [comment]
This issue can be **closed**.

The problem does not occur when there are only two players in the party. If either the member or leader leaves, the party disbands. When there are more than two players, leadership is transferred to another player, and the shields are updated normally.
