### ISSUE TITLE
Custom RSA key loader

### ISSUE THREAD

**Issue by djarek** [otland/forgottenserver#2216]
The current solution has bad security (does anyone remember to change their RSA key?).

## Requirements
- The keys should be loadable from PEM files generated by ```openssl rsa``` CLI tool
- Support for encrypted keys is optional (would be nice to have)
- ```config.lua``` must specify the absolute/global path of the key file
- If the path is missing, default keys should be loaded
- If default keys have been loaded and server is in production mode (#2215) the server should fail to start

**Comment by gugahoa** [comment]
What about the public key on the client side? Would ipchangers need to fetch it from some api?

**Comment by UltraMC** [comment]
People leave RSA key to enable bots to be operatable.

**Comment by djarek** [comment]
@UltraMC 
Using the default key means that the user's password is effectively transmitted in plaintext.

**Comment by djarek** [comment]
@gugahoa 
The public key should be part of the address, i.e.
```
otserv://ip:port/version/pubkey
```
