### ISSUE TITLE
Investigate the use of ASIO timers instead of the Scheduler tasks

### ISSUE THREAD

**Issue by djarek** [otland/forgottenserver#2218]
The current solution of implementing timers (Scheduler tasks) with thread sleeps is likely to be [inefficient](https://gha.st/short-sleeps/) in terms of OS<->Userspace context switches and thread rescheduling for short sleep times (1 ms and less). We should investigate using the ASIO timer library (which uses the ```timerfd``` API) instead.

## Requirements:
- use one of ASIO's timer implementations instead of the Scheduler
- the timers should post a functor to the Dispatcher's execution queue
- should be safe when #2217 is resolved

**Comment by CristoferMartins** [comment]
@djarek My bad, i have said dispatcher but i what mean was the replacement of scheduler thread with asio timers. Also why we need multiple asio threads to start using asio timers?

**Comment by djarek** [comment]
There's no need for a separate thread explicitly - there's need for a separarte `io_context` because the networking code is not thread-safe enough for more than 1 network/scheduling thread to operate in.

**Comment by CristoferMartins** [comment]
@djarek do you got any idea where its not thread safe? the network code(thanks to you too) is quit "simple", the only thing i can think that is issue is how the player object is used inside protocolgame.cpp.
