### ISSUE TITLE
Bug in skull system

### ISSUE THREAD

**Issue by gunzino** [otland/forgottenserver#2223]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Kill player and get white skull
2. Attack killer with the victim player (after death)
3. The victim won't get yellow skull nor PZ Lock

### Expected behaviour
After death, when the victim attack ANY white skull, he should get pz lock and yellow skull

### Actual behaviour
- Attacking killer after death gives no PZ lock  nor yellow skull, if the attacker kills you again, he will get unjustified kill

There is also one possible scenario:
1. You have player with a white skull
2. He gets attacked by someone with no skull.
3. The white skulled player will see the attacker with yellow skull.
4. The attacker will kill white skulled player
5. The previously white skulled player will come again to the attacker and he always see the attacker with yellow skull.

### Possible fix
attackedSet in Player class should store internal player ID instead of player guid. Is there some problem it can cause ?

**Comment by ninjalulz** [comment]
This sounds like an issue that were addressed (https://github.com/otland/forgottenserver/commit/132aa7fb5c3d82675b6ed10642727d9cb5ef8b14) approximately 2 months ago. Was it not fixed, or are you perhaps running TFS 1.1/1.2?

**Comment by gunzino** [comment]
Ohh I see, the bug was there for like 3 years. I use TFS 1.0. Didn't saw it was fixed in January. Thank you,

**Comment by djarek** [comment]
I'm closing the issue then.
