### ISSUE TITLE
Bug - lose pk with Monsters attacking

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2224]
### **Steps to reproduce** (include any configuration/script required to reproduce)
1. Take a PK or Pz locked
2. Run to forgive a monster and let it attack you (I tested with monsters and player atacking the character who gave xlog)
3. Xlog (close your tibia)
4. The character will logout in few seconds even all attacking

### Expected behaviour

**The character must remain online if pk / pz locked.**

### Actual behaviour

**The character will logout in few seconds even all attacking**

**Comment by ranisalt** [comment]
Isn't it dependent on the vocation? Technically you "lose connection" to the game and there's a recent feature regarding it.

**Comment by GoularPink** [comment]
Isn't it dependent on the vocation... If the player is being attacked by another player and there are no attacking monsters left, it will remain online. If in case a monster is attacking it will disconnect.

**Comment by pedriinz** [comment]
This bug is not relationed with the forgotten server.
You need added checks if player have or not pzLocked. For it, you can use function: **isPzLocked()**.

`if target:isPzLocked() then
-- action
end`
