### ISSUE TITLE
SendTutorial(tutorialId) not working since the update of 10.98 protocol. 

### ISSUE THREAD

**Issue by SavageCrown** [otland/forgottenserver#2227]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.
2.
3.

**Comment by SavageCrown** [comment]
Already tested the Tfs version 1.1 with the client 10.76 and the function is working properly sending the Tutorial hints (the ones from rookagard etc)
But with the client 10.98 is not working anymore.
Already checked the tibia.exe(HexEditor) and the tibia.pic of the tibia.exe (10.98) and the client still have the tutorial hints.
maybe something change between 10.76 to 10.98?

**Comment by EPuncker** [comment]
I'm closing this as sendnTutorial is working on client 12.x
![2021-11-22_21_57_41-OT_-_Perflex](https://user-images.githubusercontent.com/4684880/154819326-485fd1e7-e19e-4c31-b597-5158d50a6918.png)
