### ISSUE TITLE
Something to add to Wiki for Ubuntu

### ISSUE THREAD

**Issue by ghost** [otland/forgottenserver#2231]
Not a bug or anything just something to add to the wiki compiling on ubuntu?
I use linux mint but I am sure these commands are universal.

When you have finished compiling and if your config.lua is setup you can type.
`mv tfs ../ && cd ../ && ./tfs` and it will launch the server :)
```
~/forgottenserver/build $ mv tfs ../ && cd ../ && ./tfs
The Forgotten Server - Version 1.3
Compiled with GNU C++ version 5.4.0 20160609
Compiled on Apr 15 2017 22:37:57 for platform x64

A server developed by Mark Samman
Visit our forum for updates, support, and resources: http://otland.net/.

>> Loading config
>> Establishing database connection... MySQL 5.7.17
>> Running database manager
>> Loading vocations
>> Loading items
>> Loading script systems
>> Loading monsters
>> Loading outfits
>> Checking world type... PVP
>> Loading map
> Map size: 1000x1000.
> Map loading time: 1.194 seconds.
> Loaded house items in: 0.002 s
>> Initializing gamestate
>> Loaded all modules, server starting up...
>> Forgotten Server Online!
```

**Comment by ranisalt** [comment]
You should copy the config.lua and data folder to the build folder to keep the repository intact instead. Then, you won't mess with git staging area and you can just `rm -rf build` to start over.

**Comment by DSpeichert** [comment]
Or just `cd ..; build/tfs` - it works as well.

**Comment by DSpeichert** [comment]
Closing as opinion.
