### ISSUE TITLE
Slower map loading in self compiled relase

### ISSUE THREAD

**Issue by stojakes** [otland/forgottenserver#2233]
Like in topic. Map loading time depends of something?
I added only sending more columns to players_online in database, and time of loading from few seconds have grown to 160~ secs. i cannot debug scripts in normal time, horrible ;p

**Comment by djarek** [comment]
Try building the optimized version(Release target),

**Comment by stojakes** [comment]
Thanks, change to Relase solution in VS Solution configuration has solved this problem. Thanks a lot.
