### ISSUE TITLE
showTextDialog read a string function

### ISSUE THREAD

**Issue by stojakes** [otland/forgottenserver#2234]
Hello again, i have question about function in topic, is there any possibilies to read a text, what player draw on this opened window?

There is a function, i tried to include <protocol.h> and use getOutputBuffer to recieve a text into a string and make a simple function what return a string but i dont know how to declare this visible for lua script, i think that my thinking is incorrect, and there must be a easiest way to make that.

```
`LuaScriptInterface::luaPlayerShowTextDialog(lua_State* L)
{
	// player:showTextDialog(itemId[, text[, canWrite[, length]]])
	Player* player = getUserdata<Player>(L, 1);
	if (!player) {
		lua_pushnil(L);
		return 1;
	}

	int32_t length = getNumber<int32_t>(L, 5, -1);
	bool canWrite = getBoolean(L, 4, false);
	std::string text;

	int parameters = lua_gettop(L);
	if (parameters >= 3) {
		text = getString(L, 3);
	}

	uint16_t itemId;
	if (isNumber(L, 2)) {
		itemId = getNumber<uint16_t>(L, 2);
	} else {
		itemId = Item::items.getItemIdByName(getString(L, 2));
		if (itemId == 0) {
			lua_pushnil(L);
			return 1;
		}
	}

	Item* item = Item::CreateItem(itemId);
	if (!item) {
		reportErrorFunc(getErrorDesc(LUA_ERROR_ITEM_NOT_FOUND));
		pushBoolean(L, false);
		return 1;
	}

	if (length < 0) {
		length = Item::items[item->getID()].maxTextLen;
	}

	if (!text.empty()) {

		item->setText(text);
		length = std::max<int32_t>(text.size(), length);

	}

	item->setParent(player);
	player->setWriteItem(item, length);
	player->sendTextWindow(item, length, canWrite);
	pushBoolean(L, true);
	int b= atoi(text.c_str());
	return b;
}
```
`Ah i dont see that code have diffrence in last lines i wanted to make this function return a int value and convert this in lua, but there is any possibility to dont call this function twice and lose a result
```
	int b= atoi(text.c_str());
	return b;
```

**Comment by EvulMastah** [comment]
https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L2275-L2280

?

**Comment by DSpeichert** [comment]
I assume that what you are trying to achieve is to get text input from the character that was entered as text edit on an item dialog (such as writing in a book).

Current Lua function allows you to trigger writing in an item (`Player:showTextDialog`) and then reading the text (`Item:getAttribute(ATTR_TEXT)`).

You don't need to create new Lua functions to do that, just use a "temporary" item that you can later destroy.
