### ISSUE TITLE
bug in new setMaster behavior

### ISSUE THREAD

**Issue by Nu77** [otland/forgottenserver#2235]
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps
1. Place any monster near your
2. Summon any monster when the monster placed is in idle state
3. Puff. Because the summon is placed first as a monster, theres no entry in the surrounding monsters target list, our old setMaster behavior as using the monster class conviceCreature, which is updating the target list.

### Expected behaviour
Surrounding monsters target list should be updated when in idle state and on placing a summon

### Actual behaviour
Its not

**Comment by gugahoa** [comment]
In practice is this something to worry about? I can't think of a case where a monster is idle near a player, but if it's not idle but the targetList is still not updated I think it's worth to look into

**Comment by TwistedScorpio** [comment]
No, the bug itself is because the function "convinceMonster" is checking wether or not a monster is convinceable (this is wrong); hence, the monster summoned will be hostile to all players if it is not convinceable.

This only happens after the summon creature was moved to LUA.

**Comment by pzaj2** [comment]
@gugahoa 

If I understood this bug correctly, it means the summon will not be attacked by the monster? While I'm sure you're correct that monster will not be idle having any player near, I still can think of an edge case where:
1. Player is not within "visibility" range of the monster
2. Player summons a creature that in fact will be summoned within "visibility" range of the monster
3. Monster will not attack summoned creature.

I'm not sure how it's going to end when player gets within "visibility" range of this monster (will it update the target list including the summon or omit the summon). No matter what are the chances for this to happen, it should still be considered a bug.
