### ISSUE TITLE
Forgot to add parameter?

### ISSUE THREAD

**Issue by rudger** [otland/forgottenserver#2252]
https://github.com/otland/forgottenserver/commit/4fa8f3a225d70304991555d560c56f8bd246e209

In this commit, if you go to 'src/depotlocker.cpp'

this was added:

DepotLocker::DepotLocker(uint16_t type) :
	Container(type, 3), depotId(0) {}

but shouldn't it be:

DepotLocker::DepotLocker(uint16_t type) :
	Container(type, 3), depotId(0), maxSize(3) {}

**Comment by rudger** [comment]
mm, maybe I'm wrong Container(type, 3) = maxSize 3?

**Comment by pzaj2** [comment]
@rudger
Just look at Container constructor's signature. second argument is maxSize of the Container.

```Cpp
Container::Container(uint16_t type, uint16_t size, bool unlocked /*= true*/, bool pagination /*= false*/)
```
