### ISSUE TITLE
[BUG] /reload monsters will double monsters strength

### ISSUE THREAD

**Issue by Strutzz** [otland/forgottenserver#2255]
Found issue when reloading monsters. It seems to be doubling the strength of all monsters.
Easiest to see by summoning a training monk and a demon. have the demon attack the training monk and then type in '/reload monsters'  demons attack will be stronger the more you reload.

**Comment by Kamenuvol** [comment]
At least is not memory leaking nor invalidating pointers...

**Comment by Strutzz** [comment]
Just an update it looks like its not 'doubling' the monsters attack, but it is making it attack twice causing a combo.

**Comment by M4GO** [comment]
i have this bug its doubling the monsters loots too

> Strutzz commented 2 hours ago
Just an update it looks like its not 'doubling' the monsters attack, but it is making it attack twice causing a combo

**Comment by Strutzz** [comment]
The fix that @M4GO posted indeed fixes the issue... It also fixes another bug of reloading spells causing the server to crash.. ZZZZZZZZZZ

**Comment by M4GO** [comment]
@Strutzz  change the credits bug fixed by @DanielChabrowski

**Comment by marksamman** [comment]
Fixed in 967d82305e7bdbc54a5dbe92c45bd9caee736117
