### ISSUE TITLE
House sometimes fails to send items to depot

### ISSUE THREAD

**Issue by justepo** [otland/forgottenserver#2258]
Hello,
I have this problem on my server, on which players have their houses with items (like many, but no specified quantity of items), and whenever they do !sellhouse to other player, their items are supposed to be sent to their Inbox, the items vanish of course, but there is NOTHING in the depot, I've attempted to reproduce it with few items and it's all good, I've even attempted to reproduce it with 50k+ items and it works fine, what could the reason be for it to randomly fail like this? My server is live and this is killing my server population, so I had to disable house renting for the same reason.

TFS 1.2 Stable
Linux System: Debian

Thank you.

**Comment by TwistedScorpio** [comment]
https://otland.net/threads/leave-house-dont-send-items-to-depot.250596/

**Comment by gunzino** [comment]
It should send items to Inbox not depot, have you checked this ?

**Comment by justepo** [comment]
@gunzino Yes, I mean Inbox. Sorry 👍

**Comment by K3V1N-BR** [comment]
Hello guys, someone can take a look on this issue ? I'm with the same problem.

**Comment by WibbenZ** [comment]
The "problem" is most likely this; https://github.com/otland/forgottenserver/blob/5d7e54a597beb078e3e7b28a856a8920019fa18d/src/house.cpp#L203

If someone notices this and the town id is set, we can re-open this issue.
