### ISSUE TITLE
Monster loot message small or BIG bug

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#2259]
delete

**Comment by EvulMastah** [comment]
Is this a joke issue?

`if (!owner || owner->getStaminaMinutes() > 840)` means if there is *no* owner or there is an *owner* with staminaMinutes > 840. If there is no owner the stamina check is not executed, it exits the if-statement immediately.

**Comment by gesior** [comment]
@EvulMastah 
Didn't see line 79. This is how ends working for 16 hours.. :(
