### ISSUE TITLE
monster/npc skull

### ISSUE THREAD

**Issue by OPfeajoief13** [otland/forgottenserver#2265]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. <monster name="Marid" nameDescription="a marid" race="blood" experience="410" speed="234" manacost="0" skull="red">

### Expected behaviour
Monster should receive the skull

### Actual behaviour
Nothing happens

 #1023

**Comment by OPfeajoief13** [comment]
add skull="red" to the monster name tag.

**Comment by OPfeajoief13** [comment]
^ Should be in 'Steps to reproduce' but wasn't added for some reason.

**Comment by OPfeajoief13** [comment]
Also doesn't work with npcs

**Comment by WibbenZ** [comment]
Avoid spamming, each message sends an email to users, so try to get everything in one issue / message.
If you don't write how to reproduce it how should we reproduce it?
Does your server have custom mods etc etc?

Seeing as you linked a "custom PR" we need to know what you are doing with that function.
"RL" Never gives skulls to monsters AFAIK.

**Comment by OPfeajoief13** [comment]
I reproduced it by adding: skull="red" to the monster name tag.
My server is not using custom mods.
I'm not using hardcore pvp.

Well I thought the PR was implemented so it should work, but it doesn't and I'm aware rl never gave skulls to monsters/npcs.

**Comment by marciNekel** [comment]
Shouldn't this be closed already as we can add skulls to monsters/npcs?
![image](https://user-images.githubusercontent.com/4026320/109159622-1e68dd80-7775-11eb-961c-6e89003e8d31.png)

**Comment by EPuncker** [comment]
> Shouldn't this be closed already as we can add skulls to monsters/npcs? ![image](https://user-images.githubusercontent.com/4026320/109159622-1e68dd80-7775-11eb-961c-6e89003e8d31.png)

do it work on cip client thought?

**Comment by marciNekel** [comment]
Yes, it works, just tested again.
![image](https://user-images.githubusercontent.com/4026320/140615797-eb4750ce-a470-4553-812a-02b41a4b6a08.png)

**Comment by EPuncker** [comment]
> Yes, it works, just tested again. ![image](https://user-images.githubusercontent.com/4026320/140615797-eb4750ce-a470-4553-812a-02b41a4b6a08.png) This is on cipclient.

thank you for confirmation
