### ISSUE TITLE
Levitate Bug (game.cpp)

### ISSUE THREAD

**Issue by mallikar** [otland/forgottenserver#2266]
Game.cpp ---> Game::internalMoveCreature

Can't **levitate using trophy stands/parcels/boxes/etc**. multiple times in a row. I can levitate up as many times as I want. But when there are 2 or more levitate spots in a row (a good example is the big wall, west of Svargrond, with about 5 levitate spots in a row).

Seems to be an error when the hasHeight() is 3 after levitating down once.
Levitating up works perfectly fine, multiple times in a row.
But levitating down stops after the first levitate down.

**Comment by mallikar** [comment]
Oh btw, this should only apply to when levitating UP

**Comment by mallikar** [comment]
Another bug:
Can't levitate down multiple times in a row. For example the walls west of Svargrond (about 6 floors). Can only walk up 1 floor (with parcels), then it stops.

**Comment by mallikar** [comment]
Another bug: Can't levitate multiple times in a row. For example the walls west of Svargrond (like 6 levitate spots). Doesn't work with parcel/trophy stands. It stops after 1.

**Comment by mallikar** [comment]
Solution to the first bug!!

(game.cpp ---> internalMoveCreature)

Change:
if (!tmpTile->hasFlag(TILESTATE_FLOORCHANGE))

To:
if (!tmpTile->hasFlag(TILESTATE_FLOORCHANGE) && map.getTile(destPos.x, destPos.y, destPos.z)->hasFlag(TILESTATE_BLOCKSOLID))

**Comment by pzaj2** [comment]
@mallikar 
Could you please make a screenshot and draw some explanation or record a short video?
I'm still not sure what you are referring to.

Also, I would suggest to change the title to "Floor level change" in place of "levitate", since the latter I think is usually associated with levitate spell (unless this is about levitate spell and I misunderstood the issue).

**Comment by mallikar** [comment]
@pzaj2 You know those big steps west of Svargrond? It's like 5 levitate spots in a row on a mountain. If I place 3x parcels or 3x trophy stands, or something to levitate up with, I can walk up all those floors - no problem. But I can't walk all the way back down. I can only go down 1 floor. And then it just stops. It doesn't work. Until I remove one of the parcels/trophy stands.

Here is a video demonstrating it. It's really weird.
I can only walk up/down the first time. The rest of the time I can only levitate up, until I remove at least one of the items under the character.

Can't walk back down...
https://www.youtube.com/watch?v=zzLSRnsGu4A

**Comment by DanielChabrowski** [comment]
When you're standing on a tile that has 3+ height, TFS always tries to go up or onto the next tile on the same level, it doesn't even try to go down.

**Comment by mallikar** [comment]
@DanielChabrowski How can it be fixed? I have checked the file, **game.cpp**, at the **Game::internalMoveCreature**

But I'm not very good at programming. I assume it's one of the **->hasHeight(3)** that needs to be (re)moved. I've tried so many times, but it just does not work. Any pro maybe can fix it

**Comment by waqmaz93** [comment]
hasHeight is bugged in tfs .
in function:
`ReturnValue Game::internalMoveCreature(Creature* creature, Direction direction, uint32_t flags /*= 0*/)`
add this:
`
		if (creature->getTile()->hasHeight(3))
		{
			std::cout << "hasheight = 3\n";
		}
		if (creature->getTile()->hasHeight(2))
		{
			std::cout << "hasheight = 2\n";
		}
		if (creature->getTile()->hasHeight(1))
		{
			std::cout << "hasheight = 1\n";
		}
		if (creature->getTile()->hasHeight(0))
		{
			std::cout << "hasheight = 0\n";
		}`
And now start walking on parcels. You will see what i mean.
![dupa](https://user-images.githubusercontent.com/45514240/144712937-3e273562-4632-4cb2-93bd-dad6ecf910b3.gif)
