### ISSUE TITLE
use luajit cmake flag is not working

### ISSUE THREAD

**Issue by wgrriffel** [otland/forgottenserver#2269]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. generate a make file with flag -DUSE_LUAJIT=OFF

    otherwise, you can look at travis builds, even with lua jit off build, cmake still choosing luajit dynamic libs.

### Expected behaviour
link lua default dynamic lib instead luajit one

### Actual behaviour
cmake choose luajit even with USE_LUAJIT=OFF

### Environment
Debian 8.8

**Comment by ranisalt** [comment]
It happens because the configuration autodetects and uses LuaJIT. Though it is better to keep LuaJIT on if detected, I understand that not testing with pure Lua would create a dependency.

I could revert to the old behavior where it must be enabled on the command line (or disabled). What do you think?

**Comment by wgrriffel** [comment]
in this particular case i was having trouble with luajit lua5.2 compatibility, i had to recompile luajit with 5.2 extended compatibility, even with compatibility problems, i'd default luajit if both detected, however since luajit is not fully compatible with lua, if user specify to turn off by hand, it should respect user preference imo

**Comment by ranisalt** [comment]
But it's pretty hard to both detect, reset variables, fetch the option, then detect once again the correct one. It'd be something like this:
```
find_package(LuaJIT)
option(USE_LUAJIT ${LuaJIT_FOUND})
unset(Lua_LIBRARIES)
unset(Lua_INCLUDE_DIRS)
if(USE_LUAJIT)
  find_package(LuaJIT REQUIRED)
else()
  find_package(Lua REQUIRED)
endif()
```
Note that we double test LuaJIT and that is somewhat hassle.

**Comment by ranisalt** [comment]
Turns out it wasn't so hard. https://github.com/ranisalt/forgottenserver/tree/luajit-optional I'll merge as soon as it passes on Travis.

**Comment by wgrriffel** [comment]
yep, working like charm, thanks @ranisalt i'm closing this issue
