### ISSUE TITLE
Party Shared Experience - bug with enabling in protection zone

### ISSUE THREAD

**Issue by nekiro** [otland/forgottenserver#2270]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Enter protection zone tile and try to enable shared experience after you attacked monsters and got any condition which is sustaining your condition in fight.

### Expected behaviour
You should be able to enable shared experience immediately.

### Actual behaviour
You cannot enable shared experience, because the server is thinking that u got the "condition in fight" even if you are in protection zone where you can logout when you want.

**Comment by thexamx** [comment]
I fixed it in function:
`void Game::playerEnableSharedPartyExperience(uint32_t playerId, bool sharedExpActive)`

changing:
`if (!party || player->hasCondition(CONDITION_INFIGHT)) {`
to:
`if (!party || (player->hasCondition(CONDITION_INFIGHT) && !player->getTile()->hasFlag(TILESTATE_PROTECTIONZONE))) {`

Dunno if it's the correct way to do this.

**Comment by jo3bingham** [comment]
@thexamx You would also want to ensure that `player->getTile()` doesn't return a nullptr. Other than that, your approach is correct.

**Comment by joseluis2g** [comment]
is this correct?
```c++
	Party* party = player->getParty();
	Tile* tile = player->getTile();
	if (!party || (player->hasCondition(CONDITION_INFIGHT) && tile && !tile->hasFlag(TILESTATE_PROTECTIONZONE))) {
		return;
	}
```

**Comment by Eternal-Scripts** [comment]
@joseluis2g yep

**Comment by thexamx** [comment]
`Tile* playerTile = player->getTile();
if (!party || (player->hasCondition(CONDITION_INFIGHT)) && (playerTile && !player->playerTile->hasFlag(TILESTATE_PROTECTIONZONE)))`

**Comment by M4GO** [comment]
no solved
http://pt-br.tinypic.com/view.php?pic=169ol02&s=9#.WWx1qoTyuM8
