### ISSUE TITLE
creatureevent onHit(creature, target, damage?)

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#2273]
Feature request:
If player / creature has this registered its possible to script what is going to happen before/after hit is applied

Currently it's possible with onHealthChange but requires registering event on target all the time.
With onHit it would require registering on scripted creature only.

This would allow things like extra damage against certain groups of monsters, true damage, lifesteal, etc.

I think there is a better way than applying creatureevent on targets.
Is there something I am missing?

**Comment by Kamenuvol** [comment]
Hit means it has caused damage on target. What if it attacked but not damaged? I think onAttack would be better, like old TFS had.

**Comment by Vulcanx** [comment]
you can do this with a tag in monster xml files
`<script>
    <event name="someHealthChangeEvent"/>
</script>`
