### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by glombers** [otland/forgottenserver#2274]
https://otland.net/threads/hole-id-392.252646/

**Comment by WibbenZ** [comment]
Use the issue template.

Also note that it's a TFS 1.1 bug, we are on 1.3.
Have you made sure the problem isn't working on 1.3 aswell?

**Comment by glombers** [comment]
@WibbenZ I changed version to 1.1 I do not know why it added here. How to report problems for older versions?

**Comment by ranisalt** [comment]
You don't. Upgrade to newer versions as they contain fixes.
