### ISSUE TITLE
Warlock shot effect

### ISSUE THREAD

**Issue by murilow1** [otland/forgottenserver#2277]
In data monsters, warlock shoots burst arrows thats is wrong

its shoots fire...

attribute key="shootEffect" value="burstarrow" />

change to 

attribute key="shootEffect" value="fire" />

**Comment by luancuba** [comment]
I've created a pull request for this.

**Comment by marksamman** [comment]
Fixed in 5b8d2ca18eea175242183198dbf8035b9b0c6350
