### ISSUE TITLE
/i (create item bug)

### ISSUE THREAD

**Issue by rudger** [otland/forgottenserver#2279]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Using command: /i 2160 100 a few times.

### Expected behaviour
There should be a few stacks of 100 crystal coins under you or the script should tell you that it's an invalid itemid or that you would need to add a ','.

### Actual behaviour
A none valid itemid is created, when you do the command a few times and step on the tile a creature dissapears.

### Environment
In-game.

**Comment by thexamx** [comment]
correct spelling is `/i 2160, 100`

**Comment by OPfeajoief13** [comment]
I know
