### ISSUE TITLE
Condition haste is not removed by paralyze

### ISSUE THREAD

**Issue by thexamx** [otland/forgottenserver#2284]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Cast utani hur or utani gran hur
2. Wait for monster to paralyse you, I have used ghastly dragon
3. Cast utani gran hur to heal paralyse.

### Expected behaviour
Condition paralyse should overwrite you current casted haste, because if its not then if you cast haste again to remove paralyze it will not remove paralyse just extend your haste condition.
You should be able to have only one condition active paralyze or haste.
https://i.gyazo.com/dbd27dfde28df3518d5caa0c6943341d.png

### Actual behaviour
It is not overwriting, you have paralyze and haste active.

**Comment by raymondtfr** [comment]
Remove subId's from all support spells, or default them to zero.

This is due to changes in a PR of mine. I made a new PR reverting those changes (#2136).

**Comment by thexamx** [comment]
@raymondtfr You are right, it works now.
Should I close this issue?
