### ISSUE TITLE
Monsters melee bug after stair jump

### ISSUE THREAD

**Issue by nekiro** [otland/forgottenserver#2288]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Summon monsters near stairs, make them to not move, just block them with something
2. Go upstairs and downstairs repeatedly just spaming up and down

### Expected behaviour
Monsters should attack once per turn, so once per 2 seconds

### Actual behaviour
Monsters are hitting you everytime you go up and down, without any exhaust.

**Comment by Kamenuvol** [comment]
It should be a general action counter not only melee attack.

**Comment by thexamx** [comment]
@kamenuvol 
What do you mean? I see nothing wrong in their "actions" they are not spamming spells, because they use them once a turn. The only one problem was in extra melee attack after creature dissapear from the screen.

**Comment by rudger** [comment]
Wasn't this implemented to stop people from stairhop hunting?

**Comment by thexamx** [comment]
@rudger Hmm... In real tibia they implemented stairhop exhaust for spells, I don't know anything about exhausting monsters melee.

**Comment by OPfeajoief13** [comment]
Just wanted to say that I remember paladins could stairhop edron behemoths without being hit. Later they fixed it by letting monsters attack faster. But maybe that is completely unrelated to this issue.

**Comment by thexamx** [comment]
I don't know, lets just wait for response, was this intended behaviour or not.

**Comment by Ochmar** [comment]
If I remember correctly, this is **intended**.
I remember back then, there was a Cip post that I can't find. As a rookstayer myself, that was a huge change.

https://tibia.fandom.com/wiki/Updates/8.41 This link _partly_ confirms what I am saying

> A new 2-second-delay for fighting after changing floor level, teleporting, traveling with NPCs, using levitate or getting kicked out of a house; **Stairhopping without getting hit can not be done anymore**.

**Comment by TheSumm** [comment]
The update refers to stairhopping without getting hit at all.
However, if you currently stairhop you will get hit every single time you appear next to a monster, even though most monsters have a melee delay of 2000 milliseconds.
