### ISSUE TITLE
A question about combat magic fields.

### ISSUE THREAD

**Issue by slavidodo** [otland/forgottenserver#2289]
What is the purpose of this piece of code: `(OTSYS_TIME() - createTime <= 5000)` in this line: https://github.com/otland/forgottenserver/blob/master/src/combat.cpp#L1393 ?

**Comment by Mkalo** [comment]
The player that casted the field is only owner for 5 seconds. After 5 seconds the damage caused by the field is not from the player that casted it. I think it's for that purpose.

**Comment by slavidodo** [comment]
The owner remains the owner until he logs out or the field disappears, whichever came first. That's because of `harmfulField` variable.

**Comment by TheSumm** [comment]
Yes, but the damage is not attributed to the owner after 5 seconds.

**Comment by slavidodo** [comment]
Exactly, why should we do that? instead, we can just point the damage to the owner all the time. (without even the harmful variable)

**Comment by TheSumm** [comment]
That's how the game works.

**Comment by ranisalt** [comment]
IIRC this is to prevent abuse. People would often use fields on hunts, then leave the place and another player would sneak up and step over the field, so that the owner get skulled and could be killed at will.

**Comment by slavidodo** [comment]
Yes, that's correct. In addition to that, when e-pvp is enabled that's removed and replaced with a formula depending on the pvp-mode that player used to cast the magic field.
