### ISSUE TITLE
error C1083

### ISSUE THREAD

**Issue by Kuhitacop** [otland/forgottenserver#2291]
\forgottenserver-master\src\otpch.h(42): fatal error C1083: No se puede abrir el archivo incluir: 'boost/asio.hpp': No such file or directory
1>Compilación del proyecto "theforgottenserver.vcxproj" terminada -- ERROR.

**Comment by diath** [comment]
https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows

**Comment by Kuhitacop** [comment]
I followed that guide, still having this error.

**Comment by ranisalt** [comment]
You are either not downloading the required files or not running the required scripts.

**Comment by Kuhitacop** [comment]
I followed the guide full.

**Comment by Kuhitacop** [comment]
reinstalled and had windows 8.1 error, I set up the compiler to windows 10 and worked fine! 💃
