### ISSUE TITLE
errors when compilate

### ISSUE THREAD

**Issue by Kuhitacop** [otland/forgottenserver#2292]
VS is in Spanish I don't know how to change...
I get this errors

1>..\src\game.cpp(3409): warning C4189: 'targetPlayer': la variable local se ha inicializado pero no se hace referencia a ella
1>..\src\player.cpp(680): warning C4100: 'isLogin': parámetro formal sin referencia
1>..\src\protocolgame.cpp(1724): warning C4063: case '2' no es un valor válido para la instrucción switch de la enumeración 'PlayerSex_t'
1>c:\users\adri\documents\relyxia\src\enums.h(266): note: vea la declaración de 'PlayerSex_t'
1>..\src\weapons.cpp(143): warning C4100: 'level': parámetro formal sin referencia
1>..\src\weapons.cpp(148): warning C4100: 'level': parámetro formal sin referencia

**Comment by ranisalt** [comment]
You are not using a clean version of the sources. Please follow the issue template, it is the second time you completely ditch it.
