### ISSUE TITLE
std::move usage inside Protocol::getOutputBuffer

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#2298]
Should we use send(std::move(outputBuffer)) here: https://github.com/otland/forgottenserver/blob/master/src/protocol.cpp#L55
Also which would be the performance gain of std::move? I'm doing this question because tfs is using more and more std::move and its not crystal clear to me why we should use it and where we should use it.
@ranisalt @djarek

**Comment by ranisalt** [comment]
There's not much advantage in moving a pointer. It would avoid incrementing then decrementing the refcount, but not much more than that.

**Comment by HeavenIsLost** [comment]
You can close it, as far i understood std::move is good to prevent to copy huge objects(like lists and other stuff) which can give us performance gain(and removing the usage  of & parameters).
