### ISSUE TITLE
onlinetime change to bigint

### ISSUE THREAD

**Issue by kito2** [otland/forgottenserver#2301]
Hello,

After 9 months having my server online, started to have some errores regarding out of range value at onlinetime column, at players.

I recommend to update it to BIGINT.

**Comment by ranisalt** [comment]
It doesn't make sense. The online time is calculated in seconds and the int width used in the schema can hold up to 11 digits i.e. over 78 years in seconds.

**Comment by EvulMastah** [comment]
11 is the display range. Int is always 4 bytes, in schema it's signed, thus it's range is -2147483648 - 2147483647.

**Comment by ranisalt** [comment]
Yes, and 2**32 has up to 11 digits :) that's what I said. Anyway, if it holds seconds enough for a timestamp, it holds seconds enough for over 78 years of game time. If counting seconds since 1970 still doesn't overflow an int in 2017, how come your players did it in 9 months?

**Comment by kito2** [comment]
Good question, just happened somehow. Thats why I updated to bigint, since
pleople were able to dupe items with this bug, since players didnt save
correctly.

**Comment by ranisalt** [comment]
Are you really using the source code without modifications? It doesn't seem so. Why didn't you use the issue template, though?

**Comment by DSpeichert** [comment]
Signed int in MySQL can have max value of 2147483647 which is 24855 days of `onlinetime`.
