### ISSUE TITLE
Compilation steps on wiki are outdated for debian

### ISSUE THREAD

**Issue by wgrriffel** [otland/forgottenserver#2319]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. follow wiki's guide

### Actual behaviour
apt and cmake fails because there is no mysql anymore, it was replaced with mariadb

### Environment
debian 9

**Comment by ranisalt** [comment]
Fixed :)

**Comment by wgrriffel** [comment]
@ranisalt just replacing mysql with mariadb package doesn't help, cmake still complaining

> CMake Error at cmake/FindMySQL.cmake:116 (MESSAGE):
  Cannot find MySQL.  Include dir: /usr/include/mysql library dir:

replacing cmake recipe to find MariaDB instead helps, a makefile is generated, but ld fails to link mariadb shared libs, then i manually linked everything, worth a note that later on #2175 comes into play, imo it's time to drop mysql and instead supports only mariadb whole all distros

**Comment by ranisalt** [comment]
This is probably an issue with Debian packaging. I literally did nothing to make it work with MariaDB on Arch Linux.

You might need to link some files around to make sure CMake looks in the right places. It needs to find `/usr/include/mysql` dir (link to your mariadb include dir) with `mysql.h` inside (link to whatever header includes everything to mysql stuff)

**Comment by wgrriffel** [comment]
@ranisalt the problem is not with headers, it compiles fine, just linker can't find -lmysqlclient.
