### ISSUE TITLE
Bug: item abilities not work on blockHit

### ISSUE THREAD

**Issue by infister** [otland/forgottenserver#2324]
https://github.com/otland/forgottenserver/blob/24fd556052c1866535d71a633aad1273ed76cb5f/src/player.cpp#L1834

That makes all items past item without abilities reduction not to work properly (no elemental reduction).

**Comment by Codinablack** [comment]
I guess I'll say it.

I don't really understand what you are trying to say here

**Comment by infister** [comment]
Then check the code and try to figure it by yourself. They are doing "return" when "if (!it.abilities) {" occurs. So when that item occurs at helmet slot, anything else will be ignored:

```
const int16_t& absorbPercent = it.abilities->absorbPercent[combatTypeToIndex(combatType)];
		if (absorbPercent != 0) {
			damage -= std::round(damage * (absorbPercent / 100.));

			uint16_t charges = item->getCharges();
			if (charges != 0) {
				g_game.transformItem(item, item->getID(), charges - 1);
			}
		}
```
