### ISSUE TITLE
tfs 1.3 when get vocations players do not save

### ISSUE THREAD

**Issue by popitx** [otland/forgottenserver#2327]
when a player get a new vocation if you logout after get it lost the new vocation

**Comment by ObsidianQ** [comment]
You mean promotion, right?
Happens to me too, i talk to the NPC, he promotes me but after relogin, the promotion goes away and it goes back to its original vocation

**Comment by popitx** [comment]
yeah and always the function player:save() is not working

**Comment by thexamx** [comment]
This is not happening with TFS 1.3.
I'm using it and everything works fine.
Players are saved after logout or when you use /save command.

**Comment by ranisalt** [comment]
Please use the issue template. It seems very clear you are not using the code from this repository.

**Comment by matheusalbino** [comment]
I have the same problem...
