### ISSUE TITLE
Creating ItemType with empty string

### ISSUE THREAD

**Issue by infister** [otland/forgottenserver#2328]
### Before creating an issue, please ensure:
- [+ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [+ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. local itemType = ItemType("")
2. itemType:getId() will be different from 0, as it will point to first item without name:
`<item id="9060" />`

### Expected behaviour
It should return error that there is no such itemtype

### Actual behaviour
It returns item without name.

**Comment by ranisalt** [comment]
And how to create items without name? And wtf are those items without name?

**Comment by thexamx** [comment]
No idea what does this issue means tbh.
Why would you even create item without name?

**Comment by Kamenuvol** [comment]
I agree that it should return an error.

**Comment by infister** [comment]
It is for example <item id="666" name="" /> in items.xml ....

**Comment by Znote** [comment]
If im not mistaken, if you want to purposedly create an item without a name, you can use the id instead to identify what you want to create. 

So if you do want 9060, then use just ItemType(9060).

**Comment by DSpeichert** [comment]
Technically it behaves correctly as it matches the first item with matching name (empty name).
I would agree that it may be odd or unexpected but it actually behaves correctly. Why would we change that to be special case?

I think we will need votes @otland/core ?

**Comment by marksamman** [comment]
I vote for leaving it as it is.

**Comment by ninjalulz** [comment]
I vote for leaving it as it is as well.

**Comment by nekiro** [comment]
If my vote is considered then I would leave it as it is too.

**Comment by Kamenuvol** [comment]
It should return an array with all ids with the name used as parameter.

**Comment by infister** [comment]
When you try in code create ItemType object with empty param, it will match first item without name. This makes /i command broken - try to create non-existent item, for example /i forgottenserver

**Comment by WibbenZ** [comment]
I vote to leave it as it is.

**Comment by WibbenZ** [comment]
Closing due to most of the members voted to leave it as it is.
