### ISSUE TITLE
No BlackSkull spells limitations

### ISSUE THREAD

**Issue by infister** [otland/forgottenserver#2329]
### Before creating an issue, please ensure:
- [+] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [+] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Cast an area spell

### Expected behaviour
It should return cancel message saying you may not use area spells on BlackSkull

### Actual behaviour
There is no limit for spells on blackskull

**Comment by thexamx** [comment]
My attempt to fix this:
https://github.com/otland/forgottenserver/blob/master/src/spells.cpp#L562
```
if (player->getSkull() == SKULL_BLACK) {
	if (aggressive && !needTarget) {
		player->sendCancelMessage(RETURNVALUE_NOTPOSSIBLE);
		return false;
	}
}
```

**Comment by ranisalt** [comment]
`aggressive && !needTarget && player->getSkull() == SKULL_BLACK` on a single if suffices.

**Comment by raymondtfr** [comment]
And the proper cancel message 😄 (don't ask me, I don't remember at all 😄 ).

**Comment by thexamx** [comment]
@raymondtfr isnt it the proper?

**Comment by DanielChabrowski** [comment]
> They also cannot summon or convince creatures, or use Undead Legion or strike spells (i.e. Energy Strike) which are not aimed at a target

What about the situation with Energy Strike? needTarget is set to false but you should be able to cast it if you have a target selected.

**Comment by infister** [comment]
No, according to Tibia wikia, even Energy strike is disallowed.
