### ISSUE TITLE
No StairHoop delay for attacking spells/runes

### ISSUE THREAD

**Issue by infister** [otland/forgottenserver#2330]
### Before creating an issue, please ensure:
- [+] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [+] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Jump on stairs and immediately cast a attacking rune or spell

### Expected behaviour
Should be exhausted for 2s.

### Actual behaviour
You may cast everything, except autoattacking (it seems to be blocked correctly)

**Comment by thexamx** [comment]
Reproduced. You are right. Melee is blocked, but spells are not.

**Comment by ranisalt** [comment]
Isn't it the expected behavior? Spells are... magic and thus not affected by world physics. I'm not sure, it's a long time I don't play Tibia.

**Comment by thexamx** [comment]
@ranisalt if we are talking about vanilla, then spells are treatened just like melee, but only these aggressive spells if im right. I'm not sure tho.

**Comment by thexamx** [comment]
My attempt to fix this issue:
Add this:
```
if (aggressive && player->hasCondition(CONDITION_PACIFIED)) {
	player->sendCancelMessage(RETURNVALUE_YOUAREEXHAUSTED);
	g_game.addMagicEffect(player->getPosition(), CONST_ME_POFF);
	return false;
}
```
Here:
https://github.com/otland/forgottenserver/blob/master/src/spells.cpp#L562

**Comment by infister** [comment]
On RL Tibia, single target runes are allowed (sudden death etc), the rest is forbidden.

**Comment by thexamx** [comment]
@infister single target runes are exhausted too.

**Comment by infister** [comment]
@thexamx Did you check it?

**Comment by thexamx** [comment]
@infister yes

**Comment by simivar** [comment]
I can confirm, single target runes are exhausted too.

**Comment by infister** [comment]
So you did not check it for real. Just enter RL Tibia and cast that rune.... I bet you never did.
