### ISSUE TITLE
No PZ Lock on Paralyze Rune

### ISSUE THREAD

**Issue by infister** [otland/forgottenserver#2337]
### Before creating an issue, please ensure:
- [+ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ +] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Use paralyze rune as druid on another player

### Expected behaviour
I should receive white skull and pz lock

### Actual behaviour
Nothing happens

**Comment by thexamx** [comment]
Actually this is PVP related stuff, are you sure that in old pvp system, which we have here in TFS, paralyze worked like this?

**Comment by infister** [comment]
Can you imagine that now you may use paralyze on non-skulled player , receive no limitations , no white skull and just enter PZ? It is offensive and targeted rune, which is often a key to win a battle, and it works as you would just heal someone? This is illogical.

**Comment by vankk** [comment]
It is suppost to not use receive pz locked, it is working fine. It is how works when I was playing tibia rl like 5 years ago, not sure if they change.

**Comment by simivar** [comment]
I can confirm, it does give pz lock and white skull. I can upload a video if needed as confirmation.
