### ISSUE TITLE
Decaying item stops decaying when you move it

### ISSUE THREAD

**Issue by nekiro** [otland/forgottenserver#2344]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Make item decay, for example make new item in items.xml
2. item:decay()
3. move it to any equipment slot or any other position that it is in currently

This is the item I used:
```
<item id="28826" article="a" name="diamond arrow">
	<attribute key="weight" value="80" />
	<attribute key="slotType" value="ammo" />
	<attribute key="attack" value="37" />
	<attribute key="weaponType" value="ammunition" />
	<attribute key="ammoType" value="arrow" />
	<attribute key="shootType" value="diamondarrow" />
	<attribute key="maxHitChance" value="95" />
	<attribute key="decayTo" value="0" />
	<attribute key="duration" value="3600" />
	<attribute key="showduration" value="1" />
</item>
```

### Expected behaviour
Item should still be decaying

### Actual behaviour
Decaying is stopped.

**Comment by infister** [comment]
Is it in movements.xml with equip/deequip ?

**Comment by thexamx** [comment]
No, it does meant to be. This item should decay from the start, when created.

**Comment by infister** [comment]
I could not recreate this in my server. I was using an item: 

	<item id="2090" article="a" name="crystal key">
		<attribute key="type" value="key"/>
		<attribute key="weight" value="100"/>
        <attribute key="decayTo" value="0"/>
		<attribute key="duration" value="3600"/>
        <attribute key="showduration" value="1"/>
        <attribute key="slotType" value="ammo" />
	</item>

Item was created by NPC, decayed and I was switching it to ammo slot and off few times, logged in or out... It is not in movements too. And it still kept decaying with exact timer. Maybe when using it with a bow as weapon disables decaying?

**Comment by thexamx** [comment]
Maybe because its not actually an ammunition? Also I have it registered in weapons.xml, because its ammunition.

**Comment by infister** [comment]
Paste your weapons.xml entry please

**Comment by thexamx** [comment]
https://github.com/otland/forgottenserver/blob/master/data/weapons/weapons.xml#L702
It's not different from any of these.

**Comment by infister** [comment]
Paste yours entry... it’s important what action you have set there

**Comment by infister** [comment]
Item id 28826 is on my 11.47 server... a tree. I want to point out one more thing. If your ammo does really remove a count, this can be the issue.

**Comment by thexamx** [comment]
What do you mean "does really remove a count"?
Decaying it's working fine while using the item in arrow slot, its removing the count one by one and is still decaying, it stops only when I move it to another slot in backpack or anywhere.

**Comment by Olimpotibia** [comment]
confirmed

**Comment by nekiro** [comment]
Anyone have any thoughts on this which would help to fix the issue? Because I'm going to fix this in my source and make pull request.

**Comment by Kamenuvol** [comment]
There should be a flag to indicate if the item decays on equip, like rings; or decays normally, like corpses.

**Comment by pzaj2** [comment]
Was that fixed already @nekiro ? If not, can you share your progress and let me pick it up?

**Comment by nekiro** [comment]
@pzaj2 nah, it's not fixed. I didn't manage to start working on it, so there is no progress.

**Comment by pzaj2** [comment]
@nekiro ok, so to my understanding your arrows work perfectly fine until they're removed from ammo slot? Are they stackable?

I'm just wondering if that's actually a bug... well, it is, but is that something we should consider possible? What happens if you have 10 arrows with duration X left and 10 arrows with duration Y and you want to stack them together?

**Comment by nekiro** [comment]
@pzaj2 thats a bug. It doesnt matter if you move them out of the stack or not, you cant stack arrows that are not equal, even if these have same attribute and different duration, you cant stack them.

They stop decaying when you move them anywhere from the slot you created them in.

**Comment by pzaj2** [comment]
Alright.

**Comment by lipix** [comment]
no news?

**Comment by Zbizu** [comment]
probably bugged for the same reason as #1753
any idea which commit caused this bug?

**Comment by EvilHero90** [comment]
@nekiro 
does the item decay if you just create it (goes directly into bag/backpack) instead of ammo slot?
From what I can see if you use ammunition it uses the transformto function from game.cpp as the item is obviously in the ammo slot it then fires up onPlayerEquip which then makes the regular checks for level decay and such, the thing now is, once you deequip it, it removes the decay condition as it was deequiped.
This should however not happen if the item is never in the ammo slot in first place.
We would have to introduce a different decay method for this to fully work.

**Comment by nekiro** [comment]
Same thing if it goes to backpack

**Comment by EvilHero90** [comment]
found the problem it was something with Item* Item::clone() const resetting the attributes but not initializing the decay again.
