### ISSUE TITLE
nameDescription (monster attribute) is not working as intended when you "Look" at the monster

### ISSUE THREAD

**Issue by andremiles1** [otland/forgottenserver#2346]
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Spawn any monster that has the attribute `nameDescription` with some letters in uppercase (any unique/boss monster). Example: Demodras has `nameDescription="Demodras"`, unlike a normal monster like a Dragon that has `nameDescription="a dragon"`.
2. "Look" at the monster
3. The result is the name of the monster on its look message is in lowercase. (But when you kill the monster, its name on the loot message is right with all uppercases like it should be on the look message too.)

### Expected behaviour
When the player looks at an unique/boss monster, the message should be like this:
"00:00 You see Demodras."

### Actual behaviour
Instead, we get this:
"00:00 You see demodras."

**Comment by EvulMastah** [comment]
https://github.com/otland/forgottenserver/blob/master/src/monster.cpp#L45
