### ISSUE TITLE
Light items in arrow slot does not change character light

### ISSUE THREAD

**Issue by nekiro** [otland/forgottenserver#2348]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Create frozen starlight
2. Put it on ground when it is night, it glows
3. Put it into your arrow slot, make sure ur not gm

### Expected behaviour
Player should glow with the light of frozen starlight

### Actual behaviour
Light just vanishes, there is no light on player inside of player arrow slot.

https://gyazo.com/cfde7165f1139b8e2ea2b836fb34de45

**Comment by diath** [comment]
What if you add the frozen starlight to movements.xml?

**Comment by thexamx** [comment]
@diath
Same behaviour.

**Comment by thexamx** [comment]
Issue is still present. This commit didnt fix it.

**Comment by vamo89** [comment]
tested with current master, with torch on arrow slot, and works as intended

**Comment by nekiro** [comment]
@vamo89 
Yes, you are right. It was error in my repository. I have probably checked in default repository before #2353.
My bad, I'm sorry. All works fine, closing this issue.
