### ISSUE TITLE
compile in debian 9

### ISSUE THREAD

**Issue by Crock-Linux** [otland/forgottenserver#2355]
when I execute command (cmake ..)
the message below appears in the listing

-- Could NOT find LuaJIT (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR)

*************************
# cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.6 loaded.
-- Performing Test COMPILER_KNOWS_CXX11
-- Performing Test COMPILER_KNOWS_CXX11 - Success
-- Performing Test COMPILER_KNOWS_STDLIB
-- Performing Test COMPILER_KNOWS_STDLIB - Failed
-- Found GMP: /usr/include/x86_64-linux-gnu
-- Found PugiXML: /usr/include
-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib/x86_64-linux-gnu
-- MySQL client libraries: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find LuaJIT (missing:  LUA_LIBRARIES LUA_INCLUDE_DIR)
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   iostreams
--   regex
-- CXX target tfs cotired without unity build.
-- Configuring done
-- Generating done

**Comment by ranisalt** [comment]
As @wgrriffel said, we just check for both. I'd highly recommend LuaJIT, though
