### ISSUE TITLE
Possible crash in scheduler code when the server is shutting down

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#2361]
I was debugging my server with visual studio and after i close the console window to close the server i had a crash here:
https://github.com/otland/forgottenserver/blob/master/src/scheduler.cpp#L47
As the console window had the "Shutting down..." message i think Scheduler::shutdown() has been called before the crash. Inside Scheduler::shutdown() eventList priority queue and eventIds becomes empty. 
Its possible that "ret = eventSignal.wait_until(eventLockUnique, eventList.top()->getCycle());" is waiting for a task to be executed while the Scheduler::shutdown() is called by dispatcher thread and then this code "SchedulerTask* task = eventList.top();" will get a invalid task and make the crash possible.

My fix to this issue is to change this:
`if (ret == std::cv_status::timeout) {`
To this:
`if ((ret == std::cv_status::timeout) && !eventList.empty()) {`

@marksamman @djarek @ranisalt

**Comment by djarek** [comment]
@HeavenIsLost 
Seems you're right. Could you create a PR?
