### ISSUE TITLE
Bug with bank balance

### ISSUE THREAD

**Issue by infister** [otland/forgottenserver#2366]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. set player balance with lua function p:setBankBalance to negative
2. logout to save player
3. check out mysql

### Expected behaviour
Should be 0

### Actual behaviour
Because its unsigned int, its near max range of uint

**Comment by ranisalt** [comment]
So you are reporting a misuse of a command, huh? Should we protect against malicious scripters?

**Comment by kornholi** [comment]
I think the solution would be raising an error in `setBankBalance` instead of silently wrapping

**Comment by ranisalt** [comment]
@kornholi then it should fail, not set to 0, right?

**Comment by infister** [comment]
Probably should fail, right
