### ISSUE TITLE
Question about columns size

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#2372]
We really need use a bigint(20) in [this case](https://github.com/otland/forgottenserver/blob/master/schema.sql#L112)? We shouldn't just use int(11) instead? If not, why?

Thanks.

**Comment by ranisalt** [comment]
It should be a timestamp.

**Comment by vankk** [comment]
Should replace others others int/bigint that is refered to time to timestamp too?

In theses cases for example: [1](https://github.com/otland/forgottenserver/blob/master/schema.sql#L10), [2](https://github.com/otland/forgottenserver/blob/master/schema.sql#L43), [3](https://github.com/otland/forgottenserver/blob/master/schema.sql#L47), [4](https://github.com/otland/forgottenserver/blob/master/schema.sql#L48), [5](https://github.com/otland/forgottenserver/blob/master/schema.sql#L79-L80), [6](https://github.com/otland/forgottenserver/blob/master/schema.sql#L91-L92), [7](https://github.com/otland/forgottenserver/blob/master/schema.sql#L103-L104), [8](https://github.com/otland/forgottenserver/blob/master/schema.sql#L134), [9](https://github.com/otland/forgottenserver/blob/master/schema.sql#L177-L178), [10](https://github.com/otland/forgottenserver/blob/master/schema.sql#L191), [11](https://github.com/otland/forgottenserver/blob/master/schema.sql#L205-L206), [12](https://github.com/otland/forgottenserver/blob/master/schema.sql#L229-L230), [13](https://github.com/otland/forgottenserver/blob/master/schema.sql#L243), [14](https://github.com/otland/forgottenserver/blob/master/schema.sql#L259).

**Comment by ranisalt** [comment]
Maybe. If you are willing to update the schema, keep in mind it probably will only arrive in 2.0

**Comment by slawkens** [comment]
Yes, you're right. It should be int(11).
