### ISSUE TITLE
Chamaleon Rune

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2373]
Chameleon rune is bugged, sometimes players when they finish the condition, become invisible and if change outfit the player takes debbug. I do not know how to reproduce, maybe it's the ending condition while offline or something.

### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.
2.
3.

**Comment by nekiro** [comment]
And you are using 100% clean non modified version of source from this repo?

**Comment by vankk** [comment]
It is working fine here too. I think he is [basing](https://github.com/malucooo/Otxserver-New/issues/667) in OTX repo.

**Comment by GoularPink** [comment]
@nekiro  works fine here too, but in sometimes (I dont know reproduce this) this stay invisible with looktype 0 in data base. Yes basing in OTX repo, but is the same function here

**Comment by nekiro** [comment]
Reproduce this with this repo default code and then we can search for the errors.

**Comment by GoularPink** [comment]
@nekiro  I think nobody use this repo default, cuz nobody host an old otserver 10.98 
We dont have error on screen, when effect is gone the player stay without looktype (I mean player stay with looktype 0). But I dont know when its happens, its only sometimes. Each 100x this will happen 2x

**Comment by nekiro** [comment]
Nobody use this repo default? Then what your issue has to do with this repo? You modified the code, its up to you to fix what you broke or someone else.

**Comment by GoularPink** [comment]
@nekiro 
When you have an otserver with more than 200 online you will see many complaining, there you will see that the problem is not my "modifications", the chameleon code is exactly the same as here.

**Comment by vankk** [comment]
This repository is to we track issues and fix them. You are not using the repo default. You _probably_ are using it in 11.x version. There is nothing that we can do for you. I also tested last time that I commented in this and was working pretty fine.

You should open a thread in OtLand about this issue and waits for an angel knows and anwser.

**Comment by AlexxNica** [comment]
@GoularPink The best way to get help would be to find a way to reproduce what you're experiencing. Without seeing what's going on it's pretty hard to understand and help you.

**Comment by DSpeichert** [comment]
It doesn't look like anybody was able to replicate the issue.
Please post steps to reproduce using only the datapack in this repository.
