### ISSUE TITLE
Its not a issue at all... Its a doubt and a request =)

### ISSUE THREAD

**Issue by diogocamaral** [otland/forgottenserver#2378]
Hi guys!!
First of all, sorry about posting my doubt here and the request also if this isn't the place for that.

I got your release 1.2 and I'm using this with orts (server and map).
And I already finished my first version to put it online my server.

My doubt is... I implemented everything in Windows... If I download it in my server on digitalOcean (linux (ubuntu)) it will work correctly?
If not... How should I do?

This was my question.. rsrs
Now... my request =)

Could you implement skills rates uping by stages like level? example:
lvl 07 - 50 [200x]
lvl 50 - 70 [150x]
lvl 70 - 99 [100x]

I would like to have something like that for skills: 
sword,axe,club,fist
skill 10 - 30 [50x]
skill 31 - 50 [30x]
.... 
magLvl
skill 0 - 20 [10x]

Since now, thank you for attention.
Best regards all

**Comment by WibbenZ** [comment]
Please use the support boards insted, the issues are for reporting bugs etc
https://otland.net/forums/support.16/

@ranisalt @djarek This can be closed.

**Comment by diogocamaral** [comment]
Thank you for reply... Im closing here
