### ISSUE TITLE
Just a doubt. Please could someone answer?

### ISSUE THREAD

**Issue by diogocamaral** [otland/forgottenserver#2380]
Guys,

I got the release 1.2 (forgotten) and I'm using this with orts (server and map).
And I already finished my first version to put it online my server.

My doubt is... I implemented everything in Windows... If I download it in my server on digitalOcean (linux (ubuntu)) it will work correctly?
If not... What should I do?

Since now... Best Regards

**Comment by vamo89** [comment]
You will just need to compile it again when you put it on a linux machine.

**Comment by nekiro** [comment]
There is forum for these type of questions. Next time please ask there.

**Comment by ranisalt** [comment]
The wiki is very clear on this issue: https://github.com/otland/forgottenserver/wiki/Compiling

You can just recompile the server, data files do not change between Windows and Linux.

**Comment by diogocamaral** [comment]
Thank you guys!!!
