### ISSUE TITLE
getDamageMap

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2381]
### Expected behaviour
getDamageMap() It was to capture only the current floor of the script.

### Actual behaviour
getDamageMap() capturing all damage from every floors +1 and -1

int LuaScriptInterface::luaCreatureGetDamageMap(lua_State* L)

**Comment by Schiffers** [comment]
@nekiro @GoularPink doens't know how to explain that issue, but seems like he is reporting about getDamageMap() get values from floors differents than the floor that is the creature used in that function

**Comment by GoularPink** [comment]
@nekiro  Thats the problem, and when there is a boss below the floor, a player is using level spy of the mage Bot, will loot this boss, just seeing.

**Comment by nekiro** [comment]
This is impossible, player must hit the creature to be part of its damage map and btw you are probably talking about reward chest bosses.

https://github.com/otland/forgottenserver/blob/b1839eaf266fddd429dd4f68eca45b4109cb8189/src/creature.cpp#L1060
https://github.com/otland/forgottenserver/blob/b1839eaf266fddd429dd4f68eca45b4109cb8189/src/creature.cpp#L972

**Comment by GoularPink** [comment]
@nekiro  Impossible? https://vimeo.com/247180221 
@ninjalulz  Its a bug man, no close this

**Comment by nekiro** [comment]
Can you realise that the forgottenserver does not have any "reward boss" system?

**Comment by GoularPink** [comment]
The bug is related to getDamageMap() because it is capturing damage from others floors, not just because of the reward system. This may still generate more CPU usage.
