### ISSUE TITLE
Storage Error

### ISSUE THREAD

**Issue by CZacK** [otland/forgottenserver#2383]
Dear;

Lately there are some strange results in my database, as well as the following represented below:

Àé·

Could anyone tell me what this is about?

**Comment by ninjalulz** [comment]
I think you should seek support over at OTLand because this sounds like a common issue that only occurred in TFS 0.3/4 where storage values are stored in text fields.

Please use the issue template next time.

**Comment by CZacK** [comment]
Could you tell me a topic where I can find this?

Cordial greetings;
