### ISSUE TITLE
updateIdleStatus invisible condition

### ISSUE THREAD

**Issue by babymannen** [otland/forgottenserver#2410]
I noticed that if, let's say a stalker, goes invisible with a relative high chance/rate (or even just longer duration) it will never become idle due to 

`if (conditions.empty()) {` 
located in Monster::updateIdleStatus().

Anyone have a creative solution to this "problem"?

**Comment by DSpeichert** [comment]
Sounds like a plausible issue. Can we verify that @WibbenZ ?

**Comment by TheSumm** [comment]
I can confirm this: https://i.imgur.com/9KwCr77.gif

The monster may become idle at some point, but after 30 minutes the stalkers are still moving.

**Comment by babymannen** [comment]
Why are we checking for conditions in this situation? Only had a quick look from file to file and what I fouind didn't make sense to me.

**Comment by ranisalt** [comment]
> Why are we checking for conditions in this situation?

I would bet to avoid idling a monster while it's burning/poisoned/whatever condition a player might inflict.

Maybe if we split into aggressive and passive conditions? Invisibility/haste should not stop a monster from idling.
