### ISSUE TITLE
Cant connect more than 1000 players

### ISSUE THREAD

**Issue by Imperians** [otland/forgottenserver#2419]
**Can I create an issue using tfs 1.2?**
Sorry if I can not but who can help anyway .. I believe it is a tfs bug

### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Server with 1000 players online.
2. Try to connect and you can't.

### Expected behaviour

It should connect normal, since my config.lua is set to "3000"

### Actual behaviour

Nobody connect after 1000 onlines
Sometimes the server stays offline in otservlist, when it has 1000 online

### Environment

Does any other site check player limit, other than waitinglist.cpp?
I'm using tfs 1.2
waitinglist.cpp
https://hastebin.com/dodehesuqo.cpp

**Comment by nekiro** [comment]
This is not a tfs issue, you are probably using Tibia 11, so you have some custom changes in protocol, which could cause these issues.

**Comment by Imperians** [comment]
I got it on screen:

[ServicePort::open] Error: open: Too many open files

**Comment by DSpeichert** [comment]
It's `ulimit` issue, not a bug.

**Comment by Znote** [comment]
To get over 1024, which is the default, use the command:
`ulimit -n 3000`
to increase this limit to 3000.
