### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by Exedenes** [otland/forgottenserver#2427]
so i compiled the server, got my database created and everything.
but what do i do to actually start the server? where is the executable? is it one of these .cpp files and if so how do i run that? i'm on xubuntu.

**Comment by miqueiaspenha** [comment]
Buddy, you need to compile to generate an executable.

The wiki has a lot of information

Compiling on Ubuntu
https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu

Sorry my English. ;)

**Comment by WibbenZ** [comment]
https://otland.net/forums/support.16/

**Comment by Exedenes** [comment]
yeah i compiled and built as i said, i just want to know why there is no executable. no otserv or forgottenserver executable.

**Comment by ranisalt** [comment]
Yes, there is, and it's called `tfs`.

**Comment by Exedenes** [comment]
Thank you !!!!!!!!!
