### ISSUE TITLE
Berserk potion + utito tempo

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2430]
When using a utito tempo + Berserk Potion is only getting the skill of the time, it is not adding up both bonus skill.

Berserk Potion> For 10 minutes, increases by 5 points of your Melee skill (fist, sword, ax or club), but decreases your shielding skill by 10 points.

Utito tempo > Increase your melee skill by 35% for 10 seconds. The spell will only increase the skill for the type of weapon you are using, or it will increase your fist skill if you are not using any.

**Comment by GoularPink** [comment]
@Znote  Yes but the error was mine, I checked and in the global does not really add the skills.

**Comment by Znote** [comment]
@GoularPink Did you solve it? What changes did you do?

**Comment by ninjalulz** [comment]
You can stack conditions of the same type if you use different sub ids.

**Comment by GoularPink** [comment]
@Znote  This not need fix, the system are correctly (does not add skill+skill), this issue doenst exist.. sorry

**Comment by nekiro** [comment]
http://tibia.wikia.com/wiki/Berserk_Potion
This is not a bug.
