### ISSUE TITLE
[Question] Windows exception handlers not working in TFS

### ISSUE THREAD

**Issue by archlightr** [otland/forgottenserver#2434]
This is actually more a kind of question if anyone knows why TFS is not compatible with Window's SetUnhandledExceptionFilter().

### Steps to reproduce (include any configuration/script required to reproduce)
0. This is for windows builds with VS only. Happens both for Win32 and x64 configurations.
1. Add a SetUnhandledExceptionFilter() call in the main() function.
2. Force any kind of unhandled exception (AV, throw, whatever...) on any place of the code (in my case, inside Item::getDescription() to be able to trigger it at will)

### Expected behaviour
The handler specified should be called.

### Actual behaviour
The code inside the handler never gets called. While debugging, I found myself stuck at the exception being thrown once and again and again.

For context, this happens in Windows 7. I made sure the badAllocationHandler isn't the issue (commented it out, same result). Could the problem be the SetConsoleCtrlHandler we are using?

I think being able to make your own crash handler would be very useful, for example for generating minidumps or printing stack traces, would make hunting down access violations or unhandled exceptions way easier.

**Comment by DSpeichert** [comment]
We don't have SetConsoleCtrlHandler anymore. I'm sure this would be a good feature but would only be applicable to a Debug build as a Release build won't probably be able to print a meaningful stack trace anyway. As such, we will welcome a PR if you get this to work. I am closing this for now as it doesn't seem to have much traction anyway.
