### ISSUE TITLE
[Suggestion] premend instead of premdays and lastday

### ISSUE THREAD

**Issue by slawkens** [otland/forgottenserver#2436]
I suggest removing _premdays_ and _lastday_ columns from the table accounts and replace them with _premend_. Why? Its easier to maintain, understand and doesn't require ANY database updates when servers starts or when account is loaded. Its then easier to calculate from database when Premium Account ends, without performing any arithmetical operations on the both values to get the current time.

Also, OpenTibia and many other distros based on it are already using premend, so its some kind of standard.

And finally: it uses less memory, as its only one column instead of two 😃 

What do you guys think?

**Comment by ranisalt** [comment]
If I had a server, I would store premium time on a separate table to track all premium time spells.

That said, I agree that it's much better. `premdays` and `lastday` come from a time it was much harder to handle time on C++, but since `<chrono>` points and durations it is not an issue anymore.

**Comment by pzaj2** [comment]
How far do you think these changes should reach? Only `premiumDays` or perhaps all things involving time arithmetics?
