### ISSUE TITLE
hotkey stop walking

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2439]
In the current tibia global players do not stop anymore when using some hotkey (potions in example).
When we click on the map for the character to go walking, if we using a potion for example (by the hotkey) the character does not stop anymore.

someone could update in the sourcers so the character does not stop too

Movie:
https://i.gyazo.com/a5f12b5edba517ecae154933907554ce.mp4

**Comment by nekiro** [comment]
why? and its client sided not server.

**Comment by jsapparts** [comment]
It's not client-sided it's server-sided. Really simple to fix in source. This happen when using items(rune/potions)
```cpp
bool Actions::useItem(Player* player, const Position& pos, uint8_t index, Item* item, bool isHotkey)
{
	player->setNextAction(OTSYS_TIME() + g_config.getNumber(ConfigManager::ACTIONS_DELAY_INTERVAL));
	player->stopWalk(); // This is what makes player stop moving. Just remove it
        ...
}

bool Actions::useItemEx(Player* player, const Position& fromPos, const Position& toPos,
                        uint8_t toStackPos, Item* item, bool isHotkey, Creature* creature/* = nullptr*/)
{
	player->setNextAction(OTSYS_TIME() + g_config.getNumber(ConfigManager::EX_ACTIONS_DELAY_INTERVAL));
	player->stopWalk(); // Again
        ...
}
```
There's also isHotkey value to check and only stop if !isHotkey, IF neccessary.
I make this change in 0.4 and the char continues to walk when using items on hotkey

**Comment by GoularPink** [comment]
Thank you very much friend, I was looking for and did not found! Can this bring new problems? thinking

**Comment by jsapparts** [comment]
@GoularPink Not really. It was there probably just to replicate the tibia behavior, but now that global change this, it's not needed anymore. Enjoy

**Comment by GoularPink** [comment]
@jsapparts  I tested here and the character continue stoping walking ;o
did you tested in client 10.00?

**Comment by nekiro** [comment]
@jsapparts No, you are wrong, it’s not server-sided.

@goularpink Read the first comment in this issue.

**Comment by jsapparts** [comment]
@GoularPink Sorry, but not. I can't find a working IpChanger for 10.x on linux. What happen is that I make this change in tfs 0.4 and OtClient wich should emulate features like stop on hotkey, and it removes stop walk when using runes and potions.

@nekiro  Yes, seems you're right as him tested and not worked. My bad

**Comment by DSpeichert** [comment]
The current behavior should be correct for 10.98, because that's the currently supported protocol: https://github.com/otland/forgottenserver/blob/020ed5fd36518bbd41894cbdd4478bfa5993260b/src/definitions.h#L29

Question is now - was the character stopping when using a hotkey then?
