### ISSUE TITLE
item:getUniqueID() returns multiple UIDs for the same item.

### ISSUE THREAD

**Issue by DallenB** [otland/forgottenserver#2440]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x ] This issue is reproducible without changes to the code in this repository

### Description
Calling item:getUniqueID() on an item with a UID of 0 will always return a new UID.
It should set the items uniqueID to the new ID
This is a problem because calling
item:getUniqueID()
item:getUniqueID()
item:getUniqueID()
Will return a different UID every time for the same item.

### Steps to reproduce (include any configuration/script required to reproduce)
1. In a lua script call item:getUniqueID() on an item with a UID of 0 (99% of map)
2. In a lua script call item:getUniqueID() on the same item

### Expected behaviour
First Call
The item has a UID of 0
The next available UID is 65542
The item now has a UID of 65542
The function returns 65542
Second Call
The item has a UID of 65542
The function returns 65542

### Actual behaviour
First Call
The item has a UID of 0
The next available UID is 65542
The UID is added to the UID map and not used again
The item does not get the UID 65542 (stays 0)
The function returns 65542
Second Call
The item has a UID of 0
The next available UID is 65543
The UID is added to the UID map and not used again
The item does not get the UID 65543 (stays 0)
The function returns 65543

### Environment
TFS 1.2
Windows 10
Visual Studio 2015

**Comment by ranisalt** [comment]
It is worth noting that:
- `item:getUniqueId()` does not necessarily fetches `Item::uniqueID`, but may be an unique ID for the Lua environment.
- it does not change `Item::uniqueID`, too. It will stay at 0.
- one looking for a fix might try `ScriptEnvironment::addThing`.

**Comment by marksamman** [comment]
I believe this is working as intended. Temporary unique ID's should not persist over dispatcher tasks, the item you are looking for could have been transformed or stacked which could result in a new item pointer. A player holding the item and relogging would also result in a new item pointer. This would also result in a performance overhead when removing items, which may be a significant when items are removed in bulk (e.g. a player logging out).

What's your use case where this is fine and can't be solved in a different way?

**Comment by Leo32onGIT** [comment]
You can stamp items in other ways if you need to reference them across gaps:
ITEM_ATTRIBUTE_OWNER` OR `ITEM_ATTRIBUTE_CUSTOM`

**Comment by Znote** [comment]
https://otland.net/threads/suggestion-unique-item-reference-database-structure.265973/
