### ISSUE TITLE
Guild Rankings

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2442]
### Before creating an issue, please ensure:
- [ x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ x ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Create an guild
2. Make more than 3 rank names (leader, vice-leader, assassins, **healers**...)
3. Enter in game and not will display after third rank name, in this example dont will never appear the **Healers** ranking.

### Expected behaviour

1- Put name ranking on players, rank 1, 2, 3, 4, 5 and should appear in onLook the correctly ranking name for this player.

### Actual behaviour

1- If we configure in the website with 10 rankings, for example: Leader, Vice-Leader, Assassins, Healers, Mages ... only will appear the rankings: Leader, Vice-Leader and Assassins, all others will not appear when look players in the game.

### Environment

Maybe its something related to this code:
https://hastebin.com/rofekuwilo.php

PS. Ranking names displayed correctly on website and DB

**Comment by DSpeichert** [comment]
You're not using latest code.

https://github.com/otland/forgottenserver/blob/06bf9c9ec16ed0d3e9313e40b1266b68a67159cb/src/iologindata.cpp#L416-L425

**Comment by ranisalt** [comment]
It was fixed at #1447

**Comment by GoularPink** [comment]
@ranisalt  you can gimme your contact? discord
