### ISSUE TITLE
getTopParent() {invalid}

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2445]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. script onMove player.lua
`if toPosition.x == CONTAINER_POSITION and toCylinder and toCylinder:getTopParent() and toCylinder:getItemHoldingCount() >= 5 then
			self:sendCancelMessage("NOT POSSIBLE")
			self:getPosition():sendMagicEffect(CONST_ME_POFF)
			return false
		end`
2. Move item to backpacks inside others backpacks, we can move (wrong)

### Expected behaviour

1- avoid moving more than 5 items inside backpacks

### Actual behaviour

1- More than 5 itens inside, we can move another itens inside others backpacks (dont checking the parent correctly).

example movie:
https://gyazo.com/fe6c16bbf743f5aa2387f9480f171cf2

The same thing happens at container.cpp

**`ReturnValue Container::queryAdd(int32_t index, const Thing& thing, uint32_t count,
		uint32_t flags, Creature* actor/* = nullptr*/) const
{
	bool childIsOwner = hasBitSet(FLAG_CHILDISOWNER, flags);
	if (childIsOwner) {
		//a child container is querying, since we are the top container (not carried by a player)
		//just return with no error.`**

tried:
`if (getItemHoldingCount() >= 5) {
		return RETURNVALUE_CONTAINERNOTENOUGHROOM;
	} `
In this case the items are adding in another backpacks inside the TopParentbackpack, until complete 5 itens in slots. Example, if have 2 backpacks inside, will add 5 items in each backpacks, we can add infinite if add backpacks and more backpacks.

**Comment by TheSumm** [comment]
Your script does not cover that scenario. Please ask on the support board ( https://otland.net/forums/support.16/ ) if you need help with the script.

**Comment by GoularPink** [comment]
@TheSumm  toCylinder:getTopParent()  dont cover? hm
