### ISSUE TITLE
Eternal character list means eternal premium time

### ISSUE THREAD

**Issue by TwistedScorpio** [otland/forgottenserver#2446]
Premium time should be updated even when a player logs in.
On my server I've had people get free premium time by never closing the character list, hence not calling Game::updatePremium,

**Comment by okk3** [comment]
Hello,

I totally get your point but I still think the premium should be updated on server start.

You can remove premium account days via login, but that's just a feature that doesn't seem that important to have on the master repository.

Kindest Regards,
okke

**Comment by TwistedScorpio** [comment]
Updating premium time upon server boot means that if server boots and a player has 2 hours left of premium, how is the server then going to know the premium time expired? It has to be on upon player and account login.

**Comment by Kamenuvol** [comment]
every login it should add event with time left duration

**Comment by soul4soul** [comment]
On Cipbia you can stay logged in on one character until server save if your premmy expires during the day. Once your premmy expires relogging to the same or another character on the account will cause you to loose premmy even if you keep the character list up. To me that means they check premmy time on login.

**Comment by firdaus3318** [comment]
Apa fungsi serfer? Tolong jelaskan kepada saya
