### ISSUE TITLE
Player:onMoveItem not called on using item on ground on another position more than three squares away

### ISSUE THREAD

**Issue by DallenB** [otland/forgottenserver#2447]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Enable Player:onMoveItem 
`<event class="Player" method="onMoveItem" enabled="1" />`
1. in events/scripts/player.lua: Player:onMoveItem() add 
`print("onMoveItem Triggered")`
 at the top.
2. Right click an item, such as a battle axe (ID: 2378)
3. Left click on a position more than two squares away from the battle axe.

### Expected behaviour
Player:onMoveItem is triggered. And you can check the items UID or AID to decide whether the player can pick it up.

### Actual behaviour
Player:onMoveItem is not triggered. Player picks it up regardless of its UID or AID.

### Environment
Tested on Both TFS 1.2 Release and TFS 1.3 recent [commit](https://github.com/otland/forgottenserver/commit/96073bdeb80d96ecc30330b90e42ec3ad7dd2366)

**Comment by conde2** [comment]
Use With is different from Move, onMove is triggered when dragging an item from a position to another position or between containers

**Comment by Tarliton** [comment]
Maybe related with #1572?

**Comment by TheSumm** [comment]
He is talking about using an item on the ground on an object not adjacent / close to the item. This will cause the player to walk to the item, pick it up, walk to the target location and use it there.

https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L2011-L2040
