### ISSUE TITLE
Kick character

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2450]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Login
2. Go to non-logout zone
3. Causes some debbug (any type, can be an item that is not inside the client)
4. open the client again and walk normal, you will be kicked from game

### Expected behaviour

continue in the game, since the area is non-logout

### Actual behaviour

kicked from the game in non-logout area

**Comment by DSpeichert** [comment]
You have not included enough information for us to be able to look into it.

**Comment by GoularPink** [comment]
@DSpeichert 

Login in your character
Go to non-logout zone
Causes some debbug in yourself (any type, can be an item that is not inside the client)
open the client again and walk normal, you will be kicked from game after some seconds and will appear on temple

**Comment by GoularPink** [comment]
this is invalid, that was a custom script
