### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2457]
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x67ff90125700 (LWP 1667)]
0x00000000004255ec in Item::isRemoved (this=<optimized out>) at item.h:768
768				return !parent || parent->isRemoved();

error log:

https://hastebin.com/usapujuled.m

maybe related to this bug reported:
https://github.com/otland/forgottenserver/issues/996

items.cpp
https://hastebin.com/ugukonokit.cpp
items.h
https://hastebin.com/zobujihusu.cpp

item.cpp
https://hastebin.com/rekimelawe.cpp
item.h
https://hastebin.com/usozozocag.m

game.cpp checkDecay
https://hastebin.com/duwevodexi.cpp

any ideas?
I'm using tfs 1.2

**Comment by Vulcanx** [comment]
you're not using tfs 1.2, this doesn't belong here.
