### ISSUE TITLE
[QUESTION] OTB Binary Files

### ISSUE THREAD

**Issue by nettoMain** [otland/forgottenserver#2458]
I've a simple(?) question, that's not well explained on the wiki
How does the OTB files  — the one for the map, and the one for the items — work?
Also, why do we have a binary AND a xml file for the server items? It's a bit messy
Sorry if it's explained somewhere on the sources, but I couldn't find so it's the reason why I'm asking here :p 
greets;

**Comment by ranisalt** [comment]
The OTB file contains binary, static information about items: how they interact with the map (hangable, movable, pushable, dimension, etc). Its XML partner describes items in a dynamic way: names, counts, types, anything to be changed freely.

OTBM (*not* OTB) is similar to OTB, with binary, static data about the map such as floors, tiles, walls, etc. Its XML partners, spawn and house, are self explaining (and to be changed freely!)

**Comment by nettoMain** [comment]
Thanks ;-)
I have been reading the loader code of the OTB file (_not_ OTBM hahah), and I couldn't understand it. Though, I've understood the xml item props loader.
I think that it's a fault on my knowledge about bitwise operations, am I right?

**Comment by ranisalt** [comment]
Not really, the format is legacy and indeed messy. XML is a generic, widely used storage format and we are working on moving out of handcrafted binary files (#2206 #2139)
