### ISSUE TITLE
Database downgrade option

### ISSUE THREAD

**Issue by slawkens** [otland/forgottenserver#2461]
So there's an option to upgrade your database to the latest version - done with migrations.

But what when you want to do vice versa (move back to the previous version) - and downgrade your database? The reason may be different. Support for the older client versions is one of them.

Shouldn't that be an option?

Let me hear your opinions!

**Comment by ranisalt** [comment]
> Support for the older client versions is one of them.

Client support is independent from database version. I can't think of a reason that coudn't be fixed with proper server modification instead.

**Comment by DSpeichert** [comment]
I think this feature would be so rarely used and so infrequently tested that it isn't worth maintaining. We don't support downgrading the client version in the main tree, why would we support downgrading the DB? It serves no purpose for the features offered in our repo.
