### ISSUE TITLE
Where is compiled output?

### ISSUE THREAD

**Issue by Kuhitacop** [otland/forgottenserver#2487]
Hello,

I compiled with F7, 0 errors, I got confirmation msg of compiled OK, but now I can't find the output...

Which is the path? Help pls

Thanks!

**Comment by Kuhitacop** [comment]
F7 is the hotkey to compile in visual studio as guides say
Windows 10, 64 bits, visual studio community 2017 with vcpkg

**Comment by DSpeichert** [comment]
look in somewhere in  `vc14/...`

**Comment by Kuhitacop** [comment]
I can only find this:
https://gyazo.com/4c9343cea1ce8b11617872a15c0fad73

And inside that .vs folder there is "forgotten" folder and inside it, this:
https://gyazo.com/c3670fd0de52fa31399e912995a6d5c2

There are no built files...

**Comment by DSpeichert** [comment]
For 64bit, the exe will be in `vc14\x64\Release\theforgottenserver-x64.exe`.
E.g.: https://ci.appveyor.com/project/kornholi/forgottenserver/build/job/aiy20ii82j5p7dxc/artifacts
Use https://otland.net/forums/support.16/ to ask questions.
