### ISSUE TITLE
Invalid authentification token

### ISSUE THREAD

**Issue by Kuhitacop** [otland/forgottenserver#2489]
Hello, I compiled correctly, I just changed protocol to this:

https://gyazo.com/42ad44605e658090a2121e57113bf1cb

`static constexpr auto STATUS_SERVER_NAME = "Bliss Server";
static constexpr auto STATUS_SERVER_VERSION = "1.0";
static constexpr auto STATUS_SERVER_DEVELOPERS = "Kuhi";

static constexpr auto CLIENT_VERSION_MIN = 854;
static constexpr auto CLIENT_VERSION_MAX = 872;
static constexpr auto CLIENT_VERSION_STR = "8.6";`

When I login to my account I'm getting this error: Invalid authentification token

**Comment by ranisalt** [comment]
You are not using this repository codebase.

**Comment by Kuhitacop** [comment]
Yes I am https://github.com/otland/forgottenserver/blob/master/src/definitions.h
That's the repository code I edited... I didn't edit anything else

**Comment by ranisalt** [comment]
You can't just modify the client version and call it a day. The protocols change a lot from version to version, and 10.98 is not compatible with 8.5~8.7.
