### ISSUE TITLE
monster generate loot behaviour

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#2490]
### Expected behaviour
should generate loot when monster spawn

### Actual behaviour
currently generates loot when monster dies?

## Why make this change?
so spawned monsters can have light from the items they drop (example, life crystal, fire axe) etc.

**Comment by TheSumm** [comment]
Monsters no longer work like that.

**Comment by DSpeichert** [comment]
> so spawned monsters can have light from the items they drop (example, life crystal, fire axe) etc.

I don't understand what you mean here. Can you explain that better?

**Comment by emil92b** [comment]
@TheSumm strange, what update did they remove it?
@DSpeichert if a monster is about to drop a life crystal, you can see the light from the item around the monster before it dies

**Comment by emil92b** [comment]
@CristoferMartins yes

**Comment by TwistedScorpio** [comment]
It is like that in Tibia 7.7, are you guys sure it still doesn't happen in real Tibia? Given that CIP is still using the same server structure?

**Comment by CristoferMartins** [comment]
@TwistedScorpio i got some doubts since it may conflict with the prey system now(which generates the loot again like its a second death).
