### ISSUE TITLE
ID ranges in XML

### ISSUE THREAD

**Issue by rottylunia** [otland/forgottenserver#2491]
hello,

why is it no longer possible to for example register multiple ids with ; and - as seperator in files like actions.xml?
u could do for example aid="5000-5100" script="bla.lua" and it would register all aids with these numbers in the past
or aid="1924;4281;4284;4291" script="bla.lua" and it would register all those numbers before (nvm about this, as pointed out you can use fromid and toid now)

and why storage numbers cant be stored as both numbers and letters anymore?
for example it could be nice in some situations
1 example, u have a player command that lets them set their own discription when a player looks at them, this could be saved in storage values before 
or another example, when a monster gets killed, it could count +1 on the storagevalue with the same name as the monster, then player can look at this monster and see how many total monsters of it has killed. but in my last example u could for example convert all monsters to some number instead but its more works

and its also good for organizing stuff i think, for example now u have to do something like this to organize;
have all quest storages at maybe 4000->4500
have all npc storages at maybe 5000->5500
or i think most ots just take random numbers and hope its works, but if we could do strings again we could for example do
quest1->quest500
npc1->npc500

im just wondering why these things were dropped, because before it was alot easier to register multiple ids in xml files, and using letters inside storagevalues was a nice way of saving some custom stuffs, i understand u can save through different ways but it was nice to have

**Comment by emil92b** [comment]
<action fromid="x" toid="y" script="xxx.lua" />

**Comment by DSpeichert** [comment]
Please use proper title next time.

**Comment by rottylunia** [comment]
proper title???
lol

the title was right from the start, u changed it to one small part about my question

**Comment by ranisalt** [comment]
> and why storage numbers cant be stored as both numbers and letters anymore?

Numbers are more efficient than letters in a lot of aspects. Just use a map from text to number where you need it

```lua
local storage = {
    ["storage"] = 12345
}
...
player:setStorageValue(storage["storage"], 1)
```

**Comment by rottylunia** [comment]
ranisalt
hmm yes thats what i kinda meant that u can convert monster names to some number

but for example, for stuff like this it wont work
Like player say '!mydescription I am cool guy' and I want to store it somewhere
obviously u could store it in some global table maybe, but i think they get reset at restart? and saving it into some new database value is bad too since i think it laggs server,,, especially if u got many players and u need to get such a value alot

but in tfs 0.4 this would be possibel
and sure maybe having only numberts will increase performance by a tiny tiny bit, but still here we have pull requests that increase performance by a lot more than this (pathfinding is one example), and they still arent ADDED XD

**Comment by vankk** [comment]
In a global server should be better storage on letters than numbers.

**Comment by rottylunia** [comment]
yes @ranisalt thats kinda what i meant with u can convert monster names to numbers instead, but it wont work with first example, where players use a command to save a string inside a storage

and i dont rly buy that it's deleted for performance, i have made changes in database in my own server to support strings and i dont see anything changing, MAYBE if you have server with hundreds of players it will affect performance a very tiny bit, but here we have also pull requests that will improve performance by a lot more and yet we dont see these things added

**Comment by rottylunia** [comment]
@andersonfaaria 
haha fun fact, its actually kinda what they did in this version of tfs also, the pathfinding checks for new paths every 1second instead of just updating its path for every time it moves which i think it did in past versions.
this system that currently exists can make monsters wait up to 1 second for it to start walking again, it feels very bad to play with. 

How it works currently:
https://www.youtube.com/watch?v=sKCYpVWS9gM

How it works in all past ots versions, even in old ancient xml days:
https://www.youtube.com/watch?v=ouL58kGsZJI

**Comment by kornholi** [comment]
Supporting string keys in player storage is a legitimate feature request. If you want to argue that it's too slow, implement it and show some benchmarks to support your claim.

**Comment by ranisalt** [comment]
I didn't specify _performance_ efficient, because it is _space_ efficient for memory and database storage, and the performance hit is irrelevant considering everything else that hurts it. There is *no* loss of functionality since you can map storage names to storage IDs, as I exemplified.

Personally, I am indifferent to that being implemented back. I wasn't here when it was removed and I completely agree that it is a fine feature to have.

That said, one willing to implement that would need to work on [these](https://github.com/otland/forgottenserver/blob/master/src/player.h#L342-L343) functions and figure out how to handle [reserved storage keys](https://github.com/otland/forgottenserver/blob/master/src/const.h#L555-L565).

Alternatively, use [`std::hash`](https://en.cppreference.com/w/cpp/string/basic_string/hash) to convert strings to integers in a collision-avoiding way and hope nothing breaks.

**Comment by andersonfaaria** [comment]
No loss of functionality? Let me ask you something, if I map someone's name in a table through a spell, will I be able to reach this table in creaturescripts?

Also, why they removed global storages from database? Events are way harder to control when you store an environment variable that will simply disappear upon server reset.

**Comment by ninjalulz** [comment]
@rottylunia @andersonfaaria The functionalities that you are referring to has actually **never** been a part of the C++ codebase.

@andersonfaaria You will be able to access a table from a creature script if you declare it as **global** (Simply don't define **local** before the identifier).

Regarding your concern about _global storages_
- Create a database table
- Load them in **onStartup**
- Save them in **onShutdown**

**Comment by andersonfaaria** [comment]
So, this changed in recent versions of TFS right? In the past each folder had a different environment and even with global tables (literally if you created a global table in lib) each environment would have a different version of the same clean table, which mean no connection between scripts.

About the global storages, I know how to do it and personally I don't need it, but it's easier for everyone that relies on this repository if you guys didn't break the compatibility when changing versions, otherwise we can just throw away those useless compat libs.
Why removing the global storage from db to start? 99% of the events from 0.4 uses this

**Comment by ninjalulz** [comment]
Well, what you see today is actually based on the 0.2 branch, and not the 0.3/0.4 where these things existed.

**Comment by rottylunia** [comment]
actually tfs 0.2 had global storages, but its true that 0.2 just used storagevalues as numbers as we do right now

**Comment by Kamenuvol** [comment]
2 maps of storage: <int, int> and <int, string> should be enough. DB can support both in same table.

**Comment by DSpeichert** [comment]
If you want to request string-based global storage, create a new issue just for that. This issue tries to capture two different things, one of which (`why is it no longer possible to for example register multiple ids with ; and - as seperator in files like actions.xml`) is already possible and the other one never existed in TFS 1.0. Note that TFS 0.3/0.4 was a completely different source code base. TFS 1.0 matured from 0.2 and has never removed features that didn't exist.

**Comment by rottylunia** [comment]
sryt for discusing
