### ISSUE TITLE
Why the RSA keys are hardcoded?

### ISSUE THREAD

**Issue by Mirandatz** [otland/forgottenserver#2493]
Seriously, that doesn't make any  #sense.
If the keys are hardcoded and known to the public (open source project), why even bother with encryption?

**Comment by djarek** [comment]
Related to #2216 
Note that a lot of people want to be able certain *other* clients with TFS so dropping the current encryption (which is really bad even if you don't count the hardcoded RSA keys) would force them to use OTC.

**Comment by Mirandatz** [comment]
#2216 is a far better proposal. I'll close this one.
