### ISSUE TITLE
monster look direction

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#2494]
### Expected behaviour
https://i.imgur.com/rHccNho.png

### Actual behaviour
https://github.com/otland/forgottenserver/blob/bcb86eac0655c58b8dc9a35c652f8953a0edd033/src/monster.cpp#L1836

**Comment by DSpeichert** [comment]
And the problem is?

**Comment by emil92b** [comment]
@DSpeichert 
try it out yourself and compare with the image i provided, you can do so by trapping a monster and walk around it and see which direction it is facing.

the problem is that the direction is not coded correctly for monster in some squares.

**Comment by slavidodo** [comment]
@emil92b You are filing a bug, i think you should post both expected and actual behavior.

You posted expected in an image. Then post the actual in a companionable image.

**Comment by emil92b** [comment]
@slavidodo or you can just recode it after the expected image, i don't see a point in making another image of the broken code (which i did include btw). feel free to spend that time yourself making the image if you really think it is needed.

**Comment by vankk** [comment]
You are reporting a bug and expects that we try based on a image?!

Please provide more information about it and not just a stupid image that you think that it should be.

**Comment by emil92b** [comment]
and you expect me to sit another 30min to draw you a picture instead of just clicking a link that takes 30seconds. wtf dude?

**Comment by joseluis2g** [comment]
Wtf
