### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by Sempervirens256** [otland/forgottenserver#2495]
Hello, 2 friends and i compiled the source on Visual studio 2017 with vcpkg (followed the guide in this github) and got no errors while building, on different computers,  and when we try to load the server (Windows 10) the server starts and then closes without any errors, the following is the output from the command promt:

```
C:\local\forgottenserver\x64\Release>theforgottenserver-x64
The Forgotten Server - Version 1.3
Compiled with Microsoft Visual C++ version 14.1
Compiled on Aug 28 2018 03:36:52 for platform x64

A server developed by Mark Samman
Visit our forum for updates, support, and resources: http://otland.net/.

>> Loading config
>> Establishing database connection... MySQL 10.2.6
>> Running database manager
>> Loading vocations
>> Loading items
>> Loading script systems
>> Loading monsters
>> Loading outfits
>> Checking world type... PVP
>> Loading map
> Map size: 1000x1000.
> Map loading time: 0.2 seconds.
>> Initializing gamestate

C:\local\forgottenserver\x64\Release>
```
Are we doing something wrong? sorry if this is not enough to open a issue on the github.
Thanks in advance.

Edit: I should add that i haven't modified the source in any way.

**Comment by Sempervirens256** [comment]
> Can you run the server from MSVS in debug mode? (Local Windows Debugger)
> That will tell you exactly why it's crashing.

After running the server in debug mode i got an unhandled exception

`Unhandled exception at 0x00007FF7246F9120 in theforgottenserver-x64.exe: 0xC000001D: Illegal Instruction. occurred`


The exception seems to be originating from the following code snippet (line 10) on the `xutility` include in this path `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xutility`



```
1. _Diff operator()(_Diff _Index)
2. 		{	// adapt _Urng closed range to [0, _Index)
3. 		for (;;)
4. 			{	// try a sample random value
5. 			_Udiff _Ret = 0;	// random bits
6. 			_Udiff _Mask = 0;	// 2^N - 1, _Ret is within [0, _Mask]
7. 
8. 			while (_Mask < _Udiff(_Index - 1))
9. 				{	// need more random bits
10. 				_Ret <<= _Bits - 1;	// avoid full shift
11. 				_Ret <<= 1;
12. 				_Ret |= _Get_bits();
13. 				_Mask <<= _Bits - 1;	// avoid full shift
14. 				_Mask <<= 1;
15. 				_Mask |= _Bmask;
16. 				}
17. 
18. 			// _Ret is [0, _Mask], _Index - 1 <= _Mask, return if unbiased
19. 			if (_Ret / _Index < _Mask / _Index
20. 				|| _Mask % _Index == _Udiff(_Index - 1))
21. 				return (static_cast<_Diff>(_Ret % _Index));
22. 			}
23. 		}

```
Thread: `ucrtbased.dll thread`

Stack Frame:`>	theforgottenserver-x64.exe!std::_Rng_from_urng<__int64,std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> >::operator()(__int64 _Index) Line 4030	C++
`

Does this means there's a problem with my MSVS installation or the latest update? can it be fixed from my end?

Any help is appreciated, thanks in advance.

**Comment by DSpeichert** [comment]
Try the solution in this thread: https://otland.net/threads/illegal-instruction-on-compilling.259997/

**Comment by Sempervirens256** [comment]
Worked perfectly, thanks a lot.
