### ISSUE TITLE
Crash during 'Initializing Gamestate'

### ISSUE THREAD

**Issue by theshibbies** [otland/forgottenserver#2498]
I was referred here from Otland support page here:
https://otland.net/threads/tfs-1-3-stoped-working.260502/

When starting my server with the new vcpkg on Windows 10 in Visual Studio 2017 I experience an issue when Initializing Gameserver.

![untitled1](https://user-images.githubusercontent.com/43316702/45597356-1055e680-b999-11e8-84c5-e648fa913b9d.png)

Full Callstack:
theforgottenserver-x64.exe!std::_Rng_from_urng<unsigned int,std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> >::operator()(unsigned int _Index) Line 3949	C++	Non-user code. Symbols loaded.
 	
theforgottenserver-x64.exe!std::uniform_int<int>::_Eval<std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> >(std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> & _Eng, int _Min, int _Max) Line 2331	C++	Non-user code. Symbols loaded.
 	
theforgottenserver-x64.exe!std::uniform_int<int>::operator()<std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> >(std::mersenne_twister_engine<unsigned int,32,624,397,31,2567483615,11,4294967295,7,2636928640,15,4022730752,18,1812433253> & _Eng, const std::uniform_int<int>::param_type & _Par0) Line 2287	C++	Non-user code. Symbols loaded.
 	
theforgottenserver-x64.exe!uniform_random(int minNumber, int maxNumber) Line 313	C++	Symbols loaded.

theforgottenserver-x64.exe!Game::addCreatureCheck(Creature * creature) Line 3576	C++	Symbols loaded.
 	
theforgottenserver-x64.exe!Game::placeCreature(Creature * creature, const Position & pos, bool extendedPos, bool forced) Line 558	C++	Symbols loaded.
 	
theforgottenserver-x64.exe!Spawns::startup() Line 135	C++	Symbols loaded.
 	
theforgottenserver-x64.exe!Game::setGameState(GameState_t newState) Line 118	C++	Symbols loaded.
 	
theforgottenserver-x64.exe!mainLoader(int __formal, char * * __formal, ServiceManager * services) Line 252	C++	Symbols loaded.
 	
theforgottenserver-x64.exe!Task::operator()() Line 41	C++	Symbols loaded.
 	
theforgottenserver-x64.exe!Dispatcher::threadMain() Line 62	C++	Symbols loaded.

**Comment by DSpeichert** [comment]
Check #2495

**Comment by theshibbies** [comment]
Thanks! I'll make sure to research through threads more before posting next time.
