### ISSUE TITLE
What is the difference between Scheduler and Dispatcher

### ISSUE THREAD

**Issue by Humberd** [otland/forgottenserver#2512]
I've been wading through the code and stumbled upon this line of code
https://github.com/otland/forgottenserver/blob/master/src/scheduler.cpp#L54

The scheduler places tasks in a priority queue and when the time comes for the task to be executed it is placed in another queue, but this time inside a Dispatcher. What is the purpose of the Dispatcher? Why don't we execute the task in the Scheduler without bringing another layer of code?

**Comment by djarek** [comment]
Game world logic is not thread-safe and Dispatcher and Scheduler both run in their own threads. Invoking tasks in the scheduler would result in a datarace.
