### ISSUE TITLE
Missions within the same storage

### ISSUE THREAD

**Issue by rookgaard** [otland/forgottenserver#2515]
While using the same storage in multiple missions in one quest having:
- `storage = 3` first mission is completed - OK
- `storage = 4` first mission disappear, second shows - not OK

Adding `ignoreendvalue="true"` in first mission causes:
- `storage = 3` first mission is completed - OK
- `storage = 4` first mission is still completed, second shows - OK

I've created PR #2514 with that, but I think it doesn't coverage problem until the end. Personally, I would set the `ignoreendvalue` in `quests.cpp` to true by default, and then set it to false if needed in XML for mission entry. But it's only my opinion that's why I've created this issue.

**Comment by ranisalt** [comment]
Maybe it's because you have a typo?

**Comment by rookgaard** [comment]
You mean `strorage` in my description? Fixed, but that was only an example, not the code.

**Comment by rookgaard** [comment]
As #2514 is merged, I'm closing this issue.
