### ISSUE TITLE
Food Stats

### ISSUE THREAD

**Issue by GoularPink** [otland/forgottenserver#2536]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Use a Life ring (or any regeneration item)
2. Relog
3. Eat food

### Expected behaviour

1- Should start counting the time in stats
http://prntscr.com/ms17bq

### Actual behaviour

1- Dont start counting
2- Remove the regeneration item and this will start
3- Relog, the time goes to 0 again

### Environment

https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L2915

**Comment by joseluis2g** [comment]
esto lo arregle hace un tiempo :p
