### ISSUE TITLE
Unpassable and movable item teleport bug

### ISSUE THREAD

**Issue by mattyx14** [otland/forgottenserver#2537]
### Before creating an issue, please ensure:
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. If you throw an unpassable item(for example a movable coal basin(2604)) into a teleport, if you throw another the item may be teleported back to the original position. And block teleports

### Expected behaviour
on picture form a cipsoft RL
[Actual error](https://imgur.com/a/Qc3p5sc)

### Actual behaviour
I show it in the video
[how reproduce](https://gyazo.com/fcc08eabbffcc229ac203d2f49257052)

**Comment by DSpeichert** [comment]
Can regular players move movable basin?

**Comment by mattyx14** [comment]
Port this to tfs 1.3 ... Otx 2 is base 0.3.7

**Comment by DSpeichert** [comment]
You are welcome to submit a PR.
