### ISSUE TITLE
Stealth ring bug

### ISSUE THREAD

**Issue by gregorecruzeiro** [otland/forgottenserver#2549]
### Before creating an issue, please ensure:
- [X ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. When removing the stealth ring ID 2202 from the slot (ring) the player continues in the invisible condition, however the mosntros can attack him
2.
3.

### Expected behaviour

Back outfit before using the rin
### Actual behaviour

The player continues with invisible outfit

**Comment by jo3bingham** [comment]
This is probably related to #2550.
