### ISSUE TITLE
Fix #2541 Client Crash

### ISSUE THREAD

**Issue by gregorecruzeiro** [otland/forgottenserver#2550]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Attack a monster, Warlock for example, after a short time the client crash
2.
3.

### Environment

Fix crash when removing conditions in pre-death script

After this fix, when dueling with monsters, after a certain time, the client about a crash, defaced the update and the crash on the client stopped.

logs client.
https://uploaddeimagens.com.br/imagens/erro_1-png-4ecbc314-d266-47e4-a060-576b2daab3d1

https://uploaddeimagens.com.br/imagens/erro_2-png-29f34445-d081-4046-9c67-d1822fa8edd4

https://uploaddeimagens.com.br/imagens/erro_3-png-f60ecc8e-8cec-4409-8860-75a2e27d03af

**Comment by raymondtfr** [comment]
I can confirm this.

**Comment by Znote** [comment]
#2541 @jo3bingham

**Comment by jo3bingham** [comment]
Will have a look when I'm home from work this evening. The crash reason, and the creature tested on, implies this probably has to do with the invisibility condition.

**Comment by raymondtfr** [comment]
Unfortunately, it still crashes @jo3bingham .

**Comment by jo3bingham** [comment]
@raymondtfr thanks for testing. I'm struggling to see how my changes are causing the issue as all it does is change how the condition is removed from the array and deleted from memory. The original functionality of ending the condition is still there. I'll see what I can come up with.

**Comment by nekiro** [comment]
Why isnt the change implemented into Game::cleanup? Same with toreleaseconditions vector

**Comment by jo3bingham** [comment]
@nekiro because it doesn't need to be? Conditions are cleaned up in the `Creature` deconstructor.

**Comment by nekiro** [comment]
I didnt mean it needs to be there, isnt it better to have all in one place?

**Comment by nekiro** [comment]
Also if creatures dies with „pending” conditions, wouldnt that create memory leak?

**Comment by jo3bingham** [comment]
> I didnt mean it needs to be there, isnt it better to have all in one place?

It just doesn't make sense to have it there. Conditions are tied to creature logic, not game logic.

> Also if creatures dies (creature object is deleted) with „pending” to delete conditions, wouldnt that create memory leak?

The `toReleaseConditions` vector is just a placeholder of `Condition` pointers that need to be cleaned up, and those pointers are still present in the `conditions` list. Once the creature's reference counter hits 0, and the creature is deleted from memory, it's deconstructor will be called and its remaining conditions cleaned up. Then the std::vector deconstructor will clean up `toReleaseConditions`. So, no, it wouldn't create a memory leak.
