### ISSUE TITLE
Server doesnt send the hungry condition

### ISSUE THREAD

**Issue by pegason** [otland/forgottenserver#2556]
This was an important function that was found in other old and / or customized versions that was lost over time.

### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
[1.] Open server (fresh files)
[2.] Open Client
[3.] Be yourself

### Expected behaviour

1 - You are hungry, the hunger icon is sent and appears on the client.
2 - You eat something, the icon disappears.
![image](https://user-images.githubusercontent.com/49088829/55272708-558b9700-529f-11e9-9189-3f102c89ec9c.png)

### Actual behaviour
1 - the hunger icon is not sent to the client (otclient or tibia default).
2 - Nothing happens;
![image](https://user-images.githubusercontent.com/49088829/55272705-3c82e600-529f-11e9-821e-e5180dd7a3f9.png)

**Comment by Olrios** [comment]
Hungry icon was inplemented after Tibia 11.02. TFS is using 10.98. Hungry icon was in tibia.spr before inplementation to the game. We can make it work but it may not work in Cipsoft client 10.98.

**Comment by omarcopires** [comment]
Fix: https://github.com/otland/forgottenserver/commit/7b0974e6b808b9e98a3bb1e182a36275d564228d

**Comment by Zbizu** [comment]
It's an issue with otc. It works fine in QT client even without the fix.
