### ISSUE TITLE
Can not load folder 'scripts\lib'.

### ISSUE THREAD

**Issue by andreluiz93** [otland/forgottenserver#2564]
Hello, after compiling and run the tfs, i'm getting an error.

>>The Forgotten Server - Version 1.3
>>Compiled with GNU C++ version 6.3.0 20170516
>>Compiled on Apr 16 2019 22:53:00 for platform x64

>>A server developed by Mark Samman
>>Visit our forum for updates, support, and resources: http://otland.net/.

>> Loading config
>> Establishing database connection... MySQL 10.1.37-MariaDB
>> Running database manager
>> Loading vocations
>> Loading items
>> Loading script systems
>> Loading lua libs
[Warning - Scripts::loadScripts] Can not load folder 'scripts\lib'.
> ERROR: Unable to load lua libs!
> ERROR: Failed to load script systems
>> No services running. The server is NOT online.

The scripts\lib are on the data folder, i'm just clone the repository.... 

Somebody help-me?

**Comment by LucasCPrazeres** [comment]
Hi, change this:
https://github.com/otland/forgottenserver/blob/master/src/scriptmanager.cpp#L69
for this:
if (!g_libs->loadScripts("scripts/lib", true)) {

**Comment by EvilHero90** [comment]
which os are you using?
