### ISSUE TITLE
Crash when reload

### ISSUE THREAD

**Issue by Vulcanx** [otland/forgottenserver#2567]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Log on to an admin character
2. Try to /reload any reload type
3. Crash

### Expected behaviour
It should reload.

### Actual behaviour
It crashes.

Running VS Debugger shows me the error is in LuaScriptInterface::luaDeleteAction
The exception is:
```
Exception thrown: read access violation.
*(*(__imp_lua_touserdata(...))) was nullptr.```

**Comment by raymondtfr** [comment]
#2566
