### ISSUE TITLE
Fireball rune

### ISSUE THREAD

**Issue by Jarofir** [otland/forgottenserver#2572]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Use fireball rune (id 2302)

### Expected behaviour
The rune should be usable without target. Normally that rune gives area effect like GFB but smaller.
### Actual behaviour
Here it gives 1 tile effect like HMM. Also you have to aim creature to shoot.

### Environment
`<rune group="attack" spellid="15" name="Fireball Rune" id="2302" allowfaruse="1" charges="5" level="27" magiclevel="4" cooldown="2000" groupcooldown="2000" needtarget="1" blocktype="solid" script="attack/fireball_rune.lua" />`
I suggest to delete ` needtarget="1" `.

Another thing is to change combat in fireball_rune.lua to following:
```
local combat = Combat()
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_FIREAREA)
combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_FIRE)
combat:setArea(createCombatArea(AREA_CIRCLE2X2))
```

**Comment by raymondtfr** [comment]
Try removing tag ``needtarget="1"`` from ``spells.xml`` or just assigned ``0`` to it, i.e. ``needtarget="0"``.

**Comment by joseluis2g** [comment]
Fireball rune is not like original game spells, you can take a loot at any wiki

**Comment by raymondtfr** [comment]
I just tested it on vanilla. **Fireball Rune** needs a target for it to be used. I am confused.

![tibia-fireball-rune-test](https://user-images.githubusercontent.com/6445979/57044986-a72e9500-6c42-11e9-9be8-9a6140f4252a.PNG)

I also tested it on a creature, and it does not have an area, instead it is cast to a single target only.
![tibia-fireball-rune-shot-at-creature](https://user-images.githubusercontent.com/6445979/57045378-c548c500-6c43-11e9-8f3a-b0271663d6ed.PNG)

**Comment by joseluis2g** [comment]
> I just tested it on vanilla. **Fireball Rune** needs a target for it to be used. I am confused.
> 
> ![tibia-fireball-rune-test](https://user-images.githubusercontent.com/6445979/57044986-a72e9500-6c42-11e9-9be8-9a6140f4252a.PNG)
> 
> I also tested it on a creature, and it does not have an area, instead it is cast to a single target only.
> ![tibia-fireball-rune-shot-at-creature](https://user-images.githubusercontent.com/6445979/57045378-c548c500-6c43-11e9-8f3a-b0271663d6ed.PNG)

Im sorry, just tested and yeah, its working as intended. My bad.

**Comment by Jarofir** [comment]
Allright. I based my opinion on how i've remembered Tibia, since I play for 15 years.
![obraz](https://user-images.githubusercontent.com/19214612/57063613-22845b00-6cc4-11e9-8ed1-a94f25da7852.png)
They have changed how this rune works in one of updates. Now it's like HMM or Icicle.
Case closed. Thank you for your patience.
