### ISSUE TITLE
GlobalEvent interval method problem (revscriptsys)

### ISSUE THREAD

**Issue by danielsalim1** [otland/forgottenserver#2577]
When using "globalevent:interval(interval)" is assigning a range for all events, that is, all scripts, not individual.

That is, if I use a "save" and a "clean map" script, and set one of them in a range, this will work for everyone, and that is totally wrong.

**Comment by EvilHero90** [comment]
Do you want a certain event to be executed at a special time like 9am or do you want this event to trigger like every half a second?
Because `:interval` is used for the execution time between
While `:time("09:00")` is used to execute something at the exact time.

**Comment by danielsalim1** [comment]
For every half second for example, it would be globalevent: interval (500), but when I register in any file, it assigns to all globalevents, that is, it is totally wrong. The "interval" method is set for all events.

**Comment by EvilHero90** [comment]
fixed in #2578

**Comment by danielsalim1** [comment]
Yes, fixed, thanks a lot.

**Comment by danielsalim1** [comment]
There is another small problem, globalEvent->getName() is returning an empty string in duplicate.

see the photo:
http://prntscr.com/nl5z7n

**Comment by EvilHero90** [comment]
are you setting the name for the event properly like `local event = GlobalEvent("nameInHere")`?

**Comment by danielsalim1** [comment]
Yes, I'm setting it right.

```LUA
local globalevent = GlobalEvent("save")

function globalevent.onThink(interval)
	saveServer()
	return true
end

globalevent:interval(900000)
globalevent:register()
```

**Comment by EvilHero90** [comment]
hit me up on discord, so I can take a further look into this `Evil Hero#8530`
