### ISSUE TITLE
drop loot error

### ISSUE THREAD

**Issue by gregorecruzeiro** [otland/forgottenserver#2609]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.  Every time he kills a monster and drops a bag, it comes empty, does not come loot inside the bag
2.
3.

**Comment by joseluis2g** [comment]
Are you using the correct files?

**Comment by gregorecruzeiro** [comment]
yes, i use this repository

**Comment by souzajunior** [comment]
U checked your stamina?

**Comment by EPuncker** [comment]
can you tell us which monster exactly is doing it? because since I remember there is no bag in monsters anymore, so they were all removed from loot

**Comment by gregorecruzeiro** [comment]
You can close It. Loot 100%, Sorry
