### ISSUE TITLE
Regeneration not working (food and conditions)

### ISSUE THREAD

**Issue by trunksagain** [otland/forgottenserver#2614]
I was creating a regeneration condition, so I noticed that the player did not gain life or something, and since the food has the same "mechanism" I tried to eat some food to see if my life was rising, but without success, it returns to me I am full, but nothing increases. The condition is created, but it does not work.
![Screenshot_21](https://user-images.githubusercontent.com/52322799/60345431-68d9fb80-998f-11e9-893f-0f3971f48886.png)

**Comment by joseluis2g** [comment]
it is working.

**Comment by trunksagain** [comment]
> it is working.
> Actually sending the stats again to the client is not working.

How did u tested? Did u create a new regeneration condition? For me, this is not working, :/. See: https://otland.net/threads/condition-not-working.265145/

**Comment by souzajunior** [comment]
This is working perfect, maybe some implemetation on your source caused this bug.

**Comment by joseluis2g** [comment]
time is not working, you first check what is he asking

**Comment by souzajunior** [comment]
> time is not working, you first check what is he asking

The question he brought here is the regeneration condition is not working, and it's working perfect. I didn't mention about the client part. It's already related in #2556. If he uses same nick on Discord, he related it was solved because he was using a custom map, and for some reason, it's was not working.

**Comment by trunksagain** [comment]
Solved. I was making a test in protect zones (wich it is does not works)
