### ISSUE TITLE
Small Typo in Items.xml

### ISSUE THREAD

**Issue by GauzStudio** [otland/forgottenserver#2621]
Sorry, I don't have time to make pull request to fix this right now but thought maybe someone would be interested... =)

At:
<item id="23537" article="a" name="mooh'tah plate">
		<attribute ky="description" value="It can only be wielded properly by knights and paladins." />
		<attribute key="armor" value="12" />
		<attribute key="slotType" value="body" />
		<attribute key="weight" value="12500" />
	</item>

attribute "key" is misspelled as "ky"

**Comment by pegason** [comment]
Here is the line with the fix:

```
    <item id="23537" article="a" name="mooh'tah plate">
        <attribute key="description" value="It can only be wielded properly by knights and paladins." />
	<attribute key="armor" value="12" />
	<attribute key="slotType" value="body" />
	<attribute key="weight" value="12500" />
    </item>
```
