### ISSUE TITLE
meele damage not taking armor/shielding into account?

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2622]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. fight any monster that uses <attack name="melee" interval="2000" min="0" max="-45"/>

### Expected behaviour
monster melee damage should be reduced by our shielding and armor

### Actual behaviour
monster melee damage ignores everything and hits hard even an armored and decent shielding knight (mages etc)

**Comment by joseluis2g** [comment]
how did you tested it? do you have any kind of logs or something? what monster was used and what kind of equipment you wore.
