### ISSUE TITLE
Critical problem with reload of the revscriptsys (CreatureEvent)

### ISSUE THREAD

**Issue by Lyuzera** [otland/forgottenserver#2623]
### Steps to reproduce
1. Just /reload scripts with some players online (need some creatureevent scripts)

### Expected behaviour
Reload correctly

### Actual behaviour
Players lose his registers, playerdeath.lua stop working and others (happens sometimes)

I think that is a problem when try load all CreatureEvents again

**Comment by danielsalim1** [comment]
There is a real problem, we can talk to @EvilHero90 to fix it.
