### ISSUE TITLE
Warning not displaying the source file that need the change

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2629]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. just use setCombatCondition on any script
2. run the exe
3.

### Expected behaviour
It would be cool if it told us the file path/name that has it so we can change it

### Actual behaviour
tell us nothing
![2019-07-15 16_27_54-Window](https://user-images.githubusercontent.com/4684880/61243130-b095ac80-a71d-11e9-8d49-61ddd1f5e01a.jpg)

**Comment by Flyckks** [comment]
MAS ESSE EPUNCKER É UM JATO MEU AMIGO
