### ISSUE TITLE
Problem with login to ARM server.

### ISSUE THREAD

**Issue by EgzoT** [otland/forgottenserver#2631]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Compile TFS on ARM device (in my case ARM64).
2. Login to account, from high IP number (in my case 192.168.43.1).
3. Characters list was appear -> choose character -> **Connection failed. (ERROR 10061)**.
4. Login to account, from low IP number (in my case 127.0.0.1).
5. Characters list was appear -> choose character -> **ALL WORKS FINE**.

### Expected behaviour
Login to server from ip addresses > 2,147,483,647

### Actual behaviour
Connection failed for ip addresses > 2,147,483,647

### Environment
ARM64, Debian 9

### Other information
Maybe my diagnosis is wrong but, I'm may connect to server (open character list) from other ip than 127.0.0.1 but I don't may log in to game. In 127.0.0.1 (localhost) all works fine.

Maybe two cases is not enough to detect problem (one for ip higher than 2,147,483,647 and one for ip lower than 2,147,483,647). But I don't have any other idea.

For the curious, I was finded this issue when I was written tutorial "Run TFS on Android device without Root permissions".

**Comment by Znote** [comment]
192.168* sounds like a typical LAN ip range. 

Have you configured it in config.lua?
https://github.com/otland/forgottenserver/blob/af649d061180faaa3e64205d3da6e6fe74a5f1f1/config.lua.dist#L18-L19

If this server is accessed through a router, ensure ports 7171-7172 is TCP routed to that machine.

**Comment by EgzoT** [comment]
Ehh, it's been newbie mistake ...
Yeah, this is problem with ip.
In one hand i'm glad that all works but in other hand I'm nervous on myself.

So, Android with Termux + TFS works great.
Thx @Znote
