### ISSUE TITLE
Bug with the new revscriptsys moveevent slot

### ISSUE THREAD

**Issue by eduardodantas95** [otland/forgottenserver#2633]
When trying to equip the item, it will not even follow all the requirements.

![image](https://user-images.githubusercontent.com/8551443/62593072-e3117000-b8ab-11e9-9024-ac295cffc479.png)
![image](https://user-images.githubusercontent.com/8551443/62593180-3388cd80-b8ac-11e9-8b79-a7f8e7b3a879.png)

![image](https://user-images.githubusercontent.com/8551443/62593086-ec024180-b8ab-11e9-926e-49ba495645fc.png)

When trying to equip the item:
![image](https://user-images.githubusercontent.com/8551443/62593102-f6244000-b8ab-11e9-8852-5e83d8948fd7.png)

As it is in the script:

> local cobraBoots = MoveEvent()

> cobraBoots.onEquip = defaultEquip

> cobraBoots:id(35229)

> cobraBoots:type("equip")

> cobraBoots:slot("feet")

> cobraBoots:vocation("knight", true, true) -- showInDescription / lastVoc

> cobraBoots:vocation("elite knight")

> cobraBoots:level(220)

> cobraBoots:register()

Note: If I use the flag in items.xml

> slotType" value = "feet"

It works normally.

**Comment by EvilHero90** [comment]
That's actually not a bug, it's been ever since like that, if you do not specify in items.xml what kind of slot the item is intended to go to, then you are not able to dress it in equipment slots.

**Comment by eduardodantas95** [comment]
> That's actually not a bug, it's been ever since like that, if you do not specify in items.xml what kind of slot the item is intended to go to, then you are not able to dress it in equipment slots.
> The ':slot' function for moveevents in this case just tells in which slot it should check for requirements (level, vocation) and such and not if the item is equipable to 'that' certain slot.

Oh ... I'm sorry. kkk
I thought it was similar to weapons slotType
Thanks for the response.
