### ISSUE TITLE
Badger drops wrong badger fur

### ISSUE THREAD

**Issue by Wirox** [otland/forgottenserver#2636]
Badger drops the decoration (https://tibia.fandom.com/wiki/Badger_Fur_(Decoration)) instead of the creature product (https://tibia.fandom.com/wiki/Badger_Fur).

I believe the correct id is 11216, not 7965.

**Comment by Znote** [comment]
https://github.com/otland/forgottenserver/blob/master/data/monster/Misc/Misc%20Mammals/badger.xml
