### ISSUE TITLE
doSetCreatureLight meta alternative?

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2642]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

is it intended that we have no meta table option for doSetCreatureLight? there is a creature:SetLight but it doesn't accept time parameter so it really can't replace the doSetCreatureLight

**Comment by EvilHero90** [comment]
actually doSetCreatureLight is basicly a condition
You should be able to do it like:
```lua
local condition = Condition(CONDITION_LIGHT)
condition:setParameter(CONDITION_PARAM_LIGHT_LEVEL, ?)
condition:setParameter(CONDITION_PARAM_LIGHT_COLOR, ?)
condition:setParameter(CONDITION_PARAM_TICKS, ms)
creature:addCondition(condition)
```

**Comment by EPuncker** [comment]
thanks
