### ISSUE TITLE
hasCondition not working properly

### ISSUE THREAD

**Issue by maattch** [otland/forgottenserver#2648]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Create any condition and add ticks by parameter with value -1
2. Add it to creature
3. Try to check if the creature has condition by using _hasCondition_

### Expected behaviour
Function should return true

### Actual behaviour
Function return false

**Comment by EvilHero90** [comment]
show us the entire script you are using as an example.

**Comment by maattch** [comment]
@EvilHero90 
````lua
local talkAction = TalkAction("/test")

talkAction.onSay = function(player, words, param)
	local condition = Condition(CONDITION_ATTRIBUTES)
	condition:setParameter(CONDITION_PARAM_TICKS, -1)

	player:addCondition(condition)
	print(player:hasCondition(CONDITION_ATTRIBUTES))
	return true
end

talkAction:register()

**Comment by EvilHero90** [comment]
You might want to try to add a subId
```lua
local talkAction = TalkAction("/test")

talkAction.onSay = function(player, words, param)
	local condition = Condition(CONDITION_ATTRIBUTES, 10)
	condition:setParameter(CONDITION_PARAM_TICKS, -1)

	player:addCondition(condition)
	print(player:hasCondition(CONDITION_ATTRIBUTES, 10))
	return true
end

talkAction:register()
```
been quite a while since I worked with Conditions.

**Comment by EvilHero90** [comment]
After taking a closer look this is indeed a bug which happens when you certainly use ticks as -1, it'll automaticly return false.
I'll get a PR ready once I found a good solution on how to handle this.
