### ISSUE TITLE
RSA key.pem file footer blank

### ISSUE THREAD

**Issue by Riicksouzaa** [otland/forgottenserver#2660]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Expected behaviour

docker needs be able to run with a docker run command.
RSA key have a whitespace in footer and it broken when server shows up.
gesior needs a key to work in configdist

### Actual behaviour

server does not go up when started by docker command

### Environment

Dockerfile and docker-compose

**Comment by DSpeichert** [comment]
See #2661
