### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by Riicksouzaa** [otland/forgottenserver#2662]
Hello people.

I am learning about docker and I think it would be of great value to the project to add a way to asynchronously componentize the server and website as well as the database and the creation of an http proxy service for the server along with site go up in minutes in a new environment.

I started a repository which uses this project and a GESIOR website, but nothing prevents changing the website as needed.

Anyway, anyone who wants to take a look at the repository and want to contribute or give tips or even criticize will be very happy to respond.

**Comment by DSpeichert** [comment]
Is this a feature request? Or a discussion? Or advertisement?

**Comment by Riicksouzaa** [comment]
discussion. [here have an example](https://github.com/Riicksouzaa/FerobraTfsDocker)

**Comment by DSpeichert** [comment]
Discussions go in the forums, not here.

**Comment by Znote** [comment]
Post it here: https://otland.net/forums/the-forgotten-server-development.511/
