### ISSUE TITLE
item:decay(decayId) - LUA modifies all items on server

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#2665]
I'm not sure, if this code is working as it should:
```
int LuaScriptInterface::luaItemDecay(lua_State* L)
{
	// item:decay(decayId)
	Item* item = getUserdata<Item>(L, 1);
	if (item) {
		if (isNumber(L, 2)) {
			ItemType& it = Item::items.getItemType(item->getID());
			it.decayTo = getNumber<int32_t>(L, 2);
		}

		g_game.startDecay(item);
		pushBoolean(L, true);
	} else {
		lua_pushnil(L);
	}
	return 1;
}
```
You call this function on some ITEM object and it modifies 'decayTo' for ALL ITEMS WITH SAME ID (for ItemType, not for 1 item).

It's only used in one place in `data` ( data/actions/scripts/other/music.lua ):
```
	if instrument.transformId then
		player:say(instrument.text, TALKTYPE_MONSTER_SAY, false, nil, item:getPosition())
		item:transform(instrument.transformId)
		item:decay(instrument.decayId)
	end
```

**Comment by raymondtfr** [comment]
This function was updated by me in #2360 to be able to decay the specified item back to its original id? (I can't quite remember now, [but you can see here](https://github.com/otland/forgottenserver/pull/2360/commits/abaa3f55f7686c6cf24126c55664ad159414b047)). It seems to me I introduced a bug?

**Comment by gesior** [comment]
@raymondtfr 
It looks like you made that little bug there. I just commited fix for it, but I did add my debug LUA file by mistake. I will have to prepare new commit for PR.
