### ISSUE TITLE
Medusa Terra Strike life drain attack doesn't have variable effect count

### ISSUE THREAD

**Issue by soul4soul** [otland/forgottenserver#2671]
For XML attacks attribute count has no effect and is not supported by TFS attack xml implementation. It is used incorrectly for the medusa's life drain attack.
https://github.com/otland/forgottenserver/blob/6d71dd5ec064e9e302d2f970d9fafaaadda8e7c1/data/monster/Geo-Elementals/medusa.xml#L23

From [TibiaWiki Medusa](https://tibia.fandom.com/wiki/Medusa)
>1 to 5 Terra Strike simultaneously, (75-150) (does Life Drain Damage )
>

This attack should be moved to a lua script.

**Comment by nekiro** [comment]
How does that work? Medusa casts it instatly 5 times in the same time or its somehow delayed per cast?

**Comment by ayushidokwal** [comment]
How this is moved to Lua script?

**Comment by soul4soul** [comment]
> 
> 
> How does that work? Medusa casts it instantly 5 times in the same time or its somehow delayed per cast?

I don't have a character I can test with. Assuming the tibiawiki information is correct. I watched some videos on youtube, I only ever see a single terra strike animation. Based on my observations, the animation happens once and damage is dealt 1 to 5 times.


> 
> 
> How this is moved to Lua script?


Spell written in lua scripts can be used by a monster as an attack. For organization purposes monster spells written in lua are placed in `data/spells/scripts/monster/`

And called from a monster like this.
https://github.com/otland/forgottenserver/blob/23438962cf3e5ae40243e7e2c8dc3173095fd77b/data/monster/Djinn/blue_djinn.xml#L38

**Comment by Znote** [comment]
How exacly should `Medusa Terra Strike life drain attack` work? Like an envenom rune that shoots an enemy and applies 5 ticks of damage over the course of x(?) seconds?

**Comment by TheSumm** [comment]
I think this can be achieved by adding the same attack multiple times with varying chances.

**Comment by soul4soul** [comment]
> 
> 
> How exacly should `Medusa Terra Strike life drain attack` work? Like an envenom rune that shoots an enemy and applies 5 ticks of damage over the course of x(?) seconds?

I don't know, I'm just going by tibiawiki and what I can gather from youtube. I don't have any cipbia characters which can handle a medusa to check it out myself. I interrupted it to be something like envenom but all hits would happen at once with a max of 5 hits.

This was the comment for the last change to the `terra strike attack life drain attack`.
```
Changed abilities to better reflect their behavior. Their lifedrain attacks are not that strong individualy but can hit pretty hard when she shots all 5 at the same time.
```

Maybe what @TheSumm is suggesting is correct.
