### ISSUE TITLE
AddEvent Question

### ISSUE THREAD

**Issue by luanluciano93** [otland/forgottenserver#2680]
Because when I use an addEvent () calling a local function that is inside the same script returns error. Is that right?

**Comment by Znote** [comment]
Nope. addEvent works fine with local functions, presumably because the local functions or environment is passed on to the event. 

![image](https://user-images.githubusercontent.com/1552144/67132589-7e5a8600-f209-11e9-8090-e7e31bacbd89.png)

**Comment by TheSumm** [comment]
You might be passing a userdata object. In that case the error message should indicate that.

Please use the issue template in the future and include the scripts that are required to reproduce the issue as well as the error message you have received.
