### ISSUE TITLE
 Comparing onThink () and onTime ()

### ISSUE THREAD

**Issue by luanluciano93** [otland/forgottenserver#2681]
Let's suppose I have a 1500 player otserv online, and you would have both:
• use a save every 3 hours apart using on onThink ().
• use multiple saves using onTime () (put one every 3 hours).
Which would consume less of the server?

**Comment by Znote** [comment]
`onTime()` (globalevent) because it will iterate and see if the script should be executed once. (or once twice a second). 

Instead of twice a second, for every player online. (3000 checks every second). 
Assuming onThink is attached to every player as a creaturescript.

**Comment by luanluciano93** [comment]
Thanks
