### ISSUE TITLE
Item charge conflicting.

### ISSUE THREAD

**Issue by souzajunior** [otland/forgottenserver#2684]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Create an item with charge attribute.
Example:
![Screenshot_17](https://user-images.githubusercontent.com/36310159/67170458-580f2480-f388-11e9-9fcc-e8b3437247b2.png)

2. See the description, it'll show only 1 charge.
![Screenshot_16](https://user-images.githubusercontent.com/36310159/67170332-87716180-f387-11e9-806a-a6af61aa8285.png)

### Expected behaviour
Show all charges declared in items.xml.

### Environment
I made a test in  `Item::getDescription(const ItemType& it, int32_t lookDistance, const Item* item /*= nullptr*/, int32_t subType /*= -1*/, bool addArticle /*= true*/)` too see why it's returning 1, because when we set the charge by `item:setAttribute(ITEM_ATTRIBUTE_CHARGES)`, it works fine (you can test it now using enchating.lua in data/actions).
![Screenshot_11](https://user-images.githubusercontent.com/36310159/67170464-5f363280-f388-11e9-9d1a-104651a93e7c.png)

**Comment by Sickness-chan** [comment]
How did you create the item? You may have created it like `/i bonfire amulet, 1`, which would yield only 1 charge. Try putting it in a monster's loot list and see if it drops with the proper amount of charges.

**Comment by Lyuzera** [comment]
I think it's not a problem, because when the item have charges, count is = charge. See this example:

`/i might ring, 94`
```
02:04 You see a might ring (protection physical +20%, energy +20%, earth +20%, fire +20%, ice +20%, holy +20%, death +20%) that has 94 charges left.
```

**Comment by souzajunior** [comment]
I forgot to check the constructor, thank you. Yeah, maybe I create a custom function to use addItem with charges in multiple quantity. Ty, guys, closing issue.
