### ISSUE TITLE
Tile::getClientIndexOfCreature perfomance question

### ISSUE THREAD

**Issue by Eternal-Scripts** [otland/forgottenserver#2696]
I was studying the source of the forgotten server and i checked some functions where can affect more the cpu usage.

So... for now i have something big, when some creature move (specially a player) he executes the Map::moveCreature
And to get the oldstackpos of every creature, in many times he executes that function here.
https://github.com/otland/forgottenserver/blob/master/src/tile.cpp#L1176

So my question is: is not better make a variable to creature for storing the current stackpos instead of looping every time to get the stackpos?

**Comment by nekiro** [comment]
I dont think this or other functions are called so often this would make any difference.

**Comment by Eternal-Scripts** [comment]
In that point you are wrong, that function is called every time a creature move and execute a loop for every player around.
But yes, using a variable and updating him is the best solution.

**Comment by nekiro** [comment]
If the loop is executed each time you move it doesnt mean it affects your cpu usage noticeable. As I said use any profilling tool to check how much that change gives you.
As far as I remember the worst cpu eaters are decay system and spectators (which was improvedba lot recently by mark). If you feel like changing that is a big deal, open pull request, but make sure you include some statistics how it changed before and after.

**Comment by marksamman** [comment]
You would need tons of creatures on the same tile for this to matter. It is not worth adding more complexity to the codebase to cache stackpos.
