### ISSUE TITLE
Potions count on use

### ISSUE THREAD

**Issue by karimadnan** [otland/forgottenserver#2725]
### Expected behaviour

using potions on hotkeys should return a message with the amount of potions left which in fact happens but if i have 300 potions and use 1 potion i'll get a message like this:
using one of 300 mana potions..
which is fine but if i have 299 potions and use 1 potion then this happens:
using one of 99 mana potions..
it don't count the actual amount it only counts the amount on the stack i'm using from.

**Comment by EPuncker** [comment]
![aea1431e-bf1a-4775-97ec-a0327f839b52](https://user-images.githubusercontent.com/4684880/69456693-07556780-0d4a-11ea-9e09-104e29262f2c.gif)
confirmed

**Comment by EPuncker** [comment]
maybe related to #2604

**Comment by nekiro** [comment]
I see you didn't test it on main master repository, can you do it? Also does it happen with any vial or just these that got subtype, like milk, bear etc.

**Comment by EPuncker** [comment]
> I see you didn't test it on main master repository, can you do it? Also does it happen with any vial or just these that got subtype, like milk, bear etc.

it is the main master, the only thing I changed was to support new sprites, and I don't know how to test with vials that got subtype since they aren't stackables, the issue seems to be only with potions
