### ISSUE TITLE
Wrong behavior of monsters with distance attacks.

### ISSUE THREAD

**Issue by Slayertico** [otland/forgottenserver#2727]
**This issue is reproducible on Tfs 1.2**

Steps to reproduce (include any configuration/script required to reproduce)
Look for some monster that needs distance from you to attack.
Example: Warlocks

**Expected behaviour** -  I will upload a movie here, this will make understanding easier
https://streamable.com/h2uxk

In this case, the monster tries to go to the player to attack him.

**Actual behaviour** [Wrong] -  the movie here.
https://streamable.com/3jlj3

the monster is standing attacking the target, when he should go to the player and come back.

Environment
Using Windows 10, 64 bits.

Does anyone have any suggestions to fix this?
what is the function responsible for this behavior?

**Comment by EPuncker** [comment]
my guess is this code is responsible for it (monster.cpp):

`			//target dancing
			if (attackedCreature && attackedCreature == followCreature) {
				if (isFleeing()) {
					result = getDanceStep(getPosition(), direction, false, false);
				} else if (mType->info.staticAttackChance < static_cast<uint32_t>(uniform_random(1, 100))) {
					result = getDanceStep(getPosition(), direction);
				}
			}`

and here is some footage from both RL tibia and latest TFS:
![image](https://user-images.githubusercontent.com/4684880/69499533-cf792c00-0ed1-11ea-9422-de8634b1e8d2.png)
![image](https://user-images.githubusercontent.com/4684880/69499535-d30cb300-0ed1-11ea-9ba5-b00e7530fffa.png)

**Comment by MillhioreBT** [comment]
If you add this it will have a behavior that is too similar to that of tibia RL

search function `bool Monster::getDanceStep(const Position& creaturePos, Direction& direction,
                           bool keepAttack /*= true*/, bool keepDistance /*= true*/)` on monster.cpp

just above this code `if (!dirList.empty()) {
		std::shuffle(dirList.begin(), dirList.end(), getRandomGenerator());
		direction = dirList[uniform_random(0, dirList.size() - 1)];
		return true;
	}`

add the code mentioned above: `if (dirList.empty()) {
		// extra dancing
		for (uint8_t i = 0; i < 3; i++) {
			Direction dir = static_cast<Direction>(i);
			if (canWalkTo(creaturePos, dir)) {
				dirList.push_back(dir);
			}
		}
	}`

**Comment by Slayertico** [comment]
> If you add this it will have a behavior that is too similar to that of tibia RL
> 
> search function `bool Monster::getDanceStep(const Position& creaturePos, Direction& direction, bool keepAttack /*= true*/, bool keepDistance /*= true*/)` on monster.cpp
> 
> just above this code `if (!dirList.empty()) { std::shuffle(dirList.begin(), dirList.end(), getRandomGenerator()); direction = dirList[uniform_random(0, dirList.size() - 1)]; return true; }`
> 
> add the code mentioned above: `if (dirList.empty()) { // extra dancing for (uint8_t i = 0; i < 3; i++) { Direction dir = static_cast<Direction>(i); if (canWalkTo(creaturePos, dir)) { dirList.push_back(dir); } } }`
> 
> example of final code: https://image.prntscr.com/image/tHF5MmABStGDURwv8053YQ.png
> If someone manages to improve this, or create something different and better, I will be grateful

maybe this is the way, but the creature is a little slow compared to RL Tibia movie

**Comment by MillhioreBT** [comment]
change this: static constexpr int32_t EVENT_CREATURE_THINK_INTERVAL = 1000;
and <flag staticattack="90" />
if the verification is faster, the monster's actions will be faster

**Comment by Olrios** [comment]
Also the issue is more intense when you summon melee monster and you attack a ranged monster which the same movement speed as a summoned melee monster.

Just enjoy the dance :D what they are doing :D

**Comment by Leo32onGIT** [comment]
> and here is some footage from both RL tibia and latest TFS:
> ![Rvg6GAY](https://user-images.githubusercontent.com/4684880/69499588-54fcdc00-0ed2-11ea-9814-7ea0488a9bd6.gif)
> ![XM4kGNl](https://user-images.githubusercontent.com/4684880/69499590-5a5a2680-0ed2-11ea-9a78-920f046cb486.gif)

As far as I can see this is related to:
https://github.com/otland/forgottenserver/issues/1690
https://github.com/otland/forgottenserver/issues/922

It seems the behaviour of isSightClear() is not the same as real tibia(?)

Which means ranged monsters can still hit you when around a corner 2sqm away in TFS (as per gif).
Where in real tibia they can't, the corner cuts line of sight.

This explains both monster movement and spell area/wall behaviour.
