### ISSUE TITLE
Fedora build incomplete

### ISSUE THREAD

**Issue by yuripourre** [otland/forgottenserver#2729]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Follow steps in [Compiling-on-Fedora](https://github.com/otland/forgottenserver/wiki/Compiling-on-Fedora)

### Expected behaviour
Project to build (cmake)

### Actual behaviour
Build fails

### Environment
Fedora

The solution is to include `cryptopp-devel` to libraries.

**Comment by DSpeichert** [comment]
Updated wiki.
