### ISSUE TITLE
Container(item) doesn't work on Item class

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#2732]
### Steps to reproduce (include any configuration/script required to reproduce)
1. ```it = Game.createItem(2365, 1, Position(95, 117, 7))```
2. ```return it:isContainer() -> true```
3. ```return Container(it) -> nil```

### Expected behaviour
getting items for a script through
```Container(it):getItems()```

### Actual behaviour
> attempt to call method 'getItems' (a nil value)

I have to use old workarounds to make my script work:
```getContainerSize(itemUid)```
```getContainerItem(itemUid, slot)```

### Environment
Windows 7 (appVeyor build 10.0.277 (#2720))

**Comment by MillhioreBT** [comment]
Go to https://github.com/otland/forgottenserver/blob/master/src/item.cpp#L92 and remove this `|| it.useable || it.moveable || it.pickupable `

And function Container.getItems here: https://pastebin.com/k2cEgQyw

**Comment by TheSumm** [comment]
`Game.createItem` automatically assigns the `Container` metatable if the item is a container. You do not need to call `Container()`, which only accepts uids anyway.

The method `Container.getItems` is nil because it does not exists.
To get the items:
```lua
local container = Game.createItem(1988, 1, player:getPosition())
container:addItem(2148, 100)
container:addItem(2148, 100)
container:addItem(2148, 100)
player:say(container:getName() .. " created with " .. container:getSize()  .. " items inside.", TALKTYPE_MONSTER_SAY)
for i = 0, container:getSize() - 1 do
	player:say("Item #" .. i .." is " .. container:getItem(i):getName(), TALKTYPE_MONSTER_SAY)
end
```

**Comment by Zbizu** [comment]
@TheSumm 
the problem is when I try to get data on existing item (like player backpack)
it's an item, it returns true for isContainer, but container methods don't work on it
