### ISSUE TITLE
What is max client version supported?

### ISSUE THREAD

**Issue by MBoberski** [otland/forgottenserver#2736]
Hello,

what is max client version supported?

TIA :)

**Comment by Sickness-chan** [comment]
https://github.com/otland/forgottenserver/blob/master/src/definitions.h#L27-L29

**Comment by MBoberski** [comment]
Is there plans to support newest versions?

**Comment by EPuncker** [comment]
mark words: https://github.com/otland/forgottenserver/pull/2464#issuecomment-392544691
in other words: we need to update OTC protocol first in order to update TFS

**Comment by MBoberski** [comment]
Maybe I am wrong but I think OpenTibiaUnity supports newest protocols.

**Comment by EPuncker** [comment]
but OT Client doesn't

**Comment by delusionx** [comment]
There's been plans to upgrade to 11.10 I believe, but I don't think it's a reality yet.
