### ISSUE TITLE
ItemType(nil) creates ItemType(22617) userdata

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#2742]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
```print(ItemType(nil):getId())```

### Expected behaviour
```0```

### Actual behaviour
```22617```

![img](https://user-images.githubusercontent.com/5205079/70551613-24769c80-1b78-11ea-8ac2-52a6b9611691.png)

### Environment
appVeyor build 1.0.299 (x64 windows, from 8 dec 2019), also broken on 1.0.277

**Comment by MillhioreBT** [comment]
The problem is when the function tries to find a string with 0 characters.
The resulting identity is random based on your items.xml

![image](https://user-images.githubusercontent.com/28090948/70552831-70155000-1b50-11ea-92bc-75c01f1388bf.png)

`getString()` takes the nil value and interprets it as an empty string.

**Comment by MillhioreBT** [comment]
The problem is not the functions, the problem is that in your items.xml there are defined objects with an empty name.

per example:
![image](https://user-images.githubusercontent.com/28090948/70556225-d309e580-1b56-11ea-833b-582b8921b594.png)

**Comment by Zbizu** [comment]
shouldn't creating empty strings be prevented in the constructor?

**Comment by MillhioreBT** [comment]
The function can look like this to avoid looking for empty strings:
![image](https://user-images.githubusercontent.com/28090948/70579178-3101f180-1b86-11ea-8963-16fbcbb2f57f.png)
