### ISSUE TITLE
NPC Trade Window cannot distinguish SID's.

### ISSUE THREAD

**Issue by Dramia** [otland/forgottenserver#2743]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Attempting so sell an item with an identical CID but different SID does not work.
2.
3.

### Expected behaviour
Both items should (I think) be sellable under SID.

### Actual behaviour
The NPC trade window seemingly detects both items to be the same. The normal egg (sid:2328) can be sold as both a seagull egg and a normal egg. The seagull egg (sid:12674) is seen by the shop as both an egg an a seagull egg but can be sold as neither.
![afbeelding](https://user-images.githubusercontent.com/56880470/70851010-b4765800-1e90-11ea-8af1-203309439f3e.png)

### Script
```

local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)

function onCreatureAppear(cid)       npcHandler:onCreatureAppear(cid)       end
function onCreatureDisappear(cid)     npcHandler:onCreatureDisappear(cid)       end
function onCreatureSay(cid, type, msg)     npcHandler:onCreatureSay(cid, type, msg)     end
function onThink()         npcHandler:onThink()           end

local shopModule = ShopModule:new()
npcHandler:addModule(shopModule)

shopModule:addSellableItem({'meat'}, 2666, 3, 'meat')
shopModule:addSellableItem({'dragon ham'}, 2672, 10, 'dragon ham')
shopModule:addSellableItem({'phoenix egg'}, 11400, 10000, 'phoenix egg')
shopModule:addSellableItem({'egg'}, 2328, 10, 'egg')
shopModule:addSellableItem({'hydra egg'}, 4850, 2000, 'hydra egg')
shopModule:addSellableItem({'tortoise egg'}, 5678, 250, 'tortoise egg')
shopModule:addSellableItem({'terramite egg'}, 11370, 50, 'terramite egg')
shopModule:addSellableItem({'tarantula egg'}, 11198, 75, 'tarantula egg')
shopModule:addSellableItem({'egg of the many'}, 10523, 3750, 'egg of the many')
shopModule:addSellableItem({'carniphila seeds'}, 11217, 175, 'carniphila seeds')
shopModule:addSellableItem({'seagull egg'}, 12674, 75, 'seagull egg')


function creatureSayCallback(cid, type, msg)
    if not npcHandler:isFocused(cid) then
        return false
    end

    local talkUser = NPCHANDLER_CONVBEHAVIOR == CONVERSATION_DEFAULT and 0 or cid

    if msgcontains(msg, "Calene") then
		selfSay("I just love animals, that's why I set up this {shelter}.",cid)
		selfSay("Just thinking about all the sad lonely creatures out there...",cid)
		selfSay("It's almost too much to bear.",cid)
		
	elseif(msgcontains(msg, "quest") or msgcontains(msg, "job") or msgcontains(msg, "mission"))  then
		selfSay("I'll have something to do for you later.",cid)
		
	elseif msgcontains(msg, "shelter")  then
		selfSay("These animals are my children.",cid)
	
	else
		selfSay("I don't know anything about that subject, sorry.", cid)
		
	end
	return true
end

npcHandler:setCallback(CALLBACK_MESSAGE_DEFAULT, creatureSayCallback)
npcHandler:addModule(FocusModule:new())

```

**Comment by TheSumm** [comment]
The client only knows the client id of both items, which is identical in your case (see https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L3070). When buying an item the client sends a packet containing the client id and the server will retrieve the corresponding item, which in your case would be the regular egg.
AFAIK there is no way to achieve the intended behaviour within a single shop window.

You can either seperate both items into 2 shop windows e.g. `egg` appears in the list when asking for `trade` and `seagull egg` appear in the list when asking for `special offers`.
Otherwise you could sell the item using the old keyword system e.g. `buy seagull egg`.
