### ISSUE TITLE
[BUG] After using "/i water" in game, server crashing.

### ISSUE THREAD

**Issue by GugiMistrz** [otland/forgottenserver#2748]
1. Should create field with water.
2. Server is crashing.

**Comment by MillhioreBT** [comment]
This doesn't happen to me, make sure you don't have strange modifications to your sources, you must use the original sources

**Comment by delusionx** [comment]
Cannot reproduce either on master branch.
Make sure you actually read the issue template before posting one, you should've ensured that it's reproduce-able on master.

**Comment by GugiMistrz** [comment]
> 
> 
> This doesn't happen to me, make sure you don't have strange modifications to your sources, you must use the original sources

i got original sources .

**Comment by delusionx** [comment]
Original datapack as well, absolutely zero changes besides config.lua to connect?

**Comment by GugiMistrz** [comment]
I got this, wrong id of "water" .

**Comment by EPuncker** [comment]
if the issue is not a issue, just hit the close button 😃
