### ISSUE TITLE
Low level yelling "new" behaviour

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2771]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

Tibia has changed how yelling was restricted on low levels and I think we need to do so too (why not? 😝 )

### Expected behaviour
You should not yell as long as you are bellow lvl 20 or your account has premium status
(the message says: "You may not yell unless you have reached level 20 or your account has premium status")

### Actual behaviour
Currently we only restrict yelling to lvl > 1

### My suggestions
- [x] add the level 20 or premium status needed
- [x] make level configurable in config.lua
- [x] make premium restriction configurable in config.lua

PS: can't test with a char level 1 since you start at level 2 now when creating a character no matter what
PS²: need someone with a premium account available to check what the message says when you are premium and level 2 and tries to yell

**Comment by Znote** [comment]
What if your stuck in a cave without a rope? :P

**Comment by EPuncker** [comment]
> What if your stuck in a cave without a rope in rook? :P

they remapped everything so you can't be stuck anymore, to enter any cave that need a rope, you need to have a rope in the first place ;P

**Comment by WibbenZ** [comment]
In that case we should implement that at the same time, not a bad ide tbh
