### ISSUE TITLE
[Suggestion] Revscriptsys silent loading option

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2776]
Hi everyone once again, I was just thinking, it is not a big deal, but what about a config.lua option to enable/disable silent loading of Revscriptsys files? since every single one is displayed on the console on loading, so this option would only display the errors, and silent load them if enabled

**Comment by vankk** [comment]
You should read the [configmanager.cpp](https://github.com/otland/forgottenserver/blob/master/src/configmanager.cpp#L142), by chaging this variable to false it won't display the codes that was been loaded.

**Comment by EPuncker** [comment]
oh thanks beon
