### ISSUE TITLE
Defense attribute in monsters 

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2778]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

Where is it calculated when formulating the damage received? Is it used anywhere? I tried searching for it in source but no success, if any dev could enlighten this to me I'll be grateful in removing it from monster files if it is the case

**Comment by Wirox** [comment]
https://github.com/otland/forgottenserver/blob/293099a8cc518eefe66276a90544ad8d45505b87/src/creature.cpp#L800-L808

**Comment by EPuncker** [comment]
> https://github.com/otland/forgottenserver/blob/293099a8cc518eefe66276a90544ad8d45505b87/src/creature.cpp#L800-L808

isn't monster block hit code this one? https://github.com/otland/forgottenserver/blob/7eb5d3a975b2e76c61fe5add259bd2c3c8351559/src/monster.cpp#L585

**Comment by MillhioreBT** [comment]
> > https://github.com/otland/forgottenserver/blob/293099a8cc518eefe66276a90544ad8d45505b87/src/creature.cpp#L800-L808
> 
> isn't monster block hit code this one?
> 
> https://github.com/otland/forgottenserver/blob/7eb5d3a975b2e76c61fe5add259bd2c3c8351559/src/monster.cpp#L585

It is also filtered through creature::blockhit
![image](https://user-images.githubusercontent.com/28090948/74048371-74bb8080-49a8-11ea-9aee-f165d7738749.png)

**Comment by EPuncker** [comment]
oh I see, thanks
