### ISSUE TITLE
onEquip executes two times, when we equip item. [$5]

### ISSUE THREAD

**Issue by djseban** [otland/forgottenserver#278]
Hi
This bug exists in every version of TFS. When we equip item, which has custom lua script, function MoveEvents::onPlayerEquip is executed two times. For example we have lua script:
function onEquip(cid, item, slot)
     print(1)
end
After wearing item, output in TFS console is:
1
1
but should be:
1
##

**Comment by gugahoa** [comment]
Right now onEquip can be called three times, two for checking and one to run the script. I would like to suggest adding the variable isCheck to onEquip/onDeEquip. Any thoughts? I already did this in a fork, if needed I can make a PR.

**Comment by brunominervino** [comment]
@ranisalt @djarek , maybe 1.3 milestone?

**Comment by djarek** [comment]
Fixed in #2058

**Comment by gugahoa** [comment]
How do I claim my lunch? Ops, I mean the bounty

**Comment by djarek** [comment]
Ask @Znote .

**Comment by Znote** [comment]
![image](https://cloud.githubusercontent.com/assets/1552144/24285937/ef85100a-1072-11e7-8d29-3754c1ef76f0.png)
