### ISSUE TITLE
Message colours on custom channels

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#279]
Is that possible to send white or green message to custom channel?
I've tried many talktypes, but only ones that worked without debug are: 7, 8, 13

function:
sendChannelMessage(channel_id, talktype, text)

**Comment by slavidodo** [comment]
Is that solved?

**Comment by Zbizu** [comment]
it was client issue
from server-side it works fine

**Comment by slavidodo** [comment]
So I want to send white message to cast channel, how to do so ?

**Comment by slavidodo** [comment]
Also 13 is debugging on my channel ( TALKTYPE_BROADCAST )
