### ISSUE TITLE
Can not manually use runes on invisible creatures

### ISSUE THREAD

**Issue by zeeb92** [otland/forgottenserver#2792]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository.
- [X] This issue is reproducible without changes to the code in this repository.

### Steps to reproduce (include any configuration/script required to reproduce)
**1.** Spawn monster that can turn invisible. (_Stalker_)
**2.** Manually aim a rune on the invisible creature. (_SD/UH_)

### Expected behaviour
You should be able to use **needTarget** runes aimed manually on invisible creatures.

### Actual behaviour
You can not use manually aimed **needTarget** runes on invisible creatures.

### Extra information
This should be possible wether you have **hotkeys disabled** or not.

The problem _might_ lie somewhere within **topVisibleCreature**.
You get **RETURNVALUE_CANONLYUSETHISRUNEONCREATURES** upon trying.

I found this information in **spells.cpp**.

**Comment by EPuncker** [comment]
actually in real tibia we can't aim single target runes to invisible creatures, maybe we could do it in old versions, but I think TFS is trying to mimic actual version, this is more like a custom feature like the enable/disable hotkeys, not really a bug

**Comment by nekiro** [comment]
No, thats invalid. You could do that in some version pre 8 as far as I remember, not in the protocol we are in.

**Comment by zeeb92** [comment]
Are you guys actually certain they got rid of that feature in RL Tibia or are you guessing? Because I can't see the logic Cipsoft would use to validate the features removal even with the hotkeys implementation. Since you can't keep target on an invisible creature anyway.

But if you're certain that's the case then it is what it is and this report can be closed.

Thanks for answering.

**Comment by EPuncker** [comment]
> Are you guys actually certain they got rid of that feature in RL Tibia or are you guessing? Because I can't see the logic Cipsoft would use to validate the features removal even with the hotkeys implementation (_Even if they regularly take major questionable dicisions_).
> Since you can't keep target on an invisible creature anyway.
> 
> But if you're certain that's the case then it is what it is and this report can be closed.
> 
> Thanks for answering.

yes I'm 100% sure about it, used to hunt a lot of infernalists on my RP and EK and the only way to reveal them is with area runes

**Comment by Olrios** [comment]
From Tibia 8.0+ it's no longer possible to use any single target rune on any creature what is invisible.

**Comment by Znote** [comment]
Nekiro has a 7.72-downgrade branch of TFS:
https://github.com/nekiro/forgottenserver/tree/7.72-downgrade

Perhaps post an issue about it over there.
