### ISSUE TITLE
"cautious monsters"

### ISSUE THREAD

**Issue by Lycanzito** [otland/forgottenserver#2793]
Hello Everyone.
I would like to report an error that is happening in the "pathing system".
For example; A demon should have this flag:
flag canwalkonenergy="1"
flag canwalkonpoison="1"
But the problem is : if there is other way to the monster walks to go to the player position, the monster will try to get the "best way" to not receive the damage from the energy wall.
But the demon should ignore the "caution", and just pass trough the energy wall.

Will post a video showing it better ..
https://www.youtube.com/watch?v=OKohlC-Bl64

Note: that's my first topic, so take easy with me :( also my english is not that good.. Im learning ;- )

**Comment by Znote** [comment]
Which flag? A cautious flag?

**Comment by EPuncker** [comment]
I confirm this issue, the problem here (if it is not clear enough to devs), is that the demon should prioritize reaching the player by walking on the energy wall, instead of prioritizing walking any other way

**Comment by nekiro** [comment]
Do you have canWalkOnEnergy flag in demon.xml?

**Comment by EPuncker** [comment]
> Do you have canWalkOnEnergy flag in demon.xml? Set it to 1.

it is already, but seems like the code logic is to prioritize the walking around instead of walking thought it

**Comment by Lycanzito** [comment]
> > Do you have canWalkOnEnergy flag in demon.xml? Set it to 1.
> 
> it is already, but seems like the code logic is to prioritize the walking around instead of walking thought it... and it should be the other way around (as real tibia)

Thanks 4 explaining to them ! :-)

**Comment by Lycanzito** [comment]
> Which flag? A cautious flag?

updated my comment ^.-

**Comment by nekiro** [comment]
It's issue regarding path finding not the field code itself, as far as I remember field tiles got higher cost (determined by system) so it will avoid them if there is a way around it until there is none so its gonna run over it.
https://github.com/otland/forgottenserver/blob/master/src/map.cpp#L841-L856

**Comment by EPuncker** [comment]
> It's issue regarding path finding not the field code itself, as far as I remember field tiles got higher cost (determined by system) so it will avoid them if there is a way around it until there is none so its gonna run over it.
> https://github.com/otland/forgottenserver/blob/master/src/map.cpp#L841-L856

we should made an exception for monster with canwalkonXXX flag then, the cost is correct for everything but for canwalkonXXX flagged monsters, they should have less cost

**Comment by BahamutxD** [comment]
Behaviour changes when he is hit by condition damage (energy in this case) - either from spells/runes or the energy field itself if the monster has been forced to step on it. Seems to be only happening with Condition Damage.

When this happens it will ignore any field and go straight for the player - running away/changing floors seems to reset the monster to initial behaviour.

**Comment by zeeb92** [comment]
As EPuncker said, monsters with the "canwalkonXXX" flag, should get the same cost on XXX fields as normal floors.

**Comment by Lycanzito** [comment]
it shouldnt receive a tag of "bug" ?

**Comment by Lycanzito** [comment]
thx so fucking much, sir Nekiro!

you're dabest!
