### ISSUE TITLE
Move Up Issue

### ISSUE THREAD

**Issue by Lycanzito** [otland/forgottenserver#2796]
Hello everyone ;
"Move Up" is only working with no stackable itens.

With stackable itens, isnot possible to move up.
![image](https://user-images.githubusercontent.com/52710697/75034638-67b08e00-548c-11ea-836d-0d46026157b4.png)

A video to explain it better:

https://www.youtube.com/watch?v=VmkDdtHeeFM

**Comment by BahamutxD** [comment]
Can't reproduce 
![123](https://user-images.githubusercontent.com/6182531/75037404-5ed3b280-54b4-11ea-948e-9a94d1a733a4.gif)

**Comment by Lycanzito** [comment]
> Can't reproduce
> ![123](https://user-images.githubusercontent.com/6182531/75037404-5ed3b280-54b4-11ea-948e-9a94d1a733a4.gif)
The client actually happen, with the client 12, this repo doenst use the client 12?'-'

**Comment by BahamutxD** [comment]
Its 10.98 OTCv8 but 10.98 Tibia client is the same.
![1234](https://user-images.githubusercontent.com/6182531/75037895-79f2f200-54b5-11ea-88a4-64c012545802.gif)

**Comment by nekiro** [comment]
Invalid issue, you are using modified sources, this code works fine on default master branch, you should consider closing it.
