### ISSUE TITLE
Whirlwind Throw + Ice Rapier is bugged

### ISSUE THREAD

**Issue by zeeb92** [otland/forgottenserver#2799]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
**1.** Use the command "/i Ice Rapier".
**2.** Use the spell "exori hur".
**3.** No CONST_ANI will be played.

### Expected behaviour
**CONST_ANI_SWORD** should be played when using it with Ice Raper due to it being a Sword Type.

### Actual behaviour
It displays **CONST_ANI_NONE**, which is the default in the sources when no weapon type can be found.

### Extra information
Most likely due to the fact that Ice Rapier only has 1 charge of use.
So when you cast Exori Hur the weapon disappears before the spell has time to register what weapon type it was used with.

**Comment by Sickness-chan** [comment]
Did you test it after giving it more than 1 charge?

**Comment by EPuncker** [comment]
> Did you test it after giving it more than 1 charge?

if you give it more than one charge it works.

I confirm this issue, just tested it and indeed if the charge = 1 it doesn't display the distance effect:

![asdasd](https://user-images.githubusercontent.com/4684880/75408942-04908280-58f6-11ea-9009-884143b6c4b9.gif)

and it should

**Comment by Wirless** [comment]
the const_ani should be instanced before the remove of weapon charge so.

**Comment by zeeb92** [comment]
So can we have this bug confirmed?
