### ISSUE TITLE
[Suggestion] Add XML syntax check for PRs

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2801]
As a followup to this https://github.com/otland/forgottenserver/commit/f664c55537cce9cc799582e6b374a1f0cd36e0a6 it would be great to have one for XML as well!

**Comment by DSpeichert** [comment]
Sure, it's a great idea.

But we need a tool that does that first. There is http://xmlsoft.org/xmllint.html, but like most existing XML Validators/Linters out there, it would require a schema definition (XSD).

We don't happen to have those right now but if you wanted to create them and they worked, I will definitely add those checks via Github Actions.

**Comment by DSpeichert** [comment]
Done in #2973.
