### ISSUE TITLE
to/fromPosition:sendMagicEffect not working

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2803]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. use `toPosition:sendMagicEffect(CONST_ME_GIFT_WRAPS)` or `fromPosition:sendMagicEffect(CONST_ME_GIFT_WRAPS)` in any action script (I tested in revsys only but I don't think it matters)
2. use the item on your backpack or the ground, it doesn't matter
3. see

### Expected behaviour
effect should be displayed wherever the item/player is (depends if from/to) 

### Actual behaviour
no effect is displayed

### ---
am I doing something wrong or is there anything that I'm missing and this is not a bug?

**Comment by Znote** [comment]
```lua
local northWest = Position(143, 388, 7)
local northEast = Position(146, 388, 7)
local southWest = Position(143, 392, 7)
local southEast = Position(146, 392, 7)

northWest:sendMagicEffect(CONST_ME_HITBYFIRE, nil)
northEast:sendMagicEffect(CONST_ME_HITBYFIRE, nil)
southWest:sendMagicEffect(CONST_ME_HITBYFIRE, nil)
southEast:sendMagicEffect(CONST_ME_HITBYFIRE, nil)

local ppos = player:getPosition()
if ppos:isInRange(northEast, southWest) then
	ppos:sendMagicEffect(CONST_ME_ENERGYHIT, nil)
end
```

Worked fine for me a while ago. Could it be the second param is required?

**Comment by TheSumm** [comment]
He is talking about the parameters passed to the `onUse` callback. `Position.sendMagicEffect` works fine when used in combination with a proper position. However, the parameters `toPosition` and `fromPosition` may also be positions inside the player's inventory (where `fromPosition.x == 0xffff`).

You can send the effect by using `item:getPosition():sendMagicEffect(CONST_ME_ENERGYHIT)` and `target:getPosition():sendMagicEffect(CONST_ME_ENERGYHIT)`.

I would not consider this a bug. It is just inconvenient at the moment.

**Comment by EPuncker** [comment]
> He is talking about the parameters passed to the `onUse` callback. `Position.sendMagicEffect` works fine when used in combination with a proper position. However, the parameters `toPosition` and `fromPosition` may also be positions inside the player's inventory (where `fromPosition.x == 0xffff`).
> 
> You can send the effect by using `item:getPosition():sendMagicEffect(CONST_ME_ENERGYHIT)` and `target:getPosition():sendMagicEffect(CONST_ME_ENERGYHIT)`.
> 
> I would not consider this a bug. It is just inconvenient at the moment.

I tried `item:getPosition():sendMagicEffect(CONST_ME_ENERGYHIT)` and it doesn't work either

**Comment by EPuncker** [comment]
okay guys I did a simple test here and there is no bug actually, it is just way too confusing to determine what is going to be executed or not, for instance, when I told @TheSumm that the above did not worked, it didn't worked on this PR #2797 but on my test script everything works, so I have no idea:

`local test = Action()

function test.onUse(player, item, fromPosition, target, toPosition, isHotkey)
	toPosition:sendMagicEffect(CONST_ME_GIFT_WRAPS)
	fromPosition:sendMagicEffect(CONST_ME_MAGIC_RED)
	item:getPosition():sendMagicEffect(CONST_ME_ENERGYHIT)
	player:getPosition():sendMagicEffect(CONST_ME_HEARTS)
	target:getPosition():sendMagicEffect(CONST_ME_SOUND_YELLOW)
	return true
end

test:id(19392)
test:allowFarUse(true)
test:register()
`
