### ISSUE TITLE
Warning during compilation 

### ISSUE THREAD

**Issue by MohamedRefaat** [otland/forgottenserver#2804]
Hello,

I compiled using Visual Studio 2019 and found this warning

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xtgmath.h(24,70): warning C4244: 'argument': conversion from 'double' to 'T', possible loss of data
1> with
1> [
1> T=uint32_t
1> ] (compiling source file ..\src\networkmessage.cpp)

**Comment by Leo32onGIT** [comment]
I can confirm this.

Replicate with:
VS 2019 Community
Open .sln
Retarget solution/project
Build

Note the warning.
