### ISSUE TITLE
Wiki Fedora Compilation Instructions

### ISSUE THREAD

**Issue by wapean** [otland/forgottenserver#2825]
> cmake ..
> CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> -- Configuring incomplete, errors occurred!
> See also "/root/forgottenserver/build/CMakeFiles/CMakeOutput.log".

Installing make with dnf solves problem, but it wasn't mentioned in wiki. I suggest replacing
>$ sudo dnf install git cmake gcc-c++ boost-devel gmp-devel community-mysql-devel lua-devel pugixml-devel cryptopp-devel

with 
>$ sudo dnf install git cmake gcc-c++ boost-devel gmp-devel community-mysql-devel lua-devel pugixml-devel cryptopp-devel make

**Comment by Znote** [comment]
Updated:
https://github.com/otland/forgottenserver/wiki/Compiling-on-Fedora
