### ISSUE TITLE
Loot from monsters does not check if string is correct

### ISSUE THREAD

**Issue by WibbenZ** [otland/forgottenserver#2843]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Ex in #2842, TFS does not check (/ report an error) when the item does not exist

### Expected behaviour

Throw an error that the item does not exist

### Actual behaviour

Nothing

### Environment

Does not matter AFAIK

**Comment by nekiro** [comment]
Arent we going to drop any item name support? I think we should use ids everywhere.

**Comment by WibbenZ** [comment]
Not sure what the rest think, but if you ask me yes.
But it's not a quick change to move from strings to ids and add a comment saying what the item is named.
Till then this should be fixed, to avoid spelling item names wrong.

**Comment by nekiro** [comment]
I can probably write some parser that will parse items by name and convert them to ids

**Comment by EPuncker** [comment]
actually we went from using IDs to using names, now we will go the other way around? xD btw about this bug report itself, I think tfs only check for this if monster is actually spawned, and in my opinion it should check for errors in ALL monsters that are actually registered in the monsters.xml, not only the spawned ones

**Comment by DSpeichert** [comment]
Dropping support for referring to items by names is probably a no-no. Think about all the data packs that exist with names for items in monsters, etc.

TFS should:
a) warn for items that don't exist
b) warn for items that are non-unique by name when used

But it should still do the most obvious thing.

**Comment by Leo32onGIT** [comment]
I didn't realise you could use string in the names until recently. Makes for really easy readability from the xml itself. Does need the warnings though.

**Comment by EvilHero90** [comment]
actually this all is implemented already.
![tfs1](https://user-images.githubusercontent.com/3682541/76811748-f8ac2800-67f2-11ea-829f-e3b3c1dae458.png)
![tfs2](https://user-images.githubusercontent.com/3682541/76811750-f944be80-67f2-11ea-96d9-b27ce1c67ea9.png)
so this can actually be closed.

**Comment by WibbenZ** [comment]
Still in this case something is wrong, ex #2842 
![flash](https://user-images.githubusercontent.com/6361370/76812094-1463fe00-67f4-11ea-9a61-04b84ae94c09.png)

It does report an error when I changed "dagger" to "daggerr" but ignores the orshabaal loot ("tedy" compared to "teddy"

All monsters should be checked on start-up, ex found another error just now when spawning orshabaal.
![flash](https://user-images.githubusercontent.com/6361370/76812252-92c0a000-67f4-11ea-920f-1a38d65b5185.png)

Thing like this makes it harder to test new monster PR or custom edits etc
This is the reason why we should avoid string loading items or check if we got more than 1 item with a unique name during start-up.

**Comment by EvilHero90** [comment]
well it immediatly returns false once it finds an error, so the second error wont even get shown (if that's what you are refering to)

**Comment by WibbenZ** [comment]
Well either we change it so we print all errors and continue (like now, orshabaal spawns and you can loot items) or we print the error and stop loading the server.
No matter what we can't have hidden errors, if we can't find an item via string / id there should be an error when you start the server.
