### ISSUE TITLE
Loot countmax "issue" when using values bigger than 100

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2859]
I'm opening it to gather opinions rather than reporting an issue, currently our loot countmax attribute doesn't create any count higher than 100 (which is okay), the only issue here is the hassle when doing monsters that drops lots of gold coins, we need to use:

```
<item name="gold coin" countmax="100" chance="34000" />
<item name="gold coin" countmax="100" chance="34000" />	
<item name="gold coin" countmax="46" chance="20000" />
```

when we could instead use:

`<item name="gold coin" countmax="246" chance="88000" />`

=======
the first one makes more sense if we want to have each "amount" of gold to have different chance like cipsoft does, but since we don't have access to these rates, what should we do?

every opinion is welcome!

**Comment by MillhioreBT** [comment]
Here EPuncker:
I like the idea, and already implemented it thanks to you ;)
https://github.com/otland/forgottenserver/compare/master...MillhioreBT:patch-2

**Comment by EPuncker** [comment]
ohhhh, now that you mention it, maybe it used to work the way I explained, maybe it was just not ported when @joseluis2g ported loot to lua, can you confirm this to me @joseluis2g ? and thanks @MillhioreBT

**Comment by MillhioreBT** [comment]
@EPuncker  You're welcome, even though the system was passed to lua, it still didn't allow adding more than 100 stacked objects

**Comment by Zbizu** [comment]
What if we allowed countmax higher than 100 and just loop through stacks? For example, we rolled 250 gold so it would be added as 100+100+50.
