### ISSUE TITLE
kickIdlePlayerAfterMinutes - It's not working TFS 1.3

### ISSUE THREAD

**Issue by paola92** [otland/forgottenserver#2871]
Hi,
when I attack any monster and stay without move more that 15minut my character should be kicked but it is not. The same is with exit. When I attack monster and exit game character will stay and stay.
I don't have na logout zones etc.

**Comment by nekiro** [comment]
Your character will get kicked as long as it loses infight condition, so if you stay in proximity of monster, character should never log out

**Comment by paola92** [comment]
but why player is attacking monster on exit after 30 minutes. 
it's also attacking monster without idle on opened client.

**Comment by paola92** [comment]
it's working when player is not attacking monster. but when player is stay on trainer I can receive ban on otservlist.

**Comment by nekiro** [comment]
Why would we care about some otservlist, if you need that done, do it yourself or ask for help in forums.

**Comment by paola92** [comment]
but it is not working properly. the same is on real tibia. if monster attack player 15minutes and player will not move. player will be kicked.

**Comment by BahamutxD** [comment]
With kickIdlePlayerAfterMinutes = 15

Player is kicked after being 17 mins idle. (client open)

Player is kicked after 17 mins while getting attacked by monster (client closed)

Player is**not**  kicked for being in combat but not being attacked/attacking. (client closed)

Player is **not** kicked while attacking and getting attacked by monster (client closed)

If we are to mimic the real thing - https://tibia.fandom.com/wiki/X-Logging

Case 2 seems wrong - should never log you out while being in combat unless I'm missing something.

**Comment by EPuncker** [comment]
I changed kick idle minutes to 5, went to training monks and stayed there and my character never logged out... (that is wrong, afk attacking should not be counted as an action to prevent logout), then I x-logged the character being attacked and it didn't logout either...

in other words, yes I confirm this issue

**Comment by paola92** [comment]
yes, character should be kicked when attacking after 15mins.

**Comment by EPuncker** [comment]
I've just finished being afk fist attacking a swamp troll in real tibia for 15 minutes just to record it, to find out my recorder was not working lmao:
![d_for](https://user-images.githubusercontent.com/4684880/77662706-f9635d80-6f5a-11ea-834f-63db4375ad89.png)

but once again, I confirm this issue, attacking (having infight) should NOT prevent the kick from happening

**Comment by EPuncker** [comment]
> So can someone summary, what is the correct behaviour?

right now I can confirm two scenarios that are wrong on TFS:
- being attacked by a monster for 15 minutes while not attacking it will kick you out even while in fight (tfs doesn't do it)
- attacking a monster for 15 minutes with no other action, will kick you out too even while in fight (tfs doesn't do it either)

now information about X-logging:
- If player x-close client while in fight with a monster, server will try to log it out in 60 seconds (don't know how tfs behaves)
- If player x-close client while in a pvp battle (or having red swords), the server will try to log it out only after the red sword is gone (protection zone block)


and there are protections make for players in case off DDoS or connection down, that are not implemented in TFS that are the following:

> These protections make the character invisible (but not invulnerable) to creatures for 30 seconds when the connection is lost and for 10 seconds after logging in with creatures nearby. Also, characters logout completely after a period of 40 seconds for Druids and Sorcerers, 50 seconds for Paladins, and 60 seconds for Knights.

the above is the new connection state "PENDING" that displays the character name in orange on the VIP list
