### ISSUE TITLE
[Suggestion] OnMount event

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2873]
While I was working on adding achievements, I was going thru updates and found out that cip added the possibility to get the "Natural Born Cowboy" (the one you get for your first mount), while using mounts bought on the store, so here comes my idea to suggest the addition of an OnMount event, because why not 😛 it can be used for bonuses as well as the OnChangeOutfit

**Comment by MillhioreBT** [comment]
It can be simulated perfectly using the `function Creature: onChangeOutfit (outfit)` `outfit.lookMount` method, but it is a very good idea to separate a small snippet of the code so that it is especially responsible for the mount info ;)

**Comment by EPuncker** [comment]
> It can be simulated perfectly using the `function Creature: onChangeOutfit (outfit)` `outfit.lookMount` method, but it is a very good idea to separate a small snippet of the code so that it is especially responsible for the mount info ;)

ohhhhhhhhhh I didn't knew, thanks once again for giving information I didn't had

**Comment by EvilHero90** [comment]
We can do this once Event Callbacks are implemented.

**Comment by MillhioreBT** [comment]
![image](https://user-images.githubusercontent.com/28090948/77861111-0f824f80-71e1-11ea-9098-9d944b38aa48.png)
![image](https://user-images.githubusercontent.com/28090948/77861130-2d4fb480-71e1-11ea-98cf-621f8cb0a1d1.png)
:)

**Comment by EPuncker** [comment]
#2867 just referencing so I don't forget
