### ISSUE TITLE
Database issue? Debian 9.

### ISSUE THREAD

**Issue by paola92** [otland/forgottenserver#2876]
Hi,
we are doing/testing our server based on clear TFS 1.3. We use debian 9. After night server was crashed with below error. Do you have any idea? I think it is connected with database.

debugger aborting because missing DBUG_RETURN or DBUG_VOID_RETURN macro in function "?func"

Aborted

**Comment by guiismiti** [comment]
I am also experiencing some issues in debian.
I got a compiling error with xtea.cpp (lines 36 and 68) - requested alignment 16 is larger than 8

**Comment by DSpeichert** [comment]
You have to provide more information, logs, etc.
It doesn't look like issue with the code, for support try https://otland.net/forums/support.16/
