### ISSUE TITLE
[Suggestion] New house settings

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2879]
It seems that currently we have no limitations to buying houses other than one per character, and since recently tibia added the possibility to own 3 houses on the same character (or account/world), here is my list of suggestions regarding our current house configs:

- [ ] House per account limit instead of per character
- [x] Add option to show house price on look at door = true/false
- [x] Level requirement
- [x] Premium requirement
- [x] a setting to make all characters on account invited on the house by default = true/false

**Comment by MillhioreBT** [comment]
i like your idea, i safe will work with this

**Comment by MillhioreBT** [comment]
> and a bonus if you are really feeling good today: a setting to make all characters on account invited on the house by default = true/false

check!
https://github.com/otland/forgottenserver/pull/2935

**Comment by EPuncker** [comment]
closing as the last feature is more likely to be added AAC side than server's
