### ISSUE TITLE
Loot chance above maximum not giving a warning

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2885]
I know that is not a big deal, but it would be nice to have a console warning if the monster loot chance in the xml file is higher than this variable:

https://github.com/otland/forgottenserver/blob/ea4a322bb32696037c75fd635be79fb13b86cc7a/src/monsters.h#L26

its kinda a simple change in code I guess, but since I lack the knowledge to do so, here is the issue in case anyone is going to do it.

(yes, I've seen lots of monster files in bugged datapacks with chance set to 100000000 😛 )

**Comment by Leo32onGIT** [comment]
https://github.com/otland/forgottenserver/blob/08231f423984f7db78b498f0ffdd7257ea6b1a95/data/lib/core/container.lua#L12

```lua
if item.chance > 100000 then
    -- do the warning stuff
end
```

**Comment by MillhioreBT** [comment]
I think there is no need:
https://github.com/otland/forgottenserver/blob/master/src/monsters.cpp#L1301

**Comment by EPuncker** [comment]
> I think there is no need:
> https://github.com/otland/forgottenserver/blob/master/src/monsters.cpp#L1301

but still needs a warning for a better looking code 😝

**Comment by MillhioreBT** [comment]
> > I think there is no need:
> > https://github.com/otland/forgottenserver/blob/master/src/monsters.cpp#L1301
> 
> but still needs a warning for a better looking code 😝

in this case mm you can use:
`if ((attr = node.attribute("chance")) || (attr = node.attribute("chance1"))) {
		int32_t chance = pugi::cast<int32_t>(attr.value());
		if (chance > MAX_LOOTCHANCE) {
			std::cout << "[Warning - Monsters::loadMonster] the max \"chance\" is " << MAX_LOOTCHANCE << "." << std::endl;
		}
		lootBlock.chance = std::min<int32_t>(MAX_LOOTCHANCE, chance);
	} else {
		lootBlock.chance = MAX_LOOTCHANCE;
	}`

**Comment by EPuncker** [comment]
@MillhioreBT there is an error:

https://travis-ci.org/github/otland/forgottenserver/jobs/670298926#L427

**Comment by MillhioreBT** [comment]
> @MillhioreBT there is an error:
> 
> https://travis-ci.org/github/otland/forgottenserver/jobs/670298926#L427

check again:
https://github.com/MillhioreBT/forgottenserver/pull/1/commits/09dcd8fcbb49224a531e2ed3f5711dbcf14e776c
