### ISSUE TITLE
getPluralName function missing a few checks

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2941]
I stumbled into a double grapes entry when doing a change in items.xml file and noticed that our getPluralName code:

https://github.com/otland/forgottenserver/blob/b7ef46dfc7ac4fad1bcea5e3604c9ef8c4350864/src/items.h#L275-L289

is kinda "incomplete" and missing a few checks, it only adds "s" to the end of the word if it doesn't have a plural tag, that is why we need to have:

`<item id="2681" name="grapes" plural="grapes">`

or it would show "**grapess**" in game.

my suggestion is to add a check to see if the word ends in "s" it shouldn't add anything, and also if possible (I don't really know english gramar rules since its not my main language), but maybe we could also add other rules... in fact I've just researched and noticed that there is a JS lib for it, that we could borrow at least a few rules:

https://github.com/blakeembrey/pluralize/blob/master/pluralize.js#L329-L356

or maybe I'm being too deep into a simple issue? xDDD

**Comment by gpedro** [comment]
if doesn't have the plural attribute, can use this algorithm to solve. that's cool!
