### ISSUE TITLE
Problem with a code TFS 1.2 Gesior 2012

### ISSUE THREAD

**Issue by diakosz34** [otland/forgottenserver#2946]
Hello, i have problem with code. I need TOP 10 Players box on the right side of page. I have this code, but i have some problems. Help plz :)
https://imgur.com/a/7kg6VGq

`<div id="Themebox">
                                <div id="NewcomerBox" class="Themebox" style="background-image:url(<?PHP echo $layout_name; ?>/images/themeboxes/highscores.gif);height:200px;">
                                
                                <?php
                                    $TopPlayers = $SQL->query("SELECT `name`, `experience`, `level` FROM `players` ORDER BY `experience` DESC LIMIT 5")->fetchAll();
                                    $Counter = 1;
                                ?>
                                <table cellspacing="0" cellpadding="5" border="0" width="0%">
                                    <?php foreach($TopPlayers as $Player): ?>
                                    <tr>
                                        
                                        <td><a href="index.php?subtopic=characters&amp;name=<?php echo urlencode($Player['name']); ?>"><?php echo $Player['name']; ?></a></td>
                                        <td align="right" width="5%"><?php echo $Player['level']; ?> level</td>
                                    </tr>
                                    <?php endforeach; ?>
                                    <div class="Bottom" style="background-image:url(<?PHP echo $layout_name; ?>/images/general/box-bottom.gif);">
</div>

                                </table>
`

**Comment by Emilianenko** [comment]
You should ask for support on https://otland.net/forums/support.16/ not here.
