### ISSUE TITLE
Compiling TFS 1.3 on Centos 8

### ISSUE THREAD

**Issue by yrpen** [otland/forgottenserver#2947]
Hello.
Compiling manual on Centos is outdated (2016-02-08). It doesn't work on Centos 8.
https://github.com/otland/forgottenserver/wiki/Compiling-on-CentOS

After some digging and with great support in forum I compiled source code. 
https://otland.net/threads/compiling-tfs-1-3-on-centos-8.269375/

1. So how make pull request to this wiki page?
2. Does my script fit some documentation standards? Or how fix it to do so?

Working compile sript:
```
#!/bin/bash

set -e

# Enable PowerTools to install lua-devel
sudo sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/CentOS-PowerTools.repo
sudo sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/CentOS-Devel.repo

# Remove yum cache
sudo yum clean all

# Install this package to get pugixml-devel
sudo yum install epel-release
sudo yum install git cmake gcc-c++ boost-devel gmp-devel mariadb-devel make
sudo yum install lua-devel pugixml-devel

# Install to fix cmake error
sudo yum install cryptopp-devel

# Prepare tfs user and group
sudo groupadd tfs
sudo useradd -g tfs -s /bin/bash -m tfs
sudo chmod 750 /home/tfs

# Run code as tfs user
sudo su - tfs -c 'git clone --recursive https://github.com/otland/forgottenserver.git'
sudo su - tfs -c 'cd forgottenserver && mkdir build'
sudo su - tfs -c 'cd forgottenserver/build && cmake ..'
sudo su - tfs -c 'sed -i "s/-Werror//g" /home/tfs/forgottenserver/CMakeLists.txt'
sudo su - tfs -c 'cd forgottenserver/build && make'
```

**Comment by DSpeichert** [comment]
Thanks, I've updated the wiki.

**Comment by yrpen** [comment]
@DSpeichert 
Thanks.

But I found one typo and one missing line in new doc.

**1.**

```
sudo yum install epel-release  yum install git cmake gcc-c++ boost-devel gmp-devel mariadb-devel make lua-devel pugixml-devel cryptopp-devel
```

There should be two separated lines:
```
sudo yum install epel-release 
sudo yum install git cmake gcc-c++ boost-devel gmp-devel mariadb-devel make lua-devel pugixml-devel cryptopp-devel
```

**2.**

Removing **-Werror** from **CMakeLists.txt** is essential to compile TFS 1.3 on CentOS 8.

```
cd forgottenserver
sed -i "s/-Werror//g" ./CMakeLists.txt
```

**Comment by DSpeichert** [comment]
> Removing -Werror from CMakeLists.txt

Why?

**Comment by yrpen** [comment]
> > Removing -Werror from CMakeLists.txt
> 
> Why?

```
$ make
[  1%] Generating CXX prefix source cotire/tfs_CXX_prefix.cxx
[  2%] Generating CXX prefix header cotire/tfs_CXX_prefix.hxx
[  3%] Building CXX precompiled header cotire/tfs_CXX_prefix.hxx.gch
Scanning dependencies of target tfs
[  4%] Building CXX object CMakeFiles/tfs.dir/src/otpch.cpp.o
cc1plus: error: /home/tfs/forgottenserver/build/cotire/tfs_CXX_prefix.hxx.gch: had text segment at different address [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/tfs.dir/build.make:77: CMakeFiles/tfs.dir/src/otpch.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/tfs.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by DSpeichert** [comment]
I'd be curious why CentOS specifically flags that. I'd rather not remove Werror there.

**Comment by yrpen** [comment]
> I'd be curious why CentOS specifically flags that. I'd rather not remove Werror there.

Here are some CMake logs.
https://otland.net/threads/compiling-tfs-1-3-on-centos-8.269375/post-2599369

I guess it can be line 9

```
c++: error: unrecognized command line option '-stdlib=libc++'
```

**Comment by DSpeichert** [comment]
It seems to be a problem affecting a lot of software on CentOS 8:
https://bugzilla.redhat.com/show_bug.cgi?id=1721553#c11

**Comment by yrpen** [comment]
> It seems to be a problem affecting a lot of software on CentOS 8:
> https://bugzilla.redhat.com/show_bug.cgi?id=1721553#c11

Thanks for investigate this and fix wiki.

Now I can try make systemd file in ubuntu and centos and try to give feedback in spare time :D
