### ISSUE TITLE
Player::queryAdd always picking first slot

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#2954]
how to reproduce:
- have a full container of items:
![2020-04-21 18_48_41-CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US](https://user-images.githubusercontent.com/4684880/79917372-c2b91f80-8400-11ea-8689-ee1a4e3a2239.png)

- try to move a meat from the ground to the stack with 20 meat (or to any stack that is not the first)

result: it will move the meat to the first slot, no matter what slot you move it to

curious fact: it works fine moving meats from a stack to another tho, but from outside the container there is the bug

**Comment by nekiro** [comment]
I noticed this too. I believe its client issue, could you try to test that with otc? This only happens if container is full, it will always push index as 1 for some reason.

**Comment by EPuncker** [comment]
> I noticed this too. I believe its client issue, could you try to test that with otc? This only happens if container is full, it will always push index as 1 for some reason.
just did, same thing 🤔 gonna try rl tibia

**Comment by nekiro** [comment]
I see, so this might be actually bug with auto stack code inside the server, because as far as I know it will always choose the first item that matches the search in this case your index 1 is the one that matches the "query", so maybe even if we have destination supplied it will try to do that. I didn't investigate it's my wild guess right now.

**Comment by EPuncker** [comment]
![asdasd](https://user-images.githubusercontent.com/4684880/79918603-1e84a800-8403-11ea-947b-404acb09d04f.gif)

**Comment by nekiro** [comment]
@EPuncker it only happens if top parent of container is tile, am I right?

**Comment by DSpeichert** [comment]
@EPuncker is that from RL? We can confirm it as a bug then.
