### ISSUE TITLE
tile:getThing(stack) not working properly

### ISSUE THREAD

**Issue by andersonfaaria** [otland/forgottenserver#2957]
I don't know why and I can't confirm if this is the correct way of reproducing the issue but apparently when you have a stack of items in a single tile the function return the stacks in a wrong order.

Just iterating a tile with 3 borders (10639, 10638, 10640), a parcel, a backpack, a bag and a vial (in this order) for example produces me following output:
![image](https://user-images.githubusercontent.com/8560144/79928645-dd4bc280-8419-11ea-80a6-f306924a2cdf.png)
Understand blue as correct order and red as reverse order

It is giving me the answer in the reverse order divided by groups (topGroups) when in fact the items should be returned by their position in the stack.

The same behavior happens in tile:getItems() but with different results
![image](https://user-images.githubusercontent.com/8560144/79928624-cad18900-8419-11ea-9b0c-514fedbc3e46.png)

This is really giving me a hard time to get first item in a tile that isn't a border.

If you want to replicate, just use the following code inside a script with a defined pos:
```lua
local stack = STACKPOS_FIRST_ITEM_ABOVE_GROUNDTILE
		local items = tile:getItems()
		for i, v in ipairs(items) do print(i, v:getName(), v:getId()) end
		
		while (stack <= STACKPOS_FIFTH_ITEM_ABOVE_GROUNDTILE) do
			chest = tile:getThing(stack)--tile:getTopDownItem()--
			if chest and chest:getName() then
				print("(".. position.x ..", ".. position.y ..", ".. position.z ..") Searching at stack ".. stack ..", found: ".. chest:getName() .." ".. chest:getId())
			end
			stack = stack + 1		
		end
```

**Comment by nekiro** [comment]
Can you format your issue to use issue template? I have hard time understanding what do you expect from it and how it works atm

**Comment by andersonfaaria** [comment]
> Can you format your issue to use issue template? I have hard time understanding what do you expect from it and how it works atm
somehow the issue template did not appeared to me, I think someone might have deleted it.

The order is this: 3 borders (10639, 10638, 10640), a parcel, a backpack, a bag and a vial. The functions are returning the items in the wrong stack order.

**Comment by MillhioreBT** [comment]
El comportamiento que usted quiere es el siguiente:
```lua
function getTileItemByIndex(tile, index)
	local items = tile:getItems()
	return items[#items-index+1]
end
```
![image](https://user-images.githubusercontent.com/28090948/80294576-5019ae00-8738-11ea-80ad-a06b320f2364.png)

**Comment by andersonfaaria** [comment]
> The behavior you want is as follows:
> 
> ```lua
> function getTileItemByIndex(tile, index)
> 	local items = tile:getItems()
> 	return items[#items-index+1]
> end
> ```
> 
> ![image](https://user-images.githubusercontent.com/28090948/80294576-5019ae00-8738-11ea-80ad-a06b320f2364.png)

this still wouldn't give the correct items in correct order

**Comment by MillhioreBT** [comment]
> > The behavior you want is as follows:
> > ```lua
> > function getTileItemByIndex(tile, index)
> > 	local items = tile:getItems()
> > 	return items[#items-index+1]
> > end
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/28090948/80294576-5019ae00-8738-11ea-80ad-a06b320f2364.png)
> 
> this still wouldn't give the correct items in correct order

Can you show a picture of what the correct order looks like to you? because your code was not very illustrative, please

**Comment by andersonfaaria** [comment]
Correct order:

[1] 10639
[2] 10638
[3] 10640
[4] 9081 -- parcel
[5] 1988 -- backpack
[6] 1992 -- yellow bag
[7] 7636 -- empty potion flask

tile:getItems() order: 
![image](https://user-images.githubusercontent.com/8560144/80588733-3fdf2880-89ef-11ea-8cd6-729e59f09c69.png)


tile:getThing(stack) order:
![image](https://user-images.githubusercontent.com/8560144/80588768-508f9e80-89ef-11ea-929b-de9dcc50c421.png)

**Comment by MillhioreBT** [comment]
If you use the index provided in the packet input (_0x82_) and others ... this function works correctly, so for me this works fine.
![image](https://user-images.githubusercontent.com/28090948/81634869-d04d3e00-93dd-11ea-9aaa-ab8ff4499678.png)

**Comment by andersonfaaria** [comment]
@MillhioreBT I have already done it in my server using another logic, I have no idea what skipBytes and getByte is doing in your example but workarounds are not the way to go here.

I appreciate that you're trying to help me but I would be using the forum if I needed guidance. I'm just reporting the 2 functions don't work as expected.

**Comment by gesior** [comment]
**I THINK IT CAN BE CLOSED**

Items order on server side is related to weird `items and creatures on tile` implementation in Tibia Client, and Tibia communication protocol. There are items with 'alwaysOnTop' attribute, which does not disappear, even if you put 10+ items on given tile (tile items limit in client).
You cannot put items on tile in any order. When you add them in wrong order, server takes care of it and put them on valid stack [index].

`tile:getItems()` return list of items, which in real contains 2 list of items. 'top item' and 'down items'. They are on one list to make it execute faster 'is item on tile'.
If you want to read this in some other 'order' than Tibia implementation, use `tile:getDownItemCount()` and `tile:getTopItemCount()` to get information on which index start second (reversed) list.

Item structure is optimized to send tiles and changes on tiles to client as fast as possible.
You should check `tile.cpp` and `protocolgame.cpp` implementation of items and creatures on tile communication.

MillhioreBT is not doing anything special. He just reads `stackpos` sent from Tibia client, which is not position on list in `items` in `tile.cpp` on server side. On server side you can put 1000 items on tile, in client only 10 will be visible and transferred from server.
It's server job to decide which 10 should be visible - it takes a lot of calculation and is executed 100k times per second on popular servers, so data structures are designed to handle this as fast as possible.

**Comment by gesior** [comment]
For anyone having problem with handling items on tile, I made 3 functions that extend `Tile`.
Just remember that they waste some CPU and often `tile:getTopDownItem()` is what you really need.

Test tile:
![image](https://user-images.githubusercontent.com/2642737/158562186-206c1260-ecfb-4bc6-9f68-e85c4682a40e.png)

How they work:
`tile:getTopItem()` - get top item visible in game (yellow bag)
`tile:getAllItems()` - get all tile items, including ground item, in order from top visible in game (yellow bag at index 1)
`tile:getAllItemsReversed()` - get all tile items, including ground item, in order from bottom visible in game (stone floor [ground] at index 1)

Add this to `data/lib/core/tile.lua`:
```lua
function Tile.getTopItem(self)
    local items = self:getItems()
    if items and #items > 0 then
        return items[#items]
    end

    return self:getGround()
end

function Tile.getAllItems(self)
    local items = {}

    local tileItems = self:getItems()
    if tileItems and #tileItems > 0 then
        items = tileItems
    end

    local ground = self:getGround()
    if ground then
        table.insert(items, ground)
    end

    return items
end

function Tile.getAllItemsReversed(self)
    local tileItems = self:getAllItems()
    local items = {}

    if tileItems and #tileItems > 0 then
        for i = #tileItems, 1, -1 do
            table.insert(items, tileItems[i])
        end
    end

    return items
end
```

Test results on tile from screenshot:
```
TEST getItems
getItems    1    1992    yellow bag
getItems    2    1988    backpack
getItems    3    9081    parcel
getItems    4    10640    sand
getItems    5    10638    sand
getItems    6    10639    sand

TEST allTileItems
allTileItems    1    1992    yellow bag
allTileItems    2    1988    backpack
allTileItems    3    9081    parcel
allTileItems    4    10640    sand
allTileItems    5    10638    sand
allTileItems    6    10639    sand
allTileItems    7    413    stone floor

TEST getAllItemsReversed
getAllItemsReversed    1    413    stone floor
getAllItemsReversed    2    10639    sand
getAllItemsReversed    3    10638    sand
getAllItemsReversed    4    10640    sand
getAllItemsReversed    5    9081    parcel
getAllItemsReversed    6    1988    backpack
getAllItemsReversed    7    1992    yellow bag

topTop    10639    sand
topDown    1992    yellow bag
topItem    10639    sand
```
