### ISSUE TITLE
Something is wrong with stackpos

### ISSUE THREAD

**Issue by renanluis90** [otland/forgottenserver#2960]
Here my test in Realots ( the correct behavior)
https://streamable.com/4fimii

the problem is in the order that the 1 gp stay.

Here my test in TFS 1.2
https://streamable.com/yqts6p

Anyone here can test this behavior on Actual tibia and tfs? to confirm this?

**Comment by EPuncker** [comment]
nothing wrong... your "correct behavior" might be right for that version, but not for latest tibia:

![asdasd](https://user-images.githubusercontent.com/4684880/80037590-412dc400-84ca-11ea-80bd-9edabdedcac2.gif)

and actual tfs does the same
