### ISSUE TITLE
Aleta grav does not work in front of closed house door

### ISSUE THREAD

**Issue by DSpeichert** [otland/forgottenserver#2983]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Stand inside the house, face front door
2. Make sure the door is closed
3. `aleta grav`

### Expected behaviour
Door list should be editable

### Actual behaviour
Door list cannot be edited.
The command only works when front door is open.

### Environment
N/A

**Comment by MillhioreBT** [comment]
There are two options, change the behavior of the function that controls **casterTargetOrDirection="1"** or simply change the script for this:
```lua
function onCastSpell(creature, variant)
	local cPosition = creature:getPosition()
	local house = Tile(cPosition):getHouse()
	cPosition:getNextPosition(creature:getDirection())
	local doorId = house and house:getDoorIdByPosition(cPosition)
	if not doorId or not house:canEditAccessList(doorId, creature) then
		creature:sendCancelMessage(RETURNVALUE_NOTPOSSIBLE)
		creature:getPosition():sendMagicEffect(CONST_ME_POFF)
		return false
	end

	creature:setEditHouse(house, doorId)
	creature:sendHouseWindow(house, doorId)
	return true
end
```
and remove **casterTargetOrDirection** on spells.xml
