### ISSUE TITLE
CTRL Dash

### ISSUE THREAD

**Issue by Peixonauta2** [otland/forgottenserver#2988]
I just realized that The Forgotten Server does not have the infamous gamemaster dash (hold ctrl and arrow to dash).
Is this on the source or it's a missing feature?

**Comment by EvilHero90** [comment]
It is not implemented that's correct.

**Comment by nekiro** [comment]
This feature spams packets (so you get kicked out often), which is one argument against having that.

**Comment by Zbizu** [comment]
if you need it on your server, feel free to copy it from here
https://github.com/mattyx14/otxserver/blob/otxserv4/data/events/scripts/player.lua#L549

btw that walk uses around 40 packets per second (just tested)
potential downside: it lets players with otclient/bot use dash (increased walking speed)

**Comment by Peixonauta2** [comment]
Well, I just added that to my player.lua and It doesn't works.
Need to modify something else?
