### ISSUE TITLE
working on a new feature - onSay - creatureevent or event creature?

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#2998]
Hello, I had an idea to rework the way onSay and onHear are executed to make it hackable the way onHealthChange currently works (use return to change input values).

Should I code it as a creaturescript or a creature event? (I'm asking because I want to pull request here later)

**option 1** - creaturescript version: `xml -> registerEvent -> function onSay(creature, text, talktype)` I'm aware that such thing already exists for npcs (and possibly monsters) so this one can be tricky to expand it to players and make it working on monsters and npcs as well.

**option 2** - event version: `events.xml -> creature.lua -> function Creature:onSay(text, talktype)`

onHear edit (independent on those above): `return creature, text, talktype` support with some crash prevention

In case my description wasn't clear enough, I will fill the feature request template below.

### Explanation of what you want to do that is currently impossible
- change the text creatures say or hear

### Desired functionality
- change the text creatures say or hear so scripts like spam filters or word replacers could be created

### Available workarounds
- talkactions (limited to specific way of using only)

### Prior art
(want things like this to be possible in lua)
- https://otland.net/threads/lua-and-c-block-ips-links-on-default-trade-help.50954/

side note: I also want to script chat channels including private using similar event

**Comment by EPuncker** [comment]
events 👍

**Comment by Zbizu** [comment]
turns out turning onHear into bool was more efficient solution
