### ISSUE TITLE
C1083	Cannot open include file: 'lua.hpp': No such file or directory	

### ISSUE THREAD

**Issue by MohamedRefaat** [otland/forgottenserver#3009]
After i updated to latest commit [here ](https://github.com/otland/forgottenserver/commit/4233f740f2e12f191fc8538e9631f64e7e702f37) and started to compile i got this error.
I think i need to add lua.hpp into src folder, right?
and where i can find this file to add it into src folder?

**Comment by MohamedRefaat** [comment]
I think it should be luajit/lua.hpp ?

**Comment by DSpeichert** [comment]
Follow the [issue template](https://raw.githubusercontent.com/otland/forgottenserver/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

What's your environment?

**Comment by gpedro** [comment]
if you are using Windows, consider install dependencies:
```
./vcpkg install lua:x86-windows lua:x64-windows
```

**Comment by DSpeichert** [comment]
Luajit has NOT been dropped. It will work fine when you have LuaJIT installed.
On Windows, when compiling with MSVS, makes sure you uninstall Lua first.
Both options still work, you can toggle them with `cmake .. -DUSE_LUAJIT=on/off`

**Comment by MohamedRefaat** [comment]
> Follow the [issue template](https://raw.githubusercontent.com/otland/forgottenserver/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
> 
> What's your environment?

Sorry.
I am using windows, Microsoft visual studio 2019.
When i edited it in configmanager.cpp and luascript.h to be luajit/lua.hpp error disappeared. Is it correct?

**Comment by DSpeichert** [comment]
No, that shouldn't happen, I tested. Make sure you are using the updated project file from vc14.
It sounds like you're using an old one.

**Comment by MohamedRefaat** [comment]
> No, that shouldn't happen, I tested. Make sure you are using the updated project file from vc14.
> It sounds like you're using an old one.

I noticed you updated it and i made the update before doing compile and get the error.

**Comment by MohamedRefaat** [comment]
> if you are using Windows, consider install dependencies:
> 
> ```
> ./vcpkg install lua:x86-windows lua:x64-windows
> ```
> 
> if you are using Ubuntu, consider install dependencies:
> 
> ```
> apt install -y lua5.2-dev
> ```
> 
> --
> i have noticed by some users is getting this error cuz you have dropped luajit and some users haven't lua libs installed, only luajit. @DSpeichert

Should i use these commands to fix it instead of adding (luajit/) lua.hpp ?

**Comment by DSpeichert** [comment]
No, do NOT install `lua` at the same time as luajit, because you may accidentally link against `lua`. You don't want that.

Make sure lua is NOT installed, and that only `luajit:x64-windows` IS installed.

Then try to run `vcpkg install integrate` etc. again. MSVS requires the "integration" to find/detect luajit properly. We have AppVeyor testing this setup in addition to me locally, so it somehow works.

**Comment by MohamedRefaat** [comment]
> No, do NOT install `lua` at the same time as luajit, because you may accidentally link against `lua`. You don't want that.
> 
> Make sure lua is NOT installed, and that only `luajit:x64-windows` IS installed.
> 
> Then try to run `vcpkg install integrate` etc. again. MSVS requires the "integration" to find/detect luajit properly. We have AppVeyor testing this setup in addition to me locally, so it somehow works.

Can you tell me how can i make sure that lua not installed?

**Comment by gpedro** [comment]
> > No, do NOT install `lua` at the same time as luajit, because you may accidentally link against `lua`. You don't want that.
> > Make sure lua is NOT installed, and that only `luajit:x64-windows` IS installed.
> > Then try to run `vcpkg install integrate` etc. again. MSVS requires the "integration" to find/detect luajit properly. We have AppVeyor testing this setup in addition to me locally, so it somehow works.
> 
> Can you tell me how can i make sure that lua not installed?

`.\vcpkg.exe list lua`

**Comment by DSpeichert** [comment]
`vcpkg remove lua:x64-windows lua:x86-windows`

**Comment by MillhioreBT** [comment]
Something similar happened to me, however just change this and it already works wonderfully:
```c++
#include <lua.hpp>
```
to
```c++
#if __has_include("luajit/lua.hpp")
#include <luajit/lua.hpp>
#else
#include <lua.hpp>
#endif
```
I don't understand why it doesn't look for lua.hpp in the default luajit folder?

**Comment by MohamedRefaat** [comment]
> 
> 
> Something similar happened to me, however just change this and it already works wonderfully:
> 
> ```c++
> #include <lua.hpp>
> ```
> 
> to
> 
> ```c++
> #if __has_include("luajit/lua.hpp")
> #include <luajit/lua.hpp>
> #else
> #include <lua.hpp>
> #endif
> ```
> 
> I don't understand why it doesn't look for lua.hpp in the default luajit folder?



> 
> 
> > Can you tell me how can i make sure that lua not installed?
> 
> `.\vcpkg.exe owns lua`

$ ./vcpkg.exe owns lua
luajit:x64-windows: x64-windows/bin/lua51.dll
luajit:x64-windows: x64-windows/bin/lua51.pdb
luajit:x64-windows: x64-windows/debug/bin/lua51.dll
luajit:x64-windows: x64-windows/debug/bin/lua51.pdb
luajit:x64-windows: x64-windows/debug/lib/lua51.lib
luajit:x64-windows: x64-windows/debug/tools/lua51.dll
luajit:x64-windows: x64-windows/debug/tools/luajit.exe
luajit:x64-windows: x64-windows/include/luajit/lauxlib.h
luajit:x64-windows: x64-windows/include/luajit/lua.h
luajit:x64-windows: x64-windows/include/luajit/lua.hpp
luajit:x64-windows: x64-windows/include/luajit/luaconf.h
luajit:x64-windows: x64-windows/include/luajit/luajit.h
luajit:x64-windows: x64-windows/include/luajit/lualib.h
luajit:x64-windows: x64-windows/lib/lua51.lib
luajit:x64-windows: x64-windows/share/luajit/COPYRIGHT
luajit:x64-windows: x64-windows/share/luajit/vcpkg_abi_info.txt
luajit:x64-windows: x64-windows/tools/lua51.dll
luajit:x64-windows: x64-windows/tools/luajit.exe
boost-config:x64-windows: x64-windows/share/boost-config/checks/std/cpp_lib_is_constant_evaluated_20.cpp


> 
> 
> `vcpkg remove lua:x64-windows lua:x86-windows`

$ ./vcpkg.exe remove lua:x64-windows lua:x86-windows
The following packages are not installed, so not removed:
    lua:x64-windows
    lua:x86-windows
Package lua:x64-windows is not installed
Package lua:x86-windows is not installed



> 
> 
> Something similar happened to me, however just change this and it already works wonderfully:
> 
> ```c++
> #include <lua.hpp>
> ```
> 
> to
> 
> ```c++
> #if __has_include("luajit/lua.hpp")
> #include <luajit/lua.hpp>
> #else
> #include <lua.hpp>
> #endif
> ```
> 
> I don't understand why it doesn't look for lua.hpp in the default luajit folder?

This change makes it back to default before the commit of DSpeichert and ofc it is working.

**Comment by DSpeichert** [comment]
Delete everything you have in build folder and try again.

**Comment by MohamedRefaat** [comment]
> 
> 
> Delete everything you have in build folder and try again.

I deleted everything, downloaded master branch and tried it but still have the error.
Only work when i make it back to be 
#if __has_include("luajit/lua.hpp")
#include <luajit/lua.hpp>
#else
#include <lua.hpp>
#endif

**Comment by CristoferMartins** [comment]
I can confirm this issue. @MillhioreBT fix works good.

**Comment by gpedro** [comment]
i can confirm this issue too, but the @DSpeichert solution works for me.

```
.\vcpkg.exe remove lua:x86-windows
.\vcpkg.exe remove lua:x64-windows
```

on VStudio, Build > Clean Solution and Build > Rebuild Solution

**Comment by nekiro** [comment]
In my case running these fixed my issue with compiling:
```
vcpkg install --triplet x64-windows boost-iostreams boost-asio boost-system boost-filesystem boost-variant boost-lockfree luajit libmariadb pugixml cryptopp
.\bootstrap-vcpkg.bat
.\vcpkg integrate install
```
probably integrate install is enough, give it a try.

**Comment by DSpeichert** [comment]
in MSVS you never had the option to choose between luajit and lua, it always preferred Luajit (hasinclude) and then lua if Luajit wasn't found

Using cmake (typically on Linux/mac only because it was broken on Windows, nobody used it because MSVS was preferred), you had the `-DUSE_LUAJIT=on` and `-DUSE_LUAJIT=off` flags to toggle between LuaJIT and Lua.

While the flags worked and cmake was including correct includes and linking correct libs, when the source was explicitly including luajit/lua.hpp it was using and even when configured to use Lua via `-DUSE_LUAJIT=off`!
Now, with with changes in #2973, it works properly on Mac/Win/Linux when using cmake.

On MSVS, you still can't really control it very well. Now, though, instead of preferring Luajit over Lua, it's kinda random. That's why when using MSVS it's best to only have one of them installed. Then you know which one it will use.

So far, everyone who had this probably solved it by:
1. ensuring LuaJIT is installed (`vcpkg install luajit:x64-windows`)
2. ensuring Lua is NOT installed (`vcpkg remove lua:x64-windows`)
3. Running `vcpkg integrate install`
4. Restarting MSVS AFTER you run `vcpkg integrate install`

Then it will successfully link with LuaJIT.

**Comment by EPuncker** [comment]
@MohamedRefaat can you confirm that the #3029 fixes the issue? it fixed for me, because doing all of the 4 options that @DSpeichert gave didn't fixed the error for me (sorry for being late to the party 😄 ) but the change from @slavidodo did fix it

**Comment by MohamedRefaat** [comment]
> 
> 
> @MohamedRefaat can you confirm that the #3029 fixes the issue? it fixed for me, because doing all of the 4 options that @DSpeichert gave didn't fixed the error for me (sorry for being late to the party 😄 ) but the change from @slavidodo did fix it

Sorry for being late, it is fixd with it.

**Comment by Kamenuvol** [comment]
It was ok to me before I update all packages of vcpkg. After upgrading I cannot compile because of this same error.
@DSpeichert have you tested with current version of vcpkg and libs?

**Comment by VictorArchela** [comment]
> in MSVS you never had the option to choose between luajit and lua, it always preferred Luajit (hasinclude) and then lua if Luajit wasn't found
> 
> Using cmake (typically on Linux/mac only because it was broken on Windows, nobody used it because MSVS was preferred), you had the `-DUSE_LUAJIT=on` and `-DUSE_LUAJIT=off` flags to toggle between LuaJIT and Lua.
> 
> While the flags worked and cmake was including correct includes and linking correct libs, when the source was explicitly including luajit/lua.hpp it was using and even when configured to use Lua via `-DUSE_LUAJIT=off`!
> Now, with with changes in #2973, it works properly on Mac/Win/Linux when using cmake.
> 
> On MSVS, you still can't really control it very well. Now, though, instead of preferring Luajit over Lua, it's kinda random. That's why when using MSVS it's best to only have one of them installed. Then you know which one it will use.
> 
> So far, everyone who had this probably solved it by:
> 
> 1. ensuring LuaJIT is installed (`vcpkg install luajit:x64-windows`)
> 2. ensuring Lua is NOT installed (`vcpkg remove lua:x64-windows`)
> 3. Running `vcpkg integrate install`
> 4. Restarting MSVS AFTER you run `vcpkg integrate install`
> 
> Then it will successfully link with LuaJIT.

Did all of this but am still facing the issue. LuaJIT is the only one installed. Erased the build and everything. Btw I cloned the source just yesterday so it should all be up to date. 
this seems to help though:

Replacing:
#include <lua.hpp>

For:
#if __has_include("luajit/lua.hpp")
#include <luajit/lua.hpp>
#else
#include <lua.hpp>
#endif

**Comment by DSpeichert** [comment]
We can add this change (`__has_include`) when we bump requirement to C++17.

**Comment by soul4soul** [comment]
To have a bit more detail for those who don't know this issue comes from vcpkg. I don't recall the exact version where it happened but its pretty easy to sleuth it out by searching in the vcpkg github repo. The summary is vcpkg devs decided for various reasons different packages should never place headers in the same folder even if they are API compatible. So at some point they moved the luajit package into the luajit folder and they left the lua package where it was.

**Comment by randal923** [comment]
Problem still persists. I did what @VictorArchela said and it worked.
