### ISSUE TITLE
monster.voices not working in revscriptsys monsters

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3015]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. enable example monster or any other that have monster.voices
2. start tfs and create/spawn the monster

### Expected behaviour
monster should shout their sentences

### Actual behaviour
nothing happens at all, even if you set chance = 100

**Comment by EvilHero90** [comment]
![example](https://user-images.githubusercontent.com/3682541/80934290-d3d23b00-8dc7-11ea-84af-f64248b17c0f.png)

**Comment by EPuncker** [comment]
@EvilHero90 my bad, it was not working because of the speed error 🤣
