### ISSUE TITLE
delayed monster body drop bug (fix inside)

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#3023]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

Possibly a duplicate, but I can't find the original issue.

### Steps to reproduce (include any configuration/script required to reproduce)
1. spawn monsters
2. kill monsters

### Expected behaviour
body drops instantly (just like in official servers)

### Actual behaviour
body drops after a short delay dictated by EVENT_CREATURE_THINK_INTERVAL

### Reproduction rate
high, but unknown (depends on sync with interval)

### Reproduction environment
master branch, any os/hardware

### Potential solution
moving creatures death from here:
https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L3690

to here:
https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L4251

I don't have time to fix it myself and test stability in cases like when some admin decides to spam ue on his server and I don't know how to detect potential data races so I'm reporting it here with potential solution. In fact current implementation is better for big servers so you can make it toggleable in config.lua.

**Comment by nekiro** [comment]
There is a reason it works this way, as far as I remember they are not deleted instantly, because you still store references to these creatures in other places in code, so this is to avoid crashes. I don't really know if thats true, because I never tested that, but the real solution to that issue and countless others is using smart pointers for creatures, monsters and players

**Comment by kygov** [comment]
Actually I'm using code without delay (moved onDeath from checkCreatures to changeHealth) and there is no problems. It was tested with 1000 active players, more than 3 years without crashes.

**Comment by Zbizu** [comment]
important: I forgot about summons, they have to be removed when their master is dying too

**Comment by kygov** [comment]
@Zbizu https://github.com/otland/forgottenserver/blob/master/src/creature.cpp#L43

**Comment by joseluis2g** [comment]
would you like to create a PR my friend?

**Comment by kygov** [comment]
https://github.com/otland/forgottenserver/pull/3030
