### ISSUE TITLE
Error while compiling, cannot find lua.hpp file

### ISSUE THREAD

**Issue by henriquenovais** [otland/forgottenserver#3026]
Hi guys, I keep having this error:

Error C1083	
Cannot open include file: 'lua.hpp': No such file or directory (compiling source file ..\src\chat.cpp)	theforgottenserver	C:\vcpkg\forgottenserver\src\luascript.h

It repeats a bunch of times.

**Comment by henriquenovais** [comment]
I am compiling through Windows using vcpkg(x64) and Visual Studio Code 2019. I already tried using the Debug mode.

**Comment by MohamedRefaat** [comment]
We still checking this problem here
https://github.com/otland/forgottenserver/issues/3009
