### ISSUE TITLE
Ubuntu Issues Compilation 20.04

### ISSUE THREAD

**Issue by neonsoft** [otland/forgottenserver#3047]
root@server1:/home# cd forgottenserver
root@server1:/home/forgottenserver# mkdir build && cd build
root@server1:/home/forgottenserver/build# cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Crypto++: /usr/include
-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib/x86_64-linux-gnu
-- MySQL client libraries: /usr/lib/x86_64-linux-gnu/libmysqlclient.so;-ldl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PugiXML: /usr/include
-- Found LuaJIT: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so;/usr/lib/x86_64-linu                                                     x-gnu/libm.so (found version "2.1.0-beta3")
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:11                                                     7 (find_package):
  Could not find a package configuration file provided by "boost_date_time"
  (requested version 1.71.0) with any of the following names:

    boost_date_timeConfig.cmake
    boost_date_time-config.cmake

  Add the installation prefix of "boost_date_time" to CMAKE_PREFIX_PATH or
  set "boost_date_time_DIR" to a directory containing one of the above files.
  If "boost_date_time" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find                                                     _component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:63 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/forgottenserver/build/CMakeFiles/CMakeOutput.log".
See also "/home/forgottenserver/build/CMakeFiles/CMakeError.log".
root@server1:/home/forgottenserver/build#

**Comment by neonsoft** [comment]
problem fixed. need  apt install libboost-date-time-dev

 :D

**Comment by Znote** [comment]
Updated the wiki: 
https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu
