### ISSUE TITLE
Client crashes when mounting with GM outfit (also any non-standard outfits)

### ISSUE THREAD

**Issue by gigastar** [otland/forgottenserver#3051]
If you are using the GM outfit or any outfits you add other than the standard male/female outfits the client with crash when you try to mount. I created a fix for this but its probably not the best way.

In Player.cpp change player:toggleMount(bool mount) with this

int outfitIds [] = {128, 129, 130, 131, 132, 133, 134, 136, 137, 138, 139, 140, 141, 142, 143, 
144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 251, 268, 273, 278,
289, 325, 328, 335, 367, 430, 432, 463, 465, 472, 512, 516, 541, 574, 577, 610, 619, 633, 634, 
637, 665, 667, 684, 695, 697, 699, 725, 733, 746, 750, 760, 846, 853, 873, 884, 899, 252, 269, 
270, 279, 288, 324, 329, 336, 366, 431, 433, 464, 466, 471, 513, 514, 542, 575, 578, 618, 620, 
632, 635, 636, 664, 666, 683, 694, 696, 698, 724, 732, 745, 749, 759, 845, 852, 874, 885, 900};

bool Player::toggleMount(bool mount)
{
	if ((OTSYS_TIME() - lastToggleMount) < 3000 && !wasMounted) {
		sendCancelMessage(RETURNVALUE_YOUAREEXHAUSTED);
		return false;
	}

	if (mount) {
		if (isMounted()) {
			return false;
		}

		const Outfit* playerOutfit = Outfits::getInstance().getOutfitByLookType(getSex(), defaultOutfit.lookType);
		if (!playerOutfit) {
			return false;
		}
		
		bool canMount = false;
		std::vector<int> outfitsAllowed (outfitIds,outfitIds + 110);
		std::vector<int>::iterator it;
		
		it = find (outfitsAllowed.begin(), outfitsAllowed.end(), defaultOutfit.lookType);
		if (it != outfitsAllowed.end()) {
			canMount = true;
		}
		
		if (!canMount) {
			return false;
		}

		uint8_t currentMountId = getCurrentMount();
		if (currentMountId == 0) {
			sendOutfitWindow();
			return false;
		}

		Mount* currentMount = g_game.mounts.getMountByID(currentMountId);
		if (!currentMount) {
			return false;
		}

		if (!hasMount(currentMount)) {
			setCurrentMount(0);
			sendOutfitWindow();
			return false;
		}

		if (currentMount->premium && !isPremium()) {
			sendCancelMessage(RETURNVALUE_YOUNEEDPREMIUMACCOUNT);
			return false;
		}

		if (hasCondition(CONDITION_OUTFIT)) {
			sendCancelMessage(RETURNVALUE_NOTPOSSIBLE);
			return false;
		}

		defaultOutfit.lookMount = currentMount->clientId;

		if (currentMount->speed != 0) {
			g_game.changeSpeed(this, currentMount->speed);
		}
	} else {
		if (!isMounted()) {
			return false;
		}

		dismount();
	}

	g_game.internalCreatureChangeOutfit(this, defaultOutfit);
	lastToggleMount = OTSYS_TIME();
	return true;
}

**Comment by MillhioreBT** [comment]
I just tested your theory and it is not correct, mounts and outfits work very well, no crash!
if you can explain the detailed steps to generate this crash it would be perfect.

**Comment by EPuncker** [comment]
> I just tested your theory and it is not correct, mounts and outfits work very well, no crash!
> if you can explain the detailed steps to generate this crash it would be perfect.

I know one outfit that crash with mount tho 😄 looktype="1152"

**Comment by MillhioreBT** [comment]
> > I just tested your theory and it is not correct, mounts and outfits work very well, no crash!
> > if you can explain the detailed steps to generate this crash it would be perfect.
> 
> I know one outfit that crash with mount tho 😄 looktype="1152"

looktype `1152` does not exist in XML files
Am I downloading the base repository wrong? or do you mean extra modifications that don't work?

**Comment by EPuncker** [comment]
> > > I just tested your theory and it is not correct, mounts and outfits work very well, no crash!
> > > if you can explain the detailed steps to generate this crash it would be perfect.
> > 
> > 
> > I know one outfit that crash with mount tho 😄 looktype="1152"
> 
> looktype `1152` does not exist in XML files
> Am I downloading the base repository wrong? or do you mean extra modifications that don't work?

oh sorry, it is the burning outfit, my bad, I always forget that sometimes I use new sprites in 10.98 for fun 😛

**Comment by nekiro** [comment]
What is crashing? Use issue template. I bet its your client crashing right?

**Comment by EPuncker** [comment]
indeed I've just tested right now with gamemaster outfit, tried to mount and nothing happened, the client didn't crash, the char didn't mount

**Comment by Felipe21** [comment]
but if you add new outfits that doesn't handle mounts you'll get a crash how to add new outfits  and block mount for them?
