### ISSUE TITLE
Promotion bug

### ISSUE THREAD

**Issue by BahamutxD** [otland/forgottenserver#3053]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Any character with no vocation will get promotion storage = 1 upon login
2. As soon as that character gets a vocation it will be promoted after logout/login (overriding the oracle vocation it just got and applying the promotion storage = 1 it had)

### Expected behaviour
Characters shouldn't be getting the promotion storage for logging in while they have no vocation

### Actual behaviour
You are getting promoted after you get your vocation and logout/login

**Comment by EPuncker** [comment]
that is weird, the code looks fine:

https://github.com/otland/forgottenserver/blob/master/data/creaturescripts/scripts/login.lua#L19-L30

and here:
https://github.com/otland/forgottenserver/blob/master/data/npc/lib/npcsystem/modules.lua#L88

**Comment by BahamutxD** [comment]
Issue on my end. Closing this.

Just incase anyone finds this - some Svargrond arena quest script I took from OTLand was using the same storage as promotion 30018 and was registering on login.

**Comment by BahamutxD** [comment]
Upon further testing there seems to be an issue in the promotion code inside login.lua

I followed this thread https://otland.net/threads/promotion-bug-tfs-1-3.269300/post-2608312 and managed to find fix with the help of @EPuncker but due to my lack of knowledge others may need to confirm the issue and solution.

**Comment by EPuncker** [comment]
can anyone kindly confirm if changing:

`if not promotion and value ~= 1 then`

to:

`if not promotion and value == -1 then`

fixes the issue?

**Comment by ramon-bernardo** [comment]
My result: 
Player without a vocation, remains without a vocation and does not receive storage when logging in.
Player 'Admin' does not have permission, only premium.

```
if not promotion and value ~= 1 then
	player:setStorageValue(PlayerStorageKeys.promotion, 1)
	print("Storage set.")
elseif value == 1 then
	player:setVocation(promotion)
	print("Vocation set. Voc: "..player:getVocation():getName())
end
```

![image](https://user-images.githubusercontent.com/53269692/115428894-3b4fe900-a1d9-11eb-9809-c6277e030dcf.png)

![image](https://user-images.githubusercontent.com/53269692/115428796-270bec00-a1d9-11eb-8ac6-9e7ac6deab8a.png)

**Comment by ramon-bernardo** [comment]
Players with premium receive promotion automatically, is this the problem?

Remove it:
```
if not promotion and value ~= 1 then
	player:setStorageValue(PlayerStorageKeys.promotion, 1)
else
```
