### ISSUE TITLE
Compiled from source success but missing files

### ISSUE THREAD

**Issue by chapus** [otland/forgottenserver#3058]
I did all the steps to compile the source code in windows 64bits. When I publish / build the project I see a folder in vc14 x64 Release,  there I can find the .exe  if I start program seems ok but I think im missing some steps:

config.lua was misiing.
key.pem was missing
then the folder data with all the xmls  i dont have them.
then Loading lua libs... can not load folder 'scripts/lib'

What else I need to complete the process. I aprreciate the help.
![Anotación 2020-05-20 130348](https://user-images.githubusercontent.com/1543053/82481079-62b6a700-9a9a-11ea-87bc-eff0858571f1.png)

**Comment by EPuncker** [comment]
you need to download the "server" and put the dll and compiled file on it:

https://github.com/otland/forgottenserver/archive/master.zip

**Comment by chapus** [comment]
Thank you for the response, I did what you say and now it runs "ok" the program but i dont know how long it takes to set the server online,  it stuck in "Initializing gamestate" do i need to wait (5 minutes by now) or something else Im missing.
![Anotación 2020-05-20 132515](https://user-images.githubusercontent.com/1543053/82483116-7fa0a980-9a9d-11ea-8d2d-8d3501d5b54f.png)

**Comment by chapus** [comment]
I had another schema.sql i think that was my problem. Let me double check to close the ticket !.

**Comment by EPuncker** [comment]
now I see you were using tfs 1.2 version compiled on 2016, this is not the ideal place to deal with this matter, next time use our [support forum here](https://otland.net/forums/support.16/) and if you have an issue with tfs itself, open a new issue following the template
