### ISSUE TITLE
Move item to container bug

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3063]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce
1. use a normal character with regular free cap (like 200)
2. make 100 demonic candy ball (id: 12543) and put them on the ground 
3. turn off classic control (in case you use it)
4. hold shift to move one candy ball to your backpack

### Expected behaviour
it should move it to your backpack since it weights only 9.50 oz

### Actual behaviour
it doesn't success move it because it acts like you were trying to move the whole stack that weights 950 oz (using shift and moving to other sqm in the ground works tho)

**Comment by nekiro** [comment]
#2953 introduced this. I already found proper solution, will open pull request.
