### ISSUE TITLE
I can't login TFS 1.2 and 1.3 with OTClient version lowest than 10.98

### ISSUE THREAD

**Issue by yanluccasoliveira** [otland/forgottenserver#3068]
Hello! I can't login TFS 1.2 and 1.3 in a version lowest than 10.98. When I try to login in 10.41 for example, appear the message: **Invalid Token Authentification**, but, if I comment or remove that verification on protocollogin.cpp:

`/*if (!Protocol::RSA_decrypt(msg)) {
		disconnectClient("Invalid authentification token.", version);
		return;
}*/`

Appear the character list and stay loading the character, but never login. What can I do?

**Comment by Xaekai** [comment]
It appears that you have a mismatch between the RSA Pubkey in your client and the RSA Privkey in your server.

**Comment by Xaekai** [comment]
Also, this was definitely something that should have been taken to the support forum first.

**Comment by yanluccasoliveira** [comment]
> It appears that you have a mismatch between the RSA Pubkey in your client and the RSA Privkey in your server.

Where can I find the RSA Key in my client and in the source?

**Comment by yanluccasoliveira** [comment]
> Also, this was definitely something that should have been taken to the support forum first.

I asked help in the forum, but nobody helped me. Moreover, nobody answered me on the forum.

**Comment by EPuncker** [comment]
I could not find any thread regarding this issue on otland, but I found something that may help you ([here](https://otland.net/threads/invalid-authentifiaction-token-error.249497/)), and yes @Xaekai is right, this belongs to support forum, just be patient and someone might answer it for you
