### ISSUE TITLE
Monsters paralyze themselves

### ISSUE THREAD

**Issue by maganiczny** [otland/forgottenserver#3070]
https://github.com/nekiro/forgottenserver/issues/44 [Monsters paralyze themselves]

Yes, this from downgrade but Nekiro suggest that combat and spells are not modified so I decided report bug here.

If monster hit in area, not single point, eg with paralyze, and will be in range then paralyze themselves.

**Comment by EPuncker** [comment]
confirmed, monsters are being paralyzed even if they have the immunity flag, use this rat to test and summon a few: https://pastebin.com/raw/8F7smu2Q 

may be related to this https://github.com/otland/forgottenserver/commit/274722a24045efe780eec6b9b0e769f9eb871335
