### ISSUE TITLE
Refactor current fluid system

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3084]
Currently both TFS and OTC still lays into using the old fluid system where the type were simply repeated every xpatterns*ypatterns, ([code here](https://github.com/otland/otclient/blob/master/src/client/item.cpp#L307-L379)), but since tibia is adding new fluid types (and so we can add custom ones as well), we need to re-do our code, because the client expects fluid types to be in order from 0 to 17/18(ink)

![2020-06-09 11_54_24](https://user-images.githubusercontent.com/4684880/84163567-036c0700-aa48-11ea-9c83-f17632033d6f.png)

**Comment by Zbizu** [comment]
I think that we also need to get rid of fluids from items.xml.

**Comment by nekiro** [comment]
@EPuncker can you write a list of current tibia fluids that are relevant to our current tfs in order, with correct numbers for each fluid type that match client fluid type?

**Comment by nekiro** [comment]
I don't really understand all this pattern part, how should it be or how does vanilla handle it then? Fluids are ordered from 0 to 17

**Comment by Zbizu** [comment]
Why are fluids tied to items.xml anyway? imo they should be in separate file or even moved to lua.

**Comment by nekiro** [comment]
> Why are fluids tied to items.xml anyway? imo they should be in separate file or even moved to lua.
> 
> @nekiro fluid holders have subid, it's similar to old rune charges and item count. We don't really know what is being sent. It's probably determined by spr/dat or in the client code itself.

they arent, server is only taking the name from items.xml.

**Comment by EPuncker** [comment]
this was a mistake, our code is "fine"
