### ISSUE TITLE
Error in duplicate storage value warning (#3072)

### ISSUE THREAD

**Issue by luanluciano93** [otland/forgottenserver#3090]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
Implementation of this review: https://github.com/otland/forgottenserver/commit/d26ee0b80c1a58918714faf28c7b809bc0392566

### Actual behaviour
On windows it presented this error: 
**Lua Script Error: [Main Interface]
data/global.lua
attempt to compare two table values
stack traceback:
        [C]: at 0x7ff73c626a40
        [C]: in function 'sort'
        data/lib/core/storages.lua:38: in main chunk
        [C]: in function 'dofile'
        data/lib/core/core.lua:2: in main chunk
        [C]: in function 'dofile'
        data/lib/lib.lua:2: in main chunk
        [C]: in function 'dofile'
        data/global.lua:2: in main chunk
[Warning - ScriptingManager::loadScriptSystems] Can not load data/global.lua**

**Comment by Znote** [comment]
Tested, confirmed, commit reverted. 
https://github.com/otland/forgottenserver/commit/d37e264098e584ff170e9b37564795415eb518ee
