### ISSUE TITLE
Wild Growth Rune is attack rune?!

### ISSUE THREAD

**Issue by luanluciano93** [otland/forgottenserver#3096]
https://github.com/otland/forgottenserver/blob/master/data/spells/spells.xml#L504-L511

**Support Runes**

	<rune group="support" spellid="14" name="Chameleon Rune" id="2291" allowfaruse="1" charges="1" level="27" magiclevel="4" cooldown="2000" groupcooldown="2000" aggressive="0" selftarget="1" blocktype="solid" script="support/chameleon.lua" />
	<rune group="support" spellid="78" name="Disintegrate Rune" id="2310" allowfaruse="0" charges="3" level="21" magiclevel="4" cooldown="2000" groupcooldown="2000" range="1" script="support/disintegrate_rune.lua" />
	<rune group="support" spellid="30" name="Destroy Field Rune" id="2261" allowfaruse="1" charges="3" level="17" magiclevel="3" cooldown="2000" groupcooldown="2000" aggressive="0" range="5" script="support/destroy_field_rune.lua" />
	<rune group="attack" spellid="94" name="Wild Growth Rune" id="2269" allowfaruse="1" charges="2" level="27" magiclevel="8" cooldown="2000" groupcooldown="2000" blocktype="all" script="attack/wild_growth_rune.lua">
		<vocation name="Druid" />
		<vocation name="Elder Druid" showInDescription="0" />
	</rune>

**Comment by EPuncker** [comment]
according to tibia wiki, yes it shares the cooldown with the attack group and it makes sense since magic wall rune uses it as well

**Comment by luanluciano93** [comment]
I then say that she must be dragged into the attack runes group
