### ISSUE TITLE
getCorpse description

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3097]
Currently our [Player::getCorpse](https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L2091-L2105) is very simple, it either set the lasthitkiller or nothing on the body description, so I went to investigate it on how cipbia handles it and got the following info:

> 20:33 You see a dead human (Vol:10).
> You recognize Zamba Tres. She was killed by something evil and others.
> (killed by map fire field and a bunch of trolls (field did most damage))
> 
> 20:41 You see a dead human (Vol:10).
> You recognize Zamba Tres. She was killed by a bonelord and a ghoul and others.
> (killed by two bonelords and its ghoul summon and the other skeleton summon)
> 
> 20:48 You see a dead human (Vol:10).
> You recognize Ceter Alkma. He was killed by a troll-trained salamander and a mountain troll and others.
> (okay seems like it shows only the name of the most damage and the last hit)
> 
> 21:33 You see a dead human (Vol:10).
> You recognize Se Acalma Homem. He was killed by something evil and Paulo Acorda and others.
> (pvp server, only saw the body)
> 
> 21:34 You see a dead human (Vol:10).
> You recognize Makakorno king. He was killed by Brunin Dogg.
> (pvp server, solo pvp death)
> 
> 21:34 You see a dead human (Vol:10).
> You recognize Ons Vitor. He was killed by Cepexis and others.
> (pvp server, only saw the body)
> 
> 21:35 You see a dead human (Vol:10).
> You recognize Skeletinho Fatality. He was killed by Max Riick.
> (pvp server, solo pvp death)
> 
> 21:40 You see a dead human (Vol:10).
> You recognize Max Riick. He was killed by Akena Jualar and Viieiraw Myth.
> (pvp server, pvp death)
> 
> 21:44 You see a dead human (Vol:10).
> You recognize Valuk Doron. He was killed by something evil and True Gabz and others.
> (pvp server, only saw the body)
> 
> 21:45 You see a dead human (Vol:10).
> You recognize Cauthion. He was killed by something evil.
> (pvp server, died to a field thrown by other player)

the following points had been noted:
- dying to field or item (fire field, claw of the noxius spawn etc): **something evil**
- if there is more than two sources giving you damage: **and others**
- the first name is always the most damage
- the second name is the last hit (if there is a second source hitting you)

so my final suggestions to a small "refactor":

- [ ] add most damage name to corpse (killed by %most damage% and %lasthit%)
- [ ] add (Killed by something evil.) if the killer is script/item/magic field
- [ ] add (and others) if there is more than 2 "damagers" 
- [ ] if the "damagers" are an named "A" and 5 named "B", it will be (Killed by A and others) and not (Killed by A and B and others)
- [ ] in case of a summon, nothing changes, still "most damage and last hit [and others]"

### all suggestions and inputs are welcome!

**Comment by nekiro** [comment]
Didn't understand this part
`
 if the "damagers" are an named "A" and 5 named "B", it will be (Killed by A and others) and not (Killed by A and B and others)
`
can you explain it better?

**Comment by EPuncker** [comment]
> Didn't understand this part
> 
> ```
>  if the "damagers" are an named "A" and 5 named "B", it will be (Killed by A and others) and not (Killed by A and B and others)
> ```
> 
> can you explain it better?

if player is killed by Test Player and by 5 Demons it will show: "**killed by Test Player and others**" and not "**killed by Test Player and a demon and others**", like the first example from the list above


but if the player was killed by Test Player (last hit or most damage) and 1 Demon (last hit or most damage) and 1 Rat (damage), it will be: **killed by Test Player and a Demon and others**


the point is that if the creatures have the same name (five demon) they will be threatened as others even if one of them gave the most damage
