### ISSUE TITLE
Error compiling memory VS2019

### ISSUE THREAD

**Issue by marcosvpb** [otland/forgottenserver#3101]
Error	C2664	'void std::_Normal_allocator_traits<_Alloc>::destroy<_Ty>(_Alloc &,_Ty *)': não é possível converter um argumento 1 de '_Alloc' em '_Alloc &'	theforgottenserver	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\memory	1578	

Someone can help?

**Comment by EPuncker** [comment]
have you followed the guide? https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29

and please edit your issue using the issue template if possible
