### ISSUE TITLE
DOORS ERROR

### ISSUE THREAD

**Issue by luanluciano93** [otland/forgottenserver#3102]
Lua Script Error: [Action Interface]
data/actions/scripts/other/doors.lua onUse
data/actions/scripts/other/doors.lua:89: attempt to get length of local 'doorCreatures' (a nil value)
stack traceback:
[C]: in function '__len'
data/actions/scripts/other/doors.lua:89: in function <data/actions/scripts/other/doors.lua:56>

**Comment by EPuncker** [comment]
is there any steps on how to reproduce this?

@Sundance if you could kindly take a look at this too 🥰

**Comment by ggruts** [comment]
After starting the server and clicking to open any port, it no longer closes and this error appears. The console error clears only when you enter the door sqm and you can close the door again. However, sometimes, when you click the door again, the same error occurs on the console and you are unable to close the door.

**Ps**: When the door starts working again, while you are in the field of vision, it continues to work, however, when you lose sight of it, the error comes back again.

**Comment by gigastar** [comment]
Just change

if doorCreatures > 0 then

to

if doorCreatures and doorCreatures > 0 then

**Comment by EPuncker** [comment]
> Just change
> 
> if #doorCreatures > 0 then
> 
> to
> 
> if doorCreatures and #doorCreatures > 0 then

@luanluciano93 could you confirm if this fix the issue?

**Comment by gigastar** [comment]
I ran into the same problem and that fixed it.

**Comment by ggruts** [comment]
It worked just fine! Thanks.

**Comment by EPuncker** [comment]
okay everyone, please check https://github.com/otland/forgottenserver/pull/3115 and aprove if its the case
