### ISSUE TITLE
Minor issue on push return message

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3103]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. log in a GM character and a regular character
2. try to push the GM with your regular character

### Expected behaviour
"Sorry, not possible."

### Actual behaviour
"You cannot move this **object**"

### ocdc
Does this happens because the server thinks I'm trying to move the ground?

**Comment by nekiro** [comment]
Why would the expected behaviour be "sorry, not possible"?

**Comment by EPuncker** [comment]
> Why would the expected behaviour be "sorry, not possible"?

because a character/creature should not be considered an "object", it should return the same message as trying to push a monster that is not pushable

edit: I went to rl tibia to check what they return "You cannot move this object." 🤷‍♂️
