### ISSUE TITLE
doAreaCombat/doTargetCombat needs optional parameters

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3109]
We need to add:

- blockedByShield (self explanatory)
- blockedByArmor (self explanatory)
- blockedByResistance (take elemental resistance into account)

because right now its giving full damage on physical combat

**Comment by nekiro** [comment]
This is indeed needed, because we can't construct combat object anywhere we want like conditions. Maybe we should make combats work just like conditions via cloning?

**Comment by MillhioreBT** [comment]
What would the function look like with the parameters?
```lua
--doTargetCombat(cid, target, type, min, max, effect[, origin = ORIGIN_SPELL[, blockArmor = false[, blockShield = false[, blockElements = false]]]])
doTargetCombat(cid, target, COMBAT_ICEDAMAGE, -100, -100, CONST_ME_POFF, true, true, true)
```

**Comment by EPuncker** [comment]
> What would the function look like with the parameters?
> 
> ```lua
> --doTargetCombat(cid, target, type, min, max, effect[, origin = ORIGIN_SPELL[, blockArmor = false[, blockShield = false[, blockElements = false]]]])
> doTargetCombat(cid, target, COMBAT_ICEDAMAGE, -100, -100, CONST_ME_POFF, true, true, true)
> ```

yes this is good IMO
