### ISSUE TITLE
Making migration from 0.4 to 1.x easier

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3111]
### Explanation of what you want to do that is currently impossible
My goal with this suggestion/task is to make it easier for users to come to 1.x from 0.4, so I'll be leaving a huge list with 0.4 functions that we do not have, of course we won't implement everything but there are some that can be easily made on Lua (compat.lua) and a few that require small source edits.

### Goal of this issue
Lets discuss and separate the most useful ones and start working on them! Everyone is free (and welcome) to open a pull request with any function for the staff to review and judge if it is okay or not to have it added.

### Reference
[0.4 [luascript.cpp if you need to know what a certain function does](https://github.com/Fir3element/3777/blob/master/src/luascript.cpp)]

### List (in bold the most used):
- [ ] getInstantSpellInfo(cid, name)
- [ ] **doPlayerAddAddons(cid, addon)** https://pastebin.com/ZTwKKj30
- [ ] doTileQueryAdd(uid, pos[, flags[, displayError = true]])
- [ ] doItemRaidUnref(uid)
- [ ] getSearchString(fromPosition, toPosition[, fromIsCreature = false[, toIsCreature = false]]) https://pastebin.com/UYBijngS
- [ ] **getClosestFreeTile**(cid, targetpos[, extended = false[, ignoreHouse = true]])
- [ ] doSendCreatureSquare(cid, color[, player])
- [ ] **doPlayerSetExtraAttackSpeed**(cid, speed)
- [ ] doCleanTile(pos[, forceMapLoaded = false])
- [ ] getMonsterInfo(name)
- [ ] doRemoveConditions(cid[, onlyPersistent])
- [ ] doPlayerSetPzLocked(cid, locked)
- [ ] doPlayerSetGuildId(cid, id)
- [ ] doPlayerAddOutfitId(cid, outfitId, addon)
- [ ] doPlayerRemoveOutfitId(cid, outfitId[, addon = 0])
- [ ] canPlayerWearOutfitId(cid, outfitId[, addon = 0])
- [ ] **doPlayerSetLossPercent**(cid, lossType, newPercent)
- [ ] doPlayerSetLossSkill(cid, doLose)
- [ ] getPlayerLossSkill(cid)
- [ ] **doPlayerSwitchSaving**(cid)
- [ ] isPlayerSaving(cid)
- [ ] getChannelUsers(channelId)
- [ ] **getCreatureByName**(name)
- [ ] **getPlayerByGUID**(guid)
- [ ] **getPlayerByNameWildcard**(name~[, ret = false])
- [ ] getPlayerNameByGUID(guid[, multiworld = false[, displayError = true]])
- [ ] getHouseInfo(houseId[, displayError = true])
- [ ] getHouseFromPos(pos)
- [ ] getGuildMotd(guildId)
- [ ] **createCombatArea**({area}[, {extArea}])
- [ ] doCombatAreaCondition(cid, pos, area, condition, effect)
- [ ] doTargetCombatCondition(cid, target, condition, effect)
- [ ] doCombatAreaDispel(cid, pos, area, type, effect)
- [ ] doTargetCombatDispel(cid, target, type, effect)
- [ ] **getCreatureLastPosition**(cid)
- [ ] getCreaturePathTo(cid, pos, maxSearchDist)
- [ ] getPlayersByAccountId(accId)
- [ ] getAccountIdByName(name)
- [ ] getAccountByName(name)
- [ ] getAccountIdByAccount(accName)
- [ ] getAccountByAccountId(accId)
- [ ] doPlayerSendMailByName(name, item[, town[, actor]])
- [ ] getCreatureGuildEmblem(cid[, target])
- [ ] doCreatureSetGuildEmblem(cid, emblem)
- [ ] getCreaturePartyShield(cid[, target])
- [ ] doCreatureSetPartyShield(cid, shield)
- [ ] getPlayerSkullEnd(cid)
- [ ] doPlayerSetSkullEnd(cid, time, type)
- [x] **getCreatureNoMove(cid)**
- [x] **doCreatureSetNoMove(cid, block)**
- [ ] getPlayerIdleTime(cid)
- [ ] doPlayerSetIdleTime(cid, amount)
- [ ] getPlayerLastLoad(cid)
- [ ] getPlayerTradeState(cid)
- [ ] getPlayerModes(cid)
- [ ] getPlayerRates(cid)
- [ ] doPlayerSetRate(cid, type, value)
- [ ] getPlayerPartner(cid)
- [ ] doPlayerSetPartner(cid, guid)
- [ ] doPlayerFollowCreature(cid, target)
- [ ] doPlayerLeaveParty(cid[, forced = false])
- [ ] getTownHouses(townId)
- [ ] **getVocationInfo**(id)
- [ ] getGroupInfo(id[, premium = false])
- [ ] getTownList()
- [ ] doPlayerSendToChannel(cid, targetId, SpeakClasses, message, channel, ...)
- [ ] getWaypointList()
- [ ] getTalkActionList()
- [ ] getExperienceStageList()
- [ ] **getItemInfo**(itemid)
- [ ] getItemAttribute(uid, key)
- [ ] doItemSetAttribute(uid, key, value)
- [ ] doItemEraseAttribute(uid, key)
- [ ] **getItemParent**(uid)
- [ ] hasItemProperty(uid, prop)
- [ ] hasPlayerClient(cid)
- [ ] isIpBanished(ip[, mask])
- [ ] isPlayerBanished(name/guid, type)
- [ ] isAccountBanished(accountId[, playerId])
- [ ] doAddIpBanishment(...)
- [ ] doAddPlayerBanishment(...)
- [ ] doAddAccountBanishment(...)
- [ ] doAddNotation(...)
- [ ] doAddStatement(...)
- [ ] doRemoveIpBanishment(ip[, mask])
- [ ] doRemovePlayerBanishment(name/guid, type)
- [ ] doRemoveAccountBanishment(accountId[, playerId])
- [ ] doRemoveNotations(accountId[, playerId])
- [ ] doRemoveStatements(name/guid[, channelId])
- [ ] getNotationsCount(accountId[, playerId])
- [ ] getStatementsCount(name/guid[, channelId])
- [ ] **getExperienceStage**(level)
- [ ] getBanData(value[, type[, param]])
- [ ] **doSaveServer**([shallow = false])
- [ ] getBanReason(id)
- [ ] getBanAction(id[, ipBanishment = false])
- [ ] getBanList(type[, value[, param]])
- [ ] getDataDir()
- [ ] getLogsDir()
- [ ] getConfigFile()
- [ ] **isPlayerUsingOtclient**(cid)
- [ ] **doPlayerSendExtendedOpcode**(cid, opcode, buffer)
- [ ] **getConfigValue**(key)
- [ ] getModList()
- [ ] getHighscoreString(skillId)
- [ ] doWaypointAddTemporial(name, pos)
- [ ] doCreatureExecuteTalkAction(cid, text[, ignoreAccess = false[, channelId = CHANNEL_DEFAULT]])
- [ ] doReloadInfo(id[, cid])
- [ ] doCleanHouse(houseId)
- [ ] doCleanMap()
- [ ] doRefreshMap()
- [ ] **doGuildAddEnemy**(guild, enemy, war, type)
- [ ] **doGuildRemoveEnemy**(guild, enemy)
- [ ] doUpdateHouseAuctions()

**Comment by DSpeichert** [comment]
Can you update which ones made it in #3110 ?

**Comment by EPuncker** [comment]
> Can you update which ones made it in #3110 ?

none made it in #3110

the #3110 was mostly for functions that already existed but had a different name

this one is for functions that doesn't exist at all in 1.x

I tried listing them ALL, but of course there are many that are really really useless, I put some in bold that where the ones that I often see in scripts that almost every server/datapack uses and the ones that I see new 1.x users complaining that they don't have

**Comment by EPuncker** [comment]
time goes by and our mind changes... most of these are really really useless and are not even used by anyone at any datapack, most of the main things are already in compat.lua and if they aren't I'll always keep an eye at forum for missing features and possible implementation
