### ISSUE TITLE
Friendly warnings on monsters files

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3112]
First of all: its the duty of the datapack maker to make sure that their files are fine, but it won't hurt to have a few warnings about wrong values, even if the code already cap them.

so my simple request is: throw a console warning if "chance" is higher than 100 on monster xml file just like the staticattack flag does.

- [ ] basically the 5 occurrences of (uniform_random(1, 100)) **in the monster.cpp file**
- [ ] Monsters::deserializeSpell - chance node **on monsters.cpp**
- [ ] mType->info.changeTargetChance **on monsters.cpp**
- [ ] mType->info.yellChance **on monsters.cpp**
- [ ] summonNode.attribute("chance") **on monsters.cpp**

part 2
- [ ] warn user if monster doesn't have a look type set
- [ ] warn user if monster have the same element on both <elements> and <immunities> tags
- [ ] warn user if an <attack> is missing a set chance (unless it is a melee)

part 3
- [ ] warn user if convinceable and/or summonable is set to 1 but there is no manacost set or its set to 0
- [ ] warn user about duplicate element on immunity and element tags
- [ ] warn user if <'flag targetdistance="0" /'>, minimum should be 1

**Comment by MillhioreBT** [comment]
I agree with you, this does nothing wrong, in fact it encourages them to write the values ​​correctly for everything.

**Comment by nkzou** [comment]
Hi there, I haven't worked on this project before but this seemed like a good first issue. I plan to implement most of these validation checks as I familiarize myself with the codebase.
After reading through some of the docs and code, I'm not sure the 5 occurrences of `(uniform_random(1, 100))` in the `monster.cpp` file need warnings, as all of those values are loaded within `Monsters::loadMonster()` and will be checked already. Seems like duplication of the out of bound checks. Thoughts? 
Also, unsure what the part 3 "warn user if , minimum should be 1" means in the issue description. Does this refer to minimum chance value in all the chance fields? @EPuncker any insight would be great, thanks!

**Comment by EPuncker** [comment]
> Also, unsure what the part 3 "warn user if , minimum should be 1" means in the issue description. Does this refer to minimum chance value in all the chance fields?

**warn user if <'flag targetdistance="0" /'>minimum should be 1** sorry I'm still pretty new to this markdown thing
