### ISSUE TITLE
Conditions not being properly deserialized after #2545

### ISSUE THREAD

**Issue by 4mrcn4** [otland/forgottenserver#3114]
After #2545 conditions are not being properly deserialized.
This causes players f.e. to lose their regeneration and they become hungry again after relog/kick.

### Steps to reproduce
1. Log in
2. Eat till full
3. Relog
4. Eat again

### Expected behavior
Conditions persist after relog

### Actual behavior
Conditions are not being deserialized properly.

**Comment by Aeluwin** [comment]
Can confirm this issue in the TFS Master branch as of 07/05/2020.
