### ISSUE TITLE
Question about rope spots (maybe a bug).

### ISSUE THREAD

**Issue by Emilianenko** [otland/forgottenserver#3121]
If you put some usable item ,dead body or container on top of a rope spot , and right click to use this item you receive "you cannot use this object" .Is this the correct behavior?
![bug2](https://user-images.githubusercontent.com/28241119/86538820-bce6bc80-bece-11ea-8921-106235c5975b.png)
![bug33](https://user-images.githubusercontent.com/28241119/86538969-a725c700-becf-11ea-8d62-ff6394e920a0.png)

**Comment by MillhioreBT** [comment]
I am not sure if in tibia rl this is the same, but it seems more a bug than something normal, I also confirm that this happens!

**Comment by Emilianenko** [comment]
Well i'm closing this, cause Evil Puncker and Xikini from otland confirmed that this is how it works on current tibia .

**Comment by MillhioreBT** [comment]
What causes this detail is this:
![image](https://user-images.githubusercontent.com/28090948/86539643-3f21b180-becc-11ea-8928-a3c33f0bc96c.png)
