### ISSUE TITLE
is missing doTargetCombatHealth? LUA Functión??

### ISSUE THREAD

**Issue by Alkurius** [otland/forgottenserver#3141]
is missing doTargetCombatHealth? LUA Functión??

is it possible to add it?

**Comment by EPuncker** [comment]
not missing, its name was changed to doTargetCombat:

https://github.com/otland/forgottenserver/blob/master/data/lib/compat/compat.lua#L314-L317

**Comment by EPuncker** [comment]
https://github.com/otland/forgottenserver/blob/master/data/lib/compat/compat.lua#L314-L317

**Comment by Alkurius** [comment]
tnx
