### ISSUE TITLE
Group flag CanTalkRedChannelAnonymous doesn't work

### ISSUE THREAD

**Issue by kairion** [otland/forgottenserver#3142]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Download TFS stable (1.2) or TFS 1.3 (latest commit), it's up to you;
2. Check if "cantalkredchannelanonymous" on \data\XML\groups.xml is enabled (GM and God come with it enabled by default);
3. Try to talk in a chat channel using the talking syntax `#d` like that: `#d testing talking red anonymous`;
4. See that nothing happens.

### Expected behaviour
The message should be sent in red without GM/God name.

### Actual behaviour
The message will be sent in orange (default behavior for all messages from GM/God groups) with character name and level.

**Comment by SaiyansKing** [comment]
And where have you been in the last decade?
#a, #d and $name$text anonymous talktypes were removed in 8.70 version that was released in 2010... I don't know about otclient but it probably never were there since it lacks many of things that were deprecated.
Keep in mind it is impossible to do it on server-side because client don't send any message that start with "#" to the server.

**Comment by kairion** [comment]
@SaiyansKing 

> And where have you been in the last decade?

I'm truly amazed at how people on the internet are simply incapable of being rational and keep an argument without having to resource to *ad hominem*.

> #a, #d and $name$text anonymous talktypes were removed in 8.70 version that was released in 2010... I don't know about otclient but it probably never were there since it lacks many of things that were deprecated.

Honestly I've never heard of `#a` or `$player$ text` talking options, the only ones I do know are:

- `#b text` - Broadcast `text` to the server
- `#c text` - Send `text` in a chat channel in red
- `@player@ text` - Send `text` to `player` as a private message in red
- `#s text` - Say `text` in local channel/game window
- `#y text` - Yell `text` in local channel/game window
- `#w text` - Whisper `text` in local channel/game window
- `#i player` - invite `player` to your private chat channel
- `#x player` - exclude `player` from your private chat channel
- `*player* text` - Send `text` to `player` as a private message

If you're right and `#d` was removed, then I think it is necessary to remove `PlayerFlag_CanTalkRedChannelAnonymous` from the code and `cantalkredchannelanonymous` from groups.xml, since it is totally useless having both of them.
