### ISSUE TITLE
Magic Wall and Wild Growth missing changes

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3148]
- [x] magic wall should have a random duration between 14 and 20 seconds when shot
- [x] wild growth should have a random duration between 38 and 45 seconds when shot
- [x] ITEM_WILDGROWTH_NOPVP and ITEM_MAGICWALL_NOPVP should be destroyed on stepIn by any player (only on NOPVP world types or NOPVP tiles)

[since 10.01 update](https://tibia.fandom.com/wiki/Updates/10.01)

**Comment by soul4soul** [comment]
I have never heard of the random duration nor is it documented on tibiawiki. Do you have any youtube videos from RL tibia which show the random time? I have no characters that can perform these tests so I can't check myself.

**Comment by EPuncker** [comment]
> I have never heard of the random duration nor is it documented on tibiawiki. Do you have any youtube videos from RL tibia which show the random time? I have no characters that can perform these tests so I can't check myself.

https://www.tibia.com/forum/?action=thread&postid=35059085#post35059085
https://www.tibiaqa.com/11236/are-the-duration-the-magic-wall-and-the-wild-growth-random-there-factors
