### ISSUE TITLE
TFS doesn't read imported map.

### ISSUE THREAD

**Issue by LupusiAlba** [otland/forgottenserver#3166]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.remove TFS original map files from /world directory
2.import files for other map
3.point new map file's name for config.lua to use
4. launch TFS

### Expected behaviour
TFS reads imported map and server starts.

### Actual behaviour
TFS launches, and is fully functional, however old map is being loaded instead of imported one, despite of TFS console telling it had loaded imported map.

### Environment

Debian 16.04

**Comment by EPuncker** [comment]
can you test it on latest tfs? if you are the same guy from this [topic](https://otland.net/threads/cant-get-rl-10-98-map-to-work.272236/), you are using a tfs release from 2016 (way too old) and the issue you are having is not really likely to be tfs fault at all since the engine can't load a map that has been deleted, have you made sure that your server is offline when you do the changes? can you show here your `mapName = ""` entry from config.lua, a screenshot of world folder, and a screenshot of server started console window, thanks

**Comment by LupusiAlba** [comment]
Well hello, yes, that's me.
I'll provide you everything you are asking for in a moment
And how come, I am using old release? I did clone TFS via git clone --recursive https://github.com/otland/forgottenserver.git , shouldn't it download most recent release?

**Comment by EPuncker** [comment]
> Well hello, yes, that's me.
> I'll provide you everything you are asking for in a moment
> And how come, I am using old release? I did clone TFS via git clone --recursive https://github.com/otland/forgottenserver.git , shouldn't it download most recent release?

on the thread you said you were using 1.2 😄 , provide me the things and lets figure it out!

**Comment by LupusiAlba** [comment]
Okay, so...
...guess who's some immense noob over here, exactly as you had deduced, I've been applying all changes on WORKING tfs.

![map1](https://user-images.githubusercontent.com/23293054/90445357-d8ed9880-e0df-11ea-8d66-a1a1da4a7308.png)
![map2](https://user-images.githubusercontent.com/23293054/90445361-da1ec580-e0df-11ea-894f-76aaf3ea3cf1.png)
![map3](https://user-images.githubusercontent.com/23293054/90445364-da1ec580-e0df-11ea-8764-302ea0b6e606.png)
![map4](https://user-images.githubusercontent.com/23293054/90445368-dab75c00-e0df-11ea-9d57-73b973e90e3c.png)
![map5](https://user-images.githubusercontent.com/23293054/90445372-db4ff280-e0df-11ea-9084-4f3ee6d17fc7.png)

I believe this renders my issue to be nonexistent, as map now WORKS. I'd probably find this out as soon as with next server boot, but thank you dearly for the help nonetheless.

**Comment by EPuncker** [comment]
I'm glad you figured it out 😃
