### ISSUE TITLE
Character disappears, if we walk into tile with more than 9-10 people (mostly happens on stairhop)

### ISSUE THREAD

**Issue by djseban** [otland/forgottenserver#3172]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1a. Walk onto one tile with 9 players by using the stairs OR
1b. Summon 9 monsters on one tile by lua code Game.createMonster("MonsterName", {x = , y = , z =}, false, true) 
2. Try walking on said tile with 10th character (GM preferrably, or use the stairs with normal character)

### Expected behaviour
Character should walk normally on the tile

### Actual behaviour
Character disappears in both clients. In OTClient there is visible max speed, desynchronization of position server<->client, while in Official Tibia Client character also disappears, but there are no glitches mentioned latter.

### Environment
GCC 9.8.1 (TFS) in WSL2 (Windows 10)
GCC 4.9.2 (OTC) MinGW (Windows 10)

### Recordings
https://youtu.be/5eKyhBLHduc OTC
https://youtu.be/XhcJO6Uz5X8 Tibia Client

### Few words
Actually I hesitated if it wouldn't be better to post this bug in OTC repo, but it happens also in Official Tibia Client, so I post it here. I tried to fix this bug by increasing max tile items from 10 to 20, but I don't think it is the best way to handle it. When reproducing this bug with actual players, we also get OTC error "no character found" from function getPlayerHelpers and few more. After investigating further, it turns out TFS does not send info about character on tile to client in case creature count on tile exceeds 10. Players on lower position on stack (1-9) are fine, but when a player enters a higher position, he's/she's sometimes forced to do force quit.

**Comment by EPuncker** [comment]
could you test these changes please:
https://github.com/otland/forgottenserver/pull/2673

**Comment by djseban** [comment]
@EPuncker after applying aforementioned fixes I get following behavior:
Suppose n is number of characters on tile.
Tibia Client - When walking on tile with n > 9 the walking character disappears, but appears again when we walk out of tile. 
OTClient - When walking on tile with n > 9 the walking character disappears and does not appear again. We get following errors:

- after login when tile with n > 9 is in sight:
`ERROR: too many things, pos=96 116 7, stackpos=11
at:
    [C++]: ProtocolGame::setTileDescription
ERROR: too many things, pos=96 116 7, stackpos=12
at:
    [C++]: ProtocolGame::setTileDescription
ERROR: too many things, pos=101 116 7, stackpos=11
at:
    [C++]: ProtocolGame::setTileDescription`

- when walking on tile with n characters
`ERROR: no thing at pos:96 117 7, stackpos:2
at:
    [C++]: ProtocolGame::getMappedThing
ERROR: no creature found to move
at:
    [C++]: ProtocolGame::parseCreatureMove
forced player position update
ERROR: no thing at pos:96 118 7, stackpos:2
at:
    [C++]: ProtocolGame::getMappedThing
ERROR: no creature found to move
at:
    [C++]: ProtocolGame::parseCreatureMove
forced player position update`

**Comment by nekiro** [comment]
So what's the status of this. How should it behave?
According to #2673 otc has it broken.

**Comment by Zbizu** [comment]
imo if it works fine on standard client, otland/otclient repo should be updated and brought to same standards tfs currently has

**Comment by nekiro** [comment]
This is client side thing, server side code was already merged for allowing more creatures.
Reference: #2673
