### ISSUE TITLE
Pull request issues #2867

### ISSUE THREAD

**Issue by omarcopires** [otland/forgottenserver#3194]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Try to drag any item
2. Try to look at any item

### Example of one of the errors found
``Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onMoveItem
...cos\forgottenserver\data\scripts/lib\event_callbacks.lua:112: attempt to call a nil value (global 'unpack')
stack traceback:
        [C]: in global 'unpack'
        ...cos\forgottenserver\data\scripts/lib\event_callbacks.lua:112: in function <...cos\forgottenserver\data\scripts/lib\event_callbacks.lua:105>
        (...tail calls...)``

**Comment by EvilHero90** [comment]
I didn't notice this problem because I run my builds in luajit only, however lua52 or higher has it renamed in```table.unpack``` thanks for pointing it out, will prepare a PR.
