### ISSUE TITLE
Error: Allocation failed, server out of memory.

### ISSUE THREAD

**Issue by therrax** [otland/forgottenserver#3203]
Hello.
Just compiled TFS x64, using Windows 10, VS19. I set up a clean server, wanted to test a little, suddenly the engine crashed.

```
Error: Allocation failed, server out of memory.
Decrease the size of your map or compile in 64 bits mode.
```
[Example](https://gyazo.com/31f37067b2dda2de4caf55b3202b828a)

This was triggered by casting spell, but it doesn't happen every time. For some time (like 10m) I only walked on the map and there was no crash. It seems to me that the amount of my interaction (for example spells) causes a crash faster. The error suggests to me that I have insufficient memory, but I have 16GB of RAM
The topic of engines is completely foreign to me and I don't even know where to look for the reason. Could I compile the server incorrect?

Thanks for help 👍 
![Screenshot_2020-11-02 Gyazo](https://user-images.githubusercontent.com/17186894/97911566-c03e6780-1d4b-11eb-9b96-850459821772.png)

**Comment by EvilHero90** [comment]
You compiled the server in x86 which is 32 bits or atleast the version you use is compiled like that.
Follow the steps https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29 for x64 and make sure your visual studio option looks like this:
![options](https://user-images.githubusercontent.com/3682541/97946248-1f22d180-1d8a-11eb-90fc-0080a0a213f7.png) then hit build.
