### ISSUE TITLE
Revscript monster spell bug

### ISSUE THREAD

**Issue by dudantas** [otland/forgottenserver#3233]
When registering a monster in the revscriptsys interface, I will use the barbarian brutetamer as an example, and registering the spell in revscriptsys, gives the following error on the console: 
![image](https://user-images.githubusercontent.com/8551443/100688814-f1698200-3361-11eb-969d-b88061c5959e.png)

Monster spell tag ```{name ="barbarian brutetamer skill reducer", interval = 2000, chance = 15, range = 5, target = false}```

In the XML interface, the error does not occur.

**Comment by MillhioreBT** [comment]
I tried it and no such error happens.

**Comment by EvilHero90** [comment]
As of now you can only give lua monsters spells which are created through the classic interface (spells.xml) this requires a lot of rework of code for now, I'll mark this for 1.6 milestone so it doesn't get lost

**Comment by EvilHero90** [comment]
Actually after testing we noticed that this error came because the monster file was placed inside data/scripts instead of data/monster
so the behaviour is correct and working you just need to place the monster files in the correct folder :D

**Comment by Znote** [comment]
To elaborate for people stumbling upon this through search; 
As far as I know, revscriptsys monster files must be placed inside `data/monsters/lua/` folder (if it doesn't exist - create it), 
This is different from the normal location of revscriptsys files, which is `data/scripts/`

**Comment by EvilHero90** [comment]
`data/monster` or any subfolder from there on, I've already edited the wiki aswell to have it matching @Znote
