### ISSUE TITLE
Outfit number limitation

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3236]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
(to reproduce this you will need to have more outfits than the default value, I'll teach with downgraded cip files)

1. transform your original/latest/updated tibia files into spr/dat using this small tutorial [here](https://otland.net/threads/pure-latest-items-otb.268296/) and replace the original ones from your 10.98 client
2. use [this](https://pastebin.com/YMAi0qc6) outfits.xml file
3. start your server, login with your GOD male character
4. open outfit windows and start browsing from citizen outfit onward

### Expected behaviour
Show all available outfits

### Actual behaviour
It will only show up to 99 outfits, anything past that will not be available

### Environment
It happens on both cip client and OTC

**Comment by Zbizu** [comment]
https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L2695
