### ISSUE TITLE
Monsters not being idle when they should

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3246]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Open two clients
2. GM character floor 8 (monsters idle)
3. Then login normal character on the floor above

### Expected behaviour
Monsters on floor 8 should not stay active (non-idle) while there are players on the above floor
(higher floors should remain as they are, current issue is only between floor 7 and 8)

### Actual behaviour
Monsters become active when a player out of their sight is detected

### Disclaimer
Yes, I know that this is not true in other cases, but specially on floor 8 (-1) monsters should not have their idle status changed because of what happens on ground floor (0), I've discussed it with other devs and even tested it on RL tibia. Floor 7 (ground) is special and has no interaction with lower floors.

**Comment by MillhioreBT** [comment]
Confirmed, only happens on 6th and 7th floor, disappearance / appearance is not reported and even does not miss the target
