### ISSUE TITLE
Server closes on non-existing map name

### ISSUE THREAD

**Issue by slawkens** [otland/forgottenserver#3254]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Change default mapName in config.lua to something that doesn't exist

### Expected behaviour
Console should give at least some info what have gone wrong. For example: couldn't find map file.

### Actual behaviour
The server closes unexpectedly without giving any info. Screenshot included:
![image](https://user-images.githubusercontent.com/16687302/103317147-ee2de880-4a2a-11eb-96f0-929ddcf5a5f1.png)

**Comment by nekiro** [comment]
Is it crashing?
https://github.com/otland/forgottenserver/blob/master/src/otserv.cpp#L291

**Comment by SaiyansKing** [comment]
Yes, it is crashing:
[https://github.com/otland/forgottenserver/blob/master/src/fileloader.cpp#L35](https://github.com/otland/forgottenserver/blob/master/src/fileloader.cpp#L35)
throws here but
[https://github.com/otland/forgottenserver/blob/master/src/iomap.cpp#L72](https://github.com/otland/forgottenserver/blob/master/src/iomap.cpp#L72)
doesn't captch any throwed exception.

**Comment by slawkens** [comment]
enhancement? Its a bug! :sweat_smile:

**Comment by nekiro** [comment]
> enhancement? Its a bug! 😅

honestly, this does not affect anything so I would say it's an enhancement, but I guess it's matter of opinion.
