### ISSUE TITLE
Increased loot after /reload all command

### ISSUE THREAD

**Issue by Unknown-Soldier** [otland/forgottenserver#3257]
So the problem with increased loot from monsters occurs after reloading scripts, the more reloads, the more loot.
More details here:

https://otland.net/threads/increased-loot-with-rate-at-1.274093/

Solution seems to be like this:
In Talkactions => **reload.lua** change `if param:lower() == "scripts" then` to `if param:lower() == "scripts" or param:lower() == "all" then`

Cheers!

**Comment by Zbizu** [comment]
Very likely related to revscriptsys / monstertype
If you're adding loot through lua, make sure you do it only once because reload doesn't remove any variables, but actually overwrite them.

Example:

if not SOMEVARIABLE then
-- load something
SOMEVARIABLE = true
end

**Comment by EvilHero90** [comment]
Solved in #3258
