### ISSUE TITLE
Keys should not display a number if they doesn't have an action ID

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3261]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. /i 2088/silver key

### Expected behaviour
00:31 You see a silver key.

### Actual behaviour
00:31 You see a silver key (Key:0000).

Keys should not display a number if they doesn't have an action ID set

**Comment by MillhioreBT** [comment]
Confirmed!
