### ISSUE TITLE
'lua.hpp': no such file or directory

### ISSUE THREAD

**Issue by lucasgrizante** [otland/forgottenserver#3286]
Hi all,
I've followed everything from this tutorial:
https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-(vcpkg)

and when compiling, all files which include lua can't be compiled.
I'm having the same issue as #3009 and tried the solution posted there, but it's still not working:

> C:\vcpkg (master -> origin)
> λ vcpkg remove lua:x64-windows lua:x86-windows
> The following packages are not installed, so not removed:
>     lua:x64-windows
>     lua:x86-windows
> Package lua:x64-windows is not installed
> Package lua:x86-windows is not installed
> 
> C:\vcpkg (master -> origin)
> λ vcpkg install luajit:x64-windows
> Computing installation plan...
> The following packages are already installed:
>     luajit[core]:x64-windows -> 2.0.5-3
> Package luajit:x64-windows is already installed
> 
> Total elapsed time: 116 us
> 
> 
> C:\vcpkg (master -> origin)
> λ vcpkg remove lua:x64-windows
> The following packages are not installed, so not removed:
>     lua:x64-windows
> Package lua:x64-windows is not installed
> 
> C:\vcpkg (master -> origin)
> λ vcpkg integrate install
> Applied user-wide integration for this vcpkg root.
> 
> All MSBuild C++ projects can now #include any installed libraries.
> Linking will be handled automatically.
> Installing new libraries will make them instantly available.
> 
> CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
> 
> C:\vcpkg (master -> origin)
> λ

What should I do?
Note: my computer is a recently bought one, formatted with Windows 10 Pro edition and it's the first time I'm using vcpkg to compile.

**Comment by EPuncker** [comment]
does your tfs have these changes applied?
https://github.com/otland/forgottenserver/pull/3029/files

or perhaps you should try reverting the changes from https://github.com/otland/forgottenserver/pull/2973/files#diff-28ccc34104faf109b7b97582612d93779d30d1e8e57318db13ffd88d651b8c39 same with luascript.h file

**Comment by lucasgrizante** [comment]
Changing 

`#include <lua.hpp>`

to 

```
#if __has_include("luajit/lua.hpp")
#include <luajit/lua.hpp>
#else
#include <lua.hpp>
#endif
```

in both luascript.h and configmanager.cpp fixes this issue, at least for windows using vcpkg.
Shall I commit it?

**Comment by lucasgrizante** [comment]
> does your tfs have these changes applied?
> https://github.com/otland/forgottenserver/pull/3029/files
> 
> or perhaps you should try reverting the changes from https://github.com/otland/forgottenserver/pull/2973/files#diff-28ccc34104faf109b7b97582612d93779d30d1e8e57318db13ffd88d651b8c39 same with luascript.h file

Actually I cloned master branch, so yes, I have both commits in my local repo.

Wouldn't reverting https://github.com/otland/forgottenserver/pull/2973/files#diff-28ccc34104faf109b7b97582612d93779d30d1e8e57318db13ffd88d651b8c39 break anything else? that PR changed few other things also.

**Comment by EPuncker** [comment]
nope, you shouldn't revert everything, just the changes I mentioned would do no harm, I think your case is an isolated issue, if more people appear with this issue then we will have to take a deeper look into it, feel free to close this issue if you feel like doing so

**Comment by MohamedRefaat** [comment]
> nope, you shouldn't revert everything, just the changes I mentioned would do no harm, I think your case is an isolated issue, if more people appear with this issue then we will have to take a deeper look into it, feel free to close this issue if you feel like doing so

Unfortunately i still get this error, idk how i fixed it without editing luascript.h and configmanager.cpp

**Comment by DSpeichert** [comment]
`__has_include` is C++20, I wonder how is the support across latest versions of various distros.
