### ISSUE TITLE
It's not possible to register multiple times the same globalEvent

### ISSUE THREAD

**Issue by lucasgrizante** [otland/forgottenserver#3294]
I'm trying to use globalevent on RevScripts, and it's not possible to use more than 1 time.

if I do like this:

```
local globalevent = GlobalEvent("example")

function globalevent.onTime(interval)
	broadcastMessage("Good morning!", MESSAGE_STATUS_DEFAULT)
        print("hello world")
	return true
end

globalevent:time("08:00")
globalevent:time("08:01")
globalevent:time("08:02")
globalevent:register()
```

the event will only happen at "08:02" (the last one set).

my suggestion is to add a way to use the same event multiple times (maybe using commas, I don't know..)

Note that using intervals instead of times is not valid here because the server owner may need that this event happening in not a regular way (not like every 3 hours, but on specific times)

**Comment by nekiro** [comment]
You have to create new globalevent class for every single globalevent, setting time like that is just changing the time set for this globalevent. I doubt this will change.

**Comment by Azakelis** [comment]
Instead of that I'd suggest:

```
function TestGlobalEvent(interval)
    print("hello world")
    return true
end

GLOBAL_EVENTS_SCHEMAS = {
    {name = "example", onTime = TestGlobalEvent, time = "08:00"},
    {name = "example2", onTime = TestGlobalEvent, time = "08:01"},
    {name = "example3", onTime = TestGlobalEvent, time = "08:02"}
}

for i = 1, #GLOBAL_EVENTS_SCHEMAS, 1 do
    local schema = GLOBAL_EVENTS_SCHEMAS[i]
    local globalevent = GlobalEvent(schema.name)
    globalevent.onTime = schema.onTime
    globalevent:time(schema.time)
    globalevent:register()
end
```

**Comment by MillhioreBT** [comment]
I have tested global events constructed in the following way and they work correctly, the same goes for events of type `onTime`
I see no reason to add multiple intervals for a single event, since that is equivalent to implementing more lines of code for something that can already be done perfectly in lua, I think that such events that need a configuration with this will be very rare if not rather useless, so why add a whole new mechanism for the intervals to satisfy one or two scripts only xd?
```lua
local function globalEventCallback(interval)
	print(interval)
	return true
end

local glovalEvent1 = GlobalEvent("Test1")
glovalEvent1.onThink = globalEventCallback
glovalEvent1:interval(3000)
glovalEvent1:register()

local glovalEvent2 = GlobalEvent("Test2")
glovalEvent2.onThink = globalEventCallback
glovalEvent2:interval(5000)
glovalEvent2:register()
```

**Comment by lucasgrizante** [comment]
I've closed this issue. I agree about what you said. It can be configured in LUA creating another globalevent with the same callback function, so it's ok.

Thank you all!
