### ISSUE TITLE
Game::getCreatureByName slow for monsters

### ISSUE THREAD

**Issue by infister** [otland/forgottenserver#3302]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. create Lua script with Creature(“Monster Name”) on server with many monsters on the map
2.
3.

### Actual behaviour

This look up takes very long time. 

### Reproduction environment

I suggest doing mappedMonsterNames to optimize the code.

**Comment by nekiro** [comment]
I didn't even know you can do it by name, its pointless anyway, why would you try to obtain creature by name? You have Player() and Monster() respectively. You don't even have any guarantee on what monster it will be. I would even vote to just delete this as it's not needed at all.

**Comment by infister** [comment]
Then remove it or fix it. 

https://github.com/otland/forgottenserver/blob/master/data/talkactions/scripts/teleport_to_creature.lua

Use cases
1. /goto monster
2. Checking in a script if monster is on the map.

**Comment by soul4soul** [comment]
> 
> 
> Then remove it or fix it.
> 
> https://github.com/otland/forgottenserver/blob/master/data/talkactions/scripts/teleport_to_creature.lua
> 
> Use cases
> 
>     1. /goto monster
> 
>     2. Checking in a script if monster is on the map.

+1 for /goto monstername. I remember using it in a few scripts for single spawn monsters back in the day. Maybe those script could of been made differently but I was happy with what I was doing at the time.
