### ISSUE TITLE
Item IDs above 32767 - Bugs

### ISSUE THREAD

**Issue by Nug0** [otland/forgottenserver#3315]
If your like me and have a very customised server if you go above 32767 item ID you get some crazy errors. Its been an issue for years.

on TFS 1.2 when you log out and back in with an item above 32767 it will just convert the item to 32767 and freeze it in the slot you cant get rid of it, bugging the char. (you can SQL queery it off the player).

In TFS 1.3 (current master branch) as of 3 days ago it creates this database error and just deletes the item from exisitence when you log in and out.

https://gyazo.com/b2616187593b69e6c7550498043a54a2

the fix to this problem on both versions of TFS is

https://otland.net/threads/items-transform-into-another-item-after-relog.263781/#post-2549960

This SQL queery below fixes the issue permanently

ALTER TABLE `player_depotitems` CHANGE `itemtype` `itemtype` smallint(6) unsigned NOT NULL;
ALTER TABLE `player_inboxitems` CHANGE `itemtype` `itemtype` smallint(6) unsigned NOT NULL;
ALTER TABLE `player_items` CHANGE `itemtype` `itemtype` smallint(6) unsigned NOT NULL;

the above SQL queery needs to be built into the default sheme that comes with TFS.

"It's the way the database stores numbers it overflows and goes back to 0. The trade off for being able to store bigger numbers is the number saved takes up more room in the database even if it's a smaller number so the database ends up being bigger on disk"

**Comment by EPuncker** [comment]
thank you, this has been fixed here:
https://github.com/otland/forgottenserver/commit/e146147bfb3ed9cf9da702a342f95da82b4445c3
