### ISSUE TITLE
c++: fatal error: Morto signal terminated program lto1 compilation terminated.

### ISSUE THREAD

**Issue by MoraesGlider** [otland/forgottenserver#3317]
While compiling I faced this issue:

[ 53%] Linking CXX executable tfs
c++: fatal error: Morto signal terminated program lto1
compilation terminated.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: erro: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/tfs.dir/build.make:1326: tfs] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/tfs.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

How can I solve that?

**Comment by MillhioreBT** [comment]
I think this is out of place, in addition you have not provided information about your system

**Comment by EPuncker** [comment]
yeah, please follow the issue template

**Comment by EPuncker** [comment]
since OP didn't returned the questions, I'll be closing this issue as there is currently no error on compilation that we are aware of, if you have any more question or need help, please visit our support board:
https://otland.net/forums/support.16/
