### ISSUE TITLE
Change password sha1 to bcrypt

### ISSUE THREAD

**Issue by brunotonin** [otland/forgottenserver#3353]
I believe that to improve the security of otserver players' information, it would be ideal to change the way the password is saved.
SHA-1 is very practical but at the same time very insecure, there are already many databases that have broken hashes or video cards that generate millions of hashes in a short time.
So I believe that the ideal would be to save the password in the database using the bcrypt algorithm.

**Comment by brunotonin** [comment]
It is worth mentioning that today there is a "market" where databases are sold to try to hack accounts in global tibia, as many players are not aware of this risk.

**Comment by EPuncker** [comment]
there are plans for it already!

Closing as duplicate of #2148
