### ISSUE TITLE
Incorrect house size calculation

### ISSUE THREAD

**Issue by BahamutxD** [otland/forgottenserver#3379]
The issue:

Number of house tiles in house.xml is incorrect as TFS is only counting tiles where a player can stand when generating the house.xml file (on map save) - for example TFS is excluding the following: beds, doors (including normal doors inside the house and the entry door as long as they are mapped closed), tables, counters...

See this exagerated example.

This is how it looks in house.xml - size=0, yet you can fully move around the house if you just open the doors.

`<house name="Unnamed House #2" houseid="2" entryx="1021" entryy="1028" entryz="7" rent="0" townid="1" size="0" />`

![image](https://user-images.githubusercontent.com/6182531/112038782-90013500-8b43-11eb-981d-dfb73688af2f.png)

This is the same house but filled with blocking items and leaving an empty door in the middle to prove my point. The size is 1 now.

`<house name="Unnamed House #2" houseid="2" entryx="1021" entryy="1028" entryz="7" rent="0" townid="1" size="1" />`

![image](https://user-images.githubusercontent.com/6182531/112039425-4f55eb80-8b44-11eb-9fcf-6577a8b1bf0d.png)

This is how it looks in RL - Harbour Place 2 (Shop) 12SQM per room + 2 doors. Beds and counters are included.

![image](https://user-images.githubusercontent.com/6182531/112040663-c63fb400-8b45-11eb-9c01-459886a69deb.png)

![image](https://user-images.githubusercontent.com/6182531/112040589-b0ca8a00-8b45-11eb-9240-034221caf447.png)

But in TFS 

`	<house name="Harbour Place 2 (Shop)" houseid="1940" entryx="32336" entryy="32210" entryz="7" rent="1300" townid="2" size="19" />`

The dark green tiles - 10 top room (2 missing from bed) and 9 in bottom room (3 missing from counter) and the 2 doors are not counted.

![image](https://user-images.githubusercontent.com/6182531/112040805-eec7ae00-8b45-11eb-8669-aa46ebe39cbb.png)

**Comment by MillhioreBT** [comment]
Interesting but this seems like a problem that must be published in the official map editor repository

**Comment by BahamutxD** [comment]
> Interesting but this seems like a problem that must be published in the official map editor repository

Sometimes the smallest details are the most important. Sorry and thanks for pointing that out. Will do that.
