### ISSUE TITLE
onDeEquip return value no effect

### ISSUE THREAD

**Issue by robpot95** [otland/forgottenserver#3380]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
```
local feetSlot = MoveEvent()

function feetSlot.onDeEquip(player, item, slot, isCheck)
	return false
end

feetSlot:type("deEquip")
feetSlot:slot("feet")
feetSlot:id(2643)
feetSlot:register()
```

### Expected behaviour
I can still move the boots from the slot

### Actual behaviour
They should not be moveable since they script `return false`. I've used this before but after i updated to TFS 1.3, it seems not working.

**Comment by MillhioreBT** [comment]
first this `feetSlot:type("deEquip")` should not be declared, this is done automatically
secondly, this behavior is correct, if you want an item cannot be removed/move from inventory, you can use the `onItemMove` method instead and it is more perfect for this case as it does not cause problems with attributes and things related to item attributes

If what you want is to be modular, TFS has the EventCallback system for your convenience

**Comment by robpot95** [comment]
I see, but it seems bit weird that return value has not effect at all. Why i set eventType to deEquip i saw it be done in the example file. Is there even any documentation about the new revscriptsystem? Can you tell me more about eventcallback? Does it override the default eventcallback. For example if i have a default_onMoveItem. Does it override it?

**Comment by MillhioreBT** [comment]
> I see, but it seems bit weird that return value has not effect at all. Why i set eventType to deEquip i saw it be done in the example file. Is there even any documentation about the new revscriptsystem? Can you tell me more about eventcallback? Does it override the default eventcallback. For example if i have a default_onMoveItem. Does it override it?

Does not cancel it

here are some pretty clear examples:
https://github.com/otland/forgottenserver/pull/3329

looks a lot like creaturescripts but you can set the order of execution
