### ISSUE TITLE
Client crash on remove creature

### ISSUE THREAD

**Issue by forgee** [otland/forgottenserver#3381]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Log in 2 characters in the same location.
2. Let a monster target character A while character B is within view range.
3. Character B walks off screen.
4. Character A kills the monster.
5. Client of character B crashes.

Video demonstration: https://youtu.be/IeefUzWqG4Y
OTLand discussion: https://otland.net/threads/random-server-and-client-crashes.274828
### Expected behaviour

Client should not crash, server should not send RemoveTileThing when the creature is not in view range.

### Actual behaviour

The server sends RemoveTileThing when the creature is outside view range, causing the client to crash.

### Environment

Not environment dependent.
Tested on 29d484ba0554c6d985244bedda9313d9bb8b9c68

### Possible solution
Add ```
if (!canSee(pos)) {
    return;
}```
In [ProtocolGame::sendRemoveTileCreature](https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L2440)

**Comment by nekiro** [comment]
This is what I call properly submitted issue, thanks man. I'll try to push fix for this soon.
