### ISSUE TITLE
attackSpeed via items.lua feature.

### ISSUE THREAD

**Issue by DoktorHolzbein** [otland/forgottenserver#3395]
https://otland.net/threads/c-item-attack-speed-attr-key-not-recognized.262272/

Would be nice to have this on TFS.

Code is old and need a edit.

**Comment by nekiro** [comment]
Please explain your idea and how you would like it to be implemented, so maybe someone in future gonna know how to implement it.

**Comment by DoktorHolzbein** [comment]
There's nothing big at all to explain

it should be a weapon attack speed attribute which allows you to change your attack speed of all weapons via items.xml
example:

<attribute key="attackspeed" value="1000" />     <-- This means the weapon attack speed would be 1sec.

if a weapon is not regirsted with attribute attackspeed then the weapon will have the basic attack speed from vocation.xml

**Comment by Zbizu** [comment]
@nekiro it seems to be a feature request for weapons. He wants attackspeed attribute which would make the weapon attack faster than usual 2 seconds interval.

**Comment by Znote** [comment]
`attackspeed="2000"` is currently configured for vocations in data/XML/vocations.xml
You can use player:getVocation():getAttackSpeed() to get the current attack speed of your player. 

But I don't think you can change this dynamically, I dont think we have any Vocation::SetAttackSpeed(), items.xml (or weapons.xml) dont have an interface to let a player adjust this value. I'm not sure if we can do this with revscriptsys either?

I guess this would be cool to have, etc implement fist fighting weapons that have high attack speed, spells that temporarily boost your attack speed.

**Comment by DoktorHolzbein** [comment]
Would be cool to have such a system
so we could create unique weapons with faster atk speed than other weapon
