### ISSUE TITLE
"defense name="outfit"" only works after you do "/reload monsters"

### ISSUE THREAD

**Issue by andremiles1** [otland/forgottenserver#3397]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
**Any** monster which use spell outfit change on itself (under the _defenses_ tag) only start doing so after getting reloaded.
An excellent example to observe this bug is with the monster "Dark Apprentice", which transforms itself on a frog defensively, and attacks by transforming others in a broom.

1. Create /m dark apprentice, or go to any map respawn of this monster.
2. Do a utevo res "dark apprentice and start attacking the real one. They never defensively transform themselves on a frog, but transforms others/itself on a broom when attacking. So the issue is only on the _defenses_ tag.
3. After a while, just do a /reload monsters
4. They will start transforming themselves on a frog after the reload.

### Expected behaviour
Monsters should change its outfit passively/defensively when specified to do so.

### Actual behaviour
They do, but only after a forced reload on the monsters files.

**Comment by EPuncker** [comment]
yeah, I've just tested and this is indeed a bug:
```<defenses armor="15" defense="15">
		<defense name="healing" interval="2000" chance="15" min="30" max="40">
			<attribute key="areaEffect" value="greenshimmer" />
		</defense>
		<defense name="outfit" interval="2000" chance="5" target="1" monster="green frog" duration="3000" />
	</defenses>```

the healing works fine while the outfit is only triggered after the /reload monsters

**Comment by MillhioreBT** [comment]
The probability of them transforming is ridiculously low, even this monster may never transform perfectly within 5 minutes or more
If you increase the probability to 100% you will notice that it is not necessary to reload, nor to place the monsters in specific situations

they transform perfectly when they are thinking
I will continue testing and investigating a little more

**Comment by MillhioreBT** [comment]
Update: problem only occurs when `forceMonsterTypesOnLoad` is true
do your tests and confirm this

**Comment by EPuncker** [comment]
> Update: problem only occurs when `forceMonsterTypesOnLoad` is true
> do your tests and confirm this

nice catch, exactly, the problem only occurs when `forceMonsterTypesOnLoad` is true

**Comment by EPuncker** [comment]
yo @andremiles1 , can you try https://github.com/otland/forgottenserver/pull/3404 and tell us if it fix the issue? thanks
