### ISSUE TITLE
Server freeze on reload items

### ISSUE THREAD

**Issue by paola92** [otland/forgottenserver#3407]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. start tfs and login as GOD
2. do /reload items    5x very quick
3. relog character and you can move just 1 sqm and server freeze. after this also other players have the same issue not just GOD

### Expected behaviour
should work normally

### Actual behaviour
After reload items few times very quick and relog any character on server you cannot move more than 1SQM. After some time player receive infromation that connection lost and can connect again but just move 1 SQM. after restart of TFS all back to normall. 

### Environment
TFS 1.3, Debian 10

### Reproduction environment
TFS 1.3, Debian 10

**Comment by EPuncker** [comment]
sorry, couldn't reproduce this on windows

I'm able to login, spam /reload items as many times as I want and still be able to login back and play normally

**Comment by EPuncker** [comment]
@idontreallywolf confirmed it on OSX

**Comment by MillhioreBT** [comment]
> sorry, couldn't reproduce this on windows
> 
> I'm able to login, spam /reload items as many times as I want and still be able to login back and play normally
> 
> however I'll leave this issue open until someone test it on other OS

I also tried it in windows and nothing happens

> @idontreallywolf confirmed it on OSX

Although it would be good to have more specifications of the performance of the computer you are using, because I suppose there are better and worse OSX

**Comment by EPuncker** [comment]
> At first glance it seems like a pretty strange problem, just to reload items? It would be good more research about it, try more scenarios

![Skarmavbild_2021-04-09_kl _01 48 05](https://user-images.githubusercontent.com/4684880/114119404-f666b100-98c0-11eb-9422-3265c76878fb.png)

it seems like the scheduler spam is conflicting with the walking scheduler (and what not)

a simple fix would be adding a 5 seconds delay (or so) to the /reload command

**Comment by joelslamospersson** [comment]
Will just leave a comment on this then concidering it has to do with the same issue.
I am using the reload command on the server, while I do it after around 4-5 times it loses connection and you'll not be able to sign in again. This is not used with spam, just reloading things in general

**Comment by MillhioreBT** [comment]
> Will just leave a comment on this then concidering it has to do with the same issue.
> I am using the reload command on the server, while I do it after around 4-5 times it loses connection and you'll not be able to sign in again. This is not used with spam, just reloading things in general

It would be good if you leave a little more information, such as: the operating system in which you are running the server

**Comment by MillhioreBT** [comment]
Confirmed, but it seems to be an `OTC`/`OTCv8` problem, it does not happen to me with the CIP Client
I guess all OTC have this problem

According to my tests, it only happens when the recharge takes a long time and you cause the OTC to go into constant lag
the only way I got the problem to occur was by doing `/reload all` and making my computer slow with many programs to simulate late reload delay, more or less with `0.80s` is enough to get the result, do at least `10~20` reloads fast so that the otc detects a very high ping

**Comment by EPuncker** [comment]
hi @paola92 and @joelslamospersson can you guys check and confirm if https://github.com/otland/forgottenserver/commit/b920f35002f900421486de1ece1f13813804fb13 fixes this issue?
