### ISSUE TITLE
missing bosses

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3410]
so i went through the monster files and noticed some missing bosses, keep in mind i did not check past v8.2 so there might be more than these.
- https://tibia.fandom.com/wiki/Gravelord_Oshuran
- https://tibia.fandom.com/wiki/High_Templar_Cobrass
- https://tibia.fandom.com/wiki/Rukor_Zad
- https://tibia.fandom.com/wiki/Smuggler_Baron_Silvertoe
- https://tibia.fandom.com/wiki/Teleskor
- https://tibia.fandom.com/wiki/The_Big_Bad_One
- https://tibia.fandom.com/wiki/The_Old_Whopper
- https://tibia.fandom.com/wiki/The_Weakened_Count
- https://tibia.fandom.com/wiki/Zarabustor

**Comment by nekiro** [comment]
I'm still not sure why we even bother to add these monsters, we are not cip tibia map project, our map is custom, so why are we keeping monsters tibia like?

**Comment by ramon-bernardo** [comment]
I would like to help with that too, but find boss by boss on the site is slow.
Someone who understands web development could create a request for the [wiki](https://tibia.fandom.com/wiki/Bosses), returning the name of the boss and its version. 

Ex (.txt):
A Shielded Astral Glyph - 11.02
Abyssador - 9.6
