### ISSUE TITLE
Hardcoded viewport in protocolgame.cpp

### ISSUE THREAD

**Issue by kukure09** [otland/forgottenserver#3431]
Came across the tutorial to increase the number of tiles sent to the client, from 6 years ago. Apparently, to this day, the viewport values are still harcoded in the protocolgame.cpp, is there a reason for this?

**Comment by EPuncker** [comment]
> is there a reason for this?

there is no specific reason other than nobody else tried/cared to change it, except by this:

https://github.com/otland/forgottenserver/pull/3054

**Comment by nekiro** [comment]
It could be constexpr

**Comment by kukure09** [comment]
well, if he's already working on it, lets wait. I'm fixing every magic number I can find while studying the system. I have a patch for it, if nothing happens in the near future. Thanks for the answer.

**Comment by EPuncker** [comment]
> well, if he's already working on it, lets wait. I'm fixing every magic number I can find while studying the system. I have a patch for it, if nothing happens in the near future. Thanks for the answer.

I doubt he is going to open a PR, but you are welcome to do one instead 😄 it will be very appreciated
