### ISSUE TITLE
Problem with the connection after login.

### ISSUE THREAD

**Issue by ramosluis16** [otland/forgottenserver#3435]
Sometimes this happened on my project and nobody can move after login, im using latest OTClient and this current TFS 1.3

`ERROR: invalid encrypted network message 24569
at:
    [C++]: ?xteaDecrypt@Protocol@@AAE_NABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
ERROR: failed to decrypt message
at:
    [C++]: ?internalRecvData@Protocol@@AAEXPAEI@Z`

![asddaaaaad](https://user-images.githubusercontent.com/69329454/116588477-9d9b9e80-a8e9-11eb-9ef9-b021e9ba4885.png)

**Comment by EPuncker** [comment]
do you have these changes applied?
https://github.com/otland/forgottenserver/commit/b920f35002f900421486de1ece1f13813804fb13

**Comment by ramosluis16** [comment]
@EPuncker Oh!! I forgot implement this one, it could be the problem? thanks alot ill try!

**Comment by EPuncker** [comment]
> @EPuncker Oh!! I forgot implement this one, it could be the problem? thanks alot ill try!

can you confirm if it fixed the problem and if so, close this issue, thanks

**Comment by ramosluis16** [comment]
@EPuncker atm, all is working fine, not happens again, thanks alot.
