### ISSUE TITLE
Problem with browse field + construction kits, getId() method is nil value

### ISSUE THREAD

**Issue by ramon-bernardo** [otland/forgottenserver#3439]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Go to a house.
2. Create a construction kit.
3. Open browse field from your step.
4. Move parcel to your step.
5. Move parcel for other tile, later move back.
6. Use parcel.

### Actual behaviour
- `item:getParent():getId()`

![error](https://user-images.githubusercontent.com/53269692/116883395-f0cc6480-abfb-11eb-980d-b98daa0e0d24.gif)

![image](https://user-images.githubusercontent.com/53269692/116882769-33da0800-abfb-11eb-8be8-814ab09de639.png)

**Comment by Kamenuvol** [comment]
It is setting tile back as owner so it has no id.
