### ISSUE TITLE
more missing monsters

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3453]
### 8.4 (Anti-Botter monsters wont be done because reasons)
- [x] https://tibia.fandom.com/wiki/Ghostly_Apparition
- [x] https://tibia.fandom.com/wiki/Servant_Golem
- [x] https://tibia.fandom.com/wiki/Arthei
- [ ] https://tibia.fandom.com/wiki/Boreth
- [ ] https://tibia.fandom.com/wiki/Lersatio
- [ ] https://tibia.fandom.com/wiki/Marziel
- [ ] https://tibia.fandom.com/wiki/Shadow_of_Boreth
- [ ] https://tibia.fandom.com/wiki/Shadow_of_Lersatio
- [ ] https://tibia.fandom.com/wiki/Shadow_of_Marziel

###  8.5
- [ ] https://tibia.fandom.com/wiki/Acolyte_of_Darkness
- [ ] https://tibia.fandom.com/wiki/Bane_of_Light
- [ ] https://tibia.fandom.com/wiki/Bride_of_Night
- [ ] https://tibia.fandom.com/wiki/Doomsday_Cultist
- [ ] https://tibia.fandom.com/wiki/Duskbringer
- [ ] https://tibia.fandom.com/wiki/Eclipse_Knight
- [ ] https://tibia.fandom.com/wiki/Enraged_Bookworm
- [ ] https://tibia.fandom.com/wiki/Gloombringer
- [ ] https://tibia.fandom.com/wiki/Harbinger_of_Darkness
- [ ] https://tibia.fandom.com/wiki/Midnight_Warrior
- [ ] https://tibia.fandom.com/wiki/Nightslayer
- [ ] https://tibia.fandom.com/wiki/Spawn_of_Despair
- [ ] https://tibia.fandom.com/wiki/Spirit_of_Light
- [ ] https://tibia.fandom.com/wiki/Target_Dummy
- [ ] https://tibia.fandom.com/wiki/Weak_Eclipse_Knight
- [ ] https://tibia.fandom.com/wiki/Weak_Gloombringer
- [ ] https://tibia.fandom.com/wiki/Weak_Harbinger_of_Darkness
- [ ] https://tibia.fandom.com/wiki/Weak_Spawn_of_Despair
- [x] https://tibia.fandom.com/wiki/Doctor_Perhaps
- [x] https://tibia.fandom.com/wiki/Fahim_the_Wise
- [x] https://tibia.fandom.com/wiki/Merikh_the_Slaughterer
- [ ] https://tibia.fandom.com/wiki/Samael

### 8.54
- [x] https://tibia.fandom.com/wiki/Enraged_Squirrel
- [ ] https://tibia.fandom.com/wiki/Thieving_Squirrel
- [ ] https://tibia.fandom.com/wiki/Cublarc_the_Plunderer
- [ ] https://tibia.fandom.com/wiki/Dreadmaw
- [ ] https://tibia.fandom.com/wiki/Flamecaller_Zazrak
- [ ] https://tibia.fandom.com/wiki/Fleabringer
- [x] https://tibia.fandom.com/wiki/Lizard_Gate_Guardian
- [x] https://tibia.fandom.com/wiki/Mooh%27Tah_Master
- [x] https://tibia.fandom.com/wiki/Shard_of_Corruption
- [ ] https://tibia.fandom.com/wiki/The_Voice_of_Ruin

### 8.6
- [ ] https://tibia.fandom.com/wiki/Hatebreeder
- [ ] https://tibia.fandom.com/wiki/Mutated_Zalamon
- [ ] https://tibia.fandom.com/wiki/The_Keeper

### 8.61
- [ ] https://tibia.fandom.com/wiki/Spawn_of_Devovorga
- [ ] https://tibia.fandom.com/wiki/Anmothra
- [ ] https://tibia.fandom.com/wiki/Bloom_of_Doom
- [ ] https://tibia.fandom.com/wiki/Chikhaton
- [ ] https://tibia.fandom.com/wiki/Cocoon
- [ ] https://tibia.fandom.com/wiki/Devovorga_(Invincible)
- [ ] https://tibia.fandom.com/wiki/Devovorga
- [ ] https://tibia.fandom.com/wiki/Irahsae
- [ ] https://tibia.fandom.com/wiki/Phrodomo
- [ ] https://tibia.fandom.com/wiki/Teneshpar
- [ ] https://tibia.fandom.com/wiki/Vulnerable_Cocoon

-- todo 8.61-1080+

### 10.80
- [x] https://tibia.fandom.com/wiki/Wereboar
- [x] https://tibia.fandom.com/wiki/Werebadger
- [x] https://tibia.fandom.com/wiki/Werebear

@EPuncker if you or someone else is bored hehe

**Comment by MillhioreBT** [comment]
And those monsters do not exist in the datapack :o?
monster from 8.60

**Comment by omarcopires** [comment]
The following monsters have already been added:

- Werebear
- Werebadger
- Wereboar
- Shard Of Corruption
- Mooh'tah Master
- Lizard Gate Guardian
- Enraged Squirrel
- Merikh the Slaughterer
- Fahim the Wise
- Doctor Perhaps

After I finish the #4126 updates, I'll do the rest of this list.
