### ISSUE TITLE
bug while executing combat inside addevent

### ISSUE THREAD

**Issue by coderwannabe69** [otland/forgottenserver#3470]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
Use this code

```
Its issue from otland that guy requested to put as an issue

local area1 = {
    {0, 1, 0},
    {0, 1, 0},
    {0, 3, 0}
}
local area2 = {
    {1, 1, 1},
    {1, 1, 1},
    {1, 1, 1},
    {0, 0, 0},
    {0, 0, 0},
    {0, 2, 0}
}

local combat = Combat()
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MORTAREA)
combat:setArea(createCombatArea(area1))

local combat2 = Combat()
combat2:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat2:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MORTAREA)
combat2:setArea(createCombatArea(area2))

function onGetFormulaValues(player, level, ninjutsu)
    local min = (level / 5) + (ninjutsu * 1.6) + 9
    local max = (level / 5) + (ninjutsu * 3.2) + 19
    return -min, -max
end

function onGetFormulaValues2(player, level, ninjutsu)
    local min = (level / 5) + (ninjutsu * 1.6) + 9
    local max = (level / 5) + (ninjutsu * 3.2) + 19
    return -min, -max
end

combat:setCallback(CALLBACK_PARAM_NINJUTSUVALUE, "onGetFormulaValues")
combat2:setCallback(CALLBACK_PARAM_NINJUTSUVALUE, "onGetFormulaValues")

local function castSpell(creature, variant, combatt)
    combatt:execute(creature, variant)
end

function onCastSpell(creature, variant)
    castSpell(creature, variant, combat)
    addEvent(castSpell, 200, creature, variant, combat2)
    return true
end
```

Also add this spell into spells.xml
`<instant type="attack" spellid="4" name="spell" words="spell" aggressive="1" direction="1" script="attack/spell.lua">
        <vocation name="Druid"/>
</instant>`

### Expected behaviour
The spell should cast from whenever position the creature is on when the line of code from area2 gonna be executed

### Actual behaviour
https://i.gyazo.com/01948051c5c1520fdd0f2dd50af03638.mp4
When taking a step forward while this spell is casting the second area getting changed

Also addEvent() is a function that calls other stuff after x amount of time so im my opinion this is a bug cause this function should not interact negatively with anything else

**Comment by MillhioreBT** [comment]
You are programming the script in the wrong way!

You must do it this way, please do not complicate your life ;)
<details>
<summary>Script.lua</summary>

```lua
local area1 = {
    {0, 1, 0},
    {0, 1, 0},
    {0, 3, 0}
}

local area2 = {
    {1, 1, 1},
    {1, 1, 1},
    {1, 1, 1},
    {0, 0, 0},
    {0, 0, 0},
    {0, 2, 0}
}

local combat = Combat()
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MORTAREA)
combat:setArea(createCombatArea(area1))

local combat2 = Combat()
combat2:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat2:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MORTAREA)
combat2:setArea(createCombatArea(area2))

function onGetFormulaValues(player, level, ninjutsu)
    local min = (level / 5) + (ninjutsu * 1.6) + 9
    local max = (level / 5) + (ninjutsu * 3.2) + 19
    return -min, -max
end

combat:setCallback(CALLBACK_PARAM_NINJUTSUVALUE, "onGetFormulaValues")

function onGetFormulaValues(player, level, ninjutsu)
    local min = (level / 5) + (ninjutsu * 1.6) + 9
    local max = (level / 5) + (ninjutsu * 3.2) + 19
    return -min, -max
end

combat2:setCallback(CALLBACK_PARAM_NINJUTSUVALUE, "onGetFormulaValues")

local function castSpell(creatureId, variant)
	local creature = Creature(creatureId)
	if not creature then
		return
	end
	
    combat2:execute(creature, variant)
end

function onCastSpell(creature, variant)
    combat:execute(creature, variant)
    addEvent(castSpell, 200, creature:getId(), variant)
    return true
end
```

</details>

**Comment by coderwannabe69** [comment]
Ok but even after making the code written "correctly" the problem did not change from the gif the behaviour stays the same

**Comment by MillhioreBT** [comment]
> Ok but even after making the code written "correctly" the problem did not change from the gif the behaviour stays the same
> 
> Also after noticing the thread on otland i played with it a little and it only breaks whenever inside spells.xml the direction is set to 1
> 
> If i had to guess the variant is missing the direction attribute ?

It works well for me
![GIF 26-05-2021 11-05-11 a  m](https://user-images.githubusercontent.com/28090948/119684261-5d5d0c80-be12-11eb-9917-db2c915e9fc1.gif)

If someone else can check it would be great

**Comment by coderwannabe69** [comment]
> > Ok but even after making the code written "correctly" the problem did not change from the gif the behaviour stays the same
> > Also after noticing the thread on otland i played with it a little and it only breaks whenever inside spells.xml the direction is set to 1
> > If i had to guess the variant is missing the direction attribute ?
> 
> It works well for me
> ![GIF 26-05-2021 11-05-11 a m](https://user-images.githubusercontent.com/28090948/119684261-5d5d0c80-be12-11eb-9917-db2c915e9fc1.gif)
> 
> If someone else can check it would be great

im sorry but u forgot to move before the second area is executed

**Comment by MillhioreBT** [comment]
Ok the problem of blocking is already in the past and you know why! Regarding the problem of the combat area, if I just noticed, I have to do more tests to see what happens is really strange and does not make sense

**Comment by coderwannabe69** [comment]
Also take a look even if i want to execute the whole spell but after x amount of time the same stuff is happening
[https://i.gyazo.com/88d5c7f72a7612eb0038425bffadafab.mp4](url)

code:

```
local area1 = {
    {0, 1, 0},
    {0, 1, 0},
    {0, 3, 0}
}

local area2 = {
    {1, 1, 1},
    {1, 1, 1},
    {1, 1, 1},
    {0, 0, 0},
    {0, 0, 0},
    {0, 2, 0}
}

local combat = Combat()
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MORTAREA)
combat:setArea(createCombatArea(area1))

local combat2 = Combat()
combat2:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat2:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MORTAREA)
combat2:setArea(createCombatArea(area2))

function onGetFormulaValues(player, level, ninjutsu)
    local min = (level / 5) + (ninjutsu * 1.6) + 9
    local max = (level / 5) + (ninjutsu * 3.2) + 19
    return -min, -max
end

combat:setCallback(CALLBACK_PARAM_NINJUTSUVALUE, "onGetFormulaValues")

function onGetFormulaValues(player, level, ninjutsu)
    local min = (level / 5) + (ninjutsu * 1.6) + 9
    local max = (level / 5) + (ninjutsu * 3.2) + 19
    return -min, -max
end

combat2:setCallback(CALLBACK_PARAM_NINJUTSUVALUE, "onGetFormulaValues")

local function castSpell(creatureId, variant)
	local creature = Creature(creatureId)
	if not creature then
		return
	end

	combat:execute(creature, variant)
    combat2:execute(creature, variant)
end

function onCastSpell(creature, variant)
    addEvent(castSpell, 500, creature:getId(), variant)
    return true
end
```

For example if somebody want to do some build up effects and cast the spell after 500ms same stuff happening

**Comment by MillhioreBT** [comment]
I have verified that this behavior is expected, depending on how the spells work, this is because the directional spells always take an initial position and calculate the direction with respect to the player's position, and then when moving before the second is executed combat, a different direction is calculated

If you want something cleaner, you must help the spell find the correct direction, here I show you an example:
```lua
local area1 = {
    {0, 0, 0},
    {0, 0, 0},
    {0, 0, 0},
    {0, 1, 0},
    {0, 1, 0},
    {0, 3, 0}
}

local area2 = {
    {1, 1, 1},
    {1, 1, 1},
    {1, 1, 1},
    {0, 0, 0},
    {0, 0, 0},
    {0, 3, 0}
}

local combat = Combat()
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MORTAREA)
combat:setArea(createCombatArea(area1))

local combat2 = Combat()
combat2:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
combat2:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MORTAREA)
combat2:setArea(createCombatArea(area2))

function onGetFormulaValues(player, level, ninjutsu)
    local min = (level / 5) + (ninjutsu * 1.6) + 9
    local max = (level / 5) + (ninjutsu * 3.2) + 19
    return -min, -max
end

combat:setCallback(CALLBACK_PARAM_NINJUTSUVALUE, "onGetFormulaValues")

function onGetFormulaValues(player, level, ninjutsu)
    local min = (level / 5) + (ninjutsu * 1.6) + 9
    local max = (level / 5) + (ninjutsu * 3.2) + 19
    return -min, -max
end

combat2:setCallback(CALLBACK_PARAM_NINJUTSUVALUE, "onGetFormulaValues")

local function castSpell(creatureId)
    local creature = Creature(creatureId)
    if not creature then
        return
    end
    
    local position = creature:getPosition()
    position:getNextPosition(creature:getDirection(), 1)
    combat2:execute(creature, Variant(position))
end

function onCastSpell(creature, variant)
    combat:execute(creature, variant)
    addEvent(castSpell, 200, creature:getId())
    return true
end
```

**Comment by nekiro** [comment]
Combats are executed where you tell them to. Your variant holds first cast position, which was supplied from onCastSpell, you have to recreate variant and pass it to combat:execute for it to cast on another position.
You can recreate variant by like: Variant(creature:getPosition()).
This works correctly.
