### ISSUE TITLE
liquid containers ignoring subtype parameter in monster loot

### ISSUE THREAD

**Issue by Xikini** [otland/forgottenserver#3476]
### Before creating an issue, please ensure:
- [yes ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [yes ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. put subtype="0" for a liquid container item, such as golden mug in a creature loot table
2. kill monster
3. find water in container, regardless of subtype

### Expected behaviour

find water in container, regardless of subtype

### Actual behaviour

subtype should change the liquid in the container, and lack of a subtype should default to an empty container

**Comment by EPuncker** [comment]
fixed on https://github.com/otland/forgottenserver/commit/9d01be7061c96e7bd46e8c68529f412888cfb2d7
