### ISSUE TITLE
Teleport Trash

### ISSUE THREAD

**Issue by travisani** [otland/forgottenserver#3484]
Players can throw items on teleports

**Comment by nekiro** [comment]
Thats normal

**Comment by marmichalski** [comment]
Maybe he meant teleports without destination. In tibia items thrown on those are destroyed with hitbyfire effect. 🤔

**Comment by travisani** [comment]
with action/unique ids
![image](https://user-images.githubusercontent.com/13306169/122621242-51f4ae00-d06b-11eb-95ba-ebc6129ebabd.png)

**Comment by Znote** [comment]
> with action/unique ids
> ![image](https://user-images.githubusercontent.com/13306169/122621242-51f4ae00-d06b-11eb-95ba-ebc6129ebabd.png)

That is a Lua script bug (or absence of attached Lua code).

**Comment by EPuncker** [comment]
I did a little research:
> - citizen teleport1: item will appear in the right sqm of tp with a red shimmer effect (tested on venore citizen tp)
> - citizen teleport2: item will appear 5 sqm up of tp with a red shimmer effect (tested on thais citizen tp)
> - map (no destination?) teleport: item will be lost (trashholder) with fire effect (tested on shadowthorns tower tps)
> - blue flame tp (pvp arena): item will appear in the tp opposite destination with tp effect (where the player will be when he come back from tp) but will not been thrown
> - blue flame tp (thais open theater): item will be teleported to depot with no problem (lol)

and in short words: they don't have an default behavior, thus it will be user duty to have them scripted as they like since their behavior differs.

**Comment by EPuncker** [comment]
and also as found out in the leaked files, every tp is uniquely scripted

**Comment by soul4soul** [comment]
@EPuncker  Awesome research! The only other TP which comes to mind is the gnomish TP system. If memory serves me correctly, throwing an item on the TP has no effect and just covers the spot.

**Comment by EPuncker** [comment]
> @EPuncker Awesome research! The only other TP which comes to mind is the gnomish TP system. If memory serves me correctly, throwing an item on the TP has no effect and just covers the spot.

I remember in warzone we used to throw items at them and the items were just tp'd back, like the `blue flame tp (pvp arena)` behavior 😛 (I remember this one very well because I used to do this daily for months lmao)

**Comment by travisani** [comment]
like this? 
![image](https://user-images.githubusercontent.com/13306169/122657739-ad42a100-d13c-11eb-99b4-f546d8fbc253.png)

**Comment by marmichalski** [comment]
> like this?
> ![image](https://user-images.githubusercontent.com/13306169/122657739-ad42a100-d13c-11eb-99b4-f546d8fbc253.png)

Some tile-teleports accept items and ignores them - explorer society tile comes to mind. 

Anyway, I guess the shadowthorn / cyclopolis teleports destroy items, because there is a lava under them, thus the hitbyfire effect. I'll try to remember if I've found a teleport that's not placed on lava and acts the same 🤔

**Comment by travisani** [comment]
I've tryied on events/player.lua but no works.
```
`function Player:onMoveItem(item, count, fromPosition, toPosition)	
if blockTeleportTrashing and toPosition.x ~= CONTAINER_POSITION then		
local thing = Tile(toPosition):getItemByType(ITEM_TYPE_TELEPORT)		
if thing then			
self:sendCancelMessage('Sorry, not possible.')			
self:getPosition():sendMagicEffect(CONST_ME_POFF)			
return false		
end	
end`
```

**Comment by Kamenuvol** [comment]
> > * map (no destination?) teleport: item will be lost (trashholder) with fire effect (tested on shadowthorns tower tps)

There is lava under the tp, so the item is catching fire in lava.

**Comment by travisani** [comment]
this effect where delete item "trashholder", is setting in sources ou script? i can't find this.

**Comment by EPuncker** [comment]
> this effect where delete item "trashholder", is setting in sources ou script? i can't find this.

actually the trashholder effect is from the lava beneath the teleport, not the teleport itself

https://github.com/otland/forgottenserver/blob/b920f35002f900421486de1ece1f13813804fb13/src/items.cpp#L160
