### ISSUE TITLE
storage keys for accounts

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#3486]
### Explanation of what you want to do that is currently impossible
player:getAccount():setStorageValue(key, value)
or in case creating account mt wasn't worth it:
player:setAccountStorage(k, v)

### Desired functionality
- store data tied to account rather than characters
- save when a character is logging out

### Available workarounds
sql queries

### Prior art
Imagine an event you can do with multiple chars because the progress is shared.

**Comment by EPuncker** [comment]
done at https://github.com/otland/forgottenserver/commit/49976cf151fb07e5c89282941c34da85055c54e7
