### ISSUE TITLE
Update to version 12

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#3492]
### Explanation of what you want to do that is currently impossible
I've heard that one of the biggest things that is preventing us from moving to version 12 was the lack of open sourced client.

What about this one?
https://github.com/opentibiabr/otclient/ (related commit: https://github.com/opentibiabr/otclient/commit/69a98992e36622eceb99a90c4f4d28ad59579ad6)

### Desired functionality
Getting out of year 2016.

### Available workarounds
using br/spanish server engines

### Prior art
not sure what to put here, is their protocolgame file ok?
https://github.com/opentibiabr/otservbr-global/blob/c6a1b67335cae2a4e2d389c436c71d3f3cde3ed7/src/server/network/protocol/protocolgame.cpp#L634

**Comment by gesior** [comment]
> ### Prior art
> not sure what to put here, is their protocolgame file ok?
> https://github.com/opentibiabr/otservbr-global/blob/c6a1b67335cae2a4e2d389c436c71d3f3cde3ed7/src/server/network/protocol/protocolgame.cpp#L634

It's not. Most of that code gives random crashes as soon as you get 100+ online. More info: https://github.com/opentibiabr/otservbr-global/issues/2670
EVERY time I open otservbr code, I find new critical bug in 5 minutes! Every new system [bestiary/store/market/prey] they coded is sooo easy to crash/abuse/DoS.

That's a difference. TFS is stable. There are no new features, no rl map, but all other servers are based on it.

Will there be any 12+ engine with code quality like TFS? I don't think so. To create all features 10.99 -> 12.x, it will take ~2000 hours. Who will spend 2000 hours on "open source" project that is mostly used to generate money?
I get orders from few popular 12+ servers: "fix me X crash bug in otservbr, but DONT SHARE IT with others". Around 20% of OTS owners are interested in sharing fixes, rest is ready to pay more, to make bug fixes only for them. They use open source software, but they are against open source community.

**Comment by lgrossi** [comment]
I love how you sustain that a vodebase with 0% test coverage and 153 open issues without any real active development work going on is stable.
Without statistics and real data, and also an constructive attitude your comment is just toxic, trying to discredit people that try to help. This is as bad to open source community as leeshers and otadmins that pay to not share. 
That's one of the main reasons why open tibia is dead, however it's to late to you guys to wake up and see it. 

R.I.P. ❤

**Comment by Zbizu** [comment]
I mean we don't have to jump to all 12.x features instantly. New client signals can be ignored until the missing features get implemented. A new otb is enough for now. Fixing otclient isn't really our job so it's fine as long as it connects.

**Comment by dudantas** [comment]
> > ### Arte prévia
> > não sei o que colocar aqui, é o arquivo protocolar deles ok?  https://github.com/opentibiabr/otservbr-global/blob/c6a1b67335cae2a4e2d389c436c71d3f3cde3ed7/src/server/network/protocol/protocolgame.cpp#L634
> 
> Não, não é. A maioria desse código dá falhas aleatórias assim que você recebe mais de 100 on-line. Mais informações: [opentibiabr/otservbr-global#2670](https://github.com/opentibiabr/otservbr-global/issues/2670)
> Toda vez que abro o código otservbr, encontro novo bug crítico em 5 minutos! Cada novo sistema [bestiary/store/market/prey] codificado é tão fácil de travar/abusar/DoS.
> 
> Isso é uma diferença. TFS é estável. Não há novos recursos, nenhum mapa rl, mas todos os outros servidores são baseados nele.
> 
> Haverá algum motor 12+ com qualidade de código como o TFS? Eu não acho. Para criar todos os recursos 10.99 -> 12.x, levará ~2000 horas. Quem vai gastar 2000 horas em projeto de "código aberto" que é usado principalmente para gerar dinheiro?
> Recebo ordens de poucos servidores populares de 12+: "conserte-me x bug de colisão em otservbr, mas DONT COMPARTILHE-o com outros". Cerca de 20% dos proprietários de OTS estão interessados em compartilhar correções, o descanso está pronto para pagar mais, para fazer correções de bugs apenas para eles. Eles usam software de código aberto, mas são contra a comunidade de código aberto.

This is a totally inappropriate comment. The programming is not perfect, all code is flawed and prone to errors, especially when it is made by contributors. Go to the vcpkg repository... There will be several issues. And many others will be the same thing. TFS is full of problems, but since almost nobody uses it raw (it's always adapted, or only uses parts of the code, like otservbr-global does...)

What is stable code for you? A code from 5 years ago that no longer receives relevant updates to the source code (which changes A LOT of THINGS, as happens with the global otbr). Do you know what the real problem I see? It is the lack of HUMILITY in assuming that there is a project that is more advanced than TFS, even with the problems that will eventually arise. Grow up, be better, the community is only losing with this petty attitude.

**Comment by nekiro** [comment]
I cleared this conversation, cause you guys are causing unnecessary beef. Please don't get "perosnal" or just move to forums to argue about that, thanks.

**Comment by EPuncker** [comment]
I hardly agree with @Zbizu , we have to move on, we don't need every feature working, we just need to be able to connect and play (and new otb), I'm pretty sure we have people with decent/proper code to implement missing features as the time goes on, like #2710 from @joseluis2g, I'm sure there will be more, once we bump version

**Comment by Codinablack** [comment]
An official 12.x otb would rock the boat so hard, I'd love to see this, @topic, I am with Epuncker and Zbizu, adding a basic support for newer protocols, just opens the door for anyone who wishes to see these "new systems" implemented to put in a PR for said new system.

**Comment by DoktorHolzbein** [comment]
I would love to see that too!

**Comment by Erza** [comment]
> (and new otb)

The OTB file should be dropped entirely, it's been complicating things for far too long.

**Comment by Zbizu** [comment]
Solution to get rid of being dependent on login.lua:
Create protocolstatus response for website. The website would just return the output of the call directly to the player

The order would be: client -> website -> server -> website -> client
