### ISSUE TITLE
diagonal fire wall runes don't work

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#3494]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. get fire/poison/energy wall rune
2. cast it diagonally

### Expected behaviour
fields appear in diagonal area

### Actual behaviour
shoot effect animation appears, but fields don't show up on the map

### Environment
windows 7, latest commit (containerFix)

### Reproduction environment
clean tfs with config.lua directed to my local database (no other changes to lua or cpp)

**Comment by Zbizu** [comment]
extra info: it's working fine on my build from November 2020 so it might be bugged after #3347 or #3375

**Comment by Brent957** [comment]
I confirmed that wall runes are working as intended on [https://github.com/otland/forgottenserver/tree/f2d74c67959308636a7a725de3bb5af9492b9d61](url)

**Comment by Zbizu** [comment]
still bugged for me

**Comment by Zbizu** [comment]
Quite misleading to read. For the clarity: 3351 was pushed before 3347

**Comment by Zbizu** [comment]
The setupExtArea is called properly. My guess is that it fails to resize.
![obraz](https://user-images.githubusercontent.com/5205079/124523537-c95e6780-ddf7-11eb-9bdf-51456a492e4c.png)

**Comment by Brent957** [comment]
> 
> 
> Quite misleading to read. For the clarity: 3351 was pushed before 3347

Can you explain what was misleading? I compiled both versions in 3551 diagonal runes work fine, in 3347 they do not.

Thanks for fixing/creating a pr, cheers.

**Comment by Zbizu** [comment]
The numbers of the prs. For a moment I thought 3551 was after 3347.
