### ISSUE TITLE
Halberds aren't unique right now.

### ISSUE THREAD

**Issue by Alkenix** [otland/forgottenserver#3528]
Fix in items.xml (line: 20730 & 20733):
`<item id="12046" article="a" name="halberd" />
	<item fromid="12047" toid="12048" name="halberds" />
	<item fromid="12049" toid="12050" article="a" name="heavy weapon rack" />
<item id="12051" article="a" name="halberd" />`

**Comment by Zbizu** [comment]
use the template next time

see "files changed" section of this pr to see how to fix that: https://github.com/otland/forgottenserver/pull/3508
(the solution is using itemid instead of string)

**Comment by Alkenix** [comment]
w8 w8 w8.. All i did was placing an zombie on my map on an uptodate tfs 1.3 server (incl. EPuncker's latest fix).

**Comment by EPuncker** [comment]
lets blame forceMonsterTypesOnLoad to only work with monsters that are on map, and since I have no monster on my map I forgot this :D will fix it soon

**Comment by Alkenix** [comment]
Same with grave flowers (vamps). ^^
Line: 35897

**Comment by Zbizu** [comment]
I'd blame using strings in loot honestly.

Identifier's (id's) purpose is to make things possible to (as the name suggests) identify. Using strings is counterintuitive.

Considering that most of the duplicated loot can be resolved by parsing the first occurrence, I suggest stopping the search on first pickupable item. Alternatively the display of the warning can be a config value.

**Comment by nekiro** [comment]
As I said some time ago, we should drop names support for items everywhere, loot is one of the things. Name is not unique. Id is.

**Comment by Zbizu** [comment]
What about allowing some setting to disable warnings? eg about empty spawns or ambiguous item names with a simple true/false?

**Comment by Alkenix** [comment]
Gonna need to correct this issue..
There are MANY as HELL items doubled in items.xml.
I have no clue why for example an arrow or power bolt needs 2 IDs, but i corrected () all of them for me right now.^^

If someone knows how to change monster loot to ID instead of the name, I'm gonna start that for mine soon.

**Comment by Alkenix** [comment]
[#3540](https://github.com/otland/forgottenserver/pull/3540)
