### ISSUE TITLE
Maybe a bug in Shared Party Experience

### ISSUE THREAD

**Issue by ggruts** [otland/forgottenserver#3548]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Activate Shared Experience

### Expected behaviour

Monster experience is equal regardless of whether two players attack the monster or only one player attacks. (within a shared party experience).

### Actual behaviour
The monster's experience changes if only one player kills and the other is nearby and doesn't attack (within a shared party experience). I tested it with a rotworm and used print() to check. And when I kill the rotworm alone, the experience is 40, but when the other player attacks too, the experience becomes 39.

### Environment
Tibia Client / Windows /  TFS 10.98

**Comment by EPuncker** [comment]
wasn't able to reproduce this...

killing a rat alone:

> 02:59 You gained 7 experience points.

killing a rat with shared exp:

> 02:58 You gained 4 experience points.
> 02:58 Vortex gained 4 experience points.

**Comment by ggruts** [comment]
I reproduced what I'm trying to show, I find it easier to understand.
The experience gained with the monster is different from when only one attacks and the other does nothing. When both attack, the experience changes. Note: monster experience is higher in GIF due to premium account and stamina. I don't know if this is normal.

**Comment by ggruts** [comment]
I reproduced what I'm trying to show, I find it easier to understand.
The experience gained with the monster is different from when only one attacks and the other does nothing. When both attack, the experience changes. 
https://imgur.com/WimfqhB
Note: I don't know if this is normal.

**Comment by Zbizu** [comment]
my guess is that the the calculation sums every member of the party base exp and then redistributes that across party members

the proper solution would be summing the party impact on the killing monster instead, calculating the exp based on that impact and then distributing across party members

**Comment by soul4soul** [comment]
You don't need to damage a creature to get experience in a party. The experience is always distributed equally when the conditions are met. TibiaWiki does a good job at breaking it down on the [Party Page](https://tibia.fandom.com/wiki/Party#Requirements_to_Share_Experience).

**Comment by yamaken93** [comment]
As far i understand there is some floor that eats at least one point of experience.

**Comment by Zbizu** [comment]
In this video they get 10 exp more when both attack though

**Comment by nekiro** [comment]
This is interesting. I'll run some tests to check this one. I'll be back with some info probably.

**Comment by MillhioreBT** [comment]
It is quite rare, but I suppose it is due to a rounding of the numbers, I still do not have much information, but it seems that something is wrong
https://user-images.githubusercontent.com/28090948/129258205-d83d722c-5335-422c-83de-2e2034372744.mp4

**Comment by nekiro** [comment]
> It is quite rare, but I suppose it is due to a rounding of the numbers, I still do not have much information, but it seems that something is wrong
> https://user-images.githubusercontent.com/28090948/129258205-d83d722c-5335-422c-83de-2e2034372744.mp4

https://github.com/otland/forgottenserver/blob/master/data/events/scripts/party.lua#L47

std::ceil this value wouldn't be the fix?

**Comment by MillhioreBT** [comment]
> > It is quite rare, but I suppose it is due to a rounding of the numbers, I still do not have much information, but it seems that something is wrong
> > https://user-images.githubusercontent.com/28090948/129258205-d83d722c-5335-422c-83de-2e2034372744.mp4
> 
> https://github.com/otland/forgottenserver/blob/master/data/events/scripts/party.lua#L47
> 
> math.ceil this value wouldn't be the fix?

yes, for me it works with math.ceil ;)
