### ISSUE TITLE
Store Inbox Wrong ItemID

### ISSUE THREAD

**Issue by LeandroPerrotta** [otland/forgottenserver#3551]
The item id defined in const.h for store inbox is wrong:

`ITEM_STORE_INBOX = 26052,`

The item 26052 doest not exists on Tibia 10.97/98, I only could find this item id on most modern Tibia versions.

I believe the right item id for this const in 10.98 would be **17432** (Purse).

Note: This wrong item assigned in the const was even making my OTClient report a lot of errors when characters login.

**Comment by Zbizu** [comment]
looks like it's time to move forward

**Comment by EPuncker** [comment]
yes it does exist in 10.98 client, the last item id for this version is 26381 (brocade tapestry), so item id 26052 is valid as well as you can see here:

![2021-08-10 16_08_40-ItemEditor 0 5](https://user-images.githubusercontent.com/4684880/128920495-b96d0a32-68cc-4c9c-9bae-791ab5de8a78.png)


but item 17432, this one has been removed from client files...

**Comment by LeandroPerrotta** [comment]
Strange. I look for the item on RME 10.98 and didn't find. Didn't find the item either in items.xml and OTClient was reporting errors about the item does't exists... Then I download a RME for Tibia 12 and run it and found it there. Thought it doest not exists in 10.98.

Anyways you can close it then. Sorry for my mistake.
