### ISSUE TITLE
summon - setFollowCreature, setTarget

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3568]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. /summon rat

### Expected behaviour
![443](https://user-images.githubusercontent.com/43324808/129498313-f7bea6cb-07bc-4aab-ac28-a7550a46ef7b.png)

**Comment by MillhioreBT** [comment]
perfect, I'll fix it...
