### ISSUE TITLE
summon - follow/push behaviour

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3569]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. /summon bug

### Expected behaviour
S = This is where the summon stands related to player
X = Summon cannot **STEP** and player cannot **PUSH** the summon here
P = Player position

![192915484-a7ce2339-7e6c-4071-8a5f-7513b748678d](https://user-images.githubusercontent.com/43324808/213399448-dc166c20-856f-478d-ad6a-dbdc3df6500a.png)

if you try step on **X** position the summon should move "**randomly**" to any of the available tiles, like in this image (yellow squares)
![1](https://user-images.githubusercontent.com/43324808/129499327-465ce205-fc9f-4d5e-88d5-51602da7b470.png)

### Actual behaviour
it's set to 2 sqm regardless where it stands, also seems like it moves to the same position instead of checking what tile is currently available

**Comment by EPuncker** [comment]
most likely to be related to pathfinding #2464

**Comment by Zbizu** [comment]
idk what changes were made, but now they stand too far

expected:
![obraz](https://user-images.githubusercontent.com/5205079/137650631-a65f08c2-a951-4931-9429-123cf2b535fd.png)

actual:
![obraz](https://user-images.githubusercontent.com/5205079/137650636-0368636e-931d-4528-b087-79179c32b2f2.png)

**Comment by emil92b** [comment]
![192915484-a7ce2339-7e6c-4071-8a5f-7513b748678d](https://user-images.githubusercontent.com/43324808/213396365-715e5b85-82c0-4174-aef3-e3a348595337.png)

**Comment by emil92b** [comment]
S = This is where the summon stands related to player
X = Summon cannot **STEP** and player cannot **PUSH** the summon here
P = Player position

![192915484-a7ce2339-7e6c-4071-8a5f-7513b748678d](https://user-images.githubusercontent.com/43324808/213399448-dc166c20-856f-478d-ad6a-dbdc3df6500a.png)

**Comment by emil92b** [comment]
updated first post

**Comment by floki21uu** [comment]
Any possible wayt to solve that?
