### ISSUE TITLE
Client crash if you have more than 255 mounts

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3578]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Add a few custom mounts to your mounts.xml file until you have 254 or more
2. Open your server
3. Login your (GM) character and open outfit window

### Expected behaviour
no client crash

### Actual behaviour
client crash

I think we should have a limit check as we have for outfits [here](https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L2807)

**Comment by gesior** [comment]
There is already limit for outfits (send first 255):
https://github.com/otland/forgottenserver/blob/master/src/protocolgame.cpp#L2807-L2809
Probably nobody expected to have more than 255 mounts on 10.99.

**Comment by marmichalski** [comment]
Here is TFS developer opinion about that: https://github.com/otland/forgottenserver/pull/3576#issuecomment-900376506

good times

**Comment by Zbizu** [comment]
I agree with op here. The limit should be set for the sake of consistency. If otclient can display more than 255, a check for game client type could be made before building the packet.

**Comment by marmichalski** [comment]
> I agree with op here. The limit should be set for the sake of consistency. If otclient can display more than 255, a check for game client type could be made before building the packet (for both outfits and mounts).

This is not how this protocol works. Mounts size is sent as an uint8, which can hold a maximum value of 255, then it expects this size of repeated bytes. Client check solves nothing, as it would require both the server and the client to switch to uint16 for size.

**Comment by ranisalt** [comment]
> Here is TFS developer opinion about that

You do realize that those are completely orthogonal issues, right? One of them can only happen if the server owner intentionally tries to break it, the other is a client limitation that the server can't get around.

**Comment by marmichalski** [comment]
> > Here is TFS developer opinion about that
> 
> You do realize that those are completely orthogonal issues, right? One of them can only happen if the server owner intentionally tries to break it, the other is a client limitation that the server can't get around.

They're completely the same thing for `but the owners should be able to do whatever they want`. Server owner wants to crash players client, so he adds too many mounts. 🤷

**Comment by ranisalt** [comment]
And then has no players. Engine's fault for allowing that?

I'm all in for warning about the issues, though. Honest mistakes should be guarded :)

**Comment by marmichalski** [comment]
Still do not see difference here. Letting owner to crash his server leads to no players too, so?

**Comment by Zbizu** [comment]
There's also a limitation on how many conditions can be displayed. Would you lift that limit too because the server owner should be designing the server the way player can't have infight, skull, party, burning, freezing, poison, curse, electrify, haste, bledding, dazzle and party buff at the same time?
