### ISSUE TITLE
Healing a friend should count for active shared experience

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3579]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Party two characters and activate shared experience
2. Make player A attack a monster
3. Make player B heal player A

### Expected behaviour
Shared experience should activate even if player B didn't attack the monster, but if healing someone (either potion or spell/rune) that is attacking a monster (counted as active) should count as active.

### Actual behaviour
Nothing happens, shared exp is not activated unless he attacks the monster.

### Reproduction environment
I found out about it today in cipbia, and it kind of makes sense that is why I'm reporting this functionality here.

**Comment by marmichalski** [comment]
This part of code seems to be taking care of it: https://github.com/otland/forgottenserver/blob/58c5deba36d86858308baf51640cca88cd103a57/src/player.cpp#L3515-L3517

🤔 💩 🤔

**Comment by EPuncker** [comment]
I tested and it didn't 😅

**Comment by marmichalski** [comment]
In what scenario it does not work for you?

https://user-images.githubusercontent.com/57528542/130336251-98602f10-2783-4a28-9ddc-c881925a3272.mov

**Comment by EPuncker** [comment]
can't test right now but my player A killed several monsters and player B healed him with health potion (which should work), have not tested with exura sio
