### ISSUE TITLE
ghost mode - monster pathing

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3593]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. /ghost
2. place a summon where monster is trying to attack it
3. block monster path before reaches your summon

### Expected behaviour
monster should walk through you

### Actual behaviour
monster choose a different path, for example sidesteps

**Comment by marmichalski** [comment]
After a quick look this part seems to be missing ghost check: https://github.com/otland/forgottenserver/blob/5e267654a23f8bfb6d7a3697589cfe229842962e/src/creature.cpp#L87

**Comment by EPuncker** [comment]
hi @emil92b can you please test if #3595 fix this issue for you?
