### ISSUE TITLE
Fireball does more than Great Fireball

### ISSUE THREAD

**Issue by tysonstrange** [otland/forgottenserver#3606]
Looks like fireball rune does more damage than great fireball rune?

https://github.com/otland/forgottenserver/blob/master/data/spells/scripts/attack/fireball_rune.lua
https://github.com/otland/forgottenserver/blob/master/data/spells/scripts/attack/great_fireball_rune.lua

Are these back to front?

**Comment by EPuncker** [comment]
isn't this intended since one is single target and the other one is AoE? need to test in cipbia but I'm pretty sure they are that way

**Comment by tysonstrange** [comment]
Oh true, i forgot they turned this lame rune into a missle anyway. Withdrawn.
