### ISSUE TITLE
monster walkback pr causing issues

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3615]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. go -1 with normal character, wait a second for mobs to notice you then rope yourself
2. have gm wait on -1 to see what happens
3. yes this was tested with both walkToSpawnRadius enabled / disabled

### Actual behaviour
the monsters will keep walking towards the rope spot even tho normal character is not there (i thought the pr was about walking back and not surrounding the spot) regardless its a bug

### Expected behaviour
before https://github.com/otland/forgottenserver/pull/3604 they stopped walking when player left -1

it was better before, but it was also not correct since **Monster::canSee()** needs an update

i don't know exactly how it should work on all floors in this version but so far i have seen on Rl that they walk if you are on floor 0 and they are on +1 and +2

aswell will walk if you are floor 0 and they are -1

**Comment by emil92b** [comment]
https://github.com/otland/forgottenserver/pull/3612

**Comment by marmichalski** [comment]
This should be resolved by #3612, since it marks monster as idle immediately now.

**Comment by EPuncker** [comment]
hey @emil92b did you test it?

**Comment by emil92b** [comment]
> hey @emil92b did you test it?

been busy, can prob do it in a week or two
