### ISSUE TITLE
Character movement speed

### ISSUE THREAD

**Issue by ggruts** [otland/forgottenserver#3618]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Connect two characters: one of level 750 and one of level 2000. Place the character of level 750 to follow the character of 2000
2. Click on the map with your mouse to run a distance.

### Expected behaviour
The lower-level character loses sight of the other character due to the difference in movement speed. (Theoretically it would be a big difference in movement speed).

### Actual behaviour
The lower-level character can follow the other character without losing sight of him.

### Environment
Windows 10 - Tibia client

### Reproduction environment

https://user-images.githubusercontent.com/67269121/131619147-d3257e02-19e2-4575-9eb2-35692aa581a3.mp4

**Comment by EPuncker** [comment]
I don't think that "expected behavior" is true since cipsoft added the new "speed" formula exactly to prevent this big gap of speed between characters... and also there is a speed limit somewhere so a lvl 10k is not that faster than a lvl 1k

**Comment by marmichalski** [comment]
https://tibia.fandom.com/wiki/Speed_Breakpoints

**Comment by ggruts** [comment]
Oh, I understand now. I come from old tibia and I didn't know it. Thanks for the info.
