### ISSUE TITLE
Wrong return message while trying to attack at PZ

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3629]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

So today I accidentally tried to attack a **monster** while inside PZ and got a weird misleading message "You may not attack a **person** in a protection zone.", so I went to tibia to check the proper message and it is "This action is not permitted in a protection zone."

but still, we need confirmation of what messages are displayed when trying to attack a player (I couldn't test because of non pvp), but I suppose it is the same message as monsters...

edit: yes, for pvp it is the same message

**Comment by josuedhg** [comment]
I has been able to reproduce the bug, also I check the message error in different tibia pvp types (open pvp, optional pvp, retro open pvp, retro hardcore pvp, hardcore pvp) and the message was the same that you has suggested, I submitted a PR with this change #3639

**Comment by EPuncker** [comment]
fixed at https://github.com/otland/forgottenserver/pull/3639
