### ISSUE TITLE
Rune spells items missing proper description

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3633]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Issue
Runes are missing ("words") and vocation names on look

### Expected behaviour

> 17:06 You see 35 fire wall runes ("adevo mas grav flam"). They can only be used by knights, paladins, sorcerers, druids with level 33 and magic level 6 or higher.
> They weigh 18.20 oz.

### Actual behaviour

> 16:48 You see 31 fire bomb runes. They can only be used by players with level 27 and magic level 5 or higher.
> They weigh 32.55 oz.

**Comment by marciNekel** [comment]
`Players` is printed when there are no tags for what vocation the rune is for, so if we want to have listed them, then for every rune we need to add voc tags. 
![image](https://user-images.githubusercontent.com/4026320/132487385-56005d3e-1921-42e3-8a03-a27945969e30.png)
As for words it's just editing `item.cpp - L891`
From 
> s << ". " << (it.stackable && tmpSubType > 1 ? "They" : "It") << " can only be used by ";

To  
>s << " (" << it.runeSpellName << "). " << (it.stackable && tmpSubType > 1 ? "They" : "It") << " can only be used by ";

**Comment by Zbizu** [comment]
I've wrote a new onLook for a privately requested upgrade system. If you add a method to get words from ItemType in lua, I can commit the new onLook. Already got vocations and words working (as well as other "look" features on items), but it uses a cache-based workaround for spell words. All I need to get rid of that workaround is just that method.
