### ISSUE TITLE
Hardcoded values at item.cpp

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3636]
Just a few of the present hardcoded entries at item.cpp that we should take care of at sometime

list of item ids that have onD/Equip like rings and soft boots should be moved to a more friendly place for edits
here:
https://github.com/otland/forgottenserver/blob/437be37a710ff5116262a87ec8b8679e00541b5d/src/item.cpp#L70-L81

lookDistance should be moved to item attribute or something
here: https://github.com/otland/forgottenserver/blob/437be37a710ff5116262a87ec8b8679e00541b5d/src/item.cpp#L1262

this check should not be hardcoded either:
https://github.com/otland/forgottenserver/blob/437be37a710ff5116262a87ec8b8679e00541b5d/src/item.cpp#L1259

**Comment by Zbizu** [comment]
getDescription should be moved to lua entirely and you'll get rid of hardcode.

Also why are the transforms in cpp?

**Comment by Kamenuvol** [comment]
I've deleted the rings lines here and seen no diference

**Comment by EPuncker** [comment]
> I've deleted the rings lines here and seen no diference

they are used only on creating new items I think, for example: if you create item 2640 it will create 6132 instead

**Comment by Kamenuvol** [comment]
It's autotransforming even without those lines

**Comment by Kamenuvol** [comment]
Reading the item constructor it does make any difference at all for these items.

**Comment by Kamenuvol** [comment]
I was wrong, but the code is still useless because you can only create those items by artificial means.

**Comment by Zbizu** [comment]
`itemType->transformDeEquipTo` could be used as a rule for these id changes

**Comment by Kamenuvol** [comment]
It is not on the deequip it's on creation. Example: on loot, you put  with string "power ring" and it would create the using one, this code transforms it on the inactive one

**Comment by DSpeichert** [comment]
See #3669
