### ISSUE TITLE
ultimate spells area bug

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#3643]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. walk around and cast area spell (mas flam/mas tera)

Note: strike, wave and beam spells work fine for some reason

### Expected behaviour
spells get cut properly when walls block them

### Actual behaviour
the spell thinks, the caster is at x-1, y-1 from real caster position
![obraz](https://user-images.githubusercontent.com/5205079/133302994-007ce79b-911c-4633-822c-5370ddc9d38f.png)
![obraz](https://user-images.githubusercontent.com/5205079/133303037-4d57a753-ea2d-411f-9b2c-df64e5d4fc76.png)
![obraz](https://user-images.githubusercontent.com/5205079/133303061-b67044c7-7afa-438a-9806-485952c357f5.png)
![obraz](https://user-images.githubusercontent.com/5205079/133303090-85f89ef8-53f3-45f1-aaa1-c44529e85ed1.png)

### Reproduction environment
master branch, recent builds

I'm aware that I might be the person who broke it (in #3493), but I'm not really sure what is the cause / how to fix it.
edit: posted a PR with a fix. I'm no longer getting this bug with these changes.

**Comment by Alkenix** [comment]
Zbizu's Version hasn't fixed the issue. :(

**Comment by Zbizu** [comment]
@Alkenix either you didn't compile or you're running a different tfs executable than you compiled because I've got confirmation that both versions fix the issue

**Comment by Alkenix** [comment]
Oh dear. I forgot to compile. Sorry. nvm.
Thought a restart help with src too, but it has no impact on server, only on .exe.. <.<
