### ISSUE TITLE
Missing doors

### ISSUE THREAD

**Issue by Alkenix** [otland/forgottenserver#3652]
### Explanation of what you want to do that is currently impossible
Using some doors.

### Desired functionality
Change global.lua.

### Available workarounds
Changing global.lua.

### Prior art
low

Add:
```
openDoors = {, 22816, 22825}
closedDoors = { , 22814, 22823}
lockedDoors = {, 22815, 22824}
```

**Comment by EPuncker** [comment]
hi, can you test https://github.com/otland/forgottenserver/pull/3655 ? thanks

**Comment by Alkenix** [comment]
Your fix is not working for me. :/ Notepad++ says you missed those I mentioned above.^^
![image](https://user-images.githubusercontent.com/87986661/133729834-f118aa41-5b16-4118-a20e-64bc6e8490f8.png)
![image](https://user-images.githubusercontent.com/87986661/133729883-a2242312-b70f-4054-b68f-20334ba1b147.png)

**Comment by EPuncker** [comment]
are these doors in house tiles? are you using latest doors.lua script? have you applied the changes I added to items.xml?

**Comment by EPuncker** [comment]
![bora](https://user-images.githubusercontent.com/4684880/133782969-d69c3b80-d7a7-4a2e-aad6-56df0d9c17b2.gif)

I tested here, 22823 is locked as intended and doesn't open, and 22824 open and close normally

**Comment by Alkenix** [comment]
Yep. They still switch as shown in my screenshots.
Maybe there is an RME fix I need to do too?

**Comment by EPuncker** [comment]
> Maybe there is an RME fix I need to do too?

nope, RME has nothing to do with how doors works 😋 but [here](https://pastebin.com/aNAqQqEZ) is my walls.xml file so you can test
