### ISSUE TITLE
depot items not saving

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3656]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. place any item in depot
2. relog

### Expected behaviour
item should still be here

### Actual behaviour
its gone

https://github.com/otland/forgottenserver/pull/3637

**Comment by nekiro** [comment]
I'll just leave it here
https://github.com/nekiro/TFS-1.4-Downgrades/commit/1bc3eace7ba1757a748ddc279a2d1a65ab5e69d2
