### ISSUE TITLE
Player::blockHit - elemental damage protection calculating incorrectly (I think)

### ISSUE THREAD

**Issue by imranhhk** [otland/forgottenserver#3657]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Normal set up.
2. Equip two items which absorb elemental damage (in my test 1 was 10% fire protection, second was 15% fire protection)
3. Damage the player for 1000 elemental dmg (to keep round numbers)

### Expected behaviour
If for example the 2 items have a total of 25% protection against a certain element (1 item is 10% and the second is 15%) and the player receives 1000 damage of that element, they should receive 750 damage (1000 - (1000 * .25)).

### Actual behaviour
Currently is each elemental protection is handled one after the other, so what happens is:
1st Item is processed:
damage = 1000 - (1000 * .10) 
damage is now 900

2nd item is processed:
damage = 900 - (900 * .15)
damage is now 765

The final damage is 765 (23.5% reduction) instead of 750 (25% reduction)

###
I believe the issue is here: https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L1915
In the loop we should probably just get the total to be reduced and then deduct it at the end outside of the loop.

I have no idea if this is how it works in real tibia, but to me it makes sense that 25% total protection should be reflected accurately.

**Comment by Zbizu** [comment]
This is correct behaviour. Here is data from wearing 3 earth damage reducing items:

![obraz](https://user-images.githubusercontent.com/5205079/133719797-c9bced2e-fc53-44f9-b6a2-83aaed210f15.png)

**Comment by imranhhk** [comment]
> The bonuses stack multiplicatively so you'll never achieve 100% reduction unless you do that with a single item (like helmet of the deep).
> 
> This is correct behaviour. Here is data from wearing 3 earth damage reducing items:
> 
> ![obraz](https://user-images.githubusercontent.com/5205079/133719797-c9bced2e-fc53-44f9-b6a2-83aaed210f15.png)

Thank you for clarifying that! @Zbizu
