### ISSUE TITLE
loot drop fluid containers

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3659]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. add `<item name="bottle" chance="100000" />` to any monster and loot it
3. look description

### Expected behaviour
You see a bottle. It is empty.

### Actual behaviour
You see a bottle of water.

i also tested to add subtype="0", didn't work

**Comment by emil92b** [comment]
side note: 
**actions/scripts/fluids.lua is also bugged, the bottle gets deleted if you try to spill the container**

**Comment by Zbizu** [comment]
The issue doesn't happen for me. The bottle empties properly when it has water. I am getting it is empty message when I try to empty a bottle that is already empty.

tfs: most recent master branch no edits except for database fields in config.lua
platform: windows 7
env: visual studio 2017 v141 10.0.18362.0
mode: x64 release
client: edubart/otclient 10.98

**Comment by emil92b** [comment]
yeah idk how it happend, i dont get it anymore, mby a reload bug ;x

**Comment by Zbizu** [comment]
I see setting count to zero deletes the bottle after spilling the water.

**Comment by emil92b** [comment]
oh ;p makes sense then

**Comment by Zbizu** [comment]
in fact setting suptype="0" and count to anything (together) deletes the bottle after updating its contents

**Comment by EPuncker** [comment]
@emil92b can you check if #3477 fix this issue?

**Comment by emil92b** [comment]
> @emil92b can you check if #3477 fix this issue?

you dont have this commit? https://github.com/otland/forgottenserver/commit/7155c3390e8ca2859e63613ba63b11e3f36c75d1

**Comment by EPuncker** [comment]
> > @emil92b can you check if #3477 fix this issue?
> 
> it conflicts with this commit [7155c33](https://github.com/otland/forgottenserver/commit/7155c3390e8ca2859e63613ba63b11e3f36c75d1)

`local tmpItem = Game.createItem(item.itemId, item.subType ~= -1 and item.subType or count)`

**Comment by emil92b** [comment]
> > > @emil92b can you check if #3477 fix this issue?
> > 
> > 
> > it conflicts with this commit [7155c33](https://github.com/otland/forgottenserver/commit/7155c3390e8ca2859e63613ba63b11e3f36c75d1)
> 
> `local tmpItem = Game.createItem(item.itemId, item.subType ~= -1 and item.subType or count)`

it works together with subtype="0"
