### ISSUE TITLE
monster summon walkback

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3667]
### Explanation of what you want to do that is currently impossible
be able to disable monster summons walkback when they can't see the player anymore

**Comment by EPuncker** [comment]
sorry I didn't understand, where do they walkback to? can you make a small video example? thanks

**Comment by emil92b** [comment]
it's a follow mechanic, example orc shaman summon snakes, player changes floor and snakes return to shaman
i was thinking be able to have them stay around the floorchange waiting for player instead of returning
