### ISSUE TITLE
floorchange unpass objects

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3680]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. place 3 parcels and try to go up a floor onto an "unpass" object like a statue or trough
2. try to stack 2 unpassable objects aswell by pushing them into floorchange, you will get same result "not enough room"

### Expected behaviour
tested on rl-tibia and it should be possible
![bug](https://user-images.githubusercontent.com/43324808/134352724-c958b4f6-7b2a-40e2-8820-25c8dffdb2a8.png)

![stack](https://user-images.githubusercontent.com/43324808/134356381-d5d3b2bb-2347-4159-8bd0-ba256552d219.png)

### Actual behaviour
"there is not enough room."

**Comment by EPuncker** [comment]
maybe it was possible on 10.98 version, we will have to wait for version 12.x to try it again

**Comment by Zbizu** [comment]
https://github.com/otland/forgottenserver/blob/c9a65a8051d0e6aa59889b6c47aba77e74cd6f0b/src/game.cpp#L807

my guess is that we have to use something other than TILESTATE_BLOCKSOLID

**Comment by emil92b** [comment]
added another example with stacking items by floorchange

**Comment by emil92b** [comment]
> maybe it was possible on 10.98 version, we will have to wait for version 12.x to try it again since we can't test on official 10.98 anymore, unless we find a video

version 7.7 works the same as tibia 11, so doubt any difference on 10.98
![123123](https://user-images.githubusercontent.com/43324808/134357217-239d2a64-c4d9-430a-bf42-5663f03bb953.png)

**Comment by Zbizu** [comment]
Yeah it was like that since feature introduction probably. Please test if my pull request fixes the issue.

**Comment by emil92b** [comment]
> Yeah it was like that since feature introduction probably. Please test if my pull request fixes the issue.
yes it is working, only thing left is stacking those items by adding into floorchange like on the second picture

**Comment by Zbizu** [comment]
hey, do you play on pvp world? Please test if you can levitate/parcelwalk towards magic walled tiles

**Comment by emil92b** [comment]
> hey, do you play on pvp world? Please test if you can levitate/parcelwalk towards magic walled tiles
you cannot, also teleport effect on levitate and magic rope should be sent on previous position

**Comment by Zbizu** [comment]
I'll look into magic rope later. I've added a commit that changes how magic effect is launched for levitate. Check if the spell is 100% accurate now.

**Comment by emil92b** [comment]
> I'll look into magic rope later. I've added a commit that changes how magic effect is launched for levitate. Check if the spell is 100% accurate now.

ye levitate seems to be alright now, i only noticed that it seems to be case sensitive for the parameter

**Comment by Zbizu** [comment]
added a commit to ignore case sensitivity and spaces in param

**Comment by emil92b** [comment]
?

**Comment by Zbizu** [comment]
what else is here to do?

**Comment by emil92b** [comment]
> 
> 
> what else is here to do?

* read number 2 in the reproduce steps, check second image if you don't get it
* we talked about magic rope

**Comment by emil92b** [comment]
cool, now here is your **"needs-triage"**, since text wasn't enough
![33](https://user-images.githubusercontent.com/43324808/139611064-11347111-b52d-45c8-b4b7-93aa552568ff.png)
