### ISSUE TITLE
weapon usage without requirements

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3684]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Expected behaviour
players that have items equipped in weapon slot but don't fil the requirements for it should attack with fist instead (for example using wand on a knight)

### Actual behaviour
if you have wand equipped and attacking, you do nothing

**Comment by Kamenuvol** [comment]
the melee weapons are "properly used" 
all the other equips are "can be used"

**Comment by EPuncker** [comment]
Using bows in any(?) vocation without equipping arrows should not do any attack at all (this is used specially in pvp worlds at war to not get a skull by mistake)
