### ISSUE TITLE
item pushing

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3685]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Expected behaviour
there should be a cooldown for pushing items, i believe its 0.1 second

### Actual behaviour
currently no cooldown when pushing an item

**Comment by EPuncker** [comment]
I believe there is no delay other than human/internet latency limitation

https://www.youtube.com/watch?v=IWdwylR0wJ4

otherwise cipsoft would have implemente some message as they did with "You cannot use objects that fast"
