### ISSUE TITLE
stop distance attacks while moving

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3686]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Expected behaviour
your distance attacks should be on hold until you stop moving

### Actual behaviour
currently you can run around and shoot freely

**Comment by EPuncker** [comment]
is your classicAttackSpeed set to false or true?

**Comment by emil92b** [comment]
> is your classicAttackSpeed set to false or true?

tried with both, same result

**Comment by Codinablack** [comment]
This isnt the way real cibia works. In real tibia, one can stop to make the attack come sooner, but not stopping doesnt keep a paladin from ever shooting, it just takes a bit longer.
