### ISSUE TITLE
Can't run as Debug (Windows)

### ISSUE THREAD

**Issue by hugoj-goncalves** [otland/forgottenserver#3692]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Open project in Visual Studio (2019)
2. Select Debug x64 configuration
3. Set working dir to ".."

### Expected behaviour
Should run just fine

### Actual behaviour
Acess memory violation o.O
![image](https://user-images.githubusercontent.com/10927715/134796300-56caa51b-beab-47b0-a60a-ad8730e21f95.png)

### Environment
Windows 10 x64

**Comment by EPuncker** [comment]
sorry for the delay, can you check if https://github.com/otland/forgottenserver/pull/3694 fix this issue for you?

**Comment by Codinablack** [comment]
I'm pretty sure this is solved now. Black tek has been able to use debug mode for a long time now, and its based off 1.4 with mostly just fixes from 1.6. Plus, with the addition of [4742](https://github.com/otland/forgottenserver/pull/4742), this should definitely not be a factor anymore.
