### ISSUE TITLE
Should we support both 10.98 and 12.71?

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#3747]
Gentlemen, I would like to invite you to discuss a matter of high importance. I have got a question for you:

What is your opinion on supporting both 10.98 (modded) and 12.71 simultaneously? 

Here's my reasoning behind that idea:
- We have spr/dat provided (https://github.com/EPuncker/1098extended)
- We have compatible otb (also @EPuncker's repo)
- I managed to get both working (https://github.com/Zbizu/forgottenserver/tree/version12_b) (the code quality will be improved, don't worry)
- We can play that with otclient (10.98 protocol, EPuncker's spr/dat) without changing anything in it.

I have also discovered that most of new features can be backported using talkactions and modalwindows if necessary. For otclient they can be in modules.

Obligatory issue format:
### Explanation of what you want to do that is currently impossible
Play on new client version

### Desired functionality
Play using modded 10.98 or clean 12.71.

### Available workarounds
Downgrading 12.71 features.

### Prior art
![obraz](https://user-images.githubusercontent.com/5205079/137779917-f40461f6-5349-455b-9df1-7723d97f84ce.png)

**Comment by DoktorHolzbein** [comment]
Leave 10.98 support forever.

**Comment by Zbizu** [comment]
I've asked plenty of people in private as well and it seems that there is not much community interest in keeping 10.98 compatibility so I will be removing `legacyProtocol` from the code soon.

If for some reason anyone needs to have both clients supported or is planning a downgrade, I've archived current state of `version12_b` branch here: https://github.com/Zbizu/forgottenserver/tree/1098_1271

**Comment by ranisalt** [comment]
Guys who want to keep 10.98, please explain why. Out of the top 50 servers on otservlist, only 3 of them are on 10.9x, and out of those, 2 use a custom client. More than half are using 12.x, the rest is using 8.6, so I don't see a lot of appeal for 10.98

**Comment by mattyx14** [comment]
> Guys who want to keep 10.98, please explain why. Out of the top 50 servers on otservlist, only 3 of them are on 10.9x, and out of those, 2 use a custom client. More than half are using 12.x, the rest is using 8.6, so I don't see a lot of appeal for 10.98

This is my opinion ... they want to use the 10.98 client just because in that you can use the bot ...

**Comment by jo3bingham** [comment]
I agree that 10.98 should be burned, `master` should only support one protocol at a time. If need be, make a 10.98 branch and cherry-pick bug fixes to it. With that being said, the old protocol, and login protocol, should be burned from the code as well.

**Comment by soul4soul** [comment]
> 
> 
> It's pretty good actually. I was sceptical at first too, but after a month of playing global I wouldn't go back to 10.98.
> 
> Action bars are super nice for mages. Feels almost like elfbot. You only need to configure the panel on the right to display less buttons because half of them are useless.

Agreed, while I like the simplicity of old clients and it working so well with ancient hardware the 12.x client has so many nice quality of life changes. WASD + action bar + built in trackers + ability to assign hotkeys to more actions improves the game play. I'd use it over otclient given the option.

**Comment by strndi** [comment]
> > > Guys who want to keep 10.98, please explain why. Out of the top 50 servers on otservlist, only 3 of them are on 10.9x, and out of those, 2 use a custom client. More than half are using 12.x, the rest is using 8.6, so I don't see a lot of appeal for 10.98
> > 
> > 
> > What list are you even looking at? The only server on otservlist that strictly only allows 12.x client is ixodus. Every other "12.x" server supports older clients, the absolute majority of players on those servers play on older clients, or use otcv8.
> > In general this is a really weird direction we're heading in, the new tibia client isn't even good. We're going to drop 10x client support, even though it's the most used along with otclient. Does OTClient even have support for 12x? From what I know otcv8 supports it, I doubt the original version has been updated though.
> > For people actually wanting a good client, start using otcv8.
> 
> so "no one uses default tfs 10.98", but after we want to change it to support newer stuff, some people come to say HOW DARE YOU? Kinda weird ngl. Don't worry otc does not support, but will, cause why not? "New tibia client isnt even good", dude did you use it? How blinded are you? If you want 10.98 use the release and that's it.

I have used the new client extensively played on new worlds , played on the gunzodus servers using the client. I have even looked into using it for my own server and the client is absolutely terrible for custom servers for one, glad we're looking to be an exact replica of real tibia these days. Really great stuff. 

Why do you think that upgrading the distro will bring new users? TFS used to be a great minimalistic base, with all the bloat the new client adds, and in general with all the changes done the last years. This is not the case anymore, it's just another poor version of otservbr.

 Like I said before, there's only one server strictly only allowing the 12x client by itself - ixodus, and even that one would probably do better allowing old clients. So what are we looking to gain by upgrading the version?

**Comment by strndi** [comment]
All in all, it doesn't really matter much. OTCLientv8 will work and it's the superior client, just sad to see TFS going backwards in time
