### ISSUE TITLE
force exiting client removing pzlock

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3754]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. kill player
2. force exit client
3. wait for server kick (1 min) and login again then walk into protection zone

https://otland.net/threads/tfs-1-4-pz-lock-issue.278445/

### Expected behaviour
should not be able to enter

### Actual behaviour
you can enter

**Comment by waqmaz93** [comment]
this hsould be marked as a bug

**Comment by marmichalski** [comment]
> this should be marked as a bug

When someone actually confirms that the behaviour is wrong. It does not take much time to level up a character just to kill it later on. 😎
