### ISSUE TITLE
Expanding OTBM possibilities

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#3763]
Short summary: more item atrtibutes in mapeditor

### Explanation of what you want to do that is currently impossible
- setting item attributes through mapeditor (including custom attributes)

### Desired functionality
- decorating map with podiums (tp rooms, quest areas, towns, anything)
- upgraded items as quest rewards using ported 0.4 quest system
- expanding possibilities of custom attributes
 
### Available workarounds
- startup globalevent
- custom quest system

### Prior art
new attrs:
`OTBM_ATTR_PODIUM = 0x17`
`OTBM_ATTR_BASEATTRIBUTE = 0x18` (or some more distant numbers just in case there would be need for something there)
`OTBM_ATTR_CUSTOMATTRIBUTE = 0x19`

proposed attr structure:
```
(one only) 0x17 + u8 flags + u8 direction + u16 lookType + 4x u8 colors + u8 addons + u16 lookMount + 4x u8 mount colors
(multiple allowed) 0x18 + u16 attrId + u16 length + data (number, string or binary)
(multiple allowed) 0x19 + u8 key type (0x00 number, 0x01 string) + u16 or string key + u16 value length + value data (number, string or binary)
```

Backwards compatibility would be maintained. Current attributes (action, unique, text) would be kept.

**Comment by giuinktse7** [comment]
Sounds good to me! 

Some thoughts about [this related thread](https://otland.net/threads/i-need-information-about-otbm4-0-7-0-revscriptsys.278579/), specifically about the OTBM version bump: 

Is adding these three attributes enough reason for a major version bump? Is it a bad idea to remain on OTBM3? This should not break any existing OTBM3 parsers, they would just skip the unknown attributes.

**Comment by Zbizu** [comment]
otbm4 saves attributes in a bit different way. I'll have to look into serialization code to see what can be kept.

**Comment by giuinktse7** [comment]
Ah, right, I remember now. I actually used the OTBM4 way of serializing attributes for my map editor. In OTBM4, the attribute map for an item is stored as

- 1 byte for OTBM_ATTR_ATTRIBUTE_MAP = 0x80
- 2 bytes for amount of attributes
- For each attribute:
  - Attribute name as:
    - 2 bytes string length N
    - N bytes attribute name string
  - 1 byte for attribute type, types are:
    - None = 0
    - String = 1
      - 4 bytes for string length N
      - N bytes for string data
    - Integer = 2
      - 4 bytes for int data
    - Float = 3
      - ??
    - Boolean = 4
      - 1 byte for bool data
    - Double = 5
      - 8 bytes for double data

(including escape chars `0xfd` when necessary)

Is there any other known difference between OTBM3 and OTBM4? I think this is the only difference present in the RME source

**Comment by Zbizu** [comment]
I think that double, float and boolen are quite overkill, but serialization is definitely worth looking into.

**Comment by giuinktse7** [comment]
In what way do you think they are overkill? I think it's a fair assumption that we might want to store a boolean/double/float property at some point in the future.

My only gripe with this serialization is that we store the attribute type (name) as a string instead of an ID, which might impact file size. But maybe few enough items have attributes that it doesn't make a difference in practice.

**Comment by Zbizu** [comment]
After adding podium and figuring out how the otbm attributes translate to server item attributes, I deem this change no longer necessary. The workarounds I know are satisfying enough.
