### ISSUE TITLE
missing open trap mechanics

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3778]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Expected behaviour
- [ ] when adding any item ontop of an "open trap" - transform to "closed trap" and poff on (trap) pos
- [ ] throwing "open trap" from inventory to ground - transform to "closed trap" and poff on (ground) pos
- [ ] pushing "open trap" from ground or inventory into floorchange stairs/holes etc - poff on (floorchange) pos

**Comment by waqmaz93** [comment]
This will need backward compatibility in config lua for older versions like 7.6 which didnt have this feature

**Comment by emil92b** [comment]
> This will need backward compatibility in config lua for older versions like 7.6 which didnt have this feature

what are you talking about?, it works the same in all versions.
