### ISSUE TITLE
stacking items with same custom attribute doesn't work

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#3783]
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. create 20 spears
2. give them custom attribute key 450, value 3
3. split them
4. try to stack them

### Environment
TFS 1.4 fork version12_b branch
Very likely possible to reproduce on master as well considering that git blame points to commits made 7 years ago.

**Comment by MillhioreBT** [comment]
I have changed the method of comparing the items and now it works correctly

<details>
<summary>Code</summary>

```c++
bool Item::equals(const Item* otherItem) const
{
	if (!otherItem || id != otherItem->id) {
		return false;
	}

	const auto& otherAttributes = otherItem->attributes;
	if (!attributes) {
		return !otherAttributes || (otherAttributes->attributeBits == 0);
	} else if (!otherAttributes) {
		return (attributes->attributeBits == 0);
	}

	if (attributes->attributeBits != otherAttributes->attributeBits) {
		return false;
	}

	const auto& attributeList = attributes->attributes;
	const auto& otherAttributeList = otherAttributes->attributes;
	for (const auto& attribute : attributeList) {
		if (ItemAttributes::isIntAttrType(attribute.type)) {
			for (const auto& otherAttribute : otherAttributeList) {
				if (attribute.type == otherAttribute.type && attribute.value.integer != otherAttribute.value.integer) {
					return false;
				}
			}
		} else if (ItemAttributes::isStrAttrType(attribute.type)) {
			for (const auto& otherAttribute : otherAttributeList) {
				if (attribute.type == otherAttribute.type && *attribute.value.string != *otherAttribute.value.string) {
					return false;
				}
			}
		} else {
			for (const auto& otherAttribute : otherAttributeList) {
				if (attribute.type == otherAttribute.type && *attribute.value.custom != *otherAttribute.value.custom) {
					return false;
				}
			}
		}
	}
	return true;
}
```

</details>

I also added this but not if it's actually necessary:
```c++
bool operator==(const CustomAttribute& otherAttr) const {
	return value == otherAttr.value;
}

bool operator!=(const CustomAttribute& otherAttr) const {
	return value != otherAttr.value;
}
```

If you wish, you can open a PR, but feel free to try it first to see if it works for you as well as it does for me.

<details>
<summary>GIF</summary>

![GIF 26-11-2021 04-31-58 a  m](https://user-images.githubusercontent.com/28090948/143550997-e92acf53-a452-431e-a179-817a697b588a.gif)

</details>

If I get a free moment to open the PR I will

**Comment by Zbizu** [comment]
I solved that [this way](https://github.com/Zbizu/forgottenserver/commit/93b2f5867704d5a8c3892c972eac25d16b452b22), though it needs more testing.

I don't have time at the moment so I'll write what has to be tested:

normal item + normal item
normal item + custom attr item
custom attr item + same custom attr item

custom attr item + different custom attr item
- same key different value
- same value different key

normal item + item that had custom attribute erased

item with erased custom attr + another item with erased custom attr

erased item attr + item with custom attr

plus all of the above but with swapped item and item2

**Comment by Zbizu** [comment]
ok, I added a small patch to fix stacking custom attrs also. This can spawn null pointer references so I advise testing.
https://github.com/Zbizu/forgottenserver/commit/1ae91785af072c32ade25cc6589816aaf4fd3c20

**Comment by DSpeichert** [comment]
Fixed in 3803
