### ISSUE TITLE
Fix Wiki: Compiling on Windows (vcpkg)

### ISSUE THREAD

**Issue by luanluciano93** [otland/forgottenserver#3793]
On the wiki page: Compiling on Windows (vcpkg) ...

- The visual studio of the link is 2022, I don't know if anything changes in the compilation, being 2022, but the link sends to it...

- In the commands: 4. Install libraries ... the command starts with the wrong slash ... 
`./vcpkg install`
the correct one would be: 
`.\vcpkg install`

**Comment by EPuncker** [comment]
thanks, fixed

just a note for other people:
cmd uses ./
powershell uses `.\`

**Comment by luanluciano93** [comment]
could you clear a doubt? If I download visual studio 2022, would it be able to compile normally?

**Comment by EPuncker** [comment]
> could you clear a doubt? If I download visual studio 2022, would it be able to compile normally?

I'm trying it right now, but probably yes, if I succeed I'll open a PR updating tfs VS project to use latest one

**Comment by EPuncker** [comment]
> could you clear a doubt? If I download visual studio 2022, would it be able to compile normally?

yes, it works 😄 
https://github.com/otland/forgottenserver/pull/3794
