### ISSUE TITLE
Make executable and dll output to main folder

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3812]
### Explanation of what you want to do that is currently impossible
Make generated executable and dlls output to main folder when compiling with Visual Studio

### Desired functionality
explained above, making it more newbie friendly

### Available workarounds
Currently, users need to copy generated files from `tfs\vc14\x64(32)\Release(Debug)` to `tfs\` in order to run the server when compiling on Windows.

### Prior art
Adding **outdir** tags and some path under `PropertyGroup` in the `theforgottenserver.vcxproj` could do the trick
`<OutDir></OutDir>`

**Comment by DSpeichert** [comment]
That would overwrite it you want to compile both Debug & Release or 32/64 bit versions.

I'd argue that if you are not able to copy files, then you're not likely to compile either.

**Comment by Kamenuvol** [comment]
just add "_rel" and "_db", "x86" and "x64" in the output names

**Comment by EPuncker** [comment]
> I'd argue that if you are not able to copy files, then you're not likely to compile either.

[context](https://otland.net/threads/recently-compiled-tfs-1-4-downgrade-to-7-72-server-instantly-closes.278857/#post-2678957)

**Comment by DSpeichert** [comment]
> > I'd argue that if you are not able to copy files, then you're not likely to compile either.
> 
> [context](https://otland.net/threads/recently-compiled-tfs-1-4-downgrade-to-7-72-server-instantly-closes.278857/#post-2678957)

That actually proves that the issue was not the location of files but the idea of the console window disappearing.

**Comment by EPuncker** [comment]
> > > I'd argue that if you are not able to copy files, then you're not likely to compile either.
> > 
> > 
> > [context](https://otland.net/threads/recently-compiled-tfs-1-4-downgrade-to-7-72-server-instantly-closes.278857/#post-2678957)
> 
> That actually proves that the issue was not the location of files but the idea of the console window disappearing.

they disappeared because he placed the files in the src folder, but okay you won
