### ISSUE TITLE
Question/possible bug in TFS 1.2

### ISSUE THREAD

**Issue by Cdotbotbarbar** [otland/forgottenserver#3818]
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the C++ code in this repository

Steps to reproduce (include any configuration/script required to reproduce)
1.  changed in this Line 
https://github.com/otland/forgottenserver/blob/master/src/monster.cpp#L771
To
`spawn->removeCreature(this);`

I changed so that the monster (A) remains in the game after crossing the line of being (removed) and a new monster is created in monster (A) respawn.

### Expected behaviour

When i lure monster (A) remains in the game and another monster (B) is created at its respawn location, if i not kill the monster (A) and lure the monster (B) after crossing the line to being (removed), another monster (C) is created, 

### Actual behaviour
The monster (A) remain in game and monster (B) is creted at its respawn location, if not kill the monster (A) and Lure the monster (B) after crossing the line to being (removed), the other monster (C) is **NOT** created, 

### Environment
Windows 10 64 bits, visual studio 2017

### Reproduction environment
Lure a monster (A) out of the line, then wait for the respawn to appear again and then lure the monster (b) off the line too.
and so the monster (C) is not created.

I don't know why you can only create the monster again once.

**Comment by nekiro** [comment]
How are we supposed to answer that? You changed the source code and expected certain result, but it was different. Appears to be problem with your changes?
You use spawn->removeCreature which **removes** creature from spawn not from game. If you remove creature from spawn it will never respawn again.

**Comment by marmichalski** [comment]
> You use spawn->removeCreature which **removes** creature from spawn not from game. If you remove creature from spawn it will never respawn again.

This removes creature from `spawnedMap`, not `spawnMap`.

You might need to call `spawn->startSpawnCheck();` after removal?

**Comment by DSpeichert** [comment]
You say it's TFS 1.2 but link to master branch. No bueno.
