### ISSUE TITLE
hasHeight is bugged in tfs .

### ISSUE THREAD

**Issue by DSpeichert** [otland/forgottenserver#3828]
hasHeight is bugged in tfs .
in function:
`ReturnValue Game::internalMoveCreature(Creature* creature, Direction direction, uint32_t flags /*= 0*/)`
add this:
`
		if (creature->getTile()->hasHeight(3))
		{
			std::cout << "hasheight = 3\n";
		}
		if (creature->getTile()->hasHeight(2))
		{
			std::cout << "hasheight = 2\n";
		}
		if (creature->getTile()->hasHeight(1))
		{
			std::cout << "hasheight = 1\n";
		}
		if (creature->getTile()->hasHeight(0))
		{
			std::cout << "hasheight = 0\n";
		}`
And now start walking on parcels. You will see what i mean.
![dupa](https://user-images.githubusercontent.com/45514240/144712937-3e273562-4632-4cb2-93bd-dad6ecf910b3.gif)

_Originally posted by @waqmaz93 in https://github.com/otland/forgottenserver/issues/2266#issuecomment-986035784_

**Comment by Zbizu** [comment]
Can you confirm this bug? Looks like not only the author used edited sources but also was checking fromPos rather than toPos.

**Comment by waqmaz93** [comment]
try this:
`ReturnValue Game::internalMoveCreature(Creature* creature, Direction direction, uint32_t flags /*= 0*/)
{
	creature->setLastPosition(creature->getPosition());
	const Position& currentPos = creature->getPosition();
	Position destPos = getNextPosition(direction, currentPos);
	Player* player = creature->getPlayer();

	bool diagonalMovement = (direction & DIRECTION_DIAGONAL_MASK) != 0;
	if (player && !diagonalMovement) 
	{
		if (creature->getTile()->hasHeight(1))
		{
			std::cout << "creature->getTile()->hasHeight 1\n";
		}
		if (creature->getTile()->hasHeight(2))
		{
			std::cout << "creature->getTile()->hasHeight 2\n";
		}
		if (creature->getTile()->hasHeight(3))
		{
			std::cout << "creature->getTile()->hasHeight 3\n";
		}
		if (creature->getTile()->hasHeight(4))
		{
			std::cout << "creature->getTile()->hasHeight 4\n";
		}

		Tile* tmpTile = map.getTile(destPos.x, destPos.y, destPos.z);

		if (tmpTile && tmpTile->hasHeight(1)) {
			std::cout << "tmpTile->hasHeight 1\n";
		}
		if (tmpTile && tmpTile->hasHeight(2)) {
			std::cout << "tmpTile->hasHeight 2\n";
		}
		if (tmpTile && tmpTile->hasHeight(3)) {
			std::cout << "tmpTile->hasHeight 3\n";
		}

		if (tmpTile && tmpTile->getGround()) {
			std::cout << "tile ground\n";
		}

		/*
		if (currentPos.z != 8 && creature->getTile()->hasHeight(3)) {
			Tile* tmpTile = map.getTile(currentPos.x, currentPos.y, currentPos.getZ() - 1);
			if (tmpTile == nullptr || (tmpTile->getGround() == nullptr && !tmpTile->hasFlag(TILESTATE_BLOCKSOLID))) {
				tmpTile = map.getTile(destPos.x, destPos.y, destPos.getZ() - 1);
				if (tmpTile && tmpTile->getGround() && !tmpTile->hasFlag(TILESTATE_BLOCKSOLID)) {
					flags |= FLAG_IGNOREBLOCKITEM | FLAG_IGNOREBLOCKCREATURE;

					if (!tmpTile->hasFlag(TILESTATE_FLOORCHANGE)) {
						player->setDirection(direction);
						destPos.z--;
					}
				}
			}
		}

		if (currentPos.z != 7 && currentPos.z == destPos.z) {
			Tile* tmpTile = map.getTile(destPos.x, destPos.y, destPos.z);
			if (tmpTile == nullptr || (tmpTile->getGround() == nullptr && !tmpTile->hasFlag(TILESTATE_BLOCKSOLID))) {
				tmpTile = map.getTile(destPos.x, destPos.y, destPos.z + 1);
				if (tmpTile && tmpTile->hasHeight(3)) {
					flags |= FLAG_IGNOREBLOCKITEM | FLAG_IGNOREBLOCKCREATURE;
					player->setDirection(direction);
					destPos.z++;
				}
			}
		}
		*/
	}

	Tile* toTile = map.getTile(destPos);
	if (!toTile) {
		return RETURNVALUE_NOTPOSSIBLE;
	}
	return internalMoveCreature(*creature, *toTile, flags);
}`
