### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by dex-89** [otland/forgottenserver#3829]
I have problem with login to new TFS...

[X] I use original znote ACC (with login.php)
[X] Character list is ok
![image](https://user-images.githubusercontent.com/67392692/144722129-414f8966-f104-4ed2-9551-77c61ed042c1.png)

but if server is online
![image](https://user-images.githubusercontent.com/67392692/144722136-6c866b0c-7807-4277-85c5-a99df245e7fa.png)

No error in console, port (7172) is open and config.lua / config.php IP addresses and database data are the same in TFS and Znote

I can help with Cyclopedia, but I have to test it ... but I don't know how to log in...

**Sorry for the lack of style**

**Comment by Peixonauta2** [comment]
Did you solve your problem? I have this same problem.

**Comment by dex-89** [comment]
> Did you solve your problem? I have this same problem.

Yes, now all works... Edit session key for TFS
