### ISSUE TITLE
Server appears to stop after "loading LUA scripts"

### ISSUE THREAD

**Issue by lilbigmouth** [otland/forgottenserver#3872]
I've downloaded the source code of 1.4.1 / master branch and eventually got the code to compile with vcpkg. However, shortly after starting the executable in command prompt, it prints "Loading LUA Scripts" to the console but then kicks me back out with no error.

I'm not sure if this is part of the problem - when trying to compile before, the console would output [1/80] etc up until [80/80] where it would say something such as "Unable to link - missing file libmariadb_x64". Running vcpkg integrate install seemed to fix this, but the build output changed to only show 1> on each line.

Finally, I'm unable to use the debugger inside Visual Studio as well. This fails to load "./config.lua", when it is either inside the directory with the built executable, or inside the project's root folder.

**Comment by EPuncker** [comment]
Could you please provide a screenshot of the error? and does it happen with default data folder or are have you made any changes to it?

Are you using master branch or 1.4.1? they are different versions

**Comment by lilbigmouth** [comment]
Hi @EPuncker , thanks for replying.

From looking at some commit history in the master branch and at the code I have, I am confident that it was v1.4.1 that I downloaded the code of.
I have made no changes to the data folder that I am aware of.

When running from a standalone folder:
![image](https://user-images.githubusercontent.com/20950727/147237109-7a62b0af-3261-4ca4-986c-9ea42c8b8023.png)

When attempting to run the debugger in VS:
![image](https://user-images.githubusercontent.com/20950727/147237268-3714addf-a0b0-4672-a41d-97922d905419.png)

**Comment by Zbizu** [comment]
@lilbigmouth specify debugger path correctly and it will load config properly
https://otland.net/threads/useful-tricks-in-visual-studio-for-beginners.277013/#post-2665365

**Comment by lilbigmouth** [comment]
Thanks @Zbizu , that seemed to work with the release configuration! Seems to be working when copied into the standalone folder too.
Can I suggest this is pointed to from the github wiki / compile guide please?

**Comment by Zbizu** [comment]
I believe that (if possible) default debugger directory should be added to visual studio project folder.
