### ISSUE TITLE
angle spell wrong calculation

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3880]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
add this attack spell to your monster and restart your server, reloading revscript doesn't seem to work

`
{name = "combat", type = COMBAT_ENERGYDAMAGE, interval = 2*1000, chance = 100, length = 3, spread = 3, minDamage = -120, maxDamage = -210, effect = CONST_ME_POFF}
`

### Expected behaviour
![22](https://user-images.githubusercontent.com/43324808/147880032-dca16c86-bdec-436a-970f-ce3eac53ab0c.png)
[https://www.youtube.com/watch?v=UyHX_bnjLCY](https://www.youtube.com/watch?v=UyHX_bnjLCY)

### Actual behaviour
![33](https://user-images.githubusercontent.com/43324808/147880036-cbdf5a4d-42e3-42d0-946e-c53da4322b21.png)

it's wierd because dragon's fire wave `length = 8, spread = 3` is calculated correct, but not yeti's `length = 3, spread = 3`

![1111](https://user-images.githubusercontent.com/43324808/147880265-bfd79633-1c42-4ecf-8e9b-dcf3a88a7bd6.png)

**Comment by soul4soul** [comment]
You can't make that shape with the TFS spread/length. I created a mapping of all the spell shapes that can be made https://github.com/soul4soul/ot-monster-converter/wiki/TFS-Predefined-Spell-Shapes. You need to make a custom spell and define the area manually.
