### ISSUE TITLE
revscript monster summons

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3882]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
`monster.maxSummons = 4`

`monster.summons = {`
`
	{name = "minotaur archer", chance = 13, interval = 2000, max = 2},
`
`
	{name = "minotaur guard", chance = 13, interval = 2000, max = 2}`
`}`

### Expected behaviour
should summon 2 of each monster, total of 4

### Actual behaviour
it don't respect the "max" value, i'm using converted monsters so no idea if "max" actually exist or not, but it should :p

![3](https://user-images.githubusercontent.com/43324808/148111320-4309da6e-cecc-47d4-bbc4-35b61e3845c3.png)

**Comment by marmichalski** [comment]
https://github.com/otland/forgottenserver/blob/73c9c40c0dc4e684d079d7f950b960b11a2c6d4a/data/scripts/lib/register_monster_type.lua#L174-L180
