### ISSUE TITLE
revscript outfit spell

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3884]
### Explanation of what you want to do that is currently impossible

be able to read "monster" and "item", currently target is set to "invisible" instead

https://github.com/otland/forgottenserver/blob/master/data/scripts/lib/register_monster_type.lua#L280-L335
https://github.com/otland/forgottenserver/blob/master/src/monsters.cpp#L707-L717
https://github.com/otland/forgottenserver/blob/master/src/monsters.cpp#L390-L413 - xml reference

{name = "outfit", interval = 2000, chance = 17, **monster = "rabbit"**, duration = 20000, range = 7, target = true, effect = CONST_ME_MAGIC_BLUE}

{name = "outfit", interval = 2000, chance = 1, **item = 3976**, duration = 4000, range = 7, target = true, effect = CONST_ME_MAGIC_BLUE},

**Comment by theshibbies** [comment]
> ### Explanation of what you want to do that is currently impossible
> be able to read "monster" and "item", currently target is set to "invisible" instead
> 
> https://github.com/otland/forgottenserver/blob/master/data/scripts/lib/register_monster_type.lua#L280-L335 https://github.com/otland/forgottenserver/blob/master/src/monsters.cpp#L707-L717 https://github.com/otland/forgottenserver/blob/master/src/monsters.cpp#L390-L413 - xml reference
> 
> {name = "outfit", interval = 2000, chance = 17, **monster = "rabbit"**, duration = 20000, range = 7, target = true, effect = CONST_ME_MAGIC_BLUE}
> 
> {name = "outfit", interval = 2000, chance = 1, **item = 3976**, duration = 4000, range = 7, target = true, effect = CONST_ME_MAGIC_BLUE},

We can add a luaMonsterSpellSetConditionOutfit function and add it into register_monster_type.lua.

However, an issue lies with trying to get a monster types outfit when the file hasn't been loaded yet. For instance, blue djinn has trouble loading rabbit looktypes because the blue djinn file is loaded far before the rabbit. 

Reading the lua files lines via io.open is possible but seems a bit hacky to me, interested to hear others solutions.

**Comment by emil92b** [comment]
that didn't fix it for me, they are still invisible

**Comment by emil92b** [comment]
@theshibbies thanks, that worked for me! you should do a PR mby?

**Comment by Zbizu** [comment]
why don't you just use looktypes?
