### ISSUE TITLE
TFS compatible with old versions

### ISSUE THREAD

**Issue by luanluciano93** [otland/forgottenserver#3887]
### Explanation of what you want to do that is currently impossible
After a brief statistical study of the online otservers list, it's easy to see that 3 or 4 versions predominate today... and that older versions still have a large audience.

Today, for example, if an ot admin wants to open a server 8.60 or less, he only has old engines or new buggy versions.

### Desired functionality
It's just a suggestion: wouldn't it be feasible, by adding a few hundred condition lines, to adapt the current engine to past tibia versions? Wouldn't that increase the number of users and consequently of "testers", being able to find more bugs and the like?

### Available workarounds
Maybe conditions using CLIENT_VERSION_STR

Remembering that this is just a suggestion.

**Comment by gesior** [comment]
I think it's absolutely impossible after decision to go 12+ protocol.
There are too many new features waiting for implementation. It will take years to create them all, if programmers decide to not copy otservbr crap code.

**Comment by marmichalski** [comment]
> [...], if programmers decide to not copy otservbr crap code.

Oh, come on. You have not made enough contributions there to call the whole codebase crap. 👍

**Comment by EPuncker** [comment]
I already suggested that (but only for a few versions, like: 7.72/8.6/10.98) a long time ago, but unless someone actually offer himself to do that and _keep_ it maintained, that is not going to happen... but now I have to agree with gesior, after 12+ protocol it will be too much work...

**Comment by gesior** [comment]
> You have not made enough contributions there to call the whole codebase crap.

I did contributions that fixed few crash reasons. These bugs should be obvious to every OTS programmer. Somehow someone made these codes and '2 reviewers' accepted them.

If anyone decides to copy code from otservbr to TFS, please use Lua version of their systems. They made most of systems (like store, market, prey etc.) in Lua and then for some unknown reason moved it to C++.

**Comment by Znote** [comment]
@nekiro, who is an official TFS dev, has protocol downgrades available. 
I use these on [AcidsOT](https://acidsot.com/?ref=github). 5 months so far and havent had a single crash on production server. (Please [Murphy](https://en.wikipedia.org/wiki/Murphy%27s_law), have mercy on me). 

https://github.com/nekiro/TFS-1.5-Downgrades

# TFS 1.5 Nekiro's Downgrades

This repository holds three TFS 1.5 downgrades.

Keep in mind these downgrades are protocol downgrades.
What it means? It means that it's not fully featured server.
It's a nice base to start working on in desired protocol version.
Datapack is not included.

#### **[7.72](https://github.com/nekiro/TFS-1.4-Downgrades/tree/7.72)**
#### **[8.0](https://github.com/nekiro/TFS-1.4-Downgrades/tree/8.0)**
#### **[8.60](https://github.com/nekiro/TFS-1.4-Downgrades/tree/8.60)**

## Donate
If you like my work and respect my time, you can consider becoming [Github Sponsor](https://github.com/sponsors/nekiro).

**Comment by emil92b** [comment]
unless it's under official otland repository, doubt anyone going to be serious about it

in my opinion each version should have their own repository and if a mechanic or anything would work in any of them just "cherry-pick" and solve any conflict that happens

**Comment by Zbizu** [comment]
I'm pretty sure that 7.7 version is very popular and I've seen them being maintained consistently so I'm pretty sure that people are serious about it.

**Comment by Codinablack** [comment]
I think that we can close this, supporting all the clients and their various features was never the goal of this particular project, and I don't think anyone is willing to put in that much work to see it in this project either.
