### ISSUE TITLE
Some fluids and runes, being used while approaching, work in a wrong way

### ISSUE THREAD

**Issue by waqmaz93** [otland/forgottenserver#3892]
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Place a mana fluid in map editor on the ground 
2. Login to the game and type "/i ultimate healing rune" and place it near the mana fluid
3. Stand at least 2 squares from both mana fluid and ultimate healing rune
4. Try to use it on yourself from the distance

### Expected behaviour
The mana fluid or ultimate healing rune should be used on yourself. The mana fluid should be poured on the floor when player is not a target
![distance usage](https://user-images.githubusercontent.com/45514240/149190087-8d32c01b-bf5e-4489-9aae-4a1c604e9f15.gif)

### Actual behaviour
The mana fluid is being poured on the floor and ultimate healing rune returns cancel message "You can only use it on creatures".
![distance usage tfs](https://user-images.githubusercontent.com/45514240/149190194-29f87bad-a59c-457e-8778-01f43cbfec39.gif)

**Comment by EPuncker** [comment]
rune behavior is correct, I've just checked it on cip tibia and works that way, rune is not used.

since there is no way to check life fluid in rl tibia, I tested with a mana potion, and it worked just fine, it was used in my character

nekiro explained it:

> you can use uh from distance
> on people
> yuo cant use vials from distance
> thats why the behaviour differs
> in case of vial server forces you to move to the position that you choose to use
> it takes the item and walks to it
> with uh it wont take that item
> cause it can use from far away

**Comment by floki21uu** [comment]
this works this way in original 7.7 cipsoft tallbar files. i have just checked. i also remember this mechanism from like 15 years ago, used to play a lot ; p

**Comment by waqmaz93** [comment]
fuck me
it was suppose to be in Nekiro's downgraded one. I dont know why I sent it to otland, lmao, sorry. I was sleepy or what...

**Comment by floki21uu** [comment]
Hello. Does anyone know how to fix this issue? 
It looks like using mana fluid froma distance on yourself doesn't checks for Creature.
Stackpos issue or void Game::playerUseItemEx ?
