### ISSUE TITLE
Game.createMonster is sending CONST_ME_TELEPORT magic effect to monster position when it's should be specified by the script instead

### ISSUE THREAD

**Issue by andremiles1** [otland/forgottenserver#3905]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Call a script that uses the command Game.createMonster alone.

### Expected behaviour
Command Game.createMonster should only create the monster on map without any effect attached to it. Assuming a magic effect together hurts when it's not the case. If there's an occasion where you want to send a magic effect together with creating the monster, script should also include the following command sendMagicEffect(CONST_ME_TELEPORT) to monster's position, for example.
I am stating all of this because there's monsters on real server that are placed on map with no effect, or with other effects instead of the teleportation one.

### Actual behaviour
Watch as the command automatically sends a magic effect CONST_ME_TELEPORT to monster position together as creating the monster.

### Reproduction environment
Example script:
local pos = Position(500, 500, 7)
local monster = Game.createMonster("Rat", pos)
if monster then
	monster:remove()
end

**Comment by EPuncker** [comment]
Game.createMonster calls Game::placeCreature who calls Game::internalPlaceCreature who calls Map::placeCreature which calls ProtocolGame::sendAddCreature

[and there it is](https://github.com/otland/forgottenserver/blob/c21916dd65feae525e4a30728e1cef6fe6b9542f/src/protocolgame.cpp#L2871-L2873):
```
		if (isLogin) {
			sendMagicEffect(pos, CONST_ME_TELEPORT);
		}
```

I'm not sure why it is there, but I agree we should remove it

PS: this one is for monsters/npcs only, the teleport effect for players is bellow
