### ISSUE TITLE
Forgottenserver failed to build for x86 due to error LNK2001: unresolved external symbol _mysql_close with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [otland/forgottenserver#3910]
Hi All,

Environment:
VS 2019 + Windows Server 2019

Forgottenserver failed to build for x86 due to error LNK2001: unresolved external symbol _mysql_close with MSVC on windows. It can be reproduced on latest version e14ab10 on master branch. Could you please help look at this issue?

**Note:** For x64, it can build pass.

**Repro steps:**
For x86:
1. cd F:\gitP\microsoft\vcpkg
2. bootstrap-vcpkg.bat
3. vcpkg install --recurse boost-iostreams boost-asio boost-system boost-filesystem boost-variant boost-lockfree luajit libmariadb pugixml cryptopp fmt --triplet x86-windows --clean-after-build
4. git clone https://github.com/otland/forgottenserver F:\gitP\otland\forgottenserver
5. cd F:\gitP\otland\forgottenserver && mkdir build_x86
6. Block line 76 in CMakeLists.txt and add the absolute path of libmariadb.lib as "F:/gitP/microsoft/vcpkg/installed/x64-windows/lib/libmariadb.lib", otherwise the build cannot find libmariadb.lib
7. cd F:\gitP\otland\forgottenserver\build_x86
8. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows ..
9. msbuild /m /p:Platform=Win32 /p:Configuration=Release /p:PlatformToolset=v142 tfs.sln /t:Rebuild

[build_x86.zip](https://github.com/otland/forgottenserver/files/7940840/build_x86.zip)

**Error info:**
6>database.obj : error LNK2001: unresolved external symbol _mysql_close@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_init@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_options@12 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_real_connect@32 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_error@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_rollback@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_commit@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_real_query@12 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_errno@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_store_result@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_free_result@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_real_escape_string@16 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_fetch_field@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_fetch_row@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>database.obj : error LNK2001: unresolved external symbol _mysql_fetch_lengths@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>luascript.obj : error LNK2001: unresolved external symbol _mysql_insert_id@4 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>otserv.obj : error LNK2001: unresolved external symbol _mysql_get_client_info@0 [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>F:\gitP\otland\forgottenserver\build_x86\Release\tfs.exe : fatal error LNK1120: 17 unresolved externals [F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj]
6>Done Building Project "F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj" (Rebuild target(s)) -- FAILED.
4>Done Building Project "F:\gitP\otland\forgottenserver\build_x86\tfs.vcxproj.metaproj" (Rebuild target(s)) -- FAILED.
1>Done Building Project "F:\gitP\otland\forgottenserver\build_x86\tfs.sln" (Rebuild target(s)) -- FAILED.

**Comment by EPuncker** [comment]
why are you linking 64x libmaria if you are building 86x? that will not gonna work for sure
