### ISSUE TITLE
Item disappears if moved to minimized inventory

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3920]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Equip any container and make all slots full
2. Minimize your inventory by clicking the "-"(minus signal) above the necklace slot
3. Move any item that is not in your container, to the soul/cap square

### Expected behaviour
"you can not put more objects in this container"

### Actual behaviour
item disappears forever

###  GIF
![Animação](https://user-images.githubusercontent.com/4684880/152526387-4e18f8ce-262d-4100-a3f6-cca27fc0103c.gif)

issue originally reported h[ere](https://github.com/nekiro/TFS-1.5-Downgrades/issues/112)

**Comment by Zbizu** [comment]
Interesting. Could you tell me what it prints if you add line below to `Player:onItemMoved`?
`print(toPosition.x, toPosition.y, toPosition.z, toCylinder:getName())`
