### ISSUE TITLE
C++ exception at doors.lua

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#3927]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Start server
2. See error in console
3. Doors not working, but server working fine

### Error
```
\data\scripts\actions\others\doors.lua
C++ exception
> doors.lua [error]
```

### Reproduction environment
I can't test on clean tfs right now, can someone else confirm if this is happening to everyone? windows 10, compiled on release/64x

**Comment by Limmek** [comment]
I can confirm this happen for me to.
