### ISSUE TITLE
Creating item crash client

### ISSUE THREAD

**Issue by ArturKnopik** [otland/forgottenserver#3946]
Create item using /i 2323
`	<item id="2323" article="a" name="hat of the mad">
		<attribute key="description" value="You have a vague feeling that it looks somewhat silly." />
		<attribute key="weight" value="700" />
		<attribute key="armor" value="3" />
		<attribute key="magiclevelpoints" value="3" />
		<attribute key="slotType" value="head" />
	</item>`
Actual behavior - client crash
expected behavior - item created without client crash

Probably this issue can be reproduced by creating other items

**Comment by EPuncker** [comment]
I'm using 12.85.11485 client and downloaded a clean tfs-master and compiled it with release/64x and logged in with my god account and it didn't crash the client in none of the three situations:
- /i 2323 = hat equipped directly to head slot
- /i 2323 = hat went directly to backpack
- /i 2323 = hat created directly on the ground

**Comment by ArturKnopik** [comment]
![image](https://user-images.githubusercontent.com/17506599/154124733-011b86fb-d345-4cd3-b156-c1dcb2add507.png)

**Comment by EPuncker** [comment]
> ![image](https://user-images.githubusercontent.com/17506599/154124733-011b86fb-d345-4cd3-b156-c1dcb2add507.png) i will try latest version

I'm pretty sure it is because items got a new flag (almost all equipment) called "classification" and since you are using a client that doesn't have it, and we use it in both protocolgame and items.otb, your client is crashing because "unknow flag"
