### ISSUE TITLE
Error in script bank.lua

### ISSUE THREAD

**Issue by luanluciano93** [otland/forgottenserver#3951]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. hi, to NPC banker.
2. transfer
3. name that does not exist

### Expected behaviour
reply that the player does not exist

### Actual behaviour
![image](https://user-images.githubusercontent.com/6209529/154373348-7d9ddc0a-7569-4a2a-91bb-b42801b74c05.png)

### Reproduction environment
https://github.com/otland/forgottenserver/blob/master/data/npc/scripts/bank.lua

**Comment by DSpeichert** [comment]
You can paste images in GitHub.

**Comment by EPuncker** [comment]
confirmed, error on both situations:

> 00:12 Banker: Welcome to the bank, Perflex! Need some help with your bank account?
> 00:12 Perflex [1006]: transfer
> 00:12 Banker: Please tell me the amount of gold you would like to transfer.
> 00:12 Perflex [1006]: Luan Luciano

![2022-02-17 00_14_09-The Forgotten Server](https://user-images.githubusercontent.com/4684880/154397966-e49152ef-8b0d-4b95-833a-c039870fc955.png)


> 00:12 Perflex [1006]: transfer
> 00:12 Banker: Please tell me the amount of gold you would like to transfer.
> 00:12 Perflex [1006]: 100
> 00:12 Banker: Who would you like transfer 100 gold to?
> 00:13 Perflex [1006]: Luan Luciano

![2022-02-17 00_14_42-The Forgotten Server](https://user-images.githubusercontent.com/4684880/154398019-1396107a-4081-4c9d-a30a-2b905eba8dd9.png)

_seems like someone didn't test this properly before (yes, that is me hehe)_

**Comment by EPuncker** [comment]
hey @luanluciano93 can you please test https://github.com/otland/forgottenserver/pull/3955 ?

**Comment by luanluciano93** [comment]
Can check that way @Znote? https://pastebin.com/raw/zKNLKi7z
