### ISSUE TITLE
Training statue issue

### ISSUE THREAD

**Issue by lucasgrizante** [otland/forgottenserver#3965]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. in GM character do /i 18488
2. click in that statue with any premium-account character
3. check console error

### Expected behaviour

Training should start without any errors on console

### Actual behaviour

Lua Script Error: [CreatureScript Interface]
data/creaturescripts/scripts/offlinetraining.lua:onLogin
getNumber(). Argument 2 has out-of-range value for j: -1.0
stack traceback:
        [C]: in function 'setOfflineTrainingSkill'
        data/creaturescripts/scripts/offlinetraining.lua:10: in function <data/creaturescripts/scripts/offlinetraining.lua:1>
Draky Ot has logged out.

### Environment

TFS master branch, running in ubuntu 20.04 from Oracle cloud

**Comment by EPuncker** [comment]
confirmed, the error appears once you login on that character
