### ISSUE TITLE
NPCs loading with npcs.xml.

### ISSUE THREAD

**Issue by ghost** [otland/forgottenserver#40]
Hello,

I would like to suggest possibility to spawn NPCs from inside the npcs.xml file.
An example of it would be the following:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<npcs>
    <npc name="Ahmet" file="Ahmet.xml" home="33126,32810,6" radius="2" />
</npcs>
```

home = spawn position
radius = walk radius

Thanks.
##

**Comment by Zbizu** [comment]
I think that's redundant considering we're moving towards revscriptsys direction in which we can just spawn npcs through Game.createNpc(...)

**Comment by Zawodowiec1532** [comment]
7 years later xD

**Comment by Zbizu** [comment]
I'm looking through old issues to see what can be closed

**Comment by EPuncker** [comment]
I don't like it either, see no problem with the current spawning system on the spawn.xml file, also we would need to edit RME in order to make it work with this change
