### ISSUE TITLE
 still can't buy anything from npc. but now there are no bugs in the console

### ISSUE THREAD

**Issue by daniofordon** [otland/forgottenserver#4006]
tfs 1.5
otclient meh 12.81

I updated tfs 1.5. still can't buy anything from npc. but now there are no bugs in the console

https://prnt.sc/MpRhlqBNuP6w

**Comment by nekiro** [comment]
Probably client issue

**Comment by DSpeichert** [comment]
Is it same as #4031?

**Comment by EPuncker** [comment]
> Is it same as #4031?

no, here he can talk to npc, its a different issue

since the screenshot is in polish i can't read what that npc window says 😄 but seems like it is not recognizing player money or cap

seems to be an OTC problem, its working fine on QT client

**Comment by DSpeichert** [comment]
Closing as OTC issue then.
