### ISSUE TITLE
The file 'tfs-v1.4.1-windows-msvc-Release-luajit.zip' is corrupted.

### ISSUE THREAD

**Issue by bruamado** [otland/forgottenserver#4021]
The last release (tfs-v.1.4.1) for **windows** is corrupted. It can't be extracted.

`! D:\Users\Bruno\Downloads\tfs-v1.4.1-windows-msvc-Release-luajit.zip: The archive is corrupt`

The problem seems to be **data\items\items.xml**.

**Comment by EPuncker** [comment]
I can confirm this.
