### ISSUE TITLE
after recent updates, npc does not respond to hi

### ISSUE THREAD

**Issue by daniofordon** [otland/forgottenserver#4031]
after recent updates, npc does not respond to hi

tfs 1.5
otclient 12.81

no errors in the tfs console or otclient

**Comment by EPuncker** [comment]
latest tfs master I just compiled:

![2022-03-20 17_24_18-Tibia - Perflex](https://user-images.githubusercontent.com/4684880/159184586-9c398fe2-50b4-4cff-bc59-7fb1b888755b.png)

**Comment by daniofordon** [comment]
I updated otclient to version 12.85 but it still doesn't work. after typing hi npc he turns towards me and nothing

This started happening after maybe the last two updates to tfs 1.5

**Comment by ranisalt** [comment]
Please use the issue template.

**Comment by Zbizu** [comment]
the bug can only be reproduced for first NPC placed on the map, I've pushed a PR with a fix

**Comment by daniofordon** [comment]
this update does not fix the error please open :)

**Comment by Zbizu** [comment]
mb

the commit I pushed fixed a different bug though

**Comment by ArturKnopik** [comment]
in my custom project after cherry-pick commits from master(nothing new from my side) i have same issue, i thing addevent is problem here becouse spells(custom) with addevent stop working to (addevent callback never called)

**Comment by ranisalt** [comment]
@ArturKnopik in this case, you should be able to `git bisect` and find the exact commit that causes this issue, that would be very helpful

**Comment by ArturKnopik** [comment]
Hello @daniofordon, can you try revert  92b35aa3ebe3660aaebdf2ea17df8f35f776350c "Replace std::bind with lambdas" (https://github.com/otland/forgottenserver/pull/4017) and test?
In my case it solve my problem :)
