### ISSUE TITLE
lua "print" gets stuck until std::cout is called (linux terminal / git bash)

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#4045]
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Summary
Lua `print` output is not visible (windows git bash / linux terminal) until c++ output (eg. `std::cout`) updates the console
this might be useful: https://stackoverflow.com/questions/15787892/embedded-lua-does-not-print-to-allocated-console

### Steps to reproduce
1. compile
2. run in linux terminal or windows git bash 
3. print from lua
4. check console
5. log in/out

### Expected behaviour
print output shows instantly like in cmd and powershell

### Actual behaviour
print output is not visible until non-lua output (eg. std::cout) is called

### Environment
I got this problem in git bash, but another user in discord mentioned that he's facing that issue in linux also

### Reproduction environment
I managed to reproduce it on master branch at commit 4038

example script (!test):
```lua
local talk = TalkAction("!test")
local t = {}

function talk.onSay(player, words, param)
    t[#t + 1] = #t
    print(#t)
    return false
end

talk:register()
```

**Comment by Zbizu** [comment]
A potential fix could be redirecting `stdout` to a custom stream that would be calling `std::cout`, unfortunately I don't know how to modify `_G.io.stdout` from within the sources

here are the sources of various Lua io libs if it helps:
https://www.lua.org/source/5.1/liolib.c.html
https://www.lua.org/source/5.2/liolib.c.html
https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/lib_io.c

**Comment by Zbizu** [comment]
update: https://github.com/Zbizu/forgottenserver/commit/3dbc562ddf99953232726c695be43fb7e651c5c9 this seems to do the trick, though I'm not sure whether using an ugly workaround (adding code around default Lua functions) is necessary or if calling `std::flush` constantly doesn't have some unknown consequences.

**Comment by amatria** [comment]
This is the expected behaviour of any buffered I/O stream such as `stdout`... Use `io.flush()` next time
