### ISSUE TITLE
Login problem with 12.85 protocol

### ISSUE THREAD

**Issue by joeyintax** [otland/forgottenserver#4054]
I hate to have to create an issue for that, but all the issues related to the protocol were using ZnoteAAC. I used to develop to older versions and decided to develop to the newest versions, but the login simply isn't working.

Infos:
Running on a local server;
No PHP server at all;
Using the latest commits;
Using mehah's forked client;
Trying to login with 12.85 version;
Login doesn't even connect, I debugged the whole process with breakpoints using a 10.97 version and a 12.85 version and the first managed to login, the latter sent header infos and times out after that.

Every configuration is set to 127.0.0.1. I tried two clients, Canary's 12.85.11525 client and Mehah's, both times out after sending the header info.

Considering it is not even attempting a connection through 7171, I'm assuming a PHP connection is needed for newest protocols? If that is the case and one is supposed to setup ZnoteAAC or similars for local connections, may somebody point that out? Or am I missing/mixing something?

**Comment by EPuncker** [comment]
yes you do need a login.php to connect

or modify otc to support legacy login as zbizu did:
https://github.com/Zbizu/otclient/commit/4a035f5ef915d411efe18426f2ac7538f9e5eec7

**Comment by joeyintax** [comment]
Gosh, I can't believe I actually debugged it for hours while I only needed to change some lines xD
Thanks a lot EP!
