### ISSUE TITLE
[discussion] MOTD is gone from client

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#4056]
Remember that message of the day that used to be displayed before getting to the char select window?

It's gone on QT client, and replaced with this:
![2022-04-01 01_17_21-](https://user-images.githubusercontent.com/4684880/161194152-f703c866-0df8-401a-90a3-622243266212.png)

And it doesn't receive any info from server side (unless we add HTTP API).

What should we do with the [leftover code TFS-side](https://github.com/otland/forgottenserver/search?q=motd)?

**Comment by Zbizu** [comment]
Normal motd used to be sent with the character list. However, the parameter is either not known or not present in the web login way of getting the character list. Currently only way to "read" the motd is to login with otc using legacy login method.

Regarding guild motd, it is still in use. There's an ui for guild leader to edit it, though I don't know what triggers enabling that option in chatchannel context menu.

**Comment by omarcopires** [comment]
There is no reason to keep any legacy client content in the master branch, we should only keep clientQT content.

**Comment by Zbizu** [comment]
protocolstatus can return "N/A" string
