### ISSUE TITLE
WeaponType revscript register multiple IDs

### ISSUE THREAD

**Issue by C-aptC-arl** [otland/forgottenserver#4075]
From the documentation: https://github.com/otland/forgottenserver/wiki/Revscriptsys#weaponweapon_type

It doesn't appear that the documentation suggests that multiple IDs can be registered to 1 revscript, however, this does appear to be available on other revscript types.

Additionally, in case this is simply a documentation error and it is expected for multiple IDs to work within a weaponType revscript, then this should be considered a bug (as I have tested this numerous times to confirm that only the first ID within weapon:id(id1, id2, id3...) is used)

Thanks in advance for your consideration.

**Comment by Codinablack** [comment]
onUseWeapon only supports registering one id. 

Please close.
