### ISSUE TITLE
monster:onSpawn creature id is 0

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#4077]
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce
1. create a script:
```
	local ec = EventCallback
	ec.onSpawn = function(self, position, startup, artificial)
		print(self:getId())
		return true
	end
	ec:register()
```
2, start the server

### Expected behaviour
output: monster id

### Actual behaviour
output: 0
note: monster methods work normally, but this could break a script that would rely on monster id

**Comment by MillhioreBT** [comment]
I'm thinking about doing it these days, I've tried to do it in this PR #3984 but I don't really like how it was written

**Comment by Zbizu** [comment]
@MillhioreBT
I called `setID` in the event method right before calling the script.
There's probably a more elegant way to manage that, but I don't really want to risk breaking anything.
