### ISSUE TITLE
House Window showing house price

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#4080]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Description

- RME automatically assigns door ids to every house door and window
- TFS doesn't care if windows and doors are different
- When you "look" at any house window it will show house price description, which is confusing

### Possible solution
Make isDoor function ignore windows (I don't know why windows are threated as doors by RME in the first place)

**Comment by Zbizu** [comment]
weird because the code seems to be correct
https://github.com/otland/forgottenserver/blob/412950218c5e01062a5e2458d363802a5cea3115/data/lib/core/item.lua#L563

could be otb issue

**Comment by Feeltz** [comment]
If you put door ID to 0 on window in RME, then widow stops showing price.
