### ISSUE TITLE
Add table.maxn to compat.lua

### ISSUE THREAD

**Issue by EPuncker** [otland/forgottenserver#4109]
Just a reminder to add it to compat.lua as it was deprecated in lua 5.2

something like `table.maxn = table.maxn or function(t) return #t end` should do the trick

and yes, it is used in several datapacks npcs

**Comment by marmichalski** [comment]
That's not how table.maxn works, but would probably be enough as an alternative in how it is/was used in this project.

**Comment by EPuncker** [comment]
> That's not how table.maxn works, but would probably be enough as an alternative in how it is/was used in this project.

that is why I opened an issue and not a PR 😃 so someone can actually add the correct stuff

**Comment by marmichalski** [comment]
try this:
```lua
function table.maxn(table)
  if type(table) ~= "table" then
    error(("bad argument #1 to 'table.maxn' (table expected, got %s)"):format(type(table)))
  end

  local maxn = 0
  for k, _ in pairs(table) do
    maxn = k > maxn and k or maxn
  end

  return maxn
end
```
