### ISSUE TITLE
unable to read some books

### ISSUE THREAD

**Issue by torresmon** [otland/forgottenserver#4133]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Writing on some books.
- ex: book Id 1977
3. Using the transformed, readable version of that book.
- ex: book Id 1962 ( 1977 written transformation )

### Expected behaviour

Window with read-olny text
### Actual behaviour

Nothing happens

**Comment by nekiro** [comment]
Not a bug, but matter of configuration, its related to missing attributes.
