### ISSUE TITLE
OTClient log files points that does not understand many of the TFS messages - OTClient tells user to wait connection and log points many errors

### ISSUE THREAD

**Issue by alcuard86** [otland/forgottenserver#4157]
I compiled the last versions from TFS and from the OTClient, but it seems that these versions are not compatible as the client does not understands or do not agree with some messages the server sends. The log file I have got on my OTC application is on the link bellow. 

[Log File](https://www.mediafire.com/file/jaazctwo99vftjf/otclient.log/file)

The player table information I am using is set bellow

accounts table:

`2 | pedro | 40bd001563085fc35165329ea1ff5c5ecbdbbeef | NULL | 1 | 0 | pedro@ravendawn.com | 0`

players table (only player name and player id are not default):

`2 | pedro_player | 1 | 2 | 1 | 0 | 150 | 150 | 0 | 0 | 0 | 0 | 0 | 136 | 0 | 0 | 0 | 0 | 0 | 0 | 2 | 0 | 0 | 0 | 0 | 0 | 1 | 95 | 117 | 7 |   | 400 | 0 | 1654727110 | 16777343 | 1 | 0 | 0 | 1654728135 | 0 | 1634 | 0 | 0 | 43200 | -1 | 2520 | 10 | 0 | 10 | 0 | 10 | 0 | 10 | 0 | 10 | 0 | 10 | 0 | 10 | 0 `

On the client GUI it says that I have to wait for the connection and in the server terminal, the system says the player is logged in. 

There are many errors and there is no clue of how they can fixed on the forum. 2

**Comment by EPuncker** [comment]
What OTC exactly are you using? edubarts? otlands? mehahs? otcv8?

tfs master is only compatible with [mehah's](https://github.com/mehah/otclient) and cip client for now

**Comment by alcuard86** [comment]
> What OTC exactly are you using? edubarts? otlands? mehahs? otcv8?
> 
> tfs master is only compatible with [mehah's](https://github.com/mehah/otclient) and cip client for now

edubarts

**Comment by EPuncker** [comment]
> > What OTC exactly are you using? edubarts? otlands? mehahs? otcv8?
> > tfs master is only compatible with [mehah's](https://github.com/mehah/otclient) and cip client for now
> 
> edubarts - i am using the last version.

for edubarts you must use tfs 1.4.1 or earlier, or use mehah's OTC as edubarts development is inactive (when it comes to supporting new client version)

**Comment by alcuard86** [comment]
> > > What OTC exactly are you using? edubarts? otlands? mehahs? otcv8?
> > > tfs master is only compatible with [mehah's](https://github.com/mehah/otclient) and cip client for now
> > 
> > 
> > edubarts - i am using the last version.
> 
> for edubarts you must use tfs 1.4.1 or earlier, or use mehah's OTC as edubarts development is inactive (when it comes to supporting new client version)

Ok... thanks... I am going to try it.

**Comment by alcuard86** [comment]
> > > What OTC exactly are you using? edubarts? otlands? mehahs? otcv8?
> > > tfs master is only compatible with [mehah's](https://github.com/mehah/otclient) and cip client for now
> > 
> > 
> > edubarts - i am using the last version.
> 
> for edubarts you must use tfs 1.4.1 or earlier, or use mehah's OTC as edubarts development is inactive (when it comes to supporting new client version)

In TFS page you guys are pointing to eubarts OTC... You should change it once it is not updated.

**Comment by alcuard86** [comment]
> > > What OTC exactly are you using? edubarts? otlands? mehahs? otcv8?
> > > tfs master is only compatible with [mehah's](https://github.com/mehah/otclient) and cip client for now
> > 
> > 
> > edubarts - i am using the last version.
> 
> for edubarts you must use tfs 1.4.1 or earlier, or use mehah's OTC as edubarts development is inactive (when it comes to supporting new client version)

I compiled mehah´s last version. The game does not start either. It says for me to wait for the connection to the server. The server says the player is logged. 

The game does not start. It keeps telling me to hang while it connects to the server in the gui. 

Client log file:


[Log file](https://www.mediafire.com/file/4q325n5bohfknfh/otclient.log/file)

Some errors I get:


Startup done :]
Unable to translate: "Hotkey delay: %sms"
Unable to translate: "Turn delay: %sms"
Unable to translate: "You have %s hours and %s minutes left"
Unable to translate: "You don't may receive experience and loot from monsters"
ERROR: ProtocolGame parse message exception (4806 bytes unread, last opcode is 0, prev opcode is 160): unhandled opcode 0
ERROR: ProtocolGame parse message exception (2 bytes unread, last opcode is 239, prev opcode is -1): unhandled opcode 239
ERROR: ProtocolGame parse message exception (2 bytes unread, last opcode is 239, prev opcode is -1): unhandled opcode 239
ERROR: ProtocolGame parse message exception (2 bytes unread, last opcode is 239, prev opcode is -1): unhandled opcode 239

**Comment by alcuard86** [comment]
> > > What OTC exactly are you using? edubarts? otlands? mehahs? otcv8?
> > > tfs master is only compatible with [mehah's](https://github.com/mehah/otclient) and cip client for now
> > 
> > 
> > edubarts - i am using the last version.
> 
> for edubarts you must use tfs 1.4.1 or earlier, or use mehah's OTC as edubarts development is inactive (when it comes to supporting new client version)

**I have got sprints and dat files from this site: https://otland.net/threads/downgraded-12-x-assets-to-dat-spr-format.273902/ 

Pehaps it is not appropiate?! If it is not, please send me good spr and dat files =);
