### ISSUE TITLE
Question about house warnings.

### ISSUE THREAD

**Issue by Emilianenko** [otland/forgottenserver#4183]
I was looking at the house.cpp file and find out that you get warnings when you don't pay the rent,and its ok.My question is, shouldn't the warnings be removed after paying the rent?(They are never removed as it is now)
Is this the correct behavior?

**Comment by EPuncker** [comment]
yes that is correct behavior, warnings are letters and they are a sort of "physical record", thus they are not deleted.

ps: that is also how cip tibia works and that is why it was coded like this years ago

**Comment by Emilianenko** [comment]
I pointed this cause with 7 warnings you lose your house.For example in this hypothetical situation: if you didn't pay for 6 days and then you pay the rent ,you will keep 6 warnings.If you delay the payment of the next rent for 1 day you will lose the house.

**Comment by EPuncker** [comment]
oh okay, now I totally get it, and indeed you have a point, perhaps we need to add `house->setPayRentWarnings(0);` [here](https://github.com/otland/forgottenserver/blob/master/src/house.cpp#L665) if it is not reset anywhere else, but I'll leave this to someone else to check, thank you for your report

**Comment by EPuncker** [comment]
@Emilianenko can you check if https://github.com/otland/forgottenserver/pull/4185/files fix the issue?

**Comment by Emilianenko** [comment]
> @Emilianenko can you check if https://github.com/otland/forgottenserver/pull/4185/files fix the issue?

Now the warnings are being reset after paying the rent,so its working fine =)
