### ISSUE TITLE
forgottenserver failed due to error LNK1181 on MSVC

### ISSUE THREAD

**Issue by nnfdnkns** [otland/forgottenserver#4192]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository
**error message: ** 
6>LINK : fatal error LNK1181: cannot open input file 'libmariadb.lib' [F:\gitP\otland\forgottenserver\build_amd64\tfs.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'libmariadb.lib' [F:\gitP\otland\forgottenserver\build_amd64\tfs.vcxproj]
Detail log:
[build.log](https://github.com/otland/forgottenserver/files/9307925/build.log)

### Steps to reproduce (include any configuration/script required to reproduce)
1.git clone https://github.com/otland/forgottenserver F:\gitP\otland\forgottenserver
2.cd F:\gitP\Microsoft\vcpkg
3.bootstrap-vcpkg.bat
4.vcpkg.exe install --recurse boost-iostreams boost-asio boost-system boost-filesystem boost-variant boost-lockfree luajit libmariadb pugixml cryptopp fmt --triplet x64-windows --clean-after-build
5. mkdir build_amd64 & cd F:\gitP\otland\forgottenserver\build_amd64
6. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
7. cd F:\gitP\otland\forgottenserver\build_amd64
8. msbuild /m /p:Platform=x64 /p:Configuration=Release /p:PlatformToolset=v142 tfs.sln /t:Rebuild 2>&1

### Expected behaviour

build successfully.
### Actual behaviour

cannot open input file 'libmariadb.lib' [F:\gitP\otland\forgottenserver\build_amd64\tfs.vcxproj]
so build failed
### Environment

Windows: windows server 2019
### Reproduction environment

VS: 2019

**Comment by soul4soul** [comment]
Did you install the libs with vcpkg? https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29#4-install-libraries

**Comment by nnfdnkns** [comment]
Yes, please take a look at my re-updated steps to reproduce, Thanks!
