### ISSUE TITLE
casting spells over night does not lighten the ground

### ISSUE THREAD

**Issue by waqmaz93** [otland/forgottenserver#4198]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Find this line of code:
`		static constexpr uint8_t LIGHT_DAY = 250;
`
2. Change number 250 to 40 so it will be always night in the game, and compile.
3. Make sure you are not in a dungeon, it means you are on floor nr 7 (the main floor)
4. Cast for example exevo mort hur

### Actual behaviour

on floor 7 doesnt work, gif:
![exevo mort hur 7 6](https://user-images.githubusercontent.com/45514240/185810363-5aa80e5d-adf3-4b22-a302-64442f7373a4.gif)
under ground, floor 7+ works, gif:
![exevo mort hur dungeon](https://user-images.githubusercontent.com/45514240/185810412-ea0ba8b6-979b-48dd-a02b-062862cb21bc.gif)

**Comment by EPuncker** [comment]
just tested on tfs master at floor 7 with cip client:

![asdasd](https://user-images.githubusercontent.com/4684880/185813636-9878fff6-d915-4b98-8036-793364dc818a.gif)


it is working just fine, perhaps you are using OTC? if so, that is not tfs side issue

**Comment by Zbizu** [comment]
there is no code that would link magic effects with light

the light from magic effects is purely client sided
