### ISSUE TITLE
Absorb damage calculation (maybe reflect too)

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#4200]
### Steps to reproduce
1. Equip 3 items with 10% fire absorb
2. Get 1000 damage hit by fire

### Expected behaviour
700 damage = 1000 - 1000 * 0.3 (30%)

### Actual behaviour
729 damage = 1000 - (1000 * 0.1) - (900 * 0.1) - (810 * 0.1)

It removes damage percent for each item one after another and uses 'current damage' in calculations:
https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L2068-L2076

There are 2 ways to fix this:
- calculate 'total percent reduction' in `for` loop and then calculate damage
- add variable `originalDamage = damage` above `for` loop and use it in absorb calculations

**Can anyone confirm that it's a bug?**
I don't know how it works on real tibia. Maybe TFS just replicates dumb RL Tibia code, but someone reported it to me as bug on his OTS.

**Other possible bug:**
Reflect damage is calculated as percent of damage after absorb. Example:
Player has 50% absorb and 50% reflect. After getting 1000 damage hit, he will lose 500 damage and reflect 250. Should he reflect 250 or 500, as 500 is 50% of 1000 damage?

**Comment by marmichalski** [comment]
Percent damage reduction does not stack in tibia.

**Comment by gesior** [comment]
> Percent damage reduction does not stack in tibia.

I don't understand what you mean.

If player wears [-4% ice]:
https://tibia.fandom.com/wiki/Glacier_Mask
and [-8% ice]:
https://tibia.fandom.com/wiki/Glacier_Robe

How much of 1000 ice damage he should get?

**Comment by marmichalski** [comment]
See https://tibia.fandom.com/wiki/Blocking_Set for example
