### ISSUE TITLE
Clicking Use in the middle of fire bomb fields causes running into the fields

### ISSUE THREAD

**Issue by floki21uu** [otland/forgottenserver#4210]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
Throw fire bomb rune, then right click onto the middle field and choose "use" from the menu. The player will walk onto the fire field.
GIF:
![fire field gif forgotten](https://user-images.githubusercontent.com/96269029/191362443-67a2b35d-af69-4b72-b7ac-8c61181a8bed.gif)

GIF:

### Expected behaviour
Player does not walk onto the fire field, "Sorry not possible." message appears instead.
GIF:
![fire field gif real](https://user-images.githubusercontent.com/96269029/191363284-e5de2d10-c4df-4b40-a278-290e75f516bb.gif)

**Comment by EPuncker** [comment]
can you check if https://github.com/otland/forgottenserver/pull/4213 works?
