### ISSUE TITLE
Wrong order of 'combatType' effects and 'impactEffect' effects resulting animations  appearing the other way around

### ISSUE THREAD

**Issue by floki21uu** [otland/forgottenserver#4211]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. For example casting 'Exori Vis' spell displays an electric shock effect under teleport effect. It should display electric shock effect on top of teleport effect instead.
3. The same thing applies to all other effects including blockhit, blockarmor, bloodhit, poff etc.
GIF:
![exori vis](https://user-images.githubusercontent.com/96269029/191371049-ed4dbcdd-814b-4120-89a8-760f85b0d5b7.gif)

All I have noticed is that an impactEffect is responsible for spell animations like mentioned teleport effect.
I think we should start looking to fix the problem in: `void Combat::doCombat(Creature* caster, Creature* target) const`

The bug was mentioned also here: 
https://github.com/nekiro/TFS-1.5-Downgrades/issues/121

**Comment by Zbizu** [comment]
seems to be correct order
samples:
![obraz](https://user-images.githubusercontent.com/5205079/191378320-2aa3fa84-ec67-49fe-a65a-8ad2b9fa563a.png)
![obraz](https://user-images.githubusercontent.com/5205079/191378348-d46acaac-0f85-4894-a566-bb6c3d5501dd.png)
![obraz](https://user-images.githubusercontent.com/5205079/191378546-58fb4ef1-8ae2-41e5-8725-0a21ec4bb724.png)

**Comment by floki21uu** [comment]
> seems to be correct order samples: ![obraz](https://user-images.githubusercontent.com/5205079/191378320-2aa3fa84-ec67-49fe-a65a-8ad2b9fa563a.png) ![obraz](https://user-images.githubusercontent.com/5205079/191378348-d46acaac-0f85-4894-a566-bb6c3d5501dd.png) ![obraz](https://user-images.githubusercontent.com/5205079/191378546-58fb4ef1-8ae2-41e5-8725-0a21ec4bb724.png)

Strange. I use Nekiro 1.5 theforgottenserver downgraded version without any main changes to the code and this is what I get: 
![bbbbbbbbbbbbb](https://user-images.githubusercontent.com/96269029/191388896-8343fafe-1963-44ea-896a-a6df41d58e9d.png)

Could you check block effects? Just spam demons around you "/m demon"

**Comment by Zbizu** [comment]
![obraz](https://user-images.githubusercontent.com/5205079/191396581-33863e62-2fa8-41aa-8cbc-79ea6664d532.png)
block effect is below my gfb on dragon

**Comment by emil92b** [comment]
@floki21uu 
was gonna do a PR but apparently project is discontinued, anyway here is tmp fix for area spell visual order
<https://github.com/emil92b/TFS-1.5-Downgrades/commit/773dee4a912be90ad7993033333a26f0e1cfbe98>

also fix for energy strike effect + text color
https://github.com/emil92b/TFS-1.5-Downgrades/commit/ed6b03d37d6698ad1ac3caf64d3ed7ae5acf16c5

**Comment by floki21uu** [comment]
> @floki21uu was gonna do a PR but apparently project is discontinued, anyway here is tmp fix for area spell visual order [emil92b/TFS-1.5-Downgrades@773dee4](https://github.com/emil92b/TFS-1.5-Downgrades/commit/773dee4a912be90ad7993033333a26f0e1cfbe98)
> 
> also fix for energy strike effect + text color [emil92b/TFS-1.5-Downgrades@ed6b03d](https://github.com/emil92b/TFS-1.5-Downgrades/commit/ed6b03d37d6698ad1ac3caf64d3ed7ae5acf16c5)
> 
> ![123](https://user-images.githubusercontent.com/43324808/191636825-c6058ac7-25e7-40f2-bbea-9b8f2ecd0c72.png)

Great. I'll make a PR with configurable in config.lua for backward compatybility

**Comment by EPuncker** [comment]
so is this a real bug or something from a specific client version?

**Comment by floki21uu** [comment]
> so is this a real bug or something from a specific client version?

Looks like Cipsoft changed displaying animation the other way arond in Tibia version +- 10.00 so the bug is invalid. It is althought backward compatybility for earlier versions
