### ISSUE TITLE
Forgottenserver failed to build with "error LNK2001: unresolved external symbol __std_find_trivial_1 (EC Symbol)" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [otland/forgottenserver#4228]
Forgottenserver failed to build with "error LNK2001: unresolved external symbol __std_find_trivial_1 (EC Symbol)" with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?
**Versions and configuration**
OS: Windows Server 2022 Datacenter
VS: Visual Studio 2019(16.11.20)

**Repro steps:**
1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. git clone https://github.com/otland/forgottenserve  F:\forgottenserver
3. cd f:\vcpkg
4. bootstrap-vcpkg.bat 
5. vcpkg.exe install --recurse boost-iostreams boost-asio boost-system boost-filesystem boost-variant boost-lockfree luajit libmariadb pugixml cryptopp fmt --triplet x64-windows --clean-after-build 
6. cd F:\forgottenserver
7. mkdir build_arm64ec && cd build_arm64ec
8. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DMARIADB_LIBRARIES=F:/vcpkg/installed/x64-windows/lib/libmariadb.lib  -DCMAKE_TOOLCHAIN_FILE=F:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows .. 
9. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release /p:PlatformToolset=v142 tfs.sln /t:Rebuild 

**Error info:**
```
     6>cryptopp-static.lib(oaep.cpp.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1 (EC Symbol) [F:\forgottenserver\build_arm64ec\tfs.vcxproj]
     6>LINK : error LNK2001: unresolved external symbol #__std_find_trivial_1 (EC Symbol) [F:\forgottenserver\build_arm64ec\tfs.vcxproj]
     6>F:\forgottenserver\build_arm64ec\Release\tfs.exe : fatal error LNK1120: 2 unresolved externals [F:\forgottenserver\build_arm64ec\tfs.vcxproj]
```
**Error log:**
[forgottenserver_build.log](https://github.com/otland/forgottenserver/files/9796232/forgottenserver_build.log)

**Comment by Oen44** [comment]
Update vcpkg to latest, they fixed it today.
```
git pull
vcpkg upgrade --no-dry-run
./bootstrap-vcpkg.bat
```
