### ISSUE TITLE
"not walkable" error when trying to hang things on wall

### ISSUE THREAD

**Issue by ramon-bernardo** [otland/forgottenserver#4251]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Try hang items in diagonally, from far away
2. Try to move hang items from wall, being 1 sqm away.

### Expected behaviour
[](https://user-images.githubusercontent.com/53269692/200188560-14763e18-05b0-4ce5-8ed8-2f912f81d255.mp4)

### Actual behaviour
https://user-images.githubusercontent.com/53269692/200188508-a6914911-7254-455f-aea4-2948c980cc96.mp4

https://user-images.githubusercontent.com/53269692/200188590-4d3eb409-a908-4aa1-a265-cea73d4d73c7.mp4

**Comment by floki21uu** [comment]
the same issue with filling an empty vial with a drop of water from a well from distance. cant be poured out on te ground by some angle
