### ISSUE TITLE
monster atk direction update

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#4255]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. make monster change direction by walking from one side to the other
2. watch it switch two times when it should only switch once

### Expected behaviour
https://user-images.githubusercontent.com/43324808/203817025-ba585909-4f81-49bb-8974-2782c04c393c.mp4

### Actual behaviour
https://user-images.githubusercontent.com/43324808/203818611-fb14a552-3aa1-4fb0-b33e-3cee4490824e.mp4

**Comment by EPuncker** [comment]
this is related to that issue tfs have about monsters being "dumb"

**Comment by Cesar525** [comment]
The expected behavior seems to just have a delay in compare to the tfs.

**Comment by floki21uu** [comment]
the fix is easy
`void Monster::updateLookDirection()
{
	Direction newDir = getDirection();
	if (attackedCreature) {
		const Position& pos = getPosition();
		const Position& attackedCreaturePos = attackedCreature->getPosition();
		int_fast32_t minotaur_x = Position::getOffsetX(attackedCreaturePos, pos);
		int_fast32_t minotaur_y = Position::getOffsetY(attackedCreaturePos, pos);

		int32_t dx = std::abs(minotaur_x);
		int32_t dy = std::abs(minotaur_y);

		if (dx > dy) 
		{
			if (minotaur_x < 0) {
				newDir = DIRECTION_WEST;
			} else {
				newDir = DIRECTION_EAST;
			}
		} 
		else if (dx < dy)
		{
			if (minotaur_y < 0) {
				newDir = DIRECTION_NORTH;
			} else {
				newDir = DIRECTION_SOUTH;
			}
		} 
		else 
		{
			Direction dir = getDirection();

			if (minotaur_x < 0 && minotaur_y < 0) 
			{
				if (dir == DIRECTION_SOUTH)
				{
					newDir = DIRECTION_WEST;
				} 
				else if (dir == DIRECTION_NORTH)
				{
					newDir = DIRECTION_WEST;
				} 
				else if (dir == DIRECTION_EAST)
				{
					newDir = DIRECTION_WEST;
				}
			} 
			else if (minotaur_x < 0 && minotaur_y > 0)
			{
				if (dir == DIRECTION_NORTH || dir == DIRECTION_SOUTH)
				{
					newDir = DIRECTION_WEST;
				}
				else if (dir == DIRECTION_EAST) 
				{
					newDir = DIRECTION_WEST;
				}
			}
			else if (minotaur_x > 0 && minotaur_y < 0) 
			{
				if (dir == DIRECTION_NORTH || dir == DIRECTION_SOUTH)
				{
					newDir = DIRECTION_EAST;
				} 
				else if (dir == DIRECTION_WEST)
				{
					newDir = DIRECTION_EAST;
				}
			}
			else
			{
				if (dir == DIRECTION_NORTH || dir == DIRECTION_SOUTH) 
				{
					newDir = DIRECTION_EAST;
				} 
				else if (dir == DIRECTION_WEST)
				{
					newDir = DIRECTION_EAST;
				}
			}
		}
	}
	g_game.internalCreatureTurn(this, newDir);
}`

**Comment by emil92b** [comment]
> the fix is easy. change the whole void to: you can make the code even nicer by removing few useless if statements.

did you test this code after your changes?

**Comment by floki21uu** [comment]
been using it for a year now

**Comment by floki21uu** [comment]
> > the fix is easy. change the whole void to: you can make the code even nicer by removing few useless if statements.
> 
> did you test this code after your changes?

been using it for a year now
