### ISSUE TITLE
Slowly dying monster (one by one instead of all together)

### ISSUE THREAD

**Issue by floki21uu** [otland/forgottenserver#4257]
![slowly](https://user-images.githubusercontent.com/96269029/205464053-9d291881-11f5-4576-b2c9-87cdfaa310fe.gif)
The problem and video has been mentioned here aswell: https://otland.net/threads/slowly-dying-monsters-othire-0-0-3-solved.252246/

Monster do not die in the same time when killed by AOE spells but one by one.
It is due to event and for loop.
In real Tibia they all die instantly.
wrong directory. i wanted to add it for older versions like 7.6, 7.4 because now in TFS creatures die instantly

**Comment by EPuncker** [comment]
not an issue with tfs master
