### ISSUE TITLE
Yellow fire field on no-pvp damge player after re login 

### ISSUE THREAD

**Issue by Infolinia** [otland/forgottenserver#4269]
I'm throwing fire field in no-pvp zone create on remere map editor. It doesn't take away my health.  I'm going into the deposit. Logs out of the game. He logs in again. Yellow fire field takes away my health.

**Comment by EPuncker** [comment]
@nekiro can you check it whenever you feel like doing so? thank you

**Comment by Infolinia** [comment]
Hey, I added a video showing the bug.
[https://youtu.be/GYZW3RXAs0c](url)

**Comment by Infolinia** [comment]
Xcx has logged in.
Create yellow fire field in non pvp zone.
[ownerId]: 268435456
[owner]: 0x7f20d7e69b70
[owner->getPlayer()]: 0x7f20d7e69b70
[harmfulField]: 0
Xcx has logged out.
Xcx has logged in.
[ownerId]: 268435456
[owner]: 0
[harmfulField]: 1

I thing Creature* owner = g_game.getCreatureByID(ownerId); return 0 after relogin. Please help me. :)

**Comment by Infolinia** [comment]
@EPuncker Please check this bug. :)
