### ISSUE TITLE
look me 

### ISSUE THREAD

**Issue by daniofordon** [otland/forgottenserver#4274]
tfs 12.86 and otclient meh 12.86

look character

https://prnt.sc/IzzCkB6Pcroe

**Comment by EPuncker** [comment]
@ranisalt can you check this please? seems to be related to that ip commit

**Comment by ranisalt** [comment]
I can't open the image, can you post it directly to Github?

**Comment by EPuncker** [comment]
> I can't open the image, can you post it directly to Github?

![image](https://user-images.githubusercontent.com/4684880/208420678-2bbb4a28-3377-4554-a102-0637091c7f26.png)

**Comment by daniofordon** [comment]
https://user-images.githubusercontent.com/4684880/208420678-2bbb4a28-3377-4554-a102-0637091c7f26.png

**Comment by ranisalt** [comment]
Working on a fix

**Comment by Zbizu** [comment]
@daniofordon please use issue templates provided when creating an issue next time

**Comment by LuckyM91** [comment]
When you are trying to look at yourself that error appears
