### ISSUE TITLE
Item light is different on the ground and different on equip after modifying the light in object builder

### ISSUE THREAD

**Issue by floki21uu** [otland/forgottenserver#4281]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Change the light of torch from yellow to white (215) in object builder.
![wwwwwwwww](https://user-images.githubusercontent.com/96269029/209478311-bf0a7fd6-b041-453c-bd2f-6ef970ad95f0.png)
3. The light on the ground is 215 (white) so it's OK but when eqipped it is still yellow, gif:
![www gif](https://user-images.githubusercontent.com/96269029/209478332-9a83b02a-ae58-467e-a13c-319f41b27b23.gif)

There is a function which seems to work well so no idea what causes it:
`
void Player::updateItemsLight(bool internal /*=false*/)
{
	LightInfo maxLight;

	for (int32_t i = CONST_SLOT_FIRST; i <= CONST_SLOT_LAST; ++i) {
		Item* item = inventory[i];
		if (item) {
			LightInfo curLight = item->getLightInfo();

			if (curLight.level > maxLight.level) {
				maxLight = std::move(curLight);
			}
		}
	}

	if (itemsLight.level != maxLight.level || itemsLight.color != maxLight.color) {
		itemsLight = maxLight;

		if (!internal) {
			g_game.changeLight(this);
		}
	}
}
`
One more GIF in better resolution:
![www gif](https://user-images.githubusercontent.com/96269029/209478567-6d03d3f0-7d93-4904-8e6e-8ccb9b2acd41.gif)

**Comment by EPuncker** [comment]
can you reproduce this bug with cip client? or even OTC by mehahs? this seems totally like a client problem once again, tfs code is just fine related to this

**Comment by EPuncker** [comment]
oh and don't forget to update your items.otb to reflect the change in the .dat file

**Comment by floki21uu** [comment]
> oh and don't forget to update your items.otb to reflect the change in the .dat file

there is nothing according to light in items.
![Uploading asd.png…]()
otb. i ahev checked with item editor

**Comment by Zbizu** [comment]
Your otb doesn't match the dat file. This isn't a problem with tfs repo. Visit support board for further help.

**Comment by floki21uu** [comment]
I have fixed it by changing bytes in`msg.addByte(0xD7); `
