### ISSUE TITLE
Objects like roofs do not dissapear at a certain distance from a player

### ISSUE THREAD

**Issue by floki21uu** [otland/forgottenserver#4282]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
Here gifs show it all.
1. Real Tibia:
![nnnnnnnnnnnnnnn](https://user-images.githubusercontent.com/96269029/209478922-e0a7745b-b80a-413c-a53e-4c7aafacbcaa.gif)

3. TheForgottenServer:
![ot](https://user-images.githubusercontent.com/96269029/209478824-accc04db-b26c-476d-a741-14babcee6841.gif)

**Comment by EPuncker** [comment]
this has nothing to do with tfs, it is totally client sided, try it on up to date client and you will see that the behavior is the same

**Comment by floki21uu** [comment]
> this has nothing to do with tfs, it is totally client sided, try it on up to date client and you will see that the behavior is the same as rl tibia

ok, sorry
