### ISSUE TITLE
equipping 2h weapon (classic slots)

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#4287]
### Explanation of what you want to do that is currently impossible
if you try to replace your equipped 1h weapon or shield with another 2h weapon, it should unequip what you currently have.

### Desired functionality
if 2h weapon is located

- **backpack**
equipped item should be moved to first slot of the backpack and return "RETURNVALUE_BOTHHANDSNEEDTOBEFREE"

- **ground**
equipped item should be moved ontop of the 2h weapon on the ground and return "RETURNVALUE_BOTHHANDSNEEDTOBEFREE"

- **arrow slot**
equipped item should NOT be moved and instead return "RETURNVALUE_NOTENOUGHROOM"

**Comment by emil92b** [comment]
it should also be possible to replace your current weapon with another (if you could carry it after replacing current), as of now it returns 'this object is too heavy for you to carry.' which should not be the case

for example, you have 7 cap with a 'club' (25.00 oz) equipped, and trying to replace it with a 'skull staff' (17.00 oz), 
it got replaced and now you have 15 cap.

**Comment by floki21uu** [comment]
> it should also be possible to replace your current weapon with another (if you could carry it after replacing current), as of now it returns 'this object is too heavy for you to carry.' which should not be the case
> 
> for example, you have 7 cap with a 'club' (25.00 oz) equipped, and trying to replace it with a 'skull staff' (17.00 oz), it got replaced and now you have 15 cap.

they made it in othire. just cupypasta the code
