### ISSUE TITLE
MoveEvent - onAddItem does not work

### ISSUE THREAD

**Issue by ArturKnopik** [otland/forgottenserver#4300]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
create item 7655
create item 7732
put item 7732 on top 7655

### Expected behaviour
item 7655 transform to 7665

### Actual behaviour
nothing hapened

### Note
data/scripts/movements/seeds.lua

**Comment by marmichalski** [comment]
I guess it's just missing a :type("additem") call compared to other scripts? 🤔

**Comment by omarcopires** [comment]
I submitted a claim with the correction as used in #4280.
