### ISSUE TITLE
[Crash] Bug TFS 0.3.6

### ISSUE THREAD

**Issue by Vagnerking** [otland/forgottenserver#4313]
Can someone help me? I'm using "The Forgotten Server - Edited By Cyko V8, version 0.3.6 - Edited By Cyko V8 (Crying Damson - Edited By Cyko V8)" and when I have my server online with some people, at some point of the day it always crashes and I have no idea what it is.

I already tested several ways to try to make the server crash with the most known bugs in the forums but nothing worked to crash. However, after a while online, my server ends up crashing out of nowhere.

failure written to exception log:

`*****************************************************
Error report - Thu Feb 02 17:09:32 2023

Compiler Info - GNU C++ version 3.4.5 (mingw special)
Compilation Date - Jan 29 2023 19:43:28

Memory load: 66
Total phys: 4193768 K available phys: 1388372 K
Start time: 2-2-2023 16:26:28
Kernel time: 0:0:42.515
User time: 0:14:52.109
Threads: 5

Exception: 0xc0000005 at eip = 0xa3d
eax = 0xe82edc8 -> 0xa3d
ebx = 0xd58e54 -> 0x9a6768
ecx = 0xd58e0c -> 0x25e9eb60
edx = 0xe82edd0 -> 0x3e3
esi = 0x30bff08 -> 0x28fe1c
edi = 0x30bff3c -> 0xd58d88
ebp = 0x30bf8f8 -> 0x30bfa08
esp = 0x30bf8dc -> 0x837848
efl = 0x10202

---Stack Trace---
From: 0x30bf8dc to: 0x30c0000
0x30bf8dc | 0x837848 -> 0x347b83
0x30bf8e0 | 0xe82edc8 -> 0xa3d
0x30bf8e4 | 0xe82edd0 -> 0x3e3
0x30bf8e8 | 0xffb3b4c0
0x30bf8ec | 0xa23840 -> 0x9a68e8
0x30bf8f0 | 0x30bff08 -> 0x28fe1c
0x30bf8f4 | 0xa23840 -> 0x9a68e8
0x30bf8f8 | 0x30bfa08 -> 0x30bfb18 \\\\\\ stack frame //////
0x30bf8fc | 0x8579a7 -> 0xff2885ff <-- ret
0x30bf900 | 0xd58e54 -> 0x9a6768
0x30bf904 | 0
0x30bf908 | 0x30bf984 -> 0
0x30bf90c | 0x30bf988 -> 0x27c9d570
0x30bf910 | 0x27c9d570 -> 0
0x30bf914 | 0x30bfae0 -> 0x73676f6c
0x30bf918 | 0x109
0x30bf91c | 0x40
0x30bf920 | 0x180
0x30bf924 | 0x30bfae0 -> 0x73676f6c
0x30bf928 | 0
0x30bf92c | 0xd58e0c -> 0x25e9eb60
0x30bf930 | 0
0x30bf934 | 0xd58e00 -> 0xd58eb8
0x30bf938 | 0
0x30bf93c | 0x1
0x30bf940 | 0x7657f345 -> 0x90c35d59
0x30bf944 | 0x1f4
0x30bf948 | 0x10bf984 -> 0x6f006c
0x30bf94c | 0xffc
0x30bf950 | 0x30bfa70 -> 0
0x30bf954 | 0x158a6db
0x30bf958 | 0xd58db8 -> 0x9a6888
0x30bf95c | 0x1
0x30bf960 | 0x30bff08 -> 0x28fe1c
0x30bf964 | 0x9bc3d0 -> 0x9a6dec
0x30bf968 | 0
0x30bf96c | 0x30bf958 -> 0xd58db8
0x30bf970 | 0
0x30bf974 | 0x9bbf38 -> 0x9a5ca8
0x30bf978 | 0x76598cd5 -> 0x8b55ff8b
0x30bf97c | 0xcbb2ef15
0x30bf980 | 0xe
0x30bf984 | 0
0x30bf988 | 0x27c9d570 -> 0
0x30bf98c | 0x360faec -> 0x80d40f
0x30bf990 | 0x3
0x30bf994 | 0x30bff08 -> 0x28fe1c
0x30bf998 | 0x30bf9a8 -> 0x95fe50
0x30bf99c | 0x8685e6 -> 0xc908ec83
0x30bf9a0 | 0x18
0x30bf9a4 | 0x7ca7a0 -> 0x8de58955
0x30bf9a8 | 0x95fe50 -> 0x11500ff
0x30bf9ac | 0x30bf9f0 -> 0x30bf9b0
0x30bf9b0 | 0x857cc5 -> 0x8b186d8d
0x30bf9b4 | 0x30bf900 -> 0xd58e54
0x30bf9b8 | 0x23b57b9c -> 0x7c917cb1
0x30bf9bc | 0x23b57b90 -> 0x9a2688
0x30bf9c0 | 0xd58db8 -> 0x9a6888
0x30bf9c4 | 0x30bfaf0 -> 0xd58db8
0x30bf9c8 | 0x30bfa7c -> 0x30bfb7c
0x30bf9cc | 0x1
0x30bf9d0 | 0xd58de4 -> 0xa21b50
0x30bf9d4 | 0xffffff01
0x30bf9d8 | 0xffffffff
0x30bf9dc | 0x7fffffff -> 0x100
0x30bf9e0 | 0xd58de4 -> 0xa21b50
0x30bf9e4 | 0x95ff01 -> 0x401ffff
0x30bf9e8 | 0x30bf9fc -> 0xa23840
0x30bf9ec | 0x831c81 -> 0x8b0c6d8d
0x30bf9f0 | 0x30bf9b0 -> 0x857cc5
0x30bf9f4 | 0xa23840 -> 0x9a68e8
0x30bf9f8 | 0x24e1ad0 -> 0x52057327
0x30bf9fc | 0xa23840 -> 0x9a68e8
0x30bfa00 | 0x30bff08 -> 0x28fe1c
0x30bfa04 | 0x30bff3c -> 0xd58d88
0x30bfa08 | 0x30bfb18 -> 0x30bfc18 \\\\\\ stack frame //////
0x30bfa0c | 0x829503 -> 0xbb75c085 <-- ret
0x30bfa10 | 0xd58db8 -> 0x9a6888
0x30bfa14 | 0x1
0x30bfa18 | 0x30bfa70 -> 0
0x30bfa1c | 0xa23840 -> 0x9a68e8
0x30bfa20 | 0x30bfb68 -> 0x30bfbf8
0x30bfa24 | 0x9b72a4 -> 0x80000000
0x30bfa28 | 0
0x30bfa2c | 0x24e1ae4 -> 0
0x30bfa30 | 0x24e1ad8 -> 0x9a6b98
0x30bfa34 | 0x7fffffff -> 0x100
0x30bfa38 | 0x30bfe64 -> 0x30bff70
0x30bfa3c | 0x76598cd5 -> 0x8b55ff8b
0x30bfa40 | 0xcbbdd115
0x30bfa44 | 0xfffffffe
0x30bfa48 | 0x765798da -> 0x909090c3
0x30bfa4c | 0xa23840 -> 0x9a68e8
0x30bfa50 | 0x30bff08 -> 0x28fe1c
0x30bfa54 | 0xa23840 -> 0x9a68e8
0x30bfa58 | 0x8125cf -> 0x3beffff
0x30bfa5c | 0x8724ce -> 0xff44858b
0x30bfa60 | 0xd58db8 -> 0x9a6888
0x30bfa64 | 0x30bfb68 -> 0x30bfbf8
0x30bfa68 | 0
0x30bfa6c | 0xffffffff
0x30bfa70 | 0
0x30bfa74 | 0x9bbf38 -> 0x9a5ca8
0x30bfa78 | 0x9b7200 -> 0x9a57e8
0x30bfa7c | 0x30bfb7c -> 0x30bfddc
0x30bfa80 | 0x8
0x30bfa84 | 0xa2434c -> 0xb74
0x30bfa88 | 0x94ade2 -> 0x1401ffff
0x30bfa8c | 0x30bfae0 -> 0x73676f6c
0x30bfa90 | 0xa2433c -> 0x120
0x30bfa94 | 0x7ca7a0 -> 0x8de58955
0x30bfa98 | 0x95fe2c -> 0x11d00ff
0x30bfa9c | 0x30bfb00 -> 0x88e49a
0x30bfaa0 | 0x829936 -> 0x8b186d8d
0x30bfaa4 | 0x30bfa10 -> 0xd58db8
0x30bfaa8 | 0x30bfb34 -> 0x30bfbf0
0x30bfaac | 0xffffffff
0x30bfab0 | 0x23b57bcc -> 0x7fffffff
0x30bfab4 | 0x7ca7a0 -> 0x8de58955
0x30bfab8 | 0x962dea -> 0x3a01ffff
0x30bfabc | 0x30bfb50 -> 0x9b7200
0x30bfac0 | 0x74bbf6 -> 0x8b186d8d
0x30bfac0 GUILogger::eek:verflow(int)(0x74a7f0)
0x30bfac4 | 0x30bf9a0 -> 0x18
0x30bfac8 | 0x9b72a4 -> 0x80000000
0x30bfacc | 0x30bfbdc -> 0xc
0x30bfad0 | 0x24df594 -> 0x3718470
0x30bfad4 | 0xa23840 -> 0x9a68e8
0x30bfad8 | 0x24e1ad8 -> 0x9a6b98
0x30bfadc | 0xa4e1ad8 -> 0
0x30bfae0 | 0x73676f6c
0x30bfae4 | 0x7265732f
0x30bfaf4 | 0
0x30bfaf8 | 0x676f6c -> 0x45ee824
0x30bfaf8 OutputMessagePool::~OutputMessagePool()(0x676c58)
0x30bfafc | 0x30bfb50 -> 0x9b7200
0x30bfb00 | 0x88e49a -> 0x8b186d8d
0x30bfb04 | 0x30bfa80 -> 0x8
0x30bfb08 | 0x30bfbbc -> 0x1a025a
0x30bfb0c | 0xa23840 -> 0x9a68e8
0x30bfb10 | 0x30bff08 -> 0x28fe1c
0x30bfb14 | 0x30bff3c -> 0xd58d88
0x30bfb18 | 0x30bfc18 -> 0x30bfed8 \\\\\\ stack frame //////
0x30bfb1c | 0x70602b -> 0xff60958b <-- ret
0x30bfb1c ServiceManager::run()(0x705f9e)
0x30bfb20 | 0x30bfe74 -> 0x45303337
0x30bfb24 | 0x962690 -> 0x10d00ff
0x30bfb28 | 0x30bfb3c -> 0x98087e
0x30bfb2c | 0x90646c -> 0x8b0c6d8d
0x30bfb30 | 0x1
0x30bfb34 | 0x30bfbf0 -> 0xff3c
0x30bfb38 | 0x30bfbbc -> 0x1a025a
0x30bfb3c | 0x98087e -> 0x72657320
0x30bfba0 ServiceManager::run()(0x705f9e)
0x30bfbf4 | 0x30bfc18 -> 0x30bfed8
0x30bfbf8 | 0x7578724a -> 0x10c25d5e
0x30bfbfc | 0x10bb940 -> 0x1a025a
0x30bfc00 | 0
0x30bfc04 | 0x6f0cc903 -> 0x8b55ff8b
0x30bfc08 | 0
0x30bfc0c | 0xa23840 -> 0x9a68e8
0x30bfc10 | 0x30bff08 -> 0x28fe1c
0x30bfc14 | 0x30bff3c -> 0xd58d88
0x30bfc18 | 0x30bfed8 -> 0x30bfee8 \\\\\\ stack frame //////
0x30bfc1c | 0x65d559 -> 0x34fe9 <-- ret
0x30bfc1c serverMain(void*)(0x65cc1a)
0x30bfc20 | 0x30bfe70 -> 0x9a33e8
0x30bfc24 | 0xc
0x30bfc28 | 0
0x30bfc2c | 0x98088e -> 0x53203e3e
0x30bfc30 | 0xffffffff
0x30bfc34 | 0xffffffff
0x30bfc38 | 0xffffff01
0x30bfc3c | 0x24a8e10 -> 0x2564368
0x30bfe00 serverMain(void*)(0x65cc1a)
0x30bfe54 otserv(ServiceManager*)(0x65e8c8)
0x30bfe68 _SEHHandler(_EXCEPTION_RECORD*, void*, _CONTEXT*, void*)(0x47cacc)
0x30bfeb4 | 0x23b69ba8 -> 0
0x30bfeb8 | 0x2
0x30bfebc | 0x260
0x30bfec0 | 0x1010000 -> 0
0x30bfec4 | 0x30bfdfc -> 0x30bfec0
0x30bfec8 | 0
0x30bfecc | 0xa23840 -> 0x9a68e8
0x30bfed0 | 0x30bff08 -> 0x28fe1c
0x30bfed4 | 0x30bff3c -> 0xd58d88
0x30bfed8 | 0x30bfee8 -> 0x30bff48 \\\\\\ stack frame //////
0x30bfedc | 0x86dcca -> 0x8955c3c9 <-- ret
0x30bfee0 | 0x280224
0x30bfee4 | 0xa23840 -> 0x9a68e8
0x30bfee8 | 0x30bff48 -> 0x30bff80 \\\\\\ stack frame //////
0x30bfeec | 0x7c6bce -> 0xffc445c7 <-- ret
0x30bfef0 | 0xa23840 -> 0x9a68e8
0x30bfef4 | 0xd58d88 -> 0x24a8e10
0x30bfef8 | 0xd58d80 -> 0x56f1a300
0x30bfefc | 0x30bff48 -> 0x30bff80
0x30bff00 | 0x765798cd -> 0x840fc085
0x30bff04 | 0xd50000 -> 0xe1f1a3b7
0x30bff08 | 0x28fe1c -> 0
0x30bff0c | 0x1
0x30bff24 | 0x967240 -> 0x10d00ff
0x30bff28 | 0x30bff3c -> 0xd58d88
0x30bff2c | 0x7c6bf6 -> 0x830cc583
0x30bff30 | 0x30bfef0 -> 0xa23840
0x30bff34 | 0x30bff80 -> 0x30bff88
0x30bff38 | 0x7657a53a -> 0x5ec68b5f
0x30bff3c | 0xd58d88 -> 0x24a8e10
0x30bff40 | 0
0x30bff44 | 0
0x30bff48 | 0x30bff80 -> 0x30bff88 \\\\\\ stack frame //////
0x30bff4c | 0x76581287 -> 0x2fe850 <-- ret
0x30bff50 | 0xa23840 -> 0x9a68e8
0x30bff54 | 0xbee1b675
0x30bff58 | 0
0x30bff5c | 0
0x30bff60 | 0xd58d88 -> 0x24a8e10
0x30bff64 | 0x30bff54 -> 0xbee1b675
0x30bff68 | 0x30bff54 -> 0xbee1b675
0x30bff6c | 0x30bffc4 -> 0x30bffe4
0x30bff70 | 0x30bffc4 -> 0x30bffe4
0x30bff74 | 0x76598cd5 -> 0x8b55ff8b
0x30bff78 | 0xcbb25b65
0x30bff7c | 0
0x30bff80 | 0x30bff88 -> 0x30bff94 \\\\\\ stack frame //////
0x30bff84 | 0x76581328 -> 0x909090cc <-- ret
0x30bff88 | 0x30bff94 -> 0x30bffd4
0x30bff8c | 0x7663336a -> 0x415ff50 <-- ret
0x30bff90 | 0xd58d88 -> 0x24a8e10
0x30bff94 | 0x30bffd4 -> 0x30bffec \\\\\\ stack frame //////
0x30bff98 | 0x77bd9902 -> 0xfefc45c7 <-- ret
0x30bff9c | 0xd58d88 -> 0x24a8e10
0x30bffa0 | 0x771524ea -> 0xa7abf38d
0x30bffa4 | 0
0x30bffa8 | 0
0x30bffac | 0xd58d88 -> 0x24a8e10
0x30bffb0 | 0
0x30bffb4 | 0
0x30bffb8 | 0
0x30bffbc | 0x30bffa0 -> 0x771524ea
0x30bffc0 | 0
0x30bffc4 | 0x30bffe4 -> 0xffffffff
0x30bffc8 | 0x77c158c5 -> 0x8b55ff8b
0x30bffcc | 0x3a21d1e -> 0x8040804
0x30bffd0 | 0
0x30bffd4 | 0x30bffec -> 0 \\\\\\ stack frame //////
0x30bffd8 | 0x77bd98d5 -> 0x909090cc <-- ret
0x30bffdc | 0x765812e5 -> 0x8b55ff8b
0x30bffe0 | 0xd58d88 -> 0x24a8e10
0x30bffe4 | 0xffffffff
0x30bffe8 | 0x77c675cc -> 0x8b55ff8b
0x30bffec | 0 \\\\\\ stack frame //////
0x30bfff0 | 0 <-- ret
0x30bfff4 | 0x765812e5 -> 0x8b55ff8b
0x30bfff8 | 0xd58d88 -> 0x24a8e10
0x30bfffc | 0
*****************************************************`

**Comment by EPuncker** [comment]
sorry, this github is only for issues related to tfs 1.x

remember that tfs 0.3.6 is more than 10 years old and have not received any fixes or updates since them...

[I recommend reading this post](https://otland.net/threads/8-60-the-forgotten-server-0-3-6-crying-damson-v8.147913/page-60#post-2639060)
