### ISSUE TITLE
stacks with 200 or 255 instead of 100

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#4333]
### Explanation of what you want to do that is currently impossible
QT client and OTC have full client-side support for items stacked as 255
Tried to implement it myself, but the way item stacking works has to be rewritten because evil things happen when you try to combine two stacks (lots of hardcoded 100s there also)

### Desired functionality
stacking items as 200 or 255 (preferable with config.lua option)

### Available workarounds
commenting a line in `item:transform()` source code and using it to change item subtype

### Prior art
![obraz](https://user-images.githubusercontent.com/5205079/221027220-6506327d-4dbc-4b8c-8de9-14383d46dd2a.png)

![obraz](https://user-images.githubusercontent.com/5205079/221027286-6e0c21df-1a58-4919-9237-dd0a87fb9567.png)

**Comment by EPuncker** [comment]
that would be cool

**Comment by conde2** [comment]
Agreed with this feature, very useful.
