### ISSUE TITLE
crash tfs login to otclient or refresh myacc

### ISSUE THREAD

**Issue by daniofordon** [otland/forgottenserver#4335]
current tfs (all commit)

when running clean tfs no change. when i refresh the myaac page the engine turns off. it also happens when i try to login via otclient

https://prnt.sc/jjawXU-6jwOY

**Comment by daniofordon** [comment]
I found the cause of the server crash. if in config.lua instead of the server's ip, he enters the domain connected to vps debian 11, the server crashes. when i enter the server ip, the server works normally.

**Comment by EPuncker** [comment]
misconfiguration, not tfs fault IMO
