### ISSUE TITLE
[Modal Window] Default Button

### ISSUE THREAD

**Issue by omarcopires** [otland/forgottenserver#4370]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Use any modal choice script.
2. Press enter to choose one of the options.

### Expected behaviour 
You must activate the select or choice button.

### Actual behaviour 
Nothing happens, the modal is just closed.

**Comment by EPuncker** [comment]
@MillhioreBT can you take a look into this please?
