### ISSUE TITLE
Crash when opening outfits window with GM

### ISSUE THREAD

**Issue by omarcopires** [otland/forgottenserver#4383]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Login with a GM account.
2. Open customization window or ctrl + r.

### Expected behaviour 
The outfits and mounts window should open normally.

### Actual behaviour 
The client crashes when opening.

**Comment by MillhioreBT** [comment]
the crash problem occurs when the mount is active, and you try to see the gamemaster outfit, it probably also happens with other outfits that don't have synergy with mounts

I'm not sure if this can be prevented from the server side.

**Comment by omarcopires** [comment]
> the crash problem occurs when the mount is active, and you try to see the gamemaster outfit, it probably also happens with other outfits that don't have synergy with mounts
> 
> I'm not sure if this can be prevented from the server side.

Also got crashes even when wearing citizen outfits...
