### ISSUE TITLE
Broken Lua NetworkMessage API

### ISSUE THREAD

**Issue by conde2** [otland/forgottenserver#4443]
### Steps to reproduce (include any configuration/script required to reproduce)
```lua
	local networkMessage = NetworkMessage()
	networkMessage:addByte(5)
	print("BYTE:" .. networkMessage:getByte())
```

### Expected behaviour
Print anything different from 0 (zero)

### Actual behaviour
always print the value 0 (zero)

**Comment by Shawak** [comment]
Dont u have to reset the position to read a byte again
