### ISSUE TITLE
Items With Charges NPC Window.

### ISSUE THREAD

**Issue by br-it0** [otland/forgottenserver#4452]
Items with charges appears with charge "0", in npc window.
Even if configured in the npc and sold with the correct charge, the charges appear as 0.

Oficial Tibia Client.

Release 1.4.2

![Look](https://github.com/otland/forgottenserver/assets/72952643/3341b2ae-7720-478d-b868-585ac1492c27)

**Comment by EPuncker** [comment]
for anyone whiling to fix the issue, the missing getCharges part is here:
https://github.com/Znote/forgottenserver/blob/2a75da720c3ebbfa27ae7cfe619456196d42f829/data/lib/core/item.lua#L423-L425
