### ISSUE TITLE
Compilation Error - FMT::FORMAT()

### ISSUE THREAD

**Issue by Giorox** [otland/forgottenserver#4465]
### Before creating an issue, please ensure:
- [X ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ X] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Installed VCPKG and all dependencies from the wiki step-by-step for W10
2. Opened `theforgottenserver.vcxproj`, set `Release` and `x64`
3. Went to `Build > Build theforgottenserver`

### Expected behaviour
Complete build of the source code.

### Actual behaviour
Getting build errors regarding call to `fmt::format()` in `iomapserialize.cpp`

```
1>C:\vcpkg\installed\x64-windows\include\fmt\core.h(1691,7): error C2338: static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt' (compiling source file ..\src\iomapserialize.cpp)
```

The line that is triggering the error is
```
fmt::format("{:d}, {}, {:s}", house->getId(), GUEST_LIST, db.escapeString(listText))
```
I imagine that the following lines will also trigger the same problem

### Environment
Using Visual Studio Community 2022, vcpkg at latest versions. Windows 10.

**Comment by natanFernandesDev** [comment]
I'm currently trying to solve this problem, it happened to me out of the blue, if I get anything I'll post it here too.

**Comment by MillhioreBT** [comment]
> fmt::format("{:d}, {}, {:s}", house->getId(), GUEST_LIST, db.escapeString(listText))

Try changing the `{}` to `{:d}` and let me know if it works for you.

**Comment by Giorox** [comment]
> > fmt::format("{:d}, {}, {:s}", house->getId(), GUEST_LIST, db.escapeString(listText))
> 
> Try changing the `{}` to `{:d}` and let me know if it works for you.
> 
> It's quite strange. I use Visual Studio 2019 and an older compiler, but still fmt deduces the types perfectly when specializations are not specified. ![image](https://user-images.githubusercontent.com/28090948/241462852-775126fe-89f3-47f4-89e8-4c7072f08e7c.png)

Got the same error, for some reason it's not able to deduce or coerce the `AccessList_t` type (even though it's just a HEX value). What's weird, and I'm not sure that this is expected behaviour is that the following conditional statement should probably give off the same error, I'll install VS2019 and see if that solves it.

**Comment by Giorox** [comment]
Alright, this kind of fixes it, but it's janky.

I figured that since the problem wasn't type-deduction, maybe there was some sort of problem with serializing or coercing the type to something that `fmt` could work with, so what if we `static_cast` it to a primitive?

```c++
if (!stmt.addRow(fmt::format("{:d}, {}, {:s}", house->getId(), static_cast<int>(GUEST_LIST), db.escapeString(listText)))) {
```

and

```c++
if (!stmt.addRow(fmt::format("{:d}, {}, {:s}", house->getId(), static_cast<int>(SUBOWNER_LIST), db.escapeString(listText)))) {
```

By doing `static_cast<int>` we're making it so `fmt::format()` sees an `int` instead of an `enum` not sure why this works, but it does.

**Comment by Giorox** [comment]
After toying a bit with FMT (first time), I've come to a few possible solutions:

1. Add `static_cast<int>(GUEST_LIST)` and `static_cast<int>(SUBOWNER_LIST)` to `iomapserialize.cpp`
    - **Advantages**: Backwards compatible with FMT v9.0.0;
    - **Disadvantages**: Must change call to `fmt::format()` and negates the benefit of enums
2. Add an implicit function override definition for `fmt::format_as()` as exemplified in this [comment](https://github.com/otland/forgottenserver/issues/4465#issuecomment-1566113265)
    - **Advantages**: Doesn't have to change any existing code, just define an additional function
    - **Disadvantages**: Not backwards compatible with FMT v9.0.0; Might break other calls; No clear location to put it (can't be a IOMapSerialize member)
3. Add `fmt::underlying(GUEST_LIST)` and `fmt::underlying(SUBOWNER_LIST)` to `iomapserialize.cpp``
    - **Advantages**: Backwards compatible with FMT v9.0.0; Very `fmt` idiomatic; Works for any underlying type enum.
    - **Disadvantages**: Must change call to `fmt::format()`

There is probably also a way to Template the `format_as` function, I've tried the following and it **COMPILES**, but I'm not sure it works as I haven't ran a server on it yet.

```c++
template <class enumType> int format_as(enumType accessEnum)
{
	return static_cast<int>(accessEnum);
}
```

A side-benefit of this is that it would work for other integer enums (but not other types, but easy enough to change it so it does).

**Comment by slawkens** [comment]
In canary it has been fixed by using fmt::underlying function

https://github.com/opentibiabr/canary/commit/be50acfed34dfe5b55a01517bde639ca6d6d6eb5

**Comment by Giorox** [comment]
> @slawkens Reason it cannot be resolved this way: [#4466 (comment)](https://github.com/otland/forgottenserver/pull/4466#issuecomment-1566286898h) Btw it's already "resolved" by #4487 (workaround to use 9.1.0)

One workaround would be to take the implementation using `format_as` with `static_cast` I drafted in the [comment ](https://github.com/otland/forgottenserver/issues/4465#issuecomment-1566157841) above .

**Comment by slawkens** [comment]
> @slawkens  Reason it cannot be resolved this way:
> https://github.com/otland/forgottenserver/pull/4466#issuecomment-1566286898
> Btw it's already "resolved" by #4487 (workaround to use 9.1.0)

Ah, ok, I didn't know it had been discussed somewhere else. Always the same problems with different distributions and different versions. Hopefully, you guys find the correct approach 👍

**Comment by EPuncker** [comment]
https://github.com/otland/forgottenserver/commit/61452aa5dc2c8d3ff345e627295eef06d8aafa8a fixed the issue?

**Comment by Giorox** [comment]
> [61452aa](https://github.com/otland/forgottenserver/commit/61452aa5dc2c8d3ff345e627295eef06d8aafa8a) fixed the issue?

Seems like it tackles the affected code, pretty elegantly too. Can probably mark this is as solved

**Comment by victorvadl** [comment]
> ```c++
> static_cast<int>
> ```

Where should i add this line of code?  

`template <class enumType> int format_as(enumType accessEnum)
{
	return static_cast<int>(accessEnum);
}`

**Comment by Giorox** [comment]
> > ```c++
> > static_cast<int>
> > ```
> 
> Where should i add this line of code?
> 
> `template <class enumType> int format_as(enumType accessEnum) { return static_cast<int>(accessEnum); }`

Look at [61452aa](https://github.com/otland/forgottenserver/commit/61452aa5dc2c8d3ff345e627295eef06d8aafa8a), they added it in `src/tools.h`.

PTBR: Só olhar no commit acima, foi adicionado no `tools.h` e so precisa garantir que na `iomapserialize.cpp` vc ta importando o `tools.h`.
