### ISSUE TITLE
Deleting items on Quest Doors

### ISSUE THREAD

**Issue by Feeltz** [otland/forgottenserver#4467]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Log into regular character (not working for GM)
2. Use any quest door (with red handle)
3. While standing on the quest door tile put any item on the tile
4. Move in direction of closing door

Video: https://youtu.be/SI1V0Up_qZQ

### Expected behaviour
Items are pushed on the tile with character

### Actual behaviour
Character moves on tile, and items are destroyed

If you move to the opposite direction, then items are relocated correctly. If you move to the position where items are pushed then items dissapper.

**Comment by EPuncker** [comment]
@Feeltz can you please test #4468 and let is know if this fixes the issue?

**Comment by Feeltz** [comment]
Yes, it fixes the problem.
