### ISSUE TITLE
Reset idle timer by lua

### ISSUE THREAD

**Issue by ArturKnopik** [otland/forgottenserver#4470]
### Explanation of what you want to do that is currently impossible
Reset idle timer by lua
ex: training weapons from RL tibia

### Desired functionality
player:resetIdleTimer()

### Available workarounds
not known, probably some move function

### Possible implementation
```
int LuaScriptInterface::luaPlayerResetIdleTime(lua_State* L)
{
	// player:resetIdleTimer()
	Player* player = getUserdata<Player>(L, 1);
	if (!player) {
		lua_pushnil(L);
		return 1;
	}

	player->resetIdleTime();

	pushBoolean(L, true);
	return 1;
}
```

**Comment by MillhioreBT** [comment]
better to include setIdleTime and then create another resetIdleTime method in lua

**Comment by EPuncker** [comment]
also lets not forget that the player will be put in a new state:

https://github.com/otland/forgottenserver/blob/master/src/enums.h#L90-L96

**Comment by ArturKnopik** [comment]
do we really want to set idle timer?
for me resetting is enough.
