### ISSUE TITLE
Add new position method for ActionEvent (Revscripts)

### ISSUE THREAD

**Issue by soyfabi** [otland/forgottenserver#4480]
Greetings, I was reviewing one of the revscripts that has a way to place position without having to place id, aid or uid, I am clear that it is only a MoveEvent.

```
test:position(Position(33082, 31532, 7))
test:register()
```

I did the same with an Action and it throws error.

![image_2023-06-01_232852850](https://github.com/otland/forgottenserver/assets/91706615/44bb2ed3-0727-4019-811d-540bd88339c3)

I was looking at the github and I noticed that they added the way to place position in moveevents.
https://github.com/otland/forgottenserver/commit/1b0bcb642a15e9be639ad76672c4ea2c59931f97

I tried to do it with Action but the attempt failed, I would be grateful if you add this method in the future.

**Comment by EPuncker** [comment]
is this a suggestion or a bug report?
it makes no sense to have position defined in an action script, because you never use a position, but an object/item
