### ISSUE TITLE
loogin.lua errors

### ISSUE THREAD

**Issue by daniofordon** [otland/forgottenserver#4507]
I use TFS 12.87 current and when I enter the game in the console pops up this error.

https://prnt.sc/ZJnLFmRyP5D1

**Comment by EPuncker** [comment]
that is not an error, that is just a warning that was added recently in https://github.com/otland/forgottenserver/commit/66d079615b5c684294e1ddffc54afd6c52fa0431

you may want to disable the warning or update the scripts changing `-1` to `nil` in all your get/setStorage occurrences
