### ISSUE TITLE
Docker build . throwing an error 

### ISSUE THREAD

**Issue by diegoQuinas** [otland/forgottenserver#4513]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.sudo docker build . -t server

### Expected behaviour

It should build the image
### Actual behaviour

It throws the following error: 
ERROR: unable to select packages:   crypto++-dev (no such package):     required by: world[crypto++-dev]
### Environment

Alpine of the Dockerfile

**Comment by DSpeichert** [comment]
The image builds fine in our workflow. Try `docker build --pull ...` to make sure you're using latest version of the base image.
