### ISSUE TITLE
npc error, and compilation

### ISSUE THREAD

**Issue by fiapo78** [otland/forgottenserver#4516]
Good morning, Guys having a little problem if anyone can help me. Well the problem and the following I have this error.

Lua script error: [npc interface]
data/npc/scripts/runes.lua:onCreatureSay
LuaScriptInterface::getNumber(). Argument -1 has a value out of range for unsigned int: -1
stack trace:
          [C]: in 'openShopWindow' function
          data/npc/lib/npcsystem/modules.lua:1085: in 'callback' function
          data/npc/lib/npcsystem/keywordhandler.lua:26: in function 'processMessage'
          data/npc/lib/npcsystem/keywordhandler.lua:151: in function 'processNodeMessage'
          data/npc/lib/npcsystem/keywordhandler.lua:126: in function 'processMessage'
          data/npc/lib/npcsystem/npchandler.lua:408: in function 'onCreatureSay'

Then they told me that I had to change something in the sourcer, I changed it but I can't compile the sourcer, I've tried to watch videos in Portuguese, in English, to see many tutorials in Otland, in other forums it won't, if someone could please make me available The Forgotten Server but updated than 1.4.2 I thank you and this error of mine has already been solved.

**Comment by fiapo78** [comment]
Someone please

**Comment by omarcopires** [comment]
> Someone please

this is abandoned, they barely accept ready commits xD

**Comment by fiapo78** [comment]
Ah, but I say someone who has this TFS already compiled can make a donation. I don't know or help

**Comment by omarcopires** [comment]
> Ah, but I say someone who has this TFS already compiled can make a donation. I don't know or help

https://otland.net/threads/tfs-1-2-minimap-generator-map-scanner.262275/#post-2715284

**Comment by fiapo78** [comment]
I didn't understand this link and about Minimap generator, and it's with tfs 1.2, my tfs is 1.4x

**Comment by luanluciano93** [comment]
https://github.com/otland/forgottenserver/pull/4293

**Comment by Codinablack** [comment]
We can close this as #4293 resolves this issue.
