### ISSUE TITLE
ubuntu 22.04 run tfs and error 

### ISSUE THREAD

**Issue by daniofordon** [otland/forgottenserver#4533]
Hello. I have a problem with the latest TFS. When I run the server I can normally log in to the game and everything works. but when refresh the page aac myaac / znote is the server turns off giving such an error

https://prnt.sc/VzVLRk7m96xM

**Comment by gesior** [comment]
@daniofordon 
I cannot reproduce it. Tested on Mint 21, which is based on Ubuntu 22.04.

Put this in `status.php` file on your server:
```php
<?php

$sock = @fsockopen('127.0.0.1', 7171);

if($sock)
{
	$toSend = chr(6).chr(0).chr(255).chr(255).'info';

	fwrite($sock, $toSend);
	$answer = '';
	while (!feof($sock)) {
		$data = fgets($sock, 1024);
		$answer .= $data;
	}
	fclose($sock);
	echo var_dump($answer);
}
else
{
	echo 'cannot load status';
}

```
and type `php status.php` in SSH. Does it crash OTS?
