### ISSUE TITLE
FMT:: Error 1.4.2 Release version, Compilation

### ISSUE THREAD

**Issue by Fanghis** [otland/forgottenserver#4534]
### Before creating an issue, please ensure:
- [x ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Download visual studio 2022, download src 1.4.2 (Release + Source Code)
2. Follow this tutorial: https://docs.otland.net/ots-guide/compiling/compiling-on-windows-vcpkg
3. Error C2079 (3) + C2338 (2)
Errors:
'fmt::v10::detail::type_is_unformattable_for<T,char>'
fmt\core.h(1577,63):'fmt::v10::detail::type_is_unformattable_for<T,char>'
fmt\core.h(1581,7): error C2338: static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt'

Small part of output:
`E:\vcpkg\installed\x64-windows\include\fmt\core.h(1577,63): error C2079: '_' uses a struct from 'fmt::v10::detail::type_is_unformattable_for<T,char> ' not defined
1> with
1> [
1> T=AccessList_t
1> ] (compiling source file ..\src\iomapserialize.cpp)
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(1806): message: see reference to instantiation of template function 'fmt::v10::detail::value<Context > fmt::v10::detail::make_arg<true,Context,AccessList_t,0>(T &)' currently compiling
1> with
1> [
1> Context=fmt::v10::format_context,
1> T=AccessList_t
1> ] (compiling source file ..\src\iomapserialize.cpp)
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(1827): message: see reference to instantiation of template function 'fmt::v10::format_arg_store<fmt::v10 ::format_context,unsigned int,AccessList_t,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>::format_arg_store<uint32_t,AccessList_t,std::string>(uint32_t &, AccessList_t &,std::string &)' being compiled (compiling source file ..\src\iomapserialize.cpp)
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(1828,3): message: see reference to instantiation of template function 'fmt::v10::format_arg_store<fmt: :v10::format_context,unsigned int,AccessList_t,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>::format_arg_store<uint32_t,AccessList_t,std::string>(uint32_t &,AccessList_t &,std::string &)' being compiled (compiling source file ..\src\iomapserialize.cpp)
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(2789): message: see reference to instantiation of template function 'fmt::v10::format_arg_store<fmt::v10 ::format_context,unsigned int,AccessList_t,std::basic_string<char,std::char_traits<char>,std::allocator<char>>> fmt::v10::make_format_args<fmt::v10::format_context,uint32_t ,AccessList_t,std::string>(uint32_t &,AccessList_t &,std::string &)' being compiled (compiling source file ..\src\iomapserialize.cpp)
1>F:\global_dix\src\iomapserialize.cpp(315): message: see the reference to the instantiation of the template function 'std::string fmt::v10::format<uint32_t,AccessList_t,std::string >(fmt::v10::basic_format_string<char,unsigned int,AccessList_t,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>,uint32_t &&,AccessList_t &&,std: :string &&)' being compiled
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(1581,7): error C2338: static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt' (compiling the source file ..\src\iomapserialize.cpp)
1>monster.cpp
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(1577,63): error C2079: '_' uses a struct of 'fmt::v10::detail::type_is_unformattable_for<T, char>' undefined
1> with
1> [
1>T=MarketAction_t
1> ] (compiling the source file ..\src\iomarket.cpp)
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(1806): message: see reference to instantiation of template function 'fmt::v10::detail::value<Context > fmt::v10::detail::make_arg<true,Context,MarketAction_t,0>(T &)' currently compiling
1> with
1> [
1> Context=fmt::v10::format_context,
1>T=MarketAction_t
1> ] (compiling the source file ..\src\iomarket.cpp)
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(1827): message: see reference to instantiation of template function 'fmt::v10::format_arg_store<fmt::v10 ::format_context,MarketAction_t,unsigned short>::format_arg_store<MarketAction_t,uint16_t>(MarketAction_t &,uint16_t &)' being compiled (compiling source file ..\src\iomarket.cpp)
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(1828,3): message: see reference to instantiation of template function 'fmt::v10::format_arg_store<fmt: :v10::format_context,MarketAction_t,unsigned short>::format_arg_store<MarketAction_t,uint16_t>(MarketAction_t &,uint16_t &)' being compiled (compiling source file ..\src\iomarket.cpp)
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(2789): message: see reference to instantiation of template function 'fmt::v10::format_arg_store<fmt::v10 ::format_context,MarketAction_t,unsigned short> fmt::v10::make_format_args<fmt::v10::format_context,MarketAction_t,uint16_t>(MarketAction_t &,uint16_t &)' being compiled (compiling source file ..\src \iomarket.cpp)
1>F:\global_dix\src\iomarket.cpp(23,280): message: see the reference to the instantiation of the template function 'std::string fmt::v10::format<MarketAction_t&,uint16_t&>(fmt:: v10::basic_format_string<char,MarketAction_t &,uint16_t &>,MarketAction_t &,uint16_t &)' currently compiling
1>E:\vcpkg\installed\x64-windows\include\fmt\core.h(1581,7): error C2338: static_assert failed: 'Cannot format an`

### Environment
Windows 11

**Comment by EPuncker** [comment]
apply the changes related to fmt from commit:
https://github.com/otland/forgottenserver/pull/4491/files

you can get more info on this thread:
https://otland.net/threads/26-08-2023-tfs-nekiro-7-72-fmt-lib-problem.286038/

**Comment by Fanghis** [comment]
> apply the changes related to fmt from commit: https://github.com/otland/forgottenserver/pull/4491/files
> 
> you can get more info on this thread: https://otland.net/threads/26-08-2023-tfs-nekiro-7-72-fmt-lib-problem.286038/


Yes i forget mention that i already try all this options.

![image](https://github.com/otland/forgottenserver/assets/104935359/96fa1a52-cbb6-4b34-9fa0-a4fde2e3c45e)

It gives more errors, as i read somewhere maybe because Fmt version has been changed, and far as i know some people doing servers are making a fork of vcpkg, to avoid problems of updates about vcpkg and code from server.
Everything from clang to the last file ( without podium , since there is not here on 1.4.2 this file ) has been aplied, tried also only milhioreBt fix, this one, changing only 2 lines, give only 3 errors when compiling, about "formattable".

**Comment by EPuncker** [comment]
bug was fixed on master so there is no point for this issue

**Comment by Fanghis** [comment]
> bug was fixed on master so there is no point for this issue

I say the same and first time i try compile master and works without problems the compilation , but is 12.87, also can be compiled with latest vcpkg updated by Microsoft.

What was the real problem there,
1.4.2 was released with a source code on x Time , done and compiled with X version of vcpkg and not with the latest vcpkg.

how can be avoid in the future:
Next releases make a fork of vcpkg working with the server , as vcpkg has been updated so it gives plenty of errors , until your found the right version with the right libraries working.

**Comment by Fanghis** [comment]
> bug was fixed on master so there is no point for this issue

I Found the correct Vcpkg version, compiled with 0 errors.
it's not needed to apply any changes on the code, checking date of release and founding a suitable version of vcpkg of this date of release it works.
By the way it will be good at some point for some people to introduce on "Set Up Vcpkg" parts with the correct vcpkg version for each branch , this i will reduce i think a lot of posts on forum, and issues about compilation.

Thanks for the help @EPuncker
