### ISSUE TITLE
Parcel Clone Bug

### ISSUE THREAD

**Issue by Mirkaanks** [otland/forgottenserver#4535]
All TFS based codes had this error, so this is aplicable to any Canary/Otbr version.
https://gifyu.com/image/S4NL6

by [marcosvf132](https://github.com/marcosvf132)

Possible fix: https://github.com/opentibiabr/canary/pull/1598

**Comment by ArturKnopik** [comment]
I can't reproduce on top of master, can someone confirm this issue?

**Comment by EPuncker** [comment]
when will people learn that canary/otbr base is OTX and not tfs?

unless someone provides real proof that this issue is present on tfs master, this issue is useless
