### ISSUE TITLE
standardize monster/npc script interface

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#4549]
What would be the downsides of moving code from monster/npc script interfaces to same interface that handles actions, talkactions, movements, etc.?

### Desired functionality
Consistency and getting rid of code duplication. Also possible fix for memory leaks caused by npc script interface if not already fixed.

### Available workarounds
N/A (existing systems do their job)

### Prior art
example: `getNpcCid()` could get removed in favour of pushing `Npc` userdata as function argument.
```
function onCreatureAppear(npc, creature)
return npcHandler():onCreatureAppear(npc, creature)
end
```

**Comment by MillhioreBT** [comment]
I don't know if they should have the same interface, but what is true is that the Npc system must be updated, it's just that it is a tedious task and no one wants to do it.
Regarding sending the Npc instead of the CID it is a good idea if the system updates, of course it does.
