### ISSUE TITLE
New random algorithm always return max number if negative

### ISSUE THREAD

**Issue by maattch** [otland/forgottenserver#4554]
The new random algorithm introduced in #4539 is making monsters always hit the max damage, this is due to it always returning the max number if it is a negative value.

Example: https://godbolt.org/z/q4Eanx4z1

**Comment by Tarliton** [comment]
It seems it can be fixed by adding:
```cpp
	if (minNumber > maxNumber) {
		std::swap(minNumber, maxNumber);
	}
```

https://godbolt.org/z/onj6Kh589

**Comment by EPuncker** [comment]
@maattch can you test #4555 please

**Comment by maattch** [comment]
Tested and now is working fine
