### ISSUE TITLE
We need to separate features into different lua files

### ISSUE THREAD

**Issue by ramon-bernardo** [otland/forgottenserver#4587]
Looking at `data/lib`. I see that when we removed code from core and sent it to lua, the harder it is to maintain `game.lua`, `player.lua`, etc.

The ideal is to have these features separated into files such as:
- lib/core/game/vip.lua
- lib/core/player/network.lua
​

**Comment by MillhioreBT** [comment]
These files are really small, I don't think file separation is necessary yet.
