### ISSUE TITLE
Client crash when another character login

### ISSUE THREAD

**Issue by ArturKnopik** [otland/forgottenserver#4594]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
login using mc on 2 or more characters
### Expected behaviour
no crash

### Actual behaviour
first player client crash

### Environment
windows/12.91.12329
### Reproduction environment
windows/12.91.12329

**Comment by omarcopires** [comment]
Check if you are using the client, map updated with the new OTB.
I've been online for hours testing and changing my server and I haven't had any crashes so far.

![image](https://github.com/otland/forgottenserver/assets/26801045/6e86c1e5-ef76-4471-af05-e2a204c82caf)

**Comment by ArturKnopik** [comment]
problem occur only when login into game

**Comment by ArturKnopik** [comment]
qgAAAAAAAAAAIQUA5ABIZXJlIHlvdSBjYW4gYWR2ZXJ0aXNlIGFsbCBraW5kcyBvZiB0aGluZ3MuIEFtb25nIG90aGVycywgeW91IGNhbiB0cmFkZSBpdGVtcywgYWR2ZXJ0aXNlIGluZ2FtZSBldmVudHMsIHNlZWsgY2hhcmFjdGVycyBmb3IgYSBxdWVzdCBvciBhIGh1bnRpbmcgZ3JvdXAsIGZpbmQgbWVtYmVycyBmb3IgeW91ciBndWlsZCBvciBsb29rIGZvciBzb21lYm9keSB0byBoZWxwIHlvdSB3aXRoIHNvbWV0aGluZy6qAAAAAAAAAAAhBQCGAEl0IGdvZXMgd2l0aG91dCBzYXlpbmcgdGhhdCBhbGwgYWR2ZXJ0aXNlbWVudHMgbXVzdCBjb25mb3JtIHRvIHRoZSBSdWxlcywgZS5nLiBpdCBpcyBpbGxlZ2FsIHRvIGFkdmVydGlzZSB0cmFkZXMgaW5jbHVkaW5nIHJlYWwgbW9uZXku

**Comment by EPuncker** [comment]
> problem occur only when login into game

please provide step by step to reproduce

**Comment by ArturKnopik** [comment]
closing, broken client, i used client from https://github.com/dudantas/tibia-client/releases
