### ISSUE TITLE
World Light

### ISSUE THREAD

**Issue by Sajgon** [otland/forgottenserver#4621]
DEFAULT_WORLD_LIGHT is missing from configKeys enums
`registerEnumIn("configKeys", ConfigManager::DEFAULT_WORLD_LIGHT)`

Also in game.h there are unused variables
- checkLight
- EVENT_LIGHTINTERVAL

**Comment by EPuncker** [comment]
@ramon-bernardo can you take a look at this please?

**Comment by ramon-bernardo** [comment]
Fix with https://github.com/otland/forgottenserver/pull/4790
