### ISSUE TITLE
Where to get a valid tibia client assets for testing?

### ISSUE THREAD

**Issue by Humberd** [otland/forgottenserver#4622]
Currently this server supports protocol 13.10. I'd like to test on a client, for example https://github.com/mehah/otclient, but it doesn't support this version explicitly. And if it would where do you event get the assets from the original 13.10 Tibia client?

**Comment by EPuncker** [comment]
sorry, we can't provide that since it is copyrighted material

but you can find it easily by using google or youtube tutorials
