### ISSUE TITLE
Inventory Slots -  Equipment Classic Slots 

### ISSUE THREAD

**Issue by Kalyster** [otland/forgottenserver#4631]
### Explanation of what you want to do that is currently impossible

Using server: https://github.com/otland/forgottenserver/tree/1.4

client: https://github.com/OTAcademy/otclientv8

following tutorial: https://otland.net/threads/help-new-inventory-slot-tfs-1-3-and-otclient.264537/

You can add Slot 12,13,14,15.

Slot 16+ is detected as Classic equipment slot (unequipable, You cannot dress this object here )

### Desired functionality

Slot 16+ with no restriction.

### Available workarounds

Remove returnvalue cannotbedressed to no error, you can equip items , but in whatever slot.

![IMG_2158](https://github.com/otland/forgottenserver/assets/104733436/1c27473e-1dc4-4cd4-86d8-9c415cdc9269)

**Comment by EPuncker** [comment]
more of a support matter than an issue with tfs itself, so I'm closing it
