### ISSUE TITLE
Info: XZ library and vcpkg

### ISSUE THREAD

**Issue by ArturKnopik** [otland/forgottenserver#4639]
XZ library is down due backdoor issue. 
It's affect vcpkg library instalation. (other way to setup project not tested) 

more info: https://arstechnica.com/security/2024/03/backdoor-found-in-widely-used-linux-utility-breaks-encrypted-ssh-connections/

**Comment by fabsantandrea** [comment]
I found this solution https://github.com/microsoft/vcpkg/issues/37839#issuecomment-2028011285

**Comment by ArturKnopik** [comment]
i know this solution, now I have to ask whether this fork has a backdoor.
The description may suggest that yes.
"Unofficial mirror of git.tukaani.org/xz.git. Updated daily."
last tag: v5.6.1 - backdoor is there

For development this workaround is enaught.
