### ISSUE TITLE
Compiling error with VCPKG

### ISSUE THREAD

**Issue by jprzimba** [otland/forgottenserver#4660]
Trying to compile latest rev with VCPKG following this tutorial
https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29

And when I go Visual Studio->Open Local Folder-> and open directory "forgottenserver" i get this error
Yes I've installed Crypto+, since I using 
.\vcpkg install --triplet x64-windows boost-iostreams boost-asio boost-system boost-variant boost-lockfree boost-locale luajit libmariadb pugixml cryptopp fmt

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Crypto++ (missing: Crypto++_INCLUDE_DIR Crypto++_LIBRARIES)		C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake	230

**Comment by jprzimba** [comment]
when I go Visual Studio->Open Local Folder-> and open directory "forgottenserver" i get this error
following compiling tutorial  and inslled packages again
error changed to
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR Crypto) (Required is at least version "3.0.0")		C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake	230		



Maybe need to update this tutorial https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29

**Comment by EvilHero90** [comment]
> Maybe need to update this tutorial https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29

The Wiki page for vcpkg was already updated, I updated it with the PR that changed from `cryptopp` to `openssl`
Open your cmd and navigate to your vcpkg directory, then run `vcpkg install openssl:x64-windows` that should install `openssl`

**Comment by jprzimba** [comment]
```
C:\vcpkg>vcpkg install openssl:x64-windows
Computing installation plan...
The following packages are already installed:
    openssl:x64-windows@3.3.0
openssl:x64-windows is already installed
Total install time: 155 us
openssl is compatible with built-in CMake targets:

  find_package(OpenSSL REQUIRED)
  target_link_libraries(main PRIVATE OpenSSL::SSL)
  target_link_libraries(main PRIVATE OpenSSL::Crypto)
  
```
  but error still there

**Comment by EvilHero90** [comment]
Maybe you have somewhere a duplicated vcpkg installation which is the one linked with vc thus throwing the error that it cannot be found, you should probably check that

**Comment by MatthewCollard** [comment]
Hi, I compiled the latest master fine, but does it support 10.98? Can't seem to get it to work with it, I changed the required version in the config, I just get stuck on an infinite loading screen.

**Comment by EPuncker** [comment]
> Hi, I compiled the latest master fine, but does it support 10.98? Can't seem to get it to work with it, I changed the required version in the config, I just get stuck on an infinite loading screen.

no, master doesn't support 10.98, if I recall correctly it is on 12.91 or something
