### ISSUE TITLE
Bug transfering gold to player who doesn't exist in bank NPC

### ISSUE THREAD

**Issue by Coldensjo** [otland/forgottenserver#4680]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Talk to the bank NPC
2. Say "hi" "transfer 500 playerwhodoesntexist"
3. Error in console

### Expected behaviour
NPC should say "This player does not exist."

### Actual behaviour
Nothing happens

### Environment
Basic tfs

### Reproduction environment
Basic tfs

**Comment by EvilHero90** [comment]
Can't reproduce this
![client_nPcOlf6jTe](https://github.com/otland/forgottenserver/assets/3682541/058d5c59-aa98-460a-9567-9a0cd5f03a06)

**Comment by Coldensjo** [comment]
Try saying "transfer 500 randomname" and not "transfer" "500" "randomname"

**Comment by EvilHero90** [comment]
Yea this gives an error, I'll include this in #4671
