### ISSUE TITLE
docker build failing

### ISSUE THREAD

**Issue by marcinpiotrsobczyk** [otland/forgottenserver#4689]
1. clone repository
2. enter root directory and run "docker build ."

### Expected behaviour
image is build

### Actual behaviour
on line: `COPY --from=build /usr/src/forgottenserver/build/tfs /bin/tfs` we get error:
`ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref a78111f0-0625-4046-aa7d-7e91806b3d83::l3wvdh4lpw3ehmmkenf2adhri: "/usr/src/forgottenserver/build/tfs": not found`

### Environment
environment is in docker on commit 848d64f72047acb697eed7232076c03a0eff33dc, today is 18 may 2024
docker version: 25.0.3 (both client and server), docker buildx version: github.com/docker/buildx v0.12.1 30feaa1 (but I think docker version doesnt matter)

**Comment by wiktorgawronski** [comment]
Same problem here.
