### ISSUE TITLE
[Feature]: Force ITEM to DECAY to specific ID with specific DURATION (min, max)

### ISSUE THREAD

**Issue by Coldensjo** [otland/forgottenserver#4727]
### By submitting this feature issue, you agree to the following.

- [X] There is no existing issue for this feature (or similar) already

### Request

Currently you cannot change what an item should decay to.
I want to be able to do something like this.

```
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	item:decayTo(10176) --decays to this id
	item:decayDuration(30,60) --30 to 60 seconds
	item:decay()
	return true
end
```

Let's say I have a specific id, a vial.
I want to transform this item into broken glass when clicked on, but I want it to transform back to the vial after a certain period, without having to make a completely new item.

It could be used to create some complex things.

**Comment by ArturKnopik** [comment]
It's can be done via items.xml, 
1) in script remove item
2) then create new one with broken glass id

<item id="123123" article="a" name="Some Broken Vial">
   <attribute key="weight" value="TONES" />
   <attribute key="decayTo" value="123122" /> << not broken vial
   <attribute key="duration" value="AGES" />
</item>

**Comment by Coldensjo** [comment]
> It's can be done via items.xml,
> 
> 1. in script remove item
> 2. then create new one with broken glass id
> 
> ```
> <item id="123123" article="a" name="Some Broken Vial">
>    <attribute key="weight" value="TONES" />
>    <attribute key="decayTo" value="123122" /> << not broken vial
>    <attribute key="duration" value="AGES" />
> </item>
> ```

Yes it's possible using items.xml but this means its fixed to 1 type of item and cannot be changed. I want to be able to turn 1 item into different items.

**Comment by ArturKnopik** [comment]
can you try use something like that? 
```LUA
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
        item:setAttribute(ITEM_ATTRIBUTE_DECAYTO, 10176)
        item:setAttribute(ITEM_ATTRIBUTE_DURATION, 30) 
	item:decay()
	return true
end
```

**Comment by Coldensjo** [comment]
![ironcore_dx_QhGjFSz5Vk](https://github.com/otland/forgottenserver/assets/102702255/78dcaebe-0947-4d8d-8ad2-a4565867fd75)
Yea, it seems to work, can close this.
