### ISSUE TITLE
[Compilation]: missing otpch.h in compilation error

### ISSUE THREAD

**Issue by ArturKnopik** [otland/forgottenserver#4731]
### By submitting this compilation problem issue, you agree to the following.

- [X] This is a compilation problem in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository
- [X] This compilation problem has not been resolved in master branch
- [X] There is no existing issue for this compilation problem already
- [X] I have tried to compile the software using the provided instructions in the Wiki page

### Server Version

1.7 (Master)

### Operation System

Windows

### Compiler

MSVC

### Buildtype

Debug

### Compiler Description

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.9.0

### Possible Pull Requests which are to blame

- [x] #4706 

### Error Message

```cpp
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2079	'std::pair<const Position,SpectatorVec>::second' uses undefined class 'SpectatorVec'	theforgottenserver	D:\programy\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\utility	466		
Error (active)	E0020	identifier "__builtin_FUNCSIG" is undefined	theforgottenserver	D:\dev\vcpkg\installed\x64-windows\include\boost\asio\detail\throw_error.hpp	39		
Error (active)	E0020	identifier "__builtin_FUNCSIG" is undefined	theforgottenserver	D:\dev\vcpkg\installed\x64-windows\include\boost\asio\detail\throw_error.hpp	48		
Error	C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "otpch.h"' to your source?	theforgottenserver	D:\dev\forgottenserver_AK\src\http\cacheinfo.cpp	22		
Error	C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "otpch.h"' to your source?	theforgottenserver	D:\dev\forgottenserver_AK\src\http\error.cpp	15		
Error	C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "otpch.h"' to your source?	theforgottenserver	D:\dev\forgottenserver_AK\src\http\http.cpp	52		
Error	C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "otpch.h"' to your source?	theforgottenserver	D:\dev\forgottenserver_AK\src\http\listener.cpp	62		
Error	C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "otpch.h"' to your source?	theforgottenserver	D:\dev\forgottenserver_AK\src\http\login.cpp	169		
Error	C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "otpch.h"' to your source?	theforgottenserver	D:\dev\forgottenserver_AK\src\http\router.cpp	59		
Error	C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "otpch.h"' to your source?	theforgottenserver	D:\dev\forgottenserver_AK\src\http\session.cpp	102		
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2079	'std::pair<const Position,SpectatorVec>::second' uses undefined class 'SpectatorVec'	theforgottenserver	D:\programy\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\utility	466
```

**Comment by reyaleman** [comment]
add `#include "spectators.h"` to map.h file, cheers

**Comment by ArturKnopik** [comment]
> add `#include "spectators.h"` to map.h file, cheers

is there

**Comment by EvilHero90** [comment]
I can reproduce this on `Debug` build, `Release` is not effected by this

**Comment by EvilHero90** [comment]
I have a workaround solution since VS doesn't like subdirectories
### 1) map.h
- place at other includes `#include "spectators.h"`
### 2) error.cpp / http.cpp / listener.cpp / router.cpp / session.cpp
- add `#include "otpch.h"` at top
### 3) cacheinfo.cpp
- remove `../` infront of `otpch.h` & `database.h`
### 4) login.cpp
- remove `../` infront of `otpch.h` & `base64.h` & `game.h`
### 5) Add the src folder as an include directory
- **`Project-> Properties-> Configuration Properties-> C/C++-> General-> Additional Include Directories`**
- You have to include the full path to your forgottenserver/src folder in there

This will let you compile the Debug Build just fine

**Comment by EvilHero90** [comment]
@xmish did you add some kind of macro because including `..\src\` didn't work for me

**Comment by EvilHero90** [comment]
I'll cover your patch in the Wiki page, thank you for providing it
