### ISSUE TITLE
[Bug]: Cant login to game world - "Malformed session key."

### ISSUE THREAD

**Issue by ArturKnopik** [otland/forgottenserver#4739]
### By submitting this bug issue, you agree to the following.

- [X] This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository
- [X] This bug has not been resolved in master branch
- [X] There is no existing issue for this bug already

### Does this bug crash tfs?

no

### Server Version

1.5 (Development)

### Operation System

Windows

### Bug description

Cant login to game world, returns 

### Possible Pull Requests which are to blame

N/A

### Steps to reproduce

0. Use Windows 10/11
1. Setup ENV
2. Run client 13.1
3. Try login

### Actual Behavior

![Zrzut ekranu 2024-06-06 152955](https://github.com/otland/forgottenserver/assets/17506599/fddc254a-3ee5-4b9c-b146-214233d26610)
Character not enter to game world.

### Expected Behavior

Character enter to game world.

### Additional Notes
Release build (debug is not working)

![Zrzut ekranu 2024-06-06 152352](https://github.com/otland/forgottenserver/assets/17506599/d6ec45a0-6b42-4dc0-a5cc-2eeb97dd7839)
![Zrzut ekranu 2024-06-06 152725](https://github.com/otland/forgottenserver/assets/17506599/0e3a2b47-058c-429f-bcab-43441446bdf6)
Client:
![Zrzut ekranu 2024-06-06 153013](https://github.com/otland/forgottenserver/assets/17506599/c6e99e48-153a-45ea-8692-a23ba5cbd4ad)

**Comment by ranisalt** [comment]
You are using a third-party login server that needs to be updated to store session tokens in the `sessions` table.

You can drop that now and use the embedded login server by [configuring it in config.lua](https://github.com/otland/forgottenserver/blob/c677f0383d345b3cab6e93385d50761c7bed67b4/config.lua.dist#L28-L29)

**Comment by ArturKnopik** [comment]
TY, i will check it!

**Comment by ArturKnopik** [comment]
@update, tested on latest MyAcc and i got the same issue..

**Comment by ranisalt** [comment]
MyAAC needs to store in the database and Base64-encode the key before sending to the client, around here: https://github.com/slawkens/myaac/blob/81b6652738a7b04be3980cbf55443a6fbe437b34/login.php#L226-L243

**Comment by ArturKnopik** [comment]
To be honest, i used znote acc for a while and it's work without issue until openssl changes...
i tested on another(MyAcc release from last last week) accmakert to check if this is my fault.

**Comment by ArturKnopik** [comment]
I found source of problems
1) invalid setup for port (in my case should be 80 instead 8080 for http server)
2) probably bronek schema.sql (session table)  

I want to add information about my env, im using xampp to setup DB
Probably xampp reinterpretate invalid query to something valid(if can)
in this case session table is broken (image from mysql execution)
![image](https://github.com/otland/forgottenserver/assets/17506599/51b76687-a272-45bb-9540-26c76c770ad0)
xampp probably is trying to fix this issue by set default value for expired_at as 0000-00-00 00:00:00 but tfs is expecting this value as null, when i manualy changed this record to set default value as null it's start working

**Comment by ranisalt** [comment]
What version of XAMPP are you using?

**Comment by ArturKnopik** [comment]
![image](https://github.com/otland/forgottenserver/assets/17506599/efb1ad6e-eaae-4442-9b53-6c39db6926b2)
I assume this may be the source of the problem
