### ISSUE TITLE
[Bug]: Can't create multiple different NPC with the same display name

### ISSUE THREAD

**Issue by ArturKnopik** [otland/forgottenserver#4759]
### By submitting this bug issue, you agree to the following.

- [X] This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository
- [X] This bug has not been resolved in master branch
- [X] There is no existing issue for this bug already

### Does this bug crash tfs?

no

### Server Version

1.7 (Master)

### Operation System

all (listed below)

### Bug description

Can't create multiple different NPC with the same display name

### Possible Pull Requests which are to blame

- [x] #4671
- [x] #4724
- [x] #4741
- [x] #4747

### Steps to reproduce

1. Copy `Riona.xml` -> `Riona_Two.xml`
2. Add Riona Two to spawns (`/s` not working if NPC isn't on the map)
3. Start server
4. `/goto Riona_Two`

Additiona:
`/s Riona_Two` not workin

![Zrzut ekranu 2024-06-23 211139](https://github.com/otland/forgottenserver/assets/17506599/1711630b-3865-449a-a5a5-ac9dced7c1a3)

### Actual Behavior

`/goto Riona_Two` works, NPC have invalid name(name is taken from filename)
`/s Riona_Two` not working

### Expected Behavior

`/goto Riona_Two` should not works, npc Riona_Two.xml NPC should have Riona name(taken from xml file from `name` field)
`/s Riona_Two` should create npc from Riona_Two.xml file named Riona

**Comment by ArturKnopik** [comment]
for `/s` fix looks easy to be done
```LUA
function onSay(player, words, param)
	if not player:getGroup():getAccess() then
		return true
	end

	if player:getAccountType() < ACCOUNT_TYPE_GOD then
		return false
	end

	local position = player:getPosition()
	local npc = NpcType(param)  --  <<< change to Game.createNpc(param, position)
	if npc then
		Game.createNpc(param, position) -- <<< to remove
		position:sendMagicEffect(CONST_ME_MAGIC_RED)
	else
		player:sendCancelMessage("There is not enough room.")
		position:sendMagicEffect(CONST_ME_POFF)
	end
	return false
end

```

**Comment by EvilHero90** [comment]
I don't really get the sense behind this, as you can spawn the same npc just fine with `/s` or adding them several times in the mapeditor why would you want to make another xml file for the same npc?
Feel free to open a pr for the changes of the `/s` command, as I resolved the crashes with spawning npcs / reloading this can be changed back now without any problems

**Comment by ArturKnopik** [comment]
example:
i want to have 2 npc with displayed name Traveler
Traveler1.xml (travel1.lua) that teleport player to Island 
Traveler2.xml (travel2.lua) that teleport player to main land
What was possible before changes is both npc has the same display name. For now file name is used and described behavior is impossible

--------

About /s - npc must not be loaded during startup(not present in spawn.xml)

**Comment by Coldensjo** [comment]
> I don't really get the sense behind this, as you can spawn the same npc just fine with `/s` or adding them several times in the mapeditor why would you want to make another xml file for the same npc? I'll include the changes proposed to `/s` in revnpcsys version 1.4

What if you want the same NPC appear in multiple places with different outfits or something like that. Idk,

**Comment by ArturKnopik** [comment]
Fixed, closing.
