### ISSUE TITLE
[Feature]: GameHealthInfoBackground from OTCV8 Bug

### ISSUE THREAD

**Issue by luckez** [otland/forgottenserver#4771]
### By submitting this feature issue, you agree to the following.

- [X] There is no existing issue for this feature (or similar) already

### Request

This feature, when active, gives many protocol errors, would there be a solution to resolve the server part?

erros:

ERROR: ProtocolGame parse message exception (48106 bytes, 45467 unread, last opcode is 0x4b (75), prev opcode is 0x0f (15)): unable to create item with invalid id 36612
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1098)
ERROR: ProtocolGame parse message exception (19594 bytes, 14116 unread, last opcode is 0x4b (75), prev opcode is 0x42 (66)): unable to create item with invalid id 36612
Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 1098)
ERROR: no thing at pos:1108 397 7, stackpos:2
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: no creature found to move
at:
    [C++]: ?parseCreatureMove@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z

**Comment by EPuncker** [comment]
surely there should be a server side fix, but if I recall correctly, the code was not released 100%, and also this is more of a support forum issue than a github issue

**Comment by luckez** [comment]
Can you give me some help? to make her catch it?
