### ISSUE TITLE
[Feature]: Move XTEA encryption from Dispatcher thread to Network thread

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#4779]
### By submitting this feature issue, you agree to the following.

- [X] There is no existing issue for this feature (or similar) already

### Request

**What do you want to achieve?**
Reduce Dispatcher thread CPU usage.

I've tested it on TFS 1.4 with some commits from 1.6 with `CMAKE_BUILD_TYPE=Release`.

All players online were 30 SQM away from each other, making 2 steps per second with 10-20 monsters on screen of each player.
CPU usage by `sendAll(bufferedProtocols);` before changes from my commit:
```
100 online: 4.5-5.2%
200 online: 7.7-8.6%
300 online: 9.5-10.8%
```
After:
```
100 online: 0.3%
200 online: 0.44%
300 online: 0.52%-0.94%
```

Most OTS engines report `sendAll(bufferedProtocols)` in OTS Stats under name `functor`.

### Possible Solutions

https://github.com/gesior/forgottenserver-gesior/commit/ba6df5e7ab5f97cc78d86291b44e2a2a940e10eb

**Comment by Wirless** [comment]
amazing

**Comment by ranisalt** [comment]
It's not really reducing CPU usage, just moving to another thread. But it's a good idea to free up resources in the dispatcher thread, and the networking code could benefit from multiple threads to receive/send packets.

**Comment by gesior** [comment]
I got OTS Stats log from 1200+ online Evo server. It uses old Kondra - OTCv8 author - code to move XTEA to new thread (extra thread, not ASIO thread), so it's reported as "thread ID 2" in OTS Stats (30 seconds log interval):
```
Thread: 2 Cpu usage: 25.8628% Idle: 74.9945% Other: -0.857337% Players online: 1314
 Time (ms)     Calls     Rel usage %    Real usage % Description
      7758    901777      100.00000%       25.86282% std::bind(&Connection::send, shared_from_this(), msg)
```
Dispatcher thread usage:
```
Thread: 1 Cpu usage: 101.097% Idle: 0.397533% Other: -1.49486% Players online: 1314
(...)
       585      1250        1.93757%        1.95175% functor
```

With official TFS code it would be 27% CPU just to XTEA encrypt/adler32 sign packets!
