### ISSUE TITLE
[Bug]: min damage formula is wrong.

### ISSUE THREAD

**Issue by Wirless** [otland/forgottenserver#4780]
### By submitting this bug issue, you agree to the following.

- [X] This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository
- [X] This bug has not been resolved in master branch
- [X] There is no existing issue for this bug already

### Does this bug crash tfs?

no

### Server Version

1.7 (Master), 1.6 (Release), 1.5 (Development), 1.4.x (Release)

### Operation System

all (listed below)

### Bug description

The min damage is actually 0 when generating damage for weapons and fist

### Steps to reproduce

1.attack monster
2.wrong formula
3.deal wrong damage
**Code to reproduce the issue:**
```lua
-- paste your script here
```

### Actual Behavior

The minimum damage generated for formulas is 0

### Expected Behavior

The MINIMUM damage should be player->getLevel()/5
weapons.cpp
I DO NOT KNOW HOW TO MAKE PULL REQUESTS GITHUB IS THE WORST APP EVER. 
Weapon::useFist
damage.primary.value = -normal_random(player->getLevel() / 5, maxDamage);

WeaponMelee::getWeaponDamage
return -normal_random(player->getLevel() / 5, maxValue);

WeaponDistance::getWeaponDamage

return -normal_random(player->getLevel() / 5, maxValue);

**Comment by EPuncker** [comment]
can you share your source for damage please

**Comment by Wirless** [comment]
Colin Fletcher we are re-creating a rookgaard and the damage was not right so we adjusted it with those changes and he said that this is closer to real tibia.
there is reference to your damage inside of player information on 200 level its 40 so its 200/5 the mindamage should never be 0 though like it is here for many years.

**Comment by Wirless** [comment]
idk what you call that window on the cip client player info? there it shows your damage and other stuff. the damage was extremely bad when it was at 0 the medium was just not hitting the right spot.

**Comment by EPuncker** [comment]
> idk what you call that window on the cip client player info? there it shows your damage and other stuff. the damage was extremely bad when it was at 0 the medium was just not hitting the right spot.

it displays 0 because that window is not fully implemented in tfs

**Comment by Wirless** [comment]
im not talking about the window im talking about the damage level 200 player is dealing with appropriate skills etc.

**Comment by joseluis2g** [comment]
yeah very lazy, you might fix it, thats very sad.

**Comment by peteralto** [comment]
> im not talking about the window im talking about the damage level 200 player is dealing with appropriate skills etc. some lazy tfs developer decided minimum damage is 0 it is not in tibia if you are replicating engine it would be good to know someone who actually plays the game instead of assuming everything maybe then tfs would be something better.

maybe you can try Canary with expert developers

**Comment by Wirless** [comment]
havent checked it but its getmaxdamageformula is different than tfs.

**Comment by Wirless** [comment]
of course this lazy **** closed this so more people PAY for this feature because DAMAGE is not right. typical TFS Developer money grab behaviour same as canary you are all lost cause.
