### ISSUE TITLE
[Bug]: Compiling with VCPKG error in Windows and Open a Local Folder

### ISSUE THREAD

**Issue by jprzimba** [otland/forgottenserver#4822]
### By submitting this bug issue, you agree to the following.

- [X] This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository
- [X] This bug has not been resolved in master branch
- [X] There is no existing issue for this bug already

### Does this bug crash tfs?

no

### Server Version

1.7 (Master)

### Operation System

Windows

### OS Description

Windows 10 x64 22H2

### Bug description

Compiling when using Open Local Folder in Visual Studio

### Possible Pull Requests which are to blame

- [ ] #
- [ ] #

### Steps to reproduce

1. Follow wiki tutorial https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29
2. Open Visual Studio. On the Visual Studio Start Page, click Open a Local Folder.
3. You will encounter this error in the Actual Behavior section.
4. If you install the libraries following the tutorial, it works well. However, if you follow the steps above, you will encounter an error.

### Actual Behavior

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR Crypto) (Required is at least version "3.0.0")		C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake	230	

### Expected Behavior

Expected to run and configure cmake to build project

**Comment by gesior** [comment]
**NOT A BUG**

> 2\. Open Visual Studio. On the Visual Studio Start Page, click Open a Local Folder.

With `Open a Local Folder` you can open any folder in Windows to view/modify it's files in VS.

If you open TFS directory, it will try to load CMake project with 'Default' profile. 'Default' profile tries to use system libraries, not vcpkg. It would compile on Linux (without vcpkg), but it won't compile on Windows, unless you collect all required C++ libraries yourself and configure VS to read these libraries directories.

**TFS `Windows (vcpkg)` tutorial says in 5th point:**
```
Open vc17/theforgottenserver.vcxproj. This should launch Visual Studio.
```
**and that's what you should do**. Open `vcxproj` or `sln` file from `vc17` folder. It contains compilation project that will work in VS on PC with vcpkg.

**Comment by nekiro** [comment]
As above, seems to be a bug due to incorrectly following wiki page.
