### ISSUE TITLE
[Bug]: Broken onStepOut 

### ISSUE THREAD

**Issue by ArturKnopik** [otland/forgottenserver#4857]
### By submitting this bug issue, you agree to the following.

- [X] This is a bug in the software that resides in this repository, and not a support matter (use https://otland.net/forums/support.16/ for support)
- [X] This issue is reproducible without changes to the C++ code in this repository
- [X] This bug has not been resolved in master branch
- [X] There is no existing issue for this bug already

### Does this bug crash tfs?

no

### Server Version

1.7 (Master)

### Operation System

all (listed below)

### Bug description

onStepOut(creature, item, position, fromPosition)  - position, fromPosition are always the same

### Possible Pull Requests which are to blame

N/A

### Steps to reproduce

changes drowning.lua to print positions for onStepIn and onStepOut
```Lua
local condition = Condition(CONDITION_DROWN)
condition:setParameter(CONDITION_PARAM_PERIODICDAMAGE, -20)
condition:setParameter(CONDITION_PARAM_TICKS, -1)
condition:setParameter(CONDITION_PARAM_TICKINTERVAL, 2000)

function onStepIn(creature, item, position, fromPosition)
	print("onStepIn position: ", position)
	print("onStepIn fromPosition: ", fromPosition)
	if creature:isPlayer() then
		creature:addCondition(condition)
		creature:addAchievementProgress("Deep Sea Diver", 1000000)
	end
	return true
end

function onStepOut(creature, item, position, fromPosition)
	print("onStepOut position: ", position)
	print("onStepOut fromPosition: ", fromPosition)
	if creature:isPlayer() then
		creature:removeCondition(CONDITION_DROWN)
	end
	return true
end

```
goto position 374, 616, 13
start walking to left and right
check printed positions

### Actual Behavior

onStepOut print for position and fromPosition the same values
```
onStepOut position:	Position(374, 616, 13)
onStepOut fromPosition:	Position(374, 616, 13)
onStepIn position:	Position(375, 616, 13)
onStepIn fromPosition:	Position(374, 616, 13)
```

### Expected Behavior

onStepOut should print for position and fromPosition different values

### Backtrace

```cpp
N/A
```

**Comment by nekiro** [comment]
I think related #2586

**Comment by ArturKnopik** [comment]
yes, is the same issue, closing this one.
