### ISSUE TITLE
Multiplier float support

### ISSUE THREAD

**Issue by Luckey1729** [otland/forgottenserver#605]
config.lua and stages.xml should support float values.
fe. < stage minlevel="200" multiplier="0.5" />
##

**Comment by Luckey1729** [comment]
#975 was closed, but #605 was not.
Yes, `Player:onGainExperience` can be used to emulate the desired effect; it seems like it's more of a "workaround" rather than a proper implementation. If it's intended to be this way, this issue should be closed as well.

**Comment by andersonfaaria** [comment]
#975 should be merged not closed, this isn't about exp but rather using floats as possible options in config.lua. Also this issue should be closed as well...

**Comment by EPuncker** [comment]
> #975 should be merged not closed, this isn't about exp but rather using floats as possible options in config.lua. Also this issue should be closed as well...

#2750 isn't this one the same?

**Comment by ranisalt** [comment]
You can now use stages with decimal multipliers in config.lua :)
