### ISSUE TITLE
Linux signals.

### ISSUE THREAD

**Issue by dominique120** [otland/forgottenserver#770]
@marksamman I know I mentioned this before and I said I would figure it out or whatever but could you please add support for them? Just basic ones like reload all and save and quit.

I tried doing it myself but I have not been able  to do it successfully(I'm not a programmer).

Just the "Save & Quit" signal would be a huge blessing.

Thanks!
##

**Comment by ranisalt** [comment]
What signals could be implemented? I'm thinking on INT/TERM to clean and stop the server, and STOP/CONT to close the server and open, respectively. This would make the server behave easily as a daemon.

**Comment by djarek** [comment]
I believe that HUP is used by some init systems (at least by systemd) to signal a request for a reload of config files.

**Comment by ranisalt** [comment]
Nice, a good replacement for issuing /reload ingame too.
