### ISSUE TITLE
Npc cap bug

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#862]
Hello,

well there is a issue, if a item has no weight and you have 0 weight, the npc dont sell that item to you. Even tho the item has no weight.

Also, if someone could give me a fast answer, how can i ignore cap in npcs 4ever. Since, there is param ignoreCap. But seems not to work.

**Comment by marksamman** [comment]
I can't reproduce this; if you mean that the item is disabled in the shop list in the client, that's client-sided. The protocol also doesn't provide any option to tell the client to use the ignore cap option.
