### ISSUE TITLE
MoveCreature debug

### ISSUE THREAD

**Issue by Luckey1729** [otland/forgottenserver#885]
Truthfully I have no more information about how to reproduce this. I just checked my client_assertions.txt and found it rife with errors similar to this one:

----- 02/07/2014 12:27:04 - () -----
Debug Assertion 10.41 Communication.cpp 2563
Tue Jan 01 00:09:57 2002
Graphic Engine: DirectX5 (0)
Operating System: Windows XP Professional in ESP
Processor: Dual Core AMD Athlon 64 X2 400
Video Card: NVIDIA GeForce 8400GS
Last Packet Types: 109 109 109 109 109 106 109 109 109 109
Last Packet: 109 206 000 149 001 007 001 206 000 150 001 007 106 212 000 143
Player Position: [205,405,7]
Player Name:
Player Action: 048 046 048 046 048 046 048 058 055 049 055 050
Player.cpp 343: exception occurred, reason:
Network.cpp 844: exception occurred, reason:
Control.cpp 1481: exception occurred (Type = 109) (MainWindow = 26750072), reason:
Communication.cpp 2682: exception occurred, reason:
Communication.cpp 2570: exception occurred, reason:
Communication.cpp 2563: MoveCreature has been received for a coordinate where there is no creature anymore [bug0000017](7991, 0), reason:
 StartX: 16 StartY: 3 StartZ: 0
 RNum: 2
 DestX: 16 DestY: 2 DestZ: 0
 dx: 0 dy: -1 dz: 0
 abs_sx: 213 abs_sy: 402 abs_sz: 7
 abs_zx: 213 abs_zy: 401 abs_zz: 7
 Start Cylinder (1):  (409,0) (17480,0) (7991,0)
 Start Cylinder (2):  (409,0) (17480,0) (7991,0)(-)(-)(-)(-)(-)(-)(-)
 Destination Cylinder (1):  (409,0) (17471,0) (3372,0)
 Destination Cylinder (2):  (409,0) (17471,0) (3372,0)(-)(-)(-)(-)(-)(-)(-)
Comment:

**Comment by AndreFaramir** [comment]
Im having this problem also, using tfs 1.0 commit 6292f5f8eee1c4366759b72a395cab13b9f83a20

the way I find to reproduce this was 
*creating an arena with a lot of monsters inside (200~), they move quickly ...
*keep a player around this monsters making them walks randomly trying to find target to the player, but we only want they to keep moving 
*I have to simulate latency+packet loss on my internet to reproduce this, for this I use the command "tc" on linux, im my case (tc qdisc add dev eth0 root netem delay 1000ms loss 40%)
*apply the lag for 20secconds and them remove...

it appears that when the client have a lot of packet loss the server hold all the packets to deliver once it get online, but some packets are lost making the tcp stack order a mess, this way is possible the client to receive a packet of creature moving where there is no creature anymore, resulting in this debug

I tried a lot of ways to fix this network issue on server side like tcp tunning and changing the congestion control but none work, always I reproduce the same way i got the same debug !!
