### ISSUE TITLE
New function (configManager.setString)

### ISSUE THREAD

**Issue by WibbenZ** [otland/forgottenserver#896]
Well I just tought about it, why not add a function to change the string in config.lua.
Ex.
configManager.setString(motd, "Today is " os.date("%A"))

This would make it posible to add motds like cipsoft has, "Have a nice weekend" etc. But also things like if you are planning a longer server save its posible to do that without having to change it the day before that server save.
##

**Comment by esfomeado** [comment]
Why not move the MOTD to the database?

**Comment by ranisalt** [comment]
Because it is not data

**Comment by ramon-bernardo** [comment]
Server motd no longer exists, this can be **closed**.
