### ISSUE TITLE
Monster summon bug

### ISSUE THREAD

**Issue by Nu77** [otland/forgottenserver#928]
I don't know if this is a bug but if we only run away with master and summon lost target on return to summon radius no one move again.

PS: Tested with slime

**Comment by marksamman** [comment]
Can anyone confirm that the summon should be teleported to the master?

**Comment by ninjalulz** [comment]
It shouldn't be teleported to the master but it should disappear if you are:
* two floors above or beneath it
* 30+(?) SQM's away from it

Also the summon shouldn't become idle if the master is out of range.

**Comment by marksamman** [comment]
When you say that it shouldn't become idle, what do you mean that the summon should do? Take random steps? Only use defense abilities (e.g. heal)?

**Comment by ninjalulz** [comment]
Sorry, forgot to mention that. They take random steps, and use their defense abilities (e.g heal).
