### ISSUE TITLE
Server crashing after 5~20 minutes

### ISSUE THREAD

**Issue by edumntg** [otland/forgottenserver#949]
After 5~20 minutes, the server is crashing.

I've opened it through Visual Studio to check errors and this is what i got:

IN CONSOLE:

PANIC: unprotected error in call to Lua API (not enough memory)

IN VISUAL STUDIO:

>   theforgottenserver.exe!LuaScriptInterface::protectedCall(lua_State \* L, int nargs, int nresults) Línea 380 C++
>     theforgottenserver.exe!LuaScriptInterface::callFunction(int params) Línea 609  C++
>     theforgottenserver.exe!Npc::onThink(unsigned int interval) Línea 325   C++
>     theforgottenserver.exe!Game::checkCreatures(unsigned __int64 index) Línea 3731 C++
>     theforgottenserver.exe!Dispatcher::dispatcherThread() Línea 70 C++

I'm running it on x64 with a realmap datapack.

**Comment by ss1182772** [comment]
if u used real map without real-map.spwan he worked easy and if u used a real map 860 working :) 
porlbem with a ram u need big ram like 8-12gp i think
