### ISSUE TITLE
Config Rate Multiplier

### ISSUE THREAD

**Issue by Codinablack** [otland/forgottenserver#988]
When trying to use 0.5, or 1/2, or 1*0.5, or even just .5 as a rate for skill, then it doesn't give any skill tries at all.... I know I can just change all the multiplier's in the vocations.xml, but that's besides the point the config.lua SHOULD be able to read all of those values... I personally have 47 vocations in my vocations.xml, and to have to adjust all those skills would be a nightmare, when quite simply I should be able to just enter 0.5 and be done with it, or 0.8 or 0.75 if I wanted....

**Comment by iskabin** [comment]
My vocations.xml' multipliers don't work, I mean, when I change them it has no effect in the game, your's work??
