### ISSUE TITLE
Follow Fight Mode

### ISSUE THREAD

**Issue by Codinablack** [otland/forgottenserver#990]
When using follow target as the fight mode, and using arrow keys to try to go another direction, sometimes the players sprite will move to where the arrow key should put him, but will actually stay stuck in another spot next to the monster, the puffs and other affects are as if player is still next to monster, monster behaves as if player is still there, but again on your screen you see yourself one square over, if you try to move you cannot until you either click or use mouse to put yourself where the creature is fighting you at....

**Comment by marksamman** [comment]
Is anyone else able to reproduce this? I've tried to without any success.

**Comment by ninjalulz** [comment]
I'm not able to reproduce this either.
